### ISSUE TITLE
[Bug]: [Automatically hide Toolbar] is too sensitive when unhiding

### ISSUE THREAD

**Issue by sdsucks** [Floorp-Projects/Floorp#1001]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

[Automatically hide Toolbar] works too sensitively when i move my mouse towards the top of the screen to unhide the toolbar.
because of this sometimes i can't click on some menu items or buttons of some sites.
so i disabled the option and tried a css with the same feature i found on [github.com](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/autohide_toolbox.css) and this css unhides the toolbar when i move the mouse to the very top of the screen.

my userChrome.css is(without the external css):
#TabsToolbar {display: none;}
#titlebar {margin-bottom: 0px !important;}
#sidebar-header {display: none;}
#titlebar[id] {display: none;}

### Reproduction Steps

Settings - Design - Firefox Photon・Lepton UI - Lepton Settings - Automatically hide Toolbar

### Expected Behavior

toolbar should appear when i move my mouse to the very top of the screen

### Actual Behavior

toolbar appears when i move my mouse to about 40 pixels below the very top of the screen

### Screenshots

floorp internal
![floorp internal1](https://github.com/Floorp-Projects/Floorp/assets/6938353/67d75c40-049b-4fb9-ad5f-74013c4eb77c)

external css in userChrome.css
![external css1](https://github.com/Floorp-Projects/Floorp/assets/6938353/777e899b-8675-4e66-b696-98bca1c06e24)

### Browser Version

daylight 20240311090805/stable 20240226112003

### Operating System

win10

**Comment by surapunoyousei** [comment]
This is a specification. It is not a bug.
