### ISSUE TITLE
[Bug]: YouTube is hanging on Firefox/Floorp if YouTube uses VP9 codec.

### ISSUE THREAD

**Issue by surapunoyousei** [Floorp-Projects/Floorp#1004]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

YouTube is hanging on Firefox/Floorp if YouTube uses VP9 codec.

### Reproduction Steps

Watch a live stream

### Expected Behavior

Smooth watching is expected.

### Actual Behavior

Video is hanging

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/9fce430d-9a89-4714-99ff-ee71cc7819cf)

### Browser Version

11.10.5

### Operating System

Windows 11

### Additional Context

Nothing

**Comment by ioc2e3** [comment]
very worried ...

Is this a YouTube problem?

Or do browsers based on Firefox have this problem?

.

**Comment by surapunoyousei** [comment]
Every Firefox based browser have this issue

**Comment by Mennaruuk** [comment]
It depends. Firefox on Mac defaults to H264. Firefox on Linux defaults to VP9. On Windows, it defaults to whatever one's machine can run most efficiently.
