### ISSUE TITLE
[Bug]: Preferences not automatically applying from the get-go

### ISSUE THREAD

**Issue by idarianza** [Floorp-Projects/Floorp#1005]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I have settings like 'Open a new tab' button to be on the side of tabs (using horizontal tabs), but it isn't applying when I reopen the browser. I need to keep reopening settings for the preferences for that specific thing to reapply. I am using Lepton.

### Reproduction Steps

1. Open browser
2. Change preferences
3. Close browser
4. Open browser.

### Expected Behavior

I close browser then I open browser with preferences being applied automatically without having to reopen settings.

### Actual Behavior

I closed browser then I reopened it and the preferences for it isn't applying without 'about:preferences#general' being opened.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/163430688/04257620-138e-45f5-8781-e9a097c6d49a)
![image](https://github.com/Floorp-Projects/Floorp/assets/163430688/815365cb-e814-48fd-a234-28c4123ed360)

### Browser Version

11.10.5 (64-bit)

### Operating System

Windows 10

### Additional Context

Another thing that I noticed is that if I open a new window it would apply only on the new window, but it isn't applying on the first window opened unless I open settings.

**Comment by surapunoyousei** [comment]
You should provide a video. It is chaos

**Comment by idarianza** [comment]
> You should provide a video. It is complex

Not sure if this shows it. 

https://github.com/Floorp-Projects/Floorp/assets/163430688/ad29773f-3c3f-4cc5-bed5-c3204453ded0

**Comment by idarianza** [comment]
Here is a better video properly showing what I described. 

https://github.com/Floorp-Projects/Floorp/assets/163430688/242bf7a0-5d16-4b04-94c3-37a69a2497e8

**Comment by surapunoyousei** [comment]
What's? Not expected....

So... Did you try to use new profile?

**Comment by idarianza** [comment]
> What's? Not expected....
> 
> So... Did you try to use new profile?

I have. I tried everything in the check list before I sent as bug report.

**Comment by surapunoyousei** [comment]
I looked back at the video and it seems your Windows is special.

Are you changing any other settings?

**Comment by surapunoyousei** [comment]
& try this userChrome.css

```CSS
#customizableui-special-spring1[id], #customizableui-special-spring2[id],, #wrapper-customizableui-special-spring1[id],, #wrapper-customizableui-special-spring2[id], {
  display: inhert !important;
}
```

**Comment by idarianza** [comment]
> I looked back at the video and it seems your Windows is special.
> 
> Are you changing any other settings?

No it's just regular windows. It's just on 2nd screen that's why it looked different.


> & try this userChrome.css
> 
> ```css
> #customizableui-special-spring1[id], #customizableui-special-spring2[id], #wrapper-customizableui-special-spring1[id], #wrapper-customizableui-special-spring2[id] {
>     display: inherit !important;
> }
> ```

How do I try it? Not sure where to put

**Comment by surapunoyousei** [comment]
https://www.userchrome.org/how-create-userchrome-css.html

Paste my posted css
