### ISSUE TITLE
[Bug]: Home Assistant Not Rendering Dashboard Correctly

### ISSUE THREAD

**Issue by AdamWorley** [Floorp-Projects/Floorp#1006]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When viewing the dashboard screens for home assistant the screens do not render correctly on first load, changing to a different panel and back again usually 'fixes' it. 

Adjusting the screen width also almost fixes it.

### Reproduction Steps

1. Login to the latest version of a home assistant instance
2. View any of the dashboards

### Expected Behavior

The dashboards should render correctly - by default the screen renders 3 columns that flow to try and evenly distribute all of the dashboard elements

### Actual Behavior

The middle column usually renders ok but any elements that spill over all show in the right column bunched up and rendered incorrectly, usually just the text content.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/28906234/73e581a6-69ca-4135-8003-e1e5efc13774)

### Browser Version

11.10.5 (64-bit)

### Operating System

Windows

### Additional Context

It appears to be related to the following bug(s):
- Home Assistant: https://github.com/home-assistant/frontend/issues/17182
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=418039#c62

I have confirmed that the issue isn't present for Firefox 115.8.0esr (64-bit)

I'd be happy to help with testing but it should also be possible to run a docker instance for testing locally.

**Comment by CutterKnife** [comment]
Is this https://github.com/Floorp-Projects/Floorp/issues/752 the same thing?
