### ISSUE TITLE
[Bug]: Fullscreen with vertical tabs leaves tab divider on edge of screen

### ISSUE THREAD

**Issue by almighty-loaf** [Floorp-Projects/Floorp#1009]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When vertical tabs are enabled, activating fullscreen mode via F11 or other method (e.g. maximizing a video) hides the window chrome, including the tabs, but the divider between the tab area and web page area remains on screen. The divider lies on the same side of the screen as the tab section.

In fullscreen, hovering over the divider offers the resize cursor, but it cannot actually be interacted with.

### Reproduction Steps

1. Open the Floorp Settings screen
2. Navigate to the _Design_ section
3. Under the _Tab Bar Style_ header, select _Vertical Tab Bar (experimental)_
4. Restart Floorp if prompted
5. On this page, or any other page, use F11 to switch to fullscreen mode
6. A vertical line will appear on the left or right side of the screen

### Expected Behavior

In fullscreen mode, the tab bar divider should be hidden

### Actual Behavior

In fullscreen mode, the tab bar divider is shown

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/418354/1f327d82-97b4-4c94-87ea-e0860ffe2dca)

This image captures the top left corner of my screen from the GitHub bug submission page. (The line is gray in this case because I am using a dark theme in my GNOME shell.)

### Browser Version

11.10.5_2024-02-26

### Operating System

Pop!_OS 22.04 LTS using GNOME Cosmic

### Additional Context

The effect here is particularly distracting when using a light theme in the OS shell or from the Firefox theme repository, since there will be a band of bright light next to potentially darker content. 

Frequency: every time fullscreen is used
Impact: distracting and/or a nuisance, but does not otherwise impede normal browser functionality

**Comment by surapunoyousei** [comment]
This is a compatibility effect

**Comment by almighty-loaf** [comment]
@surapunoyousei Hi thanks for triaging this one. Could you elaborate on the nature of the compatibility here? Just curious why this would never be fixed.

(I can also reproduce this in KDE Plasma 5.27.10 but not Windows 11.)

**Comment by surapunoyousei** [comment]
This is because if you completely hide sidebars such as vertical tabs, they may stop working after being unhidden.

**Comment by almighty-loaf** [comment]
I was more asking whether the compatibility effect you mentioned is due to a third-party library or binary dependency, and ultimately whether it's anything this project would have control over.
i.e. is this something a contributor could fix and make a PR for, or can I submit this issue to a more appropriate project?
thanks!

**Comment by TheChilledBuffalo** [comment]
@almighty-loaf I'm not sure but I think there was a misunderstanding. This should be fixed in the next update.

https://github.com/Floorp-Projects/Floorp-core/commit/be584a11433263a6a32a6881cba893bb881e4dcc
