### ISSUE TITLE
[Bug]: Vertical Tab shows unneeded scroll bar

### ISSUE THREAD

**Issue by menguele** [Floorp-Projects/Floorp#1012]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Using vertical tab and collapse vertical tabs, a unneeded scroll bar is shown, and it reduces the tabs view, impacting negatively the user experience.

### Reproduction Steps

1. Enable Vertical Tabs
2. Enable collapse vertical tabs 

### Expected Behavior

Scroll bar not present

### Actual Behavior

Scroll bar present.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/44483994/84fa7f57-7172-49d8-8ab3-0d5119387f0f)

### Browser Version

11.10.5

### Operating System

Windows 10

**Comment by CutterKnife** [comment]
I think this was a temporary solution to the "can't scroll vertical tab bar" problem.
