### ISSUE TITLE
Floorp opens a homepage window and then minimizes it when launching its web-apps

### ISSUE THREAD

**Issue by sudo-cyril** [Floorp-Projects/Floorp#1014]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

It's a minor bug. Generally PWAs are supposed to launch just like that without another browser window opening.
But for Floorp PWAs, if there are no instances of floorp running, it first opens a homepage window, minimizes it and then opens the PWA. 

### Reproduction Steps

1. Create a webapp for any website. for example : youtube.com
2. Close all instances of floorp which are open.
3. Open the web-app by clicking the shortcut

### Expected Behavior

It's supposed to directly open the web-app.

### Actual Behavior

It first opens a normal browser window, minimizes it and then launches the web app.

### Screenshot and Video

![issue](https://github.com/Floorp-Projects/Floorp/assets/120585028/eb2ce0eb-4185-409e-b3a0-db1d749cc6da)

https://github.com/Floorp-Projects/Floorp/assets/120585028/0312ffd8-abd2-42d8-ba50-575ad52acb60

### Browser Version

11.10.5 (64-bit)

### Operating System

Windows 10

### Additional Context

This issue only happens when there's no floorp windows opened initially.
If a floorp window is already open, then the issue does not occur

**Comment by sudo-cyril** [comment]
is there any workaround for this issue?

**Comment by CutterKnife** [comment]
With our current methods, it would be difficult to solve this problem immediately. (I'm not a developer, but that's what I heard)
https://blog.ablaze.one/3865/2024-01-17/

**Comment by sudo-cyril** [comment]
I see. 
I have a random idea, is there a way to keep Floorp as a background process in Windows? That could solve the issue.

**Comment by TheChilledBuffalo** [comment]
@sudo-cyril According to my quick testing, that isn't needed. I'll work on this over the next few days.

**Comment by surapunoyousei** [comment]
This issue is duplicated.

Contributions of code to improve this specification are welcome, but I will not work on it.

**Comment by sudo-cyril** [comment]
Could you provide a link to the original issue?
