### ISSUE TITLE
[Bug]: Status Bar gets force enabled on every browser restart

### ISSUE THREAD

**Issue by legofanlovessayori** [Floorp-Projects/Floorp#1016]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After the 11.11.0 update, restarting Floorp will always enable the status bar even if you chose to disable it.

### Reproduction Steps

1. Install / update a install of Floorp to 11.11.0
2. (when on a fresh install) Go though the Setup (or skip)
3. Restart Floorp

### Expected Behavior

The status bar should follow the user's preferences.

### Actual Behavior

The status bar will be forced enabled on every restart of the browser (on all profiles)

### Screenshots

[first discovery, on the community discord](https://discord.com/channels/877135925707173889/1100329953913999394/1219738076566519808)

https://github.com/Floorp-Projects/Floorp/assets/94994630/754bd0d8-3827-4bdf-ae6b-273e42b24681

https://github.com/Floorp-Projects/Floorp/assets/94994630/75bc93ba-7968-410e-bd3c-f707bde40d34

### Browser Version

11.11.0 (Stable)

### Operating System

Windows 10 22H2 (Build 19045.4170, Locale de-DE) + Windows 11 21H2 (Build 22000.2538, Locale en-US)

**Comment by CmplxAdSys** [comment]
I also experienced this with the 11.11.0 update on Windows 10. If i "enable" the status bar (it shows as disabled, even though it's there), then re-disable it, the status bar the disappears. But it will re-appear on the next app start.

**Comment by RoblKyogre** [comment]
also experiencing the same thing here on Arch Linux w/ KDE Plasma 6.0.2 (`Linux ArchTop 6.8.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000 x86_64 GNU/Linux`)
https://github.com/Floorp-Projects/Floorp/assets/42159204/deff6609-7b4b-48ce-99d5-8d9bd53a7d6b

**Comment by surapunoyousei** [comment]
Wait for 11.11.1. I'm working on this issue

**Comment by surapunoyousei** [comment]
Fixed
