### ISSUE TITLE
[Bug]: ppa 404 for floorp-11.11.0.deb

### ISSUE THREAD

**Issue by FloraMaeWolfe** [Floorp-Projects/Floorp#1017]
EDIT: Corrected a mistake

### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Got a notice that there is an update for Floorp. I use the PPA. Tried to update and it 404'ed. Manually went to the following url which is what was noted and it 404's.
https://ppa.floorp.app/amd64/floorp-11.11.0.deb

### Reproduction Steps

1) Refresh apt repos
2) Try to install update of floorp through apt
3) 404

### Expected Behavior

1) Refresh apt repos
2) Try to install update of floorp through apt
3) No 404.

### Actual Behavior

The PPA 404s on floorp-11.11.0.deb

### Screenshots

n/a

### Browser Version

floorp-11.11.0.deb

### Operating System

Linux Mint 21.3 (Virginia)

**Comment by surapunoyousei** [comment]
I'm working on this issue

**Comment by Aviksaikat** [comment]
I have seen this issue for almost every release so am I missing something?

**Comment by ratul-cefalo** [comment]
Facing exact error in linux mint 20.3

**Comment by stilgarwolf** [comment]
Same on Debian: "404  Not Found [IP: 104.21.35.83 443]"
Also, host command says "Host 83.35.21.104.in-addr.arpa. not found: 3(NXDOMAIN)"

**Comment by benhamoudamohamed** [comment]
Hey guys I face the same error on Linux Mint 21.3 Cinnamon

trying direct link in browser

https://ppa.floorp.app/amd64/floorp-11.11.0.deb
https://ppa.floorp.app/amd64/floorp-11.11.1.deb
=> 404 Not Found

and trying in terminal

sudo apt update
sudo apt install floorp
=> E: Failed to fetch https://ppa.floorp.app/amd64/./floorp-11.11.0.deb  404  Not Found [IP: 172.67.216.53 443]

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/actions/runs/8355479801

**Comment by x3llaz** [comment]
Same error here on MX Linux 23.... 🫤

**Comment by x3llaz** [comment]
> Wait wait... don't worry. I sending update. Wait
👌
😊

**Comment by benhamoudamohamed** [comment]
Now it passes, thanks
I have the 11.11.1 v

**Comment by surapunoyousei** [comment]
Haha. No problem!
