### ISSUE TITLE
[Bug]: a tab goes into "mobile" layout mode when it is deactivated, then delays when selected again 

### ISSUE THREAD

**Issue by TaiwanTammy** [Floorp-Projects/Floorp#1021]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

title and video explains it all

### Reproduction Steps

click out of a tab, click back. 

### Expected Behavior

-

### Actual Behavior

see video

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/164152282/3fc1a54d-0b14-4504-be15-2ce41ccb9f74

### Browser Version

11.10.5 (64-bit)

### Operating System

win 11

**Comment by surapunoyousei** [comment]
Did you use splitview?

**Comment by TaiwanTammy** [comment]
i wasn't using split view on this page

However, the browser version was from last week. when i updated to the
current version it went away. will come back if it happens again Message
ID: ***@***.***>
>
>

**Comment by surapunoyousei** [comment]
ok

**Comment by TaiwanTammy** [comment]
Here it is doing it again as I browse different web sites, twitter and people's debank profiles. 

https://github.com/Floorp-Projects/Floorp/assets/164152282/a1a5c337-f185-4311-9296-044f7e0cb35a
