### ISSUE TITLE
[Bug]: Strange behavior of the tabs on the tab bar when the toolbar customization menu is opened in floorp 11.11.1

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#1022]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

In Floorp 11.11.1 when you open the customize toolbar option the tabs on the tab bar start to "dance", this only happens when you have a  pinned tab and the tab bar is "full" before the overflow arrows appear.

### Reproduction Steps

1. Open new tabs until the tab bar is full, prevent overflow arrows from appearing.
2. Pin a tab
3. Open the option to customize the toolbar
4. The tabs in the tab bar start to "shake"

### Expected Behavior

Tabs should not shake when the customize toolbar option is opened.

### Actual Behavior

Tabs shake when you open the customize toolbar option and the tab bar is full.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/86812371/bef601e5-008c-4a19-8ac0-9efdfc00a6ec

### Browser Version

11.11.1

### Operating System

Windows 10 22H2

### Additional Context

This did not occur with the version 11.10.5

**Comment by surapunoyousei** [comment]
This issue has been known for two years, but it is not resolved as it is a custom CSS issue.

**Comment by kaos-55** [comment]
Thanks for the explanation, as I recently started using the lepton theme I had not realized that the bug was in lepton. I just went to lepton's github and it already reported this problem.
Sorry for the inconvenience.
