### ISSUE TITLE
[Bug]: `Enable Extensions Content Scripts in Browser Manager Sidebar` breaks opening external links behavior

### ISSUE THREAD

**Issue by Xetrill** [Floorp-Projects/Floorp#1026]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using multiple browser windows and having `Enable Extensions Content Scripts in Browser Manager Sidebar` enabled.
Opening an external link (e.g. `.url` shortcut) that link is always opened in the first browser window.

The options `browser.link.open_newwindow` and `browser.link.open_newwindow.override.external` are effectively ignored.

### Reproduction Steps

1. Start Floorp
2. Open new browser window (`Ctrl+N`)
3. Open an external link
   - For example on Windows you can `Win+R` and enter `https://www.google.com` and run that (Floorp has to be default browser)
5. The external link is opened in the first &ndash; not last used &ndash; browser window

### Expected Behavior

By default, external links should be opened in the last used window.
As specified by `browser.link.open_newwindow` and `browser.link.open_newwindow.override.external`.

### Actual Behavior

The link is opened in the first browser window.

### Screenshots

A bit scuffed video on Youtube as its too large: https://youtu.be/hrAFGKYyA0k

### Browser Version

11.11.1

### Operating System

Windows 11 Enterprisse (22631.3296)

### Additional Context

Disabling `Enable Extensions Content Scripts in Browser Manager Sidebar` restored the expected behavior.

**Comment by regularenthropy** [comment]
Please name the issue properly.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/bbcf0025da15b5b8a5f7d146e9ecf43a1e4dc8c2
