### ISSUE TITLE
[Bug]: Video only plays audio

### ISSUE THREAD

**Issue by molitar** [Floorp-Projects/Floorp#1027]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Video on this site (NSFW) https://www.sankakucomplex.com/2024/03/22/dearest-blue-episode-1-trailer-shows-dark-side-of-idol-business/ only shows black box with audio no video. Plays fine in Chrome. 

### Reproduction Steps

1. Browse to https://www.sankakucomplex.com/2024/03/22/dearest-blue-episode-1-trailer-shows-dark-side-of-idol-business/ and try to play video you will only get black with audio

### Expected Behavior

Video should play

### Actual Behavior

Black video with only audio

### Screenshots

![Screenshot_8](https://github.com/Floorp-Projects/Floorp/assets/16074561/b600cf0a-ab74-4c4a-9541-b35eec675ab1)

### Browser Version

11.11.1 (64-bit)

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/b1e6f2d3-2884-4311-996c-e1aaddf7271e)


Firefox ESR cannot play same video. Close issue.

** DON'T SEND ISSUE BEFORE THAT DOESN'T CHECKED ON Firefox ESR**
