### ISSUE TITLE
[Bug]: 1 pixel wide line remains at the top of the window when using toolbar at the bottom, and tabs bar not on the top

### ISSUE THREAD

**Issue by xiiyuki** [Floorp-Projects/Floorp#1028]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using "Show the toolbar at the bottom of Floorp", and setting tabs bar to be displayed somewhere else than the top of the browser, there's 1 pixel wide line visible across the whole top of the windows. For increased visibility I used Fluent UI theme.

### Reproduction Steps

1. Install Floorp
2. Go to settings
3. (Optional, for better visibility in dark mode at least) Change theme to Fluent UI
4. Select "Show the Toolbar at the bottom of Floorp"
5. Change the position of the tabs bar so it would be displayed somewhere else than top of the window
6. Notice the issue

### Expected Behavior

(I suppose) No 1 pixel wide line being displayed on the top of the window (preferably nowhere? normally it's a splitter between toolbar and browser content, but if toolbar is on the bottom and tabs bar not on the top, it serves no purpose)

### Actual Behavior

1 pixel wide line being displayed on the top of the window

### Screenshots

![floorp_dJRm87N9kR](https://github.com/Floorp-Projects/Floorp/assets/87499654/cacd6d8d-746f-497c-a6fc-6992eed53057)
![floorp_RI1gYy3mAP](https://github.com/Floorp-Projects/Floorp/assets/87499654/fb02fdad-8b66-4d29-9491-6b99a31a9260)

### Browser Version

11.11.1

### Operating System

Windows 10 19045.3693

**Comment by surapunoyousei** [comment]
This is not a bug, but a specification applied by custom CSS
