### ISSUE TITLE
[Bug]: Images not displaying correctly

### ISSUE THREAD

**Issue by AzhamProdLive** [Floorp-Projects/Floorp#1030]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Trying to get a QR Code from a website or an icon from a browser tab shows up like that : 
- Browser tab : 
![image](https://github.com/Floorp-Projects/Floorp/assets/73955243/d96a70be-b493-4bb0-b67d-0292fa21bb6d)

- QR Code : 
![image](https://github.com/Floorp-Projects/Floorp/assets/73955243/2434c062-b9c8-4a22-8bca-ceecabd63ea7)

It doesn't happens on a lot of pages, but I know it happens on Trello, AnyRUN, and Webmin (from what I use most of the time)

### Reproduction Steps

Example with Trello
1 - Open Floorp
2 - Go on Trello
3 - Click on Access my Boards
4 - Icon in the browser tab is bugged

Example with Webmin : 
1 - Open Webmin dashboard 
2 - Login 
3 - The circles and Browser tab is also bugged

### Expected Behavior

The images displaying properly

### Actual Behavior

They don't display properly 

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/73955243/d96a70be-b493-4bb0-b67d-0292fa21bb6d)

![image](https://github.com/Floorp-Projects/Floorp/assets/73955243/2434c062-b9c8-4a22-8bca-ceecabd63ea7)

I don't have images from Webmin, but I'll send them later on

### Browser Version

11.11.1

### Operating System

Windows

**Comment by surapunoyousei** [comment]
Try this site on Firefox ESR. Otherwise, you can’t submit this issue.

**Comment by surapunoyousei** [comment]
Ok

**Comment by regularenthropy** [comment]
Turn off privacy.resistFingerprinting in about:config

**Comment by AzhamProdLive** [comment]
I'll try that too before trying ESR 👍-------- Original Message --------On 3/22/24 12:12 PM, regularenthropy  wrote:
Turn off privacy.resistFingerprinting in about:config

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Floorp-Projects/Floorp/issues/1030#issuecomment-2014860832",
"url": "https://github.com/Floorp-Projects/Floorp/issues/1030#issuecomment-2014860832",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AzhamProdLive** [comment]
> Turn off privacy.resistFingerprinting in about:config and `Automatically dismiss access confirmation prompts for HTML5 image data` in settings

It worked, that fixed my issue, thanks 👍
