### ISSUE TITLE
[Bug]: カスタムショートカットキー ピクチャーインピクチャーを表示は動作しません

### ISSUE THREAD

**Issue by breadbeforerice** [Floorp-Projects/Floorp#1031]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

タイトル通りです

### Reproduction Steps

1.about:preferences#cSKのピクチャーインピクチャーを表示を設定します
2.再起動します
3.youtubeなど動画のあるページでカスタムショートカットキーを試します

### Expected Behavior

カスタムショートカットキーが機能しCtrl+Shift+ ]と同じ動作をします

### Actual Behavior

何も起こりません

### Screenshots

![ピクチャーインピクチャー](https://github.com/Floorp-Projects/Floorp/assets/158130154/0282b973-3e21-48ee-b012-ce57df30acd2)

### Browser Version

11.11.1

### Operating System

Windows 10 22H2

### Additional Context

いつから機能しなかったのかはわかりませんがアップデート前の11.10.2でも機能しませんでした

**Comment by surapunoyousei** [comment]
Fixed

**Comment by breadbeforerice** [comment]
機能修正お疲れ様です。追加で発見しましたので報告します
最近の履歴を消去  ブラウザーを終了？の挙動
ブラウザーを終了　機能しません
　
このページをブックマーク　機能しません

ブックマークのアクションの
ブックマークサイドバーを開く　機能しません
↓　ただしこちらと機能が重複な気がします
サイドバーのアクション
ブックマークサイドバーを開く
