### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Decme** [Floorp-Projects/Floorp#1032]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

scrolling is broken

### Reproduction Steps

open floorp, use mouse scrollwheel on any page (including floorp settings page), scrolling up/down does not work

### Expected Behavior

scroll wheel to work

### Actual Behavior

scroll wheel not working

### Screenshots

N/A

### Browser Version

v11.11.1 (64-bit)

### Operating System

Windows 10

### Additional Context

my mouse scrollwheel works in all other apps, including Firefox; it used to work in floorp but a recent update must have broken it

**Comment by surapunoyousei** [comment]
Maybe your env issue. I cannot reproduce it
