### ISSUE TITLE
[Bug]: Sleeping Tabs in Split View

### ISSUE THREAD

**Issue by tunaflsh** [Floorp-Projects/Floorp#1039]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Unfocused tabs in the split view can fall asleep. As a result they close themselves and leave split view mode with just one tab.

### Reproduction Steps

1. Enable sleeping tabs in [about:preferences#general](about:preferences#general).
2. Set tabs to sleep after 1 minute idle.
3. Put one tab on the left side of the split view, another one on the right.

### Expected Behavior

The two tabs never go to sleep, or at least make the browser stay in split view.

### Actual Behavior

After 1 minute. the unfocused tab - that doesn't have a cursor in it - goes to sleep and closes the split view with only the focused tab.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/86954679/378ce406-684b-4b9e-96c3-7ce50eedc06b

### Browser Version

Version 11.11.2 (64-bit) | Firefox: 115.10.0

### Operating System

Windows 11

**Comment by TheChilledBuffalo** [comment]
Fixed in [129788f](https://github.com/Floorp-Projects/Floorp-core/commit/129788ff64f6c9362c2767107b867b6923835010)

You may now close this issue.

**Comment by tunaflsh** [comment]
Thank you. Should I close this or leave it until it is in the release?
