### ISSUE TITLE
[Bug]: カスタムショートカットキー ブラウザーを終了の挙動がおかしい

### ISSUE THREAD

**Issue by breadbeforerice** [Floorp-Projects/Floorp#1043]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

カスタムショートカットキー ブラウザーを終了で
設定 一般のタブグループ 同時に複数のタブを閉じる前に確認するにチェックが入っていても確認無しにウィンドウが閉じられます
Ctrl + Shift + Qの挙動と違います

### Reproduction Steps

1.カスタムショートカットキーを設定する
2.再起動する
3.試します

### Expected Behavior

終了時、複数のタブを閉じる前に確認画面が出ます

### Actual Behavior

確認無しで終了します

### Screenshots

![2024_3_26_21_16_21_11683](https://github.com/Floorp-Projects/Floorp/assets/158130154/50a7497c-649b-4bd3-8924-71e61ebdcc5a)

### Browser Version

11.11.2

### Operating System

Windows 10 22H2

**Comment by surapunoyousei** [comment]
おかしくありません。これは意図した仕様です。
