### ISSUE TITLE
[Bug]: Overlapping addon shortcuts cannot be set from about:addons when Firefox shortcuts is disabled

### ISSUE THREAD

**Issue by DivineMK** [Floorp-Projects/Floorp#1044]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I want to use the overlapping shortcuts (for example Ctrl+J, Ctrl+G...) for addons (Sidebery specifically). I tried to enable floorp.custom.shortcutkeysAndActions.remove.fx.actions. Even though this hotkey (Ctrl+J) is no longer functional, I cannot map this hotkeys for addons in the about:addons (picture 1). However, setting this same hotkey through Sidebery prefereces pages work as expected.

### Reproduction Steps

1. Enable floorp.custom.shortcutkeysAndActions.remove.fx.actions in about:config
2. Try setting a Firefox keybindings to an action in about:addons

### Expected Behavior

The hotkey is set

### Actual Behavior

Picture 1

### Screenshots

Picture 1
@
![Screenshot 2024-03-26 15:12:41](https://github.com/Floorp-Projects/Floorp/assets/42614396/7cfd2945-3692-43e8-9f86-41d0c02e520d)

### Browser Version

11.11.2

### Operating System

Linux Mint 23.1

**Comment by TheChilledBuffalo** [comment]
I just checked this in FIrefox ESR and this seems to be occurring there as well.... So maybe you can submit an issue on Bugzilla

**Comment by TheChilledBuffalo** [comment]
Ohhhhh wait... Sorry, you mean even when Firefox shortcuts are disabled, this occurs huh... Weird

**Comment by surapunoyousei** [comment]
This is not an implementation intended to run extensions, but to override them with Floorp-specific shortcut keys.

**Comment by DivineMK** [comment]
This is unfortunate. I am curious how this overriding of Firefox shortcut keys is implemented and whether something like #1045 and #1046 can be achieved.

**Comment by TheChilledBuffalo** [comment]
https://github.com/Floorp-Projects/Floorp-private-components/blob/main/browser/base/content/browser-custom-keyboard-shortcut.js

@DivineMK The source code is here
