### ISSUE TITLE
[Bug]: buggy UI in "customize toolbar" page, when vertical tabs are enabled

### ISSUE THREAD

**Issue by tunaflsh** [Floorp-Projects/Floorp#1047]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Vertical tabs appear in the title bar in the "customize toolbar" page. This gets especially buggy and laggy, when there are a lot of tabs open and they don't all fit in that area.

### Reproduction Steps

1. Enable vertical tabs.
2. Right click on the address bar and open "customize toolbar" page

### Expected Behavior

Vertical tabs remain on the left (or right depending on the settings).

### Actual Behavior

Vertical tabs get pushed to the title bar.

### Screenshots

![Screenshot 2024-03-27 191703](https://github.com/Floorp-Projects/Floorp/assets/86954679/a954167d-818e-4da7-80f1-1cfd74cb8fde)

### Browser Version

Version 11.11.2 (64-bit) | Firefox: 115.10.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
Vertical tabs require a restart when disabled, so we solve this by hiding the element. This is intentional.

**Comment by tunaflsh** [comment]
Ok, I misunderstood the UI then. But there are these things:
1. For example if you toggle the "hide button when empty" option of the "downloads" tool, the tab bar disappears.
![image](https://github.com/Floorp-Projects/Floorp/assets/86954679/25f329ac-7a92-43a3-a8bc-4c06dd4c3c63)
2. The tab bar in collapsed mode vs non-collapsed mode (when hovering over it) doesn't look right to me.
![image](https://github.com/Floorp-Projects/Floorp/assets/86954679/cdb90ed7-7896-4031-9f06-426f1a678996)
![image](https://github.com/Floorp-Projects/Floorp/assets/86954679/29bc19d0-2915-4920-af30-ff882afb1267)
