### ISSUE TITLE
[Bug]: YouTube HDR does not show corect colours unless in cinema mode MacOS

### ISSUE THREAD

**Issue by VinylNerd** [Floorp-Projects/Floorp#1048]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

youtube HDR does not show correct colours unless in cinema mode on macos

### Reproduction Steps

1. Go to YouTube in Floorp and search for HDR video on a MacOS system
2. Switch video from "cinema mode" to "default view"

### Expected Behavior

colour profiles should not change

### Actual Behavior

colour profiles do change

### Screenshots

![Screenshot 2024-03-27 at 12 10 43 PM](https://github.com/Floorp-Projects/Floorp/assets/72950020/842fe50a-8397-4873-9194-38326647e69d)

![Screenshot 2024-03-27 at 12 10 53 PM](https://github.com/Floorp-Projects/Floorp/assets/72950020/62827aee-891d-4987-b814-433e49f85057)

### Browser Version

11.11.2

### Operating System

13.6.4

### Additional Context

issue also occurs in firefox and firefox ESR

**Comment by TheChilledBuffalo** [comment]
If the issue occurs on Firefox as well, then maybe this isn't the right place to report it.

**Comment by VinylNerd** [comment]
> If the issue occurs on Firefox as well, then maybe this isn't the right place to report it.

that would imply that the browser is fully at the mercy of Firefox's issues whereas I am confident that the idea of Floorp is to improve the Firefox experience.

**Comment by surapunoyousei** [comment]
Since I'm not interested in fixing such minor details, I will close this issue.
