### ISSUE TITLE
NEED HELP (Browser Manager Sidebar

### ISSUE THREAD

**Issue by surapunoyousei** [Floorp-Projects/Floorp#105]
When registering a lot of URLs in the web panel, or when using Floorp's browser manager sidebar in a low-resolution environment, the bottom part of the website will not be displayed.

Previously, when the vertical size of the browser became smaller by applying the following CSS to the select box on the panel, we were bypassing interference with the website due to the vertical length of the select box. The following CSS does not work with Firefox 107 or later.

height:100vh;
overflow: hidden auto;

Do you have any other ideas?

In addition, the Firefox 107-based development repository is http://GitHub.com/surapunoyousei/Floorp-Nightly

**Comment by surapunoyousei** [comment]
10.6.0
![image](https://user-images.githubusercontent.com/73892113/195801768-f620f2c0-deb6-420d-86e5-68e5f5fdde91.png)

10.8.0 ( No CSS ) 100vh does not work well.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by Psypher1** [comment]
I have an unrelated question: Is there a way (preferably shortcut) to toggle its visibility. I saw the option in settings but I can't be going thee every time
