### ISSUE TITLE
[Bug]: Website resizes slightly when hovering over collapsed vertical tabs

### ISSUE THREAD

**Issue by Hikiru** [Floorp-Projects/Floorp#1050]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When "collapse vertical tabs" is enabled, it works as expected but the website will slightly resize when hovering over them. The tab bar takes a small amount of space when collapsed, but that taken space goes away when you hover over the tab bar, so the website looks weird since it resizes a little bit to fill that space. The easy fix to this is to just always use the space that collapsed tabs would take even when hovering over them.

### Reproduction Steps

1: Turn on "collapse vertical tabs"
2: Hover over tabs

### Expected Behavior

Website stays the same

### Actual Behavior

Website fills the empty space and looks kinda weird

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/18605854/91bc5dcb-d39f-4f0a-9137-114fa785a061

### Browser Version

11.11.1

### Operating System

SteamOS

**Comment by surapunoyousei** [comment]
This is a bug specific to some Linux systems, and so far no code has been found to resolve it.

Closed due to duplication.

**Comment by TheChilledBuffalo** [comment]
Finally found a fix for this!

https://github.com/Floorp-Projects/Floorp-core/commit/620cd8b733f5de4a71cd59ab4adc403a081906b6
