### ISSUE TITLE
[Bug]: Moving Tab from one window to another screen moves new and old window

### ISSUE THREAD

**Issue by Pheromir** [Floorp-Projects/Floorp#1052]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When dragging a tab from one window onto another screen to create a second window, the old window with the remaining tabs is also moved to the second screen. This seems to only happen when dragging to another screen, not if dragging to another location on the same screen.

### Reproduction Steps

1. Create a new Tab in an existing window
2. Drag and drop the new tab onto your second screen to get a new window
(3. Sometimes it seems to be necessary to click into the new tab and then drag the tab onto the second screen for this bug to occurr?)

### Expected Behavior

A new window is created with the dragged tab on the new screen.
The old window with the remaining tabs remain on the old screen.

### Actual Behavior

A new window is created with the dragged tab, but the old window with the remaining tabs is also moved to the other screen.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/13359741/d099072a-e04d-4525-a284-8d7457a4fd13

### Browser Version

11.11.2 (64-Bit)

### Operating System

Windows 11 23H2 (22631.3155)

### Additional Context

It doesn't always happen, especially if moving multiple tabs in a short time, but most of the time after using a tab normally and then moving it onto the second screen.

**Comment by surapunoyousei** [comment]
I can't fix this as I don't have more than 2 displays.
