### ISSUE TITLE
[Bug]: Slow upload speed to YouTube

### ISSUE THREAD

**Issue by GameAreaCZ** [Floorp-Projects/Floorp#1053]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Very slow upload speed to YouTube (like 20-30 Mb/s). Other browser full internet speed 70-90 MB/s.

### Reproduction Steps

1. Upload video to YouTube.

### Expected Behavior

Just normal upload speed like in other browsers.

### Actual Behavior

Slow upload speed to YouTube.

### Screenshots

Floorp:
![obrazek](https://github.com/Floorp-Projects/Floorp/assets/82257025/5ebd97dc-9f96-40cc-9ab9-1c174bd5295b)

Edge:
![obrazek](https://github.com/Floorp-Projects/Floorp/assets/82257025/d2508ee3-c0bd-4c10-8ce8-af6512d87fee)

### Browser Version

11.11.2

### Operating System

Windows 11

**Comment by CutterKnife** [comment]
Is it slower than Firefox ESR?
