### ISSUE TITLE
[Bug]: Crash upon launch on Windows 7 x86

### ISSUE THREAD

**Issue by naryfa** [Floorp-Projects/Floorp#1055]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

As in the subject.

Granted, it's an old laptop, but that's why I am trying to use this browser... W7 x86, Core 2 Duo T7600, 4GB RAM

Tried the newest version, then tried rolling back to 11.11.0, same result.

Here's the Event Viewer log:

Faulting application name: floorp.exe, version: 115.9.0.8843, time stamp: 0x65f8610d
Faulting module name: xul.dll, version: 115.9.0.8843, time stamp: 0x65f861a6
Exception code: 0x80000003
Fault offset: 0x0035db01
Faulting process id: 0xdac
Faulting application start time: 0x01da83026551fbed
Faulting application path: C:\Program Files\Ablaze Floorp\floorp.exe
Faulting module path: C:\Program Files\Ablaze Floorp\xul.dll
Report Id: a53796bf-eef5-11ee-870e-0019b96a9b51

### Reproduction Steps

1. Launch the app.

### Expected Behavior

Window should open.

### Actual Behavior

I get a crash warning

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/38587586/bad5c3a6-9608-42fe-a5f4-0367d6db5a93)

### Browser Version

11.11.0

### Operating System

Windows 7 x86

### Additional Context

Fresh install. Just installed Firefox ESR 115.7 to compare and it launches without any problems.

**Comment by breadbeforerice** [comment]
If you search for crash, you'll find this about 3 places down.
https://github.com/Floorp-Projects/Floorp/issues/311
and the discussion has this
https://github.com/Floorp-Projects/Floorp/discussions/943

**Comment by surapunoyousei** [comment]
Before talking about this, Floorp is not supported on Windows7

**Comment by TV-Toshikawa** [comment]
You could try software such as VxKex, but this is unofficial, so except buggy behaviors.
