### ISSUE TITLE
[Bug]: Websites resize when using collapsible vertical tabs

### ISSUE THREAD

**Issue by highlyreactiveNeon** [Floorp-Projects/Floorp#1056]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [x] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using collapsible vertical tabs in Arch Linux, every time the vertical tabs section is expanded the current website resizes. This issue is not present in Windows version

### Reproduction Steps

1. Enable Vertical tabs
2. Enable collapsible option
3. Go to any website and check by expanding and collapsing the vertical tabs
4. The website resizes

### Expected Behavior

The website shouldn't resize

### Actual Behavior

Actual behavior can be viewed in the attached video

### Screenshots

[floorp vertical tabs bug.webm](https://github.com/Floorp-Projects/Floorp/assets/97377851/e853d1f7-ab5d-4b38-ad19-15fdaaa372a3)

### Browser Version

11.11.2

### Operating System

Arch Linux

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1050
Duplicate

**Comment by highlyreactiveNeon** [comment]
This is issue was fixed in version 11.12.0. But after updating to 11.12.2, the same problem started again

**Comment by kasparkallas** [comment]
Just installed Floorp, also bothered by this.

@TheChilledBuffalo I guess you didn't find a better solution? FYI, the new Zen Browser is also Firefox-based and it doesn't have this problem with its vertical tabs expanding, maybe you could get an idea from its codebase: https://github.com/zen-browser/desktop/blob/c195b1ecb976f22ccdd68f6372542e45b0219f2a/src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css

**Comment by TheChilledBuffalo** [comment]
The implementation looks quite a bit different, but I'll take a look.
