### ISSUE TITLE
[Bug]:  Split View tabs are not resizable

### ISSUE THREAD

**Issue by ResponsibleBelt** [Floorp-Projects/Floorp#1057]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When split view is enabled, the tabs are not resizable.

### Reproduction Steps

1. Open multiple tabs
2. Right click on a tab and enable split view.
3. Cannot change the width of the tabs by clicking on the center line

### Expected Behavior

The width of the tabs changes

### Actual Behavior

The tabs stay as is

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/165544384/5c091139-6641-4c73-b21c-3ab43b877cda

### Browser Version

11.11.2

### Operating System

Windows 11 23H2

### Additional Context

This is possible in every other browser that supports Split View. So its expected to be available on Floorp as well.

**Comment by surapunoyousei** [comment]
Please submit as a feature request
