### ISSUE TITLE
Can't see the text in tree style tab when using proton theme

### ISSUE THREAD

**Issue by 9tin9tin9** [Floorp-Projects/Floorp#106]
## Describe the bug
Background and text are both white in the tree style tab and I can barely see the text when using proton theme
<img width="705" alt="Screenshot 2022-10-14 at 11 44 15 AM" src="https://user-images.githubusercontent.com/65890942/195757936-29182960-622a-4336-914f-8a04d4e47b6a.png">

## Expected behavior
The photon theme used dark background and white text. I guess this should be the expected the behavior when using proton theme

## Desktop (please complete the following information):
 - OS: MacOS Monterey 12.4
 - Floorp Version: 10.6

**Comment by surapunoyousei** [comment]
In the following states, Floorp's TST will be in white mode.

When the powerful anti-fingerprint feature with Firefox is enabled

When the theme is a third-party or built-in Firefox Photon theme (to be deleted)

**Comment by 9tin9tin9** [comment]
what do you mean by will be deleted? The photon theme will be deleted in future versions of Floorp?

**Comment by surapunoyousei** [comment]
Yes. Photon Theme will be deleted at v10.6.1. NOT AS DESIGN. photon design can use at v10.6.1 of Floorp.


A theme is a theme displayed in about:addons, and you can get a theme from AMO. In other words, the problem rarely happens.

**Comment by 9tin9tin9** [comment]
> In the following states, Floorp's TST will be in white mode.
> 
> When the powerful anti-fingerprint feature with Firefox is enabled
> 
> 

But I didn't enable strong protection against fingerprinting

**Comment by surapunoyousei** [comment]
What kind of themes are enabled? 

If possible, try Floorp refresh.

**Comment by 9tin9tin9** [comment]
I try it when I get back home tonight

**Comment by 9tin9tin9** [comment]
I only enabled system theme, and my Mac uses dark mode.

**Comment by surapunoyousei** [comment]
TRY refresh floorp

**Comment by surapunoyousei** [comment]
Please open write "about:support" on your URL bar. and push enter.

There is a trouble shooting information.

click "Refresh Floorp"

**Comment by surapunoyousei** [comment]
https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by 9tin9tin9** [comment]
Just followed your instruction and changed the TST theme to proton and its the same. This is the screen recording of what I have done and the behavior of Floorp for your reference

https://user-images.githubusercontent.com/65890942/195869441-7c52f4be-c224-44bd-9d85-fb754c19a9bb.mp4

**Comment by surapunoyousei** [comment]
Hmm.

OK. We will deliver 10.6.1 next week. See if it's fixed there.  Updating TST to the latest version.

**Comment by TungstenIodide** [comment]
Hi,

I am hitting the same issue on Linux Flatpak version. It happens when 'Theme Mode' is set to dark.

It happens regardless of the design chosen (Proton/Lepton/Fluerial).

I tried wiping all Floorp data, resetting startup cache in 'about:support' and launching in Troubleshoot Mode.

**Comment by surapunoyousei** [comment]
Tell me your Floorp version

**Comment by TungstenIodide** [comment]
11.1.0

Build ID: 20230804074614

**Comment by surapunoyousei** [comment]
Floorp 11 doesn't include TST. Please send report or Search same issue.

https://github.com/piroor/treestyletab/issues

**Comment by TungstenIodide** [comment]
I'm sorry. It looked similar on screenshots above and I didn't realize that current Vertical Tab Bar is different from TST.

I do not see a separate issue for VTB raised, but it looks like the same issue. Should I raise a separate issue to track it?

**Comment by surapunoyousei** [comment]
please separate issue.

Give us a screenshot
