### ISSUE TITLE
[Bug]: Copy paste doesn't work consistently with Wayland KDE

### ISSUE THREAD

**Issue by LarveyOfficial** [Floorp-Projects/Floorp#1063]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Whenever you try to copy from Floorp using Control + C or right click copy, if you are copying from the address bar, or are right clicking a link/URL, it will not copy the content to the system clipboard.

This means you cannot do the following:
Copy from the address bar and paste into another application.
Right click a link on a website and select copy.

But you can do the following:
Select and Control + C or right click text from a website, and then paste it into another application
Copy text from another application, and paste it into Floorp.
Copy text from the address bar, and paste it into another section/field in floorp.

### Reproduction Steps

1. Have KDE Wayland installed (newest version)
2. Have newest version of Floorp Installed.
3. Start Floorp using `MOZ_ENABLE_WAYLAND=1 floorp`
4. Type something into the address bar
5. Select what was typed
6. Either right click Copy, or Ctrl + C
7. Navigate to the KDE Clipboard manager
8. See that what you copied is not there
9. Attempt to paste into Konsole or Kate, and see that it wont paste.
10. Go Back to Floorp, open a new tab, and paste into the address bar
11. See that it does paste what was copied earlier.

### Expected Behavior

Copying anything should copy the contents into the KDE clipboard, no matter what.

### Actual Behavior

Copying anything from the address bar or right clicking a link and selecting copy does NOT copy it to the KDE clipboard

### Screenshots

[Screencast_20240401_200938.webm](https://github.com/Floorp-Projects/Floorp/assets/39219859/f47e6c84-457b-4da1-afae-6c12d3673e99)

### Browser Version

11.11.2

### Operating System

EndeavourOS, Kernel 6.8.2-zen2-1-zen, KDE Plasma 6.0.3 (Wayland)

### Additional Context

This issue may have already been fixed on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1762429

**Comment by surapunoyousei** [comment]
Currently, Wayland is unsupported on Floorp
