### ISSUE TITLE
[Bug]: Feature request are not very active

### ISSUE THREAD

**Issue by DivineMK** [Floorp-Projects/Floorp#1067]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary
I just wanna bump this feature request #1066
### Browser Version

11.11.2

### Operating System

Linux Mint

**Comment by regularenthropy** [comment]
If you want to bump something, please make the title and description accordingly.

**Comment by CutterKnife** [comment]
Do not post feature requests to Issues.

Currently, the team is severely under-resourced and only does work that it deems particularly important. Please be patient.

**Comment by DivineMK** [comment]
My bad I will close the issue.

**Comment by CutterKnife** [comment]
Thank you for your understanding!
