### ISSUE TITLE
[Bug]: « open new tab button at the end of the lowest row » doesn't apply correctly

### ISSUE THREAD

**Issue by LightShaft** [Floorp-Projects/Floorp#1068]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hi
So I have this issue where the "+" button to open a new tab doesn't always put itself on the lowest row (if I have the multi-row tab bar) when I start Floorp and it bugs me out

It works properly on a clean profile that has nothing but I need Firefox Sync, extensions etc. So I've tried to see what was causing the issue without success.
I've tried to disable all extensions, all themes, delete user.js, clearing data/cache, nothing.
I've tried to create a new profile then copy all the data from the first profile to the new one and surprise ... that works !! Which is weird because after checking, it's literally the same thing : same extensions, themes, user.js, options etc etc ... same thing
But I've reinstalled Windows and now it doesn't work anymore and I don't really want to do the whole process again, instead I would like to see how could this issue be resolved as I'm pretty sure that something must be triggering this.

Please understand that I've been trying to understand on my own what could be the culprit, so posting this is really a last resort. I don't know what could be interfering but Floorp itself somehow

To fix this I do have to somehow « refresh » the bar, either untoggling and retoggling the option or right click « customise toolbar » and click on « Done » without doing any modification for the option to be reapplied, or opening settings and wait around a second for the option to be applied by itself, but I have to do that every time I launch Floorp which isn't ideal.

Please let me know how I could provide more details if the issue is unclear, I've made some screen captures in order to show what was the issue, thanks a lot.

### Reproduction Steps

1. Enable multi-row tab bar
2. Use Firefox Photon Lepton UI
3. Enable « Place the "Open a new tab" button at the end of the lowest row of tabs »
4. Close all tabs
5. Restart the browser
6. The « + » button might be on the good spot, resize the window to fullscreen or open a new tab for it to go elsewhere

### Expected Behavior

The « + » new tab button should always be at the bottom of the tabs list

### Actual Behavior

The « + » new tab button go to the right as if the option wasn't toggled when I launch Floorp

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/27209225/5c13c921-8ef2-4c29-b5c5-df31fe8d542e

https://github.com/Floorp-Projects/Floorp/assets/27209225/2d5f94dc-5a9a-4c9b-8f23-71be7aec568b

### Browser Version

11.11.2 64 bits

### Operating System

Windows 11 23H2

**Comment by CutterKnife** [comment]
Giving the issue a title will help others find this issue :)

**Comment by breadbeforerice** [comment]
I tried to create a new profile, but the problem still occurs.
I have provided detailed instructions on how to reproduce the problem. 
Both are checked, is that correct?

**Comment by LightShaft** [comment]
Yes
I specified that when I created a new profile, it would work for a while so I would transfer all my data from my main profile to another and it would work surprisingly, that makes me think that it might be not something on my profile that interfere. But that only worked for a while since the issue returned

**Comment by surapunoyousei** [comment]
Please use proton UI instead of lepton UI

**Comment by TheChilledBuffalo** [comment]
@LightShaft Hey have you tried using Proton? And the issue doesn't occur there? Because during my testing, it occurs in Proton as well as Lepton. I'm working on a fix but it seems tricky.

**Comment by LightShaft** [comment]
> @LightShaft Hey have you tried using Proton? And the issue doesn't occur there? Because during my testing, it occurs in Proton as well as Lepton. I'm working on a fix but it seems tricky.

I thought it would work but you're right, when I select Proton and restart the browser the same bug happens (and somehow the tabs are a little bit thinner)

**Comment by TheChilledBuffalo** [comment]
Fixed! You may now close this issue.

https://github.com/Floorp-Projects/Floorp-core/commit/c38a64c5b5c8b31403eb730fdefe067be15e7778

**Comment by LightShaft** [comment]
Thanks a lot !!! Can't wait for the next update 😎
