### ISSUE TITLE
[Bug]: Link preview (when hovering links) disappears when unloading sidebar webpanels

### ISSUE THREAD

**Issue by yawns** [Floorp-Projects/Floorp#1070]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp's 11.11.2 release notes say, "Fix link preview doesn’t shown if user uses webpanel," but this seems to still be an issue. The link preview disappears after a panel is unloaded.

The video was taken in a newly created profile with no changes or addons.

### Reproduction Steps

1. Open a web panel in the sidebar.
2. Right click the panel's icon and "unload this panel."
3. Hover over a link. No preview is shown.

### Expected Behavior

The URL preview should always be visible when hovering a link.

### Actual Behavior

The URL preview is not visible after unloading a web panel.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/2416785/6d8ab82c-0d88-423d-8fed-ea021a797c70

### Browser Version

Floorp 11.11.2

### Operating System

MacOS 14.4.1

**Comment by surapunoyousei** [comment]
Yeah. fixed
