### ISSUE TITLE
[Bug]: No way to remove "your browser is being managed by your organisation" after accidentally importing a managed Google Account

### ISSUE THREAD

**Issue by GeekOfTheWild** [Floorp-Projects/Floorp#1075]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Browser is managed by my organisation (personal machine), there appears to get rid of this. I have tried deleting ~/.floorp and ~/.cache/floorp but to no effect. I have also tried switching profiles.

### Reproduction Steps

1. Install Floorp
2. In setup, import data from a previous browser with a Google Account managed by an organisation
3. Struggle to be rid of admin restrictions

### Expected Behavior

Able to wipe everything and start anew

### Actual Behavior

Seemingly no ability to wipe everything an start anew

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/65318026/a0d620b2-ecad-4371-a679-d54b9fc0aeb8)
Found in settings

### Browser Version

Version 11.11.2 (64-bit) | Firefox: 115.10.0

### Operating System

Arch Linux 64-bit Rolling

**Comment by TheChilledBuffalo** [comment]
@GeekOfTheWild As far as I understand this is nothing related to your Google account. I assume you've installed Floorp from the AUR. The AUR PKGBUILD disables auto-updates and some other changes which I'm not completely sure of. And this is why Floorp shows that your browser is managed by your "organization". The same thing happens in the Flatpak version as well, as they make some Flatpak specific changes. So this is completely normal. If you really want to get rid of it, you will have to build Floorp from the ground up, *on your machine*.

You can find instructions on how to do that here: https://github.com/Floorp-Projects/Floorp/wiki/developers-building-linux

**Comment by TheChilledBuffalo** [comment]
If that clarifies your issue, you may close this thread. Thanks.

**Comment by GeekOfTheWild** [comment]
Oh ok, tysm!
