### ISSUE TITLE
[Bug]: Floorp Portable doesn't start anymore

### ISSUE THREAD

**Issue by Hadden89** [Floorp-Projects/Floorp#1076]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After one of the latest update, it seems Floorp doesn't start anymore.

### Reproduction Steps

Just tried to launch the browser

### Expected Behavior

Browser start

### Actual Behavior

Error window (look below)

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/18642541/6b2e0451-ab9c-4905-b62e-04a7722b59eb)

### Browser Version

Latest floorp release

### Operating System

Windows 11 23H2

### Additional Context

Let me know if for anything else you may need to know or things to check to workaround this issue.

**Comment by regularenthropy** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/89523758/e4a10478-4176-43bd-bc5e-cef81c57c143)

Working fine on my side. What's your CPU?

**Comment by Hadden89** [comment]
ryzen 7 5800x ... btw with the portable I got the error above while trying to update to 11.11.2 where worked fine when it just launched the previous 11.11.1. 

I just installed a new regular 11.11.2 install and all seems ok :)

**Comment by surapunoyousei** [comment]
For portable versions, please create an Issue in the portable version's repository
