### ISSUE TITLE
New function `web-panel zoom` breaks standard hover-view of website link URLs. v11.11.2.

### ISSUE THREAD

**Issue by guigirl42** [Floorp-Projects/Floorp#1079]
>Hi @surapunoyousei thank you very much for `v11.11.2` ...

>I've now re-enabled `Enable Extensions Content Scripts in Browser Manager Sidebar` & tested the link-hover url-balloons again. Happily your fix seems to have worked, for the scenarios that i described in my OP. :tada: 

>Unfortunately though i found that **it breaks again** IF i use your new feature with this latest version, the _web-panel zoom_. In my testing so far, as long as i avoid using that new feature, the balloons stay working fine, but i found after trying the zoom on a couple of my web-panels the balloons stopped working again, until i restarted Floorp.

_Originally posted by @guigirl42 in https://github.com/Floorp-Projects/Floorp/issues/1024#issuecomment-2018043539_

Unfortunately my original Issue thread was Closed prematurely, so i've created this new Issue specifically for the new bug introduced with `v11.11.2`.

**Comment by DivineMK** [comment]
+1

**Comment by surapunoyousei** [comment]
Ok ~ I pushed fix code

**Comment by DivineMK** [comment]
Is it possible to add this update to my current Floorp or I should wait till the next release?

**Comment by surapunoyousei** [comment]
No problem. i will release new version of Floorp tomorrow

**Comment by DivineMK** [comment]
Oh I see I just thought there is a way to build Floorp that I don't know about 😅. Very impressed by your instant response btw :) Thank you for the great support!

**Comment by surapunoyousei** [comment]
No problem. BTW, you can build floorp.
https://docs.floorp.app/

**Comment by DivineMK** [comment]
Ohhh I see it is what I'm looking for!

**Comment by guigirl42** [comment]
> Ok ~ I pushed fix code

I just got the update, & it does indeed now seem to be fixed. Thank you _very much!_ :hugs:
