### ISSUE TITLE
How to turn off the ugly dark theme?

### ISSUE THREAD

**Issue by Telmesomething** [Floorp-Projects/Floorp#108]
## Describe the bug
After updating to 10.6.1 the preferences page is only available in the dark theme. 
## To Reproduce
1. Go to Tools ---> Settings. The Dark Theme loads and cannot be changed. Since the font used on the Settings page is the same colour as the background it's impossible tp see what's written. 
The normal browser window opens with the user selected theme which can be changed.

## Expected behavior
The Settings background color should remain the same as the normal window used for surfing. 

## Screenshots
![how to turn off the ugly dark theme](https://user-images.githubusercontent.com/33827636/196111202-9a9d1a6d-0b4a-48e8-ade2-9fd82a340854.PNG)

Normal colour window used for surfing
![normal window](https://user-images.githubusercontent.com/33827636/196111653-63f1b305-0df2-4498-838c-28a5feac7fba.PNG)

## Desktop (please complete the following information):
 - OS: Windows 8.1
 - Floorp Version: 10.6.1

## Additional context
Everything was working perfectly prior to the latest update.

**Comment by surapunoyousei** [comment]
It is mistake. We will release 10.6.2

**Comment by surapunoyousei** [comment]
Fixd. at night. we will release 10.6.2

**Comment by Telmesomething** [comment]
The update to 10.6.2 fixed the issue I described although the menu borders are still black as per the screenshot, but I can live with that. Thanks.

![menu borders are still black](https://user-images.githubusercontent.com/33827636/196253105-2389dc47-43a6-4ddd-967e-9a075f06b84a.PNG)
