### ISSUE TITLE
[Bug]: Browser Manager Sidebar drops URL parameters despite URL paremeters being included

### ISSUE THREAD

**Issue by marcyiu** [Floorp-Projects/Floorp#1083]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When opening sidebar links with URL parameters, URL parameters are dropped and the webpage without URL parameters is displayed. 

### Reproduction Steps

1. Add a page with URL parameters to the Web Panel. 
In this example, "(https://duckduckgo.com/?q=‌text&ia=chat)"
2. Accept the default settings and click on "Save Changes". 
Sidenote: Configurations including opening in a Container, using Mobile Agent were also tested and yielded the same result. 
4. Open the Web Panel that you have just created. 
5. Web Panel navigates to "https://duckduckgo.com" instead of "https://duckduckgo.com/?q=‌text&ia=chat"

### Expected Behavior

URL Parameters should be kept when specified by the user in "Address of web site". 
In the case of the above example, the web panel should navigate to "https://duckduckgo.com/?q=‌text&ia=chat". 

### Actual Behavior

URL Parameters are dropped when launching sidebar panel webpages. 

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/79884440/e32bbc53-a996-4859-b9d3-4b72368c3331

### Browser Version

Version 11.11.2 (64-bit) l Firefox: 115.10.0

### Operating System

Windows 11 Home 24H2 Build 26100.1

### Additional Context

I am not sure if this behavior is intentional, but since both the URL preview when hovering over the Web Panel icon, and the "Browser Manager Sidebar/Web Panel Settings" in Floorp Preferences shows the full URL has been saved, I assume this behavior isn't intended.

**Comment by TheChilledBuffalo** [comment]
Wow ok, this was fixed just hours ago lol.

https://github.com/Floorp-Projects/Floorp/commit/2c1b1bfdca73c748769f33a645eef46c7a36a19f

https://github.com/Floorp-Projects/Floorp/commit/f7d704aaefbe09c81ab31cee6bcca766fd09fc21

**Comment by TheChilledBuffalo** [comment]
Should be a part of the next update. Thanks for the report, but you may close it now.

**Comment by marcyiu** [comment]
That's great to hear! Thank you very much, Floorp team, for your consistent hard work on the browser!
