### ISSUE TITLE
[Bug]: Web-Apps (WPA) crash using containers

### ISSUE THREAD

**Issue by SystemError12** [Floorp-Projects/Floorp#1085]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The description was already posted a while ago in the Discussions sections. Since noone replied I would like to move it to bug report. The link is the following:

https://github.com/Floorp-Projects/Floorp/discussions/1061#discussion-6446724

### Reproduction Steps

1. Create WPA Web-App in Windows 11 with active Google-Container
2. (Alternatively try the same with Instagram and active Facebook-Container)
3. Place the web-app icon somewhere you can easily access it. 
4. Open the Web-App
5. The Window will immediately crash and not even load at all. 
6. Try the same again without Container and it works fine. 

Side-Note: This issue is pretty new. I was able to use Web-Apps with containers before until it suddenly stopped. 

### Expected Behavior

Web-App opens and displays the desired website in app version. 

### Actual Behavior

Window only opens for half a second, not full-screen but only a small Window, then crashes immediately. Not possible to make a screenshot. It's too fast. 

### Screenshots

See above

### Browser Version

11.11.2

### Operating System

Windows 11

### Additional Context

As written. Worked for many months then suddenly stopped working.

**Comment by surapunoyousei** [comment]
The reason seems to be that the extension does not support PWA.

Please consider switching as we plan to create an implementation that will allow containers to be used with PWAs.

**Comment by surapunoyousei** [comment]
Temporarily closed as containers are not supported at this time
