### ISSUE TITLE
[Bug]: Window buttons move to the right side when choosing "Display Tab Bar underneath the Toolbar" on macOS

### ISSUE THREAD

**Issue by sergeyshadok** [Floorp-Projects/Floorp#1088]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Window buttons (close/minimize/maximize) on macOS move to the right side of the Toolbar when choosing "Display Tab Bar underneath the Toolbar" option in preferences. Can't see a reason why it would be an intended behavior.

### Reproduction Steps

1. Go to "about:preferences#design".
2. Scroll down to the "Tab Bar" section.
3. Choose "Display Tab Bar underneath the Toolbar" option.

### Expected Behavior

Window buttons stay on the left side of the Toolbar.

### Actual Behavior

Window buttons move to the right side of the Toolbar.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/41486169/5f2b40c3-1ba3-465b-8703-b46e3a4c89a1

### Browser Version

11.11.2

### Operating System

macOS Ventura 13.0

### Additional Context

If it is intended behavior, I would like to know how to move window buttons back to the left side when in "Display Tab Bar underneath the Toolbar" mode. Thank you.

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1318#issuecomment-2309109848
