### ISSUE TITLE
[Bug]: Sidebar splitter is too wide.

### ISSUE THREAD

**Issue by Axenide** [Floorp-Projects/Floorp#1096]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The splitter is a lot wider than before.

### Reproduction Steps

1. Open side panel.
2. Enjoy.

### Expected Behavior

A splitter... Not that wide?

### Actual Behavior

See screenshot.

### Screenshots

![imagen](https://github.com/Floorp-Projects/Floorp/assets/66109459/355a1b99-2810-4da3-82c3-8920983679ad)

### Browser Version

Mozilla Floorp 11.12.0

### Operating System

Arch Linux

**Comment by surapunoyousei** [comment]
This should only happen when the page corners are rounded. Please turn off the setting.

**Comment by Axenide** [comment]
The setting is turned off. Those rounded corners are from my custom userChrome.css, and even with that file deleted the issue persists.

**Comment by surapunoyousei** [comment]
Please tell me your env more

**Comment by surapunoyousei** [comment]
Please let me know how it behaves with the new profile as well.

**Comment by Axenide** [comment]
No issues on a new profile, time to make another one heh.

**Comment by surapunoyousei** [comment]
Please, Don't check the checkbox " I have tried to create a new profile and the issue still occurs."

**Comment by Axenide** [comment]
I'm sorry. I tried on _other_ profile but not in a _new_ one. That's why I checked it.

**Comment by surapunoyousei** [comment]
Don't worry.

But, we can understand some of preferences or custom css occurs the issue

**Comment by Axenide** [comment]
I found the problem. When enabling collapsible vertical tabs, it creates a space on the left of the panels. I guess this has to do with the way the page resize when hovering the tabs was fixed.

**Comment by TheChilledBuffalo** [comment]
> I found the problem. When enabling collapsible vertical tabs, it creates a space on the left of the panels. I guess this has to do with the way the page resize when hovering the tabs was fixed.

Oh yeah.... that makes sense... Here's the commit that I made that fixed that issue: https://github.com/Floorp-Projects/Floorp-core/commit/620cd8b733f5de4a71cd59ab4adc403a081906b6

Do you have a better idea? Or I might have to revert this one, and that will bring back the website resizing...

**Comment by Axenide** [comment]
I checked and modified that file with the live inspector and it didn't affect side panels.
Also, about the commit, on my end it doesn't work but works with -52px and 52px instead. I guess it has to do with my userChrome.css.

**Comment by Axenide** [comment]
Alright, I made a pull request. This should finally fix the website resize and the margin inside webpanels. :)
https://github.com/Floorp-Projects/Floorp-core/pull/69
