### ISSUE TITLE
[Bug]: Scrolling speed on touchpad is too fast in 11.12.0 on macOS

### ISSUE THREAD

**Issue by sergeyshadok** [Floorp-Projects/Floorp#1098]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [x] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Today my Floorp automatically updated from 11.11.2 to 11.12.0 and scrolling speed on touchpad increased to uncomfortable levels. I completely reinstalled Floorp and created a new profile, then tried to change every setting related to scrolling but without success. Haven't tried with mouse yet. Scrolling speed in Floorp is way faster than in any other app. Video shows comparison between Firefox 115.9.1esr and Floorp 11.12.2 scrolling speed on touchpad.

### Reproduction Steps

1. Open Floorp 11.12.0 and visit floorp.app website
2. Open Firefox 115.9.1esr and visit floorp.app website
3. Try to scroll with touchpad

### Expected Behavior

Scrolling speed in Floorp is same as in every other application

### Actual Behavior

Scrolling speed in Floorp is way faster than in any other application

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/41486169/b0577cc1-b88d-44ed-862e-2d12318f3b65

### Browser Version

11.12.0

### Operating System

macOS Ventura 13.0

**Comment by n-crespo** [comment]
One temporary workaround is editing these values in about:config

for trackpad scrolling: `mousewheel.default.delta_multiplier_y   125` (or any other low value)
for scrollwheel scrolling:  `mousewheel.min_line_scroll_amount	50` (or any other low value)

**Comment by n-crespo** [comment]
In fact, all of the about:config values that were edited to change the scrolling are in the "Enable Smooth scrolling" commit, here they are: 

pref("apz.overscroll.enabled", true);
pref("general.smoothScroll", true);
pref("general.smoothScroll.msdPhysics.enabled", true);
pref("general.smoothScroll.currentVelocityWeighting", "0.15");
pref("general.smoothScroll.stopDecelerationWeighting", "0.6");
pref("mousewheel.min_line_scroll_amount", 10);
pref("general.smoothScroll.mouseWheel.durationMinMS", 80);
pref("general.smoothScroll.msdPhysics.continuousMotionMaxDeltaMS", 12);
pref("general.smoothScroll.msdPhysics.motionBeginSpringConstant", 600);
pref("general.smoothScroll.msdPhysics.regularSpringConstant", 650);
pref("general.smoothScroll.msdPhysics.slowdownMinDeltaMS", 25);
pref("general.smoothScroll.msdPhysics.slowdownSpringConstant", 250);
pref("mousewheel.default.delta_multiplier_y", 300);

**Comment by sergeyshadok** [comment]
> One temporary workaround is editing these values in about:config
> 
> for trackpad scrolling: `mousewheel.default.delta_multiplier_y 125` (or any other low value) for scrollwheel scrolling: `mousewheel.min_line_scroll_amount 50` (or any other low value)

@n-crespo it worked, thank you!

**Comment by CutterKnife** [comment]
They are in the process of adjusting the settings in stages as scrolling issues have been reported on non macOS platforms.
Presumably macOS will be excluded from this change in the future.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by ndqcdd** [comment]
How to save the edited pref. Each time the browser is restarted, the changed position takes on the default value
