### ISSUE TITLE
[Bug]: Web Apps Menu does not work. 

### ISSUE THREAD

**Issue by celozzip** [Floorp-Projects/Floorp#1100]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Web Apps Menu does not work. No Web Apps are listed.

### Reproduction Steps

1. Open Application Menu
2. Click Web Apps

### Expected Behavior

A list of installed web apps should appear.

### Actual Behavior

Nothing happens.

### Screenshots

![webapps](https://github.com/Floorp-Projects/Floorp/assets/127433056/eb3d963a-023f-4176-acb2-6b1bd5efa35c)

### Browser Version

11.12.0 (64-bit)

### Operating System

Windows 10 19045.4291

### Additional Context

Worked fine until the latest update. Noticed it was not working right after I updated the browser.

**Comment by surapunoyousei** [comment]
please provide console error. There is no same report.

**Comment by celozzip** [comment]
Uncaught ReferenceError: gSsbChromeManager is not defined
    oncommand chrome://browser/content/browser.xhtml:1

that's when i click the web apps menu, is that all you need?

**Comment by celozzip** [comment]
no, that's the other issue i filed. when i click anything in the design settings page nothing comes up in the console.

**Comment by surapunoyousei** [comment]
Thank you very much.

Last but not least, can you please submit all the screenshots of the entire console output?

**Comment by celozzip** [comment]
![console](https://github.com/Floorp-Projects/Floorp/assets/127433056/89e67ae9-649d-44af-9c4c-0323ac973799)

**Comment by surapunoyousei** [comment]
Thank you very much. It appears that this update is all about the custom shortcut keys being broken.

I will fix the bug based on your console output and release a fixed version tomorrow.

**Comment by celozzip** [comment]
just updated floorp. it's broken again...
