### ISSUE TITLE
[Bug]: Browser appearance option do not work

### ISSUE THREAD

**Issue by celozzip** [Floorp-Projects/Floorp#1101]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

"Browser appearance" options in the "Design preferences" page do not have any effect. Specifically changing from Proton UI to Photon UI and changing the Lepton Settings such as "Use Photon design" "Use Lepton design" do not have any effect. 

### Reproduction Steps

1. Open about:preferences#design
2. Change Browser appearance by selecting one of the options 
3. Nothing happens.

### Expected Behavior

The browser tab bar and general design should change style when selecting a different design style from the page.

### Actual Behavior

Nothing happens.

### Screenshots

![design](https://github.com/Floorp-Projects/Floorp/assets/127433056/7dd3420f-0d6d-4a6c-9e45-182d3893465f)

### Browser Version

11.12.0 (64-bit)

### Operating System

Windows 10 19045.4291

### Additional Context

The browser seems to be stuck on "Proton UI" which I noticed because I use "Lepton UI" and when I installed the new update it changed to Proton and I can't change it back.

**Comment by ThinkSalat** [comment]
I'm having problems with the display as well. The top tab bar is showing up even though I have the optimize for vertical sidebar option checked. I even selected vertical tabs in the Tab Bar Style options and no change. A bug seems to have slipped into the latest version


![image](https://github.com/Floorp-Projects/Floorp/assets/31082405/87f56927-3f1b-4295-9faf-7ad5f8e5fe76)

**Comment by surapunoyousei** [comment]
Could you provide console outputs?
