### ISSUE TITLE
[Bug]: Error when updating or installing floorp on Debian sid

### ISSUE THREAD

**Issue by stilgarwolf** [Floorp-Projects/Floorp#1104]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

apt reports errors when upgrading Floorp to 11.12.00 (64 bit).
Also, apt reports errors when installing Floorp, but Floorp is installed and is working

### Reproduction Steps

1. apt update
2. apt upgrade

### Expected Behavior

upgrade floorp

### Actual Behavior

Floorp upgraded to 11.12.0 (64-bit), but apt reported post-install errors.
I removed Floorp and installed it again (apt install floorp). Flpprp was installed and is working but with some errors were reported by apt.
I attached apt outputs for both install and upgrade

### Screenshots

#apt install floorp
Installing:
floorp

Suggested packages:
fonts-mplus

Summary:
Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 13
Download size: 0 B / 93.1 MB
Space needed: 301 MB / 9,642 MB available

Retrieving bug reports... Done
Parsing Found/Fixed information... Done
Selecting previously unselected package floorp.
(Reading database ... 294417 files and directories currently installed.)
Preparing to unpack .../floorp_11.12.0_amd64.deb ...
/var/lib/dpkg/tmp.ci/preinst: 61: [: Illegal number: n/a
Unpacking floorp (11.12.0) ...
Setting up floorp (11.12.0) ...

Thanks for contributing to Floorp!

Hojo Hinata
Twitter:@Hinata_Hojo

Thank you so much!

curl: (23) Failed writing received data to disk/application
dpkg: error processing package floorp (--configure):
installed floorp package post-installation script subprocess returned error exit status 23
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.27-2) ...
Errors were encountered while processing:
floorp
E: Sub-process /usr/bin/dpkg returned an error code (1)
#
#
#apt upgrade
Installing:
floorp

Suggested packages:
fonts-mplus

Summary:
Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 13
Download size: 0 B / 93.1 MB
Space needed: 301 MB / 9,642 MB available

Retrieving bug reports... Done
Parsing Found/Fixed information... Done
Selecting previously unselected package floorp.
(Reading database ... 294417 files and directories currently installed.)
Preparing to unpack .../floorp_11.12.0_amd64.deb ...
/var/lib/dpkg/tmp.ci/preinst: 61: [: Illegal number: n/a
Unpacking floorp (11.12.0) ...
Setting up floorp (11.12.0) ...

Thanks for contributing to Floorp!

Hojo Hinata
Twitter:@Hinata_Hojo

Thank you so much!

curl: (23) Failed writing received data to disk/application
dpkg: error processing package floorp (--configure):
installed floorp package post-installation script subprocess returned error exit status 23
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.27-2) ...
Errors were encountered while processing:
floorp
E: Sub-process /usr/bin/dpkg returned an error code (1)
#

### Browser Version

11.12.0 (64-bit)

### Operating System

Debian sid

**Comment by surapunoyousei** [comment]
@creeper-0910

**Comment by creeper-0910** [comment]
I cannot reproduce this problem...
Please try deleting the apt cache or download and install the deb file.

**Comment by stilgarwolf** [comment]
It's a curl bug (on some systems?) and it does not affect Floorp installation:

https://github.com/curl/curl/issues/13212

Removing "--compressed" option from floorp.postinstall script solves the error.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by creeper-0910** [comment]
Okay, thank you for the information!
