### ISSUE TITLE
[Bug]: Auto Hiding Bookmark Toolbar Issues

### ISSUE THREAD

**Issue by harukayamazaki** [Floorp-Projects/Floorp#1107]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

In the previous releases I took advantage of the "Hide the Bookmarks Toolbar unless hovering over the navigation bar" feature and it worked great. The sensitivity was set to only activate when the mouse cursor was directly on the search/url box. However in the latest release the sensitivity of this feature causes to active before reaching the search/url box. This becomes an issue if you use Browser Manager Sidebar for websites. The Hide Bookmarks Toolbar covers up the toolbar menu for the sidebar websites. Could you adjust the sensitivity or provide an option to set the sensitivity.

### Reproduction Steps

1. Enable "Hide the Bookmarks Toolbar unless hovering over the navigation bar" feature.
2. Add any website to your Browser Sidebar.
3. Load website from Browser Sidebar.
4. Try to use the back, forward, refresh or home buttons on its toolbar.
5. "Hide the Bookmarks Toolbar unless hovering over the navigation bar" will cover the toolbar

### Expected Behavior

Bookmarks Toolbar should show until your cursor is in the search/url box.

### Actual Behavior

Bookmarks Toolbar shows before your cursor reaches the search/url box.

### Screenshots

![Screenshot_20240418_195608](https://github.com/Floorp-Projects/Floorp/assets/60632993/3cdfd8c5-e514-4fca-8a56-09a42aaf8434)

### Browser Version

11.12.0 (64-bit)

### Operating System

Debian

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1097
Duplicate?
