### ISSUE TITLE
[Bug]: Usage of SSL send Floorp to quarantine

### ISSUE THREAD

**Issue by rlimaeco** [Floorp-Projects/Floorp#1108]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

 Usage of SSL (Microsoft) to connected account makes SentinelOne (cannot remove because it's a company PC) think the browser is unsafe a send Floorp to quarantine so with that cannot execute the browser anymore

### Reproduction Steps

- Open Floorp in windows
- Log in using SSL authentication
- SentinelOne should be executing in this machine and this will cause to send .exe to quarantine

### Expected Behavior

Be able to use SSL and use this awesome browser

### Actual Behavior

Cannot open Floorp anymore

### Screenshots

![photo_2024-04-19_18-04-09](https://github.com/Floorp-Projects/Floorp/assets/1217117/72278ffa-82b7-4ae9-8aa6-a0f6c690fa90)
![photo_2024-04-19_18-04-12](https://github.com/Floorp-Projects/Floorp/assets/1217117/684203f3-c422-43bd-aeb7-7936ba5a9f92)

### Browser Version

11.11.2

### Operating System

Windows 11

**Comment by TheChilledBuffalo** [comment]
Floorp can't do anything about this actually... You might want to contact your security service provider, SentinelOne in this case, and report a false positive.
