### ISSUE TITLE
[Bug]: tab bar options broken. sidebar broken

### ISSUE THREAD

**Issue by ThinkSalat** [Floorp-Projects/Floorp#1109]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

![image](https://github.com/Floorp-Projects/Floorp/assets/31082405/b0fb162a-e357-439d-8e2a-373bddd55527)

### Reproduction Steps

try to change tab bar behavior

### Expected Behavior

tab bar display options work - hides tab bar when optimized for vertical tabs

### Actual Behavior

![image](https://github.com/Floorp-Projects/Floorp/assets/31082405/ba99e6c9-33e9-488e-b8e7-8e3134c0b22f)

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/31082405/94541505-345d-401d-9211-78921e61b7c0)

### Browser Version

11.12.0

### Operating System

windows

### Additional Context

this was happening on the previous release as well. I installed the older release and then i got this new release and it happened again. please address this

**Comment by surapunoyousei** [comment]
Difficult to understand please provide more,info

**Comment by surapunoyousei** [comment]
Ok. It will fixed at 11.12.2
