### ISSUE TITLE
BST show with wrong position

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#111]
set `floorp.browser.sidebar.right` to false

![bst](https://user-images.githubusercontent.com/11323774/196138444-8159b6d9-710b-4c3c-a97e-985ad19d26bf.jpg)

**Comment by surapunoyousei** [comment]
Isee will fix it

**Comment by surapunoyousei** [comment]
Fixd https://github.com/Floorp-Projects/Floorp/commit/02ae0304192b5f8ea16d72f3f9c220247532b519
