### ISSUE TITLE
[Bug]: Floorp browsers refuses to build due errors on Compiling build-parallel v0.1.2

### ISSUE THREAD

**Issue by huakim** [Floorp-Projects/Floorp#1110]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

11:40.62    Compiling build-parallel v0.1.2
11:41.33 error[E0412]: cannot find type `SpliceableJSONWriter` in module `mozilla::baseprofiler`
11:41.33   --> tools/profiler/rust-api/src/gecko_bindings/glue.rs:18:46
11:41.33    |
11:41.33 18 |     json_writer: &mut mozilla::baseprofiler::SpliceableJSONWriter,
11:41.33    |                                              ^^^^^^^^^^^^^^^^^^^^ not found in `mozilla::baseprofiler`
11:41.34 error[E0412]: cannot find type `SpliceableJSONWriter` in module `mozilla::baseprofiler`
11:41.34   --> tools/profiler/rust-api/src/gecko_bindings/glue.rs:36:46
11:41.34    |
11:41.34 36 |     json_writer: &mut mozilla::baseprofiler::SpliceableJSONWriter,
11:41.34    |                                              ^^^^^^^^^^^^^^^^^^^^ not found in `mozilla::baseprofiler`
11:41.34 error[E0425]: cannot find function `gecko_profiler_marker_schema_stream` in module `bindings`
11:41.34   --> tools/profiler/rust-api/src/gecko_bindings/glue.rs:45:19
11:41.34    |
11:41.34 45 |         bindings::gecko_profiler_marker_schema_stream(
11:41.34    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.34 error[E0412]: cannot find type `SpliceableJSONWriter` in module `mozilla::baseprofiler`
11:41.34   --> tools/profiler/rust-api/src/json_writer.rs:13:58
11:41.34    |
11:41.34 13 | pub struct JSONWriter<'a>(&'a mut mozilla::baseprofiler::SpliceableJSONWriter);
11:41.35    |                                                          ^^^^^^^^^^^^^^^^^^^^ not found in `mozilla::baseprofiler`
11:41.35 error[E0412]: cannot find type `SpliceableJSONWriter` in module `mozilla::baseprofiler`
11:41.35   --> tools/profiler/rust-api/src/json_writer.rs:18:67
11:41.35    |
11:41.35 18 |     pub(crate) fn new(json_writer: &'a mut mozilla::baseprofiler::SpliceableJSONWriter) -> Self {
11:41.35    |                                                                   ^^^^^^^^^^^^^^^^^^^^ not found in `mozilla::baseprofiler`
11:41.36 error[E0425]: cannot find function `gecko_profiler_json_writer_int_property` in module `bindings`
11:41.36   --> tools/profiler/rust-api/src/json_writer.rs:26:23
11:41.36    |
11:41.36 26 |             bindings::gecko_profiler_json_writer_int_property(
11:41.36    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.36 error[E0425]: cannot find function `gecko_profiler_json_writer_float_property` in module `bindings`
11:41.36   --> tools/profiler/rust-api/src/json_writer.rs:39:23
11:41.36    |
11:41.37 39 |             bindings::gecko_profiler_json_writer_float_property(
11:41.37    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.37 error[E0425]: cannot find function `gecko_profiler_json_writer_bool_property` in module `bindings`
11:41.37   --> tools/profiler/rust-api/src/json_writer.rs:52:23
11:41.37    |
11:41.37 52 |             bindings::gecko_profiler_json_writer_bool_property(
11:41.37    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.37 error[E0425]: cannot find function `gecko_profiler_json_writer_string_property` in module `bindings`
11:41.37   --> tools/profiler/rust-api/src/json_writer.rs:65:23
11:41.37    |
11:41.38 65 |             bindings::gecko_profiler_json_writer_string_property(
11:41.38    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.38 error[E0425]: cannot find function `gecko_profiler_json_writer_null_property` in module `bindings`
11:41.38   --> tools/profiler/rust-api/src/json_writer.rs:79:23
11:41.38    |
11:41.38 79 |             bindings::gecko_profiler_json_writer_null_property(
11:41.38    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.38 error[E0412]: cannot find type `AutoProfilerLabel` in module `mozilla`
11:41.38   --> tools/profiler/rust-api/src/label.rs:19:51
11:41.38    |
11:41.38 19 | pub struct AutoProfilerLabel<'a>(&'a mut mozilla::AutoProfilerLabel);
11:41.38    |                                                   ^^^^^^^^^^^^^^^^^ not found in `mozilla`
11:41.39    |
11:41.39 help: consider importing this struct through its public re-export
11:41.39    |
11:41.39 10 + use crate::AutoProfilerLabel;
11:41.39    |
11:41.39 help: if you import `AutoProfilerLabel`, refer to it directly
11:41.39    |
11:41.39 19 - pub struct AutoProfilerLabel<'a>(&'a mut mozilla::AutoProfilerLabel);
11:41.39 19 + pub struct AutoProfilerLabel<'a>(&'a mut AutoProfilerLabel);
11:41.39    |
11:41.39 error[E0412]: cannot find type `AutoProfilerLabel` in module `mozilla`
11:41.40   --> tools/profiler/rust-api/src/label.rs:29:52
11:41.40    |
11:41.40 29 |         label: &mut std::mem::MaybeUninit<mozilla::AutoProfilerLabel>,
11:41.40    |                                                    ^^^^^^^^^^^^^^^^^ not found in `mozilla`
11:41.40    |
11:41.40 help: consider importing this struct through its public re-export
11:41.40    |
11:41.40 10 + use crate::AutoProfilerLabel;
11:41.40    |
11:41.40 help: if you import `AutoProfilerLabel`, refer to it directly
11:41.41    |
11:41.41 29 -         label: &mut std::mem::MaybeUninit<mozilla::AutoProfilerLabel>,
11:41.41 29 +         label: &mut std::mem::MaybeUninit<AutoProfilerLabel>,
11:41.41    |
11:41.41 error[E0425]: cannot find function `gecko_profiler_construct_label` in module `bindings`
11:41.41   --> tools/profiler/rust-api/src/label.rs:32:19
11:41.41    |
11:41.41 32 |         bindings::gecko_profiler_construct_label(
11:41.41    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.41 error[E0425]: cannot find function `gecko_profiler_destruct_label` in module `bindings`
11:41.41   --> tools/profiler/rust-api/src/label.rs:45:23
11:41.42    |
11:41.42 45 |             bindings::gecko_profiler_destruct_label(self.0);
11:41.42    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.42 error[E0412]: cannot find type `MarkerTiming` in module `mozilla`
11:41.42   --> tools/profiler/rust-api/src/marker/options.rs:23:57
11:41.42    |
11:41.42 23 | pub struct MarkerTiming(pub(crate) MaybeUninit<mozilla::MarkerTiming>);
11:41.42    |                                                         ^^^^^^^^^^^^ not found in `mozilla`
11:41.42    |
11:41.42 help: consider importing this struct through its public re-export
11:41.43    |
11:41.43 8  + use crate::MarkerTiming;
11:41.43    |
11:41.43 help: if you import `MarkerTiming`, refer to it directly
11:41.43    |
11:41.43 23 - pub struct MarkerTiming(pub(crate) MaybeUninit<mozilla::MarkerTiming>);
11:41.43 23 + pub struct MarkerTiming(pub(crate) MaybeUninit<MarkerTiming>);
11:41.43    |
11:41.43 error[E0412]: cannot find type `MarkerTiming` in module `mozilla`
11:41.43   --> tools/profiler/rust-api/src/marker/options.rs:28:56
11:41.43    |
11:41.43 28 |         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.43    |                                                        ^^^^^^^^^^^^ not found in `mozilla`
11:41.44    |
11:41.44 help: consider importing this struct through its public re-export
11:41.44    |
11:41.44 8  + use crate::MarkerTiming;
11:41.44    |
11:41.44 help: if you import `MarkerTiming`, refer to it directly
11:41.44    |
11:41.44 28 -         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.44 28 +         let mut marker_timing = MaybeUninit::<MarkerTiming>::uninit();
11:41.44    |
11:41.44 error[E0425]: cannot find function `gecko_profiler_construct_marker_timing_instant_at` in module `bindings`
11:41.44   --> tools/profiler/rust-api/src/marker/options.rs:30:23
11:41.45    |
11:41.45 30 |             bindings::gecko_profiler_construct_marker_timing_instant_at(
11:41.45    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.45 error[E0412]: cannot find type `MarkerTiming` in module `mozilla`
11:41.45   --> tools/profiler/rust-api/src/marker/options.rs:40:56
11:41.45    |
11:41.45 40 |         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.45    |                                                        ^^^^^^^^^^^^ not found in `mozilla`
11:41.45    |
11:41.45 help: consider importing this struct through its public re-export
11:41.45    |
11:41.46 8  + use crate::MarkerTiming;
11:41.46    |
11:41.46 help: if you import `MarkerTiming`, refer to it directly
11:41.46    |
11:41.46 40 -         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.46 40 +         let mut marker_timing = MaybeUninit::<MarkerTiming>::uninit();
11:41.46    |
11:41.46 error[E0425]: cannot find function `gecko_profiler_construct_marker_timing_instant_now` in module `bindings`
11:41.46   --> tools/profiler/rust-api/src/marker/options.rs:42:23
11:41.46    |
11:41.46 42 |             bindings::gecko_profiler_construct_marker_timing_instant_now(
11:41.46    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.46 error[E0412]: cannot find type `MarkerTiming` in module `mozilla`
11:41.47   --> tools/profiler/rust-api/src/marker/options.rs:51:56
11:41.47    |
11:41.47 51 |         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.47    |                                                        ^^^^^^^^^^^^ not found in `mozilla`
11:41.47    |
11:41.47 help: consider importing this struct through its public re-export
11:41.47    |
11:41.47 8  + use crate::MarkerTiming;
11:41.47    |
11:41.47 help: if you import `MarkerTiming`, refer to it directly
11:41.47    |
11:41.47 51 -         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.47 51 +         let mut marker_timing = MaybeUninit::<MarkerTiming>::uninit();
11:41.47    |
11:41.48 error[E0425]: cannot find function `gecko_profiler_construct_marker_timing_interval` in module `bindings`
11:41.48   --> tools/profiler/rust-api/src/marker/options.rs:53:23
11:41.48    |
11:41.48 53 |             bindings::gecko_profiler_construct_marker_timing_interval(
11:41.48    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.48 error[E0412]: cannot find type `MarkerTiming` in module `mozilla`
11:41.48   --> tools/profiler/rust-api/src/marker/options.rs:64:56
11:41.48    |
11:41.48 64 |         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.48    |                                                        ^^^^^^^^^^^^ not found in `mozilla`
11:41.48    |
11:41.48 help: consider importing this struct through its public re-export
11:41.48    |
11:41.48 8  + use crate::MarkerTiming;
11:41.48    |
11:41.48 help: if you import `MarkerTiming`, refer to it directly
11:41.48    |
11:41.48 64 -         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.48 64 +         let mut marker_timing = MaybeUninit::<MarkerTiming>::uninit();
11:41.48    |
11:41.48 error[E0425]: cannot find function `gecko_profiler_construct_marker_timing_interval_until_now_from` in module `bindings`
11:41.48   --> tools/profiler/rust-api/src/marker/options.rs:66:23
11:41.48    |
11:41.48 66 |             bindings::gecko_profiler_construct_marker_timing_interval_until_now_from(
11:41.48    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.48 error[E0412]: cannot find type `MarkerTiming` in module `mozilla`
11:41.49   --> tools/profiler/rust-api/src/marker/options.rs:77:56
11:41.49    |
11:41.49 77 |         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.49    |                                                        ^^^^^^^^^^^^ not found in `mozilla`
11:41.49    |
11:41.49 help: consider importing this struct through its public re-export
11:41.49    |
11:41.49 8  + use crate::MarkerTiming;
11:41.49    |
11:41.49 help: if you import `MarkerTiming`, refer to it directly
11:41.49    |
11:41.49 77 -         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.49 77 +         let mut marker_timing = MaybeUninit::<MarkerTiming>::uninit();
11:41.49    |
11:41.49 error[E0425]: cannot find function `gecko_profiler_construct_marker_timing_interval_start` in module `bindings`
11:41.49   --> tools/profiler/rust-api/src/marker/options.rs:79:23
11:41.49    |
11:41.49 79 |             bindings::gecko_profiler_construct_marker_timing_interval_start(
11:41.49    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.49 error[E0412]: cannot find type `MarkerTiming` in module `mozilla`
11:41.49   --> tools/profiler/rust-api/src/marker/options.rs:90:56
11:41.49    |
11:41.49 90 |         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.49    |                                                        ^^^^^^^^^^^^ not found in `mozilla`
11:41.49    |
11:41.49 help: consider importing this struct through its public re-export
11:41.50    |
11:41.50 8  + use crate::MarkerTiming;
11:41.50    |
11:41.50 help: if you import `MarkerTiming`, refer to it directly
11:41.50    |
11:41.50 90 -         let mut marker_timing = MaybeUninit::<mozilla::MarkerTiming>::uninit();
11:41.50 90 +         let mut marker_timing = MaybeUninit::<MarkerTiming>::uninit();
11:41.50    |
11:41.50 error[E0425]: cannot find function `gecko_profiler_construct_marker_timing_interval_end` in module `bindings`
11:41.50   --> tools/profiler/rust-api/src/marker/options.rs:92:23
11:41.50    |
11:41.50 92 |             bindings::gecko_profiler_construct_marker_timing_interval_end(
11:41.50    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.50 error[E0425]: cannot find function `gecko_profiler_destruct_marker_timing` in module `bindings`
11:41.50    --> tools/profiler/rust-api/src/marker/options.rs:110:23
11:41.50     |
11:41.50 110 |             bindings::gecko_profiler_destruct_marker_timing(self.0.as_mut_ptr());
11:41.50     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.50 error[E0412]: cannot find type `StackCaptureOptions` in module `mozilla`
11:41.50    --> tools/profiler/rust-api/src/marker/options.rs:116:33
11:41.50     |
11:41.50 116 | pub type MarkerStack = mozilla::StackCaptureOptions;
11:41.50     |                                 ^^^^^^^^^^^^^^^^^^^ not found in `mozilla`
11:41.50 error[E0412]: cannot find type `MarkerSchema_Location` in module `mozilla`
11:41.51   --> tools/profiler/rust-api/src/marker/schema.rs:14:30
11:41.51    |
11:41.52 14 | pub type Location = mozilla::MarkerSchema_Location;
11:41.52    |                              ^^^^^^^^^^^^^^^^^^^^^ not found in `mozilla`
11:41.52 error[E0412]: cannot find type `MarkerSchema_Format` in module `mozilla`
11:41.52   --> tools/profiler/rust-api/src/marker/schema.rs:17:28
11:41.52    |
11:41.52 17 | pub type Format = mozilla::MarkerSchema_Format;
11:41.52    |                            ^^^^^^^^^^^^^^^^^^^ not found in `mozilla`
11:41.52 error[E0412]: cannot find type `MarkerSchema_Searchable` in module `mozilla`
11:41.52   --> tools/profiler/rust-api/src/marker/schema.rs:20:32
11:41.52    |
11:41.52 20 | pub type Searchable = mozilla::MarkerSchema_Searchable;
11:41.53    |                                ^^^^^^^^^^^^^^^^^^^^^^^ not found in `mozilla`
11:41.53 error[E0412]: cannot find type `MarkerSchema` in module `mozilla`
11:41.53   --> tools/profiler/rust-api/src/marker/schema.rs:30:50
11:41.53    |
11:41.53 30 |     pub(crate) pin: Pin<Box<MaybeUninit<mozilla::MarkerSchema>>>,
11:41.53    |                                                  ^^^^^^^^^^^^ not found in `mozilla`
11:41.53    |
11:41.53 help: consider importing this struct through its public re-export
11:41.53    |
11:41.53 7  + use crate::MarkerSchema;
11:41.53    |
11:41.53 help: if you import `MarkerSchema`, refer to it directly
11:41.53    |
11:41.53 30 -     pub(crate) pin: Pin<Box<MaybeUninit<mozilla::MarkerSchema>>>,
11:41.53 30 +     pub(crate) pin: Pin<Box<MaybeUninit<MarkerSchema>>>,
11:41.53    |
11:41.54 error[E0412]: cannot find type `MarkerSchema` in module `mozilla`
11:41.54   --> tools/profiler/rust-api/src/marker/schema.rs:36:75
11:41.54    |
11:41.54 36 |         let mut marker_schema = Box::pin(std::mem::MaybeUninit::<mozilla::MarkerSchema>::uninit());
11:41.54    |                                                                           ^^^^^^^^^^^^ not found in `mozilla`
11:41.54    |
11:41.54 help: consider importing this struct through its public re-export
11:41.54    |
11:41.55 7  + use crate::MarkerSchema;
11:41.55    |
11:41.55 help: if you import `MarkerSchema`, refer to it directly
11:41.55    |
11:41.55 36 -         let mut marker_schema = Box::pin(std::mem::MaybeUninit::<mozilla::MarkerSchema>::uninit());
11:41.55 36 +         let mut marker_schema = Box::pin(std::mem::MaybeUninit::<MarkerSchema>::uninit());
11:41.55    |
11:41.56 error[E0425]: cannot find function `gecko_profiler_construct_marker_schema` in module `bindings`
11:41.56   --> tools/profiler/rust-api/src/marker/schema.rs:39:23
11:41.56    |
11:41.56 39 |             bindings::gecko_profiler_construct_marker_schema(
11:41.56    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.56 error[E0412]: cannot find type `MarkerSchema` in module `mozilla`
11:41.56   --> tools/profiler/rust-api/src/marker/schema.rs:51:75
11:41.56    |
11:41.56 51 |         let mut marker_schema = Box::pin(std::mem::MaybeUninit::<mozilla::MarkerSchema>::uninit());
11:41.57    |                                                                           ^^^^^^^^^^^^ not found in `mozilla`
11:41.57    |
11:41.57 help: consider importing this struct through its public re-export
11:41.57    |
11:41.57 7  + use crate::MarkerSchema;
11:41.57    |
11:41.57 help: if you import `MarkerSchema`, refer to it directly
11:41.57    |
11:41.58 51 -         let mut marker_schema = Box::pin(std::mem::MaybeUninit::<mozilla::MarkerSchema>::uninit());
11:41.58 51 +         let mut marker_schema = Box::pin(std::mem::MaybeUninit::<MarkerSchema>::uninit());
11:41.58    |
11:41.58 error[E0425]: cannot find function `gecko_profiler_construct_marker_schema_with_special_front_end_location` in module `bindings`
11:41.58   --> tools/profiler/rust-api/src/marker/schema.rs:53:23
11:41.58    |
11:41.58 53 |             bindings::gecko_profiler_construct_marker_schema_with_special_front_end_location(
11:41.58    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.58 error[E0425]: cannot find function `gecko_profiler_marker_schema_set_chart_label` in module `bindings`
11:41.59   --> tools/profiler/rust-api/src/marker/schema.rs:66:23
11:41.59    |
11:41.59 66 |             bindings::gecko_profiler_marker_schema_set_chart_label(
11:41.59    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.59 error[E0425]: cannot find function `gecko_profiler_marker_schema_set_tooltip_label` in module `bindings`
11:41.59   --> tools/profiler/rust-api/src/marker/schema.rs:81:23
11:41.59    |
11:41.59 81 |             bindings::gecko_profiler_marker_schema_set_tooltip_label(
11:41.59    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.59 error[E0425]: cannot find function `gecko_profiler_marker_schema_set_table_label` in module `bindings`
11:41.59   --> tools/profiler/rust-api/src/marker/schema.rs:96:23
11:41.60    |
11:41.60 96 |             bindings::gecko_profiler_marker_schema_set_table_label(
11:41.60    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.60 error[E0425]: cannot find function `gecko_profiler_marker_schema_set_all_labels` in module `bindings`
11:41.63    --> tools/profiler/rust-api/src/marker/schema.rs:111:23
11:41.63     |
11:41.63 111 |             bindings::gecko_profiler_marker_schema_set_all_labels(
11:41.63     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.63 error[E0425]: cannot find function `gecko_profiler_marker_schema_add_key_format` in module `bindings`
11:41.63    --> tools/profiler/rust-api/src/marker/schema.rs:134:23
11:41.66     |
11:41.66 134 |             bindings::gecko_profiler_marker_schema_add_key_format(
11:41.66     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.66 error[E0425]: cannot find function `gecko_profiler_marker_schema_add_key_label_format` in module `bindings`
11:41.67    --> tools/profiler/rust-api/src/marker/schema.rs:150:23
11:41.67     |
11:41.67 150 |             bindings::gecko_profiler_marker_schema_add_key_label_format(
11:41.67     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.67 error[E0425]: cannot find function `gecko_profiler_marker_schema_add_key_format_searchable` in module `bindings`
11:41.67    --> tools/profiler/rust-api/src/marker/schema.rs:172:23
11:41.67     |
11:41.67 172 |             bindings::gecko_profiler_marker_schema_add_key_format_searchable(
11:41.67     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.67 error[E0425]: cannot find function `gecko_profiler_marker_schema_add_key_label_format_searchable` in module `bindings`
11:41.67    --> tools/profiler/rust-api/src/marker/schema.rs:197:23
11:41.67     |
11:41.67 197 |             bindings::gecko_profiler_marker_schema_add_key_label_format_searchable(
11:41.68     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.68 error[E0425]: cannot find function `gecko_profiler_marker_schema_add_static_label_value` in module `bindings`
11:41.68    --> tools/profiler/rust-api/src/marker/schema.rs:215:23
11:41.68     |
11:41.68 215 |             bindings::gecko_profiler_marker_schema_add_static_label_value(
11:41.68     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.68 error[E0425]: cannot find function `gecko_profiler_destruct_marker_schema` in module `bindings`
11:41.68    --> tools/profiler/rust-api/src/marker/schema.rs:230:23
11:41.68     |
11:41.69 230 |             bindings::gecko_profiler_destruct_marker_schema(self.pin.deref_mut().as_mut_ptr());
11:41.69     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.69 error[E0425]: cannot find function `gecko_profiler_add_marker_untyped` in module `bindings`
11:41.69    --> tools/profiler/rust-api/src/marker/mod.rs:143:19
11:41.69     |
11:41.69 143 |         bindings::gecko_profiler_add_marker_untyped(
11:41.69     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.69 error[E0425]: cannot find function `gecko_profiler_add_marker_text` in module `bindings`
11:41.69    --> tools/profiler/rust-api/src/marker/mod.rs:167:19
11:41.69     |
11:41.69 167 |         bindings::gecko_profiler_add_marker_text(
11:41.69     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.69 error[E0425]: cannot find function `gecko_profiler_add_marker` in module `bindings`
11:41.69    --> tools/profiler/rust-api/src/marker/mod.rs:240:19
11:41.69     |
11:41.69 240 |         bindings::gecko_profiler_add_marker(
11:41.69     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.69 error[E0425]: cannot find function `gecko_profiler_register_thread` in module `bindings`
11:41.69   --> tools/profiler/rust-api/src/thread.rs:14:19
11:41.69    |
11:41.69 14 |         bindings::gecko_profiler_register_thread(name.as_ptr());
11:41.69    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.69 error[E0425]: cannot find function `gecko_profiler_unregister_thread` in module `bindings`
11:41.70   --> tools/profiler/rust-api/src/thread.rs:21:19
11:41.70    |
11:41.70 21 |         bindings::gecko_profiler_unregister_thread();
11:41.70    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.70 error[E0412]: cannot find type `TimeStamp` in module `mozilla`
11:41.70   --> tools/profiler/rust-api/src/time.rs:27:45
11:41.70    |
11:41.70 27 | pub struct ProfilerTime(pub(crate) mozilla::TimeStamp);
11:41.70    |                                             ^^^^^^^^^ not found in `mozilla`
11:41.70 error[E0412]: cannot find type `TimeStamp` in module `mozilla`
11:41.70   --> tools/profiler/rust-api/src/time.rs:31:56
11:41.70    |
11:41.70 31 |         let mut marker_timing = MaybeUninit::<mozilla::TimeStamp>::uninit();
11:41.70    |                                                        ^^^^^^^^^ not found in `mozilla`
11:41.70 error[E0425]: cannot find function `gecko_profiler_construct_timestamp_now` in module `bindings`
11:41.70   --> tools/profiler/rust-api/src/time.rs:33:23
11:41.70    |
11:41.70 33 |             bindings::gecko_profiler_construct_timestamp_now(marker_timing.as_mut_ptr());
11:41.70    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.70 error[E0412]: cannot find type `TimeStamp` in module `mozilla`
11:41.70   --> tools/profiler/rust-api/src/time.rs:39:47
11:41.70    |
11:41.70 39 |         let mut dest = MaybeUninit::<mozilla::TimeStamp>::uninit();
11:41.70    |                                               ^^^^^^^^^ not found in `mozilla`
11:41.71 error[E0425]: cannot find function `gecko_profiler_add_timestamp` in module `bindings`
11:41.71   --> tools/profiler/rust-api/src/time.rs:41:23
11:41.71    |
11:41.71 41 |             bindings::gecko_profiler_add_timestamp(&self.0, dest.as_mut_ptr(), microseconds);
11:41.71    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.71 error[E0412]: cannot find type `TimeStamp` in module `mozilla`
11:41.71   --> tools/profiler/rust-api/src/time.rs:47:47
11:41.71    |
11:41.71 47 |         let mut dest = MaybeUninit::<mozilla::TimeStamp>::uninit();
11:41.71    |                                               ^^^^^^^^^ not found in `mozilla`
11:41.71 error[E0425]: cannot find function `gecko_profiler_subtract_timestamp` in module `bindings`
11:41.71   --> tools/profiler/rust-api/src/time.rs:49:23
11:41.71    |
11:41.71 49 |             bindings::gecko_profiler_subtract_timestamp(&self.0, dest.as_mut_ptr(), microseconds);
11:41.71    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.71 error[E0412]: cannot find type `TimeStamp` in module `mozilla`
11:41.71   --> tools/profiler/rust-api/src/time.rs:57:47
11:41.71    |
11:41.71 57 |         let mut dest = MaybeUninit::<mozilla::TimeStamp>::uninit();
11:41.71    |                                               ^^^^^^^^^ not found in `mozilla`
11:41.71 error[E0425]: cannot find function `gecko_profiler_clone_timestamp` in module `bindings`
11:41.71   --> tools/profiler/rust-api/src/time.rs:59:23
11:41.71    |
11:41.71 59 |             bindings::gecko_profiler_clone_timestamp(&self.0, dest.as_mut_ptr());
11:41.72    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.72 error[E0425]: cannot find function `gecko_profiler_destruct_timestamp` in module `bindings`
11:41.72   --> tools/profiler/rust-api/src/time.rs:68:23
11:41.72    |
11:41.72 68 |             bindings::gecko_profiler_destruct_timestamp(&mut self.0);
11:41.72    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`
11:41.72 warning: unused import: `schema::MarkerSchema`
11:41.72    --> tools/profiler/rust-api/src/marker/mod.rs:125:9
11:41.72     |
11:41.72 125 | pub use schema::MarkerSchema;
11:41.72     |         ^^^^^^^^^^^^^^^^^^^^
11:41.72     |
11:41.72     = note: `#[warn(unused_imports)]` on by default
11:41.72 warning: private item shadows public glob re-export
11:41.72    --> tools/profiler/rust-api/src/marker/mod.rs:130:5
11:41.72     |
11:41.72 130 | use crate::marker::options::MarkerOptions;
11:41.72     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:41.72     |
11:41.72 note: the name `MarkerOptions` in the type namespace is supposed to be publicly re-exported here
11:41.72    --> tools/profiler/rust-api/src/marker/mod.rs:124:9
11:41.72     |
11:41.72 124 | pub use options::*;
11:41.72     |         ^^^^^^^^^^
11:41.72 note: but the private item here shadows it
11:41.72    --> tools/profiler/rust-api/src/marker/mod.rs:130:5
11:41.73     |
11:41.73 130 | use crate::marker::options::MarkerOptions;
11:41.73     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:41.73     = note: `#[warn(hidden_glob_reexports)]` on by default
11:41.73    Compiling peek-poke v0.3.0 (/extra/home/suse/Desktop/local/gitfetch/floorp/src/floorp-11.12.1/gfx/wr/peek-poke)
11:41.73 Some errors have detailed explanations: E0412, E0425.
11:41.73 For more information about an error, try `rustc --explain E0412`.
11:41.73 warning: `gecko-profiler` (lib) generated 2 warnings
11:41.73 error: could not compile `gecko-profiler` (lib) due to 62 previous errors; 2 warnings emitted

### Reproduction Steps

1. try to build browser

### Expected Behavior

1. expected browser to be built

### Actual Behavior

1. raises error

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/92579808/1ecb3ab9-a389-4b58-b55c-d74f2133551d)

### Browser Version

11.12.1

### Operating System

openSuSE

**Comment by surapunoyousei** [comment]
On Floorp, We refuse build error issue due to resource.
