### ISSUE TITLE
Floorp cannot run Enhancer for YouTube™ extension

### ISSUE THREAD

**Issue by noahnao** [Floorp-Projects/Floorp#1112]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I get an error message when I try to install the extension called Enhancer for YouTube™.
Pls fix.

### Reproduction Steps

1. Go to:
https://addons.mozilla.org/ja/firefox/addon/enhancer-for-youtube/
2. Try to download and install the extension

### Expected Behavior

The extension is download and Installed correctly.

### Actual Behavior

Enhancer for YouTube™ could not be installed because, it's not compatible with Floorp 115.10.0

### Screenshots

![Skærmbillede 2024-04-20 180519](https://github.com/Floorp-Projects/Floorp/assets/81416193/badda925-9d95-4c87-b16a-dd713b3ccf89)

### Browser Version

11.12.1

### Operating System

Windows 11

### Additional Context

I think it is caused by Floorp being a fork of an outdated version of Firefox, if so will Floorp migrate to a newer version, if so when?

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/discussions/1094
