### ISSUE TITLE
[Bug]: post-install error on debian when updating from ppa

### ISSUE THREAD

**Issue by therealfumbles** [Floorp-Projects/Floorp#1113]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Since 11.12 I get this curl error after the floorp update. I have also tried removing floorp and reinstalling but the error continues.

Setting up floorp (11.12.2) ...
----------------------------------------
Thanks for contributing to Floorp! 

Hojo Hinata
	Twitter:@Hinata_Hojo

Thank you so much!
----------------------------------------
curl: (23) Failed writing received data to disk/application
dpkg: error processing package floorp (--configure):
 installed floorp package post-installation script subprocess returned error exit status 23

### Reproduction Steps

Update or install floorp from the ppa via apt

### Expected Behavior

There should be no error once the update or install completes. There was no error prior to 11.12.

### Actual Behavior

Error is shown at the end of the apt process. Browser seems to work fine.

### Screenshots

![Screenshot from 2024-04-21 14-52-51](https://github.com/Floorp-Projects/Floorp/assets/86084089/a7530d29-aa5e-447a-8e3b-3f78bd325ada)

### Browser Version

Floorp 11.12.2

### Operating System

debian sid x86-64

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1104 duplicate
