### ISSUE TITLE
[Bug]: Workspaces broken on 11.12.2 (ChaoticAUR build only)

### ISSUE THREAD

**Issue by LFd3v** [Floorp-Projects/Floorp#1123]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

First of all, thank you a lot for creating and maintaining Floorp!

After upgrading to 11.2.2, Floorp lost all my Workspaces configuration and the feature does not work anymore, only a blank Default workspace is available when Floorp is started.

### Reproduction Steps

1. Upgrade to Floorp 11.12.2
2. Notice all workspaces and respective tabs are gone
3. Notice only Default workspace is available
4. Create a new workspace
5. Restart Floorp
6. Again, only Default workspace is available

### Expected Behavior

Floorp should not loose Workspaces configuration after upgrading, and the feature should work as expected in 11.12.1.

### Actual Behavior

All Workspaces and Tabs are gone (minus the pinned ones) after updating to 11.12.2 and Workspaces configuration tabs is reset every time the browser is started.

### Screenshots

N/D

### Browser Version

11.12.2

### Operating System

ArchLinux/Garuda

### Additional Context

- Workspaces feature does not work with a brand new profile, so it does not seem to be a configuration/profile issue
- No errors are shown when starting Floorp from the terminal
- A new "Default" entry is created in [profile]/Workspaces/Workspaces.json every time the browser is started

**Comment by LFd3v** [comment]
It seems that the problem only happens with the ChaoticAUR build. I have tested both the tarball and the AUR build and they seem to work fine.

Sorry for the noise. Thanks again.

Regards

**Comment by GlitterMonster** [comment]
> It seems that the problem only happens with the ChaoticAUR build. I have tested both the tarball and the AUR build (floorp-bin) and they seem to work fine.
> 
> Sorry for the noise. Thanks again.
> 
> Regards

2025 here...this is still happening in the AUR version, not just chaotic.  I'm on version 12.5.0.
