### ISSUE TITLE
[Bug]: You can't assign shortcut that includes a some symbol

### ISSUE THREAD

**Issue by Majoramari** [Floorp-Projects/Floorp#1125]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

You can't assgin shortcuts like (Modifier + *some symbols)

that inlcudes: 
- CTRL + =
- CTRL + -
- SHIFT + \
- SHIFT + `
- SHIFT + '
- etc...

### Reproduction Steps

1. Go to settings > shortcuts
2. Disable firefox shortcuts then restart the browser
3. Press add shortcut > start listenting, and try to add any shortcut that includes a symbel (e.g = - ' \ `) for example (CTRL + =)

Video example:
https://github.com/Floorp-Projects/Floorp/assets/33487552/38f68ba3-4267-4779-8f49-05aa75f924d7

### Expected Behavior

It should accept the shortcut as CTRL+= as any normal shortcut

### Actual Behavior

It seems to accept any shortcut that doesn't include some symbols!

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/33487552/df500f25-8616-4038-8c98-c61b1d634584)
![image](https://github.com/Floorp-Projects/Floorp/assets/33487552/17e7273a-2883-453b-a156-b5a983ac8acf)

### Browser Version

11.12.2

### Operating System

Windows 11 pro version 23H2 Build 22631.3447

### Additional Context

Its an old issue with me but I didn't want to bother you guys with it I thought anyone will notice something important like this so I didn't use floorp for months because of it + already asked on the discord server no one answer!

**Comment by surapunoyousei** [comment]
Floorp disables some symbols to maintain cross-platform compatibility. Thank you for your understanding.

**Comment by Gambloide** [comment]
> Floorp disables some symbols to maintain cross-platform compatibility. Thank you for your understanding.

Please communicate this in the user-interface then!

It should either list what you cannot use, or at least tell you that the combination you are trying to use is blocked for compatibility reasons (even though that whole idea doesn't make much sense).

I have spent a good chunk of time on two separate days now, trying to figure out why I cannot setup shortcuts based on e.g. the F-keys plus modifiers in Floorp, only to stumble across this closed issue now.
