### ISSUE TITLE
[Bug]: WhatsApp Web (web.whatsapp.com) doesn't work in Private Window

### ISSUE THREAD

**Issue by muntasimulhaque** [Floorp-Projects/Floorp#1130]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

WhatsApp Web (web.whatsapp.com) doesn't work in Private Window. Though it works fine in the normal window. 

![image](https://github.com/Floorp-Projects/Floorp/assets/106990977/9f73e77c-29dd-466a-9275-24aaea1d8d39)

### Reproduction Steps

1. Open Floorp Private Window
2. Go to web.whatsapp.com
3. The QR code doesn't load at all.

### Expected Behavior

The QR code should load and be visible to scan it through mobile phone.

### Actual Behavior

The QR code doesn't load. It keeps spinning.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/106990977/0baa2a88-d46a-4529-bb98-37dc13305b48)

### Browser Version

11.12.2 (64-bit)

### Operating System

Windows 10  Pro 22H2

**Comment by surapunoyousei** [comment]
Did you disable tracker blocker on the page?

**Comment by muntasimulhaque** [comment]
> Did you disable tracker blocker on the page?

Yes. I disabled both Enhanced tracking protection and uBlock Origin. But the issue still persists.

**Comment by surapunoyousei** [comment]
You checked "I have tried to create a new profile and the issue still occurs." Did you actually try do that?

**Comment by muntasimulhaque** [comment]
> You checked "I have tried to create a new profile and the issue still occurs." Did you actually try do that?

Yes. I created a new profile but the issue persists. But as I said, the issue is with private windows only. 

I think you should be able to reproduce the issue in private windows.

**Comment by TheChilledBuffalo** [comment]
@muntasimulhaque I see that you have checked "I have checked this problem is not occurring in the latest version of Firefox ESR" in the checklist. But did you actually do that? Please do not check the options if you haven't done it. It makes it a lot more difficult to identify from where the issue arises. This issue occurs in Firefox ESR as well.

**Comment by creeper-0910** [comment]
Perhaps this is a problem with indexedDB.
It seems to be fixed in Firefox 125 and later, but since Floorp is ESR based, it will be difficult to fix until the next ESR release.
https://bugzilla.mozilla.org/show_bug.cgi?id=1767407

**Comment by muntasimulhaque** [comment]
> Floorp has a private container feature that can be used in place of a private window.
> 
> It can reopen tab from tab context menu.

Surprisingly, it works in private container tab. That's a temporary fix, but a solution nonetheless. Thanks 😊
