### ISSUE TITLE
[Bug]: Floorp 11.12.2 failed to generate PGO with python 3.12.3

### ISSUE THREAD

**Issue by Brli** [Floorp-Projects/Floorp#1131]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp failed to properly generate pgo profile under Arch with python version 3.12.3

### Reproduction Steps

1. git clone floorp from aur
2. use 11.2.1 as base, and change version
3. run makepkg/makechrootpkg

### Expected Behavior

pass the build and the zst tarball generated.

### Actual Behavior

build abort with error

### Screenshots

```
 0:18.99 make: Leaving directory '/build/floorp/src/Floorp-11.12.2/obj'
  Parallelism determined by memory: using 16 jobs for 16 cores based on 62.7 GiB RAM and estimated job size of 1.0 GiB
Traceback (most recent call last):
  File "/build/floorp/src/Floorp-11.12.2/build/pgo/profileserver.py", line 19, in <module>
    from mozrunner import CLI, FirefoxRunner
  File "/build/floorp/src/Floorp-11.12.2/testing/mozbase/mozrunner/mozrunner/__init__.py", line 6, in <module>
    import mozrunner.base
  File "/build/floorp/src/Floorp-11.12.2/testing/mozbase/mozrunner/mozrunner/base/__init__.py", line 6, in <module>
    from .browser import BlinkRuntimeRunner, GeckoRuntimeRunner
  File "/build/floorp/src/Floorp-11.12.2/testing/mozbase/mozrunner/mozrunner/base/browser.py", line 11, in <module>
    from ..application import DefaultContext, FirefoxContext
  File "/build/floorp/src/Floorp-11.12.2/testing/mozbase/mozrunner/mozrunner/application.py", line 8, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
Site not up-to-date reason: "/build/floorp/src/Floorp-11.12.2/obj/_virtualenvs/common" does not exist
[1m[31m==> ERROR:[m[1m A failure occurred in build().[m
[1m    Aborting...[m
```

### Browser Version

11.2.2

### Operating System

Arch Linux

### Additional Context

- cause of error lines: https://github.com/Floorp-Projects/Floorp/blob/ESR115/testing/mozbase/mozrunner/mozrunner/application.py#L8C1-L8C44

- deprecation notice: https://peps.python.org/pep-0632/

- possible fix from debian https://sources.debian.org/src/mozjs102/102.15.1-5/debian/patches/fix-Python-3.12-incompatibilities-harder.patch/

**Comment by surapunoyousei** [comment]
We are sorry. We cannot support issues relating to building. Close issue

**Comment by Brli** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1866829
https://bugzilla.mozilla.org/show_bug.cgi?id=1887281
https://bugzilla.mozilla.org/show_bug.cgi?id=1893961
please at least cherry pick these three commits.
