### ISSUE TITLE
[Bug]: 日本語のユーザー名を使用しているとPWAを起動できない

### ISSUE THREAD

**Issue by gensokyo-kenken** [Floorp-Projects/Floorp#1132]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

PWAをスタートメニューやタスクバーから起動できません。

### Reproduction Steps

このバグを再現するには、マルチバイト文字が含まれるユーザー名を使用しているユーザーでFloorpを実行する必要があります。
1. PWAに対応したサイトで「このサイトをアプリとしてインストール」を実行
2. スタートメニューからPWAを起動

### Expected Behavior

PWAが起動する

### Actual Behavior

「あなたの Floorp プロファイルを読み込めませんでした。プロファイルが存在しないかアクセスできません。」と表示され、PWAが起動できません。
対応するショートカットのプロパティを表示すると、-profileに続くファイルパスのユーザー名の部分が文字化けしています。

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/51988985/654569bb-c320-430b-9dec-48258004a0ed)
![image](https://github.com/Floorp-Projects/Floorp/assets/51988985/44a8135c-c6b7-442a-8233-ff0df3da9704)

### Browser Version

115.10.0

### Operating System

Windows 10

### Additional Context

ショートカット内のファイルパスの文字化けしている部分にユーザー名を入力すると通常通り起動するようになります。

**Comment by surapunoyousei** [comment]
I don't like Japanese.

**Comment by surapunoyousei** [comment]
@nyanrus 氏の調査により、JS の問題ではなく、DOMString を AString への変換を Windows が正常に行えていないことがわかりました。

Windows 側の問題なのでこちら側で提案できる解決策はありませんが、プロファイルを切り替えてしまうと機能しなくなる最小はあるものの代替策として、コマンドライン引数からプロファイルの指定を削除することで解決できます。

申し訳ありませんが、修正できません。

**Comment by nyanrus** [comment]
この問題についてMozillaに提出したところ、Firefoxの問題であることがMozilla側で確認されました。
https://bugzilla.mozilla.org/show_bug.cgi?id=1894865

Floorpでの解決時期は、少なくとも今のESR版がサポート終了される10月1日までに解決されます。
https://whattrainisitnow.com/release/?version=esr

気長にお待ち下さい。
これからもFloorpをよろしくお願いします。
