### ISSUE TITLE
[Bug]: Floorp instruction error 0x00007FFC43478546 when using Mirillis Action! in the background.

### ISSUE THREAD

**Issue by TheGlowEk** [Floorp-Projects/Floorp#1133]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When running the "Mirillis Action!" program, Floorp after about 5-15 seconds throws an instruction error message (0x00007FFC43478546), after clicking "OK", the problem returns after about 10 seconds, it often hangs videos playing in the background (e.g. YouTube) or other tabs.

### Reproduction Steps

1. Open the "action.exe"
2. wait some time (5-15s)
3. and expect browser crash/error popup, or white screen for about 2-3s. 

### Expected Behavior

everything should be fine, the browser should not hang

### Actual Behavior

![Bez tytułu](https://github.com/Floorp-Projects/Floorp/assets/168827007/44b030a4-e360-4f83-b255-350d6be48b55)
or white screen for about 2-3 seconds...

(The instruction at 0x00007FFC43478546 referenced memory at address 0x00007FFC43478546. The memory cannot be written. Click OK to terminate the application)

### Screenshots

![Bez tytułu](https://github.com/Floorp-Projects/Floorp/assets/168827007/ae061eda-647c-4360-853b-64c8b3b0f1c4)

(The instruction at 0x00007FFC43478546 referenced memory at address 0x00007FFC43478546. The memory cannot be written. Click OK to terminate the application)

### Browser Version

Floorp 11.12.2 x64

### Operating System

Windows 11 21h2

### Additional Context

I tried using the sfc /scannow and DISM options. nothing helped. I also tried to check if the problem is not RAM, and it is not.
The problem does not occur with Firefox Stable Release or ESR. I checked Firefox 115.10.0esr and 125.0.2...
Something else worth mentioning, along with the white screen, GPU works at 100% for a while.

**Comment by RimPYExposing** [comment]
Most likely Mirillis Action! interferring with that memory address, causing the crash.
And or is a hardware issue. 
I'd suggest just not using Mirillis Action! sense its causing the issue. As its most likely a bug with Mirillis Action!

**Comment by TheGlowEk** [comment]
> Most likely Mirillis Action! interferring with that memory address, causing the crash. And or is a hardware issue. I'd suggest just not using Mirillis Action sense its causing the issue. As its most likely a bug with Mirillis Action
> 
> Just use OBS, does the same thing but better as Mirillis Action.



For now I'm back to Firefox ESR. With OBS Studio, I sometimes had problems capturing full-screen applications, often such recordings either had low bitrate. The explanation is that it is Action!'s fault is absurd in my opinion, due to the fact that I only have this problem with Floorp.

**Comment by surapunoyousei** [comment]
Floorp supports operation in recommended environments only.

Third party support is not provided.

**Comment by TheGlowEk** [comment]
EDIT: I'm back after almost a year with a solution for those who have similar problems, the problem can be fixed by changing the name from "floorp.exe "to "firefox.exe" (yes, it really works lol) The same goes for other Firefox-based browsers.
