### ISSUE TITLE
[Bug]: Incorrect headings

### ISSUE THREAD

**Issue by Sven-Ademi** [Floorp-Projects/Floorp#1136]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Many websites do not show the correct headlines, but a confusing jumble of letters
![Screenshot 2024-05-06 at 22-46-14 Raycast for Mac  The Next-generation Alfred – The Sweet Setup](https://github.com/Floorp-Projects/Floorp/assets/39700520/1e46947e-cda6-49c5-9ca8-c123485328f3)

### Reproduction Steps

1. Visit this example-site: https://thesweetsetup.com/raycast-for-mac-the-next-generation-alfred/

### Expected Behavior

Correct display of headings

### Actual Behavior

Many websites do not show the correct headlines, but a confusing jumble of letters
I am from germany, language-setting is german and I am in MacOS Sonoma 14.4.1
![Screenshot 2024-05-06 at 22-46-14 Raycast for Mac  The Next-generation Alfred – The Sweet Setup](https://github.com/Floorp-Projects/Floorp/assets/39700520/37650b93-3a25-4cd3-81d6-36b08d7ec2df)

### Screenshots

![Screenshot 2024-05-06 at 22-46-14 Raycast for Mac  The Next-generation Alfred – The Sweet Setup](https://github.com/Floorp-Projects/Floorp/assets/39700520/611e1df2-900e-4057-bdb8-0e3ca1762460)

### Browser Version

11.12.2

### Operating System

MacOS Sonoma 14.4.1

**Comment by surapunoyousei** [comment]
My env:
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/7896dba6-2d84-4c2f-a0dc-ea7f63dc9365)

**Comment by yawns** [comment]
This is a common issue on Macs when multiple versions of the same font are installed, and less often with general font corruption. See the below bug for more info.

https://bugzilla.mozilla.org/show_bug.cgi?id=1804874

They had the user dig around and manually delete the duplicates, but you can also try opening Font Book and doing file->resolve duplicates to auto search for them.

If there are definitely no duplicates, you can also try using devtools to inspect some of the gibberish to figure out what fonts the site is trying to use, then back in Font Book, find those fonts, right click and "validate" to try to address any corruption.

**Comment by surapunoyousei** [comment]
https://hg.mozilla.org/integration/autoland/rev/19d87a3a7a39

**Comment by surapunoyousei** [comment]
@yawns Thank you for your research. I will try fix this issue.

**Comment by surapunoyousei** [comment]
ESR upgrade may fixs this issue
