### ISSUE TITLE
[Bug]: Thin white strips appear next to tab page in dark mode with Lepton Proton Fix theme

### ISSUE THREAD

**Issue by lghnb** [Floorp-Projects/Floorp#1144]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using dark mode and selecting the Lepton proton fix theme with the vertical tab bar enabled, you can see some very thin white strips next to the left tab page.

### Reproduction Steps

1. Enable dark mode in the application.
2. Select the Lepton Proton Fix theme.
3. Collapse the vertical tab bar.
4. Observe the left tab page closely.

### Expected Behavior

The thin white strips should not be visible next to the tab page when using dark mode with the Lepton Proton Fix theme and the vertical tab bar enabled. The interface should appear clean and consistent without any visual artifacts.

### Actual Behavior

Upon enabling dark mode and selecting the Lepton Proton Fix theme with the vertical tab bar in its collapsed state, thin white strips became visible next to the left tab page. This visual artifact disrupts the overall aesthetic of the interface, resulting in an inconsistent look.

### Screenshots

![屏幕截图 2024-05-12 191517](https://github.com/Floorp-Projects/Floorp/assets/144093871/b31949e6-e19a-47f2-807a-a395742cf57f)

### Browser Version

11.12.2

### Operating System

Windows 11 Professional 23H2

**Comment by surapunoyousei** [comment]
We consider this a Lepton design issue and do not intend to fix it.

If you don't like it, use another design.
