### ISSUE TITLE
[Bug]: Printing.

### ISSUE THREAD

**Issue by yessukumar** [Floorp-Projects/Floorp#1148]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

 While clicking the Print button on a webpage instead of opening the printer dialog the page gets downloaded as PDF. 

### Reproduction Steps

This is paid app and you cannot test this page issue

### Expected Behavior

Printer dialog to open

### Actual Behavior

Page gets downloaded as a PDF

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/48168866/2eeba951-23b2-4f8a-8389-db9170c58718)

### Browser Version

11.12.2 (64-bit)

### Operating System

Ubuntu 22.04 LTS

**Comment by surapunoyousei** [comment]
There is no way to fix the issue. Close with wantfix
