### ISSUE TITLE
[Bug]: Workspaces and keyboard shortcuts 1.12.2 (NixOS)

### ISSUE THREAD

**Issue by Alyuu** [Floorp-Projects/Floorp#1153]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I cannot find either the workspaces configuration nor the keyboard shortcuts. I can't seem to create or select new workspaces, now I only have this "container tabs" that only color the tabs, they don't collapse or I can't select between them to only see the ones in that container.

### Reproduction Steps

1. Install floorp (version 11.12.2) in NixOS via home manager
2. Open settings
3. Notice there is no workspace nor keyboard shortcut configurations

### Expected Behavior

Being able to configure workspaces and keyboard shortcuts

### Actual Behavior

The workspaces and keyboard shortcuts tabs doesn't show in the browser's configuration

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/100941712/bc23103d-1334-4355-a0fd-0e78e7b59eae)
![image](https://github.com/Floorp-Projects/Floorp/assets/100941712/5cf79d7d-f8bf-495a-8815-da9d058fd49f)
![image](https://github.com/Floorp-Projects/Floorp/assets/100941712/d475ccdb-66c8-4508-ae9d-feb93ca239fa)

### Browser Version

11.12.2

### Operating System

NixOS

### Additional Context

I'm using NixOS with a flake referencing the unstable branch of nixpkgs and installing floorp via home manager in "home.packages"

**Comment by surapunoyousei** [comment]
Please do not submit package manager issues

**Comment by Alyuu** [comment]
it's not a package manager issue, I have the last version of the browser, the options disappeared when it updated, but in windows I have the same version and they are still there

**Comment by surapunoyousei** [comment]
The maintainer of that package manager simply has not activated the private component.
 
There is nothing we can do.

**Comment by Alyuu** [comment]
Oh okay, thx
