### ISSUE TITLE
[Bug]: Web apps don't show toolbar. 

### ISSUE THREAD

**Issue by uugaabuugaa** [Floorp-Projects/Floorp#1154]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After updating to latest v11.13.0, web apps stop showing toolbar. Have tried on a fresh profile and still same problem. I use gesturefy, so it's manageable to browse but very inconvenient if not fixed soon. Tried `Disable toolbars on Web Apps Window` option on and off but nothing changes.

### Reproduction Steps

Install any site as web app and see no toolbar when opening it.

### Expected Behavior

Show toolbar when `Disable toolbars on Web Apps Window` option is not enabled.

### Actual Behavior

Doesn't show toolbar.

### Screenshots

![Screenshot (34)](https://github.com/Floorp-Projects/Floorp/assets/70348189/ac05756a-bea7-4f46-8294-2ed617eb63a6)

### Browser Version

v11.13.0

### Operating System

Windows 10 22H2

**Comment by surapunoyousei** [comment]
I will fix this issue at 11.13.2

**Comment by uugaabuugaa** [comment]
Thanks for the quick fix!
