### ISSUE TITLE
[Bug]: Latest release of Floorp broke sites menu bar

### ISSUE THREAD

**Issue by molitar** [Floorp-Projects/Floorp#1158]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Latest release of floorp is hiding the pull down selectors in menu bar for torrent site https://sukebei.nyaa.si/ 

### Reproduction Steps

1. Browse to https://sukebei.nyaa.si/

When in Chrome it shows the expected behavior when using Floor 11.13.1 it shows the actual behavior in screenshots. 

### Expected Behavior

![0W0GsfEERc6ZPpGVEzwVNA](https://github.com/Floorp-Projects/Floorp/assets/16074561/8989c41b-11a3-4242-a783-162f12e64fb7)

### Actual Behavior

![XF5CR8kXTmG2VFEshHpk1Q](https://github.com/Floorp-Projects/Floorp/assets/16074561/a7e3e99a-9d5c-4981-8e6e-6e56243b19dd)

### Screenshots

![XF5CR8kXTmG2VFEshHpk1Q](https://github.com/Floorp-Projects/Floorp/assets/16074561/a7e3e99a-9d5c-4981-8e6e-6e56243b19dd)

### Browser Version

11.13.1

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/e9db1da6-95d0-4cbc-ac0b-c0140c47ed97)
It’s fine in my env
