### ISSUE TITLE
[Bug]: New Tab Button Disappearing

### ISSUE THREAD

**Issue by thepick** [Floorp-Projects/Floorp#1160]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using vertical tabs, the new tab button (when toggled on) disappears upon browser restart

### Reproduction Steps

1. Go to Settings ---> Design ---> Vertical Tab bar (experimental) ---> Show the "Open a new tab" button inside Vertical Tab Bar
2. Toggle the switch on
3. Restart the browser

### Expected Behavior

The button will stay visible

### Actual Behavior

The button disappears

### Screenshots

<img width="935" alt="not there" src="https://github.com/Floorp-Projects/Floorp/assets/12082594/442d24c5-12a0-4e25-b9af-32debe5b7ce3">

### Browser Version

11.13.2 (64-bit)

### Operating System

Windows 11

### Additional Context

When the button is there, it's not centered anymore; It's sitting on the left.

**Comment by TheChilledBuffalo** [comment]
I have found the fix and will commit the changes soon. 

Also, adding an appropriate title for the issue would be really helpful. Thanks!

**Comment by surapunoyousei** [comment]
It maybe my mistake...
