### ISSUE TITLE
[Bug]: Browser Sidebar toolbar is broken with Autohide Bookmarks feature enabled

### ISSUE THREAD

**Issue by harukayamazaki** [Floorp-Projects/Floorp#1161]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

it is not a duplicate of https://github.com/Floorp-Projects/Floorp/issues/1097 which was solved with an update.
But this issue still persists. When a website is open in the Browser Manager Sidebar it is impossible to control it or close the BMS because the bookmark bar is unhidden and covers the controls on top of the BMS.
This is pretty annoying because it forces me to change the setting for Auto Hide Bookmark Toolbar just to be able to close the BMS. If only there were a shortcut to close BMS - that'd be a workaround I could live with...
Please re-open and look into this!
If you need additional information I am here to provide it.
Thank you very much!

I made a short video of it. As soon as the mouse pointer hovers over the (X) the bookmarks toolbar appears and makes it impossible to close the BMS. It looks like it would be possible to very quickly click the (x) as it seems to be delayed a bit but many attempts have brought no result. The delay seems to be visual - or i am slow ;-)

### Reproduction Steps

1. Add any shortcut to a website on the Browser Sidebar
2. Enable Autohide Bookmarks feature
3. Open shortcut on Browser Sidebar
4. Try to use the Toolbar on website on sidebar and use it's toolbar

### Expected Behavior

Browser Sidebar Manager website shortcuts should let you use it's own toolbar

### Actual Behavior

Auto hide bookmarks feature is interfering with Browser Sidebar Manager website shortcut's own toolbar.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/60632993/357cfd41-cf69-40e9-8117-c8f54cdd1021

### Browser Version

v11.13.2

### Operating System

Linux

**Comment by TheChilledBuffalo** [comment]
Thank you for the report and really sorry about that. I've found a fix and will commit it asap.

**Comment by harukayamazaki** [comment]
Fixed in 11.13.3
