### ISSUE TITLE
[Bug]: Not opening hyperlinks when Floorp is closed on Mac

### ISSUE THREAD

**Issue by vikingnope** [Floorp-Projects/Floorp#1167]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When I click on any hyperlink on an app while floorp is closed, it opens floorp but it does not open the webpage, and I have to click the hyperlink again with floorp open.

### Reproduction Steps

1. Use MacOS
2. Click on a hyperlink with floorp fully closed
3. Floorp opens but new tab with hyperlink does not

### Expected Behavior

Should open hyperlink tab

### Actual Behavior

Does not open hyperlink tab and only opens floorp

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/81376423/469ad240-4e2c-4b32-91ef-be314fa2d799

### Browser Version

11.13.2

### Operating System

MacOS Sonoma 14.5

**Comment by surapunoyousei** [comment]
This is the same behavior in Firefox, which is tracked by Bugzilla, so Floorp does not solve this problem.

**Comment by vikingnope** [comment]
Do you have the link for it?

**Comment by surapunoyousei** [comment]
In the past, the same problem was reported on Discord, and I think it was on Bugzilla. I'll do some digging.
