### ISSUE TITLE
[Bug]: After a other workspace config changed, current icon & label should not changed by Floorp.

### ISSUE THREAD

**Issue by ColonelPanicks** [Floorp-Projects/Floorp#1170]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I just installed the browser (really looking forward to trying it out!) and am excited to get going with the different "Workspaces".

Perhaps I am misunderstanding how these should function but what I'm noticing is that:
1. Workspace settings seem to be "forgotten" when going into the settings menu to change them (e.g. if I select a workspace it'll default to the "Default" workspaces' options)

### Reproduction Steps

1. Install Floorp (issue seen on 11.13.2) 
2. Create new workspace
3. Rename workspace (right-click -> rename) 
4. Click settings icon
5. Make some changes to settings

### Expected Behavior

- Workspace settings remembers details for each workspace 

### Actual Behavior

- Workspace settings seem to be forgotten in the edit view

### Screenshots

Settings not persisting in menu view
https://github.com/Floorp-Projects/Floorp/assets/27725639/8a0d03fb-90d9-4b18-a46b-7c949d9caf2d

### Browser Version

11.13.2

### Operating System

MacOS

### Additional Context

I haven't tried cookie clearing or creating new profiles as I have only just installed the browser so consider this "clean". 

Let me know if there's any other info I can provide! This browser looks really neat

**Comment by surapunoyousei** [comment]
The issue of workspace label names and icons changing after setup, even though the user is in a different workspace, needs to be resolved, but other than that, there is currently no way to resolve this issue due to technical limitations.

**Comment by surapunoyousei** [comment]
Also, container settings are applied only to newly opened tabs after they are applied. Thank you for your understanding.
