### ISSUE TITLE
[Bug]: Can't log in on Twitch due browser not supported

### ISSUE THREAD

**Issue by blindmodz** [Floorp-Projects/Floorp#1171]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

As the tittle says, since like 3 or 4 updates ago you are unable to log in on Twitch due the browser not being supported. 
Tried with latest Chrome/Firefox and both works fine.
Tried using the user agent (Floorp settings) and doesn't work either.

### Reproduction Steps

1. Go to twitch.tv
2. Log in

### Expected Behavior

Log in successfully.

### Actual Behavior

Error due browser not supported.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/22939330/d2362112-9020-47c8-bca6-c4d90fb3b3c3)

### Browser Version

11.13.2

### Operating System

Windows 11

**Comment by CutterKnife** [comment]
Just to confirm, you were able to login successfully with Firefox ESR 115?

**Comment by blindmodz** [comment]
> Just to confirm, you were able to login successfully with Firefox ESR 115?

Yes tried Firefox "normal", ESR 115 and both are able to log in.

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/7e8711a7-2409-4db4-8e83-bc2d3532217e)
I can login to twitch.

**Comment by GrubBox** [comment]
I have the same issue with *twitch* also I am unable to long into war-gamming _log-in page_ . pic attached.
![twtich unable](https://github.com/Floorp-Projects/Floorp/assets/19636873/e4b53810-7ee2-438f-96ee-54e455232cce)
![wagamming](https://github.com/Floorp-Projects/Floorp/assets/19636873/6f67fe9e-25cb-4eca-9630-8f1698cd0e45)

**Comment by alishkrr** [comment]
I had the same problem in windows 11, chrome.
changed **region** and **time-zone** of my windows to _USA_, and then synced time with server. 
restart browser
**FIXED !**
