### ISSUE TITLE
[Bug]: This browser won’t be supported starting September 1st, 2024. Update your browser to keep using Slack. 

### ISSUE THREAD

**Issue by bcookatpcsd** [Floorp-Projects/Floorp#1172]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

This might be related to ESR.. 

I see a similar message randomly using the browser on different sites.. Is there a preference or setting to change whatever they are seeing as 'out of date'? 

### Reproduction Steps

1. Use Floorp to sign into Slack
2. Message is a banner sometimes and a footer others

### Expected Behavior

Accolades and praise for using Floorp.  :) 

### Actual Behavior

Told that I will be shunned and treated like an outcast.. :( 

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/55087301/ae605a3b-799a-45af-9ad6-ae0de6878502)

### Browser Version

11.12.2 (64-bit)

### Operating System

OS Name:                   Microsoft Windows 10 Pro Education OS Version:                10.0.19045 N/A Build 19045

### Additional Context

Thank you for taking the time to read this..

**Comment by regularentropy** [comment]
ESR issue. Either try spoof user agent or wait until the next release.

**Comment by bcookatpcsd** [comment]
All good.. no problem, wanted to report, will wait and spoof; yes..
