### ISSUE TITLE
[Bug]: Unable to use drop down list to select state on sites even when in safe mode!

### ISSUE THREAD

**Issue by molitar** [Floorp-Projects/Floorp#1178]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When I got to a form site that requires a pull down to select say state I can not click on the field. I can tab down and select state but I am unable to click on it.
https://www.moffitt.org/give/ways-to-give/other-ways-to-donate/moffitt-license-plate/plate/

### Reproduction Steps

1. Browse to https://www.moffitt.org/give/ways-to-give/other-ways-to-donate/moffitt-license-plate/plate/
2. Click on the State unable to click on it

### Expected Behavior

Pull down with the state Florida should show

### Actual Behavior

The field can not be clicked on at all

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/16074561/da96ecdc-1a9c-4ec2-ba5f-4e867152b2aa)

### Browser Version

11.13.3

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/a60315eb-7024-444c-9688-035fe8f78275)
