### ISSUE TITLE
[Bug]: Download from sidebar is not opening

### ISSUE THREAD

**Issue by DankestFke** [Floorp-Projects/Floorp#1179]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I always open files from sidebar because it is more convenient than pop up download windows. But recently, it didn't show anything except an extra padding of blank while I clicked it. Other sidebar works just fine. 

### Reproduction Steps

1. Open browser
2. Press Download sidebar button

### Expected Behavior

Download sidebar opened

### Actual Behavior

Download sidebar is blank

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/62785913/82e2ccd2-a46b-42ea-821b-a0184ffd3391)

### Browser Version

11.3.3

### Operating System

Windows 10 22H2

### Additional Context

This bug happens months ago, I don't want to risk losing my data; If there's no alternative than reinstalling please provide a safer way to backup my data.

**Comment by surapunoyousei** [comment]
Did you reset browser manager sidebar?

**Comment by DankestFke** [comment]
@surapunoyousei I don't know how to reset it, but actually turning off "Enable Extensions Content Scripts in Browser Manager Sidebar" works.
