### ISSUE TITLE
Floorp can't display Manjaro site properly

### ISSUE THREAD

**Issue by Telmesomething** [Floorp-Projects/Floorp#118]
## Describe the bug
Home page at [Manjaro.org](https://manjaro.org/url) won't display properly. It works properly in Firefox. 

## To Reproduce
1. Go to 'https://manjaro.org/'

## Expected behavior
The home page should display normally as per the site viewed in Firefox.

## Screenshots
Floorp display
![manjaro site display issue](https://user-images.githubusercontent.com/33827636/197749519-81196480-4a5a-4737-9e79-839753d93760.PNG)

Firefox display

![manjaro on firefox ok](https://user-images.githubusercontent.com/33827636/197749603-d2570108-3834-4d83-8d5b-902932039306.PNG)

## Desktop (please complete the following information):
 - OS: Windows 8.1
 - Floorp Version: 10.6.2

**Comment by surapunoyousei** [comment]
Our environment on Windows 11 is looks like fine.
![image](https://user-images.githubusercontent.com/73892113/197750787-5c0a7c17-e595-475b-958e-bfd466bcf410.png)

**Comment by Telmesomething** [comment]
OK. I'll check it out in a new profile. 

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Oct 25, 2022, 12:31 by ***@***.***:

**Comment by surapunoyousei** [comment]
There is no reply, and it is working fine in our environment, so I will close it as it is completed.
