### ISSUE TITLE
[Bug]: Rounder corners colors stand out a little

### ISSUE THREAD

**Issue by Minnona** [Floorp-Projects/Floorp#1180]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hey, I noticed rounded corners have a different color compared to the rest of toolbar in both dark and light themes, would be nice if they match the color of neighboring borders.

### Reproduction Steps

1. Enable rounder corners
2. Crawl into a ball and cry

### Expected Behavior

Colors of corners matching with the rest of the browser

### Actual Behavior

Rounder corners stand out

### Screenshots

![corners](https://github.com/Floorp-Projects/Floorp/assets/23418072/577630f9-b91b-4a58-8bc5-7be89d29908f)

### Browser Version

11.13.3 (64-bit)

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
This is a limitation because border-radious cannot be used. I don't care that much about it, so I don't intend to fix it.
