### ISSUE TITLE
[Bug]: crashing Konsole when installing from aur on Endeavor 

### ISSUE THREAD

**Issue by Ryder17z** [Floorp-Projects/Floorp#1182]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

crashing when installing from aur on Endeavor, taking Konsole down with it.

### Reproduction Steps

0. Get Endeavor
1. `yay floorp`
2. pick option 1 (aur/floorp which lists version 11.13.2-1)
3. (i picked "None" in "packages to cleanbuild, didn't look at diffs and left dependencies after install, if this matters)
4. crash

### Expected Behavior

not to crash the terminal?
if it had just been halting on an error, that wouldn't be as impressive...

### Actual Behavior

Install goes on for a while and unexpectedly errors out, killing the instance of Konsole the installation was started on

### Screenshots

N/A

### Browser Version

11.13.2-1

### Operating System

Freshly installed Endeavor (arch with KDE)

### Additional Context

There is no issue with floorp-bin or other browser, so i'm guessing a packaging issue?

I don't know where logs would be stored during install, otherwise i would attach them.

**Comment by TheChilledBuffalo** [comment]
Yes it indeed might be a packaging issue and so I suggest you comment about this issue on the `floorp` package on the AUR. It's not maintained by Floorp directly, so it's not something we can help with, I believe.

**Comment by Ryder17z** [comment]
Okay, thank you for confirming @TheChilledBuffalo

**Comment by Ryder17z** [comment]
Additionally, there is a pinned comment on the aur package telling users to use https://aur.archlinux.org/packages/floorp-bin instead.
