### ISSUE TITLE
[Bug]: Maximize UI-button snap layout menu on hover is broken while using 'Combine Tab Bar and Toolbar' feature.

### ISSUE THREAD

**Issue by animayyo** [Floorp-Projects/Floorp#1189]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The windows maximize UI-button on hover displays a snap layout preview in Win11 but it is broken after using 'Combine Tab Bar and Toolbar' setting. The snap layout preview moves to the left top corner toolbar UI-button instead.

### Reproduction Steps

1. Go to your 'Settings' > 'Design' > 'Firefox Photon: Lepton UI Settings'
2. Scroll down to 'Combine Tab Bar and Toolbar' and toggle on.
3. Hover over your maximize UI-button on top-right for few seconds.
4. Now, hover on your top-left corner UI-buttons until you get a snap layout preview.

### Expected Behavior

Windows Snap Layout Preview should display on maximize button like every other application.

### Actual Behavior

Windows Snap Layout Preview displays on top-left toolbar UI-button instead on hover.

### Screenshots

![SnapHoverMyProfile](https://github.com/Floorp-Projects/Floorp/assets/84479572/9004798e-6492-418a-9ac0-1d887563b6cd)

### Browser Version

11.13.3

### Operating System

Windows 11 Pro 22H2 22621.3593

### Additional Context

This issue can be replicated on a new default-user profile with no custom css, extensions, add-ons, etc.

**Comment by surapunoyousei** [comment]
This is a Lepton feature; Lepton Sorry, I do not currently guarantee Floorp compatibility with Lepton features.
