### ISSUE TITLE
[Bug]: Default new tab of a workspace does not open in the selected container

### ISSUE THREAD

**Issue by Zeit08** [Floorp-Projects/Floorp#1190]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Workspace1 has the setting to open all websites in Container1. Same for Workspace2 has the setting to open all websites in Container2, etc.

This works when I go to the Workspace and click "new tab". I see the correct color of the Container.

However when I close all the tabs in a workspace and visit it again (switch between workspaces). I am welcomed with a opened new tab. The bug is that this automatically opened new tab is not opened inside the container specified in settings. It is opened with no container.

Also another bug is that when all the tabs in a workspace are closed, Floorp automatically shows me the tabs of the above workspace, but the icon on top left still shows the previous workspace.

### Reproduction Steps

1. create 2-3 workspaces
2. assign different containers to each workspace
3. use the sidebar to manage workspaces
4. try to close all tabs in a workspace
5. go to another workspace
6. go back to the previous workspace where you closed all tabs
7. you see a new tab which is opened automatically with no container

### Expected Behavior

automatic new tab in a workspace should open with the container setting I made.

### Actual Behavior

I explained above.

### Screenshots

no visual 

### Browser Version

11.13.3 (64-bit)

### Operating System

Fedora 40

**Comment by surapunoyousei** [comment]
https://docs.floorp.app/en/others/issue-checklist/

**Comment by surapunoyousei** [comment]
This issue is difficult to fix due to current implementation method. After switch workspaces or change tab, we cannot get data immediately.
