### ISSUE TITLE
[Bug]: Error: Map.groupBy is not a function

### ISSUE THREAD

**Issue by luiskugel** [Floorp-Projects/Floorp#1191]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using the page npmgraph i got the error Map.groupBy is not supported and it looks like the function does not exist in floorp. I tried in firefox and chrome and both browsers work. 

### Reproduction Steps

1. Open this URL: [https://interactive-examples.mdn.mozilla.net/pages/js/map-groupby.html](https://interactive-examples.mdn.mozilla.net/pages/js/map-groupby.html)
2. Click Run

### Expected Behavior

The function to be existent and working

### Actual Behavior

The function seems to be missing/disabled

### Screenshots

I don't think this is necessary. You should be easily able to reproduce the issue via the url. 

### Browser Version

11.13.3 (64-Bit)

### Operating System

Windows 11

**Comment by regularentropy** [comment]
ESR issue. Please wait untill the next release.

**Comment by CutterKnife** [comment]
Now, you said it works in Firefox ESR.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/groupBy

According to this site, this feature was implemented in Firefox 119; the current version of Firefox ESR is 115, so I don't think the feature exists.
