### ISSUE TITLE
[Bug]: Floorp not detecting all browsers

### ISSUE THREAD

**Issue by Zorakie** [Floorp-Projects/Floorp#1194]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The browser does not detect other installed browsers except of edge.

I have Firefox Developer edition (127.0b7 (64-bit)) and it is not being detected as a browser to migrate data from. That means, all teh migration (bookmarks, passwords...) must be done manually.

### Reproduction Steps

1. Install Firefox Developer edition
2. Install Floorp
3. After installation, Floorp asks you if you want to import settings. Firefox is not listed.
4. Later on, if you click Import bookmparks, the same pop-up is show, Firefox is also not generated.

### Expected Behavior

Floorp should detect all known browsers.

### Actual Behavior

Floop fails to detect some installed browsers for data migration.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/14437576/f2d2abd0-a12f-4951-9312-911fc174a3e9)

### Browser Version

11.13.3

### Operating System

Windows 11 (build 22631.3593)

**Comment by breadbeforerice** [comment]
"This issue is specific to this browser and does not occur in other browsers." is checked, but I think Firefox developeredition has the same behavior.(It is in the settings.) You can use synchronization with Firefox.
