### ISSUE TITLE
[Bug]: Phantom tooltips on Linux

### ISSUE THREAD

**Issue by skyfenton** [Floorp-Projects/Floorp#1195]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp tooltips remain on screen if the virtual desktop is switched before the text is drawn.

### Reproduction Steps

1. Hover over elements with a tooltip (menu items, tabs, etc.)
2. Switch virtual desktops around the time the tooltip should fade in.
3. Observe the textbox remains on screen until returning to browser window.

### Expected Behavior

Tooltip should not appear.

### Actual Behavior

Tooltip appears and remains onscreen over other windows until the user returns to the browser window.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/77299688/432d347e-da2d-4e47-b827-f32e381859ee

### Browser Version

11.13.3 (64-bit)

### Operating System

KDE Neon 6.0.4 (Based on Ubuntu LTS with Wayland)

### Additional Context

Issue happens often, such as if the user leaves the mouse over a tab while switching virtual desktops. Bug does not occur on Firefox or Chromium.

**Comment by surapunoyousei** [comment]
I don't think this is a browser bug.

**Comment by surapunoyousei** [comment]
Ahh. Sorry. We do not support Wayland.

**Comment by skyfenton** [comment]
> Ahh. Sorry. We do not support Wayland. Wait for Floorp 12

Ohhhhhhhhhhhhhhh cool, will do!

**Comment by surapunoyousei** [comment]
I promise, Floorp will have the support...

**Comment by skyfenton** [comment]
(For anyone encountering any graphical problems that seem system/wayland-related, I just added the experimental wayland variable to my environment and it seems to work, though I don't know if there are any known side effects. `export MOZ_ENABLE_WAYLAND=1` in your favorite bash/environment script)
