### ISSUE TITLE
[Bug]: "Show Sidebar over website content" doesn't work properly when the sidebars are on the right

### ISSUE THREAD

**Issue by mbugrayilmaz** [Floorp-Projects/Floorp#1196]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When you select "Show Sidebar over website content", but also set the sidebars to show up on the right, the sidebars seem to still expand to the right, outside of the browser

### Reproduction Steps

1. Select "Move sidebar to the right" from the sidebar header
2. Enable "Automatically hide Sidebar" from Lepton Settings
3. Enable "Show Sidebar over website content"

### Expected Behavior

When you hover over the hidden sidebar on the right, it should expand to the left, making the whole thing visible

### Actual Behavior

The sidebar expands to the right, nothing happens

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/8601972/46cc3162-d67b-42d5-8575-830ef985f29f

### Browser Version

Floorp 11.13.3

### Operating System

Windows 11

### Additional Context

I tried different sidebars other than Sidebery like history, bookmarks etc. but the result is the same. I also tried toggling Browser Manager Sidebar but that didn't change anything

**Comment by surapunoyousei** [comment]
This is a Lepton setup, so there is nothing we can do about it. Sorry.

**Comment by mbugrayilmaz** [comment]
Sorry to open up this issue again, but I installed Lepton UI to a vanilla Firefox, and this problem doesn't exist there. It only happens in Floorp so maybe it's a Floorp specific Lepton configuration issue? Me and a lot of people prefer using sidebars at right side and this is the only problem I have with this wonderful browser. Thank you again for the great work
