### ISSUE TITLE
[Bug]: Rounded Corners add unnecessary padding

### ISSUE THREAD

**Issue by mysteryx93** [Floorp-Projects/Floorp#1197]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I'm on a fresh new install of Garuda Linux. Floorp-based browser default to Rounded Corners, which add unnecessary padding.

This causes 2 issues. 

First, if you move the mouse quickly to the right-side, you pass the scrollbar area and need to step back a few pixels to use the scrollbar.

Second, it's wasted real-estate. This extra padding brings no benefit whatsoever.

### Reproduction Steps

Open the browser with default settings (with Rounded Corners enabled).
Move the mouse completely to the right and see whether it hovers the scrollbar or it's on a useless padding.

### Expected Behavior

Rounded Corners should only affect corners. With no useless padding.

### Actual Behavior

View size is reduced with unnecessary padding that has no benefit.

### Screenshots

![Screenshot_20240530_170002](https://github.com/Floorp-Projects/Floorp/assets/8528033/c691048e-4455-4cc4-8307-2d5ed6a38f21)

### Browser Version

FireDragon 11.13.3, based on Floorp

### Operating System

Garuda Linux

### Additional Context

We're having the issue with FireDragon; they say it's a Floorp feature so I'm reporting it here instead. If you are not seeing the same behavior, then let me know and I'll pass it back to them. It's something really trivial but shouldn't be set as default with that padding.

**Comment by surapunoyousei** [comment]
This feature is inspired by Microsoft Edge, which is an influence to reproduce a similar design to Edge.

Not bug.  You can modify via userChrome.css

**Comment by mysteryx93** [comment]
lol answer inspired by Microsoft: "it's not a bug, it's by design" :)
