### ISSUE TITLE
Prevent Floorp from opening link in new tab immediately

### ISSUE THREAD

**Issue by Telmesomething** [Floorp-Projects/Floorp#120]
## Describe the bug
In Settings ---> Tabs I have the option to switch to a link in new tab immediately disabled. In spite of the setting when clicking a link on a site, Floorp switches to the new tab immediately. 

## To Reproduce
1. In the Settings menu ---> Tabs, turn off the setting "When you open a link, image or media in a new tab, switch to it immediately".
2. Go to [this site](https://nos.nl/artikel/2451113-99-jarige-duitse-oud-soldaat-te-broos-om-terecht-te-staan-voor-oorlogsdaden) and click the link to Duitse Media in the opening paragraph. Floorp switches to that tab in spite of the option being disabled.

## Expected behavior
Floorp should remain on the page on which the link to another site is located. 

## Screenshots

![tabs links setting](https://user-images.githubusercontent.com/33827636/200113702-621bd432-c703-47ad-b4fc-ab3fa9643139.PNG)

## Desktop (please complete the following information):
 - OS: Windows 8.1 Home
 - Floorp Version: 10.6.2

**Comment by surapunoyousei** [comment]
Thank you for your report

Tested on Firefox ?

**Comment by Telmesomething** [comment]
> Thank you for your report
> 
> Tested on Firefox ?

Firefox behaves the same way so I guess it's a Mozilla issue and not confined to Floorp.

**Comment by surapunoyousei** [comment]
Open `about:config` and search `browser.tabs.loadDivertedInBackground`.

set value `false` to `true`

**Comment by Telmesomething** [comment]
I had to create the about:config setting since it wasn't present before, but unfortunately it doesn't work. Tested on [this site](https://www.theguardian.com/technology/2022/nov/10/exodus-twitter-elon-musk-possible-bankruptcy) and then click the link to [warnings from the Federal Trade Commision (FTC)](https://www.washingtonpost.com/technology/2022/11/10/twitter-security-resignations/) Floorp switches to that link directly in a new tab.  

In Firefox, the setting is present, but when clicking the second link in the example it opens in the same tab which isn't what should happen either. 

To clarify, what should happen is that the link opens in a new tab, but Floorp remains on the page where the link is located. You have to bear in mind that when a large number of tabs are open on different sites, having Floorp switch to a new tab makes it difficult to find the previous tab since it may not open directly next to the page where the link came from. This is particularly relevant when looking up the meaning of a given word in an online dictionary using the context menu to open the site with where the word is located. 

Here's an example. In the image I want to find out what the word "Bankruptcy" means (_I know what it means, but this is just an example to illustrate the problem_). When the link to the dictionary site loads - [Collins Search](https://www.collinsdictionary.com/us/dictionary/english/bankruptcy) in this particular case - Floorp switches to it immediately. The link to a given site might be at the opposite end of the tab bar to where the origin is located which in turn makes it difficut to find it again. 

![context menu search](https://user-images.githubusercontent.com/33827636/201302767-6a819e45-aeaf-43ea-b857-06a03e2e56a5.PNG)

**Comment by Telmesomething** [comment]
**UPDATE**
The about:config change seems to be working the same way it does in Firefox now. That may be due to a PC reboot perfomed a few minutes ago. As regards opening a link in another tab without Floorp switching to it immediately, that works properly now as well.

Thanks for your valued and prompt assistance guys.
