### ISSUE TITLE
Correct Readme: (All Linux Distributions) to (Most Glibc-based Linux Distributions))

### ISSUE THREAD

**Issue by xplshn** [Floorp-Projects/Floorp#1200]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Change 

### Reproduction Steps

.

### Expected Behavior

.

### Actual Behavior

.

### Screenshots

.

### Browser Version

.

### Operating System

.

### Additional Context

Why "some" and not all? Because some Glibc versions are incompatible with recent Firefox versions, and that applies to Floorp too.
Why "Glibc-based"? Because not all Linux distros use Glibc.

**Comment by TheChilledBuffalo** [comment]
@xplshn How does it look now? Can this issue be closed?

**Comment by CutterKnife** [comment]
Maybe fixed?

**Comment by xplshn** [comment]
I was referring to this. The Tarball won't work on Alpine, Void Linux Musl, Dragora, Sabotage Linux, Gentoo LLVM Musl, Gento Musl, Chimera Linux, etc. So, in my opinion, it should say on "(Most Linux Distributions [glibc])"
```
1. PPA (Ubuntu, Linux Mint, etc.)       "https://ppa.floorp.app"

2. Flatpak (Most Linux Distributions)    "https://flathub.org/apps/one.ablaze.floorp"

3. tarball (Most Linux Distributions)    "https://GitHub.com/Floorp-Projects/Floorp/releases/latest"

4. AUR bin (Arch-based Distributions)        "https://aur.archlinux.org/packages/floorp-bin/" **Unofficial**

5. AUR (Arch-based Distributions)        "https://aur.archlinux.org/packages/floorp/" **Unofficial**
```

**Comment by surapunoyousei** [comment]
If you understand it best yourself, please send a pull request!
