### ISSUE TITLE
[Bug]: Inconsistent capitalization of "Workspace" in English localization

### ISSUE THREAD

**Issue by StrongSand94191** [Floorp-Projects/Floorp#1205]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The term "Workspaces" is mostly capitalized, but there are a few instances where it is not.
1. In Keyboard Shortcuts settings: "Open **workspaces** preferences," "Open previous **workspace,**" "Open next **workspace**"
2. In Workspaces settings: "Close **workspaces** popup when selecting a Workspace"

### Reproduction Steps

1. Have the English localization enabled
2. Go to about:preferences#workspaces
The second option says: "Close workspaces popup when selecting a Workspace"

### Expected Behavior

The term "Workspace(s)" should be consistently capitalized.

### Actual Behavior

The capitalization is inconsistent.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/79473173/9c81813e-3baa-4bcf-8756-69d2d0da2a9a)

### Browser Version

11.13.3

### Operating System

Windows 10 x86_64

**Comment by regularentropy** [comment]
OK

**Comment by regularentropy** [comment]
Fixed: https://github.com/Floorp-Projects/Unified-l10n-central/commit/91c273958b732d1d9b5173b5f305807a9033ef22
