### ISSUE TITLE
[Bug]: PWA Icon and size

### ISSUE THREAD

**Issue by bmp** [Floorp-Projects/Floorp#1206]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When I create a PWA for [web.whatsapp](https://web.whatsapp.com/) on Linux (openSUSE Tumbleweed 20240531 x86_64), the PWA is installed with the correct icon in applications. 
![Screenshot_20240604_172950](https://github.com/Floorp-Projects/Floorp/assets/1095177/37027bb9-3822-4251-8b3c-1912ea26a5cb)

However, I have a few issues (screenshot below),

1. When the application is launched the application window is still called Floorp, so the icon for it is set as Floorp and not as the icon shown in applications (if it helps, I am on KDE). 
2. The application is always launched in a small resized window
![Screenshot_20240604_172928](https://github.com/Floorp-Projects/Floorp/assets/1095177/a11441e5-6727-4db5-bfb3-3ce055aa5d6b)
3. Once in a while when the application is launched Floorp is launched as well.
![Screenshot_20240604_172928](https://github.com/Floorp-Projects/Floorp/assets/1095177/a11441e5-6727-4db5-bfb3-3ce055aa5d6b)

### Reproduction Steps

1. Install web app from the address bar after visiting the site
2. Launch the web app from the launcher being used
3. See the icon and the name for the application in the task bar and the icon in the window switcher

### Expected Behavior

1. The icon present in application list must be used in the task bar and the window switcher
2. Application should be launched in full screen or the same size as Floorp launches as

### Actual Behavior

As described previously.

### Screenshots

Added previously.

### Browser Version

11.13.3 through Flatpak

### Operating System

openSUSE Tumbleweed 20240531 x86_64

### Additional Context

KDE on openSUSE

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1102

Dupulicate
