### ISSUE TITLE
[Bug]: Floorp installation repo is not reachable

### ISSUE THREAD

**Issue by rcarey1999** [Floorp-Projects/Floorp#1215]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When installing floorp through ppa (https://ppa.ablaze.one/Floorp.list) I am receiving a "404 Not Found"

### Reproduction Steps

Below commands in terminal:
1. curl -fsSL https://ppa.ablaze.one/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/Floorp.gpg
2. sudo curl -sS --compressed -o /etc/apt/sources.list.d/Floorp.list 'https://ppa.ablaze.one/Floorp.list'
3. sudo apt update
4. sudo apt install floorp

### Expected Behavior

The Floorp browser to install

### Actual Behavior

Floorp does not install

### Screenshots

![github_issue](https://github.com/Floorp-Projects/Floorp/assets/136794134/eae2be55-2434-4808-8d84-67d5cdc65f15)

### Browser Version

11.14.0

### Operating System

Ubuntu 24.04 LTS

### Additional Context

x86 architecture

**Comment by swip3798** [comment]
Can confirm, I have the same problem, every second update the PPA is broken for a while.

**Comment by AxeldeWater** [comment]
Can confirm, same problem.

**Comment by smerte42** [comment]
Can confirm, The same problem.

**Comment by x3llaz** [comment]
This is like the 3rd time this happened to me since making Floorp my daily driver browser on my Linux machine. Why is this happening so often whenever there is an update? It seems someone in Floorp often forgets us Linux users. 😮‍💨

![floorp_error_2](https://github.com/Floorp-Projects/Floorp/assets/96539548/863a287c-7461-404c-90e4-3e13c935dfe6)

**Comment by creeper-0910** [comment]
This is a problem associated with the increased number of deb packages stored in the PPA.
We are planning to solve the problem by deleting past versions in the future.

**Comment by giangbang** [comment]
I have the same above problem, cannot upgrade floorp through `apt`. Though I can still download the new release file `tar.bz2`, extract it, and run `floorp` from the extracted folder (a clean instance, no preference, extensions, or customization). 
Just curious, should I go with something like `sudo cp -R \path-to-floorp-11.14.0 \usr\lib\floorp\`? as far as I know, `floorp` is save at `\usr\lib\floorp\`

**Comment by rcarey1999** [comment]
> This is a problem associated with the increased number of deb packages stored in the PPA. We are planning to solve the problem by deleting past versions in the future.

Glad to hear a solution is known.  Looking forward to switching back to floorp at the soonest! :grinning:

**Comment by creeper-0910** [comment]
I have corrected the PPA, has the problem been resolved?

**Comment by AxeldeWater** [comment]
It has been solved, just updated!

**Comment by creeper-0910** [comment]
I'm glad it was resolved!
