### ISSUE TITLE
[Bug]: Autohide both toolbar and navbar results in not being able to click the top area completely without toolbar interference.

### ISSUE THREAD

**Issue by Rtizer-9** [Floorp-Projects/Floorp#1216]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Choosing autohide option for both toolbar and navbar results in not being able to click anything on top area completely without toolbar reappearing inbetween.

### Reproduction Steps

1. Turn on autohide for both navbar and toolbar from leptop design menu.
2. Go to google.com or any website which has clickable things on the area where normally toolbar/navbar exists.
3. Try to click on those things.

### Expected Behavior

You should be able to click those things without the toolbar reappearing inbetween.

### Actual Behavior

You can't click those things without the toobar reappearing inbetween resulting in clicking on toolbar instead of those things you actually want to click.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/35103368/b993d4f2-2244-4d0c-a6f1-e0d4b8ed45b9

### Browser Version

11.13.3 (64-bit)

### Operating System

Kubuntu 24.04

**Comment by TheChilledBuffalo** [comment]
I was able to reproduce this issue. I'll send a PR to fix it.

**Comment by TheChilledBuffalo** [comment]
Wait... I was wrong, that didn't work.

Also as this is a lepton issue maybe you should report this in the lepton repository instead of here?

**Comment by Rtizer-9** [comment]
Umm oops
Ok.
