### ISSUE TITLE
[Bug]: custom new tab url does not work in Floorp 11.14.0

### ISSUE THREAD

**Issue by pogmommy** [Floorp-Projects/Floorp#1217]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Setting a value for floorp.newtab.overrides.newtaburl in Floorp's advanced preferences does not load the url entered when opening a new tab.

### Reproduction Steps

1. navigate to about:config
2. search for floorp.newtab.overrides.newtaburl
3. enter any url (https://example.com/) as its value
4. close and re-open browser
5. open a new tab

### Expected Behavior

opening a new tab should automatically load the URL ented for floorp.newtab.overrides.newtaburl

### Actual Behavior

opening a new tab loads whichever option is selected in about:preferences#home

### Screenshots

n/a

### Browser Version

11.14.0

### Operating System

Debian Sid

### Additional Context

Tested on Floorp x86_64 installed via tarball and aarch64 installed via flatpak. Confirmed that this issue was not present on 11.13.3.

**Comment by Car0lina5** [comment]
I also have the same problem... it started happening after the last update. :(
Windows.

**Comment by surapunoyousei** [comment]
Ah...

Researching

**Comment by Car0lina5** [comment]
It worked again after the new update. Thanks for the quick fix. :)

**Comment by surapunoyousei** [comment]
You too thank you for use Floorp!

**Comment by pogmommy** [comment]
Cheers, thank you for your hard work on Floorp!
