### ISSUE TITLE
[Bug]: 垂直タブバーを折りたたむ設定で「ツールバーをカスタマイズ」を開くと、折りたたみ時のタブバーの幅が広がる

### ISSUE THREAD

**Issue by absol-0359** [Floorp-Projects/Floorp#1219]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

「垂直タブバーを折りたたむ」設定で「ツールバーをカスタマイズ」を開くと、垂直タブの折りたたみ時の幅が本来よりも広がった状態になります。
Floorpを再起動すると元のサイズに戻ります。

### Reproduction Steps

1.タブバーのスタイルを「垂直タブ（実験的）」、「垂直タブバーを折りたたむ」に設定。
2.「ツールバーをカスタマイズ」を開いて、その後閉じる。

### Expected Behavior

垂直タブバーは元の折りたたみサイズに戻る。

### Actual Behavior

垂直タブバーは折りたたまれるが、幅が元のものより広くなっている。

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/171554857/525fee69-7657-440e-bc8b-c584ed87060a

### Browser Version

11.13.3, 11.14.0

### Operating System

Windows 11 Pro

### Additional Context

動画は新しいプロファイルを作成し、そのプロファイルでタブバーの設定のみ変更して行ったものです。

**Comment by surapunoyousei** [comment]
I send a patch for fix this issue

**Comment by absol-0359** [comment]
11.15.0にて解決されていることを確認しました。ありがとうございます！

**Comment by surapunoyousei** [comment]
それはよかったです！
