### ISSUE TITLE
Floorp & Sandboxie

### ISSUE THREAD

**Issue by CCRDude** [Floorp-Projects/Floorp#122]
## Describe the bug

When trying to run Floorp using Sandboxie Plus 1.4.2, all tabs crash with the following message:
```
WerFault.exe (22400): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 14 - WerFault.exe [FF000000]
```

## To Reproduce

1. Install [Sandboxie Plus](https://sandboxie-plus.com/)
2. Create a new sandbox for Floorp (Menu Sandbox -> Create New Box)
3. Run the floorp installer stub within sandbox (Select new box, right-click, choose installer to run).
4. Once installed, try to open any URL. A message window will appear with the message above.

## Expected behavior
Tabs should open.

## Desktop (please complete the following information):
 - OS: Windows 11, aka 10.0.22000.1098, aka 11 Pro 21H2, OS build 22000.1098.
 - Floorp Version: 10.6.2 (64-bit)

## Additional context

Background: I'm looking to add support for Floorp to Spybot - Search & Destroy (scanning browser content for malicious URLs / tracking cookies) and BrowsAlyzer (displaying and searching browser data). It is easier to support multiple browser versions of multiple browsers if we run them within a sandbox. Floorp support seems easy as it's standard Firefox, but I would prefer a fully working sandbox that creates cookies & cache as well, and for that, pages need to be opened.

**Comment by surapunoyousei** [comment]
Tried Firefox?

**Comment by surapunoyousei** [comment]
I think fx has same problem. 
![image](https://user-images.githubusercontent.com/73892113/200276482-9e0abcab-0d42-4af8-b5c8-15a09bc06c48.png)

**Comment by CCRDude** [comment]
Sure. Our software supports a bunch of browsers, for Mozilla/Firefox based ones it's Beonex, Firebird, Firefox, Flock, K-Meleon, Lolifox, Mozilla, Netscape 4.x, 6.x, PaleMoon, Wyzo, Tor Browser, Waterfox... plus a few of the non-browsers like Thunderbird, Postbox, Songbird. I just checked Waterfox and Tor Browser and both work (do not crash tabs). Will check Firefox next.

I was able to get it to run by telling sandboxie to
```
NoSecurityIsolation=y
NoSecurityFiltering=y
```
in the sandbox config file.

**Comment by surapunoyousei** [comment]
So the floorp is the only problem. Understood.

**Comment by surapunoyousei** [comment]
That option seems to work.

![image](https://user-images.githubusercontent.com/73892113/200278390-851a5d73-bafc-4f4d-8b04-a0db01519cf7.png)

**Comment by surapunoyousei** [comment]
Irrelevant console output.
![image](https://user-images.githubusercontent.com/73892113/200278691-0c82fb7d-5c8f-44bf-804e-1c98cc770fd4.png)

**Comment by CCRDude** [comment]
I just installed Firefox, fresh downlaod, 106.0.5 (64-bit) in a fresh Sandbox. It works fine, tabs open correctly.
I re-installed Floorp, same issue.

The only difference seems to be that Floorp is using a profile within the sandbox, while Firefox is accessing the pre-existing profile outside.

Will check if I can reproduce the issue in Firefox if the host has no Firefox profiles.

**Comment by surapunoyousei** [comment]
I tested it in an environment where both were newly installed, but it seems to be working

**Comment by surapunoyousei** [comment]
I'm closing this issue as it seems to work fine.
