### ISSUE TITLE
[Bug]: remove "backward"or"forward" icon from the tool bar will cause unable to use floorp.

### ISSUE THREAD

**Issue by boringl** [Floorp-Projects/Floorp#1222]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

remove "backward"or"forward" icon from the tool bar will cause unable to use floorp.

### Reproduction Steps

just remove the "backward"or"forward" icon from the tool bar

### Expected Behavior

will working properly

### Actual Behavior

unable to use floorp which means can not open any website.

### Screenshots

![图片](https://github.com/Floorp-Projects/Floorp/assets/57058206/85b8b6b0-a9fe-43e2-8cb8-30d21e372f36)

### Browser Version

11.14

### Operating System

wingdows

**Comment by CutterKnife** [comment]
Please check v11.14.1.

**Comment by surapunoyousei** [comment]
Already fixed
