### ISSUE TITLE
[Bug]: Can't change workspace icon

### ISSUE THREAD

**Issue by matijazinic** [Floorp-Projects/Floorp#1223]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Changing workspace icon simply doesn't work, icon remains default one

### Reproduction Steps

1. Create new workspace
2. Change the icon and save the changes
3. Default icon remains - no changes applied

### Expected Behavior

Workspace icon is supposed to change to whatever user picks.

### Actual Behavior

Icon doesn't change, the default one remains.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/113105344/5f251df5-74be-4605-813c-d99f7e10dce5

### Browser Version

11.14.0

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
I deploy new version of Flooorp Try it!
