### ISSUE TITLE
[Bug]:  Show sidebar button removal not persistent.

### ISSUE THREAD

**Issue by thoth-amon** [Floorp-Projects/Floorp#1225]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Show sidebars button reappears in the same place every browser restart despite being removed,

### Reproduction Steps

1. Open Browser
2. Remove "show sidebars" button which is next to the back button.
3. Close and Restart Browser.

### Expected Behavior

Removing the show sidebars button is persistent.

### Actual Behavior

Removing the show sidebars button is not persistent.

### Screenshots

![Screenshot_20240614_214946](https://github.com/Floorp-Projects/Floorp/assets/78971907/a44de9a7-a461-42db-9972-0fcac1f023c6)

### Browser Version

11.14.1

### Operating System

OpenSuse Tumbleweed.

**Comment by guigirl42** [comment]
I can confirm this new bug, which only arose with `v11.14.0`, & persists with `11.14.1.` 

Removing the icon does _not_ help, pinning it to the `Overflow Menu` does _not_ help, moving it to the `Bookmark Bar` does _not_ help. In all cases, after some period of time [measured in minutes or hours, not days], the `Show sidebars` icon returns to the lefthand end of the url bar. 

There is a second symptom of this new bug. Each time this unwelcome icon returns, the `Profile Manager` button stops obeying left-clicks, & thus cannot be used any more to open the dropdown menu & launch another profile.

**Comment by thoth-amon** [comment]
I managed to do a workaround by opening the "prefs.js" file, located in the profile folder,  in a text editor (make sure there are no instances of floorp open). I went to line 73, which shows a list of buttons. I deleted  `\"sidebar-button\",` and saved the file.  The change is persisting for now.

**Comment by guigirl42** [comment]
> the `Profile Manager` button retains correct functionality, until & unless the user opens any WebPanel in the Sidebar; immediately this operation breaks the `Profile Manager` button in the top bar.

Happy to report that this bug seems **fixed** now in Floorp Beta / Daylight `11.17.0` (64-bit) | Firefox: `128.1.0` :tada: 

Thank you.
