### ISSUE TITLE
custom font not working 

### ISSUE THREAD

**Issue by lost22git** [Floorp-Projects/Floorp#1227]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

custom font is working for firefox but not working for floorp

### Reproduction Steps

setting / fonts / advanced 

uncheck option： Allow pages to choose their own fonts, instead of your selections above

### Expected Behavior

page content should use custom font

### Actual Behavior

page content never use custom font

### Screenshots

![Screenshot 2024-06-16 011308](https://github.com/Floorp-Projects/Floorp/assets/65008815/acf7d25b-822c-437e-b2aa-8a1ada07f7bb)

## Floorp

![Screenshot 2024-06-16 011308](https://github.com/Floorp-Projects/Floorp/assets/65008815/e368e122-4f6b-4e5a-b39c-825ea8bdf9a3)

## Firefox

![Screenshot 2024-06-16 011308](https://github.com/Floorp-Projects/Floorp/assets/65008815/1a597e89-5923-4822-a905-93144c892df3)

### Browser Version

11.14.0

### Operating System

windows

**Comment by surapunoyousei** [comment]
Fingerprint protection is affecting to fonts

**Comment by lost22git** [comment]
Use https://webbrowsertools.com/font-fingerprint/
to detect fingerprint. Why is the fingerprint id generated by my floorp the same every time?

**Comment by lost22git** [comment]
I chose to use the addon `Font Fingerprint Defender` to resist font fingerprint.

And modify floorp confiig `layout.css.font-visibility.resistFingerprinting` from 1 to 3 to resolve this issue

**Comment by surapunoyousei** [comment]
Floorp's fingerprint measure is constant because it aims to make it difficult to identify users by matching their fingerprints with many users.

**Comment by ElSamhaa** [comment]
hi @surapunoyousei , can you elaborate further on what are the options here?

I've recently switched to floorp, and the experience is great so far. However, the default arabic fonts are very ugly and old. Switching to custom fonts for arabic is really a necessity. Is it possible to give the user the freedom to set the custom font or maybe you can change the arabic font by default from the installation?
