### ISSUE TITLE
[Bug]: youtube taking forever to load/wont load at all 

### ISSUE THREAD

**Issue by wammiereal** [Floorp-Projects/Floorp#1228]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

when ever i use youtube on floorp some times it takes forever for a video to load some times not loading at all and infinity loading 

### Reproduction Steps

go to youtube
click on a video  /open video in new tab (the problem happens more if i open a video in a new tab)

### Expected Behavior

click on video
it load

### Actual Behavior

click on video 
no load

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/172938879/16cf088e-d3a5-41b9-b40d-08d579b397b0)

### Browser Version

11.14.1 (64-bit)

### Operating System

windows 11

**Comment by regularentropy** [comment]
First, try updating uBlock filters. Sometimes this issue can occur because of those.
Second, try clearing the cache for YouTube.
Third, please check if the issue also occurs without extensions and with the cleared cache.

**Comment by wammiereal** [comment]
i have gone and done that and the issue still remains

**Comment by surapunoyousei** [comment]
Duplicate: https://github.com/Floorp-Projects/Floorp/issues/655
