### ISSUE TITLE
[Bug]: Keyboard Shortcuts are broken

### ISSUE THREAD

**Issue by Championers** [Floorp-Projects/Floorp#1229]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Whenever I try to change settings in Keyboard shortcuts it does not save as wanted to. The "Disable Mozilla Firefox's keyboard shortcuts" is put as off and when I try to turn it on it works, but when I leave settings and go back, it's back to being off.

Trying to type a shortcut does not entirely work. For example, trying to put "Open a new tab" as Shift + N does not do anything no matter which button I combine. Putting Ctrl or Shift + [any button] does nothing either. But putting Ctrl + Shift + [button] works (the only buttons that works though are 1-0, any special key and Y, U, F and V. No other letter does). Weirdly enough I can put Alt + [any button] and that works. Pressing spacebar does put the shortcut as an empty space, which means any time I press spacebar it does the action.
If I try to leave the shortcut empty, it reverts to whatever combination I put in. So "Open a new tab" is permanently put as Ctrl + Shift + @ now and I can only change it to another input, not remove it.

### Reproduction Steps

1. Open settings
2. Go to "Keyboard shortcuts"
3. Try to input a combination of key presses
4. Only allows Ctrl + Shift + [certain buttons], or Alt + [any button]
(optional) 5. Try to reset shortcut or enable "Disable Mozilla Firefox's keyboard shortcuts"

### Expected Behavior

I expect to go into the keyboard shortcuts and change to what shortcut I want.
If I want to leave a keybind empty, then it should stay empty

### Actual Behavior

Only certain type of combinations works.
Trying to leave a keybind empty reverts it back to the combination I last in

### Screenshots

![Screenshot 2024-06-16 033045](https://github.com/Floorp-Projects/Floorp/assets/172943666/5eb4f40a-d959-417d-ba0b-7a1d6ee277e1)

### Browser Version

Floorp 11.14.1 (64-bit)

### Operating System

Windows 11, version 23H2

**Comment by surapunoyousei** [comment]
All keyboard shortcuts registered with Windows and other systems are no longer available.

These vary depending on the environment.
