### ISSUE TITLE
[Bug]: Yokoffing Securefox and Default block Mozilla sign-in

### ISSUE THREAD

**Issue by tailwhipstruggle** [Floorp-Projects/Floorp#1230]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

On my laptop and desktop running Fedora 40 Workstation and Bazzite respectively, I downloaded the Floorp flatpak and used Flatseal to enable access to home directory. I then set up the browser and noticed that I could not log in with the Yokoffing Default user.js applied, and clicking Apply on the Floorp Default did not fix this issue. I then navigated to about:profiles for further testing, and verified the issue exists with Yokoffing Securefox as well, however with this profile clicking 'Apply' on Floorp Default lets you log in. On Yokoffing Securefox and Default, if you try to log in you get hung on the email entry with a red "Working..." message. The other profiles appear to not have this issue, and only Yokoffing Default makes it to where you need a new profile to log into a Mozilla account at all.

### Reproduction Steps

On Fedora 40 Workstation and Bazzite:
1: Download Floorp from Flathub
1.5: Use Flatseal to enable access to home directory (optional, but required to be able to view profile folders)
2: Open Floorp and navigate to about:profiles for easier troubleshooting/profile generation
3: Create a new profile and open in new window
4: Click the "Firefox Account" icon at the top right
5: Type a valid firefox email and observe that it now asks for a password
6: Open a new tab and navigate to settings
7: In setting search "user.js" and apply Yokoffing Securefox and wait for the browser to relaunch
8: Go back to the Mozilla login and enter a valid firefox email and observe the red "Working..." error indicator
9: Apply Floorp Default user.js
10: Go back to the Mozilla login and type a valid firefox email. Observe that if it is the same one as in the 5th step, it is offered as an autocomplete (this did not happen in step 8). Observe that you can now get the to password entry screen
11: In the same profile or a new one (doesn't matter), apply Yokoffing Default user.js
12: Go back to the Mozilla login and type a valid firefox email. Observe the same result as step 8
13: Apply Floorp Default user.js
14: Go back to the Mozilla login and type a valid firefox email. Observe that the red "Working..." error indicator persisted this time even though applying Floorp Default previously fixed the issues observed after applying Yokoffing Securefox
15: Create a new profile in the other firefox window and open it in a new window
16: Click the Mozilla account icon to sign in fully
17: Apply Yokoffing Default from the settings as before and observe that when the browser reloads the user is signed out

### Expected Behavior

I expect to be able to log into Mozilla accounts with any of the user.js profiles provided. I also expect not to be signed out of my Mozilla account and unable to log back in if I apply one of the user.js presets. I do not know if this is a Flatpak and/or Fedora issue specifically but since there is no official copr and the community ones are out of date I would prefer for this option to work.

### Actual Behavior

Floorp with the Yokoffing Securefox and/or Default user.js presets applied prevents Mozilla login and signs the user out if they are already logged in. For some reason you can recover a profile that has applied Securefox by simply applying a preset that isn't Yokoffing Securefox/Default, however in my testing applying Default made the profile permanently unable to sign into a Mozilla account regardless of which user.js you tried to apply over it. Since it happened on both of my devices rather than just using normal Firefox I made a report.

### Screenshots

![working](https://github.com/Floorp-Projects/Floorp/assets/122512499/8941e1a6-432a-46f6-a707-9efa729becfe)

### Browser Version

11.14.1

### Operating System

Fedora 40 Workstation / Bazzite

**Comment by surapunoyousei** [comment]
This is a natural consequence of changing your settings to protect your privacy.

Please submit this as a feature request.
