### ISSUE TITLE
[Bug]: Web Renaissance Theme Doesnt Work on Floorp

### ISSUE THREAD

**Issue by Felipefpl** [Floorp-Projects/Floorp#1232]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

This theme isnt applied on floorp https://addons.mozilla.org/en-US/firefox/addon/a-web-browser-renaissance/

### Reproduction Steps

1 - Go to theme's site.

2 - Apply the theme.

### Expected Behavior

The theme should be applied.

### Actual Behavior

The theme isnt applied. The interface become totally white.

### Screenshots

![2024-06-16 08_57_57-Greenshot](https://github.com/Floorp-Projects/Floorp/assets/5569804/e6b16c60-94b1-4638-b223-4b4d6a498f37)

### Browser Version

11.14.1

### Operating System

Win10

**Comment by surapunoyousei** [comment]
We do not support any extensions other than a few well-known ones. Please understand that we do not support other than some well-known extensions.

**Comment by yawns** [comment]
@Felipefpl 

None of the themes created by that user work when you have the old Lepton UI enabled. If you switch to the Proton UI and then apply the theme, it works. You can then switch back to Lepton and still have it.

The themes don't take the sidebar into account though, so you'll maybe want to fix that with css or something.

<img width="1512" alt="Screenshot 2024-06-19 at 2 01 01 PM" src="https://github.com/Floorp-Projects/Floorp/assets/2416785/160ce84e-2c35-42c4-a2ad-00cc401e273a">
