### ISSUE TITLE
[Bug]: Closing the last tab in a workspace opens a tab from another workspace

### ISSUE THREAD

**Issue by Korydween** [Floorp-Projects/Floorp#1233]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When several workspaces exist with tabs open, and only one tab remains in the workspace currently in use, closing this tab will open a tab from the other workpace.
 

### Reproduction Steps

1. Create at least two workspaces
2. Open several tabs in Workspace 1
3. Go to Workspace 2
4. Close all tabs in the Workspace 2
5. When the last tab is closed, a tab from Workspace 1 is brought to Workspace 2

### Expected Behavior

I would expect that a new tab opens in the current workspace when the last tab is closed.

### Actual Behavior

When the last tab of the current workspace is closed, Floorp opens a tab from another workspace.

### Screenshots

In a new Floorp without any add-on and on a new profile, I created two workspaces: 
![image](https://github.com/Floorp-Projects/Floorp/assets/15924179/f79509ca-65d8-4884-819e-9a32f402327b)

The default workspace only have one tab open :
![image](https://github.com/Floorp-Projects/Floorp/assets/15924179/e874b7fb-e082-4897-9386-081358573aaf)

The other workspace has two tabs open:
![image](https://github.com/Floorp-Projects/Floorp/assets/15924179/9df4fb31-f240-4c2d-843b-0eb6d2b316db)

If I click "close tab" on the default workspace, the tab from the other workspace is opened. I would expect a new tab to open:
![image](https://github.com/Floorp-Projects/Floorp/assets/15924179/ff06381a-3cec-46d9-b080-11c822c7c615)

If I close again this tab, the other tab from the other workspace opens: 
![image](https://github.com/Floorp-Projects/Floorp/assets/15924179/8071e54c-d1e5-4d72-bebb-781359bf2fb6)

And the "reddit" tab was also closed in the other workspace:
![image](https://github.com/Floorp-Projects/Floorp/assets/15924179/27e0bbd3-e96c-4788-8123-44211f0de1d2)

I tested and the problem is the same the other way round so it does not depend if Default is empty or the other workspace is empty

### Browser Version

11.14.1 (64-bit)

### Operating System

Ubuntu 24.04

**Comment by surapunoyousei** [comment]
Deplicate

**Comment by Kagukara** [comment]
@surapunoyousei I've tried searching for open "workspace" issues but couldn't find one related to this one. Do you have a link for where I can follow the duplicate? This is still an ongoing issue with floorp.

> ### Bug Summary
> When several workspaces exist with tabs open, and only one tab remains in the workspace currently in use, closing this tab will open a tab from the other workpace.

**Comment by mouarfff** [comment]
Same bug after years...

Same issue here
Last version from flatpak

I juste lost 1000tabs with 20 workspace


...........

**Comment by codigoisaac** [comment]
Hi there folks. This is an annoying problem I am also having. Gotta remember to open a new tab every time I will close the last one in a workspace.

I am on version 12.12.0
