### ISSUE TITLE
[Bug]: Smooth scrolling broken on some websites

### ISSUE THREAD

**Issue by UltraBlackLinux** [Floorp-Projects/Floorp#1235]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The smooth scrolling behaviour within floorp is broken. It appears that it's not just a visual effect but it's actually sending a ton of scroll events for the animation, which breaks on some websites like discord (I've also seen this happen on a news outlet's website)

### Reproduction Steps

1. Open discord
2. Scroll up

### Expected Behavior

it should stay where it is, like with smooth scrolling disabled

### Actual Behavior

discord jumps around weirdly and resets the scroll progress partially

### Screenshots
Mostly single scrolling steps:

https://github.com/Floorp-Projects/Floorp/assets/62404294/5073b432-7642-4b33-8ac2-76124eee2a5a

### Browser Version

11.14.1

### Operating System

Arch Linux

### Additional Context

(I'd also really like to know why the scrolling steps for non-smoothed scrolling are this ginormous. non-smoothed scrolling is so disorienting, and it's not been like this forever I'm pretty sure)

**Comment by surapunoyousei** [comment]
Is it wayland?

**Comment by UltraBlackLinux** [comment]
yes, should have mentioned that.

**Comment by surapunoyousei** [comment]
Current version is not support Wayland. Wait for Floorp 12

**Comment by UltraBlackLinux** [comment]
Ok will do, thanks for the info :)
