### ISSUE TITLE
[Bug] Theme menu just shows extensions.

### ISSUE THREAD

**Issue by TooSpooky** [Floorp-Projects/Floorp#124]
## Describe the bug
In the settings menu, "Themes" just shows the extensions page instead of showing themes.

## To Reproduce
1. Go to 'Settings'
2. Click on 'Themes'

## Expected behavior
When clicking on "Themes" it shows themes instead of extensions.
## Screenshots
![image](https://user-images.githubusercontent.com/21211292/201452933-d0bdb9e5-8338-4152-a995-fcd453d4b05c.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Floorp Version: 10.6.2

**Comment by surapunoyousei** [comment]
Did you try it with your new profile?

**Comment by TooSpooky** [comment]
Hey,

Tried it on a totally new profile and it's fine actually. But on my current and also the default one you start with it's bugged.

**Comment by kaonasi-biwa** [comment]
Are you seeing errors in the Web Developer Tool?

**Comment by TooSpooky** [comment]
I'm unfamiliar with any web developer tool sadly. Also just noticed an extension or two's options pop-out is cut off as well, but is fine on a new fresh profile.

**Comment by kaonasi-biwa** [comment]
Please open the Web Developer Tool, open the Console tab, and take a screenshot
That's all I need.
![image](https://user-images.githubusercontent.com/85387717/201498220-70edcfe2-4529-4f40-92fe-000e1b41487f.png)

**Comment by TooSpooky** [comment]
Ah I see. Huh, doesn't seem to be throwing out any errors.

<img width="1378" alt="steam_SZLbq3Vu0f" src="https://user-images.githubusercontent.com/21211292/201498348-e24f6f1c-3836-49b3-be5f-9b28c62cd9b2.png">

**Comment by kaonasi-biwa** [comment]
umm...

**Comment by kaonasi-biwa** [comment]
Did you use Dual Theme?

**Comment by TooSpooky** [comment]
Dual Theme?

The current theme i'm using is this one (without the css it links)
https://addons.mozilla.org/en-US/firefox/addon/edge-grey-blue/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

Installed it on a new profile and it doesn't seem to cause issues.

**Comment by kaonasi-biwa** [comment]
umm...
Please open `about:config`, and show me `floorp.dualtheme.theme` and `floorp.enable.dualtheme`
![image](https://user-images.githubusercontent.com/85387717/201499007-8d3db66e-c738-46b4-988f-469bb75120ea.png)

**Comment by TooSpooky** [comment]
![image](https://user-images.githubusercontent.com/21211292/201499365-bd1df9f6-7290-4cc6-b091-5cdddf464b44.png)

**Comment by kaonasi-biwa** [comment]
OK
Umm...

**Comment by kaonasi-biwa** [comment]
Please tell me your using extensions?
(Include disabled extensions)

**Comment by TooSpooky** [comment]
Haha, I use a stupid amount of extensions. On top of currently trying a few trying to find a few things I want. So not the easiest thing to comb through. Although I do have a librewolf install that pretty much mirrors my floorp install extension wise and it doesn't have this issue. Worst comes to worst I can just setup a new profile haha. Appreciate the troubleshooting a lot. 
![extensions](https://user-images.githubusercontent.com/21211292/201499703-2ff5c020-d773-4f23-a169-5a092e1ea6c6.png)

**Comment by kaonasi-biwa** [comment]
Thank you
Do you remember installed themes?

**Comment by TooSpooky** [comment]
No problem. No I don't sadly, I tested a few of them but can't remember off the top of my head. The default-default profile which has the same issue has only the default extensions and I believe the default themes.

**Comment by kaonasi-biwa** [comment]
Thank you

Umm...I can't understand...

**Comment by TooSpooky** [comment]
Might have to just call it a fluke haha. Thanks again. I did also possibly discover an incompatibility with panorama tab group but I need to actually see if that's not just me missing something clear haha and also it may be with tree style tabs itself or something else so not really your purview.

**Comment by TooSpooky** [comment]
Hilariously enough I just saw the pre-release update pushed and tried that. Issue is fixed with regard to the theme page. Extension options are still cut off but that's fixed with a new profile.

Take care!

**Comment by kaonasi-biwa** [comment]
OK!!
Thank you!
