### ISSUE TITLE
[Bug]: Hotkey persists even after removing it

### ISSUE THREAD

**Issue by Oneechan69** [Floorp-Projects/Floorp#1240]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Reproduction Steps

1. Go to Settings > Keyboard Shortcuts
2. Change "Show synced tabs sidebar" to `CMD + OPT + Left arrow key`
3. Unfocus the box for the shortcut, then press `CMD OPT Left`
4. Go back to the setting and press `delete` (on Mac keyboard, next to `+` key)
5. Press `CMD OPT Left` again and see the synced tabs sidebar appear again

This happens even after I clear the hotkey and restart floorp. A workaround I found is to install Daylight, run the Floorp profile on it (after closing regular Floorp), remove the hotkey on it, close it, and relaunch regular Floorp with said profile.

### Expected Behavior

Removing the hotkey is supposed to make it not trigger again

### Browser Version

11.14.1 - Regular Floorp

### Operating System

macOS 14

**Comment by surapunoyousei** [comment]
This issue will fix at Floorp 12

**Comment by YousufSSyed** [comment]
@surapunoyousei I think you really should release a fix once you come up with one, since this really breaks users workflows.

**Comment by surapunoyousei** [comment]
That is difficult because there is no other way to revert to the old way.

I am committed to Floorp 12 and send PRs to it on a daily basis.

If anyone can fix it, I would like to merge it and release it.

**Comment by surapunoyousei** [comment]
CSK will be reverted in the next release

**Comment by nyanrus** [comment]
@YousufSSyed 
author of new CSK here!
could you give me the two configs that after you register and after you unregistered?
https://github.com/Floorp-Projects/Floorp-core/blob/main/nora%2Fsrc%2Fpreferences%2Fcsk%2Fsetkey.ts#L56-L56
the config key is here, and the config value can found on about:config

**Comment by yz47** [comment]
How do I adopt the fix to 11.5?
