### ISSUE TITLE
[Bug]: ffmpeg 7.0 does not work with Floorp 11.14.1 (live videos do not play)

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#1241]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Recently in my linux distribution ffmpeg was updated to version 7.0, however after this update floorp stopped playing live video from youtube. I downgraded the ffmpeg package to version 6 and the problem is solved.

### Reproduction Steps

1.Use the latest version of floorp
2.Upgrade ffmpeg to version 7.0 or higher.
3. Go to youtube and play a live video
4.Video does not play and an error is displayed

### Expected Behavior

Live video plays without problems

### Actual Behavior

The video does not play and an error message appears.

### Screenshots

![](https://assets-prod.sumo.prod.webservices.mozgcp.net/media/uploads/images/2020-07-08-15-48-37-e83eae.png)

### Browser Version

11.14.1

### Operating System

Artix Linux (Arch Linux) Linux 5.15.160

### Additional Context

I report this problem although I don't know if it will be fixed for this version of floorp since they had mentioned that now floorp was going to be based on the current version of firefox which doesn't have this problem.

**Comment by kaos-55** [comment]
I just tried the ESR version of Firefox and it also has the same problem with ffmpeg 7.0.
I don't know what to do, I guess the "Bug" should be closed since apparently the problem is with the ESR base of Firefox and not directly from Floorp.

**Comment by creeper-0910** [comment]
Please wait for Floorp12.
