### ISSUE TITLE
[Bug]: "Show Sidebar over website content" doesn't work properly when the sidebars are on the right

### ISSUE THREAD

**Issue by mbugrayilmaz** [Floorp-Projects/Floorp#1242]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I had another thread opened but it was closed because it was a Lepton related issue, but as I stated below, Lepton itself doesn't have this issue. Here's the other thread: https://github.com/Floorp-Projects/Floorp/issues/1196

When you select "Show Sidebar over website content", but also set the sidebars to show up on the right, the sidebars seem to still expand to the right, outside of the browser.

I also tested this in Firefox by installing Lepton UI to my Firefox setup and it works there with no problems. So this could be a Floorp specific Lepton configuration.

### Reproduction Steps

1. Select "Move sidebar to the right" from the sidebar header
2. Enable "Automatically hide Sidebar" from Lepton Settings
3. Enable "Show Sidebar over website content"

### Expected Behavior

When you hover over the hidden sidebar on the right, it should expand to the left, making the whole thing visible

### Actual Behavior

The sidebar expands to the right, nothing happens

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/8601972/47be23da-0f49-4284-97ea-1e8e4b0760a1

### Browser Version

11.14.1

### Operating System

Windows 11

### Additional Context

I tried different sidebars other than Sidebery like history, bookmarks etc. but the result is the same. I also tried toggling Browser Manager Sidebar but that didn't change anything

**Comment by surapunoyousei** [comment]
This is a feature of Lepton, and the Lepton authors note that this is intentional
