### ISSUE TITLE
[Bug]: Custom Image not displaying on the first new tab of the browser when "Open previous windows and tabs" is unchecked

### ISSUE THREAD

**Issue by Perseus333** [Floorp-Projects/Floorp#1244]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When the setting: "Open previous windows and tabs" is disabled, and a custom image is selected on the Floorp Home Background, the image does not display, instead, it uses a non-valid url as its background.

This only happens in the first about:home opened in the browser. If another instance of the profile is open, the bug does not occur.

### Reproduction Steps

1. Create a new profile
2. Select a custom image for the new tab by using the about:preferences#home
3. Disable "Open previous windows and tabs"
4. Close the window or all the tabs
5. Start the profile again

### Expected Behavior

Custom Image appearing as the background of the home page

### Actual Behavior

Solid black color where the custom image should be

### Screenshots

Expected Behaviour:
![image](https://github.com/Floorp-Projects/Floorp/assets/81527705/800ace95-4142-4413-a9ab-79fc683b0538)

Actual Behaviour:
![image](https://github.com/Floorp-Projects/Floorp/assets/81527705/ecbe34f0-feb1-4f5d-8e8b-b1f2d9cfdc4e)

Console:
![image](https://github.com/Floorp-Projects/Floorp/assets/81527705/110f70d5-5b58-400b-afc4-a750d8e439b5)

### Browser Version

11.14.1

### Operating System

Windows 11

### Additional Context

It only affects the first home page of a profile and always happens.

The URLs seem to be the same (although randomized):

Working url:
blob:null/a530871f-260b-47ef-9ca0-1eb1cb46f608

Not Working url:
blob:null/7eb414b1-cd9a-45d0-a5a5-c06a2627d8f1

Also, I get this from the console:
```
1719402342597	addons.xpi	WARN	Checking C:\Program Files\Ablaze Floorp\distribution\extensions for addons

The webRequest.addListener filter doesn't overlap with host permissions. ext-webRequest.js:49
CSK Init Completed content.js:15:13

add window content.js:24:15

Object { initialized: true } content.js:450:11

[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: jar:file:///C:/Program%20Files/Ablaze%20Floorp/browser/features/floorp-system@floorp.ablaze.one.xpi!/API/aboutConfigPrefs.js :: getBoolPref :: line 58"  data: no] aboutConfigPrefs.js:58:33

LoginHelper(Main): Couldn't parse specified uri about:home with error NS_ERROR_FAILURE LoginHelper.sys.mjs:693:18

Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml

This Event is registered in System: [object KeyboardEvent] 4 content.js:61:19

NotFoundError: No such JSWindowActor 'DevToolsFrame'

LoginHelper(Main): Couldn't parse specified uri blob:null/7eb414b1-cd9a-45d0-a5a5-c06a2627d8f1 with error NS_ERROR_FAILURE LoginHelper.sys.mjs:693:18

This Event is registered in System: [object KeyboardEvent] 3 content.js:61:19
```

The issue most likely has to do with this:
`LoginHelper(Main): Couldn't parse specified uri blob:null/7eb414b1-cd9a-45d0-a5a5-c06a2627d8f1 with error NS_ERROR_FAILURE LoginHelper.sys.mjs:693:18`

Also, this is nothing new of any recent update. This has been happening to me for the last few months.

**Comment by TheChilledBuffalo** [comment]
This was already reported here #619 

A fix couldn't be found this issue, but changing the value of `browser.startup.homepage.abouthome_cache.enabled` to `false` in `about:config` does seem to be a temporary solution.

**Comment by Perseus333** [comment]
I see. I'm sorry for the duplicate bug. It's a shame that no fix could be found.

**Comment by TheChilledBuffalo** [comment]
> It's a shame that no actual fix could be found.

Definitely try changing the value of that pref I sent earlier. It does work well.
