### ISSUE TITLE
[Bug]: Floorp doesn't start after profile chosed. Glxtest crash

### ISSUE THREAD

**Issue by marek2001** [Floorp-Projects/Floorp#1246]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I could start floorp firstly but next day it didn't started with glxtest crash.

### Reproduction Steps

Click to start browser. Chose profile. And it doesn't start
![obraz](https://github.com/Floorp-Projects/Floorp/assets/78016853/4c33f02f-995b-432b-93ea-ca9080b97913)

### Expected Behavior

Browser started

### Actual Behavior

It doesn't start.

### Screenshots

![obraz](https://github.com/Floorp-Projects/Floorp/assets/78016853/945860fc-ca8a-48a7-8ece-7ea32e91adde)

### Browser Version

Latest

### Operating System

Nobara linux

### Additional Context

I use flatpak version.

**Comment by surapunoyousei** [comment]
This bug seems to be environment-specific.

I don't use Linux much, so I can't support it.

My apologies.
