### ISSUE TITLE
[Bug]: Spoofing user agent is not effective if OS is changed

### ISSUE THREAD

**Issue by stilgarwolf** [Floorp-Projects/Floorp#1249]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Spoofing user agent conflicts with script variable [window.navigator](https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator) when the specified operating system is changed.

Same  for Browser.

### Reproduction Steps

1. For Linux computers
2. Set user agent to "Spoof Chrome on Windows"
3. Check the reported True Operating System Core at https://www.deviceinfo.me

### Expected Behavior

True Operating System Core:
Windows 10 or 11 version 10.0 (64-bit), or Windows Server 2016 or 2019 or 2022 version 10.0 (64-bit)
. . .
True Browser Core:
Chrome version 125.0.0.0 (Engine: Blink)

### Actual Behavior

True Operating System Core:
Linux x86_64
. . .
True Browser Core:
Firefox

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/63443198/bcebc883-30ed-4e9b-b6bb-29e78a2171ef)

### Browser Version

11.14.1 (64-bit)

### Operating System

Linux (Debian SID)

### Additional Context

Try Chameleon extension which works better:
True Operating System Core:
Unknown. Detection not supported or is blocked by browser setting(s)/extension(s).
. . .
True Browser Core:
Chromium

**Comment by regularentropy** [comment]
The included user agent changer is obsolete. Please use extension.

**Comment by stilgarwolf** [comment]
I'm already using Chameleon
