### ISSUE TITLE
[Bug]: Private Window icon takes up way too much space with vertical tabs

### ISSUE THREAD

**Issue by Hate9** [Floorp-Projects/Floorp#1256]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When in a private window with vertical tabs enabled, the "private window" icon is horizontally next to the tab-list, taking up a *bunch* of UI space for no apparent reason.

### Reproduction Steps

1. Enable vertical tabs
2. Restart
3. Open a private window

### Expected Behavior

The icon should be below the tabs, not next to them.

### Actual Behavior

The icon is beside the tabs, which looks weird and makes the tab text less readable.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/4684153/369148c6-73f5-4a2c-923a-996ce6e1c5b8)

### Browser Version

11.14.1

### Operating System

Arch Linux

**Comment by surapunoyousei** [comment]
Do you use Custom CSS?

**Comment by Hate9** [comment]
I do not.

**Comment by surapunoyousei** [comment]
Fixed
