### ISSUE TITLE
[Bug]: Floorp not detecting headset mic

### ISSUE THREAD

**Issue by huang-jy** [Floorp-Projects/Floorp#1258]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

In Google Meet (might also be the case for other similar video-calling sites, Floop does not detect the microphone in my headset (Soundcore Q30)

![image](https://github.com/Floorp-Projects/Floorp/assets/2756283/f73a4b02-7c59-466f-828f-3eada1a7cd78)

In Firefox 127.0.2, the microphone is detected and can be used:

![image](https://github.com/Floorp-Projects/Floorp/assets/2756283/20dcdeba-2c09-49cd-89ac-6ea47d580329)

Running Floorp 11.14.1 on Fedora 39 via flatpak installation. Also verified against the portable version (tar.bz version)

### Reproduction Steps

1. Run Floorp and access Google Meet, or Jitsu or some site that requires access to your microphone
2. List the detected microphones
3. Find your headset mic missing

### Expected Behavior

As shown in post, expected to see my mic I the available list

### Actual Behavior

Mic option missing from  list

### Screenshots

Shown above

### Browser Version

11.14.1

### Operating System

Fedora 39

### Additional Context

Verified with flatpak and portable builds

**Comment by CutterKnife** [comment]
Does it work properly with Firefox ESR 115.13.0? (just checking)

**Comment by huang-jy** [comment]
FF ESR 15.12.0esr confirmed does have it listed. 

![image](https://github.com/Floorp-Projects/Floorp/assets/2756283/ad937ee3-557f-4145-bc5a-4782bd93c965)

**Comment by surapunoyousei** [comment]
Is it Flatpak?

**Comment by huang-jy** [comment]
> Is it Flatpak?

Both flatpak and portable ( `.tar.bz2` ) have this issue

**Comment by huang-jy** [comment]
Additionally, Floorp version 11.15.0 via Flatpak now doesn't detect ANY mic:

![image](https://github.com/user-attachments/assets/eb53fcb1-2410-47ea-b22e-2375cf3b1df2)

But portable Floorp (the `tar.bz2` version) does

![image](https://github.com/user-attachments/assets/fea3ccc2-34df-4ac8-9ad0-10a8d582b209)

**Comment by surapunoyousei** [comment]
Please try Floorp 11.17.0

**Comment by huang-jy** [comment]
Downloaded v11.17.4 and it detected my headset mic, but floorp crashed as soon as I selected it.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1375

**Comment by creeper-0910** [comment]
Please submit any logs of crash.

**Comment by huang-jy** [comment]
Well, I'm not sure how to get those.

However, when I tried to run floorp from a terminal and do the switch of the mic, only one message showed in the terminal:

`[Parent 199659, IPC I/O Parent] WARNING: process 200117 exited on signal 11: file /home/runner/work/Floorp/Floorp/ipc/chromium/src/base/process_util_posix.cc:335`
