### ISSUE TITLE
[Bug]:  Floorp pdf viewer/editor is not same as Firefox pdf viewer/editor

### ISSUE THREAD

**Issue by avcolar** [Floorp-Projects/Floorp#1262]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp PDF viewer/editor
![image](https://github.com/Floorp-Projects/Floorp/assets/22657728/45c54562-835d-489a-a87a-53fd9cdab9af)

Firefox PDF viewer/editor
![image](https://github.com/Floorp-Projects/Floorp/assets/22657728/429c9a9a-a782-4a19-9bfb-f005c8a85124)

### Reproduction Steps

1. Open Floorp browser
2. Drop a pdf file to Floorp browser
3. Open Firefox browser
4. Drop a pdf file to Firefox browser

### Expected Behavior

Floorp PDF viewer/editor should have the same features as Firefox PDF viewer/editor

### Actual Behavior

Floorp PDF viewer/editor does not have the same features as Firefox PDF viewer/editor

### Screenshots

Floorp PDF viewer/editor
![image](https://github.com/Floorp-Projects/Floorp/assets/22657728/1b2c5296-6847-473e-ac35-a0322afc31b2)

Firefox PDF viewer/editor
![image](https://github.com/Floorp-Projects/Floorp/assets/22657728/d87786d8-1693-4424-b73c-a0d6f61ce333)

### Browser Version

11.14.1 64 bit

### Operating System

Windows 10

**Comment by CutterKnife** [comment]
Changes to the PDF viewer/editor in Firefox 116 or higher are not implemented in Floorp, which is based on ESR 115.
