### ISSUE TITLE
[Bug]: Enter doesn't work in sidebar for some website like ChatGPT and Claude

### ISSUE THREAD

**Issue by DivineMK** [Floorp-Projects/Floorp#1263]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Enter key doesn't work for some websites in sidebar like ChatGPT, Claude but does work normally for Gemini, Whatsapp...

### Reproduction Steps

1. Add websites to sidebar
2. Try Enter

### Expected Behavior

Enter works

### Actual Behavior

It doesn't :(

### Screenshots

.

### Browser Version

11.14.1

### Operating System

Linux Mint 21.3

**Comment by regularentropy** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/89523758/0993dc0f-b333-49c0-bde7-4c5a0d14496a)
Cannot confirm.

**Comment by surapunoyousei** [comment]
This is the specification on the Chat Bot website. This is the case when it comes to the mobile version of the website

**Comment by DivineMK** [comment]
I am using the desktop version actually.

**Comment by surapunoyousei** [comment]
it means mobile layuout

**Comment by tom-gora** [comment]
Expected behaviour as implemented in those websites on mobile layout. Use tab, enter as workaround

**Comment by DivineMK** [comment]
Tab actually works very well for my use. Thank you!

**Comment by GollyJer** [comment]
Is this working for anyone else? I'm on Windows 11 and when I do a Tab, Enter, nothing is submitted and the cursor is put back into the chat input box.
