### ISSUE TITLE
cookies/sitedata save exceptions

### ISSUE THREAD

**Issue by flamesred** [Floorp-Projects/Floorp#127]
## Describe the bug
when I try to input a URL into the "Manage exceptions" in the "Cookies and Site Data" section, save it, and then close and open the browser, but it doesn't save the URL inputted 

## To Reproduce
1. Go to 'Settings'
2. Click on 'Privacy & Security'
3. Scroll down to 'Cookies and Site Data'
4. See error 'Input URL into Manage exceptions, Allow, and save it'
5. open, and close browser and repeat 1-4 to check if URL is saved.

## Expected behavior
URLs to be saved in 'Manage exceptions' when browser is opened and closed

## Desktop (please complete the following information):
 - OS: [Zorin OS 16.2 x86_64]
 - Floorp Version: [10.7.0]

**Comment by surapunoyousei** [comment]
Hmm. Do you use Flatpak？

**Comment by flamesred** [comment]
> Hmm. Do you use Flatpak？

yes
