### ISSUE TITLE
[Bug]: New tab is not working (Linux)

### ISSUE THREAD

**Issue by melroy89** [Floorp-Projects/Floorp#1272]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I installed Floorp for the first time under Linux Mint....

And the new tab is not working at all.

Enabling the menu bar and clicking on "new tab" doesn't work. Also the shortcut Ctrl+T doesn't do anything.

### Reproduction Steps

1.Remove your Floorp browser completely. Remove all Floorp config files from your machine.
2.  Install the latest Floorp x86-64 Linux binary from scratch for the first time. I used the download page to download the tar.gz.
3. Select "Advanced user" during setup. And I selected the "Native Desktop Theme" (the first one, Lepton UI)
4. Try to open a new tab (or use ctrl+t)
5. It won't work.....

### Expected Behavior

New tabs should work from the beginning. Maybe because there was no "Default" workspace present the first start-up?

### Actual Behavior

New tab does nothing.

I don't see any errors in the console log either.

### Screenshots

There is nothing to show on a screenshot, since the new tab doesn't work. 

### Browser Version

11.15.0 (64-bit)

### Operating System

Linux Mint 21.3

### Additional Context

Restarting the browser or creating a new window (thus creating a new process) seem to fixed it.

However, the first time experience was not good, since the first time I opened the tab (eg. Ctrl+T) wasn't working for me at all..

**Comment by melroy89** [comment]
Also pressing the "Profile Manager" icon didn't work during the first start-up. It did nothing basically.

**Comment by surapunoyousei** [comment]
I cannot find this bug. Please send more information.

**Comment by melroy89** [comment]
I have a very detailed reproduction steps.
