### ISSUE TITLE
[Bug]: Conflict between floorp and battleye v11.15.0

### ISSUE THREAD

**Issue by Wuest3nFuchs** [Floorp-Projects/Floorp#1273]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

**PUBG** a free to play game on steam closes itself because of the last update their seems to be a **conflict between floorp and battleye anticheat.**
https://imgur.com/a/pubg-floorp-issue-MScVwOI

**Steam Discussion:**
https://steamcommunity.com/app/578080/discussions/1/4514379280324289166/

### Reproduction Steps

every time you try to play

### Expected Behavior

The game stops and closes.
Strange thing is when i change the default browser back to firefox the game works!
And it's since the last update.

### Actual Behavior

https://imgur.com/a/pubg-floorp-issue-MScVwOI

### Screenshots

![i_view64_BW1ikb6LGh](https://github.com/user-attachments/assets/8ef0b708-f4ce-486e-a163-8ac9deeca899)

### Browser Version

v11.15.0

### Operating System

Windows 10 22H2 Build 19045.4651

### Additional Context

Is it possible to install the older versions and uncheck auto updates?

**Comment by regularentropy** [comment]
Check if this issue also occurs in Firefox ESR 115

**Comment by Wuest3nFuchs** [comment]
Hi,
testing Firefox ESR 115 right now report back asap.

**Comment by regularentropy** [comment]
I don't think so, add-ons cannot influence anticheat in any possible way.
I can suppose it's because Battleye simply doesn't know what Floorp is, and blocks it by heuristics.

> Hi, testing Firefox ESR 115 right now report back asap.
> 
> EDIT: Downloaded and installed ESR 115 but it instantly loaded ESR 115.13.0 update but, works ingame Could it be a addon?

**Comment by GunGunGun** [comment]
Try to rename `floop.exe` to `firefox.exe` and test again ?

**Comment by surapunoyousei** [comment]
Floorp is not trusted from Battleye. Please contact  Battleye support.
