### ISSUE TITLE
[Bug]: Color stripes appear in the Youtube playback window when switching UA

### ISSUE THREAD

**Issue by nanmofeng** [Floorp-Projects/Floorp#1282]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary
When changing the browser's UA using the UA switching plug-in, colored stripes appear in the Youtube playback window. Colored stripes appear when the mouse pointer is within the playback window. When the mouse pointer moves out of the playback window, the colored stripes disappear. I tested it with other UA switching plug-ins and the same problem occurred.
![12](https://github.com/user-attachments/assets/96178c28-8315-403e-859f-494a1830168a)
![13](https://github.com/user-attachments/assets/37c2a3d6-8994-4fad-94c2-c6300125f1d3)

### Reproduction Steps

1. Install the plug-in and then switch UA
2. When opening YouTube, the playback window appears abnormal.
3. Switch back to the original UA, open youtube, and playback is normal.

### Expected Behavior

1. Install the plug-in and then switch UA
2. When opening YouTube, the playback window appears abnormal.
3. Switch back to the original UA, open youtube, and playback is normal.

### Actual Behavior

Color stripes appear in the Youtube playback window when switching UA

### Screenshots

![13](https://github.com/user-attachments/assets/94575fa3-c438-4b3a-af73-4e48c3e57dd3)

### Browser Version

11.15.0（64bit）

### Operating System

windows 10

**Comment by nanmofeng** [comment]
The plug-in name is: User-Agent Switcher and Manager
![14](https://github.com/user-attachments/assets/fae8f547-de41-4451-9603-2a18b224c017)

**Comment by regularentropy** [comment]
I believe this happens because YouTube tries to use some new Chrome-specific technologies, and since they are not available in Firefox, the image is displayed incorrectly.

Please wait for the next ESR.

**Comment by nanmofeng** [comment]
When switching any UA, colored stripes will appear. 
![Uploading 17.png…]()

**Comment by mr-jnth** [comment]
no, it doesn't, i followed the reproduction steps and videos loaded normally

**Comment by nanmofeng** [comment]
This may be an occasional failure, perhaps due to the influence of other plug-ins. At present, it has not reappeared. Thank you everyone for your help.
