### ISSUE TITLE
[Bug]: Videos do not play on Udemy

### ISSUE THREAD

**Issue by justinfarrelldev** [Floorp-Projects/Floorp#1285]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The Udemy video player does not work when using it on Floorp, specifically. 

I have tried disabling all extensions, clearing the cache, and everything else but sadly it is still not working for me.

### Reproduction Steps

1. Go to Udemy.com
2. Play a video
3. Video will only show a grey screen

### Expected Behavior

The video plays correctly.

### Actual Behavior

There is a grey screen where the video is supposed to be.

### Screenshots

Screenshot: 
![image](https://github.com/user-attachments/assets/6ab5faaf-a98d-4337-83c9-6f16369f52f9)

On Firefox (notice how it is a black screen, rather than a gray one, and that it has advanced by a second): 
![image](https://github.com/user-attachments/assets/28056f2b-432d-4332-8003-da8bf0a25700)

### Browser Version

11.15.0

### Operating System

Windows 11

### Additional Context

This happens every time on Udemy. Check the screenshot above for the console logs from the Udemy page.

**Comment by CutterKnife** [comment]
Could be a DRM or codec issue. Does it work properly with Firefox ESR 115 instead of Firefox/Firefox ESR 128?

**Comment by regularentropy** [comment]
This is DRM-realted issue.

> Could be a DRM or codec issue. Does it work properly with Firefox ESR 115 instead of Firefox/Firefox ESR 128?

**Comment by justinfarrelldev** [comment]
Just tried it in Firefox ESR 115 and the videos appear to work there: 
![image](https://github.com/user-attachments/assets/214d8f21-4fab-41e9-9c84-42459cf56c43)

**Comment by AxeldeWater** [comment]
I tried to recreate the issue on Linux. The free preview videos on the site work and they seem to use the same video player. Could you check whether or not the free preview videos work in the Windows version? I might try to check it on the Windows version some time later too.

![image](https://github.com/user-attachments/assets/b8af1a94-d536-440e-a26b-16c04a9e9200)

**Comment by regularentropy** [comment]
https://docs.floorp.app/en/issues/drm/

**Comment by regularentropy** [comment]
> This is DRM-realted issue.
> 
> > Could be a DRM or codec issue. Does it work properly with Firefox ESR 115 instead of Firefox/Firefox ESR 128?

https://docs.floorp.app/en/issues/drm/

**Comment by justinfarrelldev** [comment]
Dang, yea seeing as this is marked as no-fix, I'll go ahead and close the issue. Thank you!
