### ISSUE TITLE
[Bug]: Floorp/FirefoxView does not show recently visited pages nor can be pinned to the toolbar

### ISSUE THREAD

**Issue by Consistos** [Floorp-Projects/Floorp#1286]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

about:firefoxview does not display open tabs sorted by last visit and can't be added to the toolbar

### Reproduction Steps

1. Open about:firefoxview w/ open tabs
1. alt: Edit the toolbar

### Expected Behavior

1. Opened tabs sorted by last visit displayed as in FF
1. alt: The shortcut should be available to add as in FF

### Actual Behavior

Only tab recovery and recently closed sections displayed

### Screenshots

<img width="850" alt="Floorp View" src="https://github.com/user-attachments/assets/614bced5-75d3-44d9-b5eb-eed2ee9ed0eb">

### Browser Version

11.15.0

### Operating System

macOS ARM

**Comment by surapunoyousei** [comment]
Firefox view is updated
