### ISSUE TITLE
[Bug]: Speedometer 3 scores lower than ESR

### ISSUE THREAD

**Issue by Consistos** [Floorp-Projects/Floorp#1287]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Speedometer 3 scores lower w/ same extensions and config 

### Reproduction Steps

Run https://browserbench.org/Speedometer3.0/ on both browsers

### Expected Behavior

Same score as ESR 115.13

### Actual Behavior

Benchmark is 11 % slower
[FF ESR 115.13 speedometer-3.csv](https://github.com/user-attachments/files/16393422/FF.ESR.115.13.speedometer-3.csv)
[Floorp 11.15 speedometer-3.csv](https://github.com/user-attachments/files/16393423/Floorp.11.15.speedometer-3.csv)

### Screenshots

<img width="287" alt="Capture d’écran 2024-07-26 à 17 03 23" src="https://github.com/user-attachments/assets/c94c9d8c-07c8-4b76-b20b-4299825a7ebe">
<img width="281" alt="Capture d’écran 2024-07-26 à 17 04 00" src="https://github.com/user-attachments/assets/8349cb8f-941c-400c-be55-9ec166a334c3">

### Browser Version

11.15.0

### Operating System

macOS ARM 14.5

**Comment by surapunoyousei** [comment]
ESR migration fix this isssues
