### ISSUE TITLE
[Bug]: CSS property `text-wrap: balance` not supported

### ISSUE THREAD

**Issue by beeb** [Floorp-Projects/Floorp#1291]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When visiting a webpage which uses the `text-wrap: balance` CSS property, the inspector reports "Invalid property name". The same code works fine in Firefox 121-128.

### Reproduction Steps

1. Visit https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap inside Floorp
2. Observe that "this feature is not supported by your current browser"
3. Visit the same page on Firefox 128.0esr
4. Observe that the feature works as expected in Firefox

### Expected Behavior

Floorp should handle the CSS the same way as Firefox

### Actual Behavior

Floorp doesn't know about the `text-wrap: balance` CSS property.

### Screenshots

![image](https://github.com/user-attachments/assets/011ef45f-469d-4f1f-baca-d086386218bc)

### Browser Version

11.15.0

### Operating System

Windows 11

**Comment by beeb** [comment]
I see now that the current stable release of Floorp is not using 128.0esr. This issue should resolve itself when it gets updated I suppose

**Comment by regularentropy** [comment]
Yes. The current version is esr115. The next version is ESR128.

> I see now that the current stable release of Floorp is not using 128.0esr. This issue should resolve itself when it gets updated I suppose
