### ISSUE TITLE
[Bug]: www.facebook.com - Time stamps missing from posts

### ISSUE THREAD

**Issue by sv-calin** [Floorp-Projects/Floorp#1292]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Received via webcompat: https://github.com/webcompat/web-bugs/issues/139707

### Reproduction Steps

1. Go to www.facebook.com
2. Log into your account.
3. Browse the feed.
4. Observe the posts.

### Expected Behavior

The time stamps are displayed.

### Actual Behavior

The time stamps are missing.

### Screenshots

![image](https://github.com/user-attachments/assets/d1382b6c-68cb-429a-a89e-09a2c8eae17b)

### Browser Version

11.15.0

### Operating System

Windows 10

**Comment by regularentropy** [comment]
This is an ESR issue and should be fixed in ESR128.
