### ISSUE TITLE
[Bug]: Opening a new normal window while having only a private window open closes all tabs and workspaces

### ISSUE THREAD

**Issue by damga123** [Floorp-Projects/Floorp#1293]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I had a private window left open while already having closed my normal windows, then I opened a the browser again, and now all my tabs, workspaces, pinned tabs are gone.

### Reproduction Steps

1. Open floorp
2. Open some tabs or create new workspaces
3. Open a private window
4. Close the original floorp window
5. Reopen floorp

### Expected Behavior

The tabs and workspaces should stay saved 

### Actual Behavior

All tabs and workspaces are closed.

### Screenshots

https://github.com/user-attachments/assets/a8881df7-b53c-47fa-8133-d2ce5a58c733

### Browser Version

11.15.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
Could you restore from this menu?
![image](https://github.com/user-attachments/assets/c0cf4410-a171-46e3-90e3-5df8883dfbbd)

**Comment by damga123** [comment]
Yes it seems I can reopen everything through the recently closed windows tab.

**Comment by surapunoyousei** [comment]
This is not a bug, as Firefox ESR is the same.

**Comment by damga123** [comment]
From my perspective this is clearly unexpected behavior so I would definitely say it's a bug, but okay.

**Comment by surapunoyousei** [comment]
If you consider it to be a defect, please submit a report to Bugzilla.

**Comment by damga123** [comment]
It seems this has already been reported to Bugzilla 5 years ago, but has yet to be fixed. My apologies
The actual report: https://bugzilla.mozilla.org/show_bug.cgi?id=1574834
