### ISSUE TITLE
[Bug]: PWA/Web Apps do not remember the window size on Windows

### ISSUE THREAD

**Issue by i-report-bugs** [Floorp-Projects/Floorp#1299]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When I close a web app window and open it again, it does not remember the window size and matches the main browser size.

### Reproduction Steps

1. Install a web app
2. Resize the web app
3. Close the web app
4. Re-open the web app

### Expected Behavior

It should remember the window size for each web app.

### Actual Behavior

It does not remember the size and it matches the browser's window size instead.

### Screenshots

![image](https://github.com/user-attachments/assets/0280cd3c-6887-4ed8-8393-965734184921)

### Browser Version

11.15.0 (64-bit)

### Operating System

Windows 10

### Additional Context

I was very excited when I found out about Floorp because the lack of web apps is one of the reasons why I don't switch to Firefox but knowing there's a Firefox fork with PWA support gave me hope.

The only issue that I could see so far is that the PWA window does not remember the last size. On Chromium-based browsers, it remembers the previous window size independent of the main browser or of other web apps.

**Comment by surapunoyousei** [comment]
PWA is different from normal apps. I will not fix this issue.

**Comment by surapunoyousei** [comment]
I've come up with a way to implement it, I'll try it later.
