### ISSUE TITLE
[Bug]: Temporary Containers Automatic Mode doesn't work

### ISSUE THREAD

**Issue by Muko-Tabi** [Floorp-Projects/Floorp#1300]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

# Temporary Containers Extension Issue

## Extension Details
- Name: Temporary Containers
- URL: https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

## Issue Description
The Temporary Containers extension is designed to automatically assign new tabs to temporary containers when the "Automatic Mode" setting is enabled. This feature works as expected in regular Firefox up to the current Developer Edition as of now, even if the extension is outdated. However, when using the Zen browser the "Automatic Mode" feature doesn't work.

## Steps to Reproduce
1. Install the Temporary Containers extension in Firefox.
2. Open the Temporary Containers extension settings.
3. Go to General and tick "Automatic Mode".
4. Open a new tab.

## Expected Result
When opening a new tab in step 4, the Temporary Containers extension should automatically assign the tab to a temporary container.

## Actual Result
When opening a new tab in step 4 in Zen Browser, the Temporary Containers extension does not automatically assign the tab to a temporary container.

### Screenshots

[Screencast from 2024-08-06 10-07-00.webm](https://github.com/user-attachments/assets/afb8086d-b437-4865-accf-7937ee02ccef)
- On the left is Floorp 11.15.0
- On the right is Firefox ESR 115.13.0
- I have also tested with Firefox ESR 128.0 and the result is the same as to 115.13.0

### Browser Version

11.15.0

### Operating System

Fedora Silverblue, Windows 11

### Additional Context

- Other Firefox forks such as Waterfox and Zen Browser also have the same issue, but Librewolf seems fine.

**Comment by CutterKnife** [comment]
Just to confirm, is this a Floorp issue and not Zen Browser?

**Comment by Muko-Tabi** [comment]
It's an issue on both, plus Waterfox, so Firefox forked browser issue, but Librewolf isn't affected.

**Comment by surapunoyousei** [comment]
Upon investigation, it appears that Librewolf reports itself as Firefox for extensions, but Floorp and Waterfox do not, which causes the error.
