### ISSUE TITLE
[Bug]: Video Codecs are depcreated

### ISSUE THREAD

**Issue by BinaryHarbinger** [Floorp-Projects/Floorp#1304]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

A video codec is broken and it prevents YouTube videos to play (some of them) and this also effects other websites. I also saw this problem in Firedragon (They forked Floorp). Firefox is fine with same videos. Here is the output from console (I get this output with safe mode tough) [Child 708942, MediaDecoderStateMachine #1] WARNING: Decoder=76120e859e00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - Error no decoder found for audio/mp4a-latm: file /home/main-builder/pkgwork/src/firedragon-v11.15.0-1/dom/media/MediaDecoderStateMachineBase.cpp:164

### Reproduction Steps

1. Open Floorp
2. Play one of the broken videos
3. Get Error message after spaming (otherwise it will load infinitly)

### Expected Behavior

Watching video

### Actual Behavior

Not watching video =d

### Screenshots

![image](https://github.com/user-attachments/assets/2e425eb6-d690-418e-ab8b-042ba19fe2d3)

### Browser Version

Latest

### Operating System

Arch Linux (Latest packages)

### Additional Context

I tried to install Floorp from AUR and chatic AUR and they both gave me same errors. I believe that it is because of the dependecies. I just installed base Arch Linux and the problem may be 'bout the missing dependecies

**Comment by cekimilf** [comment]
Can confirm this, I opened up the same issue about a month ago. 

It seems that the latest v11.16.0 release fixed the issue, however.

**Comment by kaos-55** [comment]
Here I put a temporary solution while Floorp 12 is being launched https://github.com/Floorp-Projects/Floorp/issues/1264#issuecomment-2271772143
I tested floorp 11.16.0 in Artix and it still has the same problem and this is not going to be fixed in version 11.

**Comment by cekimilf** [comment]
> Here I put a temporary solution while Floorp 12 is being launched https://github.com/Floorp-Projects/Floorp/issues/1264#issuecomment-2271772143
> I tested floorp 11.16.0 in Artix and it still has the same problem and this is not going to be fixed in version 11.

Sorry, yes, you're right. It is still broken on Artix, I was just accidentally looking at the windows version...

**Comment by surapunoyousei** [comment]
This issue may now be closed.
