### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Violet-RM** [Floorp-Projects/Floorp#1305]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Upon adding the PPA and updating to sync repositories on Linux Mint 22, based on Ubuntu Noble, the following error is received:
```The repository 'https://ppa.floorp.app noble Release' does not have a Release file.```

### Reproduction Steps

1. Add PPA on Linux Mint 22
2. apt update
3. Receive error

### Expected Behavior

The PPA syncs properly and Floorp will install

### Actual Behavior

The PPA does not sync properly and Floorp will not install

### Screenshots

![image](https://github.com/user-attachments/assets/6c46ba18-7ee8-4521-911c-fba03e0ef794)

### Browser Version

N/A

### Operating System

Linux Mint 22

### Additional Context

"Use the Flatpak-" No.
"Use another OS-" No.

**Comment by surapunoyousei** [comment]
Uploading PPAs update takes time

**Comment by Violet-RM** [comment]
About how much time?

**Comment by surapunoyousei** [comment]
I just tried the installation and was able to run it. Please retry.

**Comment by Violet-RM** [comment]
nope. same thing

**Comment by surapunoyousei** [comment]
Have you performed "apt update"?

**Comment by Violet-RM** [comment]
yes. results are in the screenshot

**Comment by surapunoyousei** [comment]
We have checked in several environments and there were no problems. We are unable to respond further. Sorry.

**Comment by Violet-RM** [comment]
thanks anyways. ill try it again in a few days to see if it just fixes itself
