### ISSUE TITLE
[Bug]: Enpass compatibility

### ISSUE THREAD

**Issue by theLittlePrinceAD** [Floorp-Projects/Floorp#1311]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

With latest Floorp 11.16.0 64x and installed Enpass (https://www.enpass.io/) with its extension (for inputting passwords) Enpass is giving the notification
 - please see attached picture: 
<img width="722" alt="Enpass" src="https://github.com/user-attachments/assets/25a371a2-498d-4369-8754-e4f298c98acc">

### Reproduction Steps

1. In Floorp do open password input field and click inside (having already installed Enpass and its extension).

### Expected Behavior

Enpass is putting password into field.

### Actual Behavior

Enpass is giving error.

### Screenshots

<img width="722" alt="Enpass" src="https://github.com/user-attachments/assets/f80dbea1-29c2-400f-9c1a-e60ee57c16ae">

### Browser Version

11.16.0 64x

### Operating System

Win 10 latest 64x

**Comment by surapunoyousei** [comment]
Floorp is not yet on the list of trusted browsers. There is nothing we can do to address this. Also, this issue has already been created.
