### ISSUE TITLE
[Bug]: Closing tabs in Default workspace moves tabs from other workspaces.

### ISSUE THREAD

**Issue by IncognitoFawkes** [Floorp-Projects/Floorp#1312]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When closing the tabs of the default workspace you are on, the tabs from the other workspace move to the default workspace.
Before closing tab:
![image](https://github.com/user-attachments/assets/1dbfaa32-67b9-41d3-a641-2859bf1c522c)
After closing tab::
![image](https://github.com/user-attachments/assets/919c3cec-1079-4308-b8ca-ea18830182f2)

To be precise, it's not that the tab moves to the new workspace. It's just that the tab you were on last in the other workspace appears on its own in your screen after closing all the tabs in the default workspace. When you right click on this tab, you can see that it didn't exactly move workspaces but just appears as if it's in the default workspace.
When I move back to the other workspace, the tab appears in it's main position. When moving back into the default workspace now, you see a new tab instead of the previous case where you saw the last used tab from the other workspace.

### Reproduction Steps

1. Open some tabs in Default workspace
2. Open some tabs in another workspace
3. Go to default workspace
4. Start closing tabs

### Expected Behavior

Instead of pulling the recent tab from the other workspace, I expect it to open a new tab in the default workspace when close all the existing tabs in that workspace.

### Actual Behavior

Actual Behavior explained in the description.

### Screenshots

![image](https://github.com/user-attachments/assets/2b7aba66-5592-4296-b32e-9616d970004d)
![image](https://github.com/user-attachments/assets/4d55e92c-ea9c-44f9-a176-b4cc9777f305)

### Browser Version

11.16.0 (64-bit) ; Firefox 115.15.0

### Operating System

Windows 11

**Comment by IncognitoFawkes** [comment]
Correction, it's not the last used tab but the last tab in the row from the previous workspace

**Comment by CutterKnife** [comment]
Maybe this post is a duplicate.

**Comment by surapunoyousei** [comment]
Yes. This issue is a duplicate.

I know that workspaces should be completely separated like in Vivaldi, but I don't intend to fix this issue at this time.
