### ISSUE TITLE
[Bug]: Last used tabs open as well along with PWA instead of just the PWA opening

### ISSUE THREAD

**Issue by IncognitoFawkes** [Floorp-Projects/Floorp#1313]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Opening the PWA opens previously used tabs as well in Floorp

### Reproduction Steps

1. Get a PWA
2. Open some tabs in floorp
3. Open the PWA after closing everything
4. Your previous tabs in floorp open as well

### Expected Behavior

Just the PWA to open and not the previous or open tabs on floorp.

### Actual Behavior

Since the PWA acts like another tab on Floorp, the previous tabs also open along with the PWA.

### Screenshots

![image](https://github.com/user-attachments/assets/872ce36e-7899-4569-ac37-253d3c2afdac)

### Browser Version

11.16.0 (64-bit) ; Firefox 115.15.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
duplicate
