### ISSUE TITLE
[Bug]: When using Display Tab Bar underneath/bottom, macOS window controls are on right side

### ISSUE THREAD

**Issue by ktnjared** [Floorp-Projects/Floorp#1318]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Using Floorp on macOS, with the options for either "Display Tab Bar underneath the Toolbar" or "Display Tab Bar at the bottom of the window", the window chrome controls (`<hbox class="floorp-tabbar-window-manage-container" …>`) appear on the right side instead of the left side where they're expected.

### Reproduction Steps

1. Install Floorp on macOS
2. Open `about:preferences#design`
3. Choose "Display Tab Bar underneath the Toolbar" or "Display Tab Bar at the bottom of the window"

### Expected Behavior

Window chrome controls appear on the left side, as they do with the Default, Hide tabs, and Optimize for Vertical Tab Bar options.

### Actual Behavior

Window chrome controls appear on the right side of the window.

### Screenshots

Default
<img width="1168" alt="floorp_11 16 0_macos-tabbar_default" src="https://github.com/user-attachments/assets/1befe8f9-765d-4198-88a7-6e780f14c886">

Hide tabs
<img width="1168" alt="floorp_11 16 0_macos-tabbar_hide-horizontal" src="https://github.com/user-attachments/assets/d8c0dd78-c39e-4a07-9926-4095ad0126a3">

Optimize
<img width="1168" alt="floorp_11 16 0_macos-tabbar_optimize" src="https://github.com/user-attachments/assets/81647c46-024f-4e23-b60c-e14ad89fe914">

Underneath Toolbar
<img width="1168" alt="floorp_11 16 0_macos-tabbar_underneath-toolbar" src="https://github.com/user-attachments/assets/0b137657-7fea-45fd-a908-b753a0276fff">

Bottom of Window
<img width="1168" alt="floorp_11 16 0_macos-tabbar_bottom-of-window" src="https://github.com/user-attachments/assets/1baa1441-b8d8-4f83-b971-2aee62eb4a6e">

### Browser Version

11.16.0 (64-bit)

### Operating System

macOS 14.6.1
macOS 15.1 beta 2

**Comment by sergeyshadok** [comment]
This is an exact duplicate of my #1088 that I opened 4 months ago.

**Comment by creeper-0910** [comment]
Probably fixed. Please wait for the next version.

**Comment by michael-kovalev** [comment]
This is still happening... on 12.2.1 on MacOS 26.0.1
