### ISSUE TITLE
Prevent heavy ads crypto currency mining

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#132]
Hello, i know that Floorp has a native anti cryptocurrncy mining protection, i discover also  that  chromium has invented a solution to detect and unload heavy ads ans crypto currency mining :
"In order to save our users’ batteries and data plans, and provide them with a good experience on the web, Chrome will limit the resources a display ad can use before the user interacts with the ad. When an ad reaches its limit, the ad's frame will navigate to an error page, informing the user that the ad has used too many resources. Here is an example of an ad that has been unloaded:

To determine the threshold limits for the unloading, we extensively measured the ads Chrome sees. We targeted the most egregious ads, those that use more CPU or network bandwidth than 99.9% of all detected ads for that resource. Chrome is setting the thresholds to 4MB of network data or 15 seconds of CPU usage in any 30 second period, or 60 seconds of total CPU usage. While only 0.3% of ads exceed this threshold today, they account for 27% of network data used by ads and 28% of all ad CPU usage."

[https://blog.chromium.org/2020/05/resou ... hrome.html](https://blog.chromium.org/2020/05/resource-heavy-ads-in-chrome.html)

hete test to test this if browser block heavy harmful nasty ads :

https://heavy-ads.glitch.me/

I know it's technically very hard and complicated but can Floorp implement such a native crypto mining detector and blocker like in chromium?

If not posible, i find this idea to prevent to reinforce cryptp mining protection : I read an article, the Crypto Currency Mining invented insidious methods to deceive the vigilance of the user and just use a small amount of CPU power, I no longer use adblocker extension because the DNS adsblocker unload ads at the source unlike the extension that can freeze the browser because there are a lot of lists, and sometimes when I enter sites, the sites detect that I use an adblocker extension and ask that I deactivate the adblocker so sometimes we sometimes is forced to deactivate the adblocker ....

the pirates use sophisticated techniques like using a very small power of your processor without realising it and without clicking on any link despite your web browser is up to date,
and Webassembly Tehnology (WASM) is enabled by default in web browsers but

WebAssembly may be used, just like JavaScript, to “steal” processing power instead of data. In 2019, an analysis of 150 different Wasm modules found out that about 32% of them were used for cryptocurrency-mining.

Hence the usefulness of imitating chromium which blocks the heavy ads suspects .....

It will be fantastic if Floorp could add option to let users to block by default the crypto malware domains block (rogue) js crypto miners based on the coiner blocking lists of awesome zerodot :

 https://zerodot1.gitlab.io/coinblocerlistsweb/index.htmlosis

https://github.com/hoshsadiq/adblock-nocoin-list

or another idea please : add option to disable javascript per site or per group of sites because it's a bit complicated and long to disable javascript in the browser, it's not as simple as in chrome, so you can add and copy paste suspicious sites in an option that disables the javascript of these suspicious sites!   

i suggest also to improve the speed that Floorp adds by default dns servers  dns over https that block ads and malware and even indecent vulgar web sites because many people do not know that such dns server  exist like those of adgurad dns and controld dns and radical dns and many others dns adblocker . ...
because I know that firefox added the dns of cloudflare but the dns that I propose block also ads...

https://libreops.cc/radicaldns.html

https://adguard-dns.io/en/public-dns.html

https://controld.com/free-dns/?

https://blahdns.com/

https://ahadns.com/

https://www.opennic.org/

**Comment by surapunoyousei** [comment]
Adding an ad blocker to Floorp by default goes against our manifesto and we can't do that.

By default, Firefox's Enhanced Tracking Protection is set to block tracking more broadly. It also comes with uBlock which is off by default, so I don't think it's necessary.
