### ISSUE TITLE
[Bug]: No way to add newly installed extension button to toolbar?

### ISSUE THREAD

**Issue by theLittlePrinceAD** [Floorp-Projects/Floorp#1323]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After installing new extension (Proton VPN) there is no way to add extension button to toolbar.

### Reproduction Steps

1. Install Extension
2. Try to add its button to toolbar

### Expected Behavior

In Firefox - clicking on the puzzle "Add-ons and Themes" button shows the added extension and with right click on the configuration wheel you can pin it to toolbar.

### Actual Behavior

There is no way to activate extensions.

### Screenshots

![ExtButton](https://github.com/user-attachments/assets/5d757849-ab62-4695-9f55-8d8cf8b1458d)

### Browser Version

11.16.0

### Operating System

Won 10 OS latest 19045.4780

**Comment by surapunoyousei** [comment]
Cannot reproduce
![image](https://github.com/user-attachments/assets/926ec68b-2194-4522-b211-27fd6617becd)
