### ISSUE TITLE
[Bug]: Windows version keeps trying to download update 11.17 and keeps failing

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [Floorp-Projects/Floorp#1324]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

floorp keep trying to download an update that doesn't exist

### Reproduction Steps

menu --> help --> about floorp

### Expected Behavior

ethier it tells me it's uptodate or do actual update

### Actual Behavior

fail and send me a popup to download from the website but even the url that opens has version 11.15 which even older than the one i have 11.16.0

### Screenshots

![image](https://github.com/user-attachments/assets/96e428b9-29da-4dad-843e-0af1636c36a9)

![image](https://github.com/user-attachments/assets/75274a2a-774f-4b87-90f3-537e7a8749de)

### Browser Version

11.16.0

### Operating System

windows 11

**Comment by CutterKnife** [comment]
https://github.com/Floorp-Projects/Floorp/actions/runs/10419117228

**Comment by surapunoyousei** [comment]
Work in progress
