### ISSUE TITLE
[Bug]: vertical tabs: unable to scroll the page

### ISSUE THREAD

**Issue by kfyangc** [Floorp-Projects/Floorp#1326]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using vertical tabs, opening many tabs will crowd the elements below. At this time, the mouse scroll wheel cannot be used to scroll through the tabs.

### Reproduction Steps

1. using vertical tabs
2. opening many tabs

### Expected Behavior

After upgrading Floorp, this issue occurred.

### Actual Behavior

When using vertical tabs, opening many tabs will crowd the elements below. At this time, the mouse scroll wheel cannot be used to scroll through the tabs.

I tried switching to the horizontal tab and then switching back to the vertical tab, but the issue still persists.

### Screenshots

![图片](https://github.com/user-attachments/assets/71d54df4-2979-44ec-b385-912745986f96)

![图片](https://github.com/user-attachments/assets/caf6b4c7-2b87-4569-9ba4-a0de38768775)

### Browser Version

11.17.1

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
Duplicate

**Comment by absol-0359** [comment]
This isssue occurred in my environment after updating to 11.17.1.
It may be different from the Issue that has occurred in previous versions.
In this version, not only the wheel operation is not available, but the scroll bar is not displayed, so scrolling is not possible.

https://github.com/user-attachments/assets/2467a84c-9ef2-4ad6-b705-71f451a96679

**Comment by surapunoyousei** [comment]
If you want to fix in your local Floorp.
Please add this css to your userChrome.css
#tabbrowser-tabs {
   overflow: scroll !important;
}

**Comment by surapunoyousei** [comment]
I will send update

**Comment by absol-0359** [comment]
> If you want to fix in your local Floorp. Please add this css to your userChrome.css #tabbrowser-tabs { overflow: scroll !important; }

This method worked for both scroll bars and wheel scrolling.
Thank you!
