### ISSUE TITLE
[Bug]: Proton Fix デザインでタブのハイライトが表示されない

### ISSUE THREAD

**Issue by CutterKnife** [Floorp-Projects/Floorp#1327]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Lepton 設定の「Proton Fix デザイン」では、選択中のタブのハイライトが表示されません。
通常の Proton や Photon / Lepton ではおおむね問題なく表示されることを確認しました。

### Reproduction Steps

1. `about:preferences#design` で「Firefox Photon・Lepton デザイン」を選択する
2. Lepton 設定で「Proton Fix デザイン」を選択する

### Expected Behavior

ツールバーやタブバーなどは Firefox Proton を踏襲しつつ、コンテキストメニューなどに Lepton 要素を取り入れたデザインが適用されます。

### Actual Behavior

Proton デザインと大枠は共通していますが、選択中のタブの表示が異なります。

### Screenshots

<img width="1287" alt="スクリーンショット 2024-08-17 0 59 53" src="https://github.com/user-attachments/assets/31a628e2-bd9e-4a04-9c2c-e852f5d550c1">

### Browser Version

11.17.1 (64-bit, Apple Silicon)

### Operating System

macOS Sonoma 14.6.1

### Additional Context

~~もうひとつ発見したので調査します~~ 既に報告されてました！

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/c7e81c53-12aa-4d1f-a098-09c921db62b0)
