### ISSUE TITLE
[Bug]: Extension icons are not visible

### ISSUE THREAD

**Issue by mbugrayilmaz** [Floorp-Projects/Floorp#1328]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After the 11.17.1 update, icons of extensions disappeared. The buttons still work, hovering on them still shows tooltips, but the icons are not visible

### Reproduction Steps

1. Update to 11.17.1
2. Icons are not visible

### Expected Behavior

Extension icons should be visible

### Actual Behavior

Extension icons are not visible

### Screenshots

<img width="858" alt="Screenshot 2024-08-16 at 19 17 49" src="https://github.com/user-attachments/assets/2eb91917-1a2b-417b-91f1-cd602beea691">

### Browser Version

11.17.1

### Operating System

MacOS Sonoma 14.5

**Comment by surapunoyousei** [comment]
Please use new profile. It is your env problem

**Comment by mbugrayilmaz** [comment]
> Please use new profile. It is your env problem

Just to test it, I completely uninstalled Floorp, removed Application Support/Floorp and Caches/Floorp folder, and reinstalled. But the issue still persists

**Comment by oroehrer** [comment]
I do have the same problem. A new profile did not help in any way.

**Comment by surapunoyousei** [comment]
Ok i will check it

**Comment by dennisooki** [comment]
On Macos Monterey, can confirm issue exists and new profile doesnt solve it

**Comment by surapunoyousei** [comment]
Please, don't comment "me too". I'm so busy for some issue fix. I want to release patch fast.

**Comment by ivan** [comment]
On Windows I find that the icons are visible at 100% scaling / DPI, but not at higher scaling.

**Comment by surapunoyousei** [comment]
I found a fix for this issue :)

**Comment by driftywinds** [comment]
Having the same problem, bump

**Comment by surapunoyousei** [comment]
Please don't post "me too" comment
