### ISSUE TITLE
[Bug]: Visual artifacts in unused tab bar background

### ISSUE THREAD

**Issue by ToRRent1812** [Floorp-Projects/Floorp#1329]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

With the latest floorp update (1.17.1), the background for tab bar is transparent and shows visual artifacts when adding or closing tabs.

### Reproduction Steps

Set tab bar to the bottom

### Expected Behavior

It should draw a bg color from the theme

### Actual Behavior

background display transparent void

### Screenshots

![Zrzut ekranu_20240816_184203](https://github.com/user-attachments/assets/fae2d625-17d1-45d9-8697-adf9746ff33b)

![Zrzut ekranu_20240816_185307](https://github.com/user-attachments/assets/d782baff-0ea0-4672-8136-eb945377376c)

### Browser Version

1.17.1

### Operating System

Linux x86_64

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/f286c2c2-04d7-41af-a4f6-dd2d2ec81598)

**Comment by ToRRent1812** [comment]
> ![image](https://private-user-images.githubusercontent.com/73892113/358684944-f286c2c2-04d7-41af-a4f6-dd2d2ec81598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzY1MTIsIm5iZiI6MTcyMzgzNjIxMiwicGF0aCI6Ii83Mzg5MjExMy8zNTg2ODQ5NDQtZjI4NmMyYzItMDRkNy00MWFmLWE0ZjYtZGQyZDJlYzgxNTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE5MjMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYjlhYmUyZGVlYzUyNmRjODljZjNmODE2MWY3Zjg1MzUxZjRjNWFhZGE0ZWZmMTU3Y2VhMDVkZWNkMDk1ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GyWJiPHldGcjxUpIX5g2BZ_YMVR5f5-6ytGStDQt4fA)

Just like I said, the issue is when it's set to the bottom, not to the top.

**Comment by surapunoyousei** [comment]
Ahh i see

**Comment by ToRRent1812** [comment]
I've found out, that if I enable title bar in customization menu, the issue is fixed.
