### ISSUE TITLE
Option to disable Electrolysis multi-process to reduce ram

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#133]
Hello, sometimes we use an old and not powerful pc and we don't have much ram memory and firefox use Electrolysis multi-process browsing so it will be good if our beleoved Floorp brower adds option to disable electrolysis to free up memory ram, I found this: 
"Firefox automatically uses settings based on the computer's hardware specifications [1].

Adjusting these settings can be done in Preferences or by changing the dom.ipc.processCount value to 1-8 and browser.preferences.defaultPerformanceSettings.enabled to false manually in about:config.

However you may want to manually adjust this setting to increase performance even further or decrease memory usage on low-end devices.

In this case the Content process limit for the current user has been increased to 4: "

https://wiki.archlinux.org/title/Firefox/Tweaks#Change_Performance_settings

so my request please is to add an option to quickly set : " Content process limit"  to 1 without digging into the internal settings of browser about:config  because firefox offered this option to choose the number of Content process limit but afterwards, firefox removed this option sadly :(

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/202701922-9cce588e-ef04-42b1-8ac7-da4ed3d8d176.png)


Floorp has the option

**Comment by surapunoyousei** [comment]
We cannot disable it. Firefox's code base cannot remove Electrolysis multi-process.

We do our best to reduce ram...
