### ISSUE TITLE
[Bug]: Side bar web panel doesn't work when a container is assigned to a page

### ISSUE THREAD

**Issue by gmsh** [Floorp-Projects/Floorp#1330]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

1. If you have installed the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) addon and assign a page to `always open this site in` a specific container, the same page won't open in the sidebar web panel.
2. In the Web Panel Settings, the `Use the following Container` drop-down box does not display the list of containers.

### Reproduction Steps

Taking this page `https://docs.ablaze.one/floorp_privacy_policy/` as an example, here is the steps to reproduce the issue:

**Step 1**. install the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) addon.

**Step 2**. open the page `https://docs.ablaze.one/floorp_privacy_policy/` and click the `Firefox Multi-Account Containers` addon icon, then select `always open this site in`.
<img width="688" alt="image" src="https://github.com/user-attachments/assets/de67731f-fd0f-4a2f-aca6-1a8faa4151c1">

**Step 3** . assign a container, say the `test` in the following screenshot
<img width="694" alt="image" src="https://github.com/user-attachments/assets/44e4373f-86d1-4cf2-94aa-a81655b78b7a">

**Step 4**. click the `add` button to add the page to the side bar web panel:
<img width="989" alt="image" src="https://github.com/user-attachments/assets/f5899a07-8715-4598-9c95-742c4767cdae">

**Step 5**. click `save changes` button. BTW, the `use the following container` is empty, which is also unexpected.
<img width="595" alt="image" src="https://github.com/user-attachments/assets/2428282c-30d2-4be5-80b2-de9cbdea3eb1">

**Step 6**. click the new added icon in the side bar, you get an empty page
<img width="716" alt="image" src="https://github.com/user-attachments/assets/f7e6a236-67f1-41fa-9011-32dac9ff6584">

### Expected Behavior

1. the `Use the following Container` drop-down box should show the list of containers
3. the page should not be empty if it is assigned to a container by `always open this site in` menu.

### Actual Behavior

both the `Use the following Container` drop-down box and the side bar web panel don't work as expected.

### Screenshots

I've included the screenshots in the previous sections.

### Browser Version

11.17.1 

### Operating System

macOS 14.6.1

### Additional Context

The previous ESR115 based versions don't have this bug. This bug is reproducible in a clean profile.

**Comment by surapunoyousei** [comment]
Thanks, I research the issue & Send fix

**Comment by surapunoyousei** [comment]
Fixed
