### ISSUE TITLE
[Bug]: 統合拡張機能ボタンの表示/非表示を「ツールバーをカスタマイズ」ページで管理できない

### ISSUE THREAD

**Issue by CutterKnife** [Floorp-Projects/Floorp#1332]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

`floorp.hide.unifiedExtensionsButtton` (統合拡張機能ボタンの表示設定) が、「ツールバーをカスタマイズ」で変更できなくなっています。

### Reproduction Steps

1. メニューの「ツールバーをカスタマイズ」を選択し、専用のページを開く
2. ウィンドウの下部を確認する

### Expected Behavior

統合拡張機能ボタン (パズルのピース) を表示、または非表示にできるチェックボックスが存在します。

### Actual Behavior

そのようなチェックボックスは存在しません。

### Screenshots

<img width="471" alt="スクリーンショット 2024-08-17 3 36 59" src="https://github.com/user-attachments/assets/a1a5e0a1-2de6-4775-b2ca-7d6b7aaf7570">

### Browser Version

11.17.1 (64-bit, Apple Silicon)

### Operating System

macOS Sonoma 14.6.1

### Additional Context

当該設定と同一であると思われるフラグ `floorp.hide.unifiedExtensionsButtton` は正常に機能するため、致命的な問題ではありません。
仕様変更ということにして Close することもできると思います。

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/a7287b79-cfb0-40c0-bd8e-bf5d85dce951)
直した
