### ISSUE TITLE
[Bug]: Problem with vertical tab bar in the web browser

### ISSUE THREAD

**Issue by MuerteRoja** [Floorp-Projects/Floorp#1335]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hello, good morning, today as soon as I got up first thing in the morning I updated to the latest version of the web browser, and, surprisingly, I find that the vertical tab bar is transparent (I have recorded a video documenting the bug) in the design options I have tried to change the design, however, the problem still persists, in addition to the fact that the color of the tab bar is not symmetrical / according to the theme installed in the web browser AMOLED BLACK by Darkhoof, in the previous version before updating the browser the color of the vertical tab bar was completely black, now, the color has changed and has acquired a dark gray hue

### Reproduction Steps

1 Go to your web browser settings 
2 Go to the design section 
3 Turn on the option to show vertical tab bar 
4 Turn on the option to collapse vertical tab bar 
5 Turn on the option to collapse tree-style tab bar 
6 Turn on the option to optimize browser for vertical tab bar 
7 You will see that the vertical tab bar is completely transparent and has no color

### Expected Behavior

The expected behavior is that the color of the vertical tab bar is consistent with the theme applied in the web browser, in my case AMOLED BLACK by Darkhoof and also stops being transparent.

### Actual Behavior

The current behavior is that the vertical tab bar is transparent and the color it displays is not consistent/symmetrical with the theme applied in the browser.

### Screenshots

![Captura de pantalla 2024-08-17 085856](https://github.com/user-attachments/assets/591bfa4b-e55b-4cd8-8cf2-782197545cc9)

https://github.com/user-attachments/assets/a3560f38-766f-47fe-bc3c-b53dae6c1582

### Browser Version

11.17.1 (64-bit)

### Operating System

Windows 11 Pro 23H2

### Additional Context

I would like to take advantage of this bug report to raise another question, in my web browser, what do I have to do to remove the arrow surrounded in red in the photo capture taken? Aesthetically speaking, I don't like that element to be in the tab bar, if possible I would like to remove it.

**Comment by surapunoyousei** [comment]
Duplicate

**Comment by MuerteRoja** [comment]
> Duplicate

Hello, good morning, do you have a solution for what I asked previously in "Additional Context"?

**Comment by surapunoyousei** [comment]
We are currently tracking this bug in other issues.

I am currently writing a patch to fix this.

**Comment by surapunoyousei** [comment]
If you want to fix in your local Floorp.
Please add this css to your userChrome.css
#tabbrowser-tabs {
   overflow: scroll !important;
}

**Comment by surapunoyousei** [comment]
I forgot to write this down.

If you want to remove a button from a vertical tab, you can return to the horizontal tab and remove it from the “Customize Toolbar”.

**Comment by MuerteRoja** [comment]
> I forgot to write this down.
> 
> If you want to remove a button from a vertical tab, you can return to the horizontal tab and remove it from the “Customize Toolbar”.


Uploading Grabación 2024-08-17 114800.mp4…

How can I do it?

**Comment by MuerteRoja** [comment]
> I forgot to write this down.
> 
> If you want to remove a button from a vertical tab, you can return to the horizontal tab and remove it from the “Customize Toolbar”.


https://github.com/user-attachments/assets/59cb3b14-8e9f-496d-8475-315ad1554572
How can I do it?
