### ISSUE TITLE
[Bug]: Vertical Tabs auto-collapse not working properly

### ISSUE THREAD

**Issue by FeraltCode** [Floorp-Projects/Floorp#1336]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After the 11.17.0~11.17.1 update the vertical tabs (auto-collapse enabled), leaves the icons unaligned, and when hovering it in order to expand, the background doesn't expand, only the tab names, making it difficult to read the tab titles.
![imagem](https://github.com/user-attachments/assets/966a13f7-c724-4d76-bc58-ab8fcb69a889)
Collapsed tabs
![imagem](https://github.com/user-attachments/assets/78f5f64d-c193-4310-91a4-b3379b05d45e)
Expanded Tabs, as you can see, the background/sidebar doesn't expand alongside the tabs

### Reproduction Steps

1. Turn on Vertical Tabs
2. Turn on Auto-Collapse Vertical Tabs

### Expected Behavior

The background of the tab bar should also expand, following the movement of the tab names, in order to make them readable

### Actual Behavior

The vertical tabs won't properly expand, making them hard to read and also unaligned

### Screenshots

![imagem](https://github.com/user-attachments/assets/966a13f7-c724-4d76-bc58-ab8fcb69a889)
Collapsed tabs
![imagem](https://github.com/user-attachments/assets/78f5f64d-c193-4310-91a4-b3379b05d45e)
Expanded Tabs, as you can see, the background/sidebar doesn't expand alongside the tabs

### Browser Version

11.17.1

### Operating System

Windows 11

**Comment by creeper-0910** [comment]
Duplicate https://github.com/Floorp-Projects/Floorp/issues/1335
