### ISSUE TITLE
[Bug]: Settings visual bug

### ISSUE THREAD

**Issue by UcraNerd** [Floorp-Projects/Floorp#1339]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

One option in the `Browsing` group of `General` settings has an invisible description.

### Reproduction Steps

1. Open floorp browser
2. Open floorp's settings tab
3. Scroll down to the `Browsing` settings group
4. See the 9th option from top to the bottom

### Expected Behavior

Seeing a description of the option

### Actual Behavior

The description is invisible

### Screenshots

![image](https://github.com/user-attachments/assets/41609525-9c86-4758-8548-e5405872bbe3)

### Browser Version

11.17.3 (64-bit)

### Operating System

Arch Linux

### Additional Context

I use the official portable version, not the AUR ones, to be clear.

**Comment by surapunoyousei** [comment]
Duplicate.

**Comment by UcraNerd** [comment]
> Duplicate.

Sorry, but I still can't find the original post...

**Comment by breadbeforerice** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1341
My comment is the same as yours reported.
(Sorry it didn't show up in the search, as the problem report seems to be in Japanese OK.)
