### ISSUE TITLE
Send video and files to video players and downloader manager accelerator

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#134]
Hello, i tried with one of these extension but i fail beaucause it seems complicated sadly :( so my suggestion is Floorp can may be integrate of these extensions ti send video or files to video players like vlc , mpv, splayer potplayer, qmplay2.....and economise energy when we watch video without the nedd to keep the browser open, and send large large files to donwload manager accelerators which use arai2c, wget.... like mhogomchungu/media-downloader, o7q
/MediaDownloader, hitomi downloader....which are fantastic open source dowloaders that use yt-dlp, you-get, lux...

https://github.com/mhogomchungu/media-downloader

https://github.com/o7q/MediaDownloader

https://github.com/KurtBestor/Hitomi-Downloader/releases

https://github.com/kannagi0303/yt-dlp-gui

so i find these extensions to open liks with external applications butsometimes  it's a bit difficult to use them and sometimes there are bugs so my suggestion is that Floorp integrate natively one of these tools to solve any problems and bugs and add in context muny "open with external application".....thank you very much !

this extension can play URLs in mpv player, but it seem like there is some problems in windows version: "Windows support is second-class. Feel free to open issues, but be advised that they won't be worked on unless someone else on Windows decides to fix them.

IMPORTANT: The Ruby native client does not work on Windows. You'll need to use the Python native client, which is included in the steps below and all helper scripts."

https://github.com/woodruffw/ff2mpv

this extension can be usefu if we want to increase network cache so we can use mpv palyer with big network cache and big media buffer, so can Thorium Browser integrate this extension to solve this problem or develp fork of this extension to avoid bugs and compatiblity problems please?

may be this thread can help:

woodruffw/ff2mpv#82

and also these extensions to open with external softwares : 

https://github.com/andy-portmen/open-in-vlc

https://github.com/darktrojan/openwith

https://mybrowseraddon.com/open-in-vlc.html

https://github.com/andy-portmen/external-application-button

**Comment by surapunoyousei** [comment]
These use C language etc. which operate natively.  Floorp's code is primarily written in JS, so this is not compatible.

 Some add-ons allow you to download YouTube videos in 4K, so no browser implementation is required.

 Also, other domestic browsers are working on this, and I don't want to provoke big tech, so I won't implement it.
