### ISSUE TITLE
[Bug]: Firefox Photon・Lepton デザインでは Floorp View のアイコンが表示されない

### ISSUE THREAD

**Issue by CutterKnife** [Floorp-Projects/Floorp#1340]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

***致命的ではありません！！**

Photon、Lepton、Proton Fix デザインでは、Floorp View を表すケースの様なアイコンが表示されません。
通常の Proton、および Fluerial デザインでは表示されるようです。
また、#1327 の[スクリーンショット](https://private-user-images.githubusercontent.com/110194318/358644490-31a628e2-bd9e-4a04-9c2c-e852f5d550c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTAzMTYsIm5iZiI6MTcyMzg5MDAxNiwicGF0aCI6Ii8xMTAxOTQzMTgvMzU4NjQ0NDkwLTMxYTYyOGUyLWJkOWUtNGEwNC05YzJjLWU4NTJmNWQ1NTBjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMDIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTQ0YjUzNDZhYzBlMWUxYTBiODAyZDE4YTMwMzRiYmFmNWQ0OWM1MzkzMzVjNDI4ZDE5ZDI5MjQ2ODk1NDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._HOzBvKBZW6-L2fh5JkVxqnfoJCZttiSL7WT6g_6AoE)によると、この問題は 11.17.3 で発生したようです。

### Reproduction Steps

1. about:preferences#design を開く
2. ブラウザーの外観 セクションで、「Firefox Photon・Lepton デザイン」を選択する

### Expected Behavior

アイコンなどの配置はそのままに、設定に合わせた外観に変更されます。

### Actual Behavior

Floorp View のボタンは透明になります。

### Screenshots

<img width="363" alt="スクリーンショット 2024-08-17 19 03 28" src="https://github.com/user-attachments/assets/afd9b3a9-9727-47f6-a224-204d9f968275">

Proton Fix デザイン

<img width="391" alt="スクリーンショット 2024-08-17 19 02 54" src="https://github.com/user-attachments/assets/5b090ef2-6e5f-4440-9502-6974731d4fcb">

参考: Firefox Proton デザイン

### Browser Version

11.17.3 (64-bit, Apple Silicon)

### Operating System

macOS Sonoma 14.6.1

### Additional Context

非常〜〜〜に些細な問題です (  ⁠ '-' )

**Comment by surapunoyousei** [comment]
なんで

**Comment by CutterKnife** [comment]
よし、見なかったことにしましょう

**Comment by surapunoyousei** [comment]
直そうと思います

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/5a9d3d3d-89d9-4525-ab75-78aa90c2db34)
ははははは

**Comment by CutterKnife** [comment]
うわああああ

**Comment by absol-0359** [comment]
既にご存じ、若しくは修正の目途が立っていたら恐縮ですが、「Lepton のコンテキストメニューとパネルメニューのアイコンを無効にする」のチェックを外したらアイコンが表示されました。
![image](https://github.com/user-attachments/assets/c0bd87ca-6cba-45b7-8b1e-3f4d574d08d2)

また、「Firefox Photon・Lepton デザイン」の場合、ブラウジングライブラリーのダウンロードタブでフォルダアイコンが表示されないようです。
Lepton側の問題かもですが、合わせて報告いたします。
![image](https://github.com/user-attachments/assets/4b5d6f97-b62c-41b4-85a3-e5e7496e9395)

**Comment by surapunoyousei** [comment]
了解です
