### ISSUE TITLE
[Bug]: Firefox sync forms don't accept input

### ISSUE THREAD

**Issue by holongate** [Floorp-Projects/Floorp#1342]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

On a fresh install of floorp, try to connect your firefox account: you are unable to enter your password and your security code in the corresponding box. If by chance the password is accepted through copy/paste, you are out of luck for the code anyway...

### Reproduction Steps

1. Enter your email
2. Form for password appear but the password text box is not responsive to keyboard typing
3. After an incredible struggle, and some copy/paste instead of typing the code form appear
4. The same problem exist for entering the code: text box totally unresponsive and your are send back to the first step (email)

### Expected Behavior

These fields should work as expected

### Actual Behavior

Account form fields for password and security code are not responsive to keyboard input

### Screenshots

![image](https://github.com/user-attachments/assets/d9762c2b-8bbc-46f4-9fcc-a11c5f404780)

### Browser Version

11.17.3

### Operating System

Ubuntu 22.04.4 LTS, x86_64

**Comment by absol-0359** [comment]
This issue seems to occur with the combination of Photon, Lepton Design and Dark Theme.
It's possible that the white text in the white input field makes it hard to see, but still able to enter the text.
![image](https://github.com/user-attachments/assets/b5c5b002-f532-439d-b2f7-94657ba0f9f4)
![image](https://github.com/user-attachments/assets/b8d9f802-fd08-4d19-a3b9-b93d379f49e0)

I think it will be easier to see if you change the Theme to Light or the Design to Firefox Proton.
![image](https://github.com/user-attachments/assets/93c3b504-7863-4e5b-b1ce-9dd1f2dca842)

**Comment by surapunoyousei** [comment]
I disable lepton userContent.css

**Comment by holongate** [comment]
Thanks for the investigation and the style change tip.

However,  I still can't complete the firefox sync process as the security code is always rejected:
![image](https://github.com/user-attachments/assets/c6953470-11aa-40bc-a529-ee9e8ed93d1e)
Note that this code is ok of course (as I can see it now).
After that rejection if I enter a code again, I am redirected to the password step...

Also note that the computer I use has firefox installed and I activated sync without problems, just to be sure.

This might be a different problem / bug than the input display.
Any idea?

**Comment by surapunoyousei** [comment]
Occurs when the time display of the computer is incorrect, etc.

**Comment by erenfro** [comment]
I'm curious why this was closed as completed. I'm still seeing this issue today.

**Comment by erenfro** [comment]
The problem being, for whatever reason, Floorp, specifically, is changing the way the input fields work on sites like Mozilla Sink, Accounts, etc... In way that is basically white text in white background input boxes, so you cannot even SEE what you are typing.
