### ISSUE TITLE
[Bug]: Status bar (link preview on hover) stops working after a web panel is opened

### ISSUE THREAD

**Issue by yawns** [Floorp-Projects/Floorp#1343]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Seems to be a regression of https://github.com/Floorp-Projects/Floorp/issues/1079

After you open a web panel, the status bar stops appearing. Below is a video demonstrating this in a newly created profile with no changes or addons.

### Reproduction Steps

1. Go to any website.
2. Hover over a link, the status bar at the bottom will show the location the link points to.
3. Open a web panel.
4. Hover over the link again, the status bar does not appear.
5. Hover over a link in the web panel, this is also missing the status bar.

### Expected Behavior

When a link is hovered over in either the main window or side panel, a status bar should appear at the bottom showing where the link points to.

### Actual Behavior

No status bar.

### Screenshots

https://github.com/user-attachments/assets/e249ec7e-7c3c-43af-b53f-80ded64e5a6d

### Browser Version

11.17.3

### Operating System

MacOS 14.6.1

**Comment by yawns** [comment]
https://github.com/user-attachments/assets/e249ec7e-7c3c-43af-b53f-80ded64e5a6d

Re-encoded video since the one I uploaded looks to also be in an unsupported format.

**Comment by guigirl42** [comment]
**Confirming** here too in `ArchLinux KDEPlasma`. I was the OP in https://github.com/Floorp-Projects/Floorp/issues/1079, & so was a bit sad last night when i discovered this bug has returned in the new version  `11.17.3`.

**Comment by surapunoyousei** [comment]
I had written the wrong code. Mistake.

**Comment by Vistaus** [comment]
I can confirm that it still happens with Floorp 11.17.3 on Deepin as well.

**Comment by surapunoyousei** [comment]
Please, Do not "me too" post comment at next

**Comment by Vistaus** [comment]
Sorry, I thought it would be good to share that it happens on a different Linux distro as well, since guigirl42 uses Arch.

**Comment by surapunoyousei** [comment]
I see,Thanks

**Comment by guigirl42** [comment]
> Sorry, I thought it would be good to share that it happens on a different Linux distro as well, since guigirl42 uses Arch while I use Deepin.

I agree that the OS _should_ be important info for any Dev to know. Why else are we users asked during the bug opening task to state our OS, as part of the info solicited? I mean, i can envisage scenarios where a new browser release is buggy when used in say Debian Stable, but otoh fine in Arch, & the difference can be obsolete libraries in the OS.

**Comment by surapunoyousei** [comment]
In XUL development, the distinction between Linux, Windows, etc. is important, but the difference between Deepin, etc. is not important!

**Comment by guigirl42** [comment]
Happily it seems fixed in `11.17.4`.  Thank you.

**Comment by Vistaus** [comment]
Not sure if I'm allowed to confirm it, but I'll do it anyway: it seems fixed for me too. Thanks! 🙂
