### ISSUE TITLE
[Bug]: duplicate DRM sections in Settings

### ISSUE THREAD

**Issue by lonnyshoal** [Floorp-Projects/Floorp#1344]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

In Settings, there are duplicate DRM sections.

### Reproduction Steps

upgrading Floorp from 11.16 to 11.17.3 through Synaptic package manager

### Expected Behavior

only one DRM section is required

### Actual Behavior

two DRM sections:
![螢幕快照 2024-08-18 02-28-16](https://github.com/user-attachments/assets/37a2062f-ed5d-4ff4-98ee-e42d672c6019)
![螢幕快照 2024-08-18 02-29-22](https://github.com/user-attachments/assets/5d46fc72-5927-4a3d-bc03-8b5377adcbc5)

### Screenshots

already at Actual Behavior section

### Browser Version

11.17.3

### Operating System

ubuntu 24.04

**Comment by CutterKnife** [comment]
It would be helpful if you could title the issue so that it is easy to find :)

**Comment by surapunoyousei** [comment]
Fixed
