### ISSUE TITLE
[Bug]: Vertical tab bar is not constrained to the browser's size and cannot be scrolled

### ISSUE THREAD

**Issue by yawns** [Floorp-Projects/Floorp#1346]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using vertical tabs, the tab bar isn't vertically constrained to the browser's height. If the tab list exceeds the browser's height, the bar continues to grow, pushing the other buttons out of view. The list is also not scrollable since the list isn't constrained/overflowed, and rather just extends outside of the user's view.

Attached video is of a fresh profile with no addons or changes, other than having vertical tabs enabled. At the end of the video when it's flashing, I'm hitting ctrl-t to open more tabs, since the new tab button is no longer accessible.

### Reproduction Steps

1. Enable vertical tabs
2. Open a bunch of new tabs

### Expected Behavior

The tab list height should be constrained to its container and scrollable when it exceeds this size.

### Actual Behavior

Tab list pushes other buttons out of view, cannot be scrolled, and tabs at the end of the list are inaccessible.

### Screenshots

https://github.com/user-attachments/assets/0c267deb-2322-46f7-958d-8af5356aa6a4

### Browser Version

11.17.3

### Operating System

MacOS 14.6.1

**Comment by KoJem9Ka** [comment]
Got the same problem after upgrading to 11.17.3. I had a lot of tabs and now I can't use them because the vertical list just doesn't scroll anymore.

**Comment by surapunoyousei** [comment]
I push fix.

If you want to fix in your local Floorp.
Please add this css to your userChrome.css
#tabbrowser-tabs {
   overflow: scroll !important;
}

**Comment by jedinjapan** [comment]
Thank you for the incredibly prompt response on this.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by Smyl3** [comment]
This was the 1st most annoying issue of Floorp.
The 2nd one is if have lot of tabs in vertical tabs mode, on new tab creation it doesn't get focus in the tab list automaticly so the active tab does not visible in the list unless scrolling the list manually.
3rd one is  Floorp does not have new tab button on main toolbar as every other browsers.
