### ISSUE TITLE
[Bug]: My floorp is full white and there is some old windows things??

### ISSUE THREAD

**Issue by sasufler** [Floorp-Projects/Floorp#1347]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

My browser have these white things in the top bar and all of the corners
![image](https://github.com/user-attachments/assets/b6021153-9256-4508-8dfe-f0946b611563)

### Reproduction Steps

1. Download latest version of floorp
2. launch it

### Expected Behavior

That there is not these white corner

### Actual Behavior

There is white corners

### Screenshots

![image](https://github.com/user-attachments/assets/21417a62-1abe-4989-84b5-9a63920d3e7e)

### Browser Version

v11.17.3

### Operating System

Windows 11 64-bit

**Comment by surapunoyousei** [comment]
Does this occur with new profiles?

**Comment by surapunoyousei** [comment]
https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_start-the-profile-manager-when-firefox-is-closed

Try use new profile

**Comment by surapunoyousei** [comment]
Fixed
