### ISSUE TITLE
[Bug]: HELP! Macos Mojave no longer supported ... please reallow download and install and use for older Macos!

### ISSUE THREAD

**Issue by blooddragonhero** [Floorp-Projects/Floorp#1348]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I ve opened my mac today and seen that my floorp browser which was working great till then stopped working. It was crossed as i got the info straight that i need to update my Macos ... I am using a Legacy os and it is much better cause it is the last version that runs 32bit apps... i will not update and please i m asking you to allow the use and install of floorp to Macos Mojave 10.14.6 . It is a great browser for this system and webpages loaded instantly as on one of the newest devices. It is outright ridiculous that it locks me out of my browser one day that has way too much bookmarks , passwords , extensions saved on it. Please correct this mistake of yours quickly, at least allow the install of the latest Floorp version 17.1 cause other ridiculous part is i cannot even download older versions of the app as it says. it is not compatible the same versions that i ve been using for months now... i had to copy the app from my other computer, that is crazy...

### Reproduction Steps

I ve opened my mac today and seen that my floorp browser which was working great till then stopped working. It was crossed as i got the info straight that i need to update my Macos ... I am using a Legacy os and it is much better cause it is the last version that runs 32bit apps... i will not update and please i m asking you to allow the use and install of floorp to Macos Mojave 10.14.6 . It is a great browser for this system and webpages loaded instantly as on one of the newest devices. It is outright ridiculous that it locks me out of my browser one day that has way too much bookmarks , passwords , extensions saved on it. Please correct this mistake of yours quickly, at least allow the install of the latest Floorp version 17.1 cause other ridiculous part is i cannot even download older versions of the app as it says. it is not compatible the same versions that i ve been using for months now... i had to copy the app from my other computer, that is crazy...

### Expected Behavior

I ve opened my mac today and seen that my floorp browser which was working great till then stopped working. It was crossed as i got the info straight that i need to update my Macos ... I am using a Legacy os and it is much better cause it is the last version that runs 32bit apps... i will not update and please i m asking you to allow the use and install of floorp to Macos Mojave 10.14.6 . It is a great browser for this system and webpages loaded instantly as on one of the newest devices. It is outright ridiculous that it locks me out of my browser one day that has way too much bookmarks , passwords , extensions saved on it. Please correct this mistake of yours quickly, at least allow the install of the latest Floorp version 17.1 cause other ridiculous part is i cannot even download older versions of the app as it says. it is not compatible the same versions that i ve been using for months now... i had to copy the app from my other computer, that is crazy...

### Actual Behavior

I ve opened my mac today and seen that my floorp browser which was working great till then stopped working. It was crossed as i got the info straight that i need to update my Macos ... I am using a Legacy os and it is much better cause it is the last version that runs 32bit apps... i will not update and please i m asking you to allow the use and install of floorp to Macos Mojave 10.14.6 . It is a great browser for this system and webpages loaded instantly as on one of the newest devices. It is outright ridiculous that it locks me out of my browser one day that has way too much bookmarks , passwords , extensions saved on it. Please correct this mistake of yours quickly, at least allow the install of the latest Floorp version 17.1 cause other ridiculous part is i cannot even download older versions of the app as it says. it is not compatible the same versions that i ve been using for months now... i had to copy the app from my other computer, that is crazy...

### Screenshots

![f2b42b31-0acc-4593-ae9f-a70f93252a40](https://github.com/user-attachments/assets/20d50344-cb88-4f14-bbdc-1e6634b4825f)

### Browser Version

17.3

### Operating System

Macos Mojave

**Comment by menndouyukkuri** [comment]
Firefox ESR 128 does not support macOS Mojave.
Floorp 11.17 is based on Firefox ESR 128.
