### ISSUE TITLE
[Bug]: window retracts to upper left corner of screen!

### ISSUE THREAD

**Issue by JimFlasch** [Floorp-Projects/Floorp#1349]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Bad news - in the latest version of Floorp (11.7.x, based of Firefox ESR28), the bottom of the window retracts upward and its right side retracts leftward until there is only a sliver of the browser's urlbar visible in the upper left corner of my screen.I don't know what's wrong with this release, but it should have been fixed yesterday! 

### Reproduction Steps

1. open browser
2. watch it retract to upper left corner of screen as described above

### Expected Behavior

opens like previous versions did.

### Actual Behavior

opens as described above

### Screenshots

none - i didn't realize they would be required and I'm not reinstalling v 11.7.x just to get them.

### Browser Version

11.7.x

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
You should provide screenshort

**Comment by JimFlasch** [comment]
don'tr know what a screenshort is, but I reinstalled Floorp11.7.3 to get a screenSHOT to satisfy you. Floorp is that thin white horizontal bar running for just over 800 pixels across the top of the image from the top left corner. It shrank to that top quickly for me to get more that this. Now please fix this humongous bug yesterday!


![FLoorp 11 7 3](https://github.com/user-attachments/assets/5e1d51eb-8641-4576-ae99-177d08fc4def)

**Comment by surapunoyousei** [comment]
I have to start by reproducing it, as no other users have reported that bug besides you, and I have not been able to reproduce it in my environment.


Maybe useful info: https://answers.microsoft.com/en-us/windows/forum/all/app-runs-off-screen-in-windows-11/47609284-eb59-48f2-82f8-b648a143808f

**Comment by JimFlasch** [comment]
It's not running off the screen! The bottom of the window is retracting upward and the side is retracting leftward, SHRINKING the window! And, I use Windows 10 22H2, Feature Experience Pack 1000.19060.1000.0, in case you were wondering. And how can I be the only one having problem?

**Comment by surapunoyousei** [comment]
Maybe foxed

**Comment by JimFlasch** [comment]
What the hell does "foxed" mean!? And how can you close a bug as completed when you haven't solved it!?

**Comment by JimFlasch** [comment]
BTW, if I use F11 to go from window mode into fullscreen mode, Floorp 11.17.3 does fill the whole screen. It's only in window mode that it contracts to the upper right portion of the screen. Still a big inconvenience, though. And whatever the bug is that's causing that to  happen still needs to be squashed before the next version is released.

**Comment by JimFlasch** [comment]
seems to be solved with 11.17.4.
