### ISSUE TITLE
Android version with extensions

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#135]
Hello, Floorp is amazing and it will be amzing if we can use it in android ! i find this open source android  browser based on firefox android and it adds the possiblity to install extension and addons ! this browser adds " The ability to attempt to install a much longer list of add-ons than Mozilla's Fenix version of Firefox accepts. Currently the browser queries [this AMO collection](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/) Most of them will not work"

so my suggestion is Floorp can may be take insiration from this browser and add his own options and features and therefore, we will have great Floorp for android in sha Allah !

https://github.com/fork-maintainers/iceraven-browser

**Comment by surapunoyousei** [comment]
We would like to work on this and will let you know when development begins. Until then, this issue will be closed.

**Comment by surapunoyousei** [comment]
It looks like develop is finished.
