### ISSUE TITLE
[Bug]:  can not scroll down vertical tabs with last update

### ISSUE THREAD

**Issue by ksso00** [Floorp-Projects/Floorp#1350]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

With last update (11.17.3) now can not scroll down vertical tabs with middle mouse button (scrolling) nor a sliding bar nor a keyboard shortcut

### Reproduction Steps

1. update floorp
2.  enable vertical tabs
3. cant scroll tabs

### Expected Behavior

scrolling enables

### Actual Behavior

cant scroll down

### Screenshots

vertical tabs

### Browser Version

11.17.3

### Operating System

slowroll

### Additional Context

thank you!

**Comment by surapunoyousei** [comment]
Duplicate
