### ISSUE TITLE
[Bug]: Applied user.js not in profile folder?

### ISSUE THREAD

**Issue by s0lid5n4ke** [Floorp-Projects/Floorp#1351]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

- After selecting a user.js Profile/Configuration e. g. "Yokoffing Default" the user.js file is not present in the current Floorp Profile Folder.

### Reproduction Steps

1. Open Floorp Settings.
2. Go to "General".
3. Go to section "Perfomance" and click on "user.js Settings..."
4. "Apply" a desired user.js profile and restart Floorp as prompted.
5. Check the active Floorp Profile Folder, which can be found via the URL "about:support".
6. Search for the applied user.js file which should be present for overwirting the settings.

### Expected Behavior

- Applied user.js should be louded to the Floorp active/primary Profile Folder to apply its settings to Floorp.

### Actual Behavior

- The user.js file is not present in the Profile Folder after doing the described steps to reproduce this behaviour.

### Screenshots

<img width="1586" alt="Screenshot 2024-08-18 115612" src="https://github.com/user-attachments/assets/b1c008f5-8867-4d81-b27e-7376e4d0a0a7">

### Browser Version

11.17.3 (20240817055336)

### Operating System

Windows 10 Pro (22H2)

### Additional Context

- Maybe this behaviour is normal or intended, but it in this case it would be interesting how the user.js settings are applied to Floorp.

**Comment by guigirl42** [comment]
Ever since i began using Floorp last year, that's also been the case for me, & it's always really confused me. Also, in the Settings UI after trying to apply a js then later reloading the page, i can see no visual confirmation at all that any of those user.js is actually active. :woman_shrugging: :exploding_head:  `ArchLinux KDEPlasma`.

**Comment by s0lid5n4ke** [comment]
> Now, in `11.17.4`, the `user.js` finally _does_ appear in the profile directory, so this is definite progress 👍
> 
> However, the actual _Settings_ page `about:preferences#userjs` continues to give _no_ visual indication at all that _any_ `user.js` is active. That still seems a strange design decision to me 🤷‍♀️

I am very grateful that it was solved so quickly.
The developer certainly is very busy, and we should wait for Floorp 12 (Rapid/Stable Release) as announced and not start too many more feature requests in the current ESR version in my opinion.
