### ISSUE TITLE
[Bug]: the split view option is no longer visible in in the tab cotext menu in the latest update 11.17.3.

### ISSUE THREAD

**Issue by bravadoo** [Floorp-Projects/Floorp#1352]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

earlier the option of split view was visible when a tab was right clicked. it is no longer available in the latest update. There also no mention of split view in the settings. 

### Reproduction Steps

update to the latest version of the floorp browser. In my case 11.17.3. right click on the tab and then check the menu

### Expected Behavior

like the earlier version, there was an option to enable split view through the tab context menu. 

### Actual Behavior

no option of split view for the tab is available

### Screenshots

![photo_2024-08-18_15-35-39](https://github.com/user-attachments/assets/f03dd7d5-7b1b-446a-ad8e-88614a3d0d49)

### Browser Version

11.17.3

### Operating System

windows 11

**Comment by surapunoyousei** [comment]
Split view requires a currently unselected tab to be opened via context menu

**Comment by winstonma** [comment]
Duplicate of #1355
