### ISSUE TITLE
[Bug]: Floorp v11.17.3 Mica For Everyone Setting Breaks Browser Visibility

### ISSUE THREAD

**Issue by soulcollectivex** [Floorp-Projects/Floorp#1353]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When enabling the setting "Allow Mica For Everyone to Modify The Browser Design" in the latest Floorp version 11.17.3 after first install, the window borders and most UI elements become completely white and unreadable, the window also becomes unmovable or resizable, also when this setting is turned off the browser is functional once again.

### Reproduction Steps

1.Install Floorp Latest Version
2.Enable The Setting "Allow Mica For Everyone to Modify The Browser Design"
3.[Bug]

### Expected Behavior

The setting "Allow Mica For Everyone to Modify The Browser Design" is supposed to allow the mica or acrylic accents/effects display on the browser when the app Mica For Everyone is installed and a rule has been added for floorp to it.

### Actual Behavior

After enabling this setting, the browser becomes unusable, has pure white borders, becomes unmovable and the window controls disappear upon changing the setting back off.

### Screenshots

<img width="860" alt="Floorp rule in MicaForEveryone" src="https://github.com/user-attachments/assets/def4dc5e-f967-4bcd-91ba-9bada5c28af5">

https://github.com/user-attachments/assets/b79dd239-c5c3-4420-8fba-83e2a3a900dd

### Browser Version

Floorp Version 11.17.3

### Operating System

Windows 11 Pro 23H2

### Additional Context

My System Specifications In case they are needed:
Razer Blade 15" Advanced Edition Gaming Laptop Mid-2021 Refresh Model 
CPU: Intel Core i7 11800H
GPU: NVIDIA GeForce RTX 3080 Laptop GPU
RAM: 64 GB DDR4 Crucial Ballistix Laptop Ram

**Comment by surapunoyousei** [comment]
I will remove the option

**Comment by soulcollectivex** [comment]
So there is no plan to continue supporting this feature, i understand then?

**Comment by surapunoyousei** [comment]
A little difficult to maintain.

**Comment by soulcollectivex** [comment]
I'm sorry it is so difficult, it is sad to see this feature go, and thankyou for your hard work on it.

**Comment by surapunoyousei** [comment]
Fixed
