### ISSUE TITLE
[Bug]:  The minimize and maximize button in missing at the top of the window

### ISSUE THREAD

**Issue by Ojash042** [Floorp-Projects/Floorp#1354]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

**Desktop Environment**: KDE Plasma 6
**Installed from**: Flatpak

The top bar has removed the buttons for minimizing and maximizing the window. This issue did not exist before the 11.17.x release. I updated the browser again using flatpak to the latest release as well and still the issue persists. I have also tried changing the window decoration  to see if it fixes the issue and that did not work as well. I did not encounter this issue in my Windows 10 OS on the dual booted on the same device.

### Reproduction Steps

1. Install the latest version of Floorp Browser
2. [Bug]

### Expected Behavior

Displaying of the minimize and maximize button before the Close button

### Actual Behavior

The minimize and maximize button has disappeared 

### Screenshots

![image](https://github.com/user-attachments/assets/5c1ed33b-b419-4745-bf50-ab06d5c69ef0)

### Browser Version

11.17.3

### Operating System

Endeavour OS

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/56696a39-89e9-45f0-85eb-fe83450c4b83)
I attribute this problem to Floorp now running in Wayland.

It is displayed correctly in my Linux Mint. Please check your configuration.

**Comment by TCaptainPancake** [comment]
How do I fix this.

**Comment by Ojash042** [comment]
@TCaptainPancake Installing this package "xdg-desktop-portal-gtk" fixed it for me.

**Comment by TCaptainPancake** [comment]
yup figured that out and forgot to update lol thanks anyways!!

**Comment by jarrard** [comment]
Installed GTK package.  Still no Min/Max for Wayland Compositor.  Must force it back to X11 in order for it to show those buttons. 

This is still a problem, fresh cachyos (arch) install with Plasma Wayland tested, nothing funny going on.  Firefox DEFAULT works fine, only floorp has this issue.
