### ISSUE TITLE
[Bug]: split view will result in other web pages invisible

### ISSUE THREAD

**Issue by lonnyshoal** [Floorp-Projects/Floorp#1355]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After creating split view and switching to another existing non-split-view tab, the page of that tab is invisible.

### Reproduction Steps

1. Creating a split view by open in split view.
2. Switching to another existing non-split-view tab.
3. The web page of that tab is invisible.

### Expected Behavior

All web pages of other existing tabs should be still visible.

### Actual Behavior

If you go to the split view tab and then go to another tab, the web page of another tab will be invisible.

### Screenshots

![another page invisible after split view](https://github.com/user-attachments/assets/268e893c-1638-4e6a-80f1-11ac68e15c54)

### Browser Version

11.17.3

### Operating System

ubuntu 24.04

### Additional Context

the workaround is switching to another application program and switching back to the browser

**Comment by surapunoyousei** [comment]
duplicate

**Comment by lonnyshoal** [comment]
I cannot find any open issue ticket with the same issue.
I tested the new 11.17.4 version and confirmed this issue has not been fixed.

**Comment by guigirl42** [comment]
It **IS** still a _bad problem_ in my ArchLinux `11.17.4.` I _do not understand_ why this ticket was closed :exploding_head:

**Comment by winstonma** [comment]
I recently use 11.17.5 and I got this issue too

@surapunoyousei could you please take a look

**Comment by winstonma** [comment]
@guigirl42 I updated Floorp to 11.17.7 and it seems the problem is fixed.

Please check that too

**Comment by guigirl42** [comment]
Thanks, but no, i'm _still_ getting dead tabs after invoking the split view function via kb shortcut. :sob:

**Comment by winstonma** [comment]
Sorry for the misinformation. Yes I got the blank tab.

@surapunoyousei I started floorp using terminal, opened 3 tabs, combine 2 together. And I got the following error message on the terminal:

```
Assertion failure
assert@resource:///modules/AsyncTabSwitcher.sys.mjs:510:36
onLayersCleared@resource:///modules/AsyncTabSwitcher.sys.mjs:822:10
handleEvent@resource:///modules/AsyncTabSwitcher.sys.mjs:1139:16
```

Could you please take a look? Thank you very much.

**Comment by surapunoyousei** [comment]
It seems to happen only when the tab is reloaded in an unloaded state. It will take some time to fix as it reads code.

**Comment by winstonma** [comment]
Thank you very much. Could this ticket be opened? Thanks

**Comment by Muko-Tabi** [comment]
I think this should be opened, since it's a problem for people that use Sidebery (or similar) and can only use split view via keyboard shortcut.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by winstonma** [comment]
@surapunoyousei I am using Floorp v11.18.1 and I recently saw this behavior.

1. Opened some tabs
2. Open 2 new tabs and use Split View on the 2 new tabs
3. Open one new tab and I saw the following message on my my terminal

```
Assertion failure
assert@resource:///modules/AsyncTabSwitcher.sys.mjs:510:36
onLayersCleared@resource:///modules/AsyncTabSwitcher.sys.mjs:822:10
handleEvent@resource:///modules/AsyncTabSwitcher.sys.mjs:1139:16
JavaScript error: undefined, line 0: Error: r.tab is undefined
```

4. After I type the URL I would see the blank page

But it is weird that I try to reproduce in private window but it didn't work. But I saw this weird behavior. Could you please take a look? Thanks a lot

**Comment by winstonma** [comment]
By the way when I

1. Open terminal and type `floorp --private-window`
2. Open 2 tabs and use split view
3. Open a new tab then then I saw error log in the terminal

```
Assertion failure
assert@resource:///modules/AsyncTabSwitcher.sys.mjs:510:36
onLayersCleared@resource:///modules/AsyncTabSwitcher.sys.mjs:822:10
handleEvent@resource:///modules/AsyncTabSwitcher.sys.mjs:1139:16
Assertion failure
assert@resource:///modules/AsyncTabSwitcher.sys.mjs:510:36
onLayersCleared@resource:///modules/AsyncTabSwitcher.sys.mjs:822:10
handleEvent@resource:///modules/AsyncTabSwitcher.sys.mjs:1139:16
```

But when I type an URL it would show the content. Just wonder if it is expected behavior? Thanks

**Comment by surapunoyousei** [comment]
I assume it has been fixed, but are you still experiencing problems?

Ignore the console error.

**Comment by winstonma** [comment]
Also one more report on the split view:

1. Open terminal and type `floorp --private-window`
2. Open 1 tab (Call Tab1), go to www.espn.com
3. Open a new tab 2, go to google.com
4. Use split view on Tab1 and Tab2
5. Open a new tab (Tab 3), go to three.com
6. Swap the position of Tab2 and Tab3, now Tab2 is the rightmost tab
7. Keep switching tabs like the video below

https://github.com/user-attachments/assets/a9c4d21c-2ca9-4d44-9fe1-39cf62996765

There are several things to notice
1. Split View Content is swapped (In the split view, left hand side should show espn.com, but now it is on the right hand side)
2. Tab3 content is disappeared some time, but after several switches it would come back

**Comment by lonnyshoal** [comment]
This issue has been fixed.
However, I know there is another issue on the new split view function:
The newly-opened tab page is blank sometimes and temporarily. The page can be recovered after switching pages. I think we need more tests on all Windows, Mac OS and Linux.

**Comment by winstonma** [comment]
@lonnyshoal I think your observation matches my recorded video.

**Comment by winstonma** [comment]
@surapunoyousei Would you have time to take a look at the [video in the above post](https://github.com/Floorp-Projects/Floorp/issues/1355#issuecomment-2380614356)? Also could this issue be reopened?

Thanks
