### ISSUE TITLE
[Bug]: Side bar web panel doesn't work after unloading if a container is assigned

### ISSUE THREAD

**Issue by gmsh** [Floorp-Projects/Floorp#1356]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Thanks for fixing https://github.com/Floorp-Projects/Floorp/issues/1330. However, the issue is not fully fixed. The web panel on the side bar still shows an empty page when the panel is unloaded or the browser has been restarted. I recorded a video clip to show the reproduction of this bug.

### Reproduction Steps

You can trigger it by first execute the step mentioned in https://github.com/Floorp-Projects/Floorp/issues/1330, then:
1. right click the icon of the newly added web panel, then click `unload this panel`

<img width="278" alt="image" src="https://github.com/user-attachments/assets/44babee2-b304-4880-b622-63c96996be2f">

2. click the icon on the side bar again, then you can see the empty page.

<img width="448" alt="image" src="https://github.com/user-attachments/assets/2a2c5652-dd66-4804-bf18-fee3d1c77b30">

Please refer to the video below I've uploaded for more details.

### Expected Behavior

The page should load after unloading or a browser restart.

### Actual Behavior

The page is empty.

### Screenshots

https://github.com/user-attachments/assets/45a2665c-63e1-42cb-a874-77492f6f0baa

### Browser Version

11.17.4

### Operating System

macOS 14.6.1

**Comment by surapunoyousei** [comment]
I create a patch for this issue. Waiting update
