### ISSUE TITLE
[Bug]: Cloudflare Turnstile still breaks on ESR128-based Floorp

### ISSUE THREAD

**Issue by JimFlasch** [Floorp-Projects/Floorp#1357]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

[Bug]: Cloudflare Turnstile still breaks on ESR128-based Floorp

### Reproduction Steps

go to  fanart.com
get Verify you are human by completing the action below. screen with check box
click checkbox and watch Verify you are human by completing the action below. change to Verifying you are human. This may take a few seconds. with spiinner then back to Verify you are human by completing the action below. screen with check box

### Expected Behavior

go to  fanart.tv
get Verify you are human by completing the action below. screen with check
watch website show up as it should

### Actual Behavior

go to  fanart.com
get Verify you are human by completing the action below. screen with check box
click checkbox and watch Verify you are human by completing the action below. change to Verifying you are human. This may take a few seconds. with spiinner then back to Verify you are human by completing the action below. screen with check box

### Screenshots

what you see when you initially access site:
![fanart1](https://github.com/user-attachments/assets/9da52f36-5d3c-4913-a3cf-1ec0420f5f93)

what happens when you click ckeckbox:
![fanart2](https://github.com/user-attachments/assets/38d408f6-7bd8-46f6-9c44-7cb9d36d7a30)

after a few minutes, you're back to first screenshot again!

### Browser Version

Floorp 11.17.4

### Operating System

Windows 10

### Additional Context

This situation does not happen all the time for some reason - it only happens internittently and resolves after several days. However, it should not happen at all now - I was told in [this thread](https://github.com/Floorp-Projects/Floorp/issues/812#issuecomment-2227647837) that 

"We understand this can be frustrating. This happens because ESR115 (on which Floorp is based on) is pretty old. So these captcha systems might find it suspicious. But don't worry, the main dev is working on migrating the codebase to ESR128 which should fix these issues. The release is planned for next month. Please wait until then, thanks!"

and the current version of Floorp IS based on ESR128!

**Comment by creeper-0910** [comment]
Cannot be reproduced.

**Comment by JimFlasch** [comment]
Maybe you can't but I'm reproducing it right now!

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/89fdedc3-c50e-4463-9b84-47696c45593a)
What will the new profile look like?

**Comment by JimFlasch** [comment]
I see you can get past Cloudflare Turnstile to Fanart.tv, @surapunoyousei. I still can't, though. How is this bug affecting my copy of Floorp 11.17.4 but not yours?

**Comment by surapunoyousei** [comment]
It doesn't seem to affect me.

Please try accessing with a new profile.

**Comment by JimFlasch** [comment]
Can I do that without losing my tabs, etc.

**Comment by JimFlasch** [comment]
And how do I change profiles anyway?

**Comment by JimFlasch** [comment]
Did that and it works there but I have no Idea why and I don't want to permanently switch to a new profile because it would be a pain in the butt to reinstall all my addons and rebuild my tabs list in a new profile. I'd rather get Cloudflare Turnstile working in my current profile.

**Comment by surapunoyousei** [comment]
Did you apply userAgnet change?

**Comment by nanmofeng** [comment]
This may be a problem with changing the browser UA. I encountered this in ESR version 115. At that time, Cloudflare's verification was about to crash me, and I couldn't do it no matter what. Later, I realized that I had to change the browser UA and restore the UA to Firefox to pass Cloudflare's verification. You can try it.

**Comment by JimFlasch** [comment]
How do I do that?

**Comment by JimFlasch** [comment]
You can't close this bug when it isn't fixed!

**Comment by JimFlasch** [comment]
I'm not configuring a user.js script! I'm trying to figure out why Cloudflare Turnstile is broken on my active profile!

**Comment by surapunoyousei** [comment]
Have you tried Safe Mode?

**Comment by JimFlasch** [comment]
How is that going to help? I already noted above that Turnstile works fine on an alternate profile in my C:\Users\James\AppData\Roaming\Floorp\Profiles\56clfdrw.default directory that has none of the addons or settings in my default profile. Surely Safe Mode will give me the same result.

**Comment by JimFlasch** [comment]
Here's that user.js file in a zip. I downloaded this from https://github.com/yokoffing/Betterfox, BTW.
[user.zip](https://github.com/user-attachments/files/16656252/user.zip)

What configuration page do you want screenshots of?

**Comment by surapunoyousei** [comment]
If it works in safe mode then there is a problem with your settings, add-ons etc.

**Comment by surapunoyousei** [comment]
You need to initialize the settings

**Comment by JimFlasch** [comment]
This bug, which disappeared about 18 days ago, returned two days ago after updating to 11.18.0, without any other changes. Make it disappear again!

**Comment by surapunoyousei** [comment]
Try Safe Mode, new profile

**Comment by JimFlasch** [comment]
This bug is BACK in Florrp 11.22.0, after months of not showing up! Why?

**Comment by typeling1578** [comment]
Turnstile will fail verification if it detects unusual behavior.
This is just a false positive by Turnstile and not a problem with Floorp.

**Comment by JimFlasch** [comment]
Yeah...why does it keep recurring?

**Comment by typeling1578** [comment]
We recommend that you report the problem to Cloudflare.
This is Turnstile issue and there is nothing we can do about it.

**Comment by JimFlasch** [comment]
Why does Cloudflare Turnstile always break for a short time everytime you update Floorp!?!?!?!?!?!?!?!?!?!?!?!?

**Comment by creeper-0910** [comment]
idk,it is working.

**Comment by JimFlasch** [comment]
Not for me it's not! It just keeps giving me the stupid "Verify that you are human" screen! And it does that for a coupple of weeks everytime Floorp is updated!

**Comment by creeper-0910** [comment]
Are there any users you know who can reproduce this problem?

**Comment by JimFlasch** [comment]
I don't know. Wish I did.

**Comment by JimFlasch** [comment]
Turnstile is broken on Floorp AGAIN!!!!!!!!!!!!!!!!!!!!!!!! (version 11.24.0 this time) Get 12.x out so I don't ever have to see this again!

**Comment by proxy-guy** [comment]
Somehow I'm having this in JULY OF 2026???
