### ISSUE TITLE
[Bug]: 11.7.4 Linux PPA download error

### ISSUE THREAD

**Issue by DivineMK** [Floorp-Projects/Floorp#1358]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I cannot install through the PPA.
Errors from apt:
Ign:1 https://ppa.floorp.app/amd64 ./ floorp 11.17.4
Ign:1 https://ppa.floorp.app/amd64 ./ floorp 11.17.4
Ign:1 https://ppa.floorp.app/amd64 ./ floorp 11.17.4
Err:1 https://ppa.floorp.app/amd64 ./ floorp 11.17.4
  Could not resolve 'ppa.floorp.app'
E: Failed to fetch https://ppa.floorp.app/amd64/./floorp-11.17.4.deb  Could not resolve 'ppa.floorp.app'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Errors from nala:
Error: Hash Sum does not match: floorp-11.17.4.deb
  Expected Hash: SHA256: 0ba05e348973ca3446d45cac34e9654e0b757d2a95508f7aa799110269fac3b7
  Received Hash: SHA256: 4d04119eaa425f641fbbaba065f4c955ce7e2ed1788e38aab20b69d3dacb78d6
Notice: Nala has removed floorp-11.17.4.deb but will try another mirror
Error: No more mirrors available for floorp-11.17.4.deb

### Reproduction Steps

1. apt/nala upgrade

### Expected Behavior

Install latest version 11.7.4

### Actual Behavior

Errors as mentioned above

### Screenshots

.

### Browser Version

11.7.3

### Operating System

Linux Mint 21.3

**Comment by mosamadeeb** [comment]
Installing floorp for the first time and I faced the same issue.

nala
```
Error: Hash Sum does not match: floorp-11.17.4.deb
  Expected Hash: SHA256: dd4e35b5853e36b911a67d658aff4140ad1adb734fefc0a02a46a002d7e1173d
  Received Hash: SHA256: 4d04119eaa425f641fbbaba065f4c955ce7e2ed1788e38aab20b69d3dacb78d6
Notice: Nala has removed floorp-11.17.4.deb
```

apt
```
Get:1 https://ppa.floorp.app/amd64 ./ floorp 11.17.4 [98.3 MB]
Err:1 https://ppa.floorp.app/amd64 ./ floorp 11.17.4
  File has unexpected size (27926272 != 98336684). Mirror sync in progress? [IP: 172.67.216.53 443]
  Hashes of expected file:
   - SHA256:dd4e35b5853e36b911a67d658aff4140ad1adb734fefc0a02a46a002d7e1173d
   - SHA1:6b6bacb0e69a31b4c4a7dcce2f08dacb533845a7 [weak]
   - MD5Sum:cd5a0ea2e7c76d1e11d1f4e2599022de [weak]
   - Filesize:98336684 [weak]
E: Failed to fetch https://ppa.floorp.app/amd64/./floorp-11.17.4.deb  File has unexpected size (27926272 != 98336684). Mirror sync in progress? [IP: 172.67.216.53 443]
   Hashes of expected file:
    - SHA256:dd4e35b5853e36b911a67d658aff4140ad1adb734fefc0a02a46a002d7e1173d
    - SHA1:6b6bacb0e69a31b4c4a7dcce2f08dacb533845a7 [weak]
    - MD5Sum:cd5a0ea2e7c76d1e11d1f4e2599022de [weak]
    - Filesize:98336684 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

The apt error is suggesting that the .deb is 27 MB instead of the expected 98 MB.

**Comment by creeper-0910** [comment]
Fixed!
```
sudo rm -rf /var/lib/apt/lists/*
sudo apt update
sudo apt upgrade
```
