### ISSUE TITLE
[Bug]: PPA Unable to install latest version 

### ISSUE THREAD

**Issue by OGZedHed** [Floorp-Projects/Floorp#1359]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

PPA will not install latest version 

### Reproduction Steps

Follow PPA installation steps
Attempt to install Floorp

### Expected Behavior

Installs floorp

### Actual Behavior

Provides Apt error unable to install Floorp

### Screenshots

N/A

### Browser Version

17

### Operating System

Linux Ubuntu

**Comment by creeper-0910** [comment]
Fixed&Duplicate:https://github.com/Floorp-Projects/Floorp/issues/1358
