### ISSUE TITLE
[Bug]: Home shortcut problem。

### ISSUE THREAD

**Issue by nanmofeng** [Floorp-Projects/Floorp#1360]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

First of all, are the two-line shortcuts intentional?

The homepage of version V11.17.4 has an extra row of shortcut icons. The added row only shows the first shortcut. As a patient with moderate obsessive-compulsive disorder, it is too uncomfortable to see.
In addition, the icon spacing of version 115 is 5 pixels, while the spacing between icons of version 128 is 10 pixels. I personally feel that the spacing of 10 pixels is a bit too large. Before the update to version 128, I always thought that the homepage of version 115 was the most beautiful among all browsers! This single-line shortcut is very simple and beautiful.
But unfortunately, you changed it to two lines in the latest version, which makes me very sad.
Here I would like to ask whether it is possible to completely restore the homepage style of version 115, that is:
1. Single-line homepage shortcuts on the homepage;
2. A maximum of 8 icons in one line;
3. Icon spacing of 5 pixels;

Please consider it again, and thank you again for your selfless work.

### Reproduction Steps

Just open the home page.

### Expected Behavior

See the description in Shangshu.

### Actual Behavior

Affects visual habits.

### Screenshots

![微信图片_20240819095140](https://github.com/user-attachments/assets/d8e1104b-29e4-4675-b966-f61751c99579)
![微信图片_20240819095224](https://github.com/user-attachments/assets/df917259-a1cc-4787-99f3-44ba39072b04)

### Browser Version

11.17.4

### Operating System

Windows10

**Comment by surapunoyousei** [comment]
Will be fixed

**Comment by nanmofeng** [comment]
> Will be fixed 将被修复
The spacing between icons is not necessarily 5 pixels. I just made a simple measurement. Please refer to the 115 version. Thank you.
