### ISSUE TITLE
[Bug]: Pinned tabs can scroll out of view

### ISSUE THREAD

**Issue by tbekolay** [Floorp-Projects/Floorp#1366]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Since updating floorp, pinned tabs no longer always stay stickied to the tab bar, it is now possible to scroll them out of view. I consider this a bug as that's the primary reason for having pinned tabs.

### Reproduction Steps

1. Open a new window.
2. Pin a tab.
3. Open enough new tabs that they tab bar needs to scroll.

### Expected Behavior

The pinned tabs remain visible at the left of the tab bar.

### Actual Behavior

The pinned tabs scroll out of view.

### Screenshots

See this window, in which the duckduckgo tab is pinned (you can see that it's smaller than the rest).

![1](https://github.com/user-attachments/assets/f387c74b-58e5-40a5-83d9-24882b815b31)

After opening up some new tabs, you can see that the tab bar no longer includes the pinned duckduckgo tab at the left.

![2](https://github.com/user-attachments/assets/84678422-1b49-452c-aa6c-7085fe9de269)

### Browser Version

11.17.4

### Operating System

Debian 12

### Additional Context

This has also been seen by [some users on reddit](https://www.reddit.com/r/Floorp/comments/1euzyar/bug_pinned_tabs_are_not_completely_pinned/).

**Comment by rolandixor** [comment]
I can confirm this is happening to me as well.

**Comment by azhe403** [comment]
in 11.17.5 happened too

**Comment by surapunoyousei** [comment]
Please, Do not post “Me too” comments.

**Comment by tbekolay** [comment]
I can confirm this is fixed in the new 11.18.0. ありがとうございます!
