### ISSUE TITLE
[Bug]: Vertical Tab Sidebar and Bookmarks Toolbar have conflicting/overlapping positions when bookmarks "Only show on new tab"

### ISSUE THREAD

**Issue by Picaseaux** [Floorp-Projects/Floorp#1367]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When the bookmarks toolbar is set to "only show on new tab" the vertical tabs sidebar's upper boundaries are too high (as if the bookmarks toolbar isn't there) and the bookmarks toolbar draws over the vertical tab sidebar. This can be seen on the new tab page. The issue also persists when "collapse vertical sidebar" is enabled but in this case the vertical sidebar draws over the bookmarks toolbar on the new tab page. Notably, this same upper boundary issue also applies to the Browser Manager sidebar although it doesn't cause a disruptive experience.

### Reproduction Steps

1. make sure bookmarks toolbar is visible and set to "always show"
2. Set the browser to have vertical tabs enabled (left side) (collapsing or not)
3. navigate to the new tab page by opening a new tab
4. right click the bookmarks toolbar and select "bookmarks toolbar"
5. click "only show on new tab"

### Expected Behavior

The upper boundaries of the vertical tab sidebar should adjust to a lower position when a new tab is opened

### Actual Behavior

The upper boundaries of the vertical tab sidebar does not adjust to a lower position when a new tab is opened.

### Screenshots

**Without collapsing tabs:**
https://github.com/user-attachments/assets/d9d68e7b-72a5-4368-b2d9-8fef07e643b8

**With collapsing tabs:**
https://github.com/user-attachments/assets/2659abf5-4845-4c73-be2a-cfaea4a732cd

### Browser Version

11.17.4 (64-bit)

### Operating System

Windows 10

### Additional Context

This is a new issue with one of the recent updates as this bug was not present a few days ago.

**Comment by surapunoyousei** [comment]
I will send patch
