### ISSUE TITLE
[Bug]: Shortcuts with Blur effect enabled will show overlay the menu.

### ISSUE THREAD

**Issue by TheOnlyChuon** [Floorp-Projects/Floorp#1369]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] This issue is specific to this browser and does not occur in other browsers.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.

### Bug Summary

With the 'Disable blur effect in Floorp Home' turned off, which means the blur effect for shortcuts is enabled, the blur background will show overlay the three-dot menu. This doesn't happen when we turn off that setting.

### Reproduction Steps

1. Open Floorp Settings > Home > Turn off 'Disable blur effect in Floorp Home' to make shortcuts in Home blur.
2. Click at the three-dot menu on top right of each shortcut.

### Expected Behavior

When we click at the three-dot button, the menu should show on top of those shortcuts, not being overlayed.

### Actual Behavior

With the 'Disable blur effect in Floorp Home' turned off, which means the blur effect for shortcuts is enabled, the blur background will show overlay the three-dot menu. This doesn't happen when we turn off that setting.

### Screenshots

- With the 'Disable blur effect in Floorp Home' disabled:
![image](https://github.com/user-attachments/assets/61660d2d-781d-4c7b-bf84-3002e3f8b6a8)

- With the 'Disable blur effect in Floorp Home' enabled:
![image](https://github.com/user-attachments/assets/d0de7c5b-3dc5-43b2-816b-78f9980b891f)

### Browser Version

Version 11.17.4 (64-bit) | Firefox: 128.1.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
duplicate
