### ISSUE TITLE
Invent and add a second secondary version of Floorp based on the most recent regular firefox relaese to take advantage of new technologies without telemetry

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#137]
Hello, i find this comment in reddit : "If you are a home user, use Release. ESR is meant for deployments, doesn't receive all security patches, and will be a year behind the current technology before you get a major update. Release is ALWAYS better"

https://www.reddit.com/r/firefox/comments/8uqur9/firefox_vs_firefox_esr_whats_the_right_choice/

so my suggestion please is obviously to keep the wonderful Floorp Browser based on Firefox ESR and to invent and add a second version of our beloved Floorp Browser based on the most recent regular firefox relaese to take advantage of new technologies , so this second version of Floorp will be like regular firefox but without telemetry because it's complicated and long and tiring to disable telemetry and telemetry settings may change from one version to another, this new version may have a different name from Floorp to avoid possible confusion, for example Floorp lite, or Floo browser, or a name completely different from Floorp, and you do not need to integrate all the new features and improvements of Floorp in this new version which will be content to be based on the most recent normal firefox release but removing telemetry and why not adding other interesting options that I previously suggested like dice activate the session store to save battery and hard drive and increase the network buffer cache for streaming video for smoother playback or full buffer video when the network is weak....

i know that librefox removes telemetry but librefox is privacy oriented and doesn't want us to use google as a search engine and has a different behavior than firefox for example when you click on a bookmark it opens in a new tab and librefox has some bugs that do not exist in firefox because I saw the librefox gitlab page and librefox tries to solve these rare problems but we want a more stable experience that mimics the regular firefox release but without telemetry and with the session store reduced or removed and possibility to disable MSE media source extension to full buffer video....

I know it's very difficult to invent a new version and i completely understand if you can't do it, there is no problem :) just i was scared when i heard that 'we have to wait a whole year to take advantage of new technologies in firefox ESR and that there are apparently some security problems with firefox ESR ..... thank you very much :)

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/107#issuecomment-1322826915


---
![image](https://user-images.githubusercontent.com/73892113/203184565-6508f774-17e1-4070-9c24-76a1b13453e9.png)

**Comment by surapunoyousei** [comment]
Instead, I'm going to update Firefox when the ESR version is released. You don't have to wait for the ESR version to end support.

When Firefox 115 comes out, I want to migrate to Firefox ESR 115.

**Comment by surapunoyousei** [comment]
It is currently impossible to continue to offer two versions. Because Floorp Project has only 4 developers.
