### ISSUE TITLE
[Bug]: Color the Tab Bar using the current website's favicon color is not working

### ISSUE THREAD

**Issue by odd-git** [Floorp-Projects/Floorp#1371]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported. (There is an "old" report)
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After the update to the 11.17.4  "Color the Tab Bar using the current website's favicon color" it's not working properly. 
I'm on Fedora 40 with Gnome46
I have tried also on window and the issue is the same.

### Reproduction Steps

1. Just enable  "Color the Tab Bar using the current website's favicon color"

### Expected Behavior

Color of the tab bar match the favicon

### Actual Behavior

Tab Bar color doesn't match the favicon 

### Screenshots

![Screenshot from 2024-08-20 16-04-23](https://github.com/user-attachments/assets/b06b0de5-5621-4afd-aa0c-95a7f08eccd1)

### Browser Version

11.17.4

### Operating System

Fedora 46 and Windows 11

**Comment by sillyspiel** [comment]
Same issue here, LMDE 6 (Linux Mint Debian Edition) with both flatpak and manual installation.

**Comment by xenopiece99** [comment]
same issue on my msi laptop running windows 11 with floorp version 11.17.6.

**Comment by creeper-0910** [comment]
Since we are aware of this problem, please refrain from commenting that "me too".

**Comment by surapunoyousei** [comment]
Fixed
