### ISSUE TITLE
[Bug]: unusable scroll bar in vertical tabs

### ISSUE THREAD

**Issue by surasshu** [Floorp-Projects/Floorp#1372]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

with the latest version of floorp (11.17.4, 64bit), the vertical tab has a scrollbar that doesn't do anything, covering half the icons. i've included a screenshot of what it looks like both with the auto-hide feature enabled and disabled. if you add enough icons to fill the vertical bar, another scrollbar appears, basically covering up all the tabicons (3rd screenshot).

### Reproduction Steps

1. open browser
2. observe that on the vertical tab bar, a black scrollbar appears that has no functionality

### Expected Behavior

no scrollbar until needed

### Actual Behavior

scrollbar even when not needed (also not functional)

### Screenshots

![Clipboarder 2024 08 20-003](https://github.com/user-attachments/assets/34dfb12d-3f8d-45d2-98e1-ea1f914063b0)
![Clipboarder 2024 08 20-004](https://github.com/user-attachments/assets/6ae8f212-8972-4bca-b426-07803b1e95cd)
![Clipboarder 2024 08 20-005](https://github.com/user-attachments/assets/a5e5b80a-9caf-416b-bd46-db01f27964c4)

### Browser Version

11.17.4 64bit

### Operating System

win11

**Comment by Revelin-rmz** [comment]
I am unable to verify if this before was the same before the recent updates to Floorp v11.17.0, but interacting with the scroll bar also reduces the window size and drags the application around on the desktop.

**Comment by surasshu** [comment]
yes, i'm getting that too! forgot to mention it, thank you.

**Comment by Revelin-rmz** [comment]
I will make updates if anything changes but:

It is likely that a patch has been implemented as of now, since I have not made any changes to my Floorp setup and the fake scroll bar is gone and a functional one appears when needed. Thank you to the devs who worked hard to resolve this issue promptly!

**Comment by Picaseaux** [comment]
the extra scrollbar issue has been resolved in 11.17.5 but clicking and dragging on the scroll bar still moves the whole web browser around. the window moving handle zone needs to be shrunken horizontally from the right side of the vertical scrollbar on the to accommodate for the scroll bar.

**Comment by surapunoyousei** [comment]
Since Mozilla has started a native implementation of vertical tabs, I will not address this issue, which has existed since the past.  

Thank you for your understanding.
