### ISSUE TITLE
[Bug]: "Pwa/Web apps" and "Open previous windows and tabs" feature doesn't work properly at the same time.

### ISSUE THREAD

**Issue by 09u2h4n** [Floorp-Projects/Floorp#1374]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When you check "Open previous windows and tabs" feature it should continue after you restart the browser but when you install web apps (In my case web app is YouTube Music) and firstly close browser and then web app, **the browser doesn't open my previous windows** but if you first close web app and then browser **the browser opens my previous windows**.
So i thought maybe i should install web app with another browser profile which is worked but now when i open my web app it opens two profiles at the same time

### Reproduction Steps

1. Install "https://music.youtube.com/" as web app
2. Open some tabs in the browser
3. First close the browser and then YouTube Music
4. Reopen the browser or YouTube Music
5. Your previous tabs will disappaer

### Expected Behavior

When i restart my browser it should opens previous windows and tabs.

### Actual Behavior

It doesn't open previous windows and tabs.

### Screenshots

**Browser before i close (YouTube Music is in the background as a web app)**

![resim](https://github.com/user-attachments/assets/a297be28-d7eb-45df-9625-d427cfd7a6eb)
---
**Browser after i close (I firstly closed browser then YouTube Music)**

![resim](https://github.com/user-attachments/assets/81e9dea8-5a0e-4d00-a815-d5430bc639c7)

### Browser Version

11.17.4

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
Duplicate

**Comment by 09u2h4n** [comment]
> Duplicate

Hi, i couldn't find the post that i duplicated or the answer. Can you give a link :)
