### ISSUE TITLE
[Bug]: Your Floorp profile cannot be loaded. It may be missing or inaccessible.

### ISSUE THREAD

**Issue by NevilleMthw** [Floorp-Projects/Floorp#1378]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I recently installed Floorp and could not use the browser due to a profile missing error.

### Reproduction Steps

I installed the browser using this guide: https://ubuntuhandbook.org/index.php/2024/02/install-floorp-browser-ubuntu/ and option 1. Installation seemed successful with no errors in the command line.

### Expected Behavior

Expecting to use the browser directly after installation.

### Actual Behavior

Installation was successful.

### Screenshots

![image](https://github.com/user-attachments/assets/b68ce7c6-4cfb-43b1-b8a8-5481cd11a9e8)

### Browser Version

11.17.5

### Operating System

Ubuntu-Linux

**Comment by surapunoyousei** [comment]
https://ppa.floorp.app

**Comment by iHad168** [comment]
my flatpak floorp same issue show
