### ISSUE TITLE
Add option to disable Firefox Accessibility Service to improve performance

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#138]
Hello, in some cases, Mozilla recommends to disable Firefox Accessibility Service so it will be good ideao to add option to disable this service, thank you:

" What is the impact of having Firefox Accessibility Service enabled?
Firefox Accessibility Service may negatively impact Firefox browsing performance
Third party applications may be monitoring your web surfing activity
Firefox stability may be adversely affected

Anti-Virus and Anti-Malware Browser Plugins
If you determine an anti-virus software extension is enabling Firefox Accessibility Service Mozilla recommends you disable this 3rd party software feature. If a disable configuration option is not available Mozilla recommends disabling Firefox Accessibility Service from within Firefox.

Enterprise or Educational Monitoring and Access
Users in enterprise or educational networks should contact their administrator about disabling Firefox Accessibility Service.

Niche Shareware or Freeware applications
If you determine a 3rd party desktop application is enabling Firefox Accessibility Service and you are experiencing slowness or other performance related problems in Firefox, Mozilla recommends you disable or uninstall the 3rd party application. If you are unable to disable or uninstall, Mozilla recommends disabling Firefox Accessibility Service from within Firefox as a work around.

Malware and Adware
Firefox Accessibility Service can be abused by malware, if present, to monitor user behavior or access user information on the web.

If you suspect your device is infected with malware, consider purchasing and running a competent anti-malware software product to address the issue.

Anti-Virus and Anti-Malware Browser Plugins
Often described as "browser protections" promoting security improvements, these features rarely add valuable security to Firefox and other browsers. Most are poorly designed and poorly tested, and can inadvertently disable more effective security measures built into Firefox. These features also often cause problems during upgrades to Firefox, triggering nasty startup crashes and other abnormalities.

Mozilla does not support or sanction this use of Accessibility Service and actively works with anti-virus vendors to migrate their Accessibility Service extensions to other Firefox extension mechanisms designed for this use.

Mozilla recommends disabling these anti-virus features if they enable Firefox Accessibility Service."

https://support.mozilla.org/en-US/kb/accessibility-services#w_what-is-the-impact-of-having-firefox-accessibility-service-enabled

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/140#issuecomment-1547252868
