### ISSUE TITLE
[Bug]: media.block-autoplay-until-in-foreground not working

### ISSUE THREAD

**Issue by FGD-Garuda** [Floorp-Projects/Floorp#1380]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The config `media.block-autoplay-until-in-foreground` in `about:config` is not working, whether set to TRUE or FALSE, it ignores the setting and thinks it's FALSE.

This very useful feature is working fine out of the box on Firefox ESR 128 and also Nightly 131.

### Reproduction Steps

1. Install Floorp 11.17.5
2. Fetch https://www.youtube.com
3. Search for anything in order to get a list of videos
4. Right-click on any one in the list and open it in a background tab

### Expected Behavior

The background tab should BLOCK autoplay, like this:
![Screenshot_1](https://github.com/user-attachments/assets/ebc6a257-33a4-4110-bf01-66b579e15fec)

### Actual Behavior

Instead, it plays the video:
![Screenshot_2](https://github.com/user-attachments/assets/ac9c8be2-80cf-4c59-8367-0046abe7028b)

### Screenshots

In FF Nightly, as well as ESR 128,  the same configs are set as in Floorp:
![Screenshot_3](https://github.com/user-attachments/assets/a52ad253-f79c-4866-844d-50e2c7e0ed2e)

Except for Nightly, as well as ESR 128, the `autoplay-until-in-foreground` feature works.

### Browser Version

11.17.5

### Operating System

Arch Linux

### Additional Context

- I have tried a numerous amount of configs and none made it work.
- I read this [thread](https://github.com/Floorp-Projects/Floorp/issues/1264), but I cannot easily downgrade ffmpeg, as there are dependencies:
![Screenshot_4](https://github.com/user-attachments/assets/cf19b7bb-6a70-4796-ac33-386dd09ce7ae)
- I found one half-decent workaround, which is to Block Audio on the website, instead of Allow Audio&Video. This prevents background tab from autoplaying, but it does not autoplay when you bring it to foreground, you have to manually click either on the video or on the tiny PLAY button, depending on the website. This adds steps, time and multiply by the number of videos some people can load in background it adds up. Which is why it's only a half-decent workaround.

Since this is working with both FF ESR 128 and Nightly 131, I was wondering if something got impacted during the Floorp build process?

**Comment by creeper-0910** [comment]
Wait, it doesn't work with ESR128?

**Comment by FGD-Garuda** [comment]
> Wait, it doesn't work with ESR128?

Where did I write that? I will correct immediately.

It DOES work with ESR 128. You set it to TRUE and the Autoplay is blocked. You set it to FALSE and the Autoplay is not blocked.

**Comment by creeper-0910** [comment]
Ah, I must have misunderstood “Except for Nightly, as well as ESR 128”.Sorry.

**Comment by FGD-Garuda** [comment]
> I believe this issue has been resolved. Please check the latest version

On v11.17.7 I have the exact same behavior as 11.17.5 from my OP, which is that specific config does take effect when set to TRUE (which is the default) and always behaves as FALSE.

**Comment by CelestialCrafter** [comment]
> > I believe this issue has been resolved. Please check the latest version
> 
> On v11.17.7 I have the exact same behavior as 11.17.5 from my OP, which is that specific config does take effect when set to TRUE (which is the default) and always behaves as FALSE.

Getting the same behaviour on v11.17.7 aswell

**Comment by FGD-Garuda** [comment]
Hi @surapunoyousei , since I don't seem to be alone with this behavior, is it possible to re-open this potential bug?

I don't think it gets a lot of attention being in the `closed` section.

Thanks

**Comment by tk-master** [comment]
This prevents me from using the browser honestly.. I'm forced to stay with floorp-11.15 because of this, please fix it.. autoplay is unusable when everything starts playing in the background because you opened a couple of youtube tabs.. lol seems like an obvious thing to priority fix

**Comment by pa1kia** [comment]
this used to work fine, but i also noticed that it broke after the update. very frustrating to lose this functionality.

**Comment by surapunoyousei** [comment]
We ask that you avoid unnecessary comments.

**Comment by knot2006** [comment]
11.18.0 (64-bit) Windows
Still does not work for me

Add-ons like this dont help/work as well:
https://addons.mozilla.org/en-GB/firefox/addon/enhancer-for-youtube/
![image](https://github.com/user-attachments/assets/ab39d937-e203-47fa-b335-dada70f8f174)

**Comment by surapunoyousei** [comment]
I am currently working on a solution to this problem.

**Comment by FGD-Garuda** [comment]
> I am currently working on a solution to this problem.

Thank you very much!!

**Comment by surapunoyousei** [comment]
Hey. I find the way to fix this issue. This patch will send to Daylight build first. After pass the test, This patch will available stable version of Floorp. Thank you for your help.

**Comment by CelestialCrafter** [comment]
works on daylight 11.18.1/20240907053122! thank you!

**Comment by FGD-Garuda** [comment]
Yes!! Me too it works!! 😃

**Comment by surapunoyousei** [comment]
I will deploy this fix. Thanks

**Comment by CelestialCrafter** [comment]
close issue ?

**Comment by JourneyOver** [comment]
This seems to be an issue still as I have the setting set to true and it's still playing videos in a background tab which is kind of annoying when I click multiple different youtube videos to set them to background tabs to go through and they all start playing at the same time :/ I have tried messing with the setting moving it between true and false and it does not seem to change anything.
