### ISSUE TITLE
[bug]: can't set keybindings, and apparently my browser is being managed by my organization

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [Floorp-Projects/Floorp#1381]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

1. I can't set any keybindings, I can toggle "Disable Mozilla Firefox's keyboard shortcuts
", but pressing on the input bar for the keybinding does nothing
2. aparently my browser is being managed by my organization, it shouldn't be, I tried removing all plugins, hell, I even deleted all of ~/.floorp/ and started fresh, neither of those helped

### Reproduction Steps

honestly, idk, below is a list of the extensions I use, though I doubt that'd help, as I said, I deleted everything, and that still didn't fix it

privacy badger, read aloud, sponsorblock, ublock origin, vimium, facebook container, greasemonkey, return YT dislike, redirector, video DownloadHelper, Dark Reader, Aria2 manager, proton pass, dictionary anywhere, and finally, reddit enhancement suite

### Expected Behavior

I mean, isn't it obvious

### Actual Behavior

this field is redundant lol

### Screenshots

none that are relevant, sorry

### Browser Version

Mozilla Floorp 11.17.4

### Operating System

endeavorOS (arch based linux distrobution

**Comment by surapunoyousei** [comment]
This is because many keyboard shortcuts are reserved by the operating system.

2. it is a specification in some parts of Linux

**Comment by 4rtemis-4rrow** [comment]
well, reserved by the OS should mean that the keymap doesn't work, not that I can't set it in the first place

as I said, I can't set any keymaps, period

and besides, I'm using a window manager, I know all the keymaps which I've set for my OS

**Comment by surapunoyousei** [comment]
Floorp uses the configuration state to keyboard shortcuts reported by Firefox, so there is not an exact match.

Please understand.

**Comment by surapunoyousei** [comment]
Due to The short cut registered in the system,  cannot be entered.

**Comment by regularentropy** [comment]
> I don't get it
> 
> as I'm saying, I CAN'T set a keymap, like, physically the app isn't allowing me, when I press on the input bar to type in my keymap, it doesn't respond, like, if I press it, and then press ctrl+J, it doesn't do anything, no keymap gets inserted, nothing

Hmm. I can assume it's inserted but not displayed in the GUI. Could you please go to "about:config" and search for "floorp.browser.nora.csk.data"?  Furthermore, please send the console logs.

**Comment by 4rtemis-4rrow** [comment]
> Due to The short cut registered in the system, cannot be entered.

yeah, but ctrl+J isn't used by my system, at all, infact, all my system shortcuts use the windows key as a modifier

as I said, I can't use any shortcut, regardless of what it is

> Hmm. I can assume it's inserted but not displayed in the GUI. Could you please go to "about:config" and check the entries for "floorp.browser.nora.csk.data"? Furthermore, please send the console logs.

it's empty

as for the console logs, idk how to get them, the help menu (ironically) wasn't of much help
