### ISSUE TITLE
[Bug]: Top bar completely white after update to 11.17.6 with certain browser themes (UI design doesn't effect it)

### ISSUE THREAD

**Issue by AxeldeWater** [Floorp-Projects/Floorp#1382]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

With certain browser themes (eg in this case Firefox Alpenglow theme) the top bar becomes white and unreadable. Other themes also have changed theme behaviour, but are not always as critical. The UI design has no effect on it. 

### Reproduction Steps

1. Update to 11.17.6
2. Install Firefox Alpenglow theme from the firefox theme store. 

### Expected Behavior

At least a usable top bar, preferably the previous behaviour. 

### Actual Behavior

Top bar becomes white and unusable, does not have the theme image style thing in the background like the sidebar does. 

### Screenshots

![Screenshot from 2024-08-22 22-17-40](https://github.com/user-attachments/assets/5794cac0-a57c-46ab-9030-3353134395ef)

### Browser Version

11.17.6

### Operating System

Linux Mint Cinnamon 22

**Comment by AxeldeWater** [comment]
![Screenshot from 2024-08-22 22-28-52](https://github.com/user-attachments/assets/aa5412f8-cdc1-4172-93cd-715c4dc474e2)

**Comment by creeper-0910** [comment]
That was my mistake, sorry.
It will be fixed in the next version.

**Comment by AxeldeWater** [comment]
Problem seems to be fixed now, I'll close the issue.
