### ISSUE TITLE
[Bug]: Native messaging does not work

### ISSUE THREAD

**Issue by stilgarwolf** [Floorp-Projects/Floorp#1385]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Extensions using native messaging are not working.

### Reproduction Steps

1. _Install any extension using native messaging. (Try [KeePassXC-Browser](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search))

### Expected Behavior

Extension must work, like in Firefox.

### Actual Behavior

Extension does not work.

### Screenshots

![image](https://github.com/user-attachments/assets/eb7bb02e-5eb8-4dc4-9111-f4e283ccd109)

### Browser Version

11.17.6 (64-bit)

### Operating System

Debian unstable

### Additional Context

I wrote a small extension and I found Floorp is using wrong directory when checking native messaging application json file:
"$HOME/.mozilla/native-messaging-hosts" instead of "$HOME/.floorp/native-messaging-hosts"

Workaround: For above example, moving "org.keepassxc.keepassxc_browser.json" file to "$HOME/.mozilla/native-messaging-hosts/" folder solves the issue.

**Comment by surapunoyousei** [comment]
Hmm....

**Comment by surapunoyousei** [comment]
It makes sense to fix this, so I'll investigate.

**Comment by creeper-0910** [comment]
Sorry, I made a mistake.

**Comment by surapunoyousei** [comment]
Hey! Did you check latest version?

**Comment by stilgarwolf** [comment]
> Hey! Did you check latest version?

Yes, Yes, 11.17.7 (64-bit), Debian SID
Still not working.

**Comment by noizo** [comment]
I use Enpass password manager, which is 99% also uses native messaging.
Everything works fine in Floorp.

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/f2d5aa83-fb93-4f71-bf9f-25d5a4cd91f1)

**Comment by surapunoyousei** [comment]
The latest version already seems to work.

Try the PPA version of Floorp. I'm assuming this issue is complete since we are getting a working environment again.

**Comment by stilgarwolf** [comment]
No, it's not working.

KeePassXC puts "org.keepassxc.keepassxc_browser.json" file in .mozilla folder when enables Firefox browser.
Moving the file to .floorp makes the extension unusable. Re-enabling Firefox in KeepassXC desktop app recreates json file in .mozilla folder.

The extension works with Floorp, but using .mozilla folder.

With LibreWolf, KeePassXC correctly uses .librewolf folder, so it seems Floorp is reporting wrong location of "native-messaging-hosts" folder.

**Comment by surapunoyousei** [comment]
Sorry, but Floorp intentionally uses the .mozilla folder.

This is because native applications place files to communicate with extensions in the .mozilla folder.

Using the .floorp folder would be confusing and difficult to use for users who are not familiar with difficult concepts such as hidden folders!

**Comment by stilgarwolf** [comment]
Using both .floorp and .mozilla folders would be better, I think.
And, at least, write a notice about it.
