### ISSUE TITLE
[Bug]: Security features warning after updating Floorp to 11.17.6 (Flatpak)

### ISSUE THREAD

**Issue by TheOnlyChuon** [Floorp-Projects/Floorp#1386]
### Pre-Submission Checklist

- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have included relevant screenshots or console outputs.

### Bug Summary

After updating Floorp (flatpak version) to 11.17.6, Floorp shows this warning on top of pages:
"Some of Floorp's security features may offer less protection on your current operating system."

### Reproduction Steps

Update Floorp (flatpak) to the 11.17.6

### Expected Behavior

Securities features it mentioned should work at normal

### Actual Behavior

The warning just shows up after update, and one of my addons: SponsorBlock asked me to let it access some web data because it got blocked

### Screenshots

![image](https://github.com/user-attachments/assets/f2d96bfb-add2-4e53-a3e8-70d6be14bfe9)

### Browser Version

11.17.6

### Operating System

Pop!_OS 22.04 LTS

### Additional Context

This is what I found in the link on the warning:
https://support.mozilla.org/en-US/kb/install-firefox-linux?as=u&utm_source=inproduct#w_security-features-warning
![image](https://github.com/user-attachments/assets/395d6cea-2f11-4736-9fb8-1f459c36c0da)
I don't know if this problem only happens to me, just wanna report this to you, this didn't happen in previous build so maybe this is a bug and I don't think this is really a big security problems to be reported in 'Security'.  A tutorial found in the link but for firefox only, I am not an linux nerd so if you have an easy way to temporary fix it, I will appreciate it

**Comment by creeper-0910** [comment]
Perhaps it is a Firefox issue.
A similar problem occurs in Firefox.

**Comment by TheOnlyChuon** [comment]
> Perhaps it is a Firefox issue. A similar problem occurs in Firefox.

Can you give me more details on it? I can't find any information related to this and how to get rid of it, the only thing I found just the link above.

**Comment by creeper-0910** [comment]
https://forum.manjaro.org/t/firefoxs-security-features-may-offer-less-protection-on-your-current-operating-system/166591
Similar cases
Perhaps a fix will be made on the Firefox side.

**Comment by TheOnlyChuon** [comment]
> Perhaps a fix will be made on the Firefox side.
Base on what in the docs says, I think there will no fix for this and user need to work around with it. Since there is already an official tutorial, and you are a Floorp contributor, can you tell me if the tutorial works for floorp? or I need to replace 'firefox' with 'floorp' and all directory to flatpack's installation path?

**Comment by creeper-0910** [comment]
OK, I will try it when I have time.

**Comment by creeper-0910** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1909832
It still seems to be a bug in Firefox.
I will try to apply the patch!

**Comment by TheOnlyChuon** [comment]
> I will try to apply the patch!

I understand that after the Floorp 11.15.00 update, you guys have a lot of work to do and many bugs to fix. It's 2.30 AM in Japan right now and you're still doing your best to keep Floorp alive. I just want to say a thank you from the bottom of my heart for all of your efforts, hope you guys have more time to chill and relax after work!!
![1155400693398638663](https://github.com/user-attachments/assets/ab903f0d-b218-4a77-b6e0-3457c2a7e6ac)

**Comment by tradjincal** [comment]
To fix locally the problem, I followed the instructions from firefox doc https://support.mozilla.org/fr/kb/installer-firefox-linux?as=u&utm_source=inproduct and adapt it for floorp:

1. Edit the file `/etc/apparmor.d/floorp-local` and add the following configuration
``` 
abi <abi/4.0>,
include <tunables/global>
profile floorp-local
/usr/lib/floorp/{floorp,floorp-bin,updater}
flags=(unconfined) {

userns,
include if exists <local/floorp>
}
```
Ensure about binaries path in debug information

2. restart apparmor service
```
sudo systemctl restart apparmor.service
```

3. Restart floorp and enjoy (sorry my firefox is in french but user namespace should be to true)
![image](https://github.com/user-attachments/assets/f8897efb-9b3e-40a0-b80f-a31987bfdbb3)
