### ISSUE TITLE
[Bug]: Floorp for Androidと誤った表記になっています

### ISSUE THREAD

**Issue by breadbeforerice** [Floorp-Projects/Floorp#1388]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

言語が日本語の場合、Floorp for Android または iOS をダウンロードしてモバイル端末と同期しましょう。
とFirefoxからリネームされています。（言語を英語に変更した場合はFirefox表記でした）

### Reproduction Steps

設定→同期に移動

### Expected Behavior

Firefox for Android または iOS をダウンロードしてモバイル端末と同期しましょう。と正しい製品名が表記されている

### Actual Behavior

Floorp for Android または iOS をダウンロードしてモバイル端末と同期しましょう。と誤った製品名が表記されています

### Screenshots

![2024_8_24_9_34_37_11855](https://github.com/user-attachments/assets/f8983f88-2131-4d24-b9bd-f4f453da2575)

### Browser Version

11.17.3

### Operating System

windows10

**Comment by CutterKnife** [comment]
PR を送信しました。
https://github.com/Floorp-Projects/Unified-l10n-central/pull/72

**Comment by regularentropy** [comment]
Fixed
