### ISSUE TITLE
[Bug]: When restoring windows from previous sessions, sidebar web panels are opened in new windows as well

### ISSUE THREAD

**Issue by DivineMK** [Floorp-Projects/Floorp#1391]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Previously, when restoring window after quitting, sidebar web panels are not opened. Now they also open in separate windows.

### Reproduction Steps

1. Open a sidebar web panel  (Floorp docs for instance)
2. Quit
3. Open Floorp again

### Expected Behavior

1. No sidebar web panel in new windows

### Actual Behavior

1. Previously not unloaded web panels get opened in new separate windows

### Screenshots

.

### Browser Version

11.17.7

### Operating System

Linux Mint 22

**Comment by guigirl42** [comment]
This happened to me with `11.17.6`, & unfortunately is _still_ happening with `11.17.7.`  As i routinely use multiple Web Panels during any given session, later restarts unpleasantly result in _multiple_ single-tab windows launching. It's pretty messy. 

`ArchLinux KDEPlasma`

**Comment by Muko-Tabi** [comment]
Same here as well, it delete the session with all of my pinned tabs, and open single windows from web panels. It doesn't happen everytime but it's still half of the time after closing Floorp. I think the reason might because the web panels aren't closed when quitting Floorp then Floorp think those web panels are your last session and not your real one.

**Comment by surapunoyousei** [comment]
As I mentioned on Reddit, I am already investigating this issue.

**Comment by surapunoyousei** [comment]
Hey. I find the way to fix this issue. This patch will send to Daylight build first. After pass the test, This patch will available stable version of Floorp. Thank you for your help.

**Comment by Muko-Tabi** [comment]
Works in the beta for me on Linux Fedora

**Comment by 0ussamaBernou** [comment]
same here on pop os

**Comment by Muko-Tabi** [comment]
Test again on my Windows 11 VM, lgtm as well

**Comment by surapunoyousei** [comment]
After your test, I will create new released

**Comment by Muko-Tabi** [comment]
No bug so far, so should be good for development. If any linux user wanna try it but find it annoying to launch the executable everything, you could try running this in the terminal to have everything ready:
```
mkdir -p ~/.local/share/Floorp\ Daylight && cd /tmp && curl -L -o floorp-linux-x86_64.tar.bz2 https://github.com/Floorp-Projects/Floorp/releases/download/beta/floorp-linux-x86_64.tar.bz2 && tar -xjf floorp-linux-x86_64.tar.bz2 && mv floorp/* ~/.local/share/Floorp\ Daylight/ && rm -rf floorp floorp-linux-x86_64.tar.bz2 && mkdir -p ~/.local/share/icons/hicolor/128x128/apps && cp ~/.local/share/Floorp\ Daylight/browser/chrome/icons/default/default128.png ~/.local/share/icons/hicolor/128x128/apps/floorp-daylight.png && echo "[Desktop Entry]
Version=1.0
Name=Floorp Daylight
GenericName=Web Browser
Comment=Browse the Web
Exec=\"$(echo ~)/.local/share/Floorp Daylight/floorp\" %u
Icon=floorp-daylight
Terminal=false
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Categories=Network;WebBrowser;
Keywords=ablaze;web;browser;internet;
Actions=new-window;new-private-window;profile-manager-window;
StartupWMClass=floorp

[Desktop Action new-window]
Name=Open a New Window
Exec=\"$(echo ~)/.local/share/Floorp Daylight/floorp\" --new-window %u

[Desktop Action new-private-window]
Name=Open a New Private Window
Exec=\"$(echo ~)/.local/share/Floorp Daylight/floorp\" --private-window %u

[Desktop Action profile-manager-window]
Name=Open the Profile Manager
Exec=\"$(echo ~)/.local/share/Floorp Daylight/floorp\" --ProfileManager" > ~/.local/share/applications/floorp-daylight.desktop && gtk-update-icon-cache -f -t ~/.local/share/icons
```
logout and login in case it doesn't load
and uninstall with
```
rm -rf ~/.local/share/Floorp\ Daylight && rm ~/.local/share/applications/floorp-daylight.desktop && rm ~/.local/share/icons/hicolor/128x128/apps/floorp-daylight.png && gtk-update-icon-cache -f -t ~/.local/share/icons
```

**Comment by surapunoyousei** [comment]
ty

**Comment by uugaabuugaa** [comment]
Is this issue fixed on 11.17.8? I had to stop using sidebar panel and web-app for a while. I'd either get multiple windows for sidebar panels, web-app along with normal window with all tabs or lose the main window with all tabs and only get one window with a tab from sidebar or web-app.

**Comment by DivineMK** [comment]
Fixed for me on 11.17.8 as well.

**Comment by DivineMK** [comment]
I realized there might be a new bug that seems likely to be related. I don't know if I should make a new issue or reopen this?
The bug is with the Whatsapp web panel saying that another Whatsapp tab is opened after just restarting Floorp. Please let me know how I might be able to gain more debugging information.

**Comment by surapunoyousei** [comment]
Provide video is the best esy

**Comment by surapunoyousei** [comment]
Are you saying that this button appears even though you don't have any tabs open elsewhere?


If so, please let us know if you are using a container tab for that web panel.

**Comment by DivineMK** [comment]
Yes I don't open any other Whatsapp tab. I also don't use container.

**Comment by surapunoyousei** [comment]
In that case, it is difficult to fix it because I have no idea what it is.

This is because I don't know what implementation WhatsApp uses for its web pages.
 
It does not seem to be a major problem, so I will leave it alone. Sorry.

**Comment by DivineMK** [comment]
I want to note that this issue doesn't happen before though. I realized that this doesn't happen when I open Whatsapp outside of web panels. This might be that when opening from the web panels after restarting, it actually open more than 1 windows. Is there a way to see opened windows to confirm this?

**Comment by surapunoyousei** [comment]
Use Floorp View

**Comment by DivineMK** [comment]
It doesn't show tabs open from web panels though.

**Comment by DivineMK** [comment]
I confirmed that the web panels indeed open 2 tabs by using Ctrl-Tab.

**Comment by surapunoyousei** [comment]
This is intentional. It should only do so for web panels that have the container tab applied.

I will change this in the next update.
