### ISSUE TITLE
[Bug]: Uh, I don't understand HOW and WHERE to import Bookmarks from Firefox 

### ISSUE THREAD

**Issue by aaronsql2019** [Floorp-Projects/Floorp#1399]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Uh, this is supposed to be a 'Firefox-based Browser'. 
I don't see ANY options to 'Import my bookmarks from Firefox'. 

Technically, I have TWO Firefoxes installed (Normal, and Developer).
I was expecting to be able to import Bookmarks from EITHER or preferably the OPTION for BOTH browsers into floorp.

I'm just confused why I can't select to either Import OR NOT IMPORT from Firefox.

Does Floorp automatically import from Firefox? Why can't I choose WHICH Firefox browsers?

### Reproduction Steps

1. Install Floorp
2. Open Floorp
3. I get a dialogue box to 'Import Browser' data (see screenshot)
4. I'm CONFUSED Why I can't select OR deselect Firefox browser profiles (I have standard and developer).

### Expected Behavior

I'd like to be able to import my data from Firefox.
TECHNICALLY, I'd like to keep my data SYNCED in between floorp and firefox. I'd like to see this a bi-directional relationship, instead of ONLY at import / first run.

### Actual Behavior

I don't see the option to IMPORT or NOT IMPORT from my Firefox Install(s). 

I have 6+ Chrome Profiles
Microsoft Edge
HTML / CSV

### Screenshots

![Floorp_Import_From_Browsers_20240827](https://github.com/user-attachments/assets/7e4da24a-ec7d-45c1-8fa6-5015e13c10db)

### Browser Version

Released on: August 27, 2024 v11.17.8

### Operating System

Windows 11 Latest 20240827

### Additional Context

I have a LARGE browser history and a LARGE amount of bookmarks (only 4k I thnk).
I think that in CHROME I have maybe 10k bookmarks. I'm not going to sync those right NOW, but at SOME point, I'd like to do that later (once I consolidate).

**Comment by aaronsql2019** [comment]
Also, I think it MIGHT be easier to allow me to 'Import from Multiple Browsers' upon FirstLaunch. I'll go look for the tool and see if it works for future imports. Thanks

**Comment by breadbeforerice** [comment]
https://github.com/Floorp-Projects/Floorp/issues/744
It's a duplicate.
Also, I think maybe Firefox ESR can't import the same way.

**Comment by aaronsql2019** [comment]
Sorry, I didn't see that. I checked the open issues, I'm amazed that I couldn't find that. So sorry to be a pain!
