### ISSUE TITLE
Some new revolutinary tips to speed browser and economize energy

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#140]
Hello, i discover some tips to speed browser , may be it could be interisting to enable some setting by default ou  add quick options to enable them please : 

EDIT : i just add new tricks and ideas, this is the best of the best : i repost here beacause i make new thread but it was cloded : 

Hello @surapunoyousei , after months of hard search, i think these tricks and modifcation can make Floorp browser even most faster and speed and battery saver, it will be great to add option to enable or disable them with one click , thank you !

browser.sessionstore.privacy_level 2

accessibility.force_disabled 1

browser.tabs.firefox-view false

browser.sessionstore.idleDelay 1

browser.sessionstore.interval.idle 2147483647

browser.sessionstore.interval 2147483647

DISABLE SESSION STORAGE

browser.sessionstore.max_tabs_undo 0

browser.sessionstore.max_windows_undo 0

browser.sessionstore.resume_from_crash FALSE

Browser.startup.page 0

browser.cache.disk.content_type_media_limit

MemoryReduction

Reduce session history entries

user_pref("browser.sessionhistory.max_entries", 0);

Turn off bfcache

user_pref("browser.sessionhistory.max_total_viewers", 0);

full-screen-api.warning.timeout 0
full-screen-api.transition-duration.enter = "0 0"
full-screen-api.transition-duration.leave = "0 0"
browser.fullscreen.autohide

browser.sessionhistory.max_entries 5

browser.sessionhistory.max_total_viewers 5

dom.ipc.processCount 1 RAM DIMINUTION MEMOIRE
browser.preferences.defaultPerformanceSettings.enabled false

****CACHE

https://kanasys.com/tech/892
https://wiki.calculate-linux.org/firefox

about:cache

browser.cache.disk.max_entry_size 128 (disable youtube cache)

browser.cache.disk.parent_directory (changer dossier cache)

browser.cache.disk.enable = false
browser.cache.memory.enable = false
browser.cache.offline.enable = false

set

browser.cache.disk.smart_size.enabled

REDEMARRAGE

browser.cache.disk.enable

browser.cache.disk_cache_ssl
and
browser.cache.offline.enable to false

browser.cache.offline.capacity 0

browser.cache.disk.capacity 0

activate the entry browser.cache.memory.enable -> true

set the entry browser.cache.memory.capacity to -1 for automatic adjustment
Browser.cache.memory.capacity 0

browser.cache.disk.capacity 0

browser.cache.disk.content_type_media_limit

media.cache_size 2147483647

browser.privatebrowsing.forceMediaMemoryCache true

browser.cache.disk.enable - false
browser.cache.disk.smart_size.enabled - false
browser.cache.disk_cache_ssl - false
browser.cache.offline.enable - false

browser.cache.memory.enable - true (I believe this is true by default)
browser.cache.memory.capacity - 512000 (that's 500 MB, I actually have mine set to 1 GB)

browser.cache.disk.capacity = https://github.com/Floorp-Projects/Floorp/commit/8192000991800eed058a64fa69e3f3d6960d0908 # 8 GB cache on disk
browser.cache.disk.smart_size.enabled = false # disable adaptive cache size on disk
browser.cache.frecency_half_life_hours = 128 # lower cache sweep intervals
browser.cache.max_shutdown_io_lag = 16 # let the browser finish more io on shutdown
browser.cache.memory.capacity = 2097152 # fixed maximum 2 GB in memory cache
browser.cache.memory.max_entry_size = 327680 # maximum size of in memory cached objects

https://gist.github.com/RubenKelevra/fd66c2f856d703260ecdf0379c4f59db

browser.cache.disk.content_type_media_limit

A percentage limit for media content type in the disk cache. When some entries
+# need to be evicted and media is over the limit, it's evicted first.
+- name: browser.cache.disk.content_type_media_limit
https://hg.mozilla.org/releases/mozilla-release/rev/bbc2d5705a2b0647ea2c6aabd86b7a79df836b81

browser.cache.disk.enable = false
(désactive le cache disk)
browser.cache.disk.capacity = 0
(interdit le cache disk)
browser.cache.memory.enable = true
(active le cache de la ram, accélère Mozilla)
browser.cache.memory.capacity ou browser.cache.memory.max_entry_size = 20000 (Ram pour le cache)
browser.cache.offline.enable = false
(Désactive le cache offline)
browser.cache.offline.capacity = 0
(interdit le cache offline)
network.http.sendRefererHeader = 0
(n'informe pas le site de vos ancien site visité)
network.prefetch-next = false
(Ne stock rien dans le cache)
browser.cache.disk.max
browser.cache.disk.max_entry_size = 51200 // 50 MB

turn off [browser.cache.disk.smart_size.enabled] and [browser.cache.disk.enable],

If you increase [browser.cache.memory.max_entry_size] to 1048576

I set browser.cache.disk.capacity = 0 and my Win10 Firefox is much faster

browser.privatebrowsing.forceMediaMemoryCache set to true (and it works)

*** Buffer full video or make buffer bigger

https://hg.mozilla.org/mozilla-central/rev/b597ea8f9bb4

So what actually changed is that these values changed from:

Buffer full video or make buffer bigger

There is an easy fix for it just increase media.cache_readhead_limit
to 9999 and media.cache_resume_treshold also to 9999.
This was also puzzling me since firefox 54 would buffer
till the end of the video but firefox 55 wouldn't,
so I went trough the about:config and found those
two lines once I chagned their values from (60, 30)
to those above every single video I opened in firefox so far buffered till the end, you don't even need to restart the firefox just refresh the page for changes to take the effect. Hope this helped.

cache_readahead_limit: 999999 9999
cache_resume_threshold: 999999 9999

to

cache_readahead_limit: 60
cache_resume_threshold: 30

media.cache_readahead_limit
media.cache_readahead_limit.cellular

media.cache_resume_threshold
media.cache_resume_threshold.cellular

Increase the size of

browser.cache.disk.content_type_media_limit

media.cache_size 2147483647

Increase

browser.cache.disk.capacity

You can set media.mediasource.enabled to false.
If a site's video playback breaks, try to revert this option back
to the default, before anything else.
Set media.mediasource.enabled to false so it works on Youtube

media.preload.default

media.volume_scale

media.throttle-regardless-of-download-rate

media.throttle-factor

media.throttle-regardless-of-download-rate false

media.video-queue.default-size

media.wakelock_timeout

prevent video elements from preloading too much data
pref("media.preload.default", 1); // default to preload none
pref("media.preload.auto", 2); // preload metadata if preload=auto
pref("media.cache_size", 32768); // 32MB media cache

disable firefox view : browser.tabs.firefox-view false

browser.cache.disk.capacity = 8192000 # 8 GB cache on disk
browser.cache.disk.smart_size.enabled = false # disable adaptive cache size on disk
browser.cache.frecency_half_life_hours = 128 # lower cache sweep intervals
browser.cache.max_shutdown_io_lag = 16 # let the browser finish more io on shutdown
browser.cache.memory.capacity = 2097152 # fixed maximum 2 GB in memory cache
browser.cache.memory.max_entry_size = 327680 # maximum size of in memory cached objects

A few more speed improvements to add:

browser.sessionstore.interval 600000 #10min save for resume from crash

reader.parse-on-load.enabled false

network.dnsCacheEntries 4096

network.dnsCacheExpiration 900 #15 min

network.dnsCacheExpirationGracePeriod 900 #15min

network.ssl_tokens_cache_capacity 4096 #more TLS token caching (fast reconnects)

security.remote_settings.crlite_filters.enabled true #faster than OCSP & more private

security.pki.crlite_mode 2 #use crlite for revoked & not revoked results

browser.cache.disk.metadata_memory_limit 1024 #1024KB

browser.bookmarks.max_backups 2

Idea about session store !

On-demand prefs like browser.sessionstore.restore_on_demand are about reloading all tabs automatically or leave them in a pending state that requires to click the tab to load the page (useful in case there are hundreds of tabs to restore).
It will still restore all the tabs.

The only way to prevent restoring tabs is via clearing history via "Clear history when Firefox closes" to prevent Firefox from creating sessionstore.jsonlz4.
There is no (other) way to disable Session Restore.

Good question.
Instinctively I assume that browser.sessionstore.idleDelay (30 3 min by default) is the time from which the backup function returns to "inactive" mode, and browser.sessionstore.interval.idle (60 min by default) c is the backup interval in idle mode.
It remains to be seen whether this "idle" mode is detected by the absence of user interactions or by the absence of opening/closing of a tab.

https://forum.hardware.fr/hfr/WindowsSoftware/Software/firefox-browser-nightly-sujet_107551_1635.htm

You can also change the amount of info saved (it's even more efficient), set the value browser.sessionstore.privacy_level to 2

 browser.sessionstore.privacy_level

This disables the saving of the position in the page, cookies, POST data, and any data you have typed.
 
http://kb.mozillazine.org/Browser.sessionstore.privacy_level

on old versions you could disable it with the setting browser.sessionstore.enable (false)
But you can have the same effect with the settings browser.sessionstore.max_tabs_undo / browser.sessionstore.max_windows_undo (both set to 0):

    http://kb.mozillazine.org/Browser.sessionstore.enabled
    Mozilla Firefox 3.0 and below. Since Firefox 3.5 this preference is superseded with setting browser.sessionstore.max_tabs_undo and browser.sessionstore.max_windows_undo to 0.

https://www.wilderssecurity.com/threads/adjust-this-setting-before-firefox-wears-down-your-ssd-drive.391018/

We expect that, when the user is not in front of the computer, changes
are not critical and don't need to be saved as often. We now adopt the
following strategy:

- when the user has been away for (by default) 15 seconds, finish any
  pending collect/write, then increase the collect/write buffering
  delay to (by default) 1h

- when the user returns, reschedule any pending 1h collect/write as a
  (by default) 15 seconds collect/write, then proceed with (by
  default) 15 seconds collect/write delays.

https://hg.mozilla.org/releases/mozilla-release/rev/4d8192b5ac7e

https://github.com/The-OP/Fox/blob/master/prefs/prefs_1.js

How does the setting browser.sessionstore.cleanup.forget_closed_after in about:config work?

The setting determines when tabs and windows that were closed before will no longer be remembered. If a tab or window was closed 14 days ago, it cannot be restored anymore.

The cleanup only occurs once every 24 hours when the browser is idle. There is no special case for zero or negative values, it just cleans everything that was closed.

https://www.reddit.com/r/firefox/comments/qg5air/how_does_the_setting/

 Minimal interval between two save operations (in milliseconds).
*
* To save system resources, we generally do not save changes
immediately when
* a change is detected. Rather, we wait a little to see if this change is
* followed by other changes, in which case only the last write is
necessary.
* This delay is defined by "browser.sessionstore.interval".
*
* Furthermore, when the user is not actively using the computer, webpages
* may still perform changes that require (re)writing to sessionstore, e.g.
* updating Session Cookies or DOM Session Storage, or refreshing, etc. We
* expect that these changes are much less critical to the user and do not
* need to be saved as often. In such cases, we increase the delay to
* "browser.sessionstore.interval.idle".
*
* When the user returns to the computer, if a save is pending, we
reschedule
* it to happen soon, with "browser.sessionstore.interval".
*/

**Comment by surapunoyousei** [comment]
This requires a lot of exploration. Turning it on immediately by default is risky.

However, we are interested in speeding up the browser. I will give this some consideration.

However, settings that require memory size-specific changes seem difficult to match by default.

**Comment by LilyJone** [comment]
@surapunoyousei  Hello, author. In your browser, I see things that combine different modern elements. So I'd like to request the addition of a feature. This function is to put the mouse on the label, automatically switch Windows function. Cent Browser also has this feature. Long - term use to browse the web has a good comfort

https://github.com/LilyJone/OpenTools/releases/tag/Centbrowser—Priavcy—V2
This is my Centbrowser modification of the browser, combined with all my ideas, including browser convenience, understanding. Uncompress and you'll see everything.

About mouse placed on TAB to automatically switch Windows, code github：
https://github.com/luetage/vivaldi_modding/blob/master/activate-tab-on-hover.js

**Comment by Seb3thehacker** [comment]
> @surapunoyousei Hello, author. In your browser, I see things that combine different modern elements. So I'd like to request the addition of a feature. This function is to put the mouse on the label, automatically switch Windows function. Cent Browser also has this feature. Long - term use to browse the web has a good comfort
> 
> [https://github.com/LilyJone/OpenTools/releases/tag/Centbrowser—Priavcy—V2](https://github.com/LilyJone/OpenTools/releases/tag/Centbrowser%E2%80%94Priavcy%E2%80%94V2) This is my Centbrowser modification of the browser, combined with all my ideas, including browser convenience, understanding. Uncompress and you'll see everything.
> 
> About mouse placed on TAB to automatically switch Windows, code github： https://github.com/luetage/vivaldi_modding/blob/master/activate-tab-on-hover.js

This is really cool!

**Comment by surapunoyousei** [comment]
Floorp will have user.js configuration. fastfox has this feature.

close issue. thank you for your info.
