### ISSUE TITLE
[Bug]: Visual artifacts on the vertical tabbar

### ISSUE THREAD

**Issue by wealstarr** [Floorp-Projects/Floorp#1405]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Visual artifacts on the vertical tab bar. 

1. A some sort of horizontal bar appears at the bottom that shouldn't be there.
2. List item content margins are not centered
3. Scroll bar is way too thick for a collapsed tab bar.

### Reproduction Steps

1. Enable vertical tabs
2. collapse the tab bar

### Expected Behavior

1. The Horizontal border/line or whatever that is shouldn't be there. (see screenshots)
2. There should be an option to use "slim" scrollbar on vertical tab bar.
3. Listitem should be centered on the tab icon

### Actual Behavior

1. A some sort of horizontal bar appears at the bottom that shouldn't be there.
2. List item content margins are not centered
3. Scroll bar is way too thick for a collapsed tab bar.

### Screenshots

![Capture](https://github.com/user-attachments/assets/7b22777f-81a3-4a14-90d2-684732e47982)

![2](https://github.com/user-attachments/assets/f6cc80a6-7626-4636-96d1-46bb28755772)

### Browser Version

11.17.8 (64-bit)

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
Sorry, but Floorp only handles the front-end side of Firefox, so this problem is most likely not a Floorp issue.

I've tried those other forks, but they seem to be slower overall.

**Comment by wealstarr** [comment]
This issue is entirely related to Floorp's vertical tabs. Firefox 128 that Floorp latest is based on doesn't have vertical tabs.

**Comment by surapunoyousei** [comment]
Opps,,, I made mistake. I want to send this comment to the other issue...

**Comment by creeper-0910** [comment]
Perhaps this will be fixed in 11.17.9...

**Comment by surapunoyousei** [comment]
Foxed
