### ISSUE TITLE
[Bug]: touchpad scroll on gnome is way sensitive than other browsers

### ISSUE THREAD

**Issue by Coosminn** [Floorp-Projects/Floorp#1410]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Touchpad scroll speed is way sensitive in Floorp on GNOME than other browsers, including Firefox and Google Chrome.

### Reproduction Steps

1. Use floorp
2. Be annoyed of the sensitivity of the touchpad scroll

### Expected Behavior

Touchpad scrolling speed should be lower and/ or adjustable in the settings.

### Actual Behavior

Touchpad scroll way too fast for any type of normal use.

### Screenshots

https://github.com/user-attachments/assets/aeb5705b-22c0-4cf3-b9c8-36e5c4c56488

### Browser Version

Floorp 11.17.8 (Flathub)

### Operating System

Fedora 40 GNOME

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by surapunoyousei** [comment]
https://askubuntu.com/questions/1447009/control-scrolling-speed-in-webpages-in-firefox

**Comment by someone-aka-sum1** [comment]
@surapunoyousei Thanks for the hint, but could you please check the default value for `mousewheel.default.delta_multiplier_y`? For some reason it's 300 on the latest version for me, whereas Firefox has it at 100. For comparison, both Floorp and FF have 100 as the default `delta_multiplier_x`.

**Comment by catb0t** [comment]
> [@surapunoyousei](https://github.com/surapunoyousei) Thanks for the hint, but could you please check the default value for `mousewheel.default.delta_multiplier_y`? For some reason it's 300 on the latest version for me, whereas Firefox has it at 100. For comparison, both Floorp and FF have 100 as the default `delta_multiplier_x`.

Yeah, came here and found that's the issue from your comment so thanks. Not sure why Floorp has it 3x.
