### ISSUE TITLE
[Bug]: About Dialog の内容が Floorp に最適化されていない可能性がある

### ISSUE THREAD

**Issue by CutterKnife** [Floorp-Projects/Floorp#1411]
どこに書くべきか迷いましたが……
いわゆる「Floorp について」には `browser/browser/aboutDialog.ftl ` の内容が使用されていると思われますが、その内容がほぼ Firefox と同様になっているように見えます。

たとえば「プライバシーポリシー」をクリックすると、[こちら](https://www.mozilla.org/ja/privacy/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog)のページに遷移します。

<img width="842" alt="スクリーンショット 2024-09-03 20 05 21" src="https://github.com/user-attachments/assets/010112b1-a7da-4adb-b864-ee2351684c97">

もう少し調べて、自分にできそうな部分があれば PR を送ります！ (無理そうなら諦めます)

**Comment by CutterKnife** [comment]
お手数おかけします………！！！！！！！！

**Comment by surapunoyousei** [comment]
こちらこそ申し訳ない

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/e0e31d1b-cf1a-4e69-8952-295a2afc4435)

これでいいな
