### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HonoredShadow** [Floorp-Projects/Floorp#1412]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Here is a YouTube video of the problem:
https://youtu.be/4OpS3ntGJPM

If I click fullscreen or F11 I can't use the bookmark buttons I have made as the menu now slides away before I can click on them.  It used to be that I could click on them like the rest of the UI that slides away.  But not for me or my friend for about a month or so.

I can't check if Firefox does this as it does not support this sadly.  This is why I moved to Floorp.  For this feature.

### Reproduction Steps

1)  Press F11
2)  Try to click on any button shortcuts you have made on the bookmark toolbar
3)  You can't as the menu slides away.

### Expected Behavior

It used to be that the whole UI that slides away was all clickable including the bookmarks I made.  I used to have it drop down and just use the bookmarks.

### Actual Behavior

I hover near/over the bookmarks and they slide off screen with the rest of the UI.

As you can see in the video, you can force it so I can click on it by clicking on the web bar.  Then I am able to keep the bookmark bar there so I can now use it.  Then it works!

### Screenshots

![Screenshot 2024-09-03 133502](https://github.com/user-attachments/assets/bde7aa55-cb52-44ec-b669-7ce15e2bae69)
https://youtu.be/4OpS3ntGJPM

### Browser Version

11.18.0 64 bit

### Operating System

Windows 11 64 bit latest official.

### Additional Context

Happens all the time, every page.  I use only the themes that came with Floorp.

Thank you for a wonderful job.

**Comment by surapunoyousei** [comment]
If possible, could you try it in Firefox with Lepton installed?


https://GitHub.com/black7375/Firefox-UI-Fix

**Comment by surapunoyousei** [comment]
Download Lepton.zip as it is for ESR128. ESR version is for ESR115

**Comment by HonoredShadow** [comment]
I'm sorry I am unsure how to install this.   I looked on the page but I don't see how.  I have downloaded the correct zip.

**Comment by HonoredShadow** [comment]
I followed these manual instructions on a fresh install of Firefox and the same thing happens as in the video.  I can't click the bookmark buttons I have made but they do at least show now in F11 mode unlike default Firefox.

**Comment by surapunoyousei** [comment]
Floorp Are you saying that this is not a unique problem?

**Comment by HonoredShadow** [comment]
Yep.  I does seem that way.  I did not know about the tweak that was done to Floorp.

Thanks for your help though.

**Comment by surapunoyousei** [comment]
Thanks for the reply.

This issue should move to https://github.com/black7375/Firefox-UI-Fix . Please create new issue. 

Thanks
