### ISSUE TITLE
Need a custom pref for favicon api

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#142]
## Is your feature request related to a problem? Please describe.
There's an embarrassing problem peculiar to Chinese Mainland, we can not use Google's service directly, so If I enable the browser sidebar tool, It's take more 20 secends to start Floorp.

## Describe the solution you'd like
Please add a pref for changing the api, so that I can change it on about:config

## Describe alternatives you've considered
Or specify an accessible api for Simplified Chinese users, such as `https://favicon.yandex.net/favicon/v2/`

## Additional context
https://github.com/Floorp-Projects/Floorp/blob/31d8340bd18d578ca5dc5cd125477de1e78b0051/floorp/browser/base/content/browser-command.js#L221

**Comment by surapunoyousei** [comment]
I see. Does DuckDuckGo have no problem?

**Comment by benzBrake** [comment]
duckduckgo also not work
