### ISSUE TITLE
[Bug]: Load Windy.com cause high CPU temperature

### ISSUE THREAD

**Issue by winstonma** [Floorp-Projects/Floorp#1421]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I tried to open windy.com in Floorp and it causes high CPU usage.

I also tested Firefox ESR 128 and chrome and I didn't see the high CPU usage.

### Reproduction Steps

I ran the floorp in private mode and load windy.com, using the following command:

```
$ floorp -private-window https://www.windy.com
console.warn: "CSK Init Completed"
console.error: ({})
console.log: ({initialized:true})
console.log: false
console.log: "blob:null/e0cf2ba0-df3c-4a09-b47e-eebd572b27f2"
console.log: "blob:null/7b6d8052-d1b4-44f9-b691-e75d3892280e"
console.log: "blob:null/d57563ae-49d9-4147-9b90-f45086d7b2c4"
JavaScript error: undefined, line 0: Error: Invalid window ID: 1
JavaScript error: undefined, line 0: Error: An unexpected error occurred
JavaScript error: moz-extension://32c364a9-13c6-41f6-a76d-c6efd6915292/background.js, line 1: TypeError: t is undefined
JavaScript warning: , line 0: WebGL warning: texSubImage: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.
JavaScript warning: , line 0: WebGL warning: texSubImage: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
JavaScript error: https://www.windy.com/v/43.0.0.ind.7f94/index.js, line 1: Error: NetworkError when attempting to fetch resource.
JavaScript error: https://www.windy.com/v/43.0.0.ind.7f94/index.js, line 1: Error: NetworkError when attempting to fetch resource.
JavaScript error: https://www.windy.com/v/43.0.0.ind.7f94/index.js, line 1: Error: NetworkError when attempting to fetch resource.
JavaScript error: https://www.windy.com/v/43.0.0.ind.7f94/index.js, line 1: Error: NetworkError when attempting to fetch resource.
JavaScript error: https://www.windy.com/v/43.0.0.ind.7f94/index.js, line 1: Error: NetworkError when attempting to fetch resource.
JavaScript error: moz-extension://32c364a9-13c6-41f6-a76d-c6efd6915292/background.js, line 1: TypeError: t is undefined
JavaScript error: resource://gre/modules/ConduitsChild.sys.mjs, line 122: Error: sendRemoveListener on closed conduit tongwen@softcup.274877906964
```

### Expected Behavior

CPU temperature would go down after 1 minute of loading the website

### Actual Behavior

CPU temperature keeps on high CPU usage after 1 minute

### Screenshots

No

### Browser Version

11.18.0

### Operating System

Ubuntu 24.04

**Comment by surapunoyousei** [comment]
![image](https://github.com/user-attachments/assets/d2d68900-ab9f-4354-8374-846ba7fad328)

I cannot reproduce this issue.

**Comment by creeper-0910** [comment]
What Firefox extension is “moz-extension://32c364a9-13c6-41f6-a76d-c6efd6915292/background.js”?

**Comment by winstonma** [comment]
@creeper-0910 It's ublock origin. I also started safe mode (it remove ublock origin) and I saw high CPU usage too.

**Comment by winstonma** [comment]
I guess I can't reproduce the situation after the restart. Sorry for your time.

I would open if I find the problem again. Thank you very much.

**Comment by winstonma** [comment]
Just took the screenshot with the following configuration
1. Connect to external monitor
2. Show the task manager on the other monitor and keep windy.com on the front screen (When it is running in the background then it would not have high CPU usage)

![Screenshot from 2024-09-08 07-20-17](https://github.com/user-attachments/assets/3b51ce7c-d597-4bab-af7b-740b7d55df4e)

As long as windy.com is running as the top (thus it keeps drawing) then it would cause high CPU usage. I don't see this problem in Floorp Windows version and I don't see this problem in Firefox ESR / Chrome in Ubuntu 24.04 as well.

**Comment by knot2006** [comment]
It the same here for me, but instead of checking whole CPU usage you should monitor per core usage.

Opening windy.com in floorp maxes out one of my cores on 5900x
![image](https://github.com/user-attachments/assets/ea125a74-f699-420d-b8d0-d3636fb8d3fd)

While doing the same on Chrome makes use of ~4cores at about 20-30%
![image](https://github.com/user-attachments/assets/a70e2450-d517-4b29-a42f-39c4a1360972)

**Comment by surapunoyousei** [comment]
Comparison with Chrome is meaningless since the engines are different.

I do not intend to do anything to manipulate the engine so please understand that.

**Comment by winstonma** [comment]
I am not trying to compare the Floorp result against Chrome (as it is Firefox-based). I just Floorp should compare with Firefox.

But after a while I did the retest and it seems Firefox has high CPU consumption too. In this case I think I would close this issue.

**Comment by melroy89** [comment]
> But after a while I did the retest and it seems Firefox has high CPU consumption too. In this case I think I would close this issue.

Yea that might be correct. But in general this kind of high CPU usage is insane to me for any browser. I know Floorp is a fork of Firefox. But let's face it Floorp is the future, I hope it might come with CPU & memory improvements as well.
