### ISSUE TITLE
[Bug]: Second tab is misaligned when a tab is pinned in vertical tabs

### ISSUE THREAD

**Issue by nickycolky** [Floorp-Projects/Floorp#1424]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using vertical tab mode, pinning a tab will cause the favicon of the tab below to become misaligned. 

### Reproduction Steps

1. Use vertical tabs
2. Pin a tab
3. The tab below moves off-center to the right

### Expected Behavior

Pinning a tab should not affect the alignment of other tabs

### Actual Behavior

When a tab is pinned, the favicon of the tab below moves to the right

### Screenshots

![Screenshot from 2024-09-09 05-31-19](https://github.com/user-attachments/assets/d51bc080-0f36-4701-88c7-bc23bb611871)

### Browser Version

Floorp 11.18.1

### Operating System

Ubuntu 24.04 LTS

**Comment by surapunoyousei** [comment]
Duplicate

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1383
