### ISSUE TITLE
[Bug]: wrong color/accent maximize-restore down

### ISSUE THREAD

**Issue by denzveloper** [Floorp-Projects/Floorp#1426]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

restore-down window button on KDE Plasma 6 has wrong color (black color) when use dark theme (Breeze-dark). maybe is doesnt following theme what user use.

### Reproduction Steps

1. open floorp
2. maximize floorp
3. button has changed to color with white accent (black color)

### Expected Behavior

using white color icon, following the themes like firefox:
![Screenshot_20240910_105659](https://github.com/user-attachments/assets/a27a3660-22e9-4f36-8b3c-c945b68fca22)

### Actual Behavior

wrong color icon, they use black color, dont like other button
![Screenshot_20240910_105708](https://github.com/user-attachments/assets/2d96c0bc-629c-4c83-b6d3-453c53b896dc)

### Screenshots

firefox opensuse:
![Screenshot_20240910_105659](https://github.com/user-attachments/assets/a2a30acd-8e4a-4191-ad27-659ba35b0bda)

floorp flatpak:
![Screenshot_20240910_105708](https://github.com/user-attachments/assets/63b11a7e-a231-4588-873f-79c6ddb10ac3)

### Browser Version

11.18.1 (64-bit) - Flatpak

### Operating System

 openSUSE Tumbleweed 20240908 x86_64

**Comment by surapunoyousei** [comment]
Did you try tarball package version ?

**Comment by denzveloper** [comment]
ok i will try. but AUR version also have same issue like this.

**Comment by denzveloper** [comment]
ok, wait a second..

**Comment by denzveloper** [comment]
ok tarball version has no problem:

![image](https://github.com/user-attachments/assets/02803a15-cbf4-4930-bb13-e62957249257)
