### ISSUE TITLE
[Bug]: No Format button on leetcode.com

### ISSUE THREAD

**Issue by Rope-a-dope** [Floorp-Projects/Floorp#1434]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Other browser like Chrome/Brave/Edge has the format button to format code on leetcode.com, but missing on Floorp.

### Reproduction Steps

Just go to [leetcode](https://leetcode.com/problemset/), click any problem, you will see.

### Expected Behavior

It should has a format button like circled in the screenshot. Actually, FIrefox displays correctly with the format button.
![image](https://github.com/user-attachments/assets/af4a9fbf-c904-4676-9e54-56cc17bfef11)

### Actual Behavior

There is not such button on Floorp.

### Screenshots

![image](https://github.com/user-attachments/assets/1e0e2415-6944-4d05-9382-b1d38b3a79b4)

### Browser Version

v11.18.1

### Operating System

Fedora40 KDE

**Comment by surapunoyousei** [comment]
On My Microsoft Edge, there is same issue. Plz check your preferences or Send the website support team.

![image](https://github.com/user-attachments/assets/601bc749-910a-4467-9f71-8bfc20d272fb)

**Comment by breadbeforerice** [comment]
Is the label of no reproducibility correct?
