### ISSUE TITLE
[Bug]: Shortcuts Edit window hides behind the Shortcut Icons

### ISSUE THREAD

**Issue by danjmf** [Floorp-Projects/Floorp#1439]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Like the Bug I previously reported, the Edit window of the Shortcuts in the Landing Page sometimes hides behind the icons. The previous issue where this was happening all the time was kindly resolved, but now there remains a small issue with it, where the window still appears behind the icons. This happens when someone opens the edit window for one icon and then immediately clicks again on the three dots of another icon to open the edit window of that one. When this is done directly consecutively the new window shows behind the icons. 

### Reproduction Steps

1. Open the landing page where the shortcuts appear in floorp
2. Open the Edit Window of one Shortcut icon, by clicking the three dots on the top right corner of the icon. 
3. Open directly (without clicking somewhere else in between) the edit window of another shortcut 
4. the edit window will appear behind the shortcut icons 
5. when clicking outside somewhere on the screen and then opening the same shortcut edit window again it will appear before the icons.  

### Expected Behavior

That the next edit window appears also before the shortcut icons, even after I already clicked on a shortcut edit window. 

### Actual Behavior

The new edit window opens behind the shortcuts. 

### Screenshots

![Screenshot 2024-09-17 005834](https://github.com/user-attachments/assets/2ee5459f-0302-448e-b5c8-efc4623578c0)
![Screenshot 2024-09-17 005850](https://github.com/user-attachments/assets/cadd72db-3f43-494b-9eff-8456f31884b8)
![Screenshot 2024-09-17 005907](https://github.com/user-attachments/assets/bad30401-cc35-41d0-967a-d8299660ac48)

### Browser Version

11.18.1

### Operating System

Windows 11

**Comment by danjmf** [comment]
I know it is a minor issue, but unfortunately I don't have the skills to fix it myself :)

**Comment by creeper-0910** [comment]
Sorry, we tried to fix that before but did not because we anticipated that it would require complicated changes.
