### ISSUE TITLE
[Bug]: Sidebar padding missing, when using it on the left and using round corners on pages

### ISSUE THREAD

**Issue by ManDDDDD** [Floorp-Projects/Floorp#1449]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The icons on the sidebar are crambed to the left, when using the sidebar on the left of the screen and using round corners on the pages.

### Reproduction Steps

Make sure to uncheck this checkbox in order to switch the position of the sidebar to the left.
![grafik](https://github.com/user-attachments/assets/a46227fa-193f-4b94-8dcd-554b68b61fc3)

Also make sure the pages have rounded corners.
![grafik](https://github.com/user-attachments/assets/be547046-621a-45db-887c-d331e738f37a)

### Expected Behavior

The icons should have a padding on the outer site.
Sidebar on the right:
![grafik](https://github.com/user-attachments/assets/2962ab2a-a9fb-4a57-a94f-89f220490f2c)

### Actual Behavior

The sidebar on the left doesn't have this padding.
Sidebar on the left:
![grafik](https://github.com/user-attachments/assets/f1245eca-cac6-4721-a78a-0c871c974848)

### Screenshots

In this clip you can see the difference when switching between the modes.

https://github.com/user-attachments/assets/bf4fd223-db12-4dc5-8b16-9e82de25b959

### Browser Version

11.18.1

### Operating System

Windows 11 Pro (OS build 22631.4169)

**Comment by surapunoyousei** [comment]
Thank you for submitting the Issue.

We have decided not to add Padding outside of the sidebar for UX reasons.

We felt that the padding would be too much of a distraction and not worth it for the ease of clicking.

We hope you understand.

**Comment by ManDDDDD** [comment]
Well, this doesn't really make sense to me. Why does the right side have padding then? It looks unsymmetrical and kinda weird when it's only on one side.
Additionally, you could also still have a hotbox on the side with a padding on the left of the icons, even if the icons are more in the center after.
