### ISSUE TITLE
プライバシーに関する問題とその他改善点

### ISSUE THREAD

**Issue by Hackgets** [Floorp-Projects/Floorp#146]
日本のブラウザプロジェクトということで期待していたのですが、残念ながら以下の問題を指摘させていただきます。

- Firefoxからデータのインポートが出来ない。
- プライバシー保護を強調しているが、その割にプライバシーポリシーが緩く、利益のために個人情報を利用される懸念がある。
- 無効化出来ないシステムアドオンが多い。しかもそれらに大きな権限が与えられている。
- flatpakは一部のDEやディストロが推しているが、Linuxユーザーから広い支持を得ているとは言えない。

今のFloorpの設計思想に魅力を感じず、Firefoxを置き換える気にはなりませんでした。

**Comment by kr-tukimi** [comment]
@Hackgets さん、こんにちは
プライバシーポリシーはテンプレートをもとに作成したため、おっしゃる懸念を理解しております。
今後プライバシーポリシーの改定を検討しております。

また、GitHubのIssueタイトルはIssueの内容を具体的に示すようお願いします。

**Comment by code-raisan** [comment]
横から失礼します。
[プライバシーポリシー](https://docs.ablaze.one/privacy_policy)はFloorpがリリースされるよりも前に私が制作しました。このプライバシーポリシーはAblaze全体で使用しているものです。そのためFloorpに完全に沿っているとは言えない形になってしまっていました。ご指摘を受けFloorp専用のプライバシーポリシー制定等の検討をFloorpチームとしていきたいと思います。

**Comment by creeper-0910** [comment]
> 日本のブラウザプロジェクトということで期待していたのですが、残念ながら以下の問題を指摘させていただきます。
> 
> * Firefoxからデータのインポートが出来ない。
> * プライバシー保護を強調しているが、その割にプライバシーポリシーが緩く、利益のために個人情報を利用される懸念がある。
> * 無効化出来ないシステムアドオンが多い。しかもそれらに大きな権限が与えられている。
> * flatpakは一部のDEやディストロが推しているが、Linuxユーザーから広い支持を得ているとは言えない。
> 
> 今のFloorpの設計思想に魅力を感じず、Firefoxを置き換える気にはなりませんでした。

FirefoxからのデータインポートはFirefox Syncをご利用ください。

システムアドオンは無効化すると動作に影響を及ぼす場合がございます。

大きな権限とはどのようなものでしょうか?issueを立てる際は詳細に記述していただけると嬉しいです。

FloorpではPPAを利用したインストールをサポートしています。
https://ppa.ablaze.one

**Comment by Hackgets** [comment]
申し訳ありませんが、個別の問題に具体的な指摘をする気になれません。プライバシーの問題一つとってもそうですが、あなたがたの意識は、ブラウザという重要なアプリケーションを開発するには低すぎます。これ以上私が申し上げることはありません。

**Comment by creeper-0910** [comment]
> 申し訳ありませんが、個別の問題に具体的な指摘をする気になれません。プライバシーの問題一つとってもそうですが、あなたがたの意識は、ブラウザという重要なアプリケーションを開発するには低すぎます。これ以上私が申し上げることはありません。

issueは課題や問題の詳細を提示せず個人的な意見を述べ、closeするような場所ではありません。
次回issueを立てる際は課題や詳細な情報を提示していただきますよう、よろしくお願い致します。
