### ISSUE TITLE
[Bug]: 1Password integration macOS: TouchID does not work

### ISSUE THREAD

**Issue by notDavid** [Floorp-Projects/Floorp#1467]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hi there,

i've seen the other 3 issues about 1Password integration, which are all closed now;

Can you please clarify whether this is a known limitation, a bug, or an issue 1Password should fix?

Thank you!

### Reproduction Steps

1. Unlock 1Password on the Mac
2. Open Floorp, go to any website, and try to login with 1Password
3. You have to manually type in the Password (instead of TouchID, as in Firefox.)
4. (Logging in manually with a password into the 1Password extension works)
5. As soon as it locks again after the configured timeout, you have to enter the password again, as in step 3.

### Expected Behavior

It should be possible to unlock with TouchID

### Actual Behavior

TouchID / the integration with the 1Password app does not work.
(also see the error in the 1Password app screenshot.)

### Screenshots

<details>
  <summary>Click here to expand screenshots</summary>

![1password_1](https://github.com/user-attachments/assets/de192620-4c50-492c-8077-f5b2b9c4b8c6)

![1password_2](https://github.com/user-attachments/assets/6e97b6f8-0e74-46f1-ae3e-bb9afe1bd2ad)

![1password_3](https://github.com/user-attachments/assets/58e21872-d07e-4453-9d2a-b0629f00425f)

![extension_1](https://github.com/user-attachments/assets/55ffd364-286c-4801-8512-d075888c4803)

![extension_2](https://github.com/user-attachments/assets/2e48e967-b73a-493f-8583-04e50286ff07)

![extension_3](https://github.com/user-attachments/assets/2c9f289e-7686-4c69-8467-1dd5ee27dfea)

![extension_4](https://github.com/user-attachments/assets/36831b25-0e97-4248-ac84-14e1f2768931)
<img width="602" alt="extension_5" src="https://github.com/user-attachments/assets/ec79119d-ce84-4ece-bf46-2731030b72f5">

</details>

### Browser Version

11.19.0 (64-bit)

### Operating System

macOS Sequoia 15.0.1

**Comment by surapunoyousei** [comment]
Floorp doesn't support by 1Password
