### ISSUE TITLE
[Bug]: Changing language to Slovak does not work

### ISSUE THREAD

**Issue by dodog** [Floorp-Projects/Floorp#1479]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Changing the language to Slovak does not do anything. All menus remain in English. When I try other languages, they are applied correctly. 

### Reproduction Steps

1. Open Settings
2. Change language to Slovak

### Expected Behavior

Changing menu to Slovak language

### Actual Behavior

Nothing is changed. Everything stays in English.

### Screenshots

![screenshot-2024-10-16_23-16-29](https://github.com/user-attachments/assets/7dd7c560-5c07-41ec-929c-2c68b27a7190)

### Browser Version

11.19.1 (64-bit)

### Operating System

Linux Manjaro

**Comment by surapunoyousei** [comment]
Slovak is not officially supported.

**Comment by dodog** [comment]
@surapunoyousei, and can we make it officially supported? I tried to translate it on Crowdin, but I was unable to add or request Slovak language. What is needed for Slovak to work?
