### ISSUE TITLE
[Bug]: when the vertical tab feature is on, pinned tabs are deleted when floorp is closed and opened, the pinned tab is not fixed.

### ISSUE THREAD

**Issue by universish** [Floorp-Projects/Floorp#1491]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

when the vertical tab feature is on, pinned tabs are deleted when floorp is closed and opened, the pinned tab is not fixed.

### Reproduction Steps

floorp flathub

### Expected Behavior

-

### Actual Behavior

-

### Screenshots

-

### Browser Version

11.19.1

### Operating System

fedora 40

**Comment by surapunoyousei** [comment]
Vertical tabs will be removed.

This issue is closed.

**Comment by surapunoyousei** [comment]
Instead, you can use vertical tabs implemented by Mozilla
