### ISSUE TITLE
[Bug]: There is no information in the README about how to install, run or compile the .mar and .tar.bz2 versions.

### ISSUE THREAD

**Issue by universish** [Floorp-Projects/Floorp#1495]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

There is no information in the README about how to install, run or compile the .mar and .tar.bz2 versions. There is also no information about required dependencies and packages that need to be installed. 
The README document has information on how to run the .mar version. There is also no information about required dependencies and packages that need to be installed.
There is also no information about how to compile Floorp-11.19.1.linux-x86_64.tar.bz2. There is also no information about required dependencies and packages that need to be installed.
How do I set it up, how do I compile it? How do I make it work? Please help me. I am not a software developer, coder, program developer. I am an ordinary fedora user.

### Reproduction Steps

-

### Expected Behavior

Add missing information to README document

### Actual Behavior

no

### Screenshots

-

### Browser Version

11.19.1

### Operating System

fedora 40

**Comment by surapunoyousei** [comment]
Please do not open  a build issue.
