### ISSUE TITLE
[Bug]: Old versions (=< Floorp 11.16) not persisting under MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by dajare** [Floorp-Projects/Floorp#1505]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

As reported in  #1348 old versions of Floorp will not run under MacOS 10.14.6 Mojave. 

### Reproduction Steps

1. Install Floorp =< 11.16 - this is the version that last supported Mojave according to [this bug comment](https://github.com/Floorp-Projects/Floorp/issues/1348#issuecomment-2295082817).
2. Run Floorp. 🎉 It works! Browse! Enjoy! Its icon looks like this:  
<img width="119" alt="floorp-yes" src="https://github.com/user-attachments/assets/cf9fc1b2-fd3f-4822-9e83-335eefe134bc">   

4. Close Floorp.
5. Run Floorp again. Only ... it will not run. And now the icon has a "will not run" sign, and this message:   
<img width="437" alt="floorp-no" src="https://github.com/user-attachments/assets/ffd84d97-3d6b-4aa3-b8a7-d07201f3a523">

### Expected Behavior

I expect Floorp to keep working after closing, and re-opening.

### Actual Behavior

Floorp refuses to run again after the first-run; see issues in "steps" above.

### Screenshots

n/a - see above

### Browser Version

I have tried Floorp versions: 11.16, 11.15, 11.14.1, and 11.14.

### Operating System

MacOS 10.14.6 Mojave

### Additional Context

- As noted above, I have tried four "older" (pre-11.17) versions of Floorp; all have the same behaviour.
- **CONFIRMED** : Firefox ESR 115.17.0esr runs **as expected** with no issues.
- I have installed NO ADDONS, EXTENSIONS, etc. This is as "bare-bones" Floorp as is possible, fresh from install.
- I use some *crucial, must-have* work applications that require 32-bit libraries, so this early-2015 MacBook is stuck on Mojave. I had hoped an old-Floorp version could be my go-to browser, given its fine reputation and feature set.

**Comment by surapunoyousei** [comment]
Floorp is now ESR128 based. this is the reason

**Comment by dajare** [comment]
@surapunoyousei Please **read through** the issue before closing. I KNOW that `Floorp is now ESR128 based`. **I have referenced versions that are ESR115 based.** 

The issue is NOT reproducible in ESR115; it is, then, I assume, *some* check that Floorp is making *that it should not make*. PLEASE RE-OPEN!

**Comment by surapunoyousei** [comment]
I tried it on a virtual machine and it seems to work fine.

Please make sure the binaries are correct.
