### ISSUE TITLE
[Bug]: spotify sound on web doesn't play

### ISSUE THREAD

**Issue by yutayu** [Floorp-Projects/Floorp#1509]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

spotify sound on web doesn't play .

### Reproduction Steps

1.go to https://open.spotify.com/show/6x2YlRAWIu7npx9czp2G36 or other playlist.
2.click play button.

### Expected Behavior

It sounds.

### Actual Behavior

No play.

### Screenshots

no

### Browser Version

11.20.0 (64-bit)

### Operating System

raspberry pi os 64bit.

### Additional Context

日本語でもいいです。

**Comment by surapunoyousei** [comment]
https://docs.floorp.app/docs/issue-tracker/drm/

**Comment by yutayu** [comment]
arigatou
