### ISSUE TITLE
Webtorrent

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#151]
Hello, i discocer this wonderful projet of @ThaUnknown : webtorrent-player which is "WebTorrentPlayer is a high performance player module for your next WebTorrent based project, it works around all the gotchas with WebTorrent when working with any sort of video files. It also fully supports streaming in all it's features.

General motivation is to get rid of all duplicate RAM usage and reduce CPU usage, provide better/working alternatives for existing WebTorrent functionality, and provide any features you'd see in a modern video player, ex: YouTube's."

https://github.com/ThaUnknown/webtorrent-player

but there is some problem with Firefox : " is bad. I mean, it's good as a browser, but it clearly doesn't want to support webapps, so a lot of firefox functionality is limited, for example it only allows IDB files up to 2.14GB meaing you will end up using a lot more RAM, doesn't support threaded canvas rendering etc....."

so may be the awesome Mr @surapunoyousei could make some modifications and enhancements to firefox to bypass these technical limitations....Thank you !

**Comment by ThaUnknown** [comment]
idk why you pinged me

wt-player is bad, its the first video player module i've ever made, and while it works mostly okay, its really inefficient about how it does what its meant to do, and its archived for that exact reason, it also uses quite an old build of webtorrent and i've gotten far enough in by development experience where i re-wrote a fuckload of webtorrent which is coming soon in v2, where a lot of the probles wt-player fixes simply dont exist

that said the lastest ver of webtorrent supports up to 6GB of storage, which is more than the 2GB but it likely wont get any better than that, ofc on safari/chrome that limit doest exist

**Comment by typeling1578** [comment]
Unfortunately that project seems to have been abandoned.
Also, tampering with the rendering engine is a huge security risk. So we won't be working on them.
