### ISSUE TITLE
`#sidebar-splitter2` is passing though last frame buffer contents

### ISSUE THREAD

**Issue by trickypr** [Floorp-Projects/Floorp#152]
## Describe the bug
The drag element to left of the sidebar passes through the frame buffer contents

## To Reproduce
1. Open bookmarks sidebar
2. Observe splitter

## Expected behavior
This should be pained over by the `-moz-Dialog` color every frame

## Screenshots
![image](https://user-images.githubusercontent.com/23250792/205433315-5d72fc50-b4b3-4f42-aab8-6d7295258e11.png)
Note: My screenshot program forces the frame buffer to blank, so it appears black. 

## Desktop (please complete the following information):
 - OS: Gnome 43
 - Floorp Version: 10.7.0 (Via flatpak)

**Comment by typeling1578** [comment]
Thanks for the bug report!
