### ISSUE TITLE
[Bug]: Clearkey Plugin Crashed

### ISSUE THREAD

**Issue by RVSmooth** [Floorp-Projects/Floorp#1527]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Whenever I play a video in the website ```pw.live``` there occurs an error named ```Clearkey plugin crashed``` and the video stops. This occurs in the AUR version of the floorp i.e, the native application but does not occur in the flatpak edition. 

### Reproduction Steps

1. Visit pw.live
2. Login
3. play any video (in a paid batch)

### Expected Behavior

The video should play without errors

### Actual Behavior

It just stops

### Screenshots

https://github.com/user-attachments/assets/789fd5fc-5cb9-4635-ae6c-71a79c8b5f00

```
Missing chrome or resource URL: chrome://floorp/skin/designs/lepton/edit-active.svg
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/stl_vector.h:1130: reference std::vector<unsigned char>::operator[](size_type) [_Tp = unsigned char, _Alloc = std::allocator<unsigned char>]: Assertion '__n < this->size()' failed.
Redirecting call to abort() to mozalloc_abort

[Parent 22761, IPC I/O Parent] WARNING: process 23111 exited on signal 11: file /home/builder/build/src/Floorp/ipc/chromium/src/base/process_util_posix.cc:335
[Child 22966, MediaDecoderStateMachine #1] WARNING: Decoder=70b3ae75ca00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - void mozilla::EMEDecryptor::Decrypted(const DecryptResult &): decrypted.mStatus=3: file /home/builder/build/src/Floorp/dom/media/MediaDecoderStateMachineBase.cpp:167
[Child 22966, MediaDecoderStateMachine #1] WARNING: Decoder=70b3ae75ca00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - void mozilla::EMEDecryptor::Decrypted(const DecryptResult &): decrypted.mStatus=3: file /home/builder/build/src/Floorp/dom/media/MediaDecoderStateMachineBase.cpp:167
[Child 22966, MediaDecoderStateMachine #1] WARNING: Decoder=70b3ae75ca00 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - void mozilla::EMEDecryptor::Decrypted(const DecryptResult &): decrypted.mStatus=3: file /home/builder/build/src/Floorp/dom/media/MediaDecoderStateMachineBase.cpp:167
```

### Browser Version

ESR 128

### Operating System

Arch Linux

### Additional Context

This is a common issue across firefox and its forks on distros like archlinux, fedora (have not checked in ubuntu or debian distros tho). 

This perhaps could help: https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/issues/12

This issue does not occur in firefox forks namely waterfox, mercury-browser as much as I have tested.

**Comment by typeling1578** [comment]
> This is a common issue across firefox and its forks on distros like archlinux, fedora (have not checked in ubuntu or debian distros tho).

In other words, it is an upstream bug, not a Floorp bug.

**Comment by RVSmooth** [comment]
> > This is a common issue across firefox and its forks on distros like archlinux, fedora (have not checked in ubuntu or debian distros tho).
> 
> In other words, it is an upstream bug, not a Floorp bug.

this does not exist in opensuse tho
