### ISSUE TITLE
[Bug]: Floorp DEB package depends on `libgdk-pixbuf2.0-0` instead of `libgdk-pixbuf-2.0-0`

### ISSUE THREAD

**Issue by GlowingScrewdriver** [Floorp-Projects/Floorp#1535]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The `floorp` package from the [Floorp PPA](https://ppa.floorp.app/) depends on `libgdk-pixbuf2.0-0`, which is marked as a transitional package and in turn depends on `libgdk-pixbuf-2.0-0` As a consequence, Floorp cannot be installed on the Debian testing release, since `libgdk-pixbuf2.0-0` is not available on the Debian testing repository.

You may find the description for `libgdk-pixbuf2.0-0` [here](https://packages.debian.org/sid/libgdk-pixbuf2.0-0). It states that the package is transitional, and that packages that need the library should instead depend on `libgdk-pixbuf-2.0-0`.  
Additionally, you can see that the [Firefox Debian package](https://packages.debian.org/trixie/firefox-esr) depends on `libgdk-pixbuf-2.0-0`.

I've been running Floorp from the tarball release, and I can confirm that Floorp works fine if I install `libgdk-pixbuf-2.0-0`

_NOTE: The difference between the two package names here is that the name of the transitional package, which Floorp currently depends on, is missing a single hyphen:_
```
libgdk-pixbuf-2.0-0
             ^
```

### Reproduction Steps

1. Install Debian Testing (Debian 13 "Trixe" at the time of writing)
2. Add the [Floorp PPA](https://ppa.floorp.app) to your system
3. `apt-get install floorp`

### Expected Behavior

Floorp gets installed normally

### Actual Behavior

APT is unable to resolve dependencies for Floorp

### Screenshots

```
$ sudo apt-get install floorp
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 floorp : Depends: libgdk-pixbuf2.0-0 (>= 2.22.0) but it is not installable
Error: Unable to correct problems, you have held broken packages.
```
```
$ apt show libgdk-pixbuf2.0-0
Package: libgdk-pixbuf2.0-0
State: not a real package (virtual)
Notice: Can't select candidate version from package libgdk-pixbuf2.0-0 as it has no candidate
Notice: Can't select versions from package 'libgdk-pixbuf2.0-0' as it is purely virtual
Notice: No packages found
```

### Browser Version

11.21.0

### Operating System

Debian Testing

**Comment by GlowingScrewdriver** [comment]
I just wanted to report this here, and have a discussion if needed, before attempting to fix.

If I understand correctly, the dependencies are hardcoded in your [linux x86_64 deb(-ppa) pack](https://github.com/Floorp-Projects/Floorp/blob/ddef7217ee9c5e914f32d55632cbb828baa212e8/.github/workflows/linux-x64-deb.yml#L69) GitHub workflow. Is this where I should make the change?

**Comment by typeling1578** [comment]
You're right, the linux x86_64 deb (-ppa) pack GitHub workflow needs to be changed.
