### ISSUE TITLE
[Bug]: Youtube dark mode comments are in Black Text

### ISSUE THREAD

**Issue by molitar** [Floorp-Projects/Floorp#1540]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Tested in Google works fine but in Floorp the text is all Black for comments but normal in search box

### Reproduction Steps

Go to Youtube click on any video to watch and than type in comment field text is invisible as it is remaining Black. 

### Expected Behavior

Text should display in White

### Actual Behavior

Text is black and unreadable

### Screenshots

![image](https://github.com/user-attachments/assets/f30ae03e-0f9d-40ee-af65-986a46df5492)

### Browser Version

11.21.0

### Operating System

Windows 10

**Comment by andyg2** [comment]
This is happening for a lot of people. I 'fixed' it with uBlock Origin - add a filter under My Filters

```
youtube.com###labelAndInputContainer #contenteditable-root:style( color: white !important; )
```

![image](https://github.com/user-attachments/assets/85d71e2a-c75e-466f-b9bd-9f664657be2e)

**Comment by molitar** [comment]
OK this is a bug but now it's affecting other browsers so now it's believed to be on Youtube it slowly started to affect other browsers like Chrome and Firefox also.

**Comment by typeling1578** [comment]
Since this is a bug on YouTube's side, I will close the issue.
