### ISSUE TITLE
[Bug]: Floorp not opening links from external programs on Linux

### ISSUE THREAD

**Issue by whoop-t** [Floorp-Projects/Floorp#1549]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When clicking/opening a link through an external program like Discord/Neovim/Vim/etc Floorp will open a new tab/window but will not go to the link, just start on the startup page.

I have tested on MacOS and it works correctly
I've also tested Chrome/Firefox on PopOS and they work as well

### Reproduction Steps

1. Go to program like Discord or Neovim
2. Find a link
3. Click/Open link

### Expected Behavior

Take user to page/link

### Actual Behavior

Opens tabs/window and stays on new tab page

### Screenshots

[Screencast from 12-21-2024 05:02:37 PM.webm](https://github.com/user-attachments/assets/7abbb840-5c87-4fc2-a3c7-160b73783cf7)

### Browser Version

Version 11.21.0 (64-bit) | Firefox: 128.5.0

### Operating System

PopOs

**Comment by typeling1578** [comment]
ppa.floorp.app (ppa.ablaze.one) or flatpak?

**Comment by whoop-t** [comment]
@typeling1578 downloaded tar.bz2 and extracted to install on popos

**Comment by typeling1578** [comment]
In that case, the user needs to manually create a .desktop file.

**Comment by whoop-t** [comment]
@typeling1578 I have a .desktop file

The issue is clicking links don't go to the actual link

**Comment by typeling1578** [comment]
If the Exec entry is incorrect, this problem occurs.

**Comment by whoop-t** [comment]
Im point the exec straight to where I extracted the tar. Is this exec below not correct?

```
[Desktop Entry]
Name=Floorp
Exec=/opt/floorp/floorp
Comment=Firefox based browser
Icon=/opt/floorp/browser/chrome/icons/default/default128.png
Type=Application
Categories=Network;WebBrowser;
```

**Comment by typeling1578** [comment]
It should be written like this
```
Exec=/opt/floorp/floorp %u
```

The `%u` is required at the end.

**Comment by whoop-t** [comment]
Ah yup, that fixed it

Sorry for the noise and thanks for the help!
