### ISSUE TITLE
Follow-up On TST Hiding Fitment

### ISSUE THREAD

**Issue by TooSpooky** [Floorp-Projects/Floorp#155]
Hello,

Just a follow-up to what I think is a fitment issue with the hiding TST option. 

When you have an added scroll bar stuff starts to get even more cropped off, might look a little nicer if it's extended a few pixels to the right so it's not as cut-off.

<img width="46" alt="floorp_b6z23qCoLv" src="https://user-images.githubusercontent.com/21211292/206959550-cc525552-ec13-477e-abc8-d5e29505cb5a.png">
<img width="48" alt="floorp_O3F8Cg6Mqq" src="https://user-images.githubusercontent.com/21211292/206968725-5157750e-cfaf-4051-a345-a2fada7c6b7a.png">

Thanks again! Been using and enjoying floorp and the newer additions such as the status bar.

**Comment by typeling1578** [comment]
Hmmm... There is a technical problem with this that is difficult to fix.
This is because the width of scrollbars varies depending on the environment.

**Comment by TooSpooky** [comment]
Interesting.

Have you considered in the future making a native sidetab implementation by chance? In that case I don't believe a visible scrollbar is necessarily even required and can be represented differently or with a much smaller bar. Along with keeping tab "groups" more visually in-line with other tabs if they're included. 

Or with the current TST implimentation is it possible to hide to scrollbar entirely until it's unshrunk by mouse over? 
Similar to this firefox CSS for another sidetab extension


![librewolf_JeXvteib1F](https://user-images.githubusercontent.com/21211292/207450413-646ea805-7101-4bb9-9450-bc1cdc19c91d.gif)

Thanks for the reply! Hopefully in the future something can be come up with.

**Comment by surapunoyousei** [comment]
We will replace TST to native verticaltab at v11.0.0. Close issue.
