### ISSUE TITLE
[Bug]: Cannot get a userChrome.css theme working

### ISSUE THREAD

**Issue by scrubborn** [Floorp-Projects/Floorp#1550]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The following theme -  
  
https://gitgud.io/wackyideas/aero-userchrome  
  
Will not apply no matter what I do, when the same steps work on firefox. I originally noticed this on Firedragon but was able to reproduce on current version Floorp. 

### Reproduction Steps

1. Create a new profile
2. Add my chrome folder from the gitgud rep into the proper directory
3. Ensure that “toolkit.legacyUserProfileCustomizations.stylesheets” was set to true
4. Edit the userChrome.css per the theme instructions
`@import url("Echelon/userChrome.css");
@import url("Aero/Echelon.css");`  
5. Relaunch Floorp

### Expected Behavior

The theme should activate.

### Actual Behavior

No theme changes occur.

### Screenshots

![image](https://github.com/user-attachments/assets/8ec5e4c7-945e-4fae-aff7-d508966985a0)

### Browser Version

v11.21.0

### Operating System

Garuda Linux

**Comment by black-ish** [comment]
You can remove the @import lines and just put the .css files into the CSS folder.
They should load, without needing any @import lines in the userchrome.css.

**Comment by scrubborn** [comment]
That seems to have gotten me further, though I am having rendering issues with this theme. I suppose at that point I can try and ask the maintainer of the theme, as floorp is atleast attempting to load the CSS now. Thank you.
