### ISSUE TITLE
Add Firefox view to Floorp, especially the tab pickup

### ISSUE THREAD

**Issue by divaaaries** [Floorp-Projects/Floorp#164]
I'm usually jumping from Firefox mobile to desktop, and being able to open my last tab from other device without opening sync menu is the reason why I'm still using Firefox. It's very convenient

Also, thanks for keeping sync feature in Floorp and removing useless Firefox Pocket. 

Anyway, Firefox view is like this:
![Screenshot_20221228_103130](https://user-images.githubusercontent.com/105185444/209753194-df57cf72-6327-4210-939c-af6b364c3bf9.png)

**Comment by surapunoyousei** [comment]
This is not impossible and is scheduled.

However, it takes time because you have to wait for ESR115.

**Comment by surapunoyousei** [comment]
Floorp 11.0.0 is available soon. v11 has Floorp View as Firefox View. Close issue.
