### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by BarbzYHOOL** [Floorp-Projects/Floorp#167]
What is Frea Search? I don't speak japanese
How fast is it compared to Firefox?

**Comment by typeling1578** [comment]
A custom instance of [SearXNG](https://github.com/searxng/searxng) aimed at being a search engine that only shows reliable search results.
In terms of speed, the nature of SearXNG makes it inferior to general search engines such as Google.

**Comment by BarbzYHOOL** [comment]
what about the speed of Floorp vs firefox?

**Comment by regularenthropy** [comment]
> what about the speed of Floorp vs firefox?

In the 1.7.0 release, Floorp speed has been increased compared to Firefox.
![image](https://user-images.githubusercontent.com/89523758/211268969-9fa49ea4-ab7e-4561-902b-692fe8310167.png)

**Comment by surapunoyousei** [comment]
This value generated by Jet Stream(Browser benchmark)

Floorp enabled PGO by default. PGO offers more good Performance for Floorp.

BTW, Waterfox doesn't enable this build option.

**Comment by surapunoyousei** [comment]
If U have another question, plz reply.

**Comment by BarbzYHOOL** [comment]
great project, i recommended it to some people already

When I tested it in february I was hesitant, and now it has evolved even more and I like it.
