### ISSUE TITLE
Session store idle delay

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#170]
Hello @surapunoyousei and all Floorp team, please on my side I tried to understand how session store works and I understood that I have to increase the interval of "browser.sessionstore.interval"
and "browser.sessionstore.interval.idle" to reduce disk activity but there are other more complicated settings that I can't figure out so I ask for your help and generosity to understand these settings since you are an experienced expert in the complex internal settings of firefox :)

I can't understand this setting : browser.sessionstore.idleDelay, should I increase or decrease the the value of this setting  to avoid wear and tear on my old HDD?

and should I increase or decrease the values of these parameters to disable the session store please?

browser.sessionstore.cleanup.forget_closed_after

and

browser.sessionstore.upgradeBackup.maxUpgradeBackups

maybe these documents can help, I searched and read but didn't quite understand:

"/*
  * Minimal interval between two save operations (in milliseconds).
  *
  * To save system resources, we generally do not save changes immediately when
  * a change is detected. Rather, we wait a little to see if this change is
  * followed by other changes, in which case only the last write is necessary.
  * This delay is defined by "browser.sessionstore.interval".
  *
  * Furthermore, when the user is not actively using the computer, webpages
  * may still perform changes that require (re)writing to sessionstore, e.g.
  * updating Session Cookies or DOM Session Storage, or refreshing, etc. We
  * expect that these changes are much less critical to the user and do not
  * need to be saved as often. In such cases, we increase the delay to
  * "browser.sessionstore.interval.idle".
  *
  * When the user returns to the computer, if a save is pending, we reschedule
  * it to happen soon, with "browser.sessionstore.interval".
  */
const PREF_INTERVAL_ACTIVE = "browser.sessionstore.interval";
const PREF_INTERVAL_IDLE = "browser.sessionstore.interval.idle";
const PREF_IDLE_DELAY = "browser.sessionstore.idleDelay";"

":::browser/components/sessionstore/SessionSaver.jsm:344
(Diff revision 2)
> +XPCOMUtils.defineLazyPreferenceGetter(SessionSaverInternal, "_intervalWhileIdle", PREF_INTERVAL_IDLE,
> + 3600000 /* 1h */);
> +
> +
> +XPCOMUtils.defineLazyPreferenceGetter(SessionSaverInternal, "_idleDelay", PREF_IDLE_DELAY,
> + 300000 /* 5 minutes */,

Note that due to bug 973591 we may get "spurious" active events between 2 to 5 minutes from when idle started. So the shorter the delay, the better is. I'd suggest to go for 3 minutes, that is a good compromise between not-too-short and may-never-fire."

https://git.progress-linux.org/packages/fuchur/firefox-esr/tree/browser/components/sessionstore/SessionSaver.jsm?h=upstream/78.6.1esr&id=3c992c5173d90c76b942a4c2cbe4db3833cd57c8

https://bugzilla.mozilla.org/show_bug.cgi?id=1305950

https://bugzilla.mozilla.org/show_bug.cgi?id=973591

https://bugzilla.mozilla.org/show_bug.cgi?id=1304389

**Comment by trimechee** [comment]
@surapunoyousei i find this in french forum, i translate, do you think it is right please ? 


"Good question.
Instinctively I assume that browser.sessionstore.idleDelay ( 3 min by default) is the time from which the backup function returns to "inactive" mode, and browser.sessionstore.interval.idle (60 min by default) it is the backup interval in idle mode.
It remains to be seen whether this "idle" mode is detected by the absence of user interactions or by the absence of opening/closing of a tab."

https://forum.hardware.fr/hfr/WindowsSoftware/Logiciels/firefox-browser-nightly-sujet_107551_1635.htm

**Comment by typeling1578** [comment]
Sorry, this is not the place to ask questions about Firefox, please use [Mozilla Support](https://support.mozilla.org/products/firefox), etc.

**Comment by trimechee** [comment]
@typeling1578 it also concerns Floorp browser, I spoke about it to a developer of Floorp browser and he promised me that he will try to make an option to reduce the session store which consumes a lot of data, so I propose ideas and while waiting for this option to be implemented, I am talking to @surapunoyousei  /

 @typeling1578  you said "I am a high school student in Japan. I mainly do add-on development and Firefox-fork browser development." so you develop a browser based on firefox, firefox in 2016 consumes a lot of data so floorp can be affected by this problem, i have old HDD so it affects me 

https://github.com/Floorp-Projects/Floorp/issues/128
![bftPLGy](https://user-images.githubusercontent.com/76402212/211577200-d075b486-b8d4-4254-9998-56604eb63d49.png)

**Comment by trimechee** [comment]
@typeling1578 https://github.com/Floorp-Projects/Floorp/issues/128#issuecomment-1319448482

**Comment by trimechee** [comment]
Great, thank you :)

**Comment by trimechee** [comment]
AlhamdoulilAllah i finally find the right official explanation, it was hard but i find finally the explanation , may be it can help, i think i will set it to 0 ton completely disable it : 

"Time (ms) before we assume that the user is idle and that we don't need to
// collect/save the session quite as often.
pref("browser.sessionstore.idleDelay", 180000); // 3 minutes"

https://searchfox.org/mozilla-release/source/browser/app/profile/firefox.js#1102




"I do realize there are two other settings:
"browser.sessionstore.idleDelay" and "browser.sessionstore.interval.idle".
If I read correctly, it means this: When the user is using Firefox, autosave every 15 seconds. When Firefox is left alone for 180 seconds (3 minutes), enter idle mode, autosave every hour instead."

https://www.reddit.com/r/firefox/comments/sdkrwv/comment/hufbhsa/

https://wiki.mozilla.org/Firefox/session_restore
