### ISSUE TITLE
cannot install floorp-10.8.0.deb without curl

### ISSUE THREAD

**Issue by sarukiti** [Floorp-Projects/Floorp#171]
## Describe the bug
I cannot install floorp-10.8.0.deb without curl.
I recommend to you include curl to dependency.

## To Reproduce
1. purge curl
2. sudo apt install ./floorp-10.8.0.deb

## Expected behavior
you can reproduce this when you try to install Ubuntu 22.04 immediately after installing it.

## Screenshots
![image](https://user-images.githubusercontent.com/47556340/211728673-9394320c-34e0-419a-9b7a-527d3c5aee92.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 22.04.1
 - Floorp Version: 10.8.0

**Comment by sarukiti** [comment]
訂正：インストール自体はできているようですが、エラーが出るのが気持ち悪いですね

**Comment by creeper-0910** [comment]
修正しました、ご報告ありがとうございました！
