### ISSUE TITLE
Gui languages

### ISSUE THREAD

**Issue by jipion** [Floorp-Projects/Floorp#178]
Hello

Most of the Western languages except English are only partially displayed in menus (just pop-ups, dialogs, tabs). 

![fl-french](https://user-images.githubusercontent.com/123224495/213843959-787ff6a1-3307-4902-a00e-d5f921f069f5.png)
![fl-ru](https://user-images.githubusercontent.com/123224495/213843965-3a1d5b47-13d9-4cb0-9c06-c7d59e9484a1.png)

**Comment by jipion** [comment]
Last version without that issue was 10.6.0

![fl-fr2](https://user-images.githubusercontent.com/123224495/213907766-93ee2a97-43bb-416a-95e2-bdf55ee4a62b.png)

**Comment by typeling1578** [comment]
This issue will be fixed in the next version.
Thank you for the bug report!
