### ISSUE TITLE
mp4動画を再生するコーデックを依存関係に含めてほしい

### ISSUE THREAD

**Issue by sarukiti** [Floorp-Projects/Floorp#183]
## Is your feature request related to a problem? Please describe.
mp4配信されている動画を閲覧できないです

## Describe the solution you'd like
Ubuntuのdebパッケージの依存関係に`ubuntu-restricted-extras`を含めてほしいです

## Describe alternatives you've considered
おそらくこのメタパッケージの中に各種動画再生コーデックがまとめられているのでしょうが、どれが必要なパッケージなのか調べるのは面倒でした(え

## Additional context
パッケージを追加インストールしないとyoutubeの生放送やmp4配信されている各種動画サービス(ニコニコ動画等)を閲覧できないのはなかなか不便な仕様ではないでしょうか……？

**Comment by creeper-0910** [comment]
ubuntu-restricted-extrasは、法的または著作権上の理由で含まれていないパッケージを含んでおり、依存関係として追加すると様々な問題が起こることが予想されます。
また、Ubuntu系のディストリビューションはインストール時にメディアコーデックのインストールにチェックを入れてインストールすることでこの問題は防げる事から今回は対応しない事としました。
