### ISSUE TITLE
user.jsで一部の設定が効かない

### ISSUE THREAD

**Issue by lunae-f** [Floorp-Projects/Floorp#189]
## Describe the bug
user.jsで`general.useragent.override`(ユーザーエージェントを任意のものに変更する設定)を変更しても適用されない

## To Reproduce
1. プロファイルフォルダにuser.jsを作成する。
2. 内容は、
`user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41");`
に編集して保存。
3. Floorpを再起動する。

## Expected behavior
オリジナルのFirefoxではUAがMS-Edgeのもの(`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41`)に変更された。

## Screenshots
null

## Desktop (please complete the following information):
![image](https://user-images.githubusercontent.com/62279412/218260208-42abdabf-256d-447e-a7dc-088a4a0d2fe4.png)
![image](https://user-images.githubusercontent.com/62279412/218260523-34443793-86a4-4f97-b58f-c31e8fa6fb5d.png)

## Additional context
今回使用したUAは実際に私のパソコンにインストールされているEdgeブラウザのUA。
user.jsで`browser.backspace_action`の値を変更(0)したところ、こちらは正常に適用された。
Floorpの`about:config`から編集した際には正常に適用された。
よく分からないが、Floorpでは標準で設定にUAを変更できるのでこれが邪魔してるのかなとも思う。
![image](https://user-images.githubusercontent.com/62279412/218260270-8af53c67-cad5-4c77-8760-2927331283e8.png)

よろしくお願いします。

**Comment by surapunoyousei** [comment]
おっしゃる通りです。指摘は正しいようですので解決します。何か進展があればお知らせします

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/218753945-b500b2ad-6d33-4c4b-a9e0-b83ec4e4e479.png)
![image](https://user-images.githubusercontent.com/73892113/218753958-6a34c203-f40b-4273-9565-26c3f31ecc59.png)

ユーザーエージェントの切り替え機能を実装しましたのでこれで解決としてマークします
