### ISSUE TITLE
putting distribution.ini leads to buggy behavior at about:preferences

### ISSUE THREAD

**Issue by Brli** [Floorp-Projects/Floorp#193]
## Describe the bug
Customized about:preferences conflicts with Partner Distribution Configuration file.

## To Reproduce
1. Download linux-x86_64 tarball from Releases page, and extract it.
2. put the file containing following infos as floorp/distribution/distribution.ini

```
[Global]
id=archlinux
version=1.0
about=Floorp for Archlinux
```

3. Open from terminal `./floorp -p` to make sure execute from upstream version, with clean profile.
4. Go to about:preferences

## Expected behavior
![Screenshot_20230217_182814](https://user-images.githubusercontent.com/4042566/219621205-23307e19-32c5-44d6-a4df-69f9d140e5ea.png)

## Screenshots
![Screenshot_20230216_163332](https://user-images.githubusercontent.com/4042566/219621241-90264c36-af0b-4916-8f96-2985fc12ba49.png)

## Desktop (please complete the following information):
 - OS: [e.g. Windows 11] ArchLinux
 - Floorp Version: [e.g. 10.1.2] 10.10.1

## Additional context

a example about distribution.ini
https://github.com/mozilla/build-partner-repacks/blob/master/partners/yahoo-de_foxload/distribution/distribution.ini

it is currently a support way to customize firefox without deep patch to source code.

the official build also has it https://fossies.org/linux/firefox/browser/installer/windows/msix/distribution/distribution.ini

**Comment by typeling1578** [comment]
This bug is now fixed.
Thanks!
