### ISSUE TITLE
Migrate to patchset maintanence instead of submit full tree.

### ISSUE THREAD

**Issue by Brli** [Floorp-Projects/Floorp#197]
## Is your feature request related to a problem? Please describe.

Current development repository has few disadvantages toward develop team.

1. The first clone wastes too much network bandwidth, also the coming everyday sync, which duplicates all the files due to git's nature.
2. It requires extra time to understand the code base (compare with upstream, diagnose differences etc.)
3. Troublesome to manually sync with mozilla upstream mercurial repo, as well as manually fixing conflicts here and there without clear map of diverged code.
4. Failed to automate a regular sync with upstream, which may includes known fixes on security issues, before disclosure -- which means no more hustle when news comes in.
5. A separate folder and pointer in moz.build which requires extra works to compare and analyze. -- with usage of patch set, people can easily understand the drop-in places and the pros and cons on codes and enhancements. AND, easier to generate marketing language instead of only saying it's from Japan.

## Describe the solution you'd like

Maintain patch sets and customization scripts instead of maintain diverged full source code base.

## Additional context

[Librewolf](https://gitlab.com/librewolf-community/browser/source), even have their own patch generator script
[Gentoo](https://dev.gentoo.org/~juippis/mozilla/patchsets/)
[OpenSuSE](https://github.com/openSUSE/firefox-maintenance/blob/master/firefox/firefox-kde.patch#L7) 's example of providing a simple HOWTO in patch description.

**Comment by surapunoyousei** [comment]
Hi, Thank you for your idea.

It is heavy for us. Floorp's  codes are so big. Migrate to patch may be impossible.

First clone is fast. it is right. but, If you build Floorp Browser, you have to get Firefox codes.

**Comment by surapunoyousei** [comment]
No response. close issue.
