### ISSUE TITLE
ツリー型タブを右配置した際に幅を変更できない

### ISSUE THREAD

**Issue by demodemo0818** [Floorp-Projects/Floorp#201]
## Describe the bug
ツリー型タブ(Tree Style Tab)を右側へ移動した際に幅を調節できません

## To Reproduce
1. サイドバー（デフォルトでブラウザマネージャーツールやブックマーク等があるサイドバー）を左表示
2. ツリー型タブを右側へ移動

## Expected behavior
ツリー型タブの左端をマウスオーバーした際に幅を調整可能に

## Desktop (please complete the following information):
 - OS: [Windows10 Pro 22H2]
 - Floorp Version: [10.10.1(64bit)]

**Comment by surapunoyousei** [comment]
修正しました！
