### ISSUE TITLE
Tree of tabs icon does not change color

### ISSUE THREAD

**Issue by necrosskull** [Floorp-Projects/Floorp#203]
## Black Tree of tabs icon
Tree of tabs icon is black regardless of the selected UI theme

## To Reproduce
1. Right click on any tab at the very bottom of the list

## Expected behavior
If dark theme is used, icon must be white like the rest of the icons above

## Screenshots
![image](https://user-images.githubusercontent.com/92830706/221641403-3d6a0b47-d370-46bb-bef0-28610f232503.png)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Floorp Version: 10.10.1

**Comment by surapunoyousei** [comment]
This problem caused by addon(TST). Maybe I think that is cannot fix. 

because, Firefox  doesn't offer API.
