### ISSUE TITLE
floorp cannot open external urls from other apps[Bug] 

### ISSUE THREAD

**Issue by labatts** [Floorp-Projects/Floorp#213]
### Describe the bug

I'm running this as a flatpak on opensuse kde, so it may be an issue with the flatpak build, but it cannot open any external links (thunderbird for example).

When running in terminal "xdg-open 'random-site.com', I get an error message of:

`Gtk-Message: 18:41:04.842: Failed to load module "canberra-gtk-module"
`
I've read that this may not be a big deal, but regardless the canberra modules are installed. 

### To Reproduce

1. use an external link via some other desktop application in an attempt to open in floorp.
2. does not open

### Expected behavior

1.should open

### OS Info

opensuse

### Floorp Version

10.9.0 64bit (flatpak)

**Comment by surapunoyousei** [comment]
It’s Flatpak's problem. Plz use PPA ver of Floorp.

Install PPA
```
    curl -fsSL https://ppa.ablaze.one/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/Floorp.gpg
    sudo curl -sS --compressed -o /etc/apt/sources.list.d/Floorp.list 'https://ppa.ablaze.one/Floorp.list'
    sudo apt update
    sudo apt install floorp
```

**Comment by labatts** [comment]
That work around will work fine for a debian based distro, I suppose, but  I -- as many other people -- am not on a debian based distro so this is not an option. It also is not really addressing the issue.

I have other flatpaks such as chrome that do not display this bug, so if it is an issue with flatpak, then it is an issue with the way that the program was packaged rather than the flatpak distribution method itself.

**Comment by surapunoyousei** [comment]
Isee. But, Flathub developers don't give Floorp permission. Because Foorp doesn't have permission to access all directories.

Since Flatpak has no way to deal with it, we will consider applying automatic updates to the binary itself when distributing it as a binary.

**Comment by labatts** [comment]
I have a gui app called flatseal that allows me to play around with permissions. I checked and did not see anything that would create the difference. I will look again, though, and let you know if anything is discovered.

In the meantime, I am attempting to clone it.

**Comment by surapunoyousei** [comment]
> I have a gui app called flatseal that allows me to play around with permissions. I checked and did not see anything that would create the difference. I will look again, though, and let you know if anything is discovered.
> 
> In the meantime, I am attempting to clone it.

Thanks.

**Comment by typeling1578** [comment]
This may be helpful: https://github.com/flatpak/flatpak/issues/1508

**Comment by surapunoyousei** [comment]
After some internal of Flatpak research, another developer resolved this issue. please wait for the update.
