### ISSUE TITLE
PDFファイルをページ範囲設定「すべて」にして印刷するとエラーが発生し1ページ目しか印刷されない

### ISSUE THREAD

**Issue by momizi06** [Floorp-Projects/Floorp#215]
### Describe the bug

Web上のPDFファイルを印刷しようとする際、ページ範囲設定を「すべて」に設定して印刷すると「エラーが発生しました」というダイアログが表示され、1ページ目しか印刷されない。

### To Reproduce

1. Web上のPDFファイルを開く
2. 画面右上の印刷ボタンを押す
3. ページ範囲設定を「すべて」にする
4. 印刷する
5. 画面上に「エラーが発生しました。」というダイアログが表示される
6. 1ページ目しか印刷されない

### Expected behavior

全てのページが印刷される

### OS Info

Windows 10 Home(64bit)  22H2

### Floorp Version

10.10.1

### Additional context

ページ範囲設定を「すべて」以外にすると正常に印刷される

**Comment by surapunoyousei** [comment]
Issue の報告ありがとうございます。

まずこちら側の環境で以下のファイルを再現のために印刷しました。しかし、あなたが提供してくれたような問題は再現されませんでした。
https://www.pref.kyoto.jp/kenkoshishin/documents/no_1.pdf

以下の設定で印刷しています。すべてのページが正しく印刷されました。
![image](https://user-images.githubusercontent.com/73892113/224301153-615c2af1-2aa0-4ad8-a1ca-21a723273fbe.png)

**Comment by momizi06** [comment]
> Issue の報告ありがとうございます。
> 
> まずこちら側の環境で以下のファイルを再現のために印刷しました。しかし、あなたが提供してくれたような問題は再現されませんでした。 https://www.pref.kyoto.jp/kenkoshishin/documents/no_1.pdf
> 
> 以下の設定で印刷しています。すべてのページが正しく印刷されました。 ![image](https://user-images.githubusercontent.com/73892113/224301153-615c2af1-2aa0-4ad8-a1ca-21a723273fbe.png)

先程、こちらで上記のURLのPDFを試してみましたが依然としてエラーが出ます。
もしかしたら私の環境依存の問題かもしれないです……
![2DE78B63-FF0E-42BC-ABAD-1664FECE4C40](https://user-images.githubusercontent.com/63577263/224319990-fd7642c5-3f43-4bbd-920e-0d17ee5231ff.jpeg)

**Comment by surapunoyousei** [comment]
了解です。新規プロファイルでの実行はしましたでしょうか？新規プロファイルでの実行ができた場合何らかの問題でプロファイルが壊れている可能性があります。

新機能プロファイルでの実行が方法は、Mozilla サポートの以下の記事が役に立ちます。
https://support.mozilla.org/ja/kb/profile-manager-create-and-remove-firefox-profiles

もし実行ができた場合はリフレッシュの方法がありますのでご報告下さい。また、エラーが出た場合も教えてください

**Comment by momizi06** [comment]
新規プロファイルでの実行できました。

**Comment by surapunoyousei** [comment]
なるほど。であればあなたの使用していたプロファイルに問題がありましたね。

Floorp をリフレッシュすることで解決できます。

注意：Floorp のリフレッシュはアドオンなどを削除依頼しますが、Firefox  sync を利用している場合は再インストールされます。また、大体のサイトはログイン状態が維持されますが、一部例外があります。

➀URLバーに「about:support」と入力中し、サイトに入ります。

➁サイトの右上に表示されている「Floorp をリフレッシュ」をクリックし、実行します。

➂Floorpがリフレッシュされ、タブを復元するか質問されます。

以上の手順で解決できると思われます。

**Comment by momizi06** [comment]
解決しました！ありがとうございます！
