### ISSUE TITLE
[Bug] window左上にあるspaceでwindowを移動することが出来ない

### ISSUE THREAD

**Issue by sarubo** [Floorp-Projects/Floorp#216]
### Describe the bug

タブバーをURLバーの位置に配置しているとき、window左上にあるspaceでwindowを移動することが出来ません。

### To Reproduce

1. Windowの最大化をやめる
1. メニューバーを非表示にする
1. about:preferences#lepton に移動する
1. 「タブバーをURLバーの位置に配置する」をONにする
1. window左上にあるspaceでdragする

### Expected behavior

windowが移動出来る。

### Screenshots

以下の画面の状態のときです。
![image](https://user-images.githubusercontent.com/47109823/224486141-6f9b53ff-6014-4219-9226-f4713dac16dc.png)

### OS Info

Windows 10 22H2

### Floorp Version

10.10.1

**Comment by surapunoyousei** [comment]
報告ありがとうございます。

Windows 11 で再現することはできませんでした。他の開発者に聞いてみます

**Comment by surapunoyousei** [comment]
Turned out to be a Lepton issue. I hope it will be resolved in the future.
