### ISSUE TITLE
[Bug] ウィンドウ右上にあるボタンが1段下がって表示される

### ISSUE THREAD

**Issue by mimikun** [Floorp-Projects/Floorp#218]
### Describe the bug

ウィンドウ右上に表示されるべきボタンが、1段下がって表示される

### To Reproduce

1. `about:preferences` を開く
2. 「タブバーの設定」の「垂直タブにブラウザーを最適化」を有効にする
3. 「ナビゲーションバーの設定」の「ナビゲーションバーをウィンドウの下部に表示」を有効にする
4. ウィンドウ右上にあるボタンの状態を確認する

### Expected behavior

ウィンドウ右上に表示されるべきボタンが、1段下がって表示される

### Screenshots

![image](https://user-images.githubusercontent.com/13450321/224719235-9b72019d-b1f0-4bc8-b432-9c6c965a9920.png)

### OS Info

Windows 11 22H2

### Floorp Version

10.11.0

**Comment by mimikun** [comment]
ありがとうございます。再現できなかったということですが

1. Floorp公式サイトより、ポータブルバージョンをダウンロード
2. ダウンロードしたzipファイルを展開
3. 中のFloorp.exeを実行
4. 適当なページをブックマークする
5. 適当なページがブックマークバーに表示されていることを確認
6. URLバーに `about:preferences` と入力し、設定画面にアクセス
7. 「言語と外観」の「ユーザーインターフェースの設定」より `Floorp Fluerial UIデザイン` を選択
8. 「タブバーの設定」の「垂直タブにブラウザーを最適化」を有効にする
9. 「ナビゲーションバーの設定」の「ナビゲーションバーをウィンドウの下部に表示」を有効にする
10. ウィンドウ右上にあるボタンの状態を確認する

この方法ではどうでしょうか？

**Comment by surapunoyousei** [comment]
Fixed at 11.2.0

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/17b6b39e807beeff3e678c69fe7e72706d4689d1
