### ISSUE TITLE
[Bug] BingでEdgeのUAが使用されない

### ISSUE THREAD

**Issue by lunae-f** [Floorp-Projects/Floorp#222]
### Describe the bug

タイトルの通りです。
通常通りのFirefoxのUEが送られているのか...何にせよ、Edgeへの偽装に失敗しているようです。Edge限定のBingのAIチャットも使用できません。

### To Reproduce

1. `about:preferences#search`から「既定の検索エンジン」を「Bing」に変更
2. 新しいタブを開いて検索を実行

### Expected behavior

BingにEdgeのUEが送信される。

### OS Info

Windows 11 Home Insider Preview 22H2

### Floorp Version

10.11.0

### Additional context

参考までに検索した際のURLを貼っておきます。
`form=MOZTSB` `pc=MOZI`とあるので、そもそもEdgeのUEが送れていないか、どこかでFirefoxであることを送信しているのと思います。が、よく分からないので見当違いなことを言っていればすみません。
`https://www.bing.com/search?form=MOZTSB&pc=MOZI&q=[検索した文字列]`

**Comment by surapunoyousei** [comment]
Bing.com では問題なかったようでしたが、www.bing.com でのユーザーエージェント切り替えがうまくいっていなかったようです。

次のアップデートで修正されます。このバージョンの Floorp は書き換えられているコードが増えており不安定なため、アップデートはチェック後になるため、少々遅れます。

**Comment by surapunoyousei** [comment]
近いうちにリリースされます。修正は完了しましたのでクローズします。ありがとうございました。🍻

**Comment by lunae-f** [comment]
謝謝茄子🍆
