### ISSUE TITLE
[Bug] Delete Border & Round Corners Only Display's Properly On Default Profile

### ISSUE THREAD

**Issue by TooSpooky** [Floorp-Projects/Floorp#225]
### Describe the bug

Hello,

When using the new feature to round corners, it seems that it only displays correctly on the default profile. On my current profile it is broken. I created a new profile just to test it, with the only changes being optimize for vertical tabs, shrink tabs till mouse over, and round corners which it is still broken using. Mind you with all those selected it displays properly on the default profile.

On a new profile, it works properly only with "System Theme - Auto", "Light", and "Alpenglow". Dark and my theme which I corrected to match properly are broken.  

Here's an example:

Default profile - 
<img width="1422" alt="floorp_nPNsmFHI4A" src="https://user-images.githubusercontent.com/21211292/225504601-deda7baa-59ce-4c87-839f-0193318ec028.png">

New Profile -
<img width="1329" alt="floorp_b6fIoEgRY0" src="https://user-images.githubusercontent.com/21211292/225505686-772018f8-c311-4e85-b778-0f326739530a.png">

Same theme across all instances.

Thanks for your time and take care!

### To Reproduce

1. Create a new profile
2. Activate Rounded Corners

### Expected behavior

Clean rounded corners

### Screenshots

Uploaded above.

### OS Info

Windows 11 22H2

### Floorp Version

10.11.0

**Comment by surapunoyousei** [comment]
You are right. But, this bug is fixed at aa77b4c3edb3f7bb1fd30e12a3ce08c93583292a .

Plz wait for update.
