### ISSUE TITLE
リリースノートなどは「英語」版も俎上にされると良いですね

### ISSUE THREAD

**Issue by Shitennouji** [Floorp-Projects/Floorp#23]
ブラウザ「Floorp」（及び「Frea Search」）は、
gHacks Tech News（独）のコミュニティでも注目されています。
https://www.ghacks.net/2022/08/23/firefox-104-analyze-a-websites-power-usage-and-ui-throttling/#comment-4546493
https://www.ghacks.net/2022/08/05/duckduckgo-is-soon-protecting-you-from-microsofts-tracking/#comment-4544979
https://www.ghacks.net/2022/07/26/firefox-103-improved-toolbar-access-performance-and-more/#comment-4534729

ブラウザ「Floorp」プロジェクトの主要なページやリリースノートについては、
将来的には「英語」版も俎上にされると良いですね

ドイツ語、オランダ語、フランス語、イタリア語、スペイン語、中国語（zh-CN、zh-TW）の要望も寄せられていますが.....、英語版さえあれば、他言語化は当事者に（英語から母国語への）翻訳化のコントリビューターとして助力してもらえるでしょう。

※ 老婆心ながら、
「学業」と「健康」を最優先してください！

**Comment by surapunoyousei** [comment]
こんにちは！日本語でのissue なので日本語で返信させていただきますね。

英語でのリリースノートですね！了解しました。

Floorp ブラウザ自体のローカライズは現在、日本語・関西弁・英語・ロシア語に対応しています。

リリースノートの方も英語に対応させていただきます（英語でも記述するという意味で）

> ※ 老婆心ながら、
「学業」と「健康」を最優先してください！

ありがとうございます。

これらに進展がありましたら、この issue で報告させていただきます。

**Comment by Shitennouji** [comment]
早々の返信に痛み入ります。
ところで、件名（title）が修正されていますが「リリースノートに限らない」ので、件名の修正は不適切に感じます。
優先順位は「リリースノート」が妥当ですが、
海外からも注目されているため、
将来的にはブログ（https://blog.ablaze.one/category/ablaze/ablaze-project/floorp/）なども課題にされることを願います。
実際、現在、

**Comment by surapunoyousei** [comment]
そのブログ＝リリースノートだと思っていただけば幸いです。

リリースノートはGitHub上にもありますが、基本的にあなた様の方の記載したリンクである blog.ablaze.one で提供されています。

Floorp が可能な限り様々な場所での多言語化は実します

**Comment by surapunoyousei** [comment]
一応 revert しました。失礼しました。
