### ISSUE TITLE
[Bug] back(forward)Button is null

### ISSUE THREAD

**Issue by SASIKI-64892** [Floorp-Projects/Floorp#232]
### Describe the bug

ツールバーから「進む」または「戻る」のボタンをツールバーから外した場合
アプリケーションメニューなどが正常に動作しなくなる。

### To Reproduce

ツールバーのカスタマイズで、「進む」または「戻る」のどちらかまたは両方をツールバーから外して保存した後。

#### 新しいウインドウを起動した場合、そのウィンドウは
 - アプリケーションメニューが開けなくなる、
 - ツールバーのカスタマイズが開けはするが真っ白でなにも操作できなくなる。。
#### 再起動した場合、すべてのウィンドウ、上記に加え、
- 拡張機能が左クリックで反応しなくなる。
- TSTサイドバーが無限にロードが終わらなくなる。

そしてそのプロファイルでツールバーのカスタマイズが開けるウィンドウが存在しない場合（再起動した場合など）、そのプロファイルは復旧方法は見つけられず、そうなった場合、右下の設定は開けるため、そこからプロファイルを新しく作る以外に正常な状態に戻す方法は見つかりませんでした。

### Expected behavior

それらの手順を行ってもそれらアプリケーションメニューなどが使用できること。

### Screenshots

![image](https://user-images.githubusercontent.com/99442371/226909672-c2bf2dbb-97a4-43a8-b334-6d283e4e52b6.png)
それら条件を満たし、新しいウィンドウを起動したときに表示される問題となっていそうなエラーコードで、ここで(スクリーンショットの場合は)backButton is nullと表示されているため、それによってほかのツールバーのボタンのリスナー設定ができなくなってしまい起きているものだと私は思っています。

### OS Info

Windows 11 バージョン22H2 OSビルド 22621.1413

### Floorp Version

10.11.0 (64 ビット)

### Additional context

私はjsなどweb技術には詳しくないため、間違っている可能性はありますが、[問題を出ないように修正したコード](https://github.com/SASIKI-64892/Floorp/commit/f6d22bad10c7b21a969b2dd280d029a88eca55ad)をかいてみましたが、このコードは、私がビルドができる環境を(3日かけましたが)作れなかったため、これが動くかどうかはわかりませんので参考程度にお願いします。

**Comment by surapunoyousei** [comment]
頂いたコードで動作検証しました。実装は少し変えましたが問題なく動作しているようですのでクローズさせていただきます。リリースノートにお名前の方を書きたいのですがよろしいでしょうか？

**Comment by SASIKI-64892** [comment]
動作検証していただきありがとうございます。問題く動作したようでよかったです！
お名前の方は書いていただいても大丈夫ですよ。
