### ISSUE TITLE
[Bug] Unclosable Customize tab

### ISSUE THREAD

**Issue by SASIKI-64892** [Floorp-Projects/Floorp#235]
### Describe the bug

タブ「Floorpをカスタマイズ」が消えるはずなのに存在し続け、ホワイトアウトしたタブとなりアクセスでき、再起動しない限り消滅しない。

### To Reproduce

Floorpを起動した後。
- 「多段タブを有効にする」を有効化
- タブバーを「垂直タブバーにブラウザーを最適化」か「水平タブを隠す」のどちらかに設定。
- ツールバーをカスタマイズを開き「完了」を押し終了する。
- ツリー型タブを新しく開く、またはツリー型タブを開きなおす。

それらの操作で「Floorpをカスタマイズ」という消せないタブが表示される。

### Expected behavior

それら手順を行ってもタブ「Floorpをカスタマイズ」が正常に消滅すること。

### Screenshots

![image](https://user-images.githubusercontent.com/99442371/227762446-f634f029-2b59-477a-83c3-4d7670e43043.png)
これがこのバグのエラーかどうかはわかりませんが、再現する手順四つ目を行ったときに表示されます。

### OS Info

Windows 11 22H2 build 22621.1413

### Floorp Version

10.11.1 (64 ビット)

### Additional context

なぜだか全くわからないのですが、手順一つ目を行わず(「多段タブを有効にする」を無効化)、そのあとの手順を行った時表示される場合がありますが、すぐに消滅したり、消滅はしないがアクセスできない場合など、
上記と同様に手順一を行わず、手順3まで終わらせた後、マウスジェスチャなどで、一番最後のタブ(「Floorpをカスタマイズ」があった場所)にアクセスしようとするとホワイトアウトしたタブにアクセスできるが、クリックなどを行い何か操作するとそのタブは消滅することが確認されています。

**Comment by surapunoyousei** [comment]
Floorp の垂直タブをネイティブ実装に変更するつもりなので放置します。

通常のタブバーから見えることはなさそうです。隠しタブになっているようです

**Comment by surapunoyousei** [comment]
以下から Floorp 11 のプレビュー版の特別なビルドをインストールできます。問題が発生するかお試しください。

https://github.com/Floorp-Projects/Floorp-Nightly/suites/12416413808/artifacts/660592604

**Comment by SASIKI-64892** [comment]
特別なビルドありがとうございます。
試してみたところ問題は発生せず問題なさそうです！
issues対応ありがとうございました。
