### ISSUE TITLE
[Feature Request] Microsoft TeamsでUAを偽装してほしい

### ISSUE THREAD

**Issue by lunae-f** [Floorp-Projects/Floorp#237]
### Is your feature request related to a problem?

Microsoft Teams(https://teams.live.com )がFirefoxをサポートしておらず、現状では設定でUAを変更しないと開くことが出来ない。

### Describe the solution you'd like

TeamsではUAをChromeかEdgeに偽装してほしい。

**Comment by surapunoyousei** [comment]
どれぐらい Floorp で検証しましたか？

Floorp で動かない場合、UA の上書きはできません

**Comment by lunae-f** [comment]
話す相手がいないので詳しい検証ができないのですが、設定からWindows上のChromeにUAを偽装すると一応開けました。
しかし、会議でカメラをオンにするとタブがクラッシュします。「今すぐ会議」から新規作成した際も、リンクから開いた際もクラッシュします。
その他の機能は、見た感じは正常に動くように思います。

**Comment by surapunoyousei** [comment]
よく検討して決めようと思います。ウェブ互換性のために UA の上書きを行うことが多いので場合によってはしない場合がありますがご了承ください

**Comment by surapunoyousei** [comment]
やはり、互換性としては問題があるのでやらないことにしました。ご了承ください
