### ISSUE TITLE
ブログでの投稿（コメント）がブロックされるようです

### ISSUE THREAD

**Issue by Shitennouji** [Floorp-Projects/Floorp#24]
リリースノートなどは「英語」版も俎上にされると良いですね #23 は、
当初、ブログで投稿しようとしたのですが、常にブロックされて投稿不能でした。
オランダ人（＠TelV）からも、ブログでは投稿できなかったと嘆いていました。
https://www.ghacks.net/2022/08/23/firefox-104-analyze-a-websites-power-usage-and-ui-throttling/#comment-4546642
gHacks Tech News の管理者（@Martin）から「フィードバックや問い合わせは、どのようにすればよいのか」と連絡がありました。

**Comment by surapunoyousei** [comment]
ブログは投稿できない理由は私にはよくわかりません。ですが、suppot.ablaze.one/contact なら確実に伝わりますのでご利用ください。

TelV 様には以下をお伝えください。

Blogcommentaren worden pas weergegeven nadat ze zijn goedgekeurd. Als u persoonlijk contact wilt opnemen, moet u dat dus rechtstreeks doen via "https://support.ablaze.one/contact".

Sorry voor het ongemak.

**Comment by code-raisan** [comment]
横から失礼いたします。
AblazeのWeb全般の管理をしているものですが、問題解決のためにスクリーンショット等を送って頂けないでしょうか?

**Comment by Shitennouji** [comment]
> 横から失礼いたします。 AblazeのWeb全般の管理をしているものですが、問題解決のためにスクリーンショット等を送って頂けないでしょうか?

今回は、成功しました。
https://blog.ablaze.one/2182/2022-08-01/#comment-75

**Comment by Shitennouji** [comment]
> https://www.ghacks.net/2022/08/23/firefox-104-analyze-a-websites-power-usage-and-ui-throttling/#comment-4546642

ちなみに、
It may be a case of lost in translation, but if Floorp is going to disable the built-in version of UBO after 60 seconds, what’s the point of including it? 
については事情と経緯を返信済みですが、
（日本＞ドイツ）時差（非活動時間）とモデレートのため、現時点では未公開のようです。

**Comment by code-raisan** [comment]
対応が遅れて申し訳ありません。
2件のコメントを承認しました
コメントがブロックされてしまったのは何らかの形でスパムなどと認識されてしまった可能性があります

**Comment by Shitennouji** [comment]
> 対応が遅れて申し訳ありません。 2件のコメントを承認しました コメントがブロックされてしまったのは何らかの形でスパムなどと認識されてしまった可能性があります

いえいえ、とても素早いレスポンスで、面食らってしまいます。
少なくとも私に対しては、いつでも（数日後でも）構いませんから。

ところで、
2件との事ですが、簡単に見つけることができなかったので、改めてお尋ねします：
トピック「個人的にオススメなFirefox向けのアンチトラッキングアドオン」で、2件
トピック「Floorp ブラウザー｜バージョン 10.4.0 リリースノート」で、1件（内容は、github.com/Floorp-Projects/Floorp/issues/23）でしたが。
それらの 3件が判明できたのでしょうか？
また、かのオランダ人は「キャプチャで弾かれて、うまくいかない」と述べています。

**Comment by code-raisan** [comment]
コメントは先ほど来た「test」というメッセージ以外には2件しか確認できていません

キャプチャは標準設定を使っていますが、何度も発生するようでしたらブロックレベルを下げたいと思いますのでSupportまでご連絡ください。

**Comment by Shitennouji** [comment]
この件「ブログでの投稿（コメント）がブロックされるようです
#24」は、これで十分です。
本当にご苦労様でした。
活動時間を制限されて、十分な英気を養ってくださいね。
ありがとうございました。

**Comment by code-raisan** [comment]
わざわざ、ご報告ありがとうございます。これからもAblazeをよろしくお願いいたします

**Comment by Shitennouji** [comment]
今しがた、かのオランダ人から
https://www.ghacks.net/2022/08/23/firefox-104-analyze-a-websites-power-usage-and-ui-throttling/#comment-4546684
コンタクトサイト経由でリクエストを送ったところ、画像コンテンツオプション（適切な画像を選ぶ）で動作するようになりました。
要望の送付もしました。
と連絡がありました。
以上、
ご一報まで。

**Comment by kr-tukimi** [comment]
Ablaze Support担当者のtukimiです。

お問い合わせを受け取ったことを確認いたしました。
できるだけ早くご返信させていただきます。
