### ISSUE TITLE
[Bug] Restrore defaults in Customize Mode make browser hang 

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#250]
### Describe the bug

Click Restore default button in Customize Mode make browser hang 

### To Reproduce

1.Right Click Navigaiton Bar
2.Click Customize Toolbar
3.Click Restore defaults

### Expected behavior

Toolbar position settings restore to defaults

### Screenshots

![hang](https://user-images.githubusercontent.com/11323774/232365180-8751b3cd-b746-4ac5-aa4c-8522c8057889.jpg)

### OS Info

Windows 11

### Floorp Version

10.12.0

### Additional context

```
CustomizeMode: TypeError: gDefaultTheme is undefined
    _resetUIState resource:///modules/CustomizableUI.jsm:3157
    reset resource:///modules/CustomizableUI.jsm:3114
    reset resource:///modules/CustomizableUI.jsm:4215
    reset resource:///modules/CustomizeMode.jsm:1257
    reset resource:///modules/CustomizeMode.jsm:1270
    oncommand chrome://browser/content/browser.xhtml:1
```

**Comment by typeling1578** [comment]
Fixed in https://github.com/Floorp-Projects/Floorp/commit/27d493163e0dc5a0fb1e9ac20f1f8675a39695a9
Thanks!

**Comment by benzBrake** [comment]
this problem recur in 11.3.3

**Comment by surapunoyousei** [comment]
Fixed
