### ISSUE TITLE
Floorp i686 / 32-bit builds

### ISSUE THREAD

**Issue by golf1487** [Floorp-Projects/Floorp#256]
### Is your feature request related to a problem?

Yes, 64-bit Floorp hogging resources compared to Firefox ESR and Firefox Release.

### Describe the solution you'd like

Introducing i686 / 32-bit builds tend to use less resources.

### Additional context

As you can see, right now 32-bit Firefox requires less resources:

https://www.mozilla.org/en-US/firefox/113.0/system-requirements/

One of the Firefox forks have already introduced 32-bit builds  and I'm very satisfied.

**Comment by surapunoyousei** [comment]
I see. We will consider providing only the Windows version.

**Comment by surapunoyousei** [comment]
Do you use Linux operating system?
