### ISSUE TITLE
Native Vertical Tabs

### ISSUE THREAD

**Issue by golf1487** [Floorp-Projects/Floorp#257]
### Is your feature request related to a problem?

Yes, the default top bar occupies too much space and I lost hope that Firefox is going to implement vertical tabs natively.

### Describe the solution you'd like

I really like Vertical Tab's implementation in projects like Brave - I like it more in Brave
than it's implemented in another Firefox fork, called Pulse (which I no longer use).

It would be cool to be able to choose, having vertical tabs on the left and right side as well.

**Comment by surapunoyousei** [comment]
I made it! Native verticaltab will come to Floorp at v11.0.0
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/42724feb-6971-4a44-b669-4136085d3aa4)
