### ISSUE TITLE
[Feature Request] Improve "Tab Sleep" feature

### ISSUE THREAD

**Issue by Car0lina5** [Floorp-Projects/Floorp#260]
### Is your feature request related to a problem?

For me, the Tab Sleep feature is a great feature for the browser but it frustrates me when the page is restarted.

### Describe the solution you'd like

I would like the tab to go back to the part where we left off, for example, when we scroll down the page and after a while the Tab Sleep feature is activated, it would be nice if there was an option so that we could continue from the part where we left off.

### Additional context

If I'm not mistaken, Brave's discard function is similar but it saves the page where we left off. There's also a chrome extension called "Tab Suspender" that works that way. I know that Floorp is based on Firefox so I don't know if this feature improvement would be possible. I've also looked for an extension that would do this in the Firefox store but I could never find it. Anyway, it's something I'd really like to see so here's my suggestion.

**Comment by surapunoyousei** [comment]
This seems like a difficult problem.

Chromium and Firefox are different, so they probably handle suspend differently.

We'll have to look into an alternative way to exclude pages.

**Comment by typeling1578** [comment]
related #199

**Comment by creeper-0910** [comment]
This issue is closed due to lack of activity for some time.
