### ISSUE TITLE
[Bug] Bookmarks not visible in bookmark bar

### ISSUE THREAD

**Issue by Tobitoon1** [Floorp-Projects/Floorp#267]
### Describe the bug

When pressing the star symbol to bookmark a website it will not show up in the bookmark bar. No matter where the bar is located. Bookmarks are still visible in the libary.  Sometimes the whole bookmark bar is not showing at all.

### To Reproduce

1. Open any website and press the star symbol. 
2. Choose bookmark bar and press Save in the pop up 
3. Take a look at the bookmark bar and see no saved bookmark

### Expected behavior

After saving the bookmark a small icon of the website and the title should show up in the bookmark bar

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/135463374/7d0b46bb-983b-409a-822f-356ce17d45c1)

![image](https://github.com/Floorp-Projects/Floorp/assets/135463374/060d64a0-6ebc-4c0f-810d-3ecc769a166a)

### OS Info

Windows 10 Home 10.0.19044

### Floorp Version

10.13.0

**Comment by surapunoyousei** [comment]
can't reproduce.

Please let me know the changed settings that seem related

**Comment by Tobitoon1** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/135463374/9c830188-68c9-436f-a3e8-53fbbd9a394f)

Just put on the second option

Here are the other things that related to bookmarks:
![image](https://github.com/Floorp-Projects/Floorp/assets/135463374/99c65edf-dbe0-4262-968c-d8a72002420b)

![image](https://github.com/Floorp-Projects/Floorp/assets/135463374/38195486-814f-448f-af21-49c9678dab84)

![image](https://github.com/Floorp-Projects/Floorp/assets/135463374/d8bbd904-fdf4-4598-b20f-919794b21ce0)

**Comment by Tobitoon1** [comment]
Found the appropriate setting to show the bar. No bug. Will close the issue.
