### ISSUE TITLE
No longer recording history 

### ISSUE THREAD

**Issue by Telmesomething** [Floorp-Projects/Floorp#27]
Since 26-8-2022 Floorp is no longer recording history. I was using it the whole day yesterday and also this morning. 

1. Open the History menu. The last recorded date in this particular case is 26-8-2022.

Expected behaviour:
History should be recorded. 

Screenshot from today.

![not recording history anymore](https://user-images.githubusercontent.com/33827636/187068531-010f8739-e270-4c01-906c-d71ae80bef21.jpg)

- OS is Windows 8.1 Home (fully patched)
- Floorp version 10.4.0

**Comment by surapunoyousei** [comment]
Please wait as we will verify it.

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/187069405-4076db30-42d8-404e-bad6-02b172db1882.png)

seems to be working fine.

Windows 11 Pro Releases Preview channel (latest)

Please try the following:

 Make sure the following settings are correct.

![image](https://user-images.githubusercontent.com/73892113/187069551-d121cd63-6eef-4987-a4df-db619fb2c2ac.png)

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/187069975-ef097a37-5707-4bdf-9457-70e834b5409b.png)

On linux mint

**Comment by Telmesomething** [comment]
Please disregard this post. I found the reason why it was happening in about:config. The setting "places.history.enabled" was set to _false_. 

Although I do enable various privacy settings in that location I don't recall changing that particular one.

**Comment by surapunoyousei** [comment]
I'm glad the problem went away. Thank you for your report

**Comment by Shitennouji** [comment]
> Please disregard this post. I found the reason why it was happening in about:config. The setting "places.history.enabled" was set to _false_.

> [Telmesomething](https://github.com/Telmesomething) closed this as [completed](https://github.com/Floorp-Projects/Floorp/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [yesterday](https://github.com/Floorp-Projects/Floorp/issues/27#event-7273369741)

I just checked your thread on GitHub!
I see that the cause has been found and resolved.
Also, I see you made a donation!
I'm glad you like the project as much as I do.

The project team, all of whom are current high school students, is truly remarkable in that they are working on the project while balancing their academic work.
This project team is really down to earth, as they are all current high school students, and are working on the project while juggling their schoolwork.
Moreover, they are taking the "high road" in those directions, steadily evolving as the days go by, and their user support is very sincere.
I greatly admire their (the project members') ability, passion, and ambition.

I look forward to your ([Telmesomething](https://github.com/Telmesomething)) continued attention and support for their project.
