### ISSUE TITLE
SearX in the list of Search Browser

### ISSUE THREAD

**Issue by Lunacid** [Floorp-Projects/Floorp#270]
### Is your feature request related to a problem?

I use SearX for my job (Game Designer)

### Describe the solution you'd like

Add SearX in the list of search engine in a new tab can be nice

### Describe alternatives you've considered

Or maybe add the search browser we want (For example : Qwant, Brave Search...)

**Comment by Lunacid** [comment]
Because in my opinion, if the user can add the search engine he wanted, you give more freedom to the user. And if you speak about SearX, it's because I can have the results from Google, bing, Yandex and mojeek in the same search engine

**Comment by surapunoyousei** [comment]
OK We will add it. plz wait.
