### ISSUE TITLE
Say it's not secure or can't connect to certain site

### ISSUE THREAD

**Issue by Lunacid** [Floorp-Projects/Floorp#271]
### Describe the bug

Sometimes I need to reboot because it's say the site it's not secure (Drive Google) or can't display (Reddit). It's not happen everytime
Can't search in startpage either

### To Reproduce

Go to https://drive.google.com
Go to https://www.reddit.com/

### Expected behavior

Don't need to reboot when it's happen

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/135908182/a3d2bc36-a9b2-4598-bb80-732348c286cc)

### OS Info

Windows 11 2H22

### Floorp Version

10.14

**Comment by surapunoyousei** [comment]
Hmm, Did you try to use new profile?

**Comment by Lunacid** [comment]
I don't know how to use a new profile, so no

**Comment by surapunoyousei** [comment]
https://support.mozilla.org/en-US/kb/troubleshoot-and-diagnose-firefox-problems#w_6-tnew-cmd-firefox-nopurohuairuwozuo-cheng-suru

**Comment by Lunacid** [comment]
I try it, but it doesn't work either.

**Comment by Lunacid** [comment]
ESR115 ? But the last Firefox ESR is 102.12.0 no ? Maybe I go wrong

**Comment by surapunoyousei** [comment]
Firefox 115 is new Firefox ESR. I will release next month. Floorp 11 is base on ESR115.

https://github.com/Floorp-Projects/Floorp/ESR115 is the branch.

**Comment by Lunacid** [comment]
I'm sorry, I'm not an expert at browsers, but on Firefox website they say version 115 is the next regular version no ? The next ESR is 102.13. maybe I'm wrong.

**Comment by surapunoyousei** [comment]
That's true.  but, ESR102 is keep for 2month after Firefox 115 release. Floorp 10 is same
