### ISSUE TITLE
Cannot play videos (related DRM) [Bug] 

### ISSUE THREAD

**Issue by crummei** [Floorp-Projects/Floorp#272]
### Describe the bug

When trying to watch any show/movie on multiple streaming platforms, the video doesn't play and I get met with an error message.
I've tried HBO Max, Netflix (Previews work, but not full screen streaming) which don't work and prime video and Viaplay works, but viaplay gives me this message when playing video.
![image](https://github.com/Floorp-Projects/Floorp/assets/56043602/9883df42-c214-4256-b960-ea3a6dfd5c86)
![image](https://github.com/Floorp-Projects/Floorp/assets/56043602/b3a95b00-8bfb-42dc-b58d-5b2da2bda316)

I've made sure that Enhanced Privacy Protection and/or an extension isn't causing the issue.

### To Reproduce

1. Go to one of the 2 streaming platforms above
2. Pick any show/movie to watch
3. Click ´Play´
4. Error message pops up

### Expected behavior

I expected to be able to watch the show

### Screenshots

Note: Its a new error code every time, doesn't explain what went wrong.
![image](https://github.com/Floorp-Projects/Floorp/assets/56043602/7622ec1b-ab15-4c77-9e5d-2d980e8033fd)

### OS Info

Windows 10 22H2

### Floorp Version

10.14.0 (64bit)

**Comment by surapunoyousei** [comment]
It causes by "Google Widevine" system.

most of "Non-free video provide platform" uses "Digital rights protection". If user want to see the movie or anime, have to use allowed browsers.

This system is made by Google. small browser cannot get the video or only get low quality video.

We think it is big problem. but, "Google widevine" is so close & Ostensibly it is free, but in reality it is paid for because it is exclusive. At present we have no choice but to cry and fall asleep

**Comment by crummei** [comment]
> It causes by "Google Widevine" system.
> 
> most of "Non-free video provide platform" uses "Digital rights protection". If user want to see the movie or anime, have to use allowed browsers.
> 
> This system is made by Google. small browser cannot get the video or only get low quality video.
> 
> We think it is big problem. but, "Google widevine" is so close & Ostensibly it is free, but in reality it is paid for because it is exclusive. At present we have no choice but to cry and fall asleep

well thats annoying, is there no other option than to hope google has it in their heart to deem us worthy?
Jokes aside do i really have no other choice but to switch to a chromium based browser if i want to use streaming services?

**Comment by surapunoyousei** [comment]
We contacted google but, there is no response. we have no choice.

You can use Firefox or Waterfox. They are corp or company.

**Comment by VarLad** [comment]
@surapunoyousei I haven't used the browser, but just happened to look at the issue.
How about using https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/ as a workaround :)

**Comment by surapunoyousei** [comment]
It does not work.

The website does not check the user agent, it checks if you have a "Google Widevine" and if the "Google Widevine" you have is signed.

Widevine is downloaded and installed when Floorp starts up, but the videos will not play because they are not signed by Google.

I hate Widevine because it makes it easy to check what kind of browser a browser is.

**Comment by Sa-Ja-Di** [comment]
Then i suggest it would be a good idea to fully remove the DRM option out of the browser. It is privacy invading black-box technology anyway.

Also removing the DRM options out of the settings UI would be a good idea.

**Comment by surapunoyousei** [comment]
But, Amazon can play this unsigned widevine. We cannot delete it.

I agree to blackbox opinion

**Comment by surapunoyousei** [comment]
Really!?

**Comment by avktech78** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/94455603/81fc4bfd-affc-4ab9-889e-9e6a464242d5)

**Comment by military1** [comment]
Is it possible yourself to copy Widevine and transfer it from Firefox?

**Comment by surapunoyousei** [comment]
Cannot it....

**Comment by creeper-0910** [comment]
Floorp cannot resolve the DRM issue, so we are closing this issue.
Please re-open if you have new information.

**Comment by WAZAAAAA0** [comment]
(@creeper-0910 please re-open)

hmm, weird. In Win64, the Widevine DRM: 
`floorp-win64.installer11.4.1.exe` - works!
`floorp-11.4.1-portable-windows-x86_64.zip` - doesn't work
(test demo here <https://bitmovin.com/demos/drm>)

**Comment by surapunoyousei** [comment]
As I have said many times, this is not a solution for us.

This is because the Floorp executable itself needs to be signed by Google to allow all of the DRM to run.

We don't make a profit and we rely on donations, so this is currently not possible.
