### ISSUE TITLE
[Feature Request] Add option to hide lepton icons

### ISSUE THREAD

**Issue by Sollace** [Floorp-Projects/Floorp#281]
### Is your feature request related to a problem?

??

### Describe the solution you'd like

Currently when using the Lepton theme there are all these extra icons added to menus all over the place. 

e.g. On context menus and application menus.
![image](https://github.com/Floorp-Projects/Floorp/assets/6429283/394c553d-2f66-4202-8975-e56b2e03df61)

I don't really _want_ these. I consider them rather ugly and they clutter up the UI. I'd rather just have the icons that were present in Firefox 88 without adding any extra ones.

I was able to find a way to do that using Floorp as it is, by setting `userChrome.icon.menu` to `false` in `about:config`, so really my only request is to add a checkbox for that to the Lepton settings like what Waterfox has.

**Comment by surapunoyousei** [comment]
Floorp has Lepton preferences. 

go "about:preferences#lepton". you can change lepton UI. 

But, there is no icon preferences. we have to add it.

**Comment by Sollace** [comment]
> 
> But, there is no icon preferences. we have to add it.
> 
That would be perfect. Thank you!

**Comment by surapunoyousei** [comment]
Enabled in v11.0.0. Until then, please have a cup of tea and wait .🍵

This issue will be closed once the relevant commits have been pushed
