### ISSUE TITLE
[Feature Request] Opt-in telemetry

### ISSUE THREAD

**Issue by printedz** [Floorp-Projects/Floorp#282]
### Is your feature request related to a problem?

Mozilla has telemetry so they can improve their products, disabling it by default and not having it as an opt-in feature is harmful for them.
There are also helpful studies like the currently ongoing homepage cache one which I can't benefit from since I can't enable them.

### Describe the solution you'd like

It'd be nice if there was an option in the settings to manually enable telemetry and studies.

### Describe alternatives you've considered

Maybe it could also be enabled by default.

**Comment by surapunoyousei** [comment]
You are interesting. Contributing to Mozilla is nice.

However, there are many practical problems: Floorp is a different build than Firefox and Floorp issues are also collected. Sending the wrong report would be counterproductive.

Also, don't worry. We designed the browser to contribute to Mozilla simply by using Floorp. We don't remove ads from new tabs, and we display Google search results as Firefox, so we are contributing enough to Mozilla.

With the Gecko engine's market share declining, we recommend that you don't worry about this issue, as simply promoting the engine is a contribution.

**Comment by Sa-Ja-Di** [comment]
Telemetry is NEVER good and you should NEVER have something like that activated.

And given the fact of Mozilla's countless decisions against their own user-base - making their browser more look and work like Chrome and killing off advanced UI customization - Mozilla is nobody which can be trusted much anymore. 

They are in the same boat as Google itself.

So, please, do NOT add that.

**Comment by printedz** [comment]
> Telemetry is NEVER good and you should NEVER have something like that activated.
> 
> And given the fact of Mozilla's countless decisions against their own user-base - making their browser more look and work like Chrome and killing off advanced UI customization - basically betraying their own target user base of power users who loved advanced XUL add-ons or full themes - Mozilla is nobody which can be trusted much anymore.
> 
> They are in the same boat as Google itself.
> 
> So, please, do NOT add that. I personally go even as far to masquerade the user-agent as something different, to NOT help Mozilla in any way.

Telemetry isn't always bad, you're tilting at windmills; it's helpful for developers, and not necessarily intrusive. 
Personally, I like the direction Firefox is going, and I genuinely don't understand why you go as far as masquerading your user-agent to, I presume, help to kill Mozilla, which may go extinct in the near future.

**Comment by Sa-Ja-Di** [comment]
@printedz Killing off customization is nothing what one should like. There is already a Chrome, so why replicating the browser as much as Mozilla did.

And i personally would be happy to see Mozilla "die" - as long as the browser would be pushed into different hands who are again interested in feature diversity and customization diversity, going away from this quite ridiculous simplicity madness train on which Mozilla is since Firefox 22.

**Comment by printedz** [comment]
> @printedz Killing off customization is nothing what one should like. There is already a Chrome, so why replicating the browser as much as Mozilla did.
> 
> And i personally would be happy to see Mozilla "die" - as long as the browser would be pushed into different hands who are again interested in feature diversity and customization diversity, going away from this quite ridiculous simplicity madness train on which Mozilla is since Firefox 22.
Customization leads to tons of issues one can't expect, XUL add-ons were replaced with WebExtensions because the latter is easier to maintain and is also compatible with Chromium. 
In my opinion, the simplicity of Firefox Quantum is very nice, and has a lot of features that makes it better than its Chromium counterparts: containers, Firefox Sync (it's much better than its alternatives for me), user-made CSS to modify the UI, etc.

**Comment by Sa-Ja-Di** [comment]
@printedz Wrong - Customization does not lead towards issues. People who can handle it should handle it, people who don't - should take off their hands off such features.

The only reasons as said WHY Mozilla removed features was bc they are jealous and want to replace Chrome as number one market share wise. Resulting in betraying everyone who supported them until Firefox 22/28/56

Web-extentions... you can't even hide a simple browser bar with them. With this Mozilla added finally insult to injury.

**Comment by printedz** [comment]
@Sa-Ja-Di 
You're acting as if your viewpoint is everyone's: most people wants to use a browser that just works and won't bother customizing it, there is the option to use userChrome.css for those who want customization. Of course Mozilla is doing what's trending because that's what people are used to and like.

No one's forcing you to use the browser. If you don't like it, use another one you like more, it's as easy as that.

About Mozilla's ethics: Are you seriously comparing Edge, from a tech giant, to a browser made by an NGO that focuses on privacy? That's hilarious.

**Comment by Sa-Ja-Di** [comment]
@printedz Mozilla is in the same boat like Google - just another greedy organization hungry for success and only interested in feeding corporate design and one size fits everyone to all - granted, Mozilla was different in the past and this ideology change affected later versions of their product.

If you read my comment again, i clearly mentioned ethics/morals/ideology superiority in relation to feature side of view - so yes, Edge, Brave and Vivaldi have a clear literal edge over Mozilla developer-mentality wise. And 2 of that orgs are not even open source. This simple fact should make you think.

**Comment by printedz** [comment]
> If you read my comment again, i clearly mentioned ethics/morals/ideology superiority in relation to feature side of view - so yes, Edge, Brave and Vivaldi have a clear literal edge over Mozilla developer-mentality wise. 
You said "Vivaldi, Brave or Edge has today more morals and more ethics than Mozilla as a whole". When one talks about the ethics of an organization it usually is the discipline dealing with what is good and bad and with moral duty and obligation.

I see absolutely nothing wrong in the path Mozilla is taking, I also agree with their "politics". Again, it's just a matter of one's viewpoint; if you don't like it, don't use it!

**Comment by Sa-Ja-Di** [comment]
> You said "Vivaldi, Brave or Edge has today more morals and more ethics than Mozilla as a whole". When one talks about the ethics of an organization, it usually is the discipline dealing with what is good and bad and with moral duty and obligation.

regarding in trying to be different than the rest - that is what i wrote. Read, Process, react - logical way to act ;)

> 
> I see absolutely nothing wrong in the path Mozilla is taking, I also agree with their "politics." Again, it's just a matter of one's viewpoint; if you don't like it, don't use it!

And that is my main problem with simple users - You ruin EVERYTHING - and my MAIN issue with so-called Activist politics (Progressives) - same answer.

We are done here :D

**Comment by printedz** [comment]
> regarding in trying to be different than the rest - that is what i wrote. Read, Process, react - logical way to act ;)

It's hard to understand what you mean when you use lots of hyphens for no reason and use words that don't make sense in that context. Given that I also have ASD, it's even harder.

> And that is my main problem with simple users - They ruin EVERYTHING - and my MAIN issue with so-called activist politics (Progressives) - same answer. 

They're the biggest part of the user base, Mozilla would lose them otherwise, and then it'd probably have to shut down. I don't get how progressives are related, and "activist politics" is a stupid term you came up with: not all left-wing people participate in activism, nor are all sctivists necessarily left-wing.

**Comment by Sa-Ja-Di** [comment]
> They're the biggest part of the user base
> 

After losing 90% of power and advanced users - Yes, the number of remaining users using Firefox is much (not) - nothing of what one should be proud of

**Comment by printedz** [comment]
> > They're the biggest part of the user base
> 
> After losing 90% of power and advanced users - Yes, the number of remaining users using Firefox is much (not) - nothing of what one should be proud of

The number of those users is very small. In fact, I think it's actually something to be proud of that the browser, which is not the default on any platform, is still alive with lots of millions of users all over the world!

**Comment by Sa-Ja-Di** [comment]
Uhm... Mozilla had over 20% market share with power and advanced users during version 22.... and now look at today's numbers with activists and some converted Chrome users left

**Comment by printedz** [comment]
> I personally am apolitical - i do not vote for anybody - but it is clearly visible that a very high number of activist/left related people are just destroying technology - the more progressive it becomes, the more simple and less feature rich it gets. And that gets another very wrong flag by me personally.

Oh my god, what is wrong with you? How are activists relayed to this? 

There is no "progressive" software because software isn't related to politics. 
In fact, lots of left-wing people collaborate with GNU/Linux, which is very highly customizable. You can't just make generalizations like that with no scientific base whatsoever (statistics, for example).

**Comment by Sa-Ja-Di** [comment]
There is a direct relation between ideology of developers/management - this has a clear mirror also at the software development level

**Comment by printedz** [comment]
> Uhm... Mozilla had over 20% market share with power and advanced users during version 22.... and now look at today's numbers with activists and some converted Chrome users left

People back then used Firefox because IE sucked. Now nearly everyone is tied to the Google ecosystem, which pushes Chrome onto everyone.

**Comment by printedz** [comment]
g

> There is a direct relation between ideology of developers/management - this has a clear mirror also at the software development level

Someone's political views aren't related to how they like to live their live: minimalism, materialism, etc. Please, next time you say something like that back your claim with scientific studies.

**Comment by Sa-Ja-Di** [comment]
Google is just a company. You can ignore them and do your own business or like Mozilla and Opera becoming their pawn with getting paid or using their code (especially if you had previously your own product/code)

**Comment by printedz** [comment]
> Google is just a company. You can ignore them and do your own business or like Mozilla and Opera becoming their pawn with getting paid or using their code (especially if you had previously your own 

> Google is just a company. You can ignore them and do your own business or like Mozilla and Opera becoming their pawn with getting paid or using their code (especially if you had previously your own product/code)

You can, but it's not convenient! Most people use Google products which integrate with Chrome, which also is the default Android browser and on most PCs. Almost no one gives a f*** about browsers.

**Comment by menndouyukkuri** [comment]
@Sa-Ja-Di I think you are mistaken. This is not a forum to complain about Mozilla, but a place to make feature requests. Isn't there a more appropriate place elsewhere for your activities?

**Comment by surapunoyousei** [comment]
I apologize for not closing this Issue and continuing to view it as an interesting discussion.

Both sides have very reasonable and understandable opinions, and I was very impressed with them. However, this is not a discussion forum, so please continue on Reddit or other forums.

**Comment by printedz** [comment]
I already closed the issue a few comments ago, sorry for continuing it!

**Comment by surapunoyousei** [comment]
I don't care about this.

Please continue to let us know what is wrong with the web. There are many opinions we can help develop.
