### ISSUE TITLE
[Bug] フォント設定が反映されない

### ISSUE THREAD

**Issue by kometchtech** [Floorp-Projects/Floorp#287]
### Describe the bug

設定にフォント設定を行ったところフォント設定が反映されません。

### To Reproduce

1. [設定]より実施

### Expected behavior

- 10.15.0と同様になる？

### Screenshots

- 10.15.0
![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/b7ed2c2e-da42-42b6-bf0e-10cb953ec80d)
![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/94fb78ba-d736-4bdb-a095-b0670de55966)

- 11.0.0
![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/aadca5dd-696c-44e1-8c4f-7699d0f4e79a)
![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/b7c387a1-2c9c-4821-8e8f-53f0dbf2fc3e)

### OS Info

Windows 11 22H2

### Floorp Version

11.0.0

**Comment by surapunoyousei** [comment]
Firefox 102 と Firefox 115 ではどうなりましたか？

**Comment by kometchtech** [comment]
申し訳ありません。
Firefox 102、115は両方とも使用しておりませんでした。
ただし、少なくとも114.0.2では10.15.0と同様でした。

![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/793bbd27-e543-48e2-ba7a-76d4cb23b1cd)

**Comment by surapunoyousei** [comment]
デザイン設定は何を使用していますか？

もし Lepton なのであれば、別のデザイン（Proton 等）を使用して再度検証していただけますか？

**Comment by kometchtech** [comment]
ありがとうございます。
報告の際にはProtonを使用しておりました。
Photon・LeptonデザインのLeptonに切り替えてみましたが状況は変わりませんでした。

**Comment by kometchtech** [comment]
大変申し訳ありません。
何度かFloorpの再起動およびスーパーリロードを繰り返していたところ、意図した表示になっていました。

![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/2e98546e-bed9-4393-8fc3-e9d267fc56d9)

これといった原因が分からず申し訳ありません。

**Comment by kometchtech** [comment]
原因が分かりました。
「フィンガープリントに対する強力な保護を有効にする」を有効にしていたことでこの問題が発生していました。
フィンガープリント保護は、インストールしたフォントにも影響するのですね･･･（不勉強で申し訳ありません。）

バグと報告してしまい申し訳ありませんでした。大変お騒がせいたしました。

**Comment by surapunoyousei** [comment]
すみません体調不良で寝ていました。解決できてよかったです

**Comment by kometchtech** [comment]
昨日は体調不良の中対応頂きありがとうございました。
