### ISSUE TITLE
[Bug] deoesn't remember open status of Browser Manager Sidebar

### ISSUE THREAD

**Issue by tortino2** [Floorp-Projects/Floorp#288]
### Describe the bug

I enabled Browser Manager Sidebar. 
Then I open bookmarks or other panel, and close the browser.
When restarting the browser the panel is not open, like it was before.
Floorp should rememeber the open or closed status.

### To Reproduce

1. enable Browser Manager Sidebar
2. click on the star to make visible the bookmarks panel
3. close the browser
4. reopen the browser
5. the bookmarks panel is not visible

### Expected behavior

the bookmark panel should be visibile after restart

### OS Info

windows 10 22h2

### Floorp Version

10.15.0

**Comment by surapunoyousei** [comment]
Not bug.
