### ISSUE TITLE
Some of the Floorp's elements become broken, if language is set to Russian

### ISSUE THREAD

**Issue by regularenthropy** [Floorp-Projects/Floorp#29]
## Describe the bug
Elements in the groups with the ID of "blockmoretrackers" and "trackingGroup" become broken, if language is set to Russian.

## To Reproduce
1. Set language to Russian
2. Enjoy broken elements

## Screenshots
![image](https://user-images.githubusercontent.com/89523758/187149868-f2e64f7c-8ff7-4ab8-a71e-38283e3496b2.png)
![image](https://user-images.githubusercontent.com/89523758/187149911-389f0781-40b2-49a8-8b28-1426455dc252.png)
![image](https://user-images.githubusercontent.com/89523758/187149975-71dead69-e4d2-4e6e-8130-da9b779555a2.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Version: Last from the Floorp's website

**Comment by surapunoyousei** [comment]
The size of the text varies depending on the language of the browser, so it failed to match everything.

**Comment by regularenthropy** [comment]
> The size of the text varies depending on the language of the browser, so it failed to match everything.

Indeed. I've tried to change width in the  .amourl to max-content. It fixed the overlapping, but "trackingGroup" is still broken.

I'll submit a pull request to resolve the first issue.

**Comment by regularenthropy** [comment]
The second issue is also being fixed by setting up max-height in the #trackingGroup to 910px.
This solution is pretty dumb, but working properly.
I will also open a pull request for it, but because this fix is pretty dumb (original Firefox doesn't even have it), merge at your own risk.

**Comment by surapunoyousei** [comment]
In Japanese, I was able to get the same results by forcing the site's font to be Noto Sans JP instead of Meiryo.

 Firefox's interpretation of some fonts is known to be problematic, and it turns out that a direct engine overhaul is required.


![image](https://user-images.githubusercontent.com/73892113/187164310-ae7d8893-583d-4744-b071-453ad512c401.png)


> The second issue is also being fixed by setting up max-height in the #trackingGroup to 910px. This solution is pretty dumb (works only with English and Russian) If I came up with a more dynamic solution, I'll open a pull request for it

So you can see that this fix is ​​the most realistic. Hmm...

**Comment by regularenthropy** [comment]
> In Japanese, I was able to get the same results by forcing the site's font to be Noto Sans JP instead of Meiryo.
> 
> Firefox's interpretation of some fonts is known to be problematic, and it turns out that a direct engine overhaul is required.
> 
> ![image](https://user-images.githubusercontent.com/73892113/187164310-ae7d8893-583d-4744-b071-453ad512c401.png)
> 
> > The second issue is also being fixed by setting up max-height in the #trackingGroup to 910px. This solution is pretty dumb (works only with English and Russian) If I came up with a more dynamic solution, I'll open a pull request for it
> 
> So you can see that this fix is ​​the most realistic. Hmm...

Yep. But somehow this value should be calculated dynamically because the current solution is strictly language-dependent.
If I'll set this value up in Dansk, German, French, Italian, Livetuviu and other, than the container will overflow

**Comment by regularenthropy** [comment]
Also, I can suppose, that it has something to do with the do-not-track request, which for some reason was put in the "trackingprotection" vbox

**Comment by surapunoyousei** [comment]
It seems that this problem is difficult to solve, so I would like to change the design a little to maintain compatibility.

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/187170133-b9a076cc-2406-44cf-8883-33b6ca406e69.png)

I was able to fix `display: inline` by removing the background shadow, so I would like to use this to fix it.

**Comment by regularenthropy** [comment]
If it works for all languages, then go for it.

**Comment by surapunoyousei** [comment]
Another problem occurred, so I will leave it for now. I'll keep the issue open until it's resolved

**Comment by surapunoyousei** [comment]
![изображение](https://user-images.githubusercontent.com/73892113/187202769-18fbcb06-91d3-4c27-80dc-88fee098f951.png)

I fixed it lightly.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/2611538953c435390a1b21c4a3e74aaab8a99253

Fixed
