### ISSUE TITLE
[Feature Request] add workspaces to browser manager sidebar

### ISSUE THREAD

**Issue by tortino2** [Floorp-Projects/Floorp#290]
### Is your feature request related to a problem?

In the browser manager sidebar on the right I'd like to see a new panel with the list of workspaces.

### Describe the solution you'd like

add to the browser manager sidebar a new panel with the list of workspaces

**Comment by surapunoyousei** [comment]
This issue relate to Floorp 11?

**Comment by tortino2** [comment]
yes, it's floorp beta 11.
sorry I didn't specified the browser version.

**Comment by surapunoyousei** [comment]
I will try it.

**Comment by surapunoyousei** [comment]
Progress will be a little slow as I do not have time to work on this at the moment.

**Comment by surapunoyousei** [comment]
Still progress

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/8e8d497e32afdc2d7eed65066be2a9e3db805f0c
Added

**Comment by tortino2** [comment]
thanks!
