### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sdsucks** [Floorp-Projects/Floorp#291]
### Describe the bug

my workspace button turned into "null" after updating to latest beta 11.

this "null" text can't be removed with 'customize toolbar' menu.

new workspace button is on top of vertical tab bar.

### To Reproduce

if you had workspace enabled and updated to latest beta 11

### Expected behavior

previous workspace button should be gone

### Screenshots

[[url=https://postimg.cc/K4YwvBxH][img]https://i.postimg.cc/RC1BdL84/workspace-button.jpg[/img][/url]](https://i.postimg.cc/5N217FLG/workspace-button.jpg)

### OS Info

win10 22H2

### Floorp Version

11 beta

**Comment by surapunoyousei** [comment]
Today's update  causes this problem. i will ckeck it

**Comment by surapunoyousei** [comment]
Fixed: https://github.com/Floorp-Projects/Floorp/commit/6decbcce77cf5ec8f79d93c0eaa21e212f6122e4

If you see this bug after next update, plz reopen this issue
