### ISSUE TITLE
[Feature Request] Contiune supporting Windows 7/8 past 115

### ISSUE THREAD

**Issue by K4sum1** [Floorp-Projects/Floorp#293]
### Is your feature request related to a problem?

Firefox is removing support for Windows 7/8 with version 116. To them it's just a "bug"

### Describe the solution you'd like

Reverting of any commits removing Windows 7/8 support.

### Additional context

I'm not a coder, but as far as I know these are the only commits so far removing 7/8 support so far.
https://github.com/mozilla/gecko-dev/commit/decb18e6ab705aac7036f35b9237aba85adb9ea4
The two below look to have been reverted by https://github.com/mozilla/gecko-dev/commit/377011cc9e4b770cc9ce77f6b6eced72034a4e91
https://github.com/mozilla/gecko-dev/commit/0024eac2b4177ace8cb628029af8e678c72d5aa5
https://github.com/mozilla/gecko-dev/commit/424038f49e5ccf68cda31884aa238fb600cb24bd
This is the installer commit readded.
https://github.com/mozilla/gecko-dev/commit/8fb87b4a893990c6986aa86212cd15f56d769076

**Comment by surapunoyousei** [comment]
Floorp is based on FirefoxESR115. Do not worry, existing user continue to use Floorp for 1 year.

Clean install is unsupported.

**Comment by K4sum1** [comment]
Well I hope by then I won't be tracking commits and there will be a backported browser that I can just refer to for the next ESR, unless Mozilla is especially lazy and only does superficial commits like the above.

So far Nightly 117.0a1 still runs, none of these commits have hit it yet, and even if it did all I would need to do is extract it and patch the subsystem version.

**Comment by surapunoyousei** [comment]
I understand what you are saying.

If possible, I will remove this commit or otherwise make it usable, even though it is not supported.

**Comment by surapunoyousei** [comment]
Close issue. When ESR115's next ESR released, plz open issue. I check it,
