### ISSUE TITLE
[Bug] DuckDuckGo search engine doesn't use JavaScript

### ISSUE THREAD

**Issue by Telmesomething** [Floorp-Projects/Floorp#296]
### Describe the bug

I previously deleted DuckDuckGo as a default search engine after reading an article about it relaying search results to Microsoft. However, that appears to have been resolved now so I hit the "Restore default search engines" button to reinstate it. 

It reappears in the list, but seems to be a stripped down version of the original. The URL appears as https://html.duckduckgo.com/html/ and the usual search options such as "Videos", "Images" "News" for example are missing. Here's a screenshot of what it looks like after using the search string: "Frankie Corio".

![duckduckgo bug](https://github.com/Floorp-Projects/Floorp/assets/33827636/6aaa074a-2d32-4d20-a7a2-be0002248c31)

### To Reproduce

1. Delete DuckDuckgo in the list of default search engines.
2. Hit the Restore default search engines button.
3. Provided DuckDuckGo reappears in the list, go to Search and set DDG as the default search engine.
4. Run a search using the URL field (which is the way I've always done it). 
5. When DDG shows the results, the options for Video, News etc. will be missing.

### Expected behavior

DDG should show the usual search options such as those in Google, Frea Search etc. 

### Screenshots

![after hitting restore search engines button](https://github.com/Floorp-Projects/Floorp/assets/33827636/59955626-af5d-4a4f-b34d-2628d1585487)

### OS Info

Windows 8.1 Home

### Floorp Version

10.15.0

### Additional context

The three additional search engines in the second screenshot are those I've added myself.

**Comment by surapunoyousei** [comment]
Plz following these steps:

1. open about:preferences#search
2. Remove DuckDuckGo.
3. Click [Restore Default Search Engines] for restore DDG.

**Comment by typeling1578** [comment]
It seems to occur when JavaScript fails to load properly due to some reason.
Would disabling all add-ons not solve the issue?

**Comment by Telmesomething** [comment]
Removed DDG and disabled all addons, but the issue persists are hitting the "Restore default search engines" button.

![removed ddg and disabled addons](https://github.com/Floorp-Projects/Floorp/assets/33827636/3b6498d2-429a-496c-8356-8fe82b9c1bb7)

**Comment by Telmesomething** [comment]
No problem on Firefox anyway.

![firefox ddg ok](https://github.com/Floorp-Projects/Floorp/assets/33827636/b13a350f-8120-436a-af11-cc12ba32a0eb)

**Comment by typeling1578** [comment]
Would the same issue occur if you manually add DDG?

![Screenshot from 2023-07-10 01-33-52](https://github.com/Floorp-Projects/Floorp/assets/59644555/86416fbd-69ea-4aa8-8687-8c055ee39ad3)
![Screenshot from 2023-07-10 01-34-33](https://github.com/Floorp-Projects/Floorp/assets/59644555/4bdcb439-eaa9-4fb9-9d4e-2167790487ff)

**Comment by Shitennouji** [comment]
I also tested it in my environment.
Floorp 10.15.0
Windows_NT 10.0 19045 (22H2)
A DDG search for "Frankie Corio" yielded the expected results.

I've also tested with other Firefox ESR 102.13.0, Pulse Browser 1.0.0-a.74 and Firefox Nightly version 117.0a1, but could not reproduce the issue.

I reproduced the situation you mentioned if I "disabled Java Script" in that environment.
Perhaps it's because your Floorp or browser extension (uBlock Origin) is set to "Default behavior, Disable JavaScript".

**Comment by Shitennouji** [comment]
> Perhaps it's because your Floorp or browser extension (uBlock Origin) is set to "Default behavior, Disable JavaScript".

Diagnose Firefox issues using Troubleshoot Mode
https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode
When you run Firefox in Troubleshoot Mode, add-ons and some other features and customizations are disabled. If you’re having a problem in Firefox that does not occur in Troubleshoot Mode, the cause of the problem is one of the disabled items.

**Comment by Telmesomething** [comment]
> Would the same issue occur if you manually add DDG?
> 
> ![Screenshot from 2023-07-10 01-33-52](https://user-images.githubusercontent.com/59644555/252157557-86416fbd-69ea-4aa8-8687-8c055ee39ad3.png) ![Screenshot from 2023-07-10 01-34-33](https://user-images.githubusercontent.com/59644555/252157559-4bdcb439-eaa9-4fb9-9d4e-2167790487ff.png)

Doesn't help unfortunately. The problem seems to be caused by Floorp adding "html" to the URL i.e. [https://html.duckduckgo.com/html/] when the page loads.

![ddg manual - no difference](https://github.com/Floorp-Projects/Floorp/assets/33827636/277152b9-2894-498a-a0aa-c0442d3841aa)

**Comment by Telmesomething** [comment]
https://github.com/Floorp-Projects/Floorp/issues/296#issuecomment-1627950938

Already tried both of those options. 

Default UBO settings as follows:

![UBO default settings blank](https://github.com/Floorp-Projects/Floorp/assets/33827636/de7a99ed-394b-4bf8-9496-68fcf6bdccc1)

**Comment by Telmesomething** [comment]
I fixed it by creating a new profile. Should have thought of that before.

Apologies to everyone for their input.
