### ISSUE TITLE
[Question] auto hide elements

### ISSUE THREAD

**Issue by sdsucks** [Floorp-Projects/Floorp#298]
### Describe the bug

currently "auto hide elements" doesn't seem to work.

is this intended?

i thought it was gonna work with the release of v11.

### To Reproduce

n/a

### Expected behavior

hope it will work some time soon

### Screenshots

![autohide](https://github.com/Floorp-Projects/Floorp/assets/6938353/2836b93b-a68a-45da-921d-c73b9d44e23b)

### OS Info

win10 22H2

### Floorp Version

11

**Comment by sdsucks** [comment]
![auto hide elements](https://github.com/Floorp-Projects/Floorp/assets/6938353/242a648c-3c33-4d5a-9bad-22fc2c4c4ee7)

i mean those options in settings

**Comment by surapunoyousei** [comment]
I think you not use lepton. It causes.

These preferences are lepton features,

**Comment by sdsucks** [comment]
you're right.

Leption UI - Leption preferences - Leption mode - auto hide nav bar
this audo hides the nav bar. actually all 3 modes seem to work.

but, a weird thing is i have to move the mouse pointer to where **the back button** is on the nav bar to bring the nav bar back. no where else seems to work.
pressing ALT key works of course but this is not what i want.
auto hiding and bringing back the nav bar with the mouse worked alright in version 10.

**Comment by surapunoyousei** [comment]
If you focus out from navigation-bar. Lepton use delay to hide the bar. It causes?

In y my environment, there is no problem.

**Comment by sdsucks** [comment]
autohide navbar still doesn't work correctly.

i have to move the mouse pointer to exactly where the back button is on the nav bar to bring the navbar back.

i'm using version 20230719121924.

if i enable bookmarks bar, autohide navbar works correctly.
if i hide bookmarks bar and have only navbar left. autohide starts working weirdly. 

Floorp v10.15 works just fine.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/assets/73892113/6e9b46bc-3342-4632-adf1-201c83165415

can't reproduce

**Comment by sdsucks** [comment]
try with vertical tab bar on

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/assets/73892113/20bb5598-5e1e-4f25-b43f-b05cb3b8a972

**Comment by surapunoyousei** [comment]
The problem is caused by the fact that there is no focusable element for the navigation bar.

 Naturally, this function cannot be used properly without some element at the top.

 The new vertical tabs remove the tab bar, so maybe that's the effect.


https://github.com/Floorp-Projects/Floorp/assets/73892113/45cd858e-131d-466a-9bfc-95a5869af00b

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/assets/73892113/9004c42c-64fb-4623-aaaf-36e5d6e10064

**Comment by sdsucks** [comment]
so you mean you can't do anything about it?

why does Floorp v10.15 work just fine with the same setup?

**Comment by surapunoyousei** [comment]
Floorp 10.15 doesn't have Vertical tab. What does men "same setup"?

**Comment by sdsucks** [comment]
![v10 15](https://github.com/Floorp-Projects/Floorp/assets/6938353/9f0067d0-45a7-469d-8f65-2992bfb5e991)

vertical tab bar
nav bar
auto-hide nav bar

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/assets/73892113/71a435d7-5168-4f9a-8e88-2faa0156dbda


https://github.com/Floorp-Projects/Floorp/assets/73892113/a1eb757c-5238-4d05-aa5b-d69d34863fa9

Maybe same...?

**Comment by SarreqTeryx** [comment]
> I think you not use lepton. It causes.
> 
> These preferences are lepton features,

This should be made clear in the settings
