### ISSUE TITLE
[Bug] Browser is extremely slow on some websites

### ISSUE THREAD

**Issue by crummei** [Floorp-Projects/Floorp#300]
### Describe the bug

It seems completely random, I can't find a pattern, but the browser just takes really long to load some sites, it sits there on whatever site you were on before just thinking for like 5 seconds and then finally actually starts loading the site.

### To Reproduce

1. Try to use browser
2. Wait way too long for loading times

### Expected behavior

I expected the browser to work fine and have good loading times

### OS Info

Windows 10 Home 22H2

### Floorp Version

10.15.0 (64-Bit)

**Comment by surapunoyousei** [comment]
Could you tell me the site？

**Comment by crummei** [comment]
> Could you tell me the site？

Its many, I can't find a pattern to which sites are affected, but I've experienced it happening to netflix, youtube, reddit and even just searching on google

**Comment by surapunoyousei** [comment]
Hmm, It’s odd.

**Comment by surapunoyousei** [comment]
I have gathered a lot of information to resolve this, but not much seems to stand out.

It is odd that some sites are odd, and I can understand if they are generally heavier than Firefox, but that does not apply in this case.

If you have encountered this bug, please provide information.
