### ISSUE TITLE
[Bug] Microsoft Fluent UIデザインで、通信の暗号化状態の表示がおかしい [11.0.0 beta]

### ISSUE THREAD

**Issue by newmomizi** [Floorp-Projects/Floorp#302]
### Describe the bug

Microsoft Fluent UIデザインを使用時、アドレスバー左端の鍵マーク/警告マークの中の「安全な接続」「安全でない接続」の文字の背景に、鍵マークまたは警告マークが大量に表示され、文字が非常に読みづらくなる。
少なくともGoogle、YouTube、阿部寛のホームページの3つのウェブサイトで確認済み。発生しないパターンは未確認。
また、他のデザイン使用時には発生していない。

### To Reproduce

1. 「設定」内の「デザイン」 (about:preferences#design)を開く。
2. ユーザーインターフェースの設定で、Microsoft Fluent UIを選択する。
3. 何らかのウェブサイトを開き、アドレスバー左端の鍵マーク、または警告マークをクリックする。

### Expected behavior

他のデザイン設定時と同様に、左端に鍵マーク、その右に「安全な接続」「安全でない接続」の文字のみが表示されると考えていた。

### Screenshots

<img width="254" alt="スクリーンショット 2023-07-12 165327" src="https://github.com/Floorp-Projects/Floorp/assets/114981625/f05ce158-f902-4111-ae62-2a3a8cd72181">
<img width="290" alt="スクリーンショット 2023-07-12 203703" src="https://github.com/Floorp-Projects/Floorp/assets/114981625/225c2760-5f8e-48e7-9a9c-d42660d69df4">

### OS Info

Windows 11 Enterprise 21H2

### Floorp Version

11.0.0 ( floorp.en-US.win64.zip )

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/2828a4d7502ecb20b31dc703c6a731a91297e70d

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/actions/runs/5536450359/jobs/10109149338

修正を含んだアップデートを展開しました。ご確認ください！
