### ISSUE TITLE
[Feature Request] Option to disable TreeTabs

### ISSUE THREAD

**Issue by Sollace** [Floorp-Projects/Floorp#303]
### Is your feature request related to a problem?

This is relating to an issue where tabs would keep opening in the wrong position.

When I use Ctrl+Click to open a link in a new tab, it initially opens in the correct location (to the right of the current tab) but then as soon as it loads the tab jumps to the end. I end up tripping over it, and until I realised what was happening I kept wondering why I kept switching to the wrong tab and not being able to find the one I just opened.

I thought it was me until I saw the tab _jumping_ to the end of the tab bar after I open them. All the settings are set to keep the tab at the default position, as below:
![image](https://github.com/Floorp-Projects/Floorp/assets/6429283/2aec6c6a-4466-4b2f-8bd2-af96921ba71e)

I tried changing them but it kept happening. I thought it was a bug, until today I got annoyed enough by it that I went digging and eventually stumbled into the TreeStyle tabs settings and I found this:

![image](https://github.com/Floorp-Projects/Floorp/assets/6429283/d7fb8188-d1da-4fee-a550-36124457681c)

I changed it to "(no control)" and that fixed the "bug".

### Describe the solution you'd like

It seems weird that TreeStyleTab's preferences are being used when I'm not using TreeStyle tabs. If I'm not using that layout, ideally I'd expect it to act like a regular tab bar.

Those settings shouldn't matter at all.

Although alternatively, it would also be good to have the option to disable the extension entirely for people who don't need it.

**Comment by surapunoyousei** [comment]
Floorp 11 doesn't include TST. We will remove it in the future.

**Comment by surapunoyousei** [comment]
PS: We know about opening tab issue. Because of it, remove

**Comment by Sollace** [comment]
Ah okay, sorry. Thank you for explaining.
