### ISSUE TITLE
[Feature Request] Option to choose custom urls also in new tab

### ISSUE THREAD

**Issue by Car0lina5** [Floorp-Projects/Floorp#304]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I just wish we could choose our custom urls for the new tabs. Another suggestion would also be for the url to remain blank and selected when we open this new tab.

### Describe alternatives you've considered

The solution I found was to change the "autoconfig.cfg" and "autoconfig.js" files. I found this in some tutorial on the internet and it worked.

### Additional context

It's not a big deal but it's something I think would be really cool. I don't remember any browser that has this function.

![14 07 2023  -  16 21  -  ](https://github.com/Floorp-Projects/Floorp/assets/117472773/ae76262e-d6b2-4ac2-aecb-4ea73c3e35df)

**Comment by surapunoyousei** [comment]
What is your solution? I want to know about your "autoconfig"

**Comment by Car0lina5** [comment]
1. Open the Floorp installation folder (C:\Program Files\Floorp Daylight).
2. Under this folder, open the "defaults\pref" folder. If not present, make those two folders.
3. Create a file called "autoconfig.js" inside the "defaults\prefs" folder, and put the following in it. This lets us run our own Javascript to configure the browser. The comment line at the top is required. Use Unix line endings.

//
pref("general.config.filename", "autoconfig.cfg");
pref("general.config.obscure_value", 0);
pref("general.config.sandbox_enabled", false);

4. Go back to the Floorp program folder "..\.."
5. Create a file named "autoconfig.cfg"
6. Put the following in the file, replacing the value of newTabURL with the path to your startpage.

//  
var {classes:Cc,interfaces:Ci,utils:Cu} = Components;  
  
/* set new tab page */  
try {  
  Cu.import("resource:///modules/AboutNewTab.jsm");  
  var newTabURL = "file:///PATH_TO_YOUR_START_PAGE.html";  
  AboutNewTab.newTabURL = newTabURL;  
} catch(e){Cu.reportError(e);} // report errors in the Browser Console

Note: I just copied and adapted from a post I found on reddit (community is currently private but I have the google cache link and will leave it here)

Link: https://webcache.googleusercontent.com/search?q=cache:S2nCQoKwqSsJ:https://www.reddit.com/r/startpages/comments/g3qndt/psa_how_to_set_a_custom_new_tab_page_in_firefox/


![image](https://github.com/Floorp-Projects/Floorp/assets/117472773/f9eb89a4-53af-48f7-8edb-e30113d8003e)

![image](https://github.com/Floorp-Projects/Floorp/assets/117472773/75f87ec8-1bdf-412e-9436-6897c151ddbb)

**Comment by surapunoyousei** [comment]
Thanks. will build the feature.

**Comment by surapunoyousei** [comment]
Research is finished.

It is possible to create the function you mentioned, but we cannot ignore the possibility of being vulnerable to malware attacks, so we will implement it as an experimental function that can be deleted at any time.
