### ISSUE TITLE
[Feature Request] Allow search engine changes for non-ESR as well 

### ISSUE THREAD

**Issue by firezt** [Floorp-Projects/Floorp#306]
### Is your feature request related to a problem?

I'd like to be able to edit search engines (add, remove, make default, etc.) through the policies.json file, something that is currently only possible using ESR. So it doesn't work on Floorp 11 (based on firefox v115).

### Describe the solution you'd like

The LibreWolf project got that functionality through [this](https://gitlab.com/librewolf-community/browser/source/-/blob/main/patches/sed-patches/allow-searchengines-non-esr.patch) patch, maybe Floorp can make use of it too.

### Additional context

Thanks for reading.

**Comment by surapunoyousei** [comment]
I think I can release it since I originally learned where to modify it in the version 8 era.

However, it is probably due to the fact that it is a beta version. I think it will be available by the time it becomes stable. However, it won't take much effort, so I'll release it.

**Comment by firezt** [comment]
Good to hear that, thanks. 😃

**Comment by surapunoyousei** [comment]
f1c293daaf7c299b6ee81f76525371bb04516394

**Comment by firezt** [comment]
Just tried it with the build from 13 hours ago (win64), from here: https://github.com/Floorp-Projects/Floorp/releases/tag/beta

I'm not sure if they are up to date with the search engine policy change, as it doesn't seem to have had any effect. See:
![c8ZD41juQP](https://github.com/Floorp-Projects/Floorp/assets/87192386/71566c9d-c7b0-422d-a5c7-67d4355b0316)
It would be nice if you could confirm this for me, otherwise I'll wait for the build with the change. :slightly_smiling_face:

**Comment by surapunoyousei** [comment]
Wait for new build.

**Comment by BL4CKH47H4CK3R** [comment]
Please continue your discussions here #868.
