### ISSUE TITLE
[Bug] (Floorp 11 Beta) Tabs from other workspaces are brought to the current workspace when starting or restarting the browser

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#307]
### Describe the bug

In Floorp 11 Beta when you create a new workspace and put tabs there and return to the default workspace and then restart the browser and open a new tab or switch tabs, the tabs from the other workspace are brought into the current workspace.

### To Reproduce

1. Create a new workspace (e.g. Work-1)
2. Switches to that workspace (Work-1) and opens some tabs
3. Switch to the default workspace and restart the browser.
4. Open a new tab in the current workspace and you will see that the tabs from other workspaces are brought into the current workspace

### Expected behavior

Expected result: When opening a new tab in the current workspace, tabs in other workspaces do not appear in the current workspace.

### OS Info

Windows 10 22H2

### Floorp Version

11.0.0 Daylight Beta

### Additional context

The bug also appears when you start the browser for the first time at operating system startup and not only when the browser is restarted.
I don't know if this bug only happens to me or I don't know if this is the expected behavior of this feature (Workspaces).

**Comment by surapunoyousei** [comment]
This issue was reported recently, but it looks like it was resolved in another patch.

**Comment by surapunoyousei** [comment]
Do you have a video to show this issue?

**Comment by kaos-55** [comment]
I am trying to record a video, but the bug no longer occurred when I restarted the browser, however when I restarted the OS and started the browser the bug occurred.
It seems to happen when it is a cold start of the browser.
I am going to try to record it since my PC takes ages to reboot.

**Comment by kaos-55** [comment]
Here is the video, note that when I press the new tab button, the tabs that were in the "work 1" workspace are brought to the current (default) workspace.
I tried several times and the bug did not always appear and when it did it was random.

https://github.com/Floorp-Projects/Floorp/assets/86812371/937fc6d6-fa47-4c51-9356-99ce4b89c00e

**Comment by surapunoyousei** [comment]
I see..

**Comment by surapunoyousei** [comment]
May fix this issue.

https://github.com/Floorp-Projects/Floorp/commit/fc67746c932e5da90c255f3ea16c128d36f28c0d

**Comment by surapunoyousei** [comment]
Update released. Plz check it

**Comment by kaos-55** [comment]
I just updated, I'm going to do some tests to see if the bug is fixed.

**Comment by kaos-55** [comment]
After using it for a whole day between browser restarts and OS startup, it seems that the bug has been solved.
Thanks for fixing it.
