### ISSUE TITLE
[Bug] (Beta v11) When the sidebar is on the left, the panels still open on the right side and cannot be resized

### ISSUE THREAD

**Issue by firezt** [Floorp-Projects/Floorp#308]
### Describe the bug

Basically the title says it all. If the sidebar is positioned on the left side, webpanels still open on the right side (as if the sidebar was there), and they also cannot be resized.

### To Reproduce

1. Go to `settings`
2. Enter the `Browser Manager Sidebar` section and uncheck `Display Browser Manager Sidebar on the Right` option
3. Open any webpanel on the sidebar

### Expected behavior

If the sidebar is on the left side, the panels should also open on that side and should be resizable, just like in Floorp v10.

### Screenshots

![flp_Abx12ePKj](https://github.com/Floorp-Projects/Floorp/assets/87192386/65ea5249-d124-464c-a5ca-1f72d16be6fa)

### OS Info

Windows 10 21H2

### Floorp Version

11.0.0

### Additional context
Edit: Apparently any panel has this effect, not just web ones.

Thanks for reading.

**Comment by surapunoyousei** [comment]
fixed. wait for new build

**Comment by surapunoyousei** [comment]
released !
