### ISSUE TITLE
[Feature Request] Notification badge for web panels

### ISSUE THREAD

**Issue by firezt** [Floorp-Projects/Floorp#309]
### Is your feature request related to a problem?

No web panel shows a notification badge, with the quantity in number, or anything like that. I tried with some social networks and web versions of messengers like WhatsApp and Telegram, all with the same result.

### Describe the solution you'd like

A badge that shows you that there is a notification for the respective panel, just like in Vivaldi or Opera, for example.

### Additional context

I honestly don't know how difficult it would be to bring this functionality to Floorp, but it would be a great addition to the sidebar. :slightly_smiling_face:

**Comment by surapunoyousei** [comment]
I don’t know about the feature. What like?

**Comment by firezt** [comment]
Look:
![vv-12AsWPlZ](https://github.com/Floorp-Projects/Floorp/assets/87192386/19c12d1b-1cd9-4855-85d7-9bc04cdbbcbe)

**Comment by surapunoyousei** [comment]
I see... Difficult.

Have to research it.

**Comment by surapunoyousei** [comment]
Sorry, We cannnot add it.

**Comment by firezt** [comment]
Well... could you share why? all the browsers I've tested that have web panels can do this, I can't see why Floorp couldn't.

**Comment by surapunoyousei** [comment]
Floorp use Google or DuckDuckGO API for Webpanel. Replace this codes are so difficult for us.
