### ISSUE TITLE
close workspaces menu after choosing a workspace

### ISSUE THREAD

**Issue by tortino2** [Floorp-Projects/Floorp#310]
### Is your feature request related to a problem?

I love the workspaces menu in the top left, but it doesn't work like other menus: it doesn't close after I choose one of the workspaces. 
all other menus in my pc (running windows) close after selecting an item in the menu.

### Describe the solution you'd like

I'd like an option in the setting to make possibile the closing of workpsace menu after choosing an item

**Comment by surapunoyousei** [comment]
This feature is useful?

I cannot imagine the benefit.

**Comment by tortino2** [comment]
yes, it's useful.

all of the menus in Windows work like this: they close after selecting an item from the menu.
it's the default behaviour and users expect that menus work in that way.

also I find inconvenient to select a workspace and still see the menu: I want to change workspace, I open the workspaces menu and select the new workspace... so why the workspaces menu is still open? it's useless, because I have already chosen the new workspace.

in any case I asked to implement this new behaviour as an OPTION in the settings.
this option should NOT be enabled by default, so the current behaviour is still enabled, since you like it.
but at least with the option the users can decide by themselves what they like.

**Comment by surapunoyousei** [comment]
On Floorp 11.0.1 or Floorp 11.1.0, You can change "floorp.browser.workspace.closePopupAfterClick" pref for auto close

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/2c803d546efd6a1842a8d44661d8254aa93e1603

**Comment by tortino2** [comment]
thanks!
