### ISSUE TITLE
[Bug] (Floorp 11 Beta) Pinned tabs do not stay in place when many tabs are opened

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#314]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

In the latest updates of Floorp 11 when you have pinned tabs and you open many tabs and the scroll bar appears, the pinned tabs are hidden when you scroll.

### To Reproduce

1. Pin some tabs
2. Open many tabs until the tab scroll bar appears.
3. Press the tab scroll bar and the pinned tabs are hidden.

### Expected behavior

Pinned tabs must remain visible even if the tab scroll bar appears.

### Screenshots

![Floorp](https://github.com/Floorp-Projects/Floorp/assets/86812371/a5071367-1c32-4570-9915-a4de61393fdd)

### OS Info

Windows 10 22H2

### Floorp Version

11.0.0 Beta

### Additional context

In firefox this behavior of pinned tabs does not occur.

**Comment by surapunoyousei** [comment]
relate to Workspace

**Comment by surapunoyousei** [comment]
It's not a big problem and I'll fix it when I get around to it.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/9b49914f888eb44e1edb7982865f77c18383a3fb

Fixed
