### ISSUE TITLE
[Bug] タイトルバー左端にnullと表示されることがある

### ISSUE THREAD

**Issue by kometchtech** [Floorp-Projects/Floorp#317]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

タイトルバー左端に「null」と表示されることがあります。

### To Reproduce

再現性が難しいのですが、一番発生確率が高いのは、
1. Floorpを起動したままPCをスリープする。
2. PCをスリープから復帰させる
3. Floorpを表示させるとタイトルバー左端にnullと表示されます。

Floorpを起動していなくても、nullが表示されることもあります。

### Expected behavior

nullと表示されない。

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/e7f99727-5fec-46b1-bab9-ad6c8c659f38)

### OS Info

Windows 11 22H2

### Floorp Version

11.0.0

### Additional context

- ワークスペース機能は有効にしていない
- デザインはFirefox Protonを使用している
- 垂直タブを利用している

**Comment by surapunoyousei** [comment]
なるほど。確かに発生することが確認できました。修正しますね

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/2cf4a2769c4ef28985e5cba23c2f1d3439f98bed

プッシュしました。直ると思います

**Comment by kometchtech** [comment]
ご対応ありがとうございます。
先ほど自動更新を適用し、一旦PCをスリープ、解除してみた限りでは大丈夫のようでした。

**Comment by surapunoyousei** [comment]
ありがとうございました
