### ISSUE TITLE
Support for the RPM format. Mainly openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Henkire** [Floorp-Projects/Floorp#318]
### Is your feature request related to a problem?

Its not really related to a problem. Its more of a request. 

### Describe the solution you'd like

I was wondering if it would be possible to provide a port to the RPM file format. Mainly for openSUSE Tumbleweed but with support for Fedora as well. Perhaps this could be achieved with the full release of Floorp 11

### Describe alternatives you've considered

If a build system is needed, you could use Open Build Service. It may even help and ease the transition to build a .spec file for openSUSE and Fedora. 
https://build.opensuse.org/ 

### Additional context

I don't really like to fully rely on flatpaks because I would love to do system integration with RPM packages. Its a preference, but I'm sure this would help others. 
Thank you.

**Comment by surapunoyousei** [comment]
Interesting. But, I'm not specialized in RPM package I need support about this.

**Comment by Henkire** [comment]
RPM packages are built using a .spec file and arguably would be easier to build then deb files.
You could use the firefox .spec file from both Fedora and openSUSE as a reference. OpenSUSE Tumbleweed has some KDE integration patches. 
https://build.opensuse.org/package/show/mozilla:Factory/MozillaFirefox 
https://koji.fedoraproject.org/koji/rpminfo?rpmID=35232449 

Open Build Service itself is amazing in my honest opinion. You could use it to even build deb files. It supports building Fedora packages, openSUSE packages, Debian along with Ubuntu and even flatpak and appimage support. And even Arch Linux.

Here's the documentation about it. https://openbuildservice.org/help
These links may help with RPM packaging.
https://rpm-packaging-guide.github.io/#hello-world
http://ftp.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html

**Comment by surapunoyousei** [comment]
It look like build from source. Hmm...

**Comment by Henkire** [comment]
Yes, it does build from source. But the entire project can be uploaded either as a tar.gz or tar.xz file in Open Build Service and the .spec file can build from that. Its done remotely.

**Comment by surapunoyousei** [comment]
It's like GHA.

I don't want to add any more areas to maintain, so we'll have to look into something better.

**Comment by Henkire** [comment]
Alright, thank you. I understand.

**Comment by Henkire** [comment]
Maybe Github Actions supports RPM package building. I'm not sure how that works though.

**Comment by ludg1e** [comment]
Hello,

It'd still be interesting to support this, as Flatpak has its limitations.
I don't know for openSUSE, but in Fedora you could publish the package in three diferent places:
- Fedora repos
- Fedora COPR (like AUR in Arch Linux)
- A third-party repo like [Terra](https://terra.fyralabs.com/)
