### ISSUE TITLE
[Feature Request] Implement function to change default workspace's name

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#319]
### Is your feature request related to a problem?

Currently default workspace cannot be renamed.

### Describe the solution you'd like

I think you can add a edit button at the right of the default workspace menu instead of blank

**Comment by surapunoyousei** [comment]
I will add this feature on Floorp 11.1.0

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/5a3ac6a6c7e372a16a3a7d1ec71c2d3e7a967b26
