### ISSUE TITLE
Enable ECS EDNS Client Subnet

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#320]
### Is your feature request related to a problem?

Hi, i use the great Quad9 dns that block malware and even the bad crypto-mining and i need no more antivirus ! and Quad9 has a version with ECS EDNS Client Subnet enabled and then, the dns becomes more faster,  and i discover ECS EDNS Client Subnet is sadly not enabled by default in web browser, it will be great to add option to enable quickly ECS EDNS Client Subnet, tahnk you veru much :)

### Describe the solution you'd like

Enable EDNS Client Subnet for faster dns

**Comment by surapunoyousei** [comment]
ECS EDNS Client Subnet has privacy issue.  So change default is difficult.

**Comment by surapunoyousei** [comment]
Sending user location to directory is maybe aweful

**Comment by trimechee** [comment]
Hello @surapunoyousei , in the  New Features of Waterfox, it says : 

  "  Waterfox now uses Oblivious DNS by default, a privacy preserving method for DNS queries."



i read I read that activating ECS makes it possible to circumvent geolocation and censorship of ip addresses based on geopgraphical location....apparmament the old ECS is replaced by EDNS ....i think activating EDNS is one of the most great functions to bypass surveillance and censorship and we would no longer need vpn, the ISP and the state can no longer monitor us apparently

**Comment by trimechee** [comment]
Hello @surapunoyousei , what do you think about my discover ? is that really tre and it really works please ? 



"Firefox – Blind your ISP & keep your data safe!

Today I will guide you How to Blind your ISP & keep your data safe!

Protect your privacy. Defend yourself against network surveillance 
and traffic analysis and stop your isp from spying on you.

It’s simple and can be done via Firefox. 
When you enable this, you don’t need a VPN to browse blocked websites, 
It will unlock all domains worldwide.

about:config
esni.enabled
trr.mode
5) Search for “trr.mode”

Double click on it or right click and select Modify.

Set `network.trr.mode` to 2 to make DNS Over HTTPS.
 It will secure your connection and unlock all blocked domain names.

Enter 2 and Click OK!

Note: Try 2 first, if you get error, set trr.mode to 1."

**Comment by trimechee** [comment]
it seems that the amzing ESNI becomes ECH, wu hope that Floorp will add option to enable ECH please : 

Encrypted Client Hello: the future of ESNI in Firefox 
https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/
