### ISSUE TITLE
MPEG-DASH and HEVC/H.265[Feature Request] 

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#321]
### Is your feature request related to a problem?

Hi, may be these features may help to have even more smooth playback compared to many another web browsers that does not have these options enabled :

Experimental MPEG-DASH support

https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) support

and

HEVC/H.265 support on Linux and Windows.

It will be great to have option to activate these features, thank you :)

### Describe the solution you'd like

Enable MPEG-DASH and HEVC/H.265 support

**Comment by surapunoyousei** [comment]
Sorry, H.265 is licensed by  a few compony. Floorp cannot use it.

**Comment by surapunoyousei** [comment]
If we use it, We have to pay lots of money.

**Comment by surapunoyousei** [comment]
Patents such as H264 are not recognized in some countries. Therefore, in those countries, H264 and H265 can be used without permission and without paying.

In Japan, this is not possible, so we are in a situation where we cannot implement it.

If we could, we would be able to improve performance and so on.

**Comment by AKL55** [comment]
> Patents such as H264 are not recognized in some countries. Therefore, in those countries, H264 and H265 can be used without permission and without paying.
> 
> In Japan, this is not possible, so we are in a situation where we cannot implement it.
> 
> If we could, we would be able to improve performance and so on.

Forgive me for my ignorance but, Is it not possible to just make a way for us users to add the H.265 support ourselves?
Like we can with other projects like: https://github.com/saschanaz/jxl-winthumb or Okular

**Comment by AKL55** [comment]
I remember testing Floorp-12 beta and it played HEVC just fine.
Hope it stays in the final version.
