### ISSUE TITLE
[Bug] ワークスペースを有効にしてもタイトルバー左端にアイコンが表示されない

### ISSUE THREAD

**Issue by kometchtech** [Floorp-Projects/Floorp#322]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

設定からワークスペース機能を有効にしてもタイトルバー左端にアイコンが表示されない

### To Reproduce

1. 設定から「ワークスペース機能を有効にする（実験的）」を有効にする
2. すぐに反映される認識だが、タイトルバー左端にアイコンが表示されない

### Expected behavior

タイトルバー左端にワークスペースのためのアイコンが表示される

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/ed2b3ad1-e45c-4c43-b024-9fc3d912e445)
![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/5e580290-ac5a-4ecb-ab57-60055302c41e)

### OS Info

Windows 11 22H2

### Floorp Version

11.0.0

### Additional context

#317 を依頼した際に関連している？

- デザインはFirefox Protonを使用している
- 垂直タブを利用している

**Comment by surapunoyousei** [comment]
多分ですが、ベータ版のバグの影響でワークスペースが正しく起動してない可能性が高いと思います。

about:config で、ワークスペース関連の設定を初期状態に戻す必要があります。(今後自動化すべきですね。)

floorp.browser.workspace.current
floorp.browser.workspace.all
floorp.browser.workspace.tabs.state

この3つを初期化してください

**Comment by kometchtech** [comment]
> floorp.browser.workspace.current
> floorp.browser.workspace.all
> floorp.browser.workspace.tabs.state
> 
> この3つを初期化してください

案内ありがとうございます。
提示いただいた操作を実施し、Floorpを再起動したところアイコンが表示されるようになりました。
お手数をおかけいたしました。

**Comment by surapunoyousei** [comment]
良かったです
