### ISSUE TITLE
Disable containers feature Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#323]
### Is your feature request related to a problem?

Hello, i would like to keep my browser the most light possible so i disable every option and feature i don't use, i can't find in Floorp seting option to disable containers Firefox Multi-Account Containers, it will be great to add option to disable this feature, thank you :)

### Describe the solution you'd like

Disable containers

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/6e88ff21-b0b8-4cd8-9181-a75f4f8cb306)

**Comment by trimechee** [comment]
sorry, I forgot to answer, the "enable container" button is grayed out and therefore we cannot deactivate this option

**Comment by surapunoyousei** [comment]
If you install addon that depends on Container, You cannot disable it

**Comment by surapunoyousei** [comment]
if you want to force disable, privacy.userContext.enabled change this key. Maybe break addons

**Comment by surapunoyousei** [comment]
Hmm。

**Comment by trimechee** [comment]
Yes, all extenson are disabled however we can't disable containers :( i will try your trick privacy.userContext.enabled , thank you

**Comment by surapunoyousei** [comment]
Ok

**Comment by trimechee** [comment]
Now i verifiy, firefox last version, the default value of privacy.userContext.enabled  is false, so even mozilla disbale containers by default

**Comment by trimechee** [comment]
Ahh, now everything is explained :)

**Comment by trimechee** [comment]
@surapunoyousei  and all my congratulations for the new exceptional out standing version ! 💯 🥇

**Comment by surapunoyousei** [comment]
I would like to hear it! Cheer!
