### ISSUE TITLE
Tanslation function settings doesn't work 

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#324]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Hello, Tanslation function settings doesn't work , nothing happens when i click in this setting 

### To Reproduce

1-Go to Tanslation function settings

### Expected behavior

Show options of Tanslation function settings

### OS Info

Windows 10 22H2 last version

### Floorp Version

v10.16.0

**Comment by surapunoyousei** [comment]
Translation settings will not function without the add-on present.

It will be turned off in Floorp 11, so don't worry about it.
