### ISSUE TITLE
マウスのホイール長押しでのスクロール

### ISSUE THREAD

**Issue by newmomizi** [Floorp-Projects/Floorp#325]
### Is your feature request related to a problem?

マウスホイールを押しながらマウスを上下左右に動かしたときのスクロールが使えず、ページを高速でスクロールさせたいときに困っています。

### Describe the solution you'd like

マウスホイールを押しながらマウスを上下左右に動かしたとき、その方向へスクロールするようにしてほしいです。

### Describe alternatives you've considered

キーボードのPage Up、Page Downキーを使用して操作する
→いちいちマウスから右手を離すのが面倒

### Additional context

この機能は通常のFirefoxにも搭載されていましたが、それがFloorpで使えないのは意図的な仕様なのか、バグなのか、私には判断できません。
もしこれが意図的な変更なのであれば、大変申し訳ありません。

**Comment by surapunoyousei** [comment]
バージョンは何でしょうか？

**Comment by newmomizi** [comment]
Daylight v11.0.0 (20230727090534)です

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/70652298-caba-4999-b04c-1f8da5382bcb)
私の環境では可能です。一度新しいプロファイルでテストしてしていただけますか？

**Comment by newmomizi** [comment]
すみません、「自動スクロール機能を使用する」の設定を知らぬ間にオフにしてしまっていたことが原因でした。
オンにすることで使用できるようになりました。ありがとうございます

**Comment by surapunoyousei** [comment]
👍
