### ISSUE TITLE
[Bug] (Floorp 11 Beta) Blurry Page After Widening the Browser Window

### ISSUE THREAD

**Issue by chrisliu298** [Floorp-Projects/Floorp#326]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

On macOS, everything on a page (not including the tabs bar and sidebar) become blurry when the browser window is set to be wide enough, beyond some constant threshold.

Here is [a video](https://mega.nz/file/ceEF3B7J#iQXb2fSsZ0dm8-T4Vo2IXtOMkKHDRCjiO13ZNKbNOl0) that demonstrates the bug.

### To Reproduce

1. Drag the right (or left) border of the browser window so that it becomes wider.
2. When the width of the browser window exceeds some threshold, everything on the current page becomes blurry.

This might not occur on a laptop screen unless it has high resolution. It's more likely to reproduce this on an external display.

### Expected behavior

The rendering of the page should not be affected by how wide the browser window is.

### Screenshots

Blurry:

![2023-07-30 at 08 34 26@2x](https://github.com/Floorp-Projects/Floorp/assets/59010212/f2ef5e34-432a-45fb-a17a-7a2a92fecef9)

Normal:

![2023-07-30 at 08 34 17@2x](https://github.com/Floorp-Projects/Floorp/assets/59010212/3907a8c7-a19b-49ef-b4a5-5c81f9a6b27a)

### OS Info

macOS Sonoma 14.0

### Floorp Version

11.0.0

### Additional context

This does not occur in Floorp 10.16.0.

**Comment by surapunoyousei** [comment]
On my Mac (M1 2020 Mac mini), I cannot found the bug. Please try on Firefox ESR115?

**Comment by chrisliu298** [comment]
Thanks for the quick response. I tried Firefox ESR115 and did not encounter this issue. I also double-checked Floorp version 10.16.0 and it showed normal font too. This started to happen after I updated to version 11.

**Comment by surapunoyousei** [comment]
Ok..

Plz tell me about your Mac

**Comment by chrisliu298** [comment]
I also just realized that this won't occur if the scaling of the display is not large enough. Can you try switching to a different scaling (with higher resolution and more space) in System Settings -> Displays?

For me, the problem occurs for all resolutions higher than 2560x1440 but not for 1920x1080.

**Comment by surapunoyousei** [comment]
OK.

I have no 2560x1440 or later size of Mac (

Icannot fix it.

**Comment by chrisliu298** [comment]
I see. Looks like it might require a 4K monitor to reproduce this issue, because it occurs to all resolutions higher than the one shown below, and does not happen for the smallest one.

![2023-07-30 at 14 46 25@2x](https://github.com/Floorp-Projects/Floorp/assets/59010212/89f9ff6f-fa51-4f5b-93bf-72f8b6c262d7)

For now, I'll wait to see if this problem also occurs to other people who use external displays and use it as is. Thanks anyway!

**Comment by surapunoyousei** [comment]
Thanks for the info. I will continue to investigate and will write if there is any progress.

It doesn't seem to be that big of a problem.

**Comment by chrisliu298** [comment]
Update: I found what was causing the blurry rendering issue.

In settings, when "Round up Floorp's corners" is enabled, the blurry problem occurs immediately. When the round corners are disabled, everything is rendered perfectly.

I don't know why it is the case, but this does fix the issue.

**Comment by surapunoyousei** [comment]
I will disable the option next version

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/bb8fdb152959aa5f2cfad732bca7ef67714a5c88

Disabled

**Comment by Benp248** [comment]
I still see this same issue when using the rounded corners option with higher resolutions (Though I am on windows) is this something that is planned to be fixed in a later version? 

System Information:
- Floorp 11.21.0 (64-bit)
- Windows 11 Ver 24H2 (OS Build 26100.2314)
