### ISSUE TITLE
[Feature Request] include ublock origin as default addon again

### ISSUE THREAD

**Issue by slrgt** [Floorp-Projects/Floorp#327]
### Is your feature request related to a problem?

ublock origin is an amazing addon that protects people from ads with viruses on search and many websites. It also increases speed and protects privacy of user.

### Describe the solution you'd like

ublock origin as default addon on this amazing browser :)

**Comment by surapunoyousei** [comment]
In fact, I didn't review addons. ex) uBlock Origin, Gesturefy. 

Waterfox developer of Mr.Alex said me about this, "This is security risk" I agree this opinion.

system-add-on cannot get the fastest update but, Pre-install addon cannot review update. I cannot do it.
