### ISSUE TITLE
[Bug] Disabling Rounded Corners leaves white boarder

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [Floorp-Projects/Floorp#329]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Disabling Rounded Corners leaves white boarder around the page

### To Reproduce

install the new stable version 11.0.0

### Expected behavior

it shouldn't have this border around the page

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/7858946/1322d4ee-e27b-4cac-adca-21d0cf76cdcf)
![image](https://github.com/Floorp-Projects/Floorp/assets/7858946/5387c22c-b383-4239-b75a-0b3a64dc56d1)
![image](https://github.com/Floorp-Projects/Floorp/assets/7858946/2f2c4b8e-11bd-49bf-adc5-93303ae7fec0)

### OS Info

windows 11

### Floorp Version

11.0.0

**Comment by surapunoyousei** [comment]
I will disable it 11.0.1

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/bb8fdb152959aa5f2cfad732bca7ef67714a5c88

**Comment by ahmed-abdelrazek** [comment]
that didn't fix my issue it's not just in full screen videos it's in every page 
you see this white-ish border around the page when you keep `Round the corners of pages` enabled

![image](https://github.com/Floorp-Projects/Floorp/assets/7858946/1aa9f385-c679-46c9-87c6-88353585dbc3)
![image](https://github.com/Floorp-Projects/Floorp/assets/7858946/c1d6d768-1291-4131-af59-835bd978b653)

when you disable the option the borders will still be there (without the rounded corners) around the web page

will be more visible when the browser is using dark theme and its window maximized and on websites with dark theme (like github)
will be harder to notice if the browser and the website are using light theme or the window is not maximized 
will not be visible in the browser settings page or in the new tab page

**Comment by surapunoyousei** [comment]
Floorp 11.1.0 doesn't resolve it?

**Comment by surapunoyousei** [comment]
The option makes white border is especificación

**Comment by ahmed-abdelrazek** [comment]
> The option makes white border is specification

for when the rounded corners are on only or both on/off?

**Comment by surapunoyousei** [comment]
Default, There is 1px border still alive there. It's specification
