### ISSUE TITLE
[Feature Request] easy profile management and switching like chrome and edge

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [Floorp-Projects/Floorp#330]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

i would like to see https://github.com/null-dev/firefox-profile-switcher-connector integrated into the browser or a similar solution like in chrome for easy profile switching

**Comment by surapunoyousei** [comment]
Toolbar button ?

**Comment by ahmed-abdelrazek** [comment]
> Toolbar button ?

in a nutshell, yes

**Comment by surapunoyousei** [comment]
I made it. If I have free time

**Comment by dominichayesferen** [comment]
unstaling bump

**Comment by surapunoyousei** [comment]
Hmm...

I think this feature can be created. But, My energy is missing.

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/3108f825-f997-415e-ab32-c93d767cde21)

**Comment by dominichayesferen** [comment]
tbh once done this would probably be a worthy replacement for the Firefox Sync button on the toolbar by default.

**Comment by surapunoyousei** [comment]
maybe. 

I will integrate Firefox sync

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/7db99980-3bda-41a5-a16e-dd626d9ee3eb)
