### ISSUE TITLE
[Bug] macOS close, minimize, and maximize buttons shifted in Lepton UI

### ISSUE THREAD

**Issue by chrisliu298** [Floorp-Projects/Floorp#334]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The close, minimize, and maximize buttons in macOS are all shifted to the top when enabling "Hide tabbar" with Lepton UI.

### To Reproduce

1. In Settings -> Design, select Firefox Photon・Lepton UI
2. Go to Lepton Preferences and click "Hide tabbar"

### Expected behavior

The close, minimize, and maximize buttons stay in the middle of the navigation bar (vertically), where they usually are.

### Screenshots

![2023-07-31 at 08 13 16@2x](https://github.com/Floorp-Projects/Floorp/assets/59010212/59b11baa-0295-4fd4-a559-78571cf57818)

### OS Info

macOS Sonoma 14.0

### Floorp Version

11.0.0

**Comment by surapunoyousei** [comment]
11.2.0 で修正されるかもしれません。Daylight チャンネルでテストします

**Comment by surapunoyousei** [comment]
私の環境では修正されました。アップデートをお待ちください
