### ISSUE TITLE
[Bug] Rounded Corners leaves border in fullscreen videos

### ISSUE THREAD

**Issue by TheLich132** [Floorp-Projects/Floorp#336]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Entering fullscreen in videos leaves white, rounded corner on the upper left corner of the screen and white border on the right side of the screen (visible on the screenshot).
Also disabling rounded corners ends with white, thin border around the screen (second screenshot). This could be related to this issue #329 

### To Reproduce

1. Open any video in fullscreen (eg. YouTube, local video from computer)

### Expected behavior

No borders around the screen

### Screenshots

Rounded corners enabled:
![Screenshot_20230730_171224](https://github.com/Floorp-Projects/Floorp/assets/49432482/0b52a4ed-4a7d-4800-a1d2-95d9e56d6fb0)

Rounded corners disabled:
![Screenshot_20230730_171244](https://github.com/Floorp-Projects/Floorp/assets/49432482/f16e56f4-18ff-4b3f-9aed-92b7e84a76d7)

### OS Info

EndeavourOS

### Floorp Version

11.0.0

**Comment by surapunoyousei** [comment]
I will fix it

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/bb8fdb152959aa5f2cfad732bca7ef67714a5c88
