### ISSUE TITLE
[Bug] Workspaces is oversized, resulting in a softlock, in GNOME Theme

### ISSUE THREAD

**Issue by dominichayesferen** [Floorp-Projects/Floorp#338]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

This image speaks for itself.

![Screenshot_20230731_225712](https://github.com/Floorp-Projects/Floorp/assets/11057934/044f151d-4202-4e24-bc19-94d869629f6c) 

### To Reproduce

1. Go to Design
2. Select GNOME Theme

### Expected behavior

It's... not oversized, thus the browser being actually usable on this theme.

### OS Info

Feren OS 2023.07 Alpha 2, and Feren OS 2023.04

### Floorp Version

FLATHUB - 11.0.0

### Additional context

Is your Firefox-GNOME-Theme version outdated? The profile button is also oversized, and Extensions is using the Firefox icon rather than the GNOME Theme icon, thus why I ask that rhetorically.

**Comment by surapunoyousei** [comment]
Wow. I will fix it

**Comment by surapunoyousei** [comment]
11.2.0 is milestone.

**Comment by surapunoyousei** [comment]
Fixed at 11.1.1
