### ISSUE TITLE
[Feature Request]  Bfcache for recently closed tabs, so if you reopen a closed tab few seconds later, the opening is instantaneously 

### ISSUE THREAD

**Issue by ericpa06** [Floorp-Projects/Floorp#344]
### Is your feature request related to a problem?
I guess it is not a problem per se. But more like a design issue. It's always frustrating when I accidentally close a tab, or when I remember that there were another link or thing I want to see there, and I have to wait for the page to load again. It would be cool if the page remained on cache for a few extra seconds, this way it is instantaneously if you want to see that content again. 

### Describe the solution you'd like

Essentially when you "close the tab", keep the tab hidden away for a few extra seconds, like 5 or 10 seconds, in case you accidentally closed that tab, and only after this time actually remove the tab from memory. If that tab is playing a video, for instance, pause that video immediately _(so you don't have to deal with a 10 seconds delay until that the audios stops playing)_ .

If during this time span you press to restore the tab, the feature just bring it back without having to reload the page (pretty useful if you were on some heavy page). This feature was tested on some chromium browsers , and there is a bugzilla report to implement it:

https://bugzilla.mozilla.org/show_bug.cgi?id=1655199

### Describe alternatives you've considered

I'm tried to play a little bit with scripting  and implement this through that manner, but I have no skills for doing that. Also, I think this can't be implement with run of the mill extensions.

### Additional context

I guess there isn't any more context. I hope my description was clear and I that I describe the suggestion good enough.

And thank you very for making such a wonderful browner.

**Comment by surapunoyousei** [comment]
I don't think it is possible. It would require major changes on the back end, which I don't have in mind.

**Comment by ericpa06** [comment]
Well, thank you very much anyway. I imagined it would probably be something pretty complex to implement, involving a lot of work under the hood. Thank you for your reply; I truly appreciate your time and attention.

**Comment by surapunoyousei** [comment]
Sorry.
