### ISSUE TITLE
[Feature Request] TODOs to organize build actions

### ISSUE THREAD

**Issue by nyanrus** [Floorp-Projects/Floorp#345]
### Is your feature request related to a problem?

ビルドファイルの再利用がよくできていない。

### Describe the solution you'd like

ビルドファイルの整理
- [x] #328 daily buildとdeploymentで既存の個別ビルドを再利用する。
- [x] linuxビルドでdebとdeb-ppaビルドをflatpackみたいに別実行に切り出す。
- [x] linuxビルドでflatpackをもっと使いやすくする。

**Comment by surapunoyousei** [comment]
flatpak と DEB はメンテナーが違うので全然わかりません

**Comment by nyanrus** [comment]
debはuntarして再パッケージしてるように見えて、
flatpackはdebと違って別のactionなので、debの感じ（上記）に加えてtarのurl要求してる感じです。

**Comment by surapunoyousei** [comment]
メンテナーの差が出ているので何とも言えませんが、やる気あるときに同じ仕様にしますね

**Comment by typeling1578** [comment]
> flatpackはdebと違って別のactionなので、debの感じ（上記）に加えてtarのurl要求してる感じです。

これ、わざわざFloorp-Projects/FloorpのGitHub Actions上でこの作業をする必要があるのか疑問なんですよね。
Flatpakのビルド時に同じ作業をすれば済む気がしてます。
時間がある時にやってみます。

**Comment by surapunoyousei** [comment]
終わり

https://github.com/Floorp-Projects/Floorp/commit/2afa9447ea5815cf7c99549d2a126dced5385bba

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/actions/runs/5753909443/job/15598076490

**Comment by typeling1578** [comment]
Flatpakのほうができてないので再オープンしますね

**Comment by typeling1578** [comment]
https://github.com/flathub/one.ablaze.floorp/tree/devel
Floorp-Projects/FloorpのGitHub Actionsで行っていたものをこちらに統合してみました。

**Comment by nyanrus** [comment]
Mergeされたので閉じます。

**Comment by surapunoyousei** [comment]
後は任せとき
