### ISSUE TITLE
[Feature Request] Use custom icons for workspaces

### ISSUE THREAD

**Issue by ecspresso** [Floorp-Projects/Floorp#346]
### Is your feature request related to a problem?

I want to use custom icons for my workspaces, it gives feels nice and gives a quicker overview when I am looking for a specific workspace.

### Describe the solution you'd like

I would like to be able to set the icon from a file on my computer.
I would right click the workspace and there would be an option to change the icon.

### Describe alternatives you've considered

SimpleTabGroup is an addon with similar functionallity but since I am now trying Floorp instead of Firefox, I would prefer to use the native solution.

**Comment by surapunoyousei** [comment]
Floorp 11.1.0 will make it available

**Comment by surapunoyousei** [comment]
Try beta version. You can check the feature
https://github.com/Floorp-Projects/Floorp/releases/download/beta/floorp.en-US.win64.installer.exe

**Comment by AKL55** [comment]
> Try beta version. You can check the feature https://github.com/Floorp-Projects/Floorp/releases/download/beta/floorp.en-US.win64.installer.exe

Would it be possible to have more icons available, or perhaps the option to add custom local icons? I have a Workspace named 'Music,' but unfortunately, there are no Music icons available at the moment.

I would use icons from this website here https://pictogrammers.com.

Additionally, I have a quick question: Is there any way to prevent the Workspace from being deleted if I close all tabs?

**Comment by creeper-0910** [comment]
Please open a new issue.

**Comment by Hate9** [comment]
Shouldn't this issue not be marked as completed? From the text, it appears that it always referred to adding custom icons from the user's filesystem to the workspaces, not just the ability to choose icons.
