### ISSUE TITLE
[Feature Request] Add option to hide lepton icons in context menus only

### ISSUE THREAD

**Issue by Sollace** [Floorp-Projects/Floorp#347]
### Is your feature request related to a problem?

This is relating to the feature requested in #281 which was to add an option to hide the context menu icons. 

While I appreciate the option that was added, that is the same as what Waterfox already has, it isn't really what I was asking for in the original issue. I asked for a toggle for the `userChrome.icon.menu` because that lets you turn off the context menus without affecting the dock.

### Describe the solution you'd like

I have attached a video that I hope can make it a little clearer what I mean.

https://github.com/Floorp-Projects/Floorp/assets/6429283/4babd775-fe2e-49ca-bcbe-02a833773c73

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/843f7383-fae6-4781-971d-41c110dcb706)

This is same option

**Comment by Sollace** [comment]
No it is not

**Comment by Sollace** [comment]
The option you added hides context menus and the dock.

The option I wanted was for context menu only.

**Comment by Sollace** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/6429283/3c2f4e1d-e9e9-4792-bcd3-547a50e6361e)

**Comment by Sollace** [comment]
Again, it's `userChrome.icon.menu` ***NOT*** `userChrome.icon.disable`.

These are different things. The flag you added is not what I asked for.

**Comment by surapunoyousei** [comment]
Ok. I will add it

**Comment by Sollace** [comment]
Thank you ^-^'

**Comment by surapunoyousei** [comment]
I don't know how it works, so please tell me what to do with the setting name

**Comment by Sollace** [comment]
It works the same as in https://github.com/Floorp-Projects/Floorp/commit/3588650021d312636ef06848a6c23dc1be00b278

preference="userChrome.icon.menu"

And:

true = with icons
false = no icons

For the label maybe "Enable context menu icons"?

Thank you again. Sorry if I sounded harsh.

**Comment by surapunoyousei** [comment]
OK
