### ISSUE TITLE
[Bug] 前回終了直前に閉じていたタブが復元されてしまう。

### ISSUE THREAD

**Issue by pice5** [Floorp-Projects/Floorp#348]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

前回終了直前に閉じていたタブが起動時に復元されてしまう。

### To Reproduce

1. about:preferences を開く
2. 「一般」→「起動」→前回のウィンドウとタブを開く(S)を有効にする
3. 「デザイン」→「タブスタイル」→垂直タブ(実験的)を有効にする
4. 適当なサイトを開く（ここではyoutubeで行いました)
5. 動画一覧から適当な動画を2つ、中クリックで新しいタブへ開く
6. 新しいタブに開いた2つのタブを中クリックで閉じる
7. ウインドウ右上の×ボタンでブラウザを閉じる
8. 再度floorpを起動する
9. 閉じたはずの2つのタブが復元されてしまう

### Expected behavior

水平タブを有効にしている状態だと発生しないので、垂直タブ時のタブ挙動がおかしいと思われます。

### OS Info

Windows 11 22H2

### Floorp Version

11.1.0

**Comment by surapunoyousei** [comment]
11.0.0 で発生しました？

**Comment by pice5** [comment]
11.0.0でも再現しました。

**Comment by surapunoyousei** [comment]
巡回したんですけど想像の２０倍面倒な気がするので直せれば直します

**Comment by surapunoyousei** [comment]
TST は今でも使えるので気に入らなかったらそちらをご使用ください

**Comment by surapunoyousei** [comment]
何とかなるかもしれないです

**Comment by pice5** [comment]
よろしくお願いします

**Comment by surapunoyousei** [comment]
タブ３つが何らかの問題で閉じることをリッスンされていないようです。３つ目以降は問題が発生しないことがわかりました。

該当コードを詳しく精査しないといけないので問題の解決には時間がかかるでしょう。致命的ではないのでゆっくりコードを調べたいと思います・

**Comment by surapunoyousei** [comment]
この問題の解決が進行中です。

垂直タブの実装を１から書き直すことで解決を図っています

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/f2327247-6d81-41ba-b96a-1fde57946c53)

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp-core/pull/3

**Comment by surapunoyousei** [comment]
今後、このバグの遭遇率は減ると思いますが、まだ残っている可能性もあります。ピン止めして閉じます。

**Comment by BarbzYHOOL** [comment]
I also have several tabs randomly restored at startup and I use vertical tab bar (I didn't read the rest of the issue because my translation extension is not working right now)

**Comment by BarbzYHOOL** [comment]
I have another issue with vertical tabs: when I ctrl+tab to switch to a tab, it does not bring the scrollbar to the tab position
It should be like that (or an option to enable).
Example: you have 100 tabs open (lol), then you move all the way back up. You click one tab at the top. Then you Ctrl+Tab for quick switching to the last tab you were viewing. The scrollbar does never go down, so you have to use your mouse again to scroll the bar down.
This probably doesn't happen with horizontal tabs (it didn't happen on firefox at least)

**Comment by surapunoyousei** [comment]
完全解決できました。
