### ISSUE TITLE
[Bug] Can't set Floorp as my default browser?

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [Floorp-Projects/Floorp#350]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Floorp does not show up in my settings app. and when i try to set it manually, it doesn't show up in the HTTP & HTTPS section... I tried setting a different browser as default and uninstalling it, then clicking on a link, but Floorp didn't show up in the selection menu. i've tried everything, but i can't seem to make it my default browser. can you help?

### To Reproduce

1. Install Floorp
2. Try to set it as a default browser.
3. **fail.**

### Expected behavior

For Floorp to show up when changing my default browser.

### Screenshots

![Screenie](https://github.com/Floorp-Projects/Floorp/assets/123305689/9a96b990-ce4f-4ce6-b7ac-6aa176ca07da)
![Screenie2](https://github.com/Floorp-Projects/Floorp/assets/123305689/ac3e946e-27f5-4b4f-b583-7ae73fc53542)

### OS Info

Windows 11 2H22

### Floorp Version

v11.1.0 (latest)

**Comment by surapunoyousei** [comment]
What？

**Comment by surapunoyousei** [comment]
Do you use Portable version of Floorp?

**Comment by TeaEndsAcronyms** [comment]
I used this file. Is this the portable version?
![Screenshot_20230806-130225~2.png](https://github.com/Floorp-Projects/Floorp/assets/123305689/194bb0ad-f462-485e-8fbc-10da15f70c35)

**Comment by surapunoyousei** [comment]
No, I see. I will check it on Virtual machine environment.

**Comment by TeaEndsAcronyms** [comment]
Thanks for trying to help!

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/9f1d069e-0f73-4f43-b0fe-151905a44c21)


Ok It's odd. You can try to fix. Use Hibit Uninstaller or Geek Uninstaller for force uninstall.

**Comment by TeaEndsAcronyms** [comment]
Ok thanks! I'll see if it works.

**Comment by TeaEndsAcronyms** [comment]
Just reinstalled it and it worked! Thank you!
