### ISSUE TITLE
[Bug] WebGL not loading

### ISSUE THREAD

**Issue by Inklingboiii** [Floorp-Projects/Floorp#351]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Websites that use Three.js/WebGL don't load correctly.
Console messages: 
`WebGL warning: \<Create>: AllowWebgl2:false restricts context creation on this system. [three.module.js:28221:27](http://localhost:42069/node_modules/three/build/three.module.js)
Failed to create WebGL context: WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system. () [three.module.js:28221:27](http://localhost:42069/node_modules/three/build/three.module.js)
THREE.WebGLRenderer: A WebGL context could not be created. Reason:  WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system. ()`

Note: I've also looked in the settings and made sure that I didn't disable WebGL. Additionally I compared the about:config with regular firefox (where it's working normally) and I didn't see any differences when looking for webgl settings

### To Reproduce

1. Go to any website with WebGL (e.g https://bruno-simon.com/)
2. Notice that no WebGL is loading
3. Look at the error messages in the console

### Expected behavior

I expected the WebGl to load correctly.

### Screenshots

![Bildschirmfoto vom 2023-08-06 23-59-03](https://github.com/Floorp-Projects/Floorp/assets/69518450/ba653c61-d7bd-4f27-a933-b2743985baf6)

### OS Info

Linux Mint 21.2 x86_64

### Floorp Version

11.1.0

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/ee7329c9-d823-448f-8427-5378bc5574fc)

Did you install user.js ? & Check this option

![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/99699775-b38f-4485-9ffb-08d0b8e2515b)

**Comment by Inklingboiii** [comment]
![grafik](https://github.com/Floorp-Projects/Floorp/assets/69518450/5b6638e2-8dd5-4b54-9fa4-c2c374d052a0)
I tried turning this option on and off and in both cases it didn't load.
I also didn't install any user.js

**Comment by Inklingboiii** [comment]
I tried that just now and it worked for some reason! Thanks alot^^
