### ISSUE TITLE
[Bug] Cannot close the window when closing the only tab in it

### ISSUE THREAD

**Issue by itsmohmans** [Floorp-Projects/Floorp#353]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When trying to close the only tab in the window either via <kbd>Ctrl</kbd> + <kbd>W</kbd> or clicking on the `x` button, instead of closing the tab and the window, it closes the tab and opens a new tab in the window, and therefore the window is still open.

### To Reproduce

1. Open a new window
2. Try to close the window by closing the tab either by using <kbd>Ctrl</kbd> + <kbd>W</kbd> or clicking on the `x` button on the tab.
3. The window won't close, you'll have to close it manually by clicking on the window's `X` button.

### Expected behavior

The window should close automatically when you close the only tab in it. That's the expected behavior in Firefox and Chromium-based browsers.

### OS Info

Manjaro Linux

### Floorp Version

11.1.0

**Comment by creeper-0910** [comment]
This is not a bug but a specification.

**Comment by creeper-0910** [comment]
To disable this behavior, set "browser.tabs.closeWindowWithLastTab" to true.
