### ISSUE TITLE
[Bug] (Daylight 11.1.1)「ワークスペースを追加」ボタンが反応しない

### ISSUE THREAD

**Issue by menndouyukkuri** [Floorp-Projects/Floorp#357]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

ワークスペースのポップアップにある「ワークスペースを追加」ボタンと、ブラウザーマネージャーサイドバーにある [+] ボタンが反応しない。

### To Reproduce

1. ワークスペースのポップアップを開く
2. 「ワークスペースを追加」ボタンを押す

または

1. ブラウザーマネージャーサイドバーから [+] ボタンを押す

### Expected behavior

新しいワークスペースの名前を決めるためのダイアログボックスが表示される。

### OS Info

Windows 10 / 11 22H2

### Floorp Version

Daylight 11.1.1

**Comment by surapunoyousei** [comment]
ブラウザーコンソールの出力はありますか？

**Comment by menndouyukkuri** [comment]
これであってますか？
![スクリーンショット 2023-08-08 133700](https://github.com/Floorp-Projects/Floorp/assets/61068665/7c0cc729-8122-4967-a342-af2fc1027b1b)

**Comment by surapunoyousei** [comment]
解決しますね
