### ISSUE TITLE
[Enhancement] Please apply rounded corner to verticaltab box

### ISSUE THREAD

**Issue by Marin-Kitagawa** [Floorp-Projects/Floorp#361]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I am using the experimental vertical tab bar. I really like how it has been changed to native vertical tab bar instead of using an add-on. However, I also enabled the rounded corners. But the web page view has rounded corners while the tab bar still retains the sharp corners. Also, the color contrast is obvious between the other sections and the tab bar unlike Microsoft Edge. I am using Microsoft Fluent UI theme. As you can see, the tab bar is black and the rest is gray. Also, the corners of the tab bar is not rounded. I know that the vertical tab bar is mentioned as experimental. So, I don't know if this issue should be a bug or a feature request

![image](https://github.com/Floorp-Projects/Floorp/assets/49131888/f3ab2720-4251-4c8a-b4b3-9ec03d1b7ed4)

### To Reproduce

1. Open Floorp
2. Enable Vertical Tab Bar
3. Use Microsoft Fluent UI theme
4. Enable rounded corners
5. Now, the tab bar color will be different from the rest and the corners of the tab bar won't be rounded unlike the rest

### Expected behavior

Tab bar must have the same color as the rest and it must have rounded corners

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/49131888/5550bb66-1981-4f56-81cc-991e2dfe95e3)

### OS Info

Windows 11 22H2

### Floorp Version

11.1.0

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/00c69147-623d-4f55-9653-d65d05fb3984)

https://github.com/Floorp-Projects/Floorp/commit/7e17b673afbcdb39d63a121bc3a58c4c7f10832b
