### ISSUE TITLE
[Bug] Client-side decoration titlebar buttons are not rendered in GNOME Theme

### ISSUE THREAD

**Issue by dominichayesferen** [Floorp-Projects/Floorp#365]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

In the GNOME Theme, the expected Adwaita-esque titlebar buttons are nowhere to be seen - in fact, no titlebar buttons whatsoever are even present. 

### To Reproduce

1. Turn off the titlebar if on
2. Switch to GNOME theme

### Expected behavior

LibAdwaita-styled titlebar buttons will appear on the window

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/11057934/0451f496-c82f-4bba-95a7-2ed0a3d75e4b)

### OS Info

Feren OS 2023.04

### Floorp Version

11.1.0 (Flathub)

**Comment by surapunoyousei** [comment]
I've confirmed that it's buggy, so I'll fix it.
