### ISSUE TITLE
[Bug] Merged Toolbar and Tabs Bar (in Lepton) has oversized address bar

### ISSUE THREAD

**Issue by dominichayesferen** [Floorp-Projects/Floorp#366]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The Floorp address bar is too wide on this mode, causing the toolbar buttons, and menu, after it to be inaccessible while in this mode.

### To Reproduce

1. Go to Lepton settings
2. Enable Combine Tab Bar and Toolbar

### Expected behavior

The address bar will have a minimum width more fitting of Floorp's minimum window size.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/11057934/b10b0df2-1d42-492c-a543-cf5841b6380b)

### OS Info

Feren OS 2023.04

### Floorp Version

11.1.0 (Flathub)

### Additional context

This looks to be caused by Firefox's built-in feature to ensure the address bar has a specific minimum width value applied to it, irregardless of the bugs it can cause, like this one.

Two fixes I'd have in mind for this are either increase Floorp's minimum window size to compensate for the minimum address bar width (not recommended, given that window, in the above screenshot, filled most of my 1920x1080 screen), or reduce the minimum width value the address bar uses to be accomodating of Floorp's minimum window size (I would, however, slightly increase Floorp's minimum window size while you're at it as Firefox's minimum is far too small to be usable and causes visual glitches without modifications).

**Comment by surapunoyousei** [comment]
This is a Lepton problem, not something that Floorp can solve.

 It doesn't seem like a big deal, so I'll close it as wontfix.
