### ISSUE TITLE
[Bug] 複数ウインドウ下での閉じたタブを開くボタンの不具合

### ISSUE THREAD

**Issue by maju812** [Floorp-Projects/Floorp#370]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

ウインドウを複数開いている際に閉じたタブを開くボタンが特定のウインドウにしか機能しない

### To Reproduce

1.floorpのウインドウを複数開く(ウインドウA,B,C…とする)
2.A,B,Cのどの閉じたタブを開くボタンを押してもAのタブが復元される

### Expected behavior

Aの閉じたタブを開くボタンを押したらAのタブが，Bの閉じたタブを開くボタンを押したらBのタブが復元される．
floorp10では期待された動作をしていました．

### OS Info

Windows 10 22H2, macOS Ventrua 13.5 共に確認

### Floorp Version

11.1.0

**Comment by surapunoyousei** [comment]
垂直タブをお使いですか？

**Comment by maju812** [comment]
はい，垂直タブを使っています

**Comment by surapunoyousei** [comment]
その機能がバグの温床になっているのを把握しているので、近いうちに垂直タブの実装を丸ごと変更するつもりです。

一時的にオフにするか、TST（ツリー型タブ）をご利用ください

**Comment by maju812** [comment]
ありがとうございます．しかし機能オフ，再起動と試しましたが改善はされませんでした．

**Comment by surapunoyousei** [comment]
再現できないですね。。。

新しいプロファイルで試しましたでしょうか？

**Comment by surapunoyousei** [comment]
https://support.mozilla.org/ja/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by honkaiimpact3rd** [comment]
I can confirm to also have this issue on Linux. It started happening after updating from 11.1.0 to 11.1.2. It still happens in a new profile.

**Comment by surapunoyousei** [comment]
could you give me a video.

**Comment by honkaiimpact3rd** [comment]
As in the video, only tabs in the second window are restored, the tabs I closed in the first window don't get restored at all
https://github.com/Floorp-Projects/Floorp/assets/107812489/28ac4b83-fa1a-4130-a3fd-d7bc8f7ff98c

**Comment by surapunoyousei** [comment]
Ok. I see
