### ISSUE TITLE
[Bug] タブバーの設定が反映されない

### ISSUE THREAD

**Issue by poponta1218** [Floorp-Projects/Floorp#374]
### Attention!

- [x] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

水平タブ及び多段タブを有効化している場合、タブバーの設定の5項目のうちどれを選択しても"通常モード（変更なし）"のままになる

### To Reproduce

1. 水平タブor多段タブを有効にする
2. タブバーの設定で"通常モード（変更なし）"以外を選択する
3. 選択した設定が反映されない
4. 再起動すると"通常モード（変更なし）"が選択されている状態に戻る

### Expected behavior

選択したUIの変化が起こる。
Floorp 11.1.0ではUIの変化が起こっていました。
また、Floorp 11.1.1で垂直タブの機能を有効にすると"垂直タブにブラウザーを最適化"と同様のUIの変化が起こります。

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/34686350/4b7031f8-ebed-4b93-9c9d-f039c2102bde)
![image](https://github.com/Floorp-Projects/Floorp/assets/34686350/edd92482-635f-4568-9535-b85fd93d1ddc)

### OS Info

Windows 10 22H2

### Floorp Version

11.1.1

**Comment by surapunoyousei** [comment]
新規プロファイルで試しましたか？

**Comment by surapunoyousei** [comment]
再起動後に発生する場合であれば私のミスなので今直しています

**Comment by poponta1218** [comment]
新規プロファイルで確認したところ、正常な動作が確認できました
また、規定のプロファイルでアドオンを無効にして再起動してみたところ、こちらについても正常な動作が確認できました
なのでアドオン等でJavascriptをいじってるものを調べて、原因の切り分けをしてみます
失礼しました

**Comment by surapunoyousei** [comment]
再起動後に設定が維持されないバグはわたくしたちのほうで解決します

**Comment by poponta1218** [comment]
"Tab Session Manager"という拡張機能を無効にしたところ、設定が反映されるようになることを確認しました。
再起動時がこの拡張機能によって変化していたので、再起動周りで何かあるのかもしれません
ありがとうございます

**Comment by surapunoyousei** [comment]
一応テストして欲しいんですが、タブバーの設定は再起動後に破棄されてしまいませんか？

**Comment by poponta1218** [comment]
そちらは拡張機能に依らず再起動後に破棄されて"通常モード（変更なし）"に戻ってしまいますね

**Comment by poponta1218** [comment]
"Tab Session Manager"で復元させたウィンドウで設定が反映されない現象が起こっているようです。
元々あるA, 拡張機能で復元したBの2つのウィンドウを用意してブラウザを再起動したところ、Aでのみ設定が反映されました。
また再起動後にウィンドウAから拡張機能でウィンドウCを復元するとCでは設定が反映されません。
設定の再起動後の破棄については先程と同様でした。

**Comment by surapunoyousei** [comment]
直りました。

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/9408f4da8b486bf0e829473a6a29e0e7e9295ad4
