### ISSUE TITLE
[Bug, Regression] Firefox View is now slightly oversized in Fluerial UI

### ISSUE THREAD

**Issue by dominichayesferen** [Floorp-Projects/Floorp#376]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

As of Floorp 11.1.1, the Firefox View button is now slightly oversized when using Fluerial UI.

### To Reproduce

1. Make sure Firefox View is on the toolbar
2. Switch to Fluerial UI

### Expected behavior

It's small just like the rest of the toolbar buttons are. 

### Screenshots

![Screenshot_20230813_173310](https://github.com/Floorp-Projects/Floorp/assets/11057934/674781ca-5b53-465c-a75d-c5830a2bffab)

### OS Info

Feren OS 2023.04

### Floorp Version

11.1.2 (Flathub)

**Comment by surapunoyousei** [comment]
Fixed
