### ISSUE TITLE
[Feature Request] Enable ContentScripts on all domains and extension generated pages

### ISSUE THREAD

**Issue by zakius** [Floorp-Projects/Floorp#377]
### Is your feature request related to a problem?

it's really bad for use flow when certain extensions (like mouse gestures) just stop working when certain pages are active

### Describe the solution you'd like

making ContentScripts work on all pages would be a great workaround for a lack of proper browserwide API for these extensions 

### Describe alternatives you've considered

updating FireGestures to work with modern codebase while using Bootstrapped loader would probably be the optimal solution for gestures, but due to lack of sources for some parts of the extension that's unlikely to happen

additionally that wouldn't solve issues with other extensions other people may be experiencing

**Comment by surapunoyousei** [comment]
We have decided not to work on this due to security concerns.

**Comment by surapunoyousei** [comment]
This is also the reason why there are compatibility issues in the past, as a result of making it executable only once, unexpected problems have occurred in the past.

**Comment by zakius** [comment]
this doesn't necessarily have to be enabled by default and can be granted per extension, and allowing extensions screened by AMO to do so would be more secure than injecting code completely bypassing that

but I understand adding that new permission and fixing the compatibility issues would be more work than you're willing to put into a niche

**Comment by zakius** [comment]
I just noticed Gesturefy is somehow mentioned in the settings so using it should provide native experience but it still doesn't work on these pages, can we get proper support of mouse gestures somehow?
