### ISSUE TITLE
[Bug] Floorp not displaying correctly on 5120x1440

### ISSUE THREAD

**Issue by FopseN** [Floorp-Projects/Floorp#378]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Running Floorp on maximize on 5120x1440, the window will get blurry and unreadable,

### To Reproduce

Set Resolution to 5120x1440
Maximize Floorp
Go to any webpage.

### Expected behavior

No blurs in the browser

### Screenshots

![maximize 5120x1440](https://github.com/Floorp-Projects/Floorp/assets/36802449/c404a6bc-2321-4d9e-9fbb-db175edfdbc0)
![How it should be](https://github.com/Floorp-Projects/Floorp/assets/36802449/5f5457a0-d5c9-48e2-b97f-9c7d5c2a87bb)

### OS Info

Win11 22H2

### Floorp Version

11.1.2

**Comment by surapunoyousei** [comment]
What is your PC's GPU? Nvidia?

**Comment by FopseN** [comment]
RTX 3070

**Comment by surapunoyousei** [comment]
https://github.com/Orbmu2k/nvidiaProfileInspector

download this and add "floorp.exe" to the "Mozilla Firefox" profile (編集済)

nvidia GPUs have a special profile for firefox that doesn't recognize forks of firefox

**Comment by FopseN** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/36802449/16cb8fa8-a5fe-4e29-8420-d461d1a99115)
Added it, but the issue still persist.

**Comment by surapunoyousei** [comment]
I don't know. About more... Search the web

**Comment by creeper-0910** [comment]
Does that problem also occur in Firefox?

**Comment by FopseN** [comment]
No, this issue only occurs in Floorp.

**Comment by FopseN** [comment]
Floorp window gets blurry when exceeding 3440x1440 resolution.

**Comment by creeper-0910** [comment]
Turn off hardware acceleration and see if symptoms improve.

**Comment by FopseN** [comment]
Unfortunately, this does not fix the issues.

**Comment by legofanlovessayori** [comment]
also noticed that on my surface plugged into a external monitor on 125% dpi scaling the same issue occurs, but only on the external monitor

most likely dpi related issue

**Comment by FopseN** [comment]
Tested it on Floorp Lightning and it works fine there, so it must be an issue from Floorp after the 11.1.2 version.

**Comment by surapunoyousei** [comment]
Frankly, I don't believe it is on the Floorp side, as I have not added any code to the window that would cause the problem.

Even more so since Lightning shares code with Floorp.
