### ISSUE TITLE
[Bug] Workspace icon size issue

### ISSUE THREAD

**Issue by jojoto** [Floorp-Projects/Floorp#382]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

After the update to v11.1.2 with the Microsoft Fluent UI style and Display Tab Bar underneath the Toolbar activated, the tab bar takes on the size of the workspace image/icon:
![image](https://github.com/Floorp-Projects/Floorp/assets/29695477/bec8a675-31e6-4729-ab5a-09abd0b5aa7b)

With a new profile i have check Floorp Fluerial UI and have similar issue :
![image](https://github.com/Floorp-Projects/Floorp/assets/29695477/4f801218-e118-456d-964e-10a1324d2ebf)

### To Reproduce

1. go to about:preferences#design
2. check Microsoft Fluent UI or Floorp Fluerial UI
3. enjoy big icon

### Expected behavior

Icons size similar to Proton/Lepton UI

### OS Info

Windows_NT 10.0 22621 (windows 11 22h2)

### Floorp Version

11.1.2

**Comment by surapunoyousei** [comment]
fixed
