### ISSUE TITLE
 [Feature Request]  PLEASE add "cmd + z" re-open closed tab!!!! 

### ISSUE THREAD

**Issue by Yoyopizzacat** [Floorp-Projects/Floorp#383]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Can't use cmd+z to restore last closed tab on macOS 11.1.2
I consider this to be a key feature of any browser.

### To Reproduce

1. Close a tab
2. cmd + z
3. Nothing happens

### Expected behavior

The last closed tab is restored/reopened.

### OS Info

macOS Sonoma Beta 14.0

### Floorp Version

11.1.2

**Comment by surapunoyousei** [comment]
It this feature request?

**Comment by Yoyopizzacat** [comment]
Sure it could very well be a feature request.

**Comment by Yoyopizzacat** [comment]
Thank you
