### ISSUE TITLE
[Bug] Some extensions don't work in the sidebar, while others do.

### ISSUE THREAD

**Issue by check-m4te** [Floorp-Projects/Floorp#385]
### Attention!

- [x] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Some extensions like Vencord Web work correctly in Discord in the sidebar.

Others don't, such as Dark Reader or uBlock Origin.

### To Reproduce

1. Open a website in the sidebar
2. Some extensions work and others don't

### Expected behavior

I expect every extension to work properly

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/132251469/5552e566-47f9-4cc1-ac8c-2fd455a14337) Vencord Web working

![image](https://github.com/Floorp-Projects/Floorp/assets/132251469/43e4a6da-4031-4f43-98ea-480023f2ea58)
Gmail in the sidebar not being affected by Dark reader even tho it is affected when in  a normal tab

### OS Info

Windows 11 22621

### Floorp Version

11.1.2

**Comment by check-m4te** [comment]
I think maybe only extensions which are made to affect only specific sites work, while extensions designed to affect all sites don't?

**Comment by surapunoyousei** [comment]
Content scripts not work on Sidebar.

I didn't find the way to resolve this issue

**Comment by check-m4te** [comment]
Oh.

**Comment by surapunoyousei** [comment]
After Floorp 11.2.1, You can change preferences in about:config `floorp.browser.sidebar2.addons.enabled`. 

It is an experimental feature that allow run addon on webpanel.

**Comment by surapunoyousei** [comment]
There is a bug that the page opened in the web panel by mistake is restored in another window after restarting.

 I'm looking for a fix but it seems very difficult

**Comment by Carbocode** [comment]
I enabled `floorp.browser.sidebar2.addons.enabled`, and now, when I open the sidebar, I can see the toolbar for a while. It's not a big issue considering it's experimental, but just letting you know.


https://github.com/Floorp-Projects/Floorp/assets/65976264/2bdf6b82-7d64-48b1-884f-c140a62b7c15

**Comment by surapunoyousei** [comment]
> 有効にしました `floorp.browser.sidebar2.addons.enabled`, そして今、サイドバーを開くと、しばらくツールバーが表示されます。 実験的なものであることを考えると大きな問題ではありませんが、お知らせしておきます。
> Screen.Recording.2023-11-11.at.10.17.11.AM.mov



> I enabled `floorp.browser.sidebar2.addons.enabled`, and now, when I open the sidebar, I can see the toolbar for a while. It's not a big issue considering it's experimental, but just letting you know.
> Screen.Recording.2023-11-11.at.10.17.11.AM.mov

It's expected.

**Comment by surapunoyousei** [comment]
I will be launching an effort to ship this as a stable version in the near future.

**Comment by surapunoyousei** [comment]
Floorp Daylight channel will be able to enable this feature in stable.

Just change floorp.browser.sidebar2.addons.enabled to true and restart and it should be available.

The code has been rewritten and should be more stable now.

**Comment by surapunoyousei** [comment]
I forgot to write this down. User agent changes are now also respected.

Container tabs and the mute feature still do not work

**Comment by surapunoyousei** [comment]
Image of this feature. Running uBlock Origin & Mobile YouTube Website. 
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/f66e9f76-2657-4413-8761-a20ddfb61c88)

**Comment by Carbocode** [comment]
IDK if still an issue. But when I enable `floorp.browser.sidebar2.addons.enabled`, at reboot, floorp opens a new window for each time I opened and closed a page in the sidebar. I'm on MacOS

**Comment by surapunoyousei** [comment]
As early as today, we will be providing a version to the Daylight channel with the configuration we plan to ship to stable

**Comment by surapunoyousei** [comment]
OK. You guys! Meet the feature on Floorp 11.10.0.

Close this issue. This issue is the longest opening issue in Floorp GitHub repo.
