### ISSUE TITLE
[Bug] Window controls buttons not visible on other windows when vertical tabs opened

### ISSUE THREAD

**Issue by honkaiimpact3rd** [Floorp-Projects/Floorp#387]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

An issue I encountered after updating to 11.1.2. When you have vertical tab bar enabled, only the first window has window control buttons, new windows opened after that don't have them. I can confirm that the issue wasn't there in 11.1.0.

### To Reproduce

1. Enable "Vertical Tab Bar (experimental)"
2. Open multiple new windows

### Expected behavior

All windows to have window control buttons

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/107812489/1f3e1331-07c7-4750-a3cd-256da89e4760)

### OS Info

EndeavourOS (Arch Linux)

### Floorp Version

11.1.2 (Flatpak)

**Comment by surapunoyousei** [comment]
Fixed  wait for next version
