### ISSUE TITLE
[Bug] about:welcome from upstream still exists, despite about:setup being present too

### ISSUE THREAD

**Issue by dominichayesferen** [Floorp-Projects/Floorp#389]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

What the title says.

### To Reproduce

1. Just go to about:welcome

### Expected behavior

It either wouldn't exist, or about:setup would be an entire modification of that page instead.

### Screenshots

![Screenshot_20230821_144435](https://github.com/Floorp-Projects/Floorp/assets/11057934/c3084288-1e93-4860-bd54-241971683cd3)

### OS Info

Feren OS 2023.04

### Floorp Version

11.1.2 (Flathub)

### Additional context

Unrelated, but this screenshot shows that Edge-Frfox works just fine in Linux... well except for maybe bugged titlebuttons (that's easy enough to fix, though - just hide the hardcoded/lwtheme titlebuttons outside lwthemes after all), so maybe consider having it be a platform-irrespective option like the Chrome-like user interface already is.

**Comment by surapunoyousei** [comment]
Hmm. Disable is need ?


Additional context
> Linux version has Gnome UI.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/db6f0ce6c1b027210b187ed22fd247ba77d5a69c
