### ISSUE TITLE
[Feature Request] Add options to spoof other browsers / use custom user agent strings on specific URLs and domains?

### ISSUE THREAD

**Issue by YousufSSyed** [Floorp-Projects/Floorp#395]
### Is your feature request related to a problem?

Snapchat web doesn't work on Firefox and Floorp. I don't want to spoof another browser on all domains since I want them to know that I'm using Firefox or a fork of it.

### Describe the solution you'd like

Spoof should add boxes in the settings under "User Agent" to enter in URLs and domains and which browser to spoof as, or specify a custom user agent.

**Comment by surapunoyousei** [comment]
Firefox spoofs on Snapchat ?

**Comment by menndouyukkuri** [comment]
Perhaps you want to change the user agent only in a specific domain.

**Comment by YousufSSyed** [comment]
That's literally what I wrote, I guess the example of Snapchat made it less clear. I'd like to just spoof to Chrome on snapchat.com, and leave it unspoofed on all other sites. Basically a whitelist.

**Comment by surapunoyousei** [comment]
https://addons.mozilla.org/en-US/firefox/search/?q=UserAgent

**Comment by YousufSSyed** [comment]
I know, I currently use an addon for that. I just think the built-in setting would be a lot more useful with a whitelist.

**Comment by surapunoyousei** [comment]
We do not intend to implement this feature because the return on implementing this feature is not very large.
