### ISSUE TITLE
[Bug] Extension context menu actions don't work in pages in the side panel

### ISSUE THREAD

**Issue by YousufSSyed** [Floorp-Projects/Floorp#396]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I right click on a side panel page and select an action from an addon, it doesn't work.

### To Reproduce

1. Install [Translate Web Pages](https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/).
2. Add a page like this to the side panel and open it: https://blog.ablaze.one/3225/2023-06-22/.
3. Right click in it and select "translate to english" or whatever the addon context menu item says.

### Expected behavior

The page is supposed to translate but it doesn't.

### OS Info

MacOS 14 Beta

### Floorp Version

11.1.2

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/385
