### ISSUE TITLE
"Recently bookmarked" list is missing from the sidebar

### ISSUE THREAD

**Issue by Telmesomething** [Floorp-Projects/Floorp#40]
## Describe the bug
"Recently bookmarked" list is missing from the sidebar

## To Reproduce
1. Add the "Show sidebars" button to the toolbar.
2. Click the button to open the sidebar and change the layout from "Tree style tabs" to "Bookmarks". 
3. The "Recently bookmarked" list is missing. 

## Expected behavior
"Recently bookmarked" list should be visible when performing the above steps. 

## Desktop (please complete the following information):
 - OS: Windows 8.1 Home version.
 - Floorp Version: 10.4.0

A screenshot of how the "Recently bookmarked" list appears in the latest version of Firefox is included. 
Screenshot taken from Floorp version 10.4.0
![floorp sidebar](https://user-images.githubusercontent.com/33827636/189142537-be84c0a8-df6a-4e27-bbbb-b1638464da14.PNG)

Screenshot taken from Mozilla Firefox 104.0.2
![recently bookmarked missing](https://user-images.githubusercontent.com/33827636/189144120-ef1054db-d3da-4f21-9e42-6a9cdb9e0e1f.PNG)

**Comment by surapunoyousei** [comment]
I think it's not bug. This feature, or rather the bookmark feature, is just no longer auto-generated in the latest Firefox.

 Try syncing your bookmarks or migrating below.

https://support.mozilla.org/ja/kb/restore-bookmarks-from-backup-or-move-them

**Comment by Telmesomething** [comment]
Oh, I see what's happened. The "Recently bookmarked" list is still present, but it's only accessible via the dropdown hamburger link on the right hand side now.  So click the hamburger --> click the right facing arrow to "Bookmarks" and the recently bookmarked list appears.

**Comment by surapunoyousei** [comment]
Glad you were able to resolve it
