### ISSUE TITLE
[Feature Request] Disable the "download started" banner when the downloads icon is pinned to the toolbar.

### ISSUE THREAD

**Issue by YousufSSyed** [Floorp-Projects/Floorp#400]
### Is your feature request related to a problem?

Its redundant to see this banner,
<img width="342" alt="Screenshot 2023-08-23 at 5 47 42 AM" src="https://github.com/Floorp-Projects/Floorp/assets/42646062/eacbb383-0d2b-4c61-8b60-321f75b18c86">

if I have the downloads menu on the top toolbar:
<img width="479" alt="Screenshot 2023-08-23 at 5 45 05 AM" src="https://github.com/Floorp-Projects/Floorp/assets/42646062/d9f2a889-0ae7-4b85-82df-82962fe22eed">

### Describe the solution you'd like

The banner should be disabled in this case.

**Comment by surapunoyousei** [comment]
Please check this preferences

![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/dec11cbe-1273-4fe1-b6d9-a291f0bf0677)

**Comment by YousufSSyed** [comment]
What if this was automatically toggled depending on if the downloads managers is pinned, and if the user didn't set it manually before? If the user did, then the settings page would just respect that.

**Comment by surapunoyousei** [comment]
It is undesirable to change the settings without permission since there are download-related items in the sidebar.

It is certainly better if the user is free to change it.

**Comment by YousufSSyed** [comment]
Ok.
