### ISSUE TITLE
Sidebar icons are overlapping with other elements

### ISSUE THREAD

**Issue by regularenthropy** [Floorp-Projects/Floorp#42]
## Describe the bug
Sidebar icons are overlapping with other elements

## To Reproduce
1. Enable sidebar
2. Click on any icon on it.
4. See overlapping.
5. 
## Screenshots
![image](https://user-images.githubusercontent.com/89523758/189351363-cbf9e1de-3d10-40d6-b06d-dcead4a80ca4.png)
![image](https://user-images.githubusercontent.com/89523758/189351412-f44369ee-e256-454a-847f-7bd401e729bb.png)
![image](https://user-images.githubusercontent.com/89523758/189352675-90f25088-0251-4294-a1c9-141e80a2b39f.png)

## Desktop (please complete the following information):
 - Floorp Version: 10.5.0 BETA

**Comment by surapunoyousei** [comment]
It's Fixed

https://github.com/Floorp-Projects/Floorp/commit/d8c47c7f1a9bde24aa84db49259c27365bf8e042#diff-1a0596f39860d593041b2458f14cdd07a70fae2fb219b97ba8f129c957291dda
