### ISSUE TITLE
[Bug] Floorp browser UI bug based on Firefox 117 or higher

### ISSUE THREAD

**Issue by black7375** [Floorp-Projects/Floorp#420]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

This issue is not distinguished exactly whether bug report or feature request.
However, I would like to explain the possibility of many UI bugs.
(I think it is necessary to track as an issue)

In Firefox 117 or later, Windows 7 and 8 related codes are deleted, resulting in a braking change in this process. https://github.com/black7375/Firefox-UI-Fix/issues/744
So I did a theme release for ESR (based v115) and Standard (v117) respectively.

Stnadard
- [`css/leptonChrome.css`](https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonChrome.css)
- [`css/leptonContent.css`](https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonContent.css)

ESR
- [`css/leptonChromeESR.css`](https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonChromeESR.css)
- [`css/leptonContentESR.css`](https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonContentESR.css)

Now, Floorp seems to be following v115 ESR, so you should use an ESR-only version.

### To Reproduce

Floorp based on Windows Firefox v117 or later

### Expected behavior

Here is the main bug UI:

1. Menu layout
![image](https://github.com/Floorp-Projects/Floorp/assets/25581533/eae232c1-2af9-4a84-ba2f-553ff262e169)

2. Not apply default theme
![image](https://github.com/Floorp-Projects/Floorp/assets/25581533/278cd727-7c13-40bd-96ce-d636cd75bdee)

### OS Info

Windows10  22H2

### Floorp Version

NaN

**Comment by surapunoyousei** [comment]
Thanks for your warring.
https://github.com/Floorp-Projects/Floorp/commit/6a7b028c311b90fc01f3d0014f07630efbb79805

I already upgrade to esr version of Lepton. Start of today version of Floorp Daylight has new version Lepton.

If we get bug, I send bug report for you.

**Comment by black7375** [comment]
Wow, that's really fast.
I didn't expect it to be applied already.

Yes, if you have a problem, please give me a report.
