### ISSUE TITLE
[Bug] sidebar addons don't work when vertical tabs is enabled.

### ISSUE THREAD

**Issue by YousufSSyed** [Floorp-Projects/Floorp#426]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I can't open the bookmarks sidebar with `CMD B` (on MacOS) or a sidebar addon like Sidebery or Tree Style Tabs when vertical tabs are enabled.

### To Reproduce

1. In preferences, se verical tabs on tab bar set to "Optimize browser for vertical tab bar".
2. Turn of verical tabs.
3. Press `CMD B` or `CTRL B` to open the bookmarks sidebar, or install and try Tree Style Tabs.
4. Neither appears on the side.
5. It only works when tabs are horizontal, and tab bar is set to normal mode.

### Expected behavior

The sidebar window for bookmarks or the addon appears, with the vertical tabs to the right.

### OS Info

MacOS 14 Beta

### Floorp Version

11.1.2

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/6fceea0b-9229-4c21-89a0-596d7461f77c)

**Comment by surapunoyousei** [comment]
Use Browser Manager Sidebar instead of Firefox's sidebar

**Comment by YousufSSyed** [comment]
Have you looked at making the vertical tabs work with sidebar addons? It works fine with the side panel menu stuff like history and bookmarks.

**Comment by YousufSSyed** [comment]
@surapunoyousei Do you know why vertical tabs and sidebar addons can't coexist? There are CSS tweaks out there that make it work.

**Comment by surapunoyousei** [comment]
If user gets 3 sidebars. It not good at user experience

**Comment by YousufSSyed** [comment]
I think it should be allow, since users can easily toggle all of them on or off. If the user doesn't want them, then they. Its better to allow these things for power users than to disable it completely.

**Comment by surapunoyousei** [comment]
I don't like it because it doesn't work properly

**Comment by YousufSSyed** [comment]
Is there a way to force it on anyway?
