### ISSUE TITLE
[Bug] about:preferencesが開けない

### ISSUE THREAD

**Issue by newmomizi** [Floorp-Projects/Floorp#429]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Floorpの設定ページ(about:preferences)を開こうとした際にXMLのエラーが発生する。
```
XML パースエラー: タグの対応が間違っています。終了タグが必要です: </vbox>
URL: about:preferences
行番号: 1498, 列番号: 7:
    </hbox>
------^
```
他のaboutページをいくつか検証した(config, addons, profiles, profile-manager)が、それらは通常通り開くことができた。

### To Reproduce

about:preferencesを開く。
(ハンバーガーメニュー内のボタン、BMSのボタン、)

### Expected behavior

ブラウザーの設定画面のGUIが表示されると予想していた。

### Screenshots

![スクリーンショット 2023-08-27 204257](https://github.com/Floorp-Projects/Floorp/assets/114981625/363262a0-56bd-44f7-a20e-faaf075f9ab2)

### OS Info

Windows 10 Pro 22H2 (build 19045.3208)

### Floorp Version

Floorp 11.2.0 (build 20230825090642)

**Comment by surapunoyousei** [comment]
Fixed
https://github.com/Floorp-Projects/Floorp/actions/runs/5986973349
