### ISSUE TITLE
[Bug] タブの移動時に割り込むようなアニメーションが発生しない

### ISSUE THREAD

**Issue by menndouyukkuri** [Floorp-Projects/Floorp#431]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

タブの移動時に、タブとタブの間にドラッグしているタブが割り込むようなアニメーションが発生しません。
水平タブ、多段タブ、垂直タブの全てで発生します。

### To Reproduce

タブを複数開き、1つをドラッグして移動します。

### Expected behavior

タブの移動時に、タブとタブの間にドラッグしているタブが割り込むようなアニメーションが発生します。

### OS Info

Windows 11 22H2

### Floorp Version

11.2.0

### Additional context

このバグは現状Floorp 11.2.0 / Floorp Daylight 11.2.0でのみ発生します。

**Comment by surapunoyousei** [comment]
ほんとだなんでだろ

**Comment by surapunoyousei** [comment]
ワークスペースのピン止めしたタブ関連の問題っぽいので後ほど修正します

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/90da3d729d19d3097d30db1b2e967170cbfb2c00
