### ISSUE TITLE
[Bug] ブラウジングライブラリーで一部のアイコンが表示されない

### ISSUE THREAD

**Issue by menndouyukkuri** [Floorp-Projects/Floorp#432]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Floorp 11.2.0 / Floorp Daylight 11.2.0ではブラウジングライブラリーで一部のアイコンが表示されません。

Floorp 11.1.2
![スクリーンショット 2023-08-30 131106](https://github.com/Floorp-Projects/Floorp/assets/61068665/fc5a81d0-fc4d-48a5-958a-b2fc8d418b34)

Floorp Daylight 11.2.0
![スクリーンショット 2023-08-30 131223](https://github.com/Floorp-Projects/Floorp/assets/61068665/b2445af8-734c-4ffe-86e3-e68f78c07d10)

### To Reproduce

ブラウジングライブラリーを開く。

### Expected behavior

上のFloorp 11.1.2の画像のように、ブラウジングライブラリーで全てのアイコンが表示されます。

### OS Info

Windows 11 22H2

### Floorp Version

11.2.0

### Additional context

立て続けに送ってしまいました。ごめんなさい。

**Comment by surapunoyousei** [comment]
バグは建てても結構です。

Lepton のアイコン関連がうまくいっていなかったようです。どちらもそこまで大きい問題ではない（使用上は）なので１週間後に修正パッチを配信するつもりです

**Comment by menndouyukkuri** [comment]
ありがとうございます。

**Comment by surapunoyousei** [comment]
Fixed
