### ISSUE TITLE
[Bug] Pin tabs overlap on workspace button

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#433]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When you have a tab pinned in the tab bar and open many tabs until the tab scroll button appears, the pinned tab overlaps the workspace button.

### To Reproduce

1. Activate workspaces
2. Pin a tab
3. Open many tabs until the scroll button of the tabs is displayed

### Expected behavior

The pinned tabs do not overlap the workspace button.

### Screenshots

![floorp-bug](https://github.com/Floorp-Projects/Floorp/assets/86812371/4988eefd-18e9-472f-a8a6-cacfb8a50146)

### OS Info

Windows 10 22H2

### Floorp Version

11.2.0

### Additional context

Apparently a change made in version 11.2.0 of Floorp causes the bug, this does not occur in the previous version 11.1.2.
The test was performed on a new profile to avoid an error in the current profile.

**Comment by surapunoyousei** [comment]
Exclude pinned tabs causes some issue. Remove preferences resolve it. Sorry.

https://github.com/Floorp-Projects/Floorp/commit/90da3d729d19d3097d30db1b2e967170cbfb2c00
