### ISSUE TITLE
[Bug] ice.default_address_only and ice.no_host causing loophole on some websites

### ISSUE THREAD

**Issue by gunir** [Floorp-Projects/Floorp#436]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Website: https://chat.zalo.me/

Fresh profile Firefox 117: https://streamable.com/0kp5tx
Fresh profile latest Floorp: https://streamable.com/d8e9f1

### To Reproduce

1. Go to https://chat.zalo.me/
2. In Firefox it loads really fast, but it takes forever to load in Floorp

### Expected behavior

The website should loads as fast as Firefox

### Screenshots

Video:

Fresh profile Firefox 117: https://streamable.com/0kp5tx
Fresh profile latest Floorp: https://streamable.com/d8e9f1

### OS Info

Windows 10

### Floorp Version

latest

### Additional context

Can be fixed by setting: 
`media.peerconnection.ice.default_address_only` -> false
`media.peerconnection.ice.no_host` -> false

Result: https://streamable.com/sz1py5

**Comment by surapunoyousei** [comment]
Ok

thanks. I will check it

**Comment by surapunoyousei** [comment]
Removed. wait for 11.2.1
