### ISSUE TITLE
[Bug] Line appears on the left side of the screen when playing a video in full screen, in a window that is in full screen.

### ISSUE THREAD

**Issue by Riax0n** [Floorp-Projects/Floorp#440]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

White-ish line on the left side of the screen when going full screen on a video, from a window that is in full screen too.

### To Reproduce

1. Go to any site that hosts videos ( e.g. [YouTube](https://www.youtube.com/) )
2. Go full screen in the window.
3. Play a video in full screen.
4. Observe as the line appears on the left side of the screen.

### Expected behavior

No line appearing.

### Screenshots

Video in full screen whilst window is in full screen:
<img width="34" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/97038823/8d7395bc-ddc8-4f50-be86-6fa436509f5d">

Video in full screen whilst window isn't in full screen:
<img width="47" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/97038823/f7f6763a-a12e-4dd5-8463-a6a9a72dfd19">

### OS Info

MacOS Ventura 13.5.1 (22G90)

### Floorp Version

11.2.0

**Comment by surapunoyousei** [comment]
Not big problem I will fix it later

**Comment by surapunoyousei** [comment]
On my desktop machine, This issule is fixed
