### ISSUE TITLE
[Bug] 1password extension doesn't connect to 1password app (mac)

### ISSUE THREAD

**Issue by Nixobe** [Floorp-Projects/Floorp#446]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

hello, i've started using floorp recently and i can say that it is great, however, i'm having troubles with 1password app connecting with the extension (it can't connect, so i have to type in my password every time i login to my browser.). Works properly with the regular firefox

### To Reproduce

1. I go to my 1password extension settings
2. I see this:

<img width="560" alt="Screen Shot 2023-09-05 at 10 03 12 AM" src="https://github.com/Floorp-Projects/Floorp/assets/68926902/095deaec-d991-45aa-9ac1-b8faeea2817d">

4. I go to my 1password app settings
5. I see this:

<img width="464" alt="Screen Shot 2023-09-05 at 10 04 01 AM" src="https://github.com/Floorp-Projects/Floorp/assets/68926902/dae424b2-2d93-48e7-964b-67c243de5f7b">

### Expected behavior

i expect them to connect with eachother

### OS Info

macOS Big Sur 11.7.9

### Floorp Version

115.2.0

**Comment by surapunoyousei** [comment]
https://1password.community/discussion/140735/extending-support-for-trusted-web-browsers
