### ISSUE TITLE
[Bug] 最小化、拡大、閉じるボタン のバーが左上に表示される

### ISSUE THREAD

**Issue by kometchtech** [Floorp-Projects/Floorp#449]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Windows 11 22H2環境において、垂直タブ、垂直タブにブラウザーを最適化を有効にした状態だと、戻る・進むなどのツールバーの並びではなく、その上で表示され、かつ左上に表示されるようになった。

### To Reproduce

- 垂直タブを有効にした状態でv11.3.0 -> 11.3.1にしたときから

### Expected behavior

終了などのボタンが右上に表示される

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/5137077/47fecda4-2bd1-40ec-bad3-8214b277faeb)

### OS Info

Windows 11 22H2

### Floorp Version

11.3.1

### Additional context

- なお、垂直タブを有効にした状態だと、タブバーの設定（実験的）を変更しても変化がない
- LeptonやPhotonなどを切り替えても変化なし
- 水平タブ、多段タブだと問題なし

**Comment by kometchtech** [comment]
v11.3.2では問題が発生していないことを確認しました。

**Comment by surapunoyousei** [comment]
修正しました

**Comment by kometchtech** [comment]
対応ありがとうございました。
