### ISSUE TITLE
Prevent the sidebar window from opening by default

### ISSUE THREAD

**Issue by regularenthropy** [Floorp-Projects/Floorp#45]
## Is your feature request related to a problem? Please describe.
I find it annoying, that the sidebar window always opens after starting Floorp.

## Describe the solution you'd like
Add a button that will prevent the sidebar window from opening by default without turning off the sidebar itself.
(The sidebar remains visible, but the window does not open automatically)

**Comment by surapunoyousei** [comment]
I'll adjust

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/2acb3056fce0f3088583d331162fabc3089881b8
