### ISSUE TITLE
[Bug] Many Extension Icons become invisible when using the Dark variant of the GNOME Theme

### ISSUE THREAD

**Issue by adsewadsw** [Floorp-Projects/Floorp#450]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When using the GNOME Theme and toggling "Optimize browser for Vertical Tab Bar" instead of "Hide Tabs on Horizontal Tab Bar" the Minimize, Maximize and Close buttons gets duplicated with a blank/invisible version. Both sets of buttons work but one is invisible.

### To Reproduce

(Toggle GNOME Theme)
1. Go to Settings.
2. Go to Design.
3. Scroll down to "Tab Bar (not supported in macOS)"
4. Toggle Optimize browser for Vertical Tab Bar.
5. invisible set of Minimize, Maximize and Close buttons gets duplicated to the left side.

### Expected behavior

(Toggle GNOME Theme)
1. Go to Settings.
2. Go to Design.
3. Scroll down to "Tab Bar (not supported in macOS)"
4. Toggle Optimize browser for Vertical Tab Bar.
5. Minimize, Maximize and Close buttons gets integrated with the Horizontal Tab Bar.

### Screenshots

![Screenshot from 2023-09-08 23-48-14](https://github.com/Floorp-Projects/Floorp/assets/140419348/2da0caad-f699-4643-a326-267b6494e151)
![Screenshot from 2023-09-08 23-48-03](https://github.com/Floorp-Projects/Floorp/assets/140419348/b239e5db-497f-473b-9952-139ad2b2f2c1)
![Screenshot from 2023-09-09 00-07-23](https://github.com/Floorp-Projects/Floorp/assets/140419348/8a6c0fa6-1577-4dd7-9913-0ce700209a32)
![Screenshot from 2023-09-09 00-07-17](https://github.com/Floorp-Projects/Floorp/assets/140419348/cc3df211-c7e5-40a5-96bc-515515a6f3df)

### OS Info

Fedora Linux 38 (Bazzite GNOME) x86_64 (Basically Fedora 38, Silverblue :)

### Floorp Version

11.1.2 (64-bit)

### Additional context

1. I am using the Flatpak version of Floorp, which is at version "11.1.2" **(The issue is still present in version 11.4.0)**
3. This doesn't happen with other themes enabled.
4. I'm not sure why the buttons are grayed out but that also happens with other themes enabled, whether it's the light or dark variant. (Unrelated issue)

**Comment by mandiuk** [comment]
Yeah, same thing on Windows 11.  I have a problem with only 1 extension "Stylish", icon sometimes disappears on some websites, becomes empty transparent space.

**Comment by surapunoyousei** [comment]
Fixed
