### ISSUE TITLE
[Bug] Visual bug on sidebar

### ISSUE THREAD

**Issue by vinicioscst** [Floorp-Projects/Floorp#452]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The sidebar in standard mode continues to display beyond the border.
When rounded corners are active, the width of the bar in relation to the edge is displayed normally, but it generates a large spacing and the icons are not centered.

### To Reproduce

1. Show the Browser Manager Sidebar needs to be active on Config > Browser Manager Sidebar
2. Active 'Round the corners of pages' on Config > Design

### Expected behavior

Sidebar icons should be centered and sidebar width should respect the border limits.

### Screenshots

Default sidebar
![Default sidebar](https://github.com/Floorp-Projects/Floorp/assets/121524525/b1cf1575-f0f9-49d0-867c-6f0c6ca62dc4)
Sidebar with rounded corners
![Sidebar with rounded corners](https://github.com/Floorp-Projects/Floorp/assets/121524525/452c62ca-0c3d-4f0f-a517-4da3e0842274)

### OS Info

Windows 11 22H2

### Floorp Version

11.3.2

**Comment by surapunoyousei** [comment]
I will not work this problem now.
