### ISSUE TITLE
[Bug] Firefox Sync login hangs forever at first page

### ISSUE THREAD

**Issue by chrishazfun** [Floorp-Projects/Floorp#461]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I'm unable to login to Firefox Sync to grab any info and sync data.

### To Reproduce

1. Open Floorp
2. Attempt to login to sync options
3. Enter email associated with sync data, attempt proceed to next step
4. Loading stays on "Working..."

### Expected behavior

I successfully login and gather my sync data as I can in regular Firefox.

### OS Info

Windows 10.0.19045 - Build 19045

### Floorp Version

11.3.3

### Additional context

I've cleared all the relevant caches and even attempted to reinstall and nothing changes, login to sync still hangs on email.

**Comment by surapunoyousei** [comment]
Did you restart & retry it？

**Comment by chrishazfun** [comment]
Yeah, clean restart and retry, hangs at the email field

**Comment by surapunoyousei** [comment]
I cannot find the bug. Try new profile.

**Comment by chrishazfun** [comment]
Cleared all profiles, start-up cache, reinstalled and it's still hanging

**Comment by surapunoyousei** [comment]
No other reports have come in so perhaps something is wrong with you.

Please write down the exact process you went through to log in.

**Comment by gunir** [comment]
This issue could be related to your network, can you try with Firefox ESR 115.

**Comment by chrishazfun** [comment]
Tried with Firefox ESR 115, two times over including re-installing and it's still hanging. I added it to the firewall unblock list too so that's also cleared.

**Comment by creeper-0910** [comment]
If the problem also occurs in Firefox, there is no way to address it in Floorp.
We recommend that you contact the Firefox forum.
