### ISSUE TITLE
[Bug] Runtime Error while compiling under linux

### ISSUE THREAD

**Issue by Brli** [Floorp-Projects/Floorp#462]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

24:31.04 RuntimeError: File "en-US/floorp.ftl" not found in /build/floorp/src/Floorp-11.3.3/floorp/browser/locales, /build/floorp/src/Floorp-11.3.3/obj/floorp/browser/locales

occurs during `./mach build`

### To Reproduce

1. git clone and checkout tag v11.3.3
2. configure mozconfig like in workflow
3. run ./mach build

### Expected behavior

passes

### OS Info

Archlinux

### Floorp Version

11.3.3

**Comment by surapunoyousei** [comment]
git submodule update --init --recursive

**Comment by Brli** [comment]
Sorry, it was a v11.3.3.zip from release page
instead of git clone <(_ _)>

**Comment by surapunoyousei** [comment]
OK.

Following this process:

1. Create dir:
`floorp/browser/locales/en-US`

2. Add English localize file:
Download this file `https://raw.githubusercontent.com/Floorp-Projects/Floorp-Strings/main/floorp.ftl`

3. copy to `floorp/browser/locales/en-US`

retry build

**Comment by Brli** [comment]
still not working

**Comment by surapunoyousei** [comment]
Maybe you made a mistake.

Check photo
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/5461221c-eb2a-46cb-91a2-fbcb77849981)
