### ISSUE TITLE
[Bug] White flash when playing video

### ISSUE THREAD

**Issue by ekrem-qb** [Floorp-Projects/Floorp#464]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The browser window flashes/blinks entirely in white when trying to play a video on page. This bug only occurs if hardware acceleration is enabled in browser preferences and Vertical sync is set to Fast in NVIDIA Control Panel. Also, this doesn't happen in vanilla Firefox, for example in 117.0.1 version.

### To Reproduce

1. Go to any web-site with video on page, for example [Mozilla HTML Video page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)
2. Play the video
3. Browser window will flash 1-2 times

### Expected behavior

Browser window shouldn't flash or blink when it tries to render video on page.

### Screenshots

![](https://github.com/Floorp-Projects/Floorp/assets/37544619/bca6b652-589a-4ace-8a21-9579902ac816)

https://github.com/Floorp-Projects/Floorp/assets/37544619/e6f76409-7fd5-4284-b566-5c0276654bf0

### OS Info

Windows 10 22H2 & Windows 11 22H2

### Floorp Version

11.3.3

### Additional context

GPU: NVIDIA Geforce RTX 2060

**Comment by surapunoyousei** [comment]
Follow it

https://github.com/Floorp-Projects/Floorp/issues/378#issuecomment-1691132211

**Comment by ekrem-qb** [comment]
Thanks 👍
