### ISSUE TITLE
 [Bug]

### ISSUE THREAD

**Issue by ogkimra** [Floorp-Projects/Floorp#466]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I used to use official firefox with [firefox containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension to use workspace. But as floorp already had this workspace feature I decided to uninstall that extension but still if I click on any tabs, it shows "add to container" which is the command of that extension. I dont see the extension anymore in my list.
![image](https://github.com/Floorp-Projects/Floorp/assets/32086892/33ca2f9e-97bd-4464-a422-49da54ee5d17)
![image](https://github.com/Floorp-Projects/Floorp/assets/32086892/f11070b0-09f0-4c79-a650-624f15a219b4)

And the weird thing is that even after removing it is working like a ghost or something.

### To Reproduce

1. Install [firefox container ](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension in official app and sync it with floorp
2. Uninstall the extension in floorp
3. Right click on tabs to get that option

### Expected behavior

Should remove its feature from right click menu upon clicking on tabs

![image](https://github.com/Floorp-Projects/Floorp/assets/32086892/8d84a366-df69-4bad-b19a-c29cd56be0e6)

This is what the official firefox shows upon right clicking

### OS Info

Windows 10 Pro 22H2

### Floorp Version

11.3.3 (64-bit)

**Comment by surapunoyousei** [comment]
Not bug.

you can disable it on preferences page
