### ISSUE TITLE
[Bug] git hub assets stuck loading

### ISSUE THREAD

**Issue by viking316** [Floorp-Projects/Floorp#471]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

so i was downloading this https://github.com/betterbrowser/arcfox/releases/tag/2.4.3 for my windows 10 and then the assets would be stuck loading tried restarting.

### To Reproduce

go to https://github.com/betterbrowser/arcfox/releases/tag/2.4.3
go to releases section
none of the assets in the releases section is loading for me 

### Expected behavior

it is supposed to load the assets as expected and not be stuck loading 

### OS Info

windows 10 22h2

### Floorp Version

115.3.0

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/b41ab712-2f41-42b3-9b0b-8856466f98eb)

**Comment by viking316** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/82701532/5dee4fa4-0630-4742-9f5e-791098b83c59)

**Comment by viking316** [comment]
also the site itself is not right, i removed all extensions except ublock origin and still the same problem
![image](https://github.com/Floorp-Projects/Floorp/assets/82701532/deec0fce-e9eb-4855-ba42-bbdf249ae1b1)

**Comment by surapunoyousei** [comment]
Did you try to use new profile?

**Comment by viking316** [comment]
hey! thanks that fixed the issue,
idk why it worked but it did. hope i didnt cause any problems.
