### ISSUE TITLE
[Bug] Reddit site is not rendering corredtly 

### ISSUE THREAD

**Issue by viking316** [Floorp-Projects/Floorp#472]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

as the title says, check the ss.

### To Reproduce

go to reddit.com

### Expected behavior

load reddit.com

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/82701532/539e9c7e-6a37-4294-a5bb-9ad776b0ed55)

### OS Info

windows 10 22h2

### Floorp Version

115.3.0

**Comment by creeper-0910** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/56744841/bf497621-5484-4de2-b4d1-efd3edc60792)

**Comment by creeper-0910** [comment]
Have you tried a new profile?

**Comment by viking316** [comment]
no, let me try that
