### ISSUE TITLE
All tabs disapear when I use Photon UI mode and try to customize with setting Tab Bar to the location of Title Bar

### ISSUE THREAD

**Issue by Stop-Unsecure-ZeroInstall-Updating** [Floorp-Projects/Floorp#473]
Hello Team,

I don't know this behavior is the first time in this build. Now the resolution of this laptop is 1920x1080.

Anyway, as I wrote above briefly, all tabs seem disapear or untachable when the following procedure:
  Setting 1: Design=>Firefox Photon-Lepton Design=>Photon UI Mode=>allocate Tab Bar to the position of Title Bar
  Setting 2: Enable Multi Low
Then, all tabs disapear and the upper part become so much slim. 

If these are intended effects, I apologize my misunderstanding.
Please check this behavior is correct or not with the two attached screen captures, 
but I deleted the part which may unvail my privacy.

Thanks, I D&D the pictures.

In addition, I strongly desire to realize the followings, at this time:
1, Please make the Note to a full-spec Markdown editor which fully supports "commonMark+MATHJAX" or "GFM."
  I consider most of you prefer GFM. And CSS for Markdown to html converters would be custamised.
  Hopefully, it's greatly appreciated if you make WYSIWYG real-time editor similar to "typora."
2. Then, because I found the FirefFox's extention, "fx_cast" for Chromecast, please implement  Chroamcast and/or AirPlay.
  Please check: https://hensm.github.io/fx_cast/ which need the other bridge companion. Now you have WideVine, so I guess you will also not be abused by Google?
3, Microsoft released "On-Premise<=>Cloud movable" Office 365 boot/switch. I'm using many types of Google Cloud products with Invitation. I don't like Duet AI.  Google are also making their products into very small parts around micro-kernel like old Mach structure which were used by NeXT OS made by Steve Jobs when he was hired from Apple  by CEO who was hired by Jobs. Jobs also made Pixer. 
Anyway, their plan is to make more movable any software parts on K8s incl. Chrome. Enterprise can pay the cost to the real movable software. But, consumer will not pay. So, additionally,  the really effective and efficient business model and plans to involve consumer and so on.  Patrons are really great people, however, this monetize model cannot make well. At first, I' would like to start to make the whole software structure into the micro parts as many giants. But, I cannot do it well now, being too old.

Yours Sincerely,
away

![floorp-2023-09-26-002](https://github.com/Floorp-Projects/.github/assets/109265402/5e97207f-a2d3-459c-b36c-bb14834a95d8)

![floorp-2023-09-26-003](https://github.com/Floorp-Projects/.github/assets/109265402/f3383def-526c-4629-9dca-82c8638408d7)

**Comment by surapunoyousei** [comment]
Pleease separate issue & feature request

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/f51524df-36d0-4fb1-9180-863bcabc95a3)

**Comment by Stop-Unsecure-ZeroInstall-Updating** [comment]
### ___Dear @surapunoyousei and all___,

##### **First of all, I absolutely apologize for my insolence.**

　　__Completely as you wrote, I had to split the possible issues and the feature requests.__
    __This is one of the basic manners in all kinds of engineering.__
      ***I must do the right things.***

Then, the following link means what I thought the possible issue is not a real issue and removed? 

> https://github.com/Floorp-Projects/Floorp/issues/473#issuecomment-1735591314

----------
This may be just my excuse for you and myself, I'm still confused about anything to write and so on in GitHub,
because the repository management systems, I have used and have a bit of experience with, look almost obsolete.
So, when I suddenly opened the form, I wrote both a possible issue and some feature requests.


Best,
away

**Comment by surapunoyousei** [comment]
> ### _**Dear @surapunoyousei and all**_,
> ##### **First of all, I absolutely apologize for my insolence.**
> 
> 　　**Completely as you wrote, I had to split the possible issues and the feature requests.** **This is one of the basic manners in all kinds of engineering.** _**I must do the right things.**_
> 
> Then, the following link means what I thought the possible issue is not a real issue and removed?
> 
> > [#473 (comment)](https://github.com/Floorp-Projects/Floorp/issues/473#issuecomment-1735591314)
> 
> This may be just my excuse for you and myself, I'm still confused about anything to write and so on in GitHub, because the repository management systems, I have used and have a bit of experience with, look almost obsolete. So, when I suddenly opened the form, I wrote both a possible issue and some feature requests.
> 
> Best, away

The screenshot shows your commented bug can not be founded

**Comment by Stop-Unsecure-ZeroInstall-Updating** [comment]
Thank you for your prompt reply and sorry for consuming your precious time. 

Please let me have a little more time to confirm that the following movement is correct in the specifications,  is it correct?
> Even if in this mode, when we click the downward arrow at the right part of the top bar,
> the tabs are displayed downward as usual. 

Thanks,

**Comment by surapunoyousei** [comment]
OK
