### ISSUE TITLE
Traditional Chinese interface is incomplete

### ISSUE THREAD

**Issue by kikushyu** [Floorp-Projects/Floorp#476]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Hello team,
I use traditional Chinese interface in floorp.but there are many simplified Chinese characters in the traditional Chinese interface.
 Thanks!

### To Reproduce

go to  settings

### Expected behavior

Traditional Chinese interface display

### Screenshots

![螢幕擷取畫面 2023-09-27 144653](https://github.com/Floorp-Projects/Floorp/assets/103197572/46c199f5-2da7-444b-8479-d487c125da9e)

### OS Info

win10 22h2

### Floorp Version

11.4.0

**Comment by surapunoyousei** [comment]
@benzBrake

Help

**Comment by benzBrake** [comment]
> @benzBrake
> 
> Help

I am not a Traditional Chinese user, and Traditional Chinese has different terms for Hong Kong and Taiwan. I don’t know these.
I can only "convert" Simplified Chinese to the corresponding Traditional Chinese characters
