### ISSUE TITLE
[Bug] Theme API won't affect the right sidebar and bottom bar

### ISSUE THREAD

**Issue by SettingDust** [Floorp-Projects/Floorp#478]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I'm using https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour
But the color from the addon won't take effect on bottom and right sidebar. 
The colors are different from the title bar(theme)

### To Reproduce

Install it

### Expected behavior

The same color

### Screenshots

![图片](https://github.com/Floorp-Projects/Floorp/assets/19922286/1b1c9630-8118-464a-b131-5f25b30068bc)

### OS Info

Windows 10 22H2 19045.3448

### Floorp Version

11.4.0

**Comment by SettingDust** [comment]
And another problem that I don't know how to describe in English. There is a blank line at the top of window that will affect the behavior commonly. Like I always try to drag the cursor to the top right for closing. But failed with this
![图片](https://github.com/Floorp-Projects/Floorp/assets/19922286/a9af9039-8cc2-46da-b0e3-dbeaad9a535e)

**Comment by surapunoyousei** [comment]
> And another problem that I don't know how to describe in English. There is a blank line at the top of window that will affect the behavior commonly. Like I always try to drag the cursor to the top right for closing. But failed with this
Fluerial has the bug, You can use Lepton.

I didn't care about it. I have to fix it

**Comment by SettingDust** [comment]
And another. There is a weird border between page and left sidebar
![图片](https://github.com/Floorp-Projects/Floorp/assets/19922286/3fe8aa64-cf3d-4bf2-a791-21a453e3c5c0)
No in Firefox Dev
![图片](https://github.com/Floorp-Projects/Floorp/assets/19922286/7f9488ec-0f93-4e08-8ac9-b274835b8a42)

**Comment by surapunoyousei** [comment]
May be you enable rounded corner preferences.

**Comment by SettingDust** [comment]
> May be you enable rounded corner preferences.

No
![图片](https://github.com/Floorp-Projects/Floorp/assets/19922286/d85e8143-4f9a-46d7-8497-a0036681e2ea)

**Comment by surapunoyousei** [comment]
> And another. There is a weird border between page and left sidebar ![图片](https://user-images.githubusercontent.com/19922286/271030385-1ef535f0-b9ec-469b-b051-ce99916e8be9.png) No in Firefox Dev ![图片](https://user-images.githubusercontent.com/19922286/271027689-7f9488ec-0f93-4e08-8ac9-b274835b8a42.png)


It is Floorp's splitter. If you drag to change sidebar width, Need spliter.

**Comment by surapunoyousei** [comment]
Only fix theme API Bug

**Comment by SettingDust** [comment]
How about a thinner splitter like firefox?

**Comment by surapunoyousei** [comment]
If I do this, it will be difficult to focus with the mouse.

あなたは以下の CSS で小さくできます。

```CSS

#sidebar-splitter {
   width: 1px !important
}

```

**Comment by SettingDust** [comment]
okay :D

**Comment by surapunoyousei** [comment]
fixed
