### ISSUE TITLE
Floorp seems to have a number of third-party modules, what purpose they serve?

### ISSUE THREAD

**Issue by Shitennouji** [Floorp-Projects/Floorp#48]
代筆ですが、
[gHacks Technology News（独）でのコメントから](https://www.ghacks.net/2022/08/30/firefox-104-0-1-fixes-youtube-playback-issues/#comment-4549015)
There appears to be a large number of third party modules in Floorp. Do you happen to know what purpose they serve?（Floorp には多数のサードパーティモジュールがあるようです。それらはどのような目的で使用されているのでしょうか？）

Floorp 10.4.0
Here’s a list of them:
1. xul.dll, 
2. nss3.dll, 
3. softokn3.dll, 
4. freebl3.dll, 
5. api-ms-win-crt-multibyte-l1-1-0.dll, 
6. lgpllibs.dll, 
7. ipcclientcerts.dll, 
8. nssckbi.dll, 
9. osclientcerts.dll. 

I was surprised to see them all since I thought Mozilla was blocking third party modules by default these days.（最近 Mozilla はデフォルトでサードパーティモジュールをブロックしていると思っていたので、それらの全部を見て驚いています。）

**Comment by surapunoyousei** [comment]
xul.dll は基本的に Mozilla 製品の全てに同封されている「ユーザインタフェースマークアップ言語」である XUL の解釈に必要なものだと思われます。Firefox の部分ではなく、Gecko エンジンの部分かと。

nss3.dll, は Network Security Services の共有ライブラリ SSL 操作のサポートなどを行うようです。

softokn3.dll は NSS が FIPS 140 モードで動作するために必要なチェックサム ファイルらしいです。意味はよくわかりません。私が得意なのは Firefox のフロントエンドなので。

freebl3 は不明です。ただし、扱いが上記の softokn3.dll と同じなのでチェックサムファイルかもしれません。

api-ms-win-crt-multibyte-l1-1-0.dll  は Windows のライブラリなのはわかりますが用途は不明です。

nssckbi.dll は Servo エンジンに使用されているライブラリです。これも NSS に近いようです。

osclientcerts.dll. は OS に保存されているクライアント証明書を Firefox で使用できるようにする PKCS#11 モジュールです。環境設定→プライバシーとセキュリティ→証明書 という設定周りの機能かと思われます。

記載されていないものは理解できませんでした！お許しを。
