### ISSUE TITLE
[Bug] Window Controls won't take the correct color

### ISSUE THREAD

**Issue by SettingDust** [Floorp-Projects/Floorp#482]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

![图片](https://github.com/Floorp-Projects/Floorp/assets/19922286/ee7f62b3-45fd-46f4-b629-4c579a998965)
Controls won't follow the icon color in floorp. Appears on some page such as the home page of floorp. And fine in github

### To Reproduce

Install https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour
Open https://floorp.app/en/
Maybe some options need change

### Expected behavior

![图片](https://github.com/Floorp-Projects/Floorp/assets/19922286/bb46ea8d-374c-4db2-973b-95e3577ed2de)

### OS Info

Windows 10 22H2 19045.3448

### Floorp Version

11.4.0

**Comment by surapunoyousei** [comment]
Maybe U changed Floorp's theme

**Comment by SettingDust** [comment]
> Maybe U changed Floorp's theme

I'm using Lepton ProtonFix.

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/dbdff99a-3c45-4acc-ab7c-184b6bd04856)

Not design. It's Theme. Did you install Theme? 
 In my env, It's correct.

**Comment by SettingDust** [comment]
> ![image](https://user-images.githubusercontent.com/73892113/271766364-dbdff99a-3c45-4acc-ab7c-184b6bd04856.png)
> 
> Not design. It's Theme. Did you install Theme? In my env, It's correct.

https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour is using theme api to change the color of firefox/floorp

**Comment by surapunoyousei** [comment]
It's true.

IMO, Default Floorp doesn't has you problem. My worry is your customize makes this problem.

**Comment by SettingDust** [comment]
> It's true. 这是真的。
> 
> IMO, Default Floorp doesn't has you problem. My worry is your customize makes this problem.IMO，Default Floorp 不会给你带来问题。我担心的是你的定制会导致这个问题。

My theme is the default dark.

**Comment by surapunoyousei** [comment]
Ok.

> > It's true. 这是真的。
> > IMO, Default Floorp doesn't has you problem. My worry is your customize makes this problem.IMO，Default Floorp 不会给你带来问题。我担心的是你的定制会导致这个问题。
> 
> My theme is the default dark.

Ok. Did you try to use Proton Design (NOT theme)?

**Comment by SettingDust** [comment]
I tried. Same result. The controls being white in floorp home page

**Comment by surapunoyousei** [comment]
Not true.

Ok. Try new profile.

![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/2eb229cf-7d18-443d-9258-94dc0c6f3577)

**Comment by SettingDust** [comment]
It's fine in new profile. I need figure out the reason. That's weird

**Comment by surapunoyousei** [comment]
This could be due to compatibility issues with other add-ons.

Or are you using userChrome.css?

**Comment by SettingDust** [comment]
> Or are you using userChrome.css?
No. Just the built in css for address bar.

> This could be due to compatibility issues with other add-ons.
Should. But not appears in firefox. I'll try to find out

**Comment by surapunoyousei** [comment]
OK. Could you list your installed addons?

**Comment by SettingDust** [comment]
> OK. Could you list your installed addons?

They are in Chinese. How can I share the list of addons with their id?

**Comment by SettingDust** [comment]
I'm afraid of that's not caused by addons. I tried disable all of them besides sidebery and https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour. The issue still there. But it's fine in new profile with the addons

**Comment by SettingDust** [comment]
Fine after fresh install. Can't find the reason

**Comment by surapunoyousei** [comment]
Good works.
