### ISSUE TITLE
[Bug] Weird container around status bar/status tooltip

### ISSUE THREAD

**Issue by alok-debnath** [Floorp-Projects/Floorp#484]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

status bar/status tooltip shows a edge-rounded single lined container around it

### To Reproduce

1. Go to "about:preferences#design"
2. Enable "Round the corners of pages"

### Expected behavior

That container thing just should not even appear when enabling "Round the corners of pages", can probably be fixed by not applying any additional styles to status tooltip when enabling this option

### Screenshots

![Screenshot from 2023-09-30 13-39-22](https://github.com/Floorp-Projects/Floorp/assets/67475527/885c2f9c-bb9c-4dd0-9393-6b91da0d3f44)

### OS Info

Fedora Linux 38 (Workstation Edition)

### Floorp Version

11.4.1

**Comment by surapunoyousei** [comment]
Fixed !

Wait for update
