### ISSUE TITLE
[Bug] NVIDIA Max Frame Rate, Limits Floorp FPS even when focused/Fullscreen! unlike Firefox

### ISSUE THREAD

**Issue by AKL55** [Floorp-Projects/Floorp#485]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

NVIDIA Max Frame Rate Limits Floorp's FPS even when focused/Fullscreen!

### To Reproduce

To reproduce, just set Max Frame Rate in global settings to any value.

![awfawfaw](https://github.com/Floorp-Projects/Floorp/assets/89634553/4bf9826e-4399-4d99-9399-ab3daf63a7d2)

### Expected behavior

Don't limit the FPS when focused like on firefox.

### OS Info

Windows 11 Pro. 10.0.22621 Build 22621

### Floorp Version

11.4.0 Portable and Installer

**Comment by AKL55** [comment]
Nevermind, it was a mistake. I think I changed the max frame rate instead of the background max frame rate without realizing it.

**Comment by surapunoyousei** [comment]
OK
