### ISSUE TITLE
[Bug]  QR-Code Title not in English

### ISSUE THREAD

**Issue by Nachtpfoetchen** [Floorp-Projects/Floorp#488]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When clicking on the icon in the url-bar, the Title over the qr code says "QR コードをスキャンしてください"
instead of the alt text of the image suggests: "Scan me!"

### To Reproduce

Click on th QR-code icon

### Expected behavior

Text says "Scan me!"

### Screenshots

![grafik](https://github.com/Floorp-Projects/Floorp/assets/47748053/b2dc6f0f-ec45-46b4-a4df-e476c233ffc9)

### OS Info

Debian 12 stable

### Floorp Version

11.4.1 (64-Bit)

**Comment by surapunoyousei** [comment]
We will fix it

**Comment by surapunoyousei** [comment]
<img width="1130" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/73892113/f2072767-3a03-47ce-b1c2-2c17b410130a">

Hi, I reimplement QR-code generator. It can be applied localization.

**Comment by jqtmviyu** [comment]
Would you consider removing the built-in qr code feature and using the extensions of the store, for example: https://addons.mozilla.org/en-US/firefox/addon/qr-code-address-bar/, its experience is better.

**Comment by Nachtpfoetchen** [comment]
This example looks pretty outdated to me (last update was 2 years ago). And most others that i found in the addon store don't integrate the qr code button in the url bar (like https://addons.mozilla.org/de/firefox/addon/url-to-qrcode/) or are more outdated (like https://addons.mozilla.org/de/firefox/addon/qr-code-fx-q/) so i really appreciate the floorp re implementation. Also the tab icon in the middle looks really pretty!

**Comment by surapunoyousei** [comment]
Infact, Addons cannot follow browser theme & color, however native implement makes it could
