### ISSUE TITLE
[Bug] Tab text becomes white when light theme enabled and tabs are on the left

### ISSUE THREAD

**Issue by Sukuratchi** [Floorp-Projects/Floorp#489]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When selecting certain tabs, some tabs make the text on them go white, some go black (as it should be)

Here's an example

https://github.com/Floorp-Projects/Floorp/assets/66184829/3a114cbe-c8b3-4eb1-b5de-e4b413e7fdd1

### To Reproduce

Enable the left side tabs
Enable light mode

### Expected behavior

Text should not be switching to white when there's a light theme enabled

### OS Info

Windows 11 22H2

### Floorp Version

11.4.1

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/5c76b59a-1c05-4ce8-9cb1-9a043f9ddad4)


Did you change Firefox's theme?

**Comment by surapunoyousei** [comment]
or.. Install addon

**Comment by Sukuratchi** [comment]
> ![image](https://user-images.githubusercontent.com/73892113/271942882-5c76b59a-1c05-4ce8-9cb1-9a043f9ddad4.png)
> 
> Did you change Firefox's theme?

I'm using firefox photon - lepton ui
![image](https://github.com/Floorp-Projects/Floorp/assets/66184829/ae6a5eba-18e6-4a7b-9804-9524f7d143aa)

These are the settings
![image](https://github.com/Floorp-Projects/Floorp/assets/66184829/44c7c060-b82f-4f1e-94d1-29c701586f97)


Specifically themes wise I'm not using any, just the default
![image](https://github.com/Floorp-Projects/Floorp/assets/66184829/04ab4216-0217-491a-8ce8-6ab9759f35b5)

**Comment by surapunoyousei** [comment]
Fixed.

**Comment by Sukuratchi** [comment]
Thank you so much!
