### ISSUE TITLE
Themes don't work in Floorp

### ISSUE THREAD

**Issue by Telmesomething** [Floorp-Projects/Floorp#49]
## Describe the bug
When enabling a Firefox theme selected from the addons menu, the theme doesn't display properly.

## To Reproduce
1. Go to [Glass Milk](https://addons.mozilla.org/en-US/firefox/addon/glass-milk/)
2. Install the theme.
## Expected behavior
The theme should display itself the way it does in Mozilla Firefox.

## Screenshots
The theme as is looks in Floorp.
![Floorp Glass Milk](https://user-images.githubusercontent.com/33827636/190852145-fd847cdc-4ac5-43e3-ab84-bd957eb1c4dd.PNG)

The theme as it should appear (as in Firefox)
![FF Glass Milk](https://user-images.githubusercontent.com/33827636/190852199-5d51cdf7-e445-424f-870f-d68c45a785f6.PNG)

## Desktop (please complete the following information):
 - OS: Windows 8.1
 - Floorp Version: 104.4.0

## Additional context
Tried it on a completely new profile without being able to change the result.

**Comment by surapunoyousei** [comment]
Colors seem to change. Default floorp has no border

**Comment by Telmesomething** [comment]
> Colors seem to change. Default floorp has no border

You can maybe see the difference better if the Menu Bar is enabled. 

In Firefox, the text is legible and can be easily read. Also, there's a subtle curve in the theme which isn't present in Floorp.
![glass milk FF](https://user-images.githubusercontent.com/33827636/190860592-377e0997-881d-43b0-bfa9-399ab0d2cfba.PNG)

In Floorp it's completely the opposite with no curve at all and just a flat background which makes it difficult to see what's written on Menu Bar.
![glass milk floorp](https://user-images.githubusercontent.com/33827636/190860659-2771beab-361d-4b5b-8e93-e8dd350e4f1a.PNG)

Floorp seems to just overlay the original Windows colour scheme visible in this screenshot with a grey film. 

![default colours](https://user-images.githubusercontent.com/33827636/190861067-433d8305-245f-44d3-8257-c66193bed997.PNG)

**Comment by regularenthropy** [comment]
> > Colors seem to change. Default floorp has no border
> 
> You can maybe see the difference better if the Menu Bar is enabled.
> 
> In Firefox, the text is legible and can be easily read. Also, there's a subtle curve in the theme which isn't present in Floorp. ![glass milk FF](https://user-images.githubusercontent.com/33827636/190860592-377e0997-881d-43b0-bfa9-399ab0d2cfba.PNG)
> 
> In Floorp it's completely the opposite with no curve at all and just a flat background which makes it difficult to see what's written on Menu Bar. ![glass milk floorp](https://user-images.githubusercontent.com/33827636/190860659-2771beab-361d-4b5b-8e93-e8dd350e4f1a.PNG)
> 
> Floorp seems to just overlay the original Windows colour scheme visible in this screenshot with a grey film.
> 
> ![default colours](https://user-images.githubusercontent.com/33827636/190861067-433d8305-245f-44d3-8257-c66193bed997.PNG)

Did you change the theme settings in Floorp, or is it the default one?
PS: What Linux distribution is it?

**Comment by surapunoyousei** [comment]
@regularenthropy 

His OS is Windows 8.1

**Comment by Telmesomething** [comment]
Hi,

Works perfectly!

Thank you very much!

Best regards,

Terence Verney

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Sep 19, 2022, 12:41 by ***@***.***:

**Comment by regularenthropy** [comment]
@surapunoyousei The problem was related to an old theme. I think we need to change the old theme to something else (like proton fix ui) to maintain compatibility. I will open a pool request for this, since I can assume that this is not the only user who has encountered this issue.

**Comment by surapunoyousei** [comment]
Defaulting to Proton UI hurts differentiation. That said, given Waterfox's adoption of photon, the day may come when we'll have to consider reverting the design.

Discuss with  other developers

**Comment by Telmesomething** [comment]
For some unknown reason the theme works on Legacy Photon UI now as well. Here's a pix of it.
![theme works in Legacy Photon UI too](https://user-images.githubusercontent.com/33827636/191050434-96d42bc2-682d-4fd3-a8b9-2cbf3b2bd3f2.PNG)

Although changing the theme to "Firefox modern Proton UI" works, the context menu reverts to the plain layout as well. In that respect I prefer the design of the Legacy Photon UI and switched back to it a few minutes ago expecting that the theme would be disabled. But as you can see, the theme is retained and we get the pretty menus back as well. 

So I would suggest leaving the Legacy Photon UI in place otherwise users could become unhappy with the bland menus which go with Modern Photon UI design.

**Comment by surapunoyousei** [comment]
I see. I'm going to take a survey on the official Twitter.

I'm posting in Japanese, so I think voting is difficult, so I'll treat your opinion as one vote.
