### ISSUE TITLE
[Bug] typos on main web page (english version)

### ISSUE THREAD

**Issue by masukomi** [Floorp-Projects/Floorp#490]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

go here: <https://floorp.app/en/>

Under the "Switchable Design" heading it says 

> In addition to the usual Firefox heme customization, allow...

it should say 

> In addition to the usual Firefox **theme** customization, **it allows**...

"theme" is misspelled and regardless of if you add the "it" it is implied, and being singular means allow needs an "s"

### To Reproduce

load the web page in english 

### Expected behavior

correct grammar

### OS Info

n/a

### Floorp Version

n/a

### Additional context

none required

**Comment by surapunoyousei** [comment]
Thanks.
