### ISSUE TITLE
[Bug] Lepton Theme: Performance issue with opening tab

### ISSUE THREAD

**Issue by gunir** [Floorp-Projects/Floorp#493]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

With Lepton Theme enabled, opening new tab is slow and spikes CPU usage.

### To Reproduce

- Change Design to Leptop
- Press Ctrl+T or `+` button
- New Tab opened with delay

- Change back to Proton
- Restart (must)
- Press Ctrl+T or `+` button
- New Tab opened with ZERO delay 

### Expected behavior

New Tab should opens with zero delay

### Screenshots

I recorded a video:

Lepton: https://streamable.com/pkzocv
Proton: https://streamable.com/9mxs20

### OS Info

Windows 10 Latest

### Floorp Version

Floorp Latest

### Additional context

No.

**Comment by surapunoyousei** [comment]
It will be fixed. I send PR

**Comment by gunir** [comment]
> It will be fixed. I send PR

Thanks, I'm so glad it's fixed, Lepton is beautiful, maybe only [OperaGX](https://github.com/Godiesc/firefox-gx) is a bit better.

The issue can now be closed.

**Comment by BarbzYHOOL** [comment]
@gunir close only when it has been fixed

**Comment by surapunoyousei** [comment]
Maybe fixed.

**Comment by gunir** [comment]
> Maybe fixed.

I'll check when patch is available, for now re-opened for checking.

**Comment by surapunoyousei** [comment]
No response close issue
