### ISSUE TITLE
[Bug] : cannot import data from firefox

### ISSUE THREAD

**Issue by BarbzYHOOL** [Floorp-Projects/Floorp#497]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

"Floorp couldn’t find any programs that contain bookmark, history or password data."

Cannot import while I have firefox on my computer. 
Firefox is installed as a .deb on my linux system but floorp as a flatpak, is it the reason?

### To Reproduce

Click import data, doesn't work

### Expected behavior

Should work.

### OS Info

POP OS 22

### Floorp Version

11.4.1

### Additional context

 I can import from brave/opera (but not from floorp strangely) to my firefox but nothing for floorp

**Comment by surapunoyousei** [comment]
Could you give me a screenshot about that?

The import option shouldn't display on the dialog.

**Comment by BarbzYHOOL** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/29780637/faf0068a-c5c2-43f4-96dd-e79cfc98fe1f)
![image](https://github.com/Floorp-Projects/Floorp/assets/29780637/27328e87-1ba5-42fd-a5b2-38a016db6544)

Note: I imported almost all the files one by one (cookies.sqlite etc), but I still miss some localstorage stuff

**Comment by surapunoyousei** [comment]
Well, What that?

Is the "Import from Firefox" visible on your Floorp?

**Comment by regularenthropy** [comment]
I think, you need to give Floorp an access to your home folder, so it will be able to access local .firefox folder with profiles.

sudo flatpak override one.ablaze.floorp --filesystem=host

This may solve the issue.

**Comment by surapunoyousei** [comment]
> ### Attention!
> 
>     * [x]  I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.
> 
> 
> ### Describe the bug
> 
> "Floorp couldn’t find any programs that contain bookmark, history or password data."
> 
> Cannot import while I have firefox on my computer. Firefox is installed as a .deb on my linux system but floorp as a flatpak, is it the reason?
> ### To Reproduce
> 
> Click import data, doesn't work
> ### Expected behavior
> 
> Should work.
> ### Screenshots
> 
> _No response_
> ### OS Info
> 
> POP OS 22
> ### Floorp Version
> 
> 11.4.1
> ### Additional context
> 
> I can import from brave/opera (but not from floorp strangely) to my firefox but nothing for floorp

In my experience, the import option should not be visible; Flatpak is sandboxed by the system and therefore not obtainable in many cases.

**Comment by surapunoyousei** [comment]
Firefox also causes problems in the case of via Flatpak, so this is not an issue we need to deal with.

**Comment by BarbzYHOOL** [comment]
> Well, What that?
> 
> Is the "Import from Firefox" visible on your Floorp?

no

> I think, you need to give Floorp an access to your home folder, so it will be able to access local .firefox folder with profiles.
> 
> sudo flatpak override one.ablaze.floorp --filesystem=home
> 
> This may solve the issue.

Same result

**Comment by BarbzYHOOL** [comment]
I installed Floorp from PPA and it could import from Brave or Opera but not from Firefox, nor from Flatpak Floorp
