### ISSUE TITLE
[Bug] On your site, it says ublock Origin is installed but it's not

### ISSUE THREAD

**Issue by BarbzYHOOL** [Floorp-Projects/Floorp#499]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

> Floorp は Firefox をベースにしているため、Firefox と同じレベルの包括的な保護を利用できます。また、起動時にインストールされる uBlock Origin を有効にすれば、広告をブロックしより安全にブラウジングできます。

I had to install ublock origin myself

### To Reproduce

https://support.ablaze.one/articles/floorp/is-floorp-secure-browser

### Expected behavior

Fixed text

### OS Info

linux

### Floorp Version

lalala

### Additional context

also references to frea search seem outdated

**Comment by surapunoyousei** [comment]
Unlike Mozilla, I currently work Floorp by myself, from creating new features to writing support articles and release notes.

To be honest, I am completely under-resourced.

I am a student and attending college, so I am limited. Please forgive me where past articles have not been updated.

**Comment by BarbzYHOOL** [comment]
oh okay

I just wanted to help out with that documentation though

**Comment by surapunoyousei** [comment]
Need access to the private repository and I will update it when I have time.
