### ISSUE TITLE
White Page Bug

### ISSUE THREAD

**Issue by Ayush-Kumar-web** [Floorp-Projects/Floorp#505]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Hey I came across this browser it's mind blowing and fantastic both in UI and performance.
I have installed this on my windows 11 pc and it works flawlessly I am quite satisfied with it.
I installed it on my laptop too But I am facing a strange bug 
Whenever I open new tab it shows white page after closing the browser and reopening it new tab does show unsplash image but reopening new tab after that prompts this strange phenomenon

### To Reproduce

1. New tag page

### Expected behavior

Should Display Unsplash Image

### Screenshots

![bug](https://github.com/Floorp-Projects/Floorp/assets/69073878/d4a3c342-533d-48ac-bc3e-2050c832b674)

### OS Info

Windows 10 21H2

### Floorp Version

11.4.1

**Comment by 32bitx64bit** [comment]
Same issue here on Linux
using Floorp 11.5.0 (64bit)
On Arch Linux using KDE Plasma X11

Also using Intel with Iris XE graphics.

Hopefully this bug gets fixed as its legit a flash bang during night usage.

**Comment by 32bitx64bit** [comment]
Issue still exists in the stable version of 11.5.0

**Comment by creeper-0910** [comment]
Delete the profile or use [Floorp-portable](https://github.com/Floorp-Projects/Floorp-Portable/releases) to see if the problem occurs.

**Comment by creeper-0910** [comment]
The hardware acceleration feature does not seem to work well with Iris.
Please turn it off and see if your symptoms improve.

https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration

**Comment by 32bitx64bit** [comment]
> The hardware acceleration feature does not seem to work well with Iris. Please turn it off and see if your symptoms improve.
> 
> https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration

I doubt its hardware acceleration issue, the fast browser worked with it on and didnt have this issue.

**Comment by Ayush-Kumar-web** [comment]
> Same issue here on Linux using Floorp 11.5.0 (64bit) On Arch Linux using KDE Plasma X11
> 
> Also using Intel with Iris XE graphics.
> 
> Hopefully this bug gets fixed as its legit a flash bang during night usage.|
> 
> Edit : IT only happens for me when I load a webpage in any tab.

I switched to linux and tried this browser again 
Didn't encounter that problem

did you find any solutions yet?

**Comment by surapunoyousei** [comment]
Since Lightning and regular Floorp share the exact same code for new tabs, it seems unlikely that the problem is occurring in Floorp.

I have seen this bug in Firefox as well, so it is probably a Firefox bug, not a Floorp bug. There are actually some Firefox users on the Internet who have encountered this bug.

I have not seen it so it must be a problem with your customization.

Therefore, I will wait for Mozilla to fix it.

Translated with www.DeepL.com/Translator (free version)

**Comment by 32bitx64bit** [comment]
Found a fix for anyone looking

Go into about:config
and disable "browser.newtab.preload" 
For some reason newtab preload causes this issue, disabling it has sense made the issue vanish lmao. *atleast for me*

**Comment by 32bitx64bit** [comment]
Found a sorta fix.
Go to about:Config
and disable "browser.newtab.preload"
It makes it way worse, though it still does it **sometimes** though it doesnt happen often for me.
