### ISSUE TITLE
[Bug] Installation fails on Debian 11.7

### ISSUE THREAD

**Issue by hcsaustrup** [Floorp-Projects/Floorp#506]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Followed the installation guide - got this error when running `apt install floorp`:

```
$ sudo apt install floorp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  floorp
0 upgraded, 1 newly installed, 0 to remove and 79 not upgraded.
1 not fully installed or removed.
Need to get 0 B/92,3 MB of archives.
After this operation, 299 MB of additional disk space will be used.
dpkg-deb: error: archive '/var/cache/apt/archives/floorp_11.4.1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/floorp_11.4.1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/floorp_11.4.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The installation page did not indicate any specific version of Debian, so I assumed that this would work?

### To Reproduce

Follow installation guide for Linux on Debian 11.7.

### Expected behavior

Installation works.

### OS Info

Debian 11.7 (amd64)

### Floorp Version

11.4.1

**Comment by creeper-0910** [comment]
I'll check.

**Comment by creeper-0910** [comment]
The installation seems to succeed in my environment.
Try downloading and installing the .deb file from here.
https://ppa.floorp.app/amd64/floorp-11.4.1.deb

**Comment by creeper-0910** [comment]
I found the cause.
It appears that dpkg does not support the zstd format in Debian 12 and earlier versions.
https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg/745467#745467

**Comment by creeper-0910** [comment]
We would like to add Debian 12 or later as a recommended environment. We apologize for any inconvenience.
