### ISSUE TITLE
[Bug] "Floorp view" icon not available with vertical tabs

### ISSUE THREAD

**Issue by BarbzYHOOL** [Floorp-Projects/Floorp#507]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

"Floorp view" icon not available with vertical tabs, it just disappears

### To Reproduce

Enable vertical tabs and see it disappear

### Expected behavior

Available in the overflow menu

### OS Info

POP OS 22

### Floorp Version

11.4.1

**Comment by surapunoyousei** [comment]
This is not an unexpected behavior. Toolbar buttons are not available on vertical tabs.

**Comment by BarbzYHOOL** [comment]
wtf

**Comment by BarbzYHOOL** [comment]
seems like you fixed it with the new vertical tabs! :)

**Comment by surapunoyousei** [comment]
Yeah. Re-implemente fixs this issue
