### ISSUE TITLE
[Bug] browser cannot start with full screen

### ISSUE THREAD

**Issue by CodingPlatelets** [Floorp-Projects/Floorp#508]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When double clicked the floorp button on desktop, it will start the main window. However, it wouldn't act as firefox or ms edge, it will just show a little window with specific size. I can not find a way to adjust it. If this is designed on purpose?
![image](https://github.com/Floorp-Projects/Floorp/assets/58300006/dc0675fe-37e8-476e-be2b-2473701fdfa7)

### To Reproduce

1. open the browser
2. everything will show

### Expected behavior

act like 
![image](https://github.com/Floorp-Projects/Floorp/assets/58300006/fcb7b763-9133-41cd-97ce-58834b19c946)

### OS Info

windows 11 22h2 22621.2428

### Floorp Version

11.4.1

**Comment by kaos-55** [comment]
Hi, it seems to be a problem with the fingerprint block.
Are you by any chance using a script like Arkenfox?
Search in about:config for the key "privacy.resistFingerprinting" and set it to false.

**Comment by surapunoyousei** [comment]
No response close issue.

**Comment by rampageX** [comment]
> Hi, it seems to be a problem with the fingerprint block. Are you by any chance using a script like Arkenfox? Search in about:config for the key "privacy.resistFingerprinting" and set it to false.

Thanks, work here!
