### ISSUE TITLE
Major Privacy Issues

### ISSUE THREAD

**Issue by schoolprivacy** [Floorp-Projects/Floorp#51]
I think you need to remove Privacy from your advertisement of this browser.
This is false advertisement.

So many connections when start the browser.

contile.services.mozilla.com  
aus5.mozilla.org
services.addons.mozilla.org  
support.mozilla.org 
unsplash.com
repo.ablaze.one
blog.ablaze.one
support.ablaze.one
wiki.mozzila.org
addons.mozilla.org
www.amazon.com
floorp.ablaze.one
google.com

**Comment by surapunoyousei** [comment]
The Mozilla-related connection comes from Firefox and is therefore required in terms of browser functionality.
 ```
 contile.services.mozilla.com
 aus5.mozilla.org
 services.addons.mozilla.org
 support.mozilla.org 
 wiki.mozzila.org
 addons.mozilla.org 
 ```
 repo.ablaze.one is for checking for updates blog.ablaze.one and floorp.ablaze.one are for showing release notes on first launch.
 support.ablaze.one is for our privacy policy.

 Amazon and Google are also based on search engines, so I will close it by judging it to be the minimum necessary.

**Comment by surapunoyousei** [comment]
Amazon.co.jp may be deleted in the future.

**Comment by Flashwalker** [comment]
E.g. [LibreWolf](https://librewolf.net/) trying only few:

```
push.services.mozilla.com
shavar.services.mozilla.com
addons.mozilla.org
```

**Comment by creeper-0910** [comment]
Comparing Librewolf and Floorp is a mistake.

**Comment by surapunoyousei** [comment]
> E.g. [LibreWolf](https://librewolf.net/) trying only few on startup:
> 
> ```
> push.services.mozilla.com
> shavar.services.mozilla.com
> addons.mozilla.org
> ```

We are completely open source in form, so if you are interested in the communication content, I suggest you take a look at the source code. Also, Librewolf does not have an update system, and it is not reasonable to compare it to Floorp's functionality-oriented derivation.

At a minimum, no telemetry harvesting, no bundleware, and strong tracking protection, Librewolf does not seem to consider Mozilla's revenue, but we respect Mozilla by showing ads on new tab icons such as Google and We hope it will lead to an increase in revenue.

Derivative browsers should honor and respect their derivatives.

**Comment by surapunoyousei** [comment]
However, this is just our opinion, since promoting the Gecko engine, as Librewolf and Floorp do, is already a contribution to Mozilla.

Librewolf has its good points, and we think Floorp has its good points too.
