### ISSUE TITLE
[Bug] (Daylight 11.5.0) 設定のデザインの項目が開けない

### ISSUE THREAD

**Issue by menndouyukkuri** [Floorp-Projects/Floorp#510]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

設定の デザイン の項目 (about:preferences#design) が開けなくなっています。

### To Reproduce

1. 設定を開く
2. デザイン をクリックしても開かない

### Expected behavior

設定の デザイン の項目を開くことができる。

### OS Info

Windows 11 22H2

### Floorp Version

Daylight 11.5.0

**Comment by surapunoyousei** [comment]
垂直タブを改造中です。その影響で開けない状態になっていると思います。

今後元に戻りますのでお気になさらず

**Comment by menndouyukkuri** [comment]
開けるようになったのを確認したので閉じます。
