### ISSUE TITLE
[Bug] Floorp always prefers HTTP/2 over HTTP/3

### ISSUE THREAD

**Issue by federicotorrielli** [Floorp-Projects/Floorp#512]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

For some reason, when using floorp, it always prefers HTTP/2 over HTTP/3. This is a big deal given that the flags in the config are enabled correctly...

### To Reproduce

Go to https://cloudflare-quic.com/

### Expected behavior

It should default to HTTP/3 on most sites

### OS Info

Arch Linux - rolling

### Floorp Version

11.4.1

**Comment by 32bitx64bit** [comment]
You can forcefully make it use http/3 by going into about:config and turning off http2.
Though do expect compatibility losses on older websites who havent updated to http/3.

**Comment by federicotorrielli** [comment]
> Edit - it appears firefox uses http2 to connect to a website at first, refreshing the page seems to use http3, atleast according to cloudflares website.
This is not true (in my case), even when reloading several times websites like cf or https://http3.is/
Maybe is a Linux thing?
> You can forcefully make it use http/3 by going into about:config and turning off http2
I'm not going to disable everything for this. All I want is an option for preference, such as "use http/3 when is available, use http/2 all the other times"

**Comment by creeper-0910** [comment]
Which version are you using?
Flatpak?AUR?

**Comment by federicotorrielli** [comment]
> Which version are you using? Flatpak?AUR?

AUR

> I have tried this in my environment and it seems that HTTP/2 is used for the first access and HTTP/3 is used from the second.

In my case it chooses HTTP/2 every time

@creeper-0910

**Comment by typeling1578** [comment]
Information that may be helpful

> Thanks for the log! It's really helpful.
>
> The problem here is that the http3 connection is not ready within 50ms (defined in this pref network.dns.httpssvc.http3_fast_fallback_timeout), so we switch to use http2 connection.
> I'd suggest to set network.dns.httpssvc.http3_fast_fallback_timeout to a larger value or set it to 0 for disabling it.

https://bugzilla.mozilla.org/show_bug.cgi?id=1701829#c4

**Comment by 32bitx64bit** [comment]
> Information that may be helpful
> 
> > Thanks for the log! It's really helpful.
> > The problem here is that the http3 connection is not ready within 50ms (defined in this pref network.dns.httpssvc.http3_fast_fallback_timeout), so we switch to use http2 connection.
> > I'd suggest to set network.dns.httpssvc.http3_fast_fallback_timeout to a larger value or set it to 0 for disabling it.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1701829#c4

Lol, 3 year old bug thats still not resolved. smh. Typical firefox though.
