### ISSUE TITLE
[Bug] `Ctrl + w` on last tab should quit the browser

### ISSUE THREAD

**Issue by rahul0x00** [Floorp-Projects/Floorp#513]
### Attention!

- [x] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Closing the last tab in normal as well as in incognito mode with `Ctrl + w ` should quit the browser

### To Reproduce

1. Keep only 1 tab.
2. Try to close it with `ctrl+w` shortcut, it won't close

### Expected behavior

`ctrl+w` shortcut on the last tab  should close the browser

### OS Info

Kali Linux 2023.2

### Floorp Version

11.4.1 (64-bit)

**Comment by creeper-0910** [comment]
This is not a bug but a specification.
To disable this behavior, set "browser.tabs.closeWindowWithLastTab" to true.
