### ISSUE TITLE
[Bug][Floorp Daylight] Vertical Tab -> on, restart -> no Vertical Tab at all

### ISSUE THREAD

**Issue by gunir** [Floorp-Projects/Floorp#516]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Vertical Tab disappear after restart

### To Reproduce

- Go to settings
- Design
- Vertical Tab
- Restart
- Check image

![image](https://github.com/Floorp-Projects/Floorp/assets/134402102/3c5cad22-ed77-41b0-a244-cba739a77810)

### Expected behavior

Vertical Tab should appear normally

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/134402102/3c5cad22-ed77-41b0-a244-cba739a77810)

### OS Info

Windows 10

### Floorp Version

Floorp Daylight 1.15.0

### Additional context

No.

**Comment by surapunoyousei** [comment]
Recently commit will fix this issue.
