### ISSUE TITLE
About "Color the Tab Bar using the current website's favicon color" 

### ISSUE THREAD

**Issue by callmehanu** [Floorp-Projects/Floorp#518]
### Attention!

- [x] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I've active this feature but anything change.

### To Reproduce

1. Go Settings
2. Go to Design section
3. Turn On "Color the Tab Bar using the current website's favicon color" 

### Expected behavior

I waiting for a color change in the current tab based in its icon.

### Screenshots

![imagen](https://github.com/Floorp-Projects/Floorp/assets/13230502/99818d7c-f4af-4d12-8536-b5b9eca76e98)

### OS Info

Linux - Fedora 38

### Floorp Version

11.4.1 (64-bit)

**Comment by surapunoyousei** [comment]
This is a known issue and is design specific with no plans to fix it.
