### ISSUE TITLE
"Hidden button" in Gnome Theme

### ISSUE THREAD

**Issue by callmehanu** [Floorp-Projects/Floorp#519]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

In the top rigth position appears a button with appears without any icon, just as a ghost.
When I clicked Floorp show up a message to close all current tabs. 

### To Reproduce

1. Go to the top right position in the topbar
2. Click the hidden button

### Expected behavior

I really prefer don´t show any actions in that ubication.

### Screenshots

![imagen](https://github.com/Floorp-Projects/Floorp/assets/13230502/2d55f4f2-5c8d-4d63-9b94-a66800d66236)
![imagen](https://github.com/Floorp-Projects/Floorp/assets/13230502/24bff23a-fc71-414f-9fbf-c974431dc202)

### OS Info

Fedora 38

### Floorp Version

11.4.1 (64-bit)

**Comment by surapunoyousei** [comment]
This is a known issue and is design specific with no plans to fix it.
