### ISSUE TITLE
Hide title bar option does not work.

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#52]
## Describe the bug
When the title bar option is disabled, the title bar is not hidden.

## To Reproduce
1. Open Browser
2. Go to customize toolbar
3. Uncheck the title bar checkbox
4. The title bar is not hidden

## Expected behavior
When unchecking the title bar checkbox the title bar disappears

## Screenshots
![Captura de pantalla_2022-09-18_13-47-47](https://user-images.githubusercontent.com/86812371/190910632-53e18a69-de4f-44b7-bf47-288c4aaff72e.png)

## Desktop (please complete the following information):
 - OS: Linux x86_64
 - Floorp Version: 10.5.0 and 10.4.0

## Additional context
I don't know if this option worked in other versions or if this is the behavior desired by the developers in the browser.

**Comment by surapunoyousei** [comment]
It looks like a Linux distribution specific issue. At least it works fine on Debian, Ubuntu and LinuxMint.

**Comment by surapunoyousei** [comment]
What about Firefox?

**Comment by kaos-55** [comment]
Thank you for your response.
I just tried it in another distribution and the option works in both Floorp and Firefox.
My fault for not testing on another distro 🤦‍♂️
As I have never had such a problem in any distro until now, I assumed that there was a problem on the browser side.
I close the issue and sorry for the inconvenience.
