### ISSUE TITLE
[Bug] Floorp does not save tabs when closing the browser

### ISSUE THREAD

**Issue by BabarKhanDev** [Floorp-Projects/Floorp#521]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I have enabled "open previous windows and tabs" In settings > general > startup

Expected behaviour:
When I close the browser and then reopen it my tabs should reopen

Actual behaviour:
When I close the browser I get a window asking if I want to close my tabs, then when I reopen the browser my tabs are gone

### To Reproduce

Open some tabs
Close the browser
Reopen the browser

### Expected behavior

The opened tabs should remain

### OS Info

Apple Silicon 13.4

### Floorp Version

11.4.1

**Comment by gunir** [comment]
It works for me, make sure you don't have this checked:

![image](https://github.com/Floorp-Projects/Floorp/assets/134402102/a34da46f-11d4-425e-862b-4a5de9352103)

**Comment by surapunoyousei** [comment]
No response. Close issue
