### ISSUE TITLE
[Bug] 垂直タブ+ツールバーに検索バーを配置でデザインがおかしくなる

### ISSUE THREAD

**Issue by menndouyukkuri** [Floorp-Projects/Floorp#525]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

垂直タブに設定した状態で検索バーをツールバーに配置するとこれまでになかった崩壊が起こります。

言葉で表現しづらかったので詳しくは添付したスクリーンショットを参照していただきたいのですが、ツールバーの縦の幅が不自然に広くなり、アドレスバーが上よりにズレ、検索バーの背景がツールバーの右端まで続いてしまっています。

なお、アドレスバーより左側に多くのアイテムが配置されていて、右側のアイテムがオーバーフローメニューに格納されている場合は起こらないようです。

### To Reproduce

1. 垂直タブに設定
2. 検索バーをツールバーに配置

### Expected behavior

ツールバーの縦の幅は不自然に広くならず、アドレスバーは上下方向にズレず、検索バーの背景は検索バーの長さ分しか持続しません。

### Screenshots

- 発生した例
![2023-10-24_01h56_39](https://github.com/Floorp-Projects/Floorp/assets/61068665/60c8098f-9ffd-487f-af71-89209f957b25)

- 発生しない例
![2023-10-24_01h59_19](https://github.com/Floorp-Projects/Floorp/assets/61068665/b7273c08-f0ff-47d6-9427-55925aef8b1f)

### OS Info

Windows 11 / 10 22H2

### Floorp Version

11.5.0

### Additional context

Daylightでも発生します。

**Comment by surapunoyousei** [comment]
なおった
