### ISSUE TITLE
[Bug] No scrollbar on vertical tabs

### ISSUE THREAD

**Issue by BarbzYHOOL** [Floorp-Projects/Floorp#526]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The new vertical tabs is great, it scrolls fast but there is no scrollbar so we don't know where we are

### To Reproduce

Try it with many tabs open

### Expected behavior

See the scrollbar

### OS Info

POP OS 22

### Floorp Version

11.5

**Comment by surapunoyousei** [comment]
I also removed the scrollbar on vertical tabs so that horizontal tabs don't have scrollbars

**Comment by BarbzYHOOL** [comment]
what about adding it as an option? or only if vertical tabs are enabled?
but it's a low priority issue, for sure
