### ISSUE TITLE
[Bug] "Keep Tab awake" menu item does not update its "checked" state for the target tab's context menu

### ISSUE THREAD

**Issue by aruraune** [Floorp-Projects/Floorp#529]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

While the "Enable Sleeping Tabs" option is active, the menu checkbox item "Keep Tab awake" is added to each tab's context menu.

When right-clicking a tab, this option does not represent if the tab is kept awake or not, but instead, it keeps its state from the last time the user interacted with the checkbox menu item.

### To Reproduce

1. Make sure the "Enable Sleeping Tabs" setting active.
2. Have two or more tabs open.
3. Right-click any tab and confirm that the "Keep Tab awake" is not checked.
4. Click the "Keep Tab awake" option and confirm that it is now checked.
5. Right-click any other tab and verify if it's still checked.
6. Click the "Keep Tab awake" option and confirm that it is now unchecked.
7. Right-click the first tab and confirm that the "Keep Tab awake" is unchecked, while the 3rd action should have enabled its sleeping tab exclusion.

### Expected behavior

The "Keep Tab awake" option should reflect if a tab is marked to not be suspended when the "Enable Sleeping Tabs" is activated.

### Screenshots

This video was recorded to reproduce the bug on a clean profile:
https://streamable.com/klxwm2

### OS Info

Arch Linux x86_64 (6.5.8-arch1-1)

### Floorp Version

11.5.0 (be26b7fc, build_id: 20231022102100, flatpak ref: app/one.ablaze.floorp/x86_64/stable, commit: e207f6d5cc8d146cdbf5c8f7fc662b8884c00cbfc38b14f88e00df0c6a6fdc95)

### Additional context

From my short investigation, I believe the issue is related to this:
https://github.com/Floorp-Projects/Floorp-core/blob/efb9d46ee6227bf695f90864d4f1b463bd2ece1c/browser/components/tabsleep/TabSleep.sys.mjs#L372

I believe either `popupshowing` event isn't being fired, or `e.currentTarget` is referring to something else. I could be wrong, though, I did not have time yet to compile or test other versions.

**Comment by surapunoyousei** [comment]
No response. Close issue
