### ISSUE TITLE
[Bug] vertical tabs: two bugs

### ISSUE THREAD

**Issue by BarbzYHOOL** [Floorp-Projects/Floorp#530]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

- no easy way to go at the bottom of the list: ctrl+tab does not bring the view to the current tab, opening a new tab does not bring the view to the current tab, and the only way to go to the bottom of the list is to scroll with the mouse wheel (cannot use keyboard, cannot select the scrollbar)
- vertical tab panel width is not remembered when you restart floorp
- modifying the vertical tab panel width is on the right side (on the border of the screen) but it should be on the left side. I suppose it's because when we have both sidebars, it must be on the right side. But when the bookmark sidebar is hidden, then it should switch.
- we cannot hide the panel anymore (already reported on reddit by some people)
- when we watch a video fullscreen, the panel is still visible

### To Reproduce

try ctrl+tab, ctrl+t, or arrows
try to change the width

### Expected behavior

logical behavior as explained

### OS Info

POP OS 22

### Floorp Version

11.5

**Comment by thepick** [comment]
I have the same problem that vertical tab panel width is not remembered when restarting Floorp. I'm on Windows 11 with Floorp 11.5.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by BarbzYHOOL** [comment]
@surapunoyousei I had edited the issue the next day and added 3 more lines (so more than 2 issues). I'm just pointing it out in case you have not read it yet.

These

> modifying the vertical tab panel width is on the right side (on the border of the screen) but it should be on the left side. I suppose it's because when we have both sidebars, it must be on the right side. But when the bookmark sidebar is hidden, then it should switch.
we cannot hide the panel anymore (already reported on reddit by some people)
when we watch a video fullscreen, the panel is still visible

**Comment by BarbzYHOOL** [comment]
> no easy way to go at the bottom of the list: ctrl+tab does not bring the view to the current tab, opening a new tab does not bring the view to the current tab, and the only way to go to the bottom of the list is to scroll with the mouse wheel (cannot use keyboard, cannot select the scrollbar)

this thing is so annoying, i feel like stopping  to use vertical tabs completely
