### ISSUE TITLE
AUR floorp is not passing validity checks

### ISSUE THREAD

**Issue by DahTach** [Floorp-Projects/Floorp#531]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Having some trouble installing floorp via YAY.
AUR package appears not to be passing a validity check for floorp-11.5.0.linux-x86_64.tar.bz2.
Log below:
```
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with md5sums...
    Creater_pack_Floorp.zip ... Passed
    floorp.desktop ... Passed
==> Validating source_aarch64 files with md5sums...
    floorp-11.5.0.linux-x86_64.tar.bz2 ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

### To Reproduce

`yay floorp`

### Expected behavior

expected aarch64 package of floorp browser to install

### OS Info

Asahi Linux - Alarm Minimal

### Floorp Version

11.5.0

**Comment by surapunoyousei** [comment]
AArch 64 is unspoorted on AUR.
