### ISSUE TITLE
[Bug] macOS Floorp Daylight.app damaged or incomplete.

### ISSUE THREAD

**Issue by GollyJer** [Floorp-Projects/Floorp#532]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I get this when trying to run the app.
<img width="251" alt="SCR-20231024-sklb" src="https://github.com/Floorp-Projects/Floorp/assets/689204/e1dc6bba-3731-4220-a49c-b7fc2b42edb9">

### To Reproduce

Try and run on macOS with this configuration.
<img width="266" alt="SCR-20231024-skzv" src="https://github.com/Floorp-Projects/Floorp/assets/689204/0349232b-06b4-49f5-b0b1-6532614d2f3b">

### Floorp Version

Release v11.5.0

**Comment by surapunoyousei** [comment]
Could you try to reinstall?

**Comment by lukepolak** [comment]
I've got the same problem, Macbook Pro with Apple M1 chip, on Sonoma 14.0. I tried 11.5.0 and 11.5.1-lightning, both got same error at startup as @GollyJer and app doesn't show icon in Finder:

![image](https://github.com/Floorp-Projects/Floorp/assets/16986690/9a313e3c-1324-4631-9ade-76373630bad4)

**Comment by lukepolak** [comment]
Also, I just checked previous version (11.4.1) and it works.

**Comment by surapunoyousei** [comment]
Lightning build is not stable.

**Comment by surapunoyousei** [comment]
> ### Attention!
> 
>     * [x]  I understand that Floorp is NOT supported on Windows 7/8.1 or lower.
> 
> 
> ### Describe the bug
> 
> I get this when trying to run the app. <img alt="SCR-20231024-sklb" width="251" src="https://user-images.githubusercontent.com/689204/277871450-e1dc6bba-3731-4220-a49c-b7fc2b42edb9.png">
> ### To Reproduce
> 
> Try and run on macOS with this configuration. <img alt="SCR-20231024-skzv" width="266" src="https://user-images.githubusercontent.com/689204/277871591-0349232b-06b4-49f5-b0b1-6532614d2f3b.png">
> ### Floorp Version
> 
> Release v11.5.0

Well, What version before you updated

**Comment by surapunoyousei** [comment]
Fixed

**Comment by GollyJer** [comment]
@surapunoyousei Will the fix be in a future build? I don't see a way to try the fixed version yet. Thanks!

**Comment by surapunoyousei** [comment]
11.5.1 is target

**Comment by josh-clarke** [comment]
This is still occurring for me with the 11.5.1 pre-release.

**Comment by surapunoyousei** [comment]
What is prerelease

**Comment by josh-clarke** [comment]
<img width="880" alt="Screen Shot 2023-10-29 at 6 12 57 PM" src="https://github.com/Floorp-Projects/Floorp/assets/1128799/6828399d-a21e-46d5-97eb-8a89580bf617">

**Comment by surapunoyousei** [comment]
It's lightning. Not stable build. Do not use it.
