### ISSUE TITLE
[Bug] macOS App Damaged or Incomplete

### ISSUE THREAD

**Issue by sidnoway** [Floorp-Projects/Floorp#533]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The app appears to be damaged when trying to open it. I'm not sure whether this is because I am on an Intel machine or what, but I'm on the latest macOS, so I don't think it has to do with the age of my machine other than the Intel processor.

### To Reproduce

1. Mount Image
2. Install Program
3. Attempt to run program

### Expected behavior

Program runs

### Screenshots

https://files.catbox.moe/dnnkjg.png
https://files.catbox.moe/zc8cy9.png
https://files.catbox.moe/2nhux8.png

### OS Info

macOS Sonoma 14.0

### Floorp Version

11.5.0

### Additional context

My machine uses OpenCore Legacy Patcher to run the latest version of macOS without Apple's support

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/532
