### ISSUE TITLE
[Bug] Browser Manager Sidebar doesn't remember it's open/close state.

### ISSUE THREAD

**Issue by GollyJer** [Floorp-Projects/Floorp#534]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I close the browser and reopen the sidebar is always closed even though I had it open when closing.

### To Reproduce

open the sidebar, restart browser, sidebar is closed.

### Expected behavior

sidebar remains open

### OS Info

Windows 11

### Floorp Version

11.5.0

**Comment by surapunoyousei** [comment]
This is not unexpected behavior

**Comment by GollyJer** [comment]
Ah. Sorry @surapunoyousei.
Should I enter this as a feature request? It could be a setting for the Browser Manager.
