### ISSUE TITLE
[Bug] Cannot remove extension buttons from the toolbar or move to the overflow menu when "Unified Extension button" is off

### ISSUE THREAD

**Issue by Sollace** [Floorp-Projects/Floorp#535]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I see in the new update you can now remove the unified extensions. Thanks for that! I really appreciate it.

Unfortunately turning it off isn't very useful on its own if it doesn't allow you to also unpin or move the extension buttons to the overflow menu like in previous versions.

### To Reproduce

1. Open Floorp
2. Click on the unified extensions button
3. Right-click one or more extensions and select "Pin to toolbar" so a button is created for that extension
4. Right-click the toolbar and select "Customise Toolbar..."
5. Uncheck "Unified Extension Button" checkbox
6a. Drag and drop the button for one of the extensions off the toolbar
6b. Drag and drop the button for one of the extensions into the "Overflow Menu"

### Expected behavior

I should be able to move the button to either of the areas mentioned in 6a and 6b, like you could before the "Unified Extensions Button" was added to firefox. 

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/6429283/2a8444ea-2b53-48af-b90c-20dd8f506741)

### OS Info

ManjaroKDE

### Floorp Version

11.5.0 (64-bit) (flatpak)

**Comment by surapunoyousei** [comment]
Haha

FIrefox's issue

**Comment by Sollace** [comment]
> Haha
> 
> FIrefox's issue

Firefox doesn't allow you to remove the unified extensions button. That's a Floorp feature.

**Comment by surapunoyousei** [comment]
Then why did you make it a bug?

**Comment by Sollace** [comment]
> Then why did you make it a bug?

It's just that what I described in this issue is meant to be part of #340, which was included in the recent release.

Removing the unified extensions button is useless if it doesn't allow you to remove or drag extension buttons into the overflow menu. It's supposed to restore the old behaviour fully, and without doing that I don't consider the feature it to be working correctly.

If you think this is better as a feature request I can change it.
