### ISSUE TITLE
[Bug] Multiple line separator on context menu

### ISSUE THREAD

**Issue by ridwanpratama** [Floorp-Projects/Floorp#537]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

After I right-click on any button and then right-click on another object on the webpage, there are multiple lines at the top of the context menu.

### To Reproduce

1. Open https://floorp.app/en/
2. Right-click on the "Download" button or any other button.
3. Right-click on anything other than a button.

### Expected behavior

The context menu should be clear without any random separator lines.

### Screenshots

![Screenshot 2023-10-27 150307](https://github.com/Floorp-Projects/Floorp/assets/56720407/ca958499-1588-44b6-b233-2e933e28f9e0)

### OS Info

Windows 11 22H2

### Floorp Version

Floorp Lightning 11.5.1 (64-bit)

**Comment by surapunoyousei** [comment]
Not big problem. I will fix later

**Comment by surapunoyousei** [comment]
Fixed

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/dba790e1-ef79-4e5e-862c-bb36a0c1b3b8)

All good working. Fixesd
