### ISSUE TITLE
[Bug] ポータブル版が11.5以降のバージョンでも11.4.1に更新される

### ISSUE THREAD

**Issue by menndouyukkuri** [Floorp-Projects/Floorp#541]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

ポータブル版が11.5以降のバージョンでも11.4.1に更新される

### To Reproduce

ポータブル版を数回起動する

### Expected behavior

11.5以降のバージョンから11.4.1に更新されることはありません。

### OS Info

Windows 11 22H2

### Floorp Version

11.5.1 ポータブル版

### Additional context

発生しない場合があるようですが、まだ突き止められていません。

**Comment by surapunoyousei** [comment]
I'll fix it

**Comment by surapunoyousei** [comment]
Fixed
