### ISSUE TITLE
[Bug]  window decorations on kde plasma

### ISSUE THREAD

**Issue by Nachtpfoetchen** [Floorp-Projects/Floorp#545]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The window decorations are not the one that are set in the plasma settings. This hinders the integration of floorp to the plasma desktop.

### To Reproduce

1. Install Floorp via ppa on kde plasma
2. Open floorp

### Expected behavior

Floorp using the plasma window decorations

### Screenshots

![Screenshot_20231029_193540](https://github.com/Floorp-Projects/Floorp/assets/47748053/9a399f44-195c-4599-a903-e6072ee4087d)

### OS Info

Debian 12 stable Floorp via ppa

### Floorp Version

11.5.1

### Additional context

KDE Plasma Version: 5.27.5
KDE-Frameworks Version: 5.103.0
QT Version: 5.15.8

**Comment by surapunoyousei** [comment]
It's follow to Firefox. You can make specific build for KDE Plasma.
