### ISSUE TITLE
[Bug] Hardware Acceleration Not Using dGPU and Fails to Switch to iGPU in Windows' Battery Saver Mode

### ISSUE THREAD

**Issue by minlmao** [Floorp-Projects/Floorp#549]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When enabling hardware acceleration for the Floorp browser, it does not utilize the dedicated GPU (dGPU) by default as expected.

### To Reproduce

1. Enable **Use hardware acceleration when available** in about:preferences
2. Setting `layers.acceleration.force-enabled = true` in about:config
3. Setting `HardwareAcceleration = true` in `%ProgramFiles%\Ablaze Floorp\distribution\policies.json`:
```
{
  "policies": {
    "HardwareAcceleration": true
  }
}
```
4. Close Floorp, reboot the computer (if necessary), then reopen Floorp.
5. Observe NVIDIA GPU Activity in system tray seeing Floorp continues to use the integrated GPU (iGPU) instead of the dedicated GPU (dGPU).

### Expected behavior

Floorp's Hardware Acceleration uses the dGPU by default, similar to the behavior in Chromium browsers or Alex313031's Mercury browser.

### OS Info

Windows 11 21H2

### Floorp Version

11.5.1

### Additional context

Another method I tried was to set floorp.exe to "High Performance" in Windows Graphics Settings, but it resulted in Floorp consistently using the laptop's dGPU even when the power-saving mode was enabled. Ordinarily, when Hardware Acceleration functions correctly, it should switch to the integrated card in power-saving mode.

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/issues/378#issuecomment-1691132211

**Comment by minlmao** [comment]
> Try this method. [#378 (comment)](https://github.com/Floorp-Projects/Floorp/issues/378#issuecomment-1691132211)

I can make Floorp use dGPU through Windows Graphics settings or the NVIDIA Control Panel. However, I'd like Floorp to seamlessly switch to the iGPU when I activate the battery saver mode. That's why I want Floorp's Hardware Acceleration to work properly, similar to how Chromium browser or Alex313031's Mercury browser handles it.

**Comment by midvightmirage** [comment]
this is not conpleted on linux you cant use amd dgpu its burning my cpu
