### ISSUE TITLE
[Bug] Vertical tabs have disappeared when the Browser Manager Sidebar is toggled to the OFF position

### ISSUE THREAD

**Issue by thepick** [Floorp-Projects/Floorp#551]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

After the 11.5.1 update, vertical tabs have disappeared when the Browser Manager Sidebar is disabled. However, when browsing to Settings --> Browser Manager Sidebar --> and then toggling on Show the Browser manager Sidebar, the sidebar and vertical tabs reappear together.

### To Reproduce

1. Go to Settings --> Browser Manager Sidebar --> and then toggling OFF Show the Browser Manager Sidebar
2. Go to Settings --> Design --> toggle ON Vertical Tab Bar (experimental)
3. The vertical tabs don't show
4. Leave the Vertical Tab Bar (experimental) set to the ON position
5. Toggle ON the Browser Manager Sidebar and the vertical tabs (along with the Browser Manager Sidebar) appear

### Expected behavior

If I have vertical tabs toggled to the ON position, and the the Browser Manager Sidebar disabled, then the vertical tabs should still show up independently of the BMS.

### OS Info

Windows 11 22H2

### Floorp Version

11.5.1

**Comment by surapunoyousei** [comment]
Fixed issue. Close
