### ISSUE TITLE
[Bug] The setting: 'Hide tabs on Horizontal Tab Bar' resets after each closing of the browser

### ISSUE THREAD

**Issue by delyan-kirov** [Floorp-Projects/Floorp#552]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The setting: 'Hide tabs on Horizontal Tab Bar' resets every time the browser is closed. 

### To Reproduce

1. Turn on the setting: 'Hide tabs on Horizontal Tab Bar' on
2. Turn on the setting: 'Tree style tabs'
3. Exist Floorp
4. Reopen Floorp

### Expected behavior

The setting should be remembered by browser. 

### Screenshots

N/A

### OS Info

- Kernel: 6.5.6-200.fc38.x86_64 - Architecture: x86_64 - Distribution: Fedora release 38 (Thirty Eight)

### Floorp Version

1.5.0 (64-bit) (Flatpak)

### Additional context

Other setting may also reset. Some settings do not reset.

**Comment by surapunoyousei** [comment]
What is TST?
