### ISSUE TITLE
[Bug] Certain Text Strings get cut off in the Setup on certain Languages

### ISSUE THREAD

**Issue by legofanlovessayori** [Floorp-Projects/Floorp#553]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Certain text strings in german cause text to be cut off in the "Choose a Template" page in setup. 

### To Reproduce

1. Install Floorp in a language that is affected (or create a new profile from about:profiles and switch)
2. Proceed in the Setup until you reach the "Choose a template" page

### Expected behavior

The text should be fully readable.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/94994630/756500cc-2d3f-43ce-a0a7-b22db585781d)

### OS Info

Windows 11 Dev Insider Preview v. 23575.1001 (in German)

### Floorp Version

11.5.1

### Additional context

Only have seen this issue occur on german, other languages might be affected aswell.

**Comment by surapunoyousei** [comment]
It seems that the translated sentence is too long. Just remind you to keep it short

**Comment by legofanlovessayori** [comment]
> It seems that the translated sentence is too long. Just remind translator to keep it short

kinda of hard to do since german words are longer than english ones

**Comment by surapunoyousei** [comment]
Fixed
