### ISSUE TITLE
[Bug] Preferences Heading in about:preferences stays untranslated

### ISSUE THREAD

**Issue by legofanlovessayori** [Floorp-Projects/Floorp#555]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Title kinda explains it on its own.

The "Preferences" title in about:preferences (Settings) does not get translated and has no way of being translated.

### To Reproduce

1. Open Settings via the hamburger menu or typing about:preferences.

### Expected behavior

The title should be translatable

### Screenshots

![Screenshot 2023-10-31 224754](https://github.com/Floorp-Projects/Floorp/assets/94994630/f932e9b5-83d5-4bd8-8e47-ac6e1db1540e)

### OS Info

Windows 11 Dev Insider Preview v. 23575.1001 (in German)

### Floorp Version

11.5.1

### Additional context

Happens across all languages, friends of mine confirmed that the behavior is the same on Japanese and Polish.

**Comment by surapunoyousei** [comment]
Yeah. The string is fixed.
