### ISSUE TITLE
[Bug] gnomeTheme.tabsAsHeaderbar=true doesn't work

### ISSUE THREAD

**Issue by SoiledBrush** [Floorp-Projects/Floorp#557]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

firefox-gnome-theme optional feature gnomeTheme.tabsAsHeaderbar doesn't work on floorp.
Other optional features work as expected.

### To Reproduce

1. Set GNOME Theme in settings>design
2. Go to about:config page
3. Search for gnomeTheme.tabsAsHeaderbar
4. Set it as a boolean and click on the add button
5. Restart Firefox

### Expected behavior

To see tabs above the navigation bar

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/43366389/38303a49-921f-446b-be89-6cf5f7cbdbd3)

### OS Info

Fedora 39 beta 

### Floorp Version

11.5.1

**Comment by surapunoyousei** [comment]
This is because it is for ESR115 and is not compatible with different versions of ESR115. Unable to resolve.

**Comment by menndouyukkuri** [comment]
Posting anything other than a bug that Floorp has in an issue is a nuisance. You should solve the problem by yourself or talk about it on a forum that handles Floorp topics.
