### ISSUE TITLE
xul.dll reduces web benchmark performance by 17% compared to esr of the same version

### ISSUE THREAD

**Issue by sakanatha** [Floorp-Projects/Floorp#56]
Performance with xul.dll that comes with floorp is worse than with xul.dll from ff esr of the same version 

0. Close all other programs
1. Go to https://browserbench.org/Speedometer2.0/ 
2. Check results
3. Replace xul.dll with the one from the esr build and go to https://browserbench.org/Speedometer2.0/  again
4. Check results
5. Compare results

## Expected behavior
Same results in both cases, 17% loss instead (150/180). 
Firefox is already much slower than chromium based browsers. Losing  performance even more, especially when using some heavy addons like dark reader is absolutely unacceptable 

## Desktop (please complete the following information):
 - OS: Windows 10
 - Floorp Version: v10.5.0  v10.4.0 and probably previous ones

## Additional context
What's interesting is that waterfox also suffers from the same exact problem (in g5 beta and g4 at least), so if there's no harm in replacing this dll, why cant we just not use waterfox code in xul.dll?

**Comment by surapunoyousei** [comment]
Is there a performance difference between Firefox and Floorp?

 it's strange

**Comment by sakanatha** [comment]
Yes, again its exactly the same for waterfox and floorp because of this dll

**Comment by surapunoyousei** [comment]
Check your Firefox build configuration to see if there is a difference

**Comment by sakanatha** [comment]
Sorry, I dont understand. What do you mean? Like I said, I only replaced one single file (xul.dll). For latest floorp for example I used this one https://ftp.mozilla.org/pub/firefox/candidates/102.3.0esr-candidates/build1/win64/en-US/firefox-102.3.0esr.zip

**Comment by surapunoyousei** [comment]
I just have to check.

 The official Mozilla build environment for Firefox is a bit peculiar and does not exactly match Floorp's build. All build settings are defined in a file called mozconfig and can be viewed from about:buildconfig.

 It is very difficult to make it the same as the original Firefox

**Comment by sakanatha** [comment]
Ok so this page is obviously a bit different on esr and floorp, however its exactly the same with replaced xul.dll. I really cant help with anything else, I just wanted to let you know that there's a problem which can be easily replicated

**Comment by surapunoyousei** [comment]
Got it.

If I can solve something or improve it by replacing it, I will try to improve it.

Thank you for the report.

**Comment by surapunoyousei** [comment]
Currently a Floorp developer and researching build flags. However, the flags available in GitHub Actions are limited and difficult

**Comment by surapunoyousei** [comment]
Performance improvements are being adjusted to implement what is possible.

Thank you for the information.

**Comment by surapunoyousei** [comment]
Hi. I've made progress on this issue and would like to report.

We are happy to announce that we have resolved this issue with Floorp for Linux.  Windows and Mac are open.

**Comment by surapunoyousei** [comment]
Improved performance by reviewing build flags. The results are as follows.

Before enable (10.6.2） 
![image](https://user-images.githubusercontent.com/73892113/197718880-78971904-ff5a-498a-9f44-b2224edb1db6.png)


After enable (10.7.0)
![image](https://user-images.githubusercontent.com/73892113/197718944-0ec07889-18d6-4b55-8ca9-90a326a6d1ea.png)

Firefox 106.0.1
![image](https://user-images.githubusercontent.com/73892113/197719005-5f9fbc31-8f24-4d0d-8a58-776212b25416.png)
