### ISSUE TITLE
Changing The Tab bar options is messing up the rendering of the window

### ISSUE THREAD

**Issue by viking316** [Floorp-Projects/Floorp#560]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Changing The Tab bar options is messing up the rendering of the window for unprecedented amounts of time and the whole ui is shifted the extreme bottom, and the title bar of the window also goes missing.

![image](https://github.com/Floorp-Projects/Floorp/assets/82701532/7b99df44-3be0-4145-8018-d7f73f00e5b6)

### To Reproduce

go to settings
design
tab bar
choosing any of the options and the ui is messed up differently for each of the option.

### Expected behavior

it should stay the same and not messup the ui

### OS Info

windows 10 22H2

### Floorp Version

Version 11.5.1 (64-bit) | Firefox: 115.4.0

**Comment by surapunoyousei** [comment]
If vertical tabs are used, this is a specification.
