### ISSUE TITLE
[Bug] Low resolution text on docs.google.com

### ISSUE THREAD

**Issue by rymdimperiet** [Floorp-Projects/Floorp#563]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

In Google Docs, Floorp renders text in the document area in a lower resolution than on the rest of the page.
This does not occur in the latest version of Firefox.

### To Reproduce

1. Go to docs.google.com
2. Log in and start a new document
3. Type some words on the page.

### Expected behavior

The resolution of the text is supposed to be the same all over the page.

### Screenshots

<img width="224" alt="2023-11-07 14_03_39" src="https://github.com/Floorp-Projects/Floorp/assets/4344637/762569f1-ecbb-42b1-a62e-67559da4cef4">

### OS Info

Windows 10

### Floorp Version

11.5.1

**Comment by surapunoyousei** [comment]
Did you try ESR115 version of Firefox?

**Comment by rymdimperiet** [comment]
I've just tested it and the bug does not occur in Firefox ESR115.4 (could not locate 115.0). I also tried with Floorp in safe-mode and the bug still occurs.

**Comment by surapunoyousei** [comment]
Hmm. odd. OK. I'll check it

**Comment by surapunoyousei** [comment]
& Please try on new profile

**Comment by rymdimperiet** [comment]
That solved it! How interesting. Thank you for this!
