### ISSUE TITLE
TAB Key Focus with "Clear Recent History"

### ISSUE THREAD

**Issue by AllanHigdon** [Floorp-Projects/Floorp#566]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

There is no problem with TAB key focus on Web page links.
However, when displaying "Clear Recent History", there is no TAB key focus at all.
With my other Firefox based Web browser, SlimBrowser, you can see where the focus is.
The included screenshot of SlimBrowser shows that the focus is on the "Site settings" option.

### To Reproduce

Press CTRL+SHIFT+DEL to display Clear Recent History.
Press TAB or SHIFT-TAB key.
No highlighted focus on any of the options.

### Expected behavior

One of the options should be highlighted.

### Screenshots

![Screenshot](https://github.com/Floorp-Projects/Floorp/assets/101118106/e13637cd-37c5-426a-bed3-a809211efbee)

### OS Info

Windows 10 22H2

### Floorp Version

11.5.1

**Comment by surapunoyousei** [comment]
No plan to fix this problem. Not big issue
