### ISSUE TITLE
Option to disable auto-adding https://  for custom added urls of the sidebar

### ISSUE THREAD

**Issue by sakanatha** [Floorp-Projects/Floorp#57]
## Is your feature request related to a problem? Please describe.
Option to disable auto-adding https://  for custom added urls of the sidebar. Because of this behaviour its impossible to add moz-extension:// addresses without editing prefs manually.

## Describe the solution you'd like
Add this option.

## Describe alternatives you've considered
Manually editing prefs every time this page was opened
![tbprb9PfaA28qx29Al3tl7Uvg0vKjog9BENUxD2o](https://user-images.githubusercontent.com/113897465/191308508-abe50813-27e2-4f04-a1f4-f0004bb70f5e.jpg)
![iZ88SsX2ctWru0By7J15EuqOWBkLu92DLIFHYieo](https://user-images.githubusercontent.com/113897465/191308513-aa780c7b-9358-41cd-baea-c98b8da2f5fc.jpg)

**Comment by surapunoyousei** [comment]
As a temporary workaround, you can search for and change the customurl from about:config
