### ISSUE TITLE
[Bug] "Add X as an application for XXX" keeps showing up, even if i say no

### ISSUE THREAD

**Issue by BarbzYHOOL** [Floorp-Projects/Floorp#574]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Check the screenshot below, when I click on the little cross to ignore this thing, it keeps coming back to me EVERYTIME i reopen that page

### To Reproduce

Go here https://app.tuta.com/mail/

### Expected behavior

It should only show once

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/29780637/148ac51e-73f0-479c-8574-692106999114)

### OS Info

POP OS 22

### Floorp Version

11.5

**Comment by surapunoyousei** [comment]
Not big.
