### ISSUE TITLE
[Bug] Update Website Under "No User Tracking"

### ISSUE THREAD

**Issue by Nitrousoxide** [Floorp-Projects/Floorp#583]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The English Floorp Website says that it has no affiliation with any advertising company

However, version 11.5.1 added sponsored links to the new tab page which makes this false.

I believe it could be reworded to say that you don't track any users through advertisements, or something like that to remain accurate.

### To Reproduce

1. Open new tab.
2. See sponsored links

### Expected behavior

Website text should be reworded since you do have companies advertising within Floorp

### Screenshots

<img width="342" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/1363931/321edd29-886a-4bff-810f-e250942980f2">

### OS Info

MacOS

### Floorp Version

11.5.1

**Comment by surapunoyousei** [comment]
That is a simple shortcut, and it doesn't depend on what the user is liking.

We don't even count the number of times a user clicks on it, so don't worry about it.

We are just displaying organizations that have made a certain amount of donations through GitHub sponsorships, and we are not connected to any ad networks.
