### ISSUE TITLE
[Bug] Spotify skips songs. Even with DRM enabled.

### ISSUE THREAD

**Issue by 32bitx64bit** [Floorp-Projects/Floorp#584]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Spotify skips through songs, and after a bit plays around 10 seconds of the song, then just outright stops playing the song.

This doesn't happen on firefox, even upon a complete reinstall of floorp this still happens.

### To Reproduce

Go to spotify.
Play any song

### Expected behavior

Got o spotify
Song(s) play correctly

### OS Info

Windows 10 *latest*

### Floorp Version

11.5.1

### Additional context

Doesn't happen on Firefox, Chrome, Vivaldi, Brave, or any other known browser.

**Comment by creeper-0910** [comment]
It's a problem that has existed for some time.
and is considered to be a Widevine level issue.
