### ISSUE TITLE
[Bug] Window not proper size with PowerToys FancyZones

### ISSUE THREAD

**Issue by gothicdecadence** [Floorp-Projects/Floorp#585]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Floorp window doesn't properly snap to set FancyZones. It's smaller by about 5 pixels on the left, right, and bottom sides. 

### To Reproduce

1. Download [Microsoft PowerToys](https://github.com/microsoft/PowerToys)
2. Enable FancyZones. 
3. Create and save a layout. 
4. Snap Floorp to zone. 

### Expected behavior

Floorp fills the window properly.

### Screenshots

This is proper behavior, with Signal for reference. 
![image](https://github.com/Floorp-Projects/Floorp/assets/148832708/83aea731-4a6c-43b8-bd45-54ec68376c3b)

This is what Floorp does
![image](https://github.com/Floorp-Projects/Floorp/assets/148832708/95202c50-2fc7-4438-b89c-6990de56cfbf)

This is with the FancyZone overlay to show the size difference
![image](https://github.com/Floorp-Projects/Floorp/assets/148832708/348d8dd1-b325-4225-aa76-8ecf1839c094)

### OS Info

Windows 10 Version 10.0.19045 Build 19045

### Floorp Version

11.6.0 (64-bit)

### Additional context

This has been happening on every version on every version of Floorp I've used so far since I started using it a month ago, including the latest version. Firefox doesn't have this issue, in fact no other app I've used has this issue from what I can tell.

**Comment by surapunoyousei** [comment]
Third party support is difficult on the Floorp side, so please submit issues to PowerToys FancyZones rather than opening them in an issue.
