### ISSUE TITLE
[Bug] Floorp 11.6.0 no longer respects the Title Bar option

### ISSUE THREAD

**Issue by hvdijk** [Floorp-Projects/Floorp#586]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

In Floorp 11.5, the option to show a title bar worked.
In Floorp 11.6.0, the option to show a title bar has no effect.

### To Reproduce

1. Right-click the tool bar
2. Click 'Customise Toolbar...'
3. In the bottom left corner, click 'Title Bar'

### Expected behavior

The button has an effect of enabling or disabling the title bar

### OS Info

Windows 11 23H2

### Floorp Version

11.6.0

### Additional context

https://github.com/Floorp-Projects/Floorp/compare/v11.5.1..v11.6.0 and looking for "title bar" provides a change that was almost certainly responsible: https://github.com/Floorp-Projects/Floorp/commit/c3041c9aebd207d42e8da75ea298cecd7c573196.

```javascript
let allowed =
      this.systemSupported &&
      !window.fullScreen ||
      floorpSBBWindow == "true" &&
      !Object.keys(this._disallowed).length;
```
means
```javascript
let allowed = (this.systemSupported && !window.fullScreen)
  || (floorpSBBWindow == "true" && !Object.keys(this._disallowed).length);
```
so on any supported system with a non-fullscreen window, `allowed` is now true regardless of what's in `_disallowed`. And indeed, in Floorp 11.6.0, if I press F11 to make my window full screen, and hover near the top, I see the title bar I am expecting. (Edit: However I am not 100% sure what the title bar is supposed to look like in a full screen window, so there is a possibility I am misinterpreting this part.)

**Comment by surapunoyousei** [comment]
I'll fix it

**Comment by surapunoyousei** [comment]
at 11.6.1, You can use the option. The version will release next day

**Comment by hvdijk** [comment]
Thanks for the prompt response, can confirm this is working as expected again in 11.6.1.
