### ISSUE TITLE
[Bug] Scrollbar doesn't work when mouse is all the way right

### ISSUE THREAD

**Issue by uwidev** [Floorp-Projects/Floorp#588]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Moving the mouse all the way to the right to click the scroll bar does not scroll.

### To Reproduce

1. Move mouse to scrollbar on right until it cannot move anymore
2. Click, or click and drag

### Expected behavior

Scrollbar is expected to be dragged with mouse if clicked-and-dragged on, or move to clicked area.

### OS Info

Windows 10 22H2 (Modified AtlasOS v0.3.2)

### Floorp Version

11.6.0 64-bit

**Comment by uwidev** [comment]
I forgot to mention that my sidebar is disabled (Show the Browser Manager Sidebar is OFF).

Bug disappears when Display the Browser Manager Sidebar on the right is OFF. In other words, moving the sidebar to the left side causes scrollbar to work as expected.

**Comment by surapunoyousei** [comment]
I'll fix it

**Comment by surapunoyousei** [comment]
Fixed. It available on 11.6.1
