### ISSUE TITLE
[Bug] Built in Vertical Tab Bar causes page to jitter and redraw when moused over

### ISSUE THREAD

**Issue by Nitrousoxide** [Floorp-Projects/Floorp#590]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When the (experimental) vertical is moused over after being set to auto-hide it causes the background page to jitter and redraw and reposition the elements.

Tree Style Bar leaves the underlying page unchanged when expanding/hiding the bar.

### To Reproduce

1. Mouse over side bar
2. Page redraws in the background

### Expected behavior

Page should remain static when expanding the vertical bar.

### Screenshots

Built-in Vertical Tab Bar

https://github.com/Floorp-Projects/Floorp/assets/1363931/69c2610f-43bf-42ec-8db3-88b6a4c55b50

Tree Style Bar

https://github.com/Floorp-Projects/Floorp/assets/1363931/af736ee6-5e00-459a-99b7-223201f0caea

### OS Info

Fedora 39 (Flatpak Floorp

### Floorp Version

11.6.0

**Comment by surapunoyousei** [comment]
this is not a bug
