### ISSUE TITLE
[Bug]  Floorp flatpak displays 2 separate icons instead of one on Plank Dock

### ISSUE THREAD

**Issue by blobcatz** [Floorp-Projects/Floorp#592]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I am on Linux using the Pantheon (Elementary OS) DE, that uses Plank Dock (I'm not sure if it happens on other docks).
If I use the flatpak version of Floorp, it displays 2 separate icons for it, one high quality with the options (but is not the opened window) and a second lower quality that only has a "close" option.
The issue doesn't happen with the Firefox flatpak (or any other browsers).

### To Reproduce

1. Open the flatpak version of Floorp with Plank Dock

### Expected behavior

Only have one unified icon on the dock

### Screenshots

![Firefox and Floorp flatpaks on the Plank Dock](https://github.com/Floorp-Projects/Floorp/assets/149013930/519719d8-d77c-46e4-bb8a-1d076f390369)

Video showing the weird behavior of the Floorp flatpak compared to Firefox flatpak

https://github.com/Floorp-Projects/Floorp/assets/149013930/5eab5004-b84b-47a1-a03f-34d9fa56a894

### OS Info

Ultramarine Linux 39 (Pantheon)

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
Please on in https://github.com/flathub/one.ablaze.floorp

**Comment by typeling1578** [comment]
fixed
