### ISSUE TITLE
[Bug] Dead link in About

### ISSUE THREAD

**Issue by dominichayesferen** [Floorp-Projects/Floorp#593]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

this one.
![image](https://github.com/Floorp-Projects/Floorp/assets/11057934/e1f2313b-947b-4a29-8f50-c6b21b2e0e47)

### To Reproduce

1. Cllick that link
2. Enjoy a missing Twitter account.

### Expected behavior

No link, their profile on a different service, or a typo fix if it's just a mere typo.

### OS Info

Feren OS 2023.04

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
account has been deleted.
