### ISSUE TITLE
[Bug] Vertical tabs scrollbar won't disappear after opening the browser toolbox once, even after closing it.

### ISSUE THREAD

**Issue by YousufSSyed** [Floorp-Projects/Floorp#594]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

If I have vertical tabs enabled and open the browser toolbox (toggled with CMD OPT SHIFT I on macOS), and I scroll on the tabs, then the scrollbar stats instead of automatically disappearing. 

### To Reproduce

1. Enable vertical tabs
2. Open Browser Toolbox
3. Scroll on the tabs list

### Expected behavior

The scrollbar automatically goes away as expected.

### OS Info

macOS 14

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
Sorry I didn't enderstand

**Comment by YousufSSyed** [comment]
@surapunoyousei What about it do u not understand? Do you know abut the Browser Toolbox, like the dev tools but for customizing Firefox CSS?

**Comment by surapunoyousei** [comment]
Yeah

**Comment by gunir** [comment]
> Yeah

I usually press Ctrl+Shift+Alt+I to open Browser Toolbox

**Comment by surapunoyousei** [comment]
Browser toolbox does not affect most of user. close issue
