### ISSUE TITLE
[Bug] Workspaces Are Not Restored Upon Browser Restart

### ISSUE THREAD

**Issue by itsDevBlaze** [Floorp-Projects/Floorp#598]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When more than one workspace is created and Manage Workspace on Browser Manager Sidebar is enabled, only the Default workspace will appear on the sidebar when the browser is restarted. You can make the workspaces appear again by adding them with the same name from the sidebar. Furthermore, the removed workspaces do not appear in the Workspace Manager.

### To Reproduce

1. Open Settings.
2. Toggle "Enable Workspaces" to enabled.
3. Click "Workspace Settings..."
4. Toggle "Manage Workspace on Browser Manager Sidebar" to enabled.
5. Add a workspace or two and select a different icon that what was automatically selected.
6. Restart Floorp.
7. Observe that only the default workspace appears in the Sidebar.
8. Observe that the Workspace Manager only shows the default workspace.
9. Add the same workspace(s) using the same name(s) you used previously.
10. Observe that the icon you selected is the same, and the workspace(s) have been restored.

### Expected behavior

The Workspace Manager and the Sidebar should automatically remember and restore all workspaces upon Browser restart.

### OS Info

Garuda Linux (Arch-Based Rolling Release)

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
Workspaces with no operations or tabs will be deleted due to the private container feature
