### ISSUE TITLE
Floorp won't launch

### ISSUE THREAD

**Issue by Amarnamoth** [Floorp-Projects/Floorp#600]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The browser, installed via curl, blinks once on the task bar after being clicked on and then disappears from the bar. It doesn't launch.

### To Reproduce

1. Go to the Floorp icon in the apps menu
2. Click it
3. Watch it appear for 1 second on the task bar and then disappear.

### Expected behavior

Expected behaviour is the launching of the browser

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/84014982/887a11d6-f5fd-4455-be70-58cc8623aeec

### OS Info

Kubuntu 22.04

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
What is curl...

Please write Flatpak or PPA.

**Comment by Amarnamoth** [comment]
I meant PPA, sorry

**Comment by surapunoyousei** [comment]
Package manager problem is not Floorp problem. Try tarball (Auto update can be use)

**Comment by creeper-0910** [comment]
If type "floorp" on the command line to start the program, what logs will be displayed on the console?
