### ISSUE TITLE
[Bug] Applying non-default user.js from about:preferences#userjs breaks mozilla sync

### ISSUE THREAD

**Issue by Nitrousoxide** [Floorp-Projects/Floorp#601]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Applying any non-default user.js from about:preferences#userjs will break sync.  I have tried this on both a Mac and Linux flatpak.  In both cases you get logged out of your browser's user and if you try to log back in it will hang after entering the password.

Manually copying over one of Yokoffing's user.js files to your profile from their git repo, however, will, properly apply the settings and not break sync.

### To Reproduce

1. Go to about:preferences#userjs
2. Select any of the Yokoffing user.js to apply
3. Floorp will reset and sync will be broken and you cannot log back into it.

### Expected behavior

Sync should still work, like when you manually plug in a user.js file.

### Screenshots

this is a fresh profile applying the user.js
![image](https://github.com/Floorp-Projects/Floorp/assets/1363931/7555b844-8c08-4a7f-aace-6d15e9d81629)

attempting to relog in just hangs
![image](https://github.com/Floorp-Projects/Floorp/assets/1363931/ac3bff60-1a41-4a31-a0a6-dee8f78837b0)

### OS Info

MacOS and Fedora 39 (Flatpak ver. 11.6.1)

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
betterfox disable Firefox Sync. It expected

**Comment by Nitrousoxide** [comment]
So it does.  I see `identity.fxaccounts.enabled` is set to false.  I believe you only apply the user.js file once on the reboot and the delete it?  Is that right?  Flipping `identity.fxaccounts.enabled` to true in about:config seems to persist it across application restarts.  If the user.js file does not persist then the user can re-enable it if they want.  

Perhaps a note in the about:preferences#userjs page on what flag to toggle?    I see you posted in yokoffing's repo about the topic so it's probably some documentation a floorp user might like on that settings page.

https://github.com/yokoffing/Betterfox/discussions/196

**Comment by surapunoyousei** [comment]
Once you apply a customization to Betterfox, it will be applied permanently.

Floorp is designed to re-download Betterfox at startup and always use the latest settings.

Selecting "Floorp Default" will remove all of these settings.

**Comment by yarub123** [comment]
@surapunoyousei So how can we use betterfox user.js, but have it save any changes we make to user.js or to about:config?

It keeps resetting back to the default betterfox user.js 😬.
