### ISSUE TITLE
[Bug] [New] Scrollbar doesn't disappear when vertical tabs are enabled.

### ISSUE THREAD

**Issue by YousufSSyed** [Floorp-Projects/Floorp#602]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

**I found out that I can have this bug without opening the dev tools at all during a session.** When I hover over the vertical tabs at few times and trigger the scrollbar, the scrollbar might not go away even after I stop scrolling and move my mouse away.

### To Reproduce

1. Open a new Floorp session with lots of tabs.
2. Scroll on it a few times within 5-10 mins.
3. The scrollbar might get stuck

### Expected behavior

The scrollbar goes away

### OS Info

macOS 

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
It's not a big problem, so I won't fix it

**Comment by YousufSSyed** [comment]
@surapunoyousei I just loaded a blank profile, enabled vertical tabs, opened a bunch and got the scrollbar stuck, its still stuck while I'm writing this. I'm wondering why users should use Floorp features if you're outright refusing to fix glaring bugs.

<img width="1191" alt="Screenshot 2023-11-25 at 11 36 28 AM" src="https://github.com/Floorp-Projects/Floorp/assets/42646062/692a3707-8282-42b8-9e97-7b6347f81f27">

**Comment by surapunoyousei** [comment]
This is Mac-specific scrollbar behavior and there is no solution.

On Windows and Linux, they are automatically hidden.

**Comment by surapunoyousei** [comment]
The width of the scroll bar has been narrowed. There shouldn't be any visual issues with this.
