### ISSUE TITLE
[Bug] I can't drag vertical tabs out to create new windows.

### ISSUE THREAD

**Issue by Oneechan69** [Floorp-Projects/Floorp#603]
### Attention!

- [X] #608

### Describe the bug

When vertical tabs aren't enabled, I can drag the tab out of the window to have it in a new window. It doesn't when when Vertical tabs are enabled.

### To Reproduce

1. Enable Vertical Tabs.
2. Open two tabs on Floorp.
3. Drag one out of the window

### Expected behavior

A new window is created with the dragged tab.

### OS Info

MacOS 14

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
Maybe fixed.  I changed the mechanism slightly. Fingers crossed that it improves.

**Comment by Oneechan69** [comment]
@surapunoyousei I'm still having the issue on Floorp 11.7.1

**Comment by surapunoyousei** [comment]
Drag tab to outside of Floorp Window to split them.

**Comment by Oneechan69** [comment]
Yeah that doesn't work in Floorp 1.8.2

**Comment by surapunoyousei** [comment]
11.9.0 should be working fine

**Comment by LuisHenri** [comment]
Hello @surapunoyousei 
It doesn't seem to be working on 11.23.0 (64-bits)
