### ISSUE TITLE
[Bug] When the navigation bar is set to bottom, the text input field needs to stay fixed

### ISSUE THREAD

**Issue by lbrdt** [Floorp-Projects/Floorp#605]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Thanks a lot for the Floorp browser. It has customization features I've always wanted in Firefox and Floorp accomplishes it while being lightweight and customizable. 

Currently in the experimental "Show the toolbar tat the bottom" feature, when typing anything, the text input field moves around vertically with variable number of suggestions available. It makes it hard to focus on what you are typing. It would be nice for the text field to stay at a fixed position at the bottom and the suggestions and search engines to appear above it.

### To Reproduce

1. Set navigation bar to bottom
2. Start typing any letters in the navigation field
3. The text input field moves above and changes height according to suggestions available

### Expected behavior

The text input field should stay fixed at the bottom

### Screenshots

Demo:
https://i.imgur.com/hKCRauA.gif

### OS Info

Windows 10

### Floorp Version

11.6.1

### Additional context

Vivaldi does this great.

**Comment by surapunoyousei** [comment]
I implement it next day

**Comment by surapunoyousei** [comment]
Added. If you send feature request, please use discussion
