### ISSUE TITLE
Vertical Tabs dont scroll[Bug] 

### ISSUE THREAD

**Issue by Ryanics** [Floorp-Projects/Floorp#607]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I wanted to use Floorp for the vertical tabs, but the Issue that I have is that vertical tabs do not scroll. You can use the scrollbar to scroll if you click and drag it, but you cannot scroll with the mouse wheel. 

### To Reproduce

1. Enable Vertical Tabs
2. Attempt to scroll with scroll wheel

### Expected behavior

The expected behavior is for the vertical tabs to scroll. 

### OS Info

Nobara 38 (Fedora 38)

### Floorp Version

11.6.1

### Additional context

Some extra stuff that may or may not give a change is Im running Wayland (but scrolling works in multi row tab bar and horizontal tab bar). Besides that, I've tried all of the themes, because I know others have said that might have been a problem a long time ago. Whatever changes have happened in the last few months since like August or September, it's just stopped working. Also yes, I know this is mostly meant for Windows first and linux on the backburner, but figured it might help.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by BarbzYHOOL** [comment]
i don't know what you did @surapunoyousei but I reported many issues with vertical side bar, now it has even more

I cannot scroll as fast as before, therefore it takes forever to go to the top of the tabs or to the bottom and since you always cancel my issue about fixing this, it's unusable. it takes like 30 sec for me to scroll all the way up because I have many tabs that I need to sort
In top of that, I cannot grab the scrollbar with the mouse else it minimize the window....... On linux

I didn't want to update floorp because I knew it would have new issues. I'm sadly forced to stop using Floorp totally as soon as possible

**Comment by surapunoyousei** [comment]
I knew it.

**Comment by creeper-0910** [comment]
> i don't know what you did @surapunoyousei but I reported many issues with vertical side bar, now it has even more
> 
> I cannot scroll as fast as before, therefore it takes forever to go to the top of the tabs or to the bottom and since you always cancel my issue about fixing this, it's unusable. it takes like 30 sec for me to scroll all the way up because I have many tabs that I need to sort In top of that, I cannot grab the scrollbar with the mouse else it minimize the window....... On linux
> 
> I didn't want to update floorp because I knew it would have new issues. I'm sadly forced to stop using Floorp totally as soon as possible

If you know there's a problem, why don't you fix it?
If you can't fix it, then stop posting messages for issues that you didn't open yourself.

**Comment by menndouyukkuri** [comment]
> i don't know what you did @surapunoyousei but I reported many issues with vertical side bar, now it has even more
> 
> I cannot scroll as fast as before, therefore it takes forever to go to the top of the tabs or to the bottom and since you always cancel my issue about fixing this, it's unusable. it takes like 30 sec for me to scroll all the way up because I have many tabs that I need to sort In top of that, I cannot grab the scrollbar with the mouse else it minimize the window....... On linux
> 
> I didn't want to update floorp because I knew it would have new issues. I'm sadly forced to stop using Floorp totally as soon as possible

Floorp is open source software and is not a guaranteed product provided by a company.
If you cannot use it at your own risk, you should not use OSS.

**Comment by BarbzYHOOL** [comment]
> > i don't know what you did @surapunoyousei but I reported many issues with vertical side bar, now it has even more
> > I cannot scroll as fast as before, therefore it takes forever to go to the top of the tabs or to the bottom and since you always cancel my issue about fixing this, it's unusable. it takes like 30 sec for me to scroll all the way up because I have many tabs that I need to sort In top of that, I cannot grab the scrollbar with the mouse else it minimize the window....... On linux
> > I didn't want to update floorp because I knew it would have new issues. I'm sadly forced to stop using Floorp totally as soon as possible
> 
> If you know there's a problem, why don't you fix it? If you can't fix it, then stop posting messages for issues that you didn't open yourself.

I'm not a browser developer.

And yes, Menndouyukkuri, you are right

That is what I'm going to do, but I felt like saying why before leaving.

**Comment by surapunoyousei** [comment]
> > > i don't know what you did @surapunoyousei but I reported many issues with vertical side bar, now it has even more
> > > I cannot scroll as fast as before, therefore it takes forever to go to the top of the tabs or to the bottom and since you always cancel my issue about fixing this, it's unusable. it takes like 30 sec for me to scroll all the way up because I have many tabs that I need to sort In top of that, I cannot grab the scrollbar with the mouse else it minimize the window....... On linux
> > > I didn't want to update floorp because I knew it would have new issues. I'm sadly forced to stop using Floorp totally as soon as possible
> > 
> > 
> > If you know there's a problem, why don't you fix it? If you can't fix it, then stop posting messages for issues that you didn't open yourself.
> 
> I'm not a browser developer. everytime I open an issue, Surapunouyusei closes it and says either nothing or just says "i do not fix" or "intended" looool
> 
> And yes, Menndouyukkuri, you are right
> 
> That is what I'm going to do, but I felt like saying why before leaving.

If I cannot reproduce it in my environment, I will not correct it; if I can reproduce it, I will attempt to correct it.

I am the same person and student as you are. I am also a student.

I am not a company, so there are limits to what I can develop on my own. If you demean me without praising me for developing one new feature every month, I will not be motivated to do it.

**Comment by surapunoyousei** [comment]
I changed the mechanism slightly. Fingers crossed that it improves.
