### ISSUE TITLE
[Bug] Download notifications can't be localized

### ISSUE THREAD

**Issue by legofanlovessayori** [Floorp-Projects/Floorp#611]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Self explanatory title again, the Download Notifications can't be translated and stay in English. 

### To Reproduce

1. Use any Language that isn't English
2. Enable Download notifications
3. Start any download

### Expected behavior

The Notification title should be able to be translated.

### Screenshots

![grafik](https://github.com/Floorp-Projects/Floorp/assets/94994630/cfd96924-82e6-46a1-87ba-6eb8dc23e4e8)
![grafik](https://github.com/Floorp-Projects/Floorp/assets/94994630/46414372-47a6-4525-8b99-0ee6d2262f38)

### OS Info

Windows 10 22H2 (Build 19045.3758)

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
I'll work on this tomorrow

**Comment by surapunoyousei** [comment]
Ok. You can translate text on Crowdin. Remove extension i18n codes. Migrate to L10n
