### ISSUE TITLE
[Bug] Low quality background image for Ultrawide screens (32:9)

### ISSUE THREAD

**Issue by federicotorrielli** [Floorp-Projects/Floorp#612]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When using a ultrawide monitor (i.e. 32:9), the background image (the random firefox in the start page) does stretch and makes it very low quality. I'd suggest not to include any background image in the start page.

### To Reproduce

1. Have a 32:9 monitor
2. Open Floorp

### Expected behavior

No image or supported image for ultrawide monitor

### OS Info

Arch Linux - rolling

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
You can disable it at preferences. 

It expected & normal... No way to fix
