### ISSUE TITLE
[Bug] Browser Manager Sidebar and local website icons 

### ISSUE THREAD

**Issue by Nitrousoxide** [Floorp-Projects/Floorp#613]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The Browser Sidebar appears to try to grab icons from an icon provider like Google or DuckDuckGo.  This works well for sites accessible by the internet at large.  However any internal-only websites (for instance self-hosted ones or intranet-only accessible ones) end up not populating with any icon in the sidebar despite a corresponding bookmark of that page in firefox/floop populating just using the websites own self-reported icon.

### To Reproduce

Create new web panel for site not accessible to icon provider
get blank icon

### Expected behavior

Web panel should grab the icon as presented by the website itself first before looking to an icon provider like DDG or Google.

### Screenshots

See a bookmark for a self-hosted website populating correctly:
<img width="97" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/1363931/932c2529-afc2-49b1-a4bf-113ef5b5fd2a">

and in the tab bar:
<img width="238" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/1363931/c8924d29-9fb3-4dc4-8ef5-1997d132984f">

but not in the side bar

<img width="235" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/1363931/d20bae4a-365b-4e44-b9a7-56a6ca9707e2">

### OS Info

MacOS 14.1.2

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
It is difficult to implement this functionality, because the Floorp sidebar is not a tab, so doing this is not a priority due to Firefox's limitations
