### ISSUE TITLE
[Bug] Problem with the vertical tabs

### ISSUE THREAD

**Issue by Car0lina5** [Floorp-Projects/Floorp#617]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The tabs are very different now, when I hover the mouse there is no longer a close button and their appearance has changed. There are also some things in Floop View that weren't there before.

### To Reproduce

1. Choose vertical tabs.
2. Choose the "Collapse Vertical Tab Bar" option.

### Expected behavior

I expected the look to be the same as before, that there was a button to close the tab and there weren't those things together with the Floorp View.

### Screenshots

Before view:
![30 11 2023  -  18 22  -  ](https://github.com/Floorp-Projects/Floorp/assets/117472773/14eb5bfb-6abf-427c-8bdf-1ba02be1d5f5)

Today after update:
![05 12 2023  -  22 18  -  ](https://github.com/Floorp-Projects/Floorp/assets/117472773/ef09455c-6526-40b8-a93f-c065745e5b9a)
![05 12 2023  -  22 17  -  ](https://github.com/Floorp-Projects/Floorp/assets/117472773/92d7391a-333f-433c-86ad-db5b6fe9d10a)

### OS Info

Windows 11 23H2

### Floorp Version

Floorp Daylight 11.7.0

**Comment by Car0lina5** [comment]
The horizontal tab is also strange, even by right clicking and unchecking the "Tab Stacks Toolbar" when I restart the browser the option is activated again.

![image](https://github.com/Floorp-Projects/Floorp/assets/117472773/b4a427fc-e521-4a56-a5f4-5e688b8955e9)

**Comment by surapunoyousei** [comment]
Currently, I enabled TabStacks Features. It's on development. 

Please disable at about:config "floorp.browser.tabstacks.enabled" to "false"
