### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ElijahHW** [Floorp-Projects/Floorp#618]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

**Pinned tabs are synced across workspaces.**

Surely this isn't supposed to be the case? It isn't the case on Vivaldi at least. I would assume that the main point of workspaces/containers are to have a complete separation of tabs?

### To Reproduce

1. Create workspace "testA"
2. Create workspace "testB"
3. In workspace "testA", open any website + pin that current tab.
4. Now open workspace "testB" and the same pinned tab is there. 

### Expected behavior

Expect the pinned tab to be only visible in the workspace it was pinned, not multiple. 

### Screenshots

Workspace 1:
![image](https://github.com/Floorp-Projects/Floorp/assets/53635291/9cc34405-fd4e-4198-9898-cefd90bb065a)
Workspace 2:
![image](https://github.com/Floorp-Projects/Floorp/assets/53635291/9ff76ddc-7161-4a52-9d65-3f4bfe01b61c)

### OS Info

Garuda Linux x86_64

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
Please, Write issue title before send issue.
 
Originally, it was possible to include pinned tabs in a workspace, but now, this is impossible due to limitations in Firefox.

**Comment by ElijahHW** [comment]
Ah my bad for missing the title, apologies! 
Thanks for the swift response; what a bummer though, guess I will keep my tabs unpinned. 

Otherwise its been a swift migration from Vivaldi, thanks for the good work!

**Comment by joezimjs** [comment]
@surapunoyousei 
You're removing workspaces in a few months? Why? That's the biggest reason I chose Floorp when I wanted to move off Vivaldi. Personally I'm happy the pinned tabs stay the same between workspaces. That was something I didn't like about Vivaldi's.

**Comment by surapunoyousei** [comment]
This was rescinded and only the workspace was rewritten

**Comment by bdbch** [comment]
I would also rather still have the option to keep workspaces. Tab stacks really have a weird UI and I think the best and straight forward solution are workspaces.

- It doesn't clutter the UI with "different" types of tabs
- It helps keeping things logically separated from each other

**Comment by lmcr666** [comment]
would love for this to be "fixed" or at the very least added as an option

**Comment by jordanbates** [comment]
> Please, Write issue title before send issue.
> 
> Originally, it was possible to include pinned tabs in a workspace, but now, this is impossible due to limitations in Firefox.

Zen browser has isolated workspace pinned tabs. But I have no idea how either browser handles that stuff and if their implementation applies here. 

This is my only big issue with Floorp. Proper tab isolation between workspaces feels critical

**Comment by etardiff** [comment]
[Natsumi](https://github.com/greeeen-dev/natsumi-browser) fixes this issue for Floorp, but I'd really like to see it as a native Floorp feature. The Natsumi implementation breaks periodically with Floorp updates.
