### ISSUE TITLE
[Bug] Custom New Tab background stays black on first start

### ISSUE THREAD

**Issue by legofanlovessayori** [Floorp-Projects/Floorp#619]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When starting a fresh Floorp instance custom new tab backgrounds don't load on the first tab said session loads if only one wallpaper exists in the chosen folder

### To Reproduce

1. Enable Custom Tab Backgrounds
2. Make a folder and place **one** image file into it and use it as the path for wallpapers
3. Restart Floorp

### Expected behavior

The background should show properly.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/94994630/2c7a1dd2-269f-4455-a17a-f77cc64d4ba3

### OS Info

Windows 10 22H2 (Build 19045.3758)

### Floorp Version

11.6.1

### Additional context

Was able to reproduce the same bug on another PC of mine so if its a one off thing then... strange

**Comment by surapunoyousei** [comment]
I wIll check it

**Comment by surapunoyousei** [comment]
Not find the bug

**Comment by surapunoyousei** [comment]
I can't help you with this issue. It cannot be reproduced. Why is that?

**Comment by legofanlovessayori** [comment]
have asked another person in my friend circle that uses floorp to try that and it happens to them aswell

and said bug still affects my installs aswell, maybe try asking others if they can try this

**Comment by surapunoyousei** [comment]
Ok

**Comment by Demo337** [comment]
I will think you know how to customize floorp using userChrome.css method (same as firefox no difference) 
There is a workaround which you can change the background using `userContent.css` in floorp profile folder
just disable background in floorp setting and put this css style code in `userContent.css` that I take it from a guide in the internet.
```
@-moz-document url(about:home), url(about:newtab), url(about:privatebrowsing) {
    .click-target-container *, .top-sites-list * {
        color: #fff !important;
        text-shadow: 2px 2px 2px #222 !important;
    }

    body::before {
        content: "";
        z-index: -1;
        position: fixed;
        top: 0;
        left: 0;
        background: no-repeat url("your picture path here") center;
        background-size: cover;
        width: 100vw;
        height: 100vh;
    }
}
```
sorry for bad English :)

**Comment by legofanlovessayori** [comment]
i mean, good to know that we have a workaround for this but its kinda pointless to rely on a workaround

**Comment by legofanlovessayori** [comment]
and yeah, seems like both slideshows and single pictures have the same behavior
https://github.com/Floorp-Projects/Floorp/assets/94994630/94956ed5-b764-44ef-ac0c-f429d0270b45

_and if its speed related... this is running on a nvme ssd so can't be_

**Comment by EliasRonefors** [comment]
Just commenting to say I'm having this issue too

**Comment by surapunoyousei** [comment]
Frankly, this problem has been reported to occur only at startup, and we have determined that it is not a priority item to be fixed.

**Comment by surapunoyousei** [comment]
OK

**Comment by legofanlovessayori** [comment]
> I found that setting `browser.startup.homepage.abouthome_cache.enabled` in `about:config` to `false` can fix this issue.
> 
> This issue arises because at startup, the browser loads `about:home` from cache. But the custom image does not get stored in the cache. Firefox's code to write the cache seems too complex and I don't think I'll be able to modify it to include the custom background. So setting the above preference to `false` seems like our best bet.
> 
> @surapunoyousei If this seems like a viable option to you, I'll send a PR to set `browser.startup.homepage.abouthome_cache.enabled` to `false` when a user wants to use a Custom Image or a Custom Folder of images.

yeah that does fix it, changed that flag and it shows the bg on every start

just that the new tab elements take a bit to have transparency but i think thats just a speed issue regarding my device i tried that on
