### ISSUE TITLE
[Bug] New Tab Button Randomly Disappers/ moves to the right  

### ISSUE THREAD

**Issue by senposage** [Floorp-Projects/Floorp#621]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

when using the browser normally sometimes the New tab button [+] will disappear or move all the way to the right instend of behind the last tab 

### To Reproduce

n/a

### Expected behavior

New Tab button should always stay where pinned 

### OS Info

Windows 11 23H2 

### Floorp Version

11.6.1

### Additional context

New tab button is also sometimes missing from the Customize toolbar menu

**Comment by surapunoyousei** [comment]
On Multirow tabs？

**Comment by senposage** [comment]
Horizontal tabs I will test multi row to see if the issue persists in that mode

**Comment by surapunoyousei** [comment]
So. normal tabbar  & multirow tab bar are not same.

**Comment by senposage** [comment]
i made a video demonstrating the issue it looks like opening the setting menu makes it come back untill the program is closed
https://streamable.com/uuqctq

**Comment by surapunoyousei** [comment]
Didi you find the bug  on Firefox?

**Comment by senposage** [comment]
No firefox does not have this bug

**Comment by surapunoyousei** [comment]
So... It can be found on Firefox?

**Comment by surapunoyousei** [comment]
No response close issue
