### ISSUE TITLE
[Bug] Floorp works on Windows 7, but requires SSE4.1 processor

### ISSUE THREAD

**Issue by sergeevabc** [Floorp-Projects/Floorp#622]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Dear developers, Floorp version 11.6.1 works fine on Windows 7 x64 which has been proved by feedback from various sources. However, it only launches on computers with SSE4.1 processors. My laptop has a Core 2 Duo T7250 processor with SSE2 and SSE3, so I see an error. Please consider compiling the next version with SSE2 or SSE3 support like [IceCat](https://icecatbrowser.org/download/index.html) (another modern FF fork) does -- it's just a matter of changing one parameter.

### Screenshots

![2023-1210-0858 floorp 11-6-1](https://github.com/Floorp-Projects/Floorp/assets/373718/5f058bb5-82b4-4503-b1d6-cb5070371b7a) ![2023-1210-0903 floorp 11-6-1](https://github.com/Floorp-Projects/Floorp/assets/373718/7a6a6bfa-2ac0-480d-9099-2b3aac98189a)

### Additional context

[Elfx86exts](https://github.com/pkgw/elfx86exts) is a utility to analyze what CPU features are required.

``` console
$ elfx86exts.exe floorp.exe
File format and CPU architecture: Pe, X86_64
MODE64 (push)
SSE1 (xorps)
CMOV (cmovb)
SSE2 (pcmpeqd)
SSE41 (pcmpeqq)
NOT64BITMODE (xchg)
Instruction set extensions used: CMOV, MODE64, NOT64BITMODE, SSE1, SSE2, SSE41
CPU Generation: Unknown

$ elfx86exts.exe icecat.exe
File format and CPU architecture: Pe, X86_64
MODE64 (push)
SSE1 (movaps)
CMOV (cmovl)
SSE2 (pxor)
Instruction set extensions used: CMOV, MODE64, SSE1, SSE2
CPU Generation: Intel Core
```

**Comment by creeper-0910** [comment]
**Floorp is NOT supported on Windows 7/8.1 or lower.**

**Comment by sergeevabc** [comment]
@creeper-0910, it has nothing to do with OS, but with CPU features set required during compilation. So the error upon launch is the same be it Windows 7, 10, or 11 if CPU without SSE4.1 is used. Oh well, I rephrased it for you in another issue.

**Comment by creeper-0910** [comment]
I too love WIndows 7, but unfortunately it is no longer supported by MS.

**Comment by andika207** [comment]
> I too love WIndows 7, but unfortunately it is no longer supported by MS.

that's a stupid excuse because many other software utilities still support W7
otherwise you must prove with facts that a W7 security breach would seriously affect the Foorp browser.
will you drop the support for W10 withing 2 years or will you support it because of the upcoming paid updates program ?

**Comment by creeper-0910** [comment]
> > I too love WIndows 7, but unfortunately it is no longer supported by MS.
> 
> that's a stupid excuse because many other software utilities still support W7 otherwise you must prove with facts that a W7 security breach would seriously affect the Foorp browser functioning
> 
> will you drop the support for W10 withing 2 years or will you support it because of the upcoming paid updates program ?

Originally, Floorp was to be configured in ESR115 to refuse installation on Windows 7.
However, due to [user feedback](https://github.com/Floorp-Projects/Floorp/issues/311), installation is now permitted on the condition that **problems encountered with Windows 7 will not be supported**.

**Comment by surapunoyousei** [comment]
@andika207 

Hey. Floorp 11.10.3 extend supported CPU. Maybe you can install Floorp.
