### ISSUE TITLE
[Bug] Error if CPU has no SSE4.1

### ISSUE THREAD

**Issue by sergeevabc** [Floorp-Projects/Floorp#623]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Floorp 11.6.1 only launches on computers with SSE4.1 processors. My laptop, however, has a Core 2 Duo T7250 processor that supports SSE, SSE2, SSE3, so Floorp throws an error upon launch.

[IceCat](https://icecatbrowser.org/download/index.html) browser, which also uses Firefox ESR 115 under the hood, works fine here, because it is compiled with older processors in mind.

Consider compiling the next version of Floorp for a broader audience with SSE2 or SSE3 processors -- it's just a matter of changing one parameter.

### OS Info

Windows 10 x64 IoT LTSC 21H2

### Floorp Version

11.6.1

**Comment by creeper-0910** [comment]
After discussing this issue, it is unlikely to be addressed because Windows 10/11 does not support processors that use the older SSE and cannot support any Floorp issues that may arise related to it.

If we ever support the old SSE, we will let you know at that time.

**Comment by sergeevabc** [comment]
@creeper-0910, what is the basis for your claim that Windows 10 cannot run on processors without SSE4.1? [It can](https://qr.ae/pKUIyW). In particular, my laptop's CPU (Core 2 Duo T7250) supports MMX, SSE, SSE2, SSE3, SSSE3, EM64T, VT-x features and runs Windows 10 fine. The functionality of the browser will not be affected by the fact that you simply lower the number of the minimum required CPU instruction set when compiling.

**Comment by andika207** [comment]
> my laptop's CPU (Core 2 Duo T7250) supports MMX, SSE, SSE2, SSE3, SSSE3, EM64T, VT-x features and runs Windows 10 fine. 

I thought you were using Win7
what's your interest for old web browsers  ?

**Comment by creeper-0910** [comment]
**Windows 10/11  does not support processors**

**Comment by creeper-0910** [comment]
It appears that performance may be sacrificed when adding support for older SSEs.

**Comment by creeper-0910** [comment]
Sorry, Core2Duo did support Windows 10.
But in reality, more SSEs to support will only cause more problems, and we don't have the manpower resources to deal with them.
If there are many similar comments, they may be added.

**Comment by sergeevabc** [comment]
@creeper-0910,
a) the main consumers of SSE optimizations are multimedia applications (e.g. games) and we're talking about a damn browser (browser is not a luxury for the golden billion with the latest OSes and bleeding-edge hardware, but a daily necessity/tool for all people to send some input and receive some output), 
b) the difference between SSE3 and SSE4.1 is a couple of extra FPS, nothing that special,
c) the difficulties with support are far-fetched -- how many software errors in your life can you remember that are associated with the support of certain SSEs? I've been reporting bugs since 1996 and I barely count more such bugs than there are fingers on my hands.

In the end, who are you creating a fork of a famous browser for -- people who don't like the fox logo, or a broader audience who are disappointed by Silicon Valley developers?

**Comment by creeper-0910** [comment]
If there are many similar comments, they may be added.

**Comment by menndouyukkuri** [comment]
There seem to be a lot of very rude statements in this issue that could be interpreted as an attack on the development team or an attempt to stop development.

**Comment by clst** [comment]
The rudeness is not to be tolerated.  
However it is sad to see that older PCs will need to be destroyed and pollute the planet in order to be able to run Floorp on Windows.  
This seems to be the same issue as this Waterfox issue: https://github.com/BrowserWorks/Waterfox/issues/3218#issuecomment-2046095132 (has nothing to do with the version of Windows)  
The performance impact of the optimization setting seems to be minimal there.

On Linux the issue can simply be avoided by using a Linux distribution that supports the CPU (which is almost all of them).

Thank you for a great Browser to the Floorp team.
