### ISSUE TITLE
[Bug] Mutli Row Tabs shake when a 2nd row appears

### ISSUE THREAD

**Issue by Azuretare** [Floorp-Projects/Floorp#625]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When a 2nd row with Multi Row Tabs is formed, all of the browser tabs vibrate until I close enough to go back to 1 row. For some reason they also stop when you open the browser settings.

### To Reproduce

1: Open enough tabs for a 2nd row
2: They start shaking

### Expected behavior

They are still.

### OS Info

Windows 11 22H2 and OpenSUSE Tumbleweed 20231211  running KDE Plasma 5.27.11 in an X11 session

### Floorp Version

11.6.1

### Additional context

I have not yet tested if this happens on Windows or Wayland or another desktop. I tried changing my monitor to 1080p and refresh rate to 60hz and it still happened

**Edit:** I changed a few design settings back and forth and this issue seemed to have disappeared, I am not sure which one caused this.

**Comment by surapunoyousei** [comment]
lepton's problem.

**Comment by surapunoyousei** [comment]
No response close issue
