### ISSUE TITLE
[Bug] Floorp does not honor dark mode setting

### ISSUE THREAD

**Issue by adriankarlen** [Floorp-Projects/Floorp#627]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When browsing a site with css-rule:` prefers-color-scheme: dark/light` it is not using the website appearance setting in Floorp.

### To Reproduce

1. Go to a site setting dark mode based on prefers-color-scheme
2. Setting is not honored

### Expected behavior

Website appearance setting should affect website visited

### OS Info

Wndows 11

### Floorp Version

11.6.1

**Comment by surapunoyousei** [comment]
Please tell me the site

**Comment by surapunoyousei** [comment]
Please tell me the site

**Comment by adriankarlen** [comment]
For me it's every site. For instance setting GitHub to use system setting causes the browser to ignore the system setting.

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/5a361293-8175-4410-9008-6a3562f2d47e)

My env, It's working. Tell me your env

**Comment by DrkXo** [comment]
i think enabling strong protection against fingerprinting overrides **prefers-color-scheme** choice


![image](https://github.com/Floorp-Projects/Floorp/assets/22086701/77bff118-a27f-4c9c-9820-9cde03369619)

**Comment by adriankarlen** [comment]
Okay it was the fingerprinting setting that blocked it. Thank you :)
