### ISSUE TITLE
The width of the sidebar is too small after startup

### ISSUE THREAD

**Issue by regularenthropy** [Floorp-Projects/Floorp#63]
## Describe the bug
The width of the sidebar is too small after startup.

## Screenshots
![image](https://user-images.githubusercontent.com/89523758/191741751-fb76edf7-1023-4d23-8521-5ce7dd920b87.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Floorp Version: 10.6.0 BETA

**Comment by surapunoyousei** [comment]
It's because you added a scrollbar. We have a plan to match the design to the Proton UI, so we will expand the width of the bar at that time.

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/191871597-34a974b9-c6d3-4310-b38b-f35ef7d14806.png)

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/191872017-5cc18c8f-0908-46f5-baaa-434df7803f32.png)
