### ISSUE TITLE
[Bug] Vertical Tabs with enabled workspace switcher don't scroll

### ISSUE THREAD

**Issue by xTunio** [Floorp-Projects/Floorp#632]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Whenever using a window with active workspace switcher, vertical tabs don't scroll and start visually shaking

### To Reproduce

1. Enable:
- vertical tabs
- window with workspace switcher
- (might be unrelated) bottom address bar 
2. Attempt to scroll in window with workspace switcher

### Expected behavior

Tabs should behave like in 2nd window in linked video

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/22046158/4cbe8a27-b55d-410f-b99d-1fc380050e90

### OS Info

Windows 10 22H2

### Floorp Version

11.7.0

**Comment by surapunoyousei** [comment]
The feature will be removed

**Comment by april83c** [comment]
Why is this closed? I'm still having this problem

**Comment by surapunoyousei** [comment]
Workspace V2 has new feature. It will fix this issue
