### ISSUE TITLE
[Bug]  Floorp does not remember windows placements after restart or quit

### ISSUE THREAD

**Issue by Fiffian** [Floorp-Projects/Floorp#633]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

All windows are placed randomly between the screens. So it does not remember last position.

### To Reproduce

1. open multiple windows and place them in each screens.
2. exit and restart the browser.

### Expected behavior

Windows should be reopened and placed on the last screen.

### OS Info

OS: openSUSE Tumbleweed 20231218 x86_64, Kernel: 6.6.6-1, DE: KDE Plasma 5.27.10, WM: KWin (X11)

### Floorp Version

11.7.0 (64-bit)

**Comment by snoozysoft** [comment]
Can confirm a similar problem happens on Windows 11 as well. The browser will always start up unmaximized no matter what, including if the browser was closed in a maximized state.

**Comment by surapunoyousei** [comment]
Please disable betterfox and fingerprint protection

**Comment by Fiffian** [comment]
> Please disable betterfox and fingerprint protection

I have disabled fingerprint and did not have betterfox. The problem still occurs.

**Comment by Fiffian** [comment]
i have uninstalled the app and removed local .var folder and reinstalled. The problem still persists.

**Comment by Fiffian** [comment]
The following works for me:

1. Open Floorp new window
2. Open tabs in that window
3. Move the tabs to your desired screens
4. Now if you quit or exit, it will reopen on the correct screens.

I am not sure if this is a bug or just the excepted behavior.

**Comment by surapunoyousei** [comment]
I can't solve the Firefox problem myself, so please submit it to Bugzilla.

Please make sure that you can reproduce the problem in Firefox before submitting it to Bugzilla.
