### ISSUE TITLE
[Bug] Floorp 11.7.0 "updates" to 11.6.1

### ISSUE THREAD

**Issue by zooool** [Floorp-Projects/Floorp#635]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I use floorp-11.7.0-portable-windows-x86_64. I extract the contents and boot the browser.
I get a notification a download is available, it is downloading and Floorp will be updated on the next launch.
I restart the browser, the notification on my desktop says "Update succeeded!", I go to the Help/About window again and suddenly it says "11.6.1". That can't be right.

### To Reproduce

1. Download the latest portable Windows version.
2. Extract the contents and boot the browser.
3. See that an update is ready, restart the browser.
4. 11.7.0 has now been updated (or rather downgraded) to 11.6.1.

### Expected behavior

The browser should never "update" to a lower version.

### OS Info

Windows 10

### Floorp Version

11.7.0

**Comment by surapunoyousei** [comment]
Fixed

**Comment by ioc2e3** [comment]
> ### 注意力！
> * [x] 據我了解，Windows 7/8.1 或其他版本不支援 Floorp。
> 
> ### 描述錯誤
> 我使用Florp-11.7.0-portable-windows-x86_64。我提取內容並啟動瀏覽器。 我收到一條通知，可以下載，正在下載，Florp將在下次啟動時更新。 我重新啟動瀏覽器，桌面上的突然通知顯示“更新成功！”，我再次進入“幫助/關於”窗口，顯示“11.6.1”。那是不對的。
> 
> ### 重新
> 1. 下載最新的便攜式Windows版本。
> 2. 提取內容並啟動瀏覽器。
> 3. 查看更新已準備就緒，重新啟動瀏覽器。
> 4. 11.7.0現在更新（徹底達到降級）至11.6.1。
> 
> ### 預期行為
> 瀏覽器永遠不應該“更新”到較低版本。
> 
> ### 截圖
> _沒有反應_
> 
> ### 作業系統資訊
> Windows 10
> 
> ### 基礎版本
> 11.7.0
> 
> ### 其他背景資訊
> _沒有反應_

Encountered the same problem ...

And it is ( the entire Floorp Browser is removed and reinstalled ) is useless ...
