### ISSUE TITLE
[Bug] Disabling Mozilla Firefox's keyboard shortcuts breaks bookmarks bar and settings button

### ISSUE THREAD

**Issue by Exogenic** [Floorp-Projects/Floorp#637]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When Mozilla Firefox's keyboard shortcuts are disabled and you open a new window, bookmarks will not show on the bookmarks bar. Also the settings button will not work when clicked. Opening a new tab will work as expected.

### To Reproduce

1. Go to keyboard shortcuts and enable the "Disable Mozilla Firefox's keyboard shortcuts" button.
2. Restart browser for settings to take effect.
3. Open a new window either by file menu or dragging a tab out of the browserwindow to create a new window.

### Expected behavior

Expected behavior is that when creating a new window it should have all bookmarks showing and settings button should work.

### OS Info

Windows 11 23H2

### Floorp Version

11.7.1

**Comment by surapunoyousei** [comment]
I'll fix it
