### ISSUE TITLE
[Bug] Enable row limit for multi-row tabs not working after re-open floorp

### ISSUE THREAD

**Issue by nnh53** [Floorp-Projects/Floorp#641]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When using Tab Bar Style - Multi-Row Tab Bar and Enable row limit for multi-row tabs 

All the tabs still show normal but Row limit not working after re-open floorp 
Only work when re-enable after each floorp open. 

### To Reproduce

1. Turn on Multi-Row Tab Bar
2. Enable row limit for multi-row tabs - enable
3. Number of rows when multi-row tabs are enabled - 3
4. Browse normal 
5. Close Floorp
6. Open Floorp
The setting Enable row limit for multi-row tabs is still enable but not working

### Expected behavior

1. Browse normal 
2. Close Floorp
3. Open Floorp
The setting Enable row limit for multi-row tabs still enable and working

### Screenshots

Before 
![image](https://github.com/Floorp-Projects/Floorp/assets/113448161/6980c707-3f4c-481d-9a58-3cd1552073fb)

After close and open 
![image](https://github.com/Floorp-Projects/Floorp/assets/113448161/d97bc350-c9ba-46fb-8e45-c81590d2eaca)

### OS Info

Windows 10 22H2

### Floorp Version

11.7.1 (64-bit)

**Comment by nnh53** [comment]
can anyone reproduce the bug or is the bug only at my side :<<

**Comment by surapunoyousei** [comment]
I found that why the problem occurred.

**Comment by surapunoyousei** [comment]
Fixed
