### ISSUE TITLE
[Bug] Toggling "Ask to save logins and passwords for websites" to the on position not sticking after browser restart 

### ISSUE THREAD

**Issue by thepick** [Floorp-Projects/Floorp#643]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

After toggling the option for the browser to save usernames and passwords to the on position, it turns off automatically upon restarting the browser.

### To Reproduce

1. Go to Settings -->Logins and Passwords
2. Toggle "Ask to save logins and passwords for websites" to the "on" position
3. Restart Floorp, and it switches to the "off" position again

### Expected behavior

When toggling the option to the "on" position, it should stay in the "on" position until I manually toggle it off.

### OS Info

Windows 11 Pro 23H2

### Floorp Version

11.7.1 (64-bit)

**Comment by surapunoyousei** [comment]
Maybe you install userjs

**Comment by thepick** [comment]
Thank you, @surapunoyousei . That was the issue. Under "Customize Floorp with user.js" I applied "Floorp Default" and now it's fixed. I can't remember user.js on the list I had applied before. It might have been Yokoffing Default.
