### ISSUE TITLE
[Bug] Fully updated Floorp v11.7.1 seems to download update on every start

### ISSUE THREAD

**Issue by astatine** [Floorp-Projects/Floorp#645]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Every time I start Floorp (v11.7.1 portable), the Windows Action Center (Win 10 22H2) shows me two notifications 'Updates found!' followed shortly by 'Ready to update!'. It is possibly updating to the same (current and up-to-date) version on every restart.

### To Reproduce

1. Close Floorp if running
2. Start Floorp
3. Open the Windows Action Center

### Expected behavior

Updates should be downloaded only when a new version is available

### Screenshots

![Floorp Updates](https://github.com/Floorp-Projects/Floorp/assets/1077402/6d0bfe2e-91bb-47fb-9b4c-1e7311963765)

### OS Info

Windows 10 22H2

### Floorp Version

11.7.1

**Comment by CutterKnife** [comment]
Maybe related to this issue: https://github.com/Floorp-Projects/Floorp/issues/635

**Comment by astatine** [comment]
@surapunoyousei Why was this closed? I still see this issue and no update has been released yet.

**Comment by CutterKnife** [comment]
It probably means it will be fixed in the next release.

**Comment by creeper-0910** [comment]
I tested with the portable version of 11.7.1 and could not reproduce the same problem.
Please try downloading again.

**Comment by astatine** [comment]
@surapunoyousei @creeper-0910  This issue is repeating with Floorp v11.8.1. I had to manually download v11.8.2; the portable version didn't update by itself.

Also, does the 'Check for updates' button do anything for the portable version?

**Comment by creeper-0910** [comment]
The "Check for Updates" button does not work on the portable version.
Update notifications are also notified only when an update is present, and are automatically updated on the next startup.

**Comment by astatine** [comment]
> The "Check for Updates" button does not work on the portable version.

Cool.

>Update notifications are also notified only when an update is present, and are automatically updated on the next startup.

So are updates automatically downloaded and 'installed' on portable versions or not? On every Floorp start, I also see a message "Rebuild has been completed." on its status bar (bottom left of UI). What is being rebuilt on every startup?

**Comment by surapunoyousei** [comment]
> > The "Check for Updates" button does not work on the portable version.
> 
> Cool.
> 
> > Update notifications are also notified only when an update is present, and are automatically updated on the next startup.
> 
> So are updates automatically downloaded and 'installed' on portable versions or not? On every Floorp start, I also see a message "Rebuild has been completed." on its status bar (bottom left of UI). What is being rebuilt on every startup?

That is CSS build feature
