### ISSUE TITLE
[Bug] '"Open a new tab" button inside Vertical Tab Bar' setting affects horizontal tabs

### ISSUE THREAD

**Issue by itsTyrion** [Floorp-Projects/Floorp#648]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

If `Show the "Open a new tab" button inside Vertical Tab Bar` is toggled on, it also affects horizontal tabs (they become very small)

### To Reproduce

1. Switch to `Vertical Tab Bar (experimental)`
2. Enable `Show the "Open a new tab" button inside Vertical Tab Bar`
3. Switch to `Horizontal Tab Bar`, the tabs are now very slim

### Expected behavior

horizontal tabs not being affected by a vertical tabs setting

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/17730120/c85218d9-070f-418a-84f3-e333217ca455)
![image](https://github.com/Floorp-Projects/Floorp/assets/17730120/153b889a-d93f-48ac-8b79-d0d8d74516bd)

### OS Info

Windows 11 22H2 

### Floorp Version

11.7.1

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/abd32e6e-7d1d-4e2c-ac48-1d50b157c333)
