### ISSUE TITLE
[Bug] Spotify web player skips most songs

### ISSUE THREAD

**Issue by Moxfi** [Floorp-Projects/Floorp#650]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Attempting to play any song through Spotify Web Player causes the following text:
"Spotify can't play this right now. If you have the file on your computer you can import it".

Works fine in Chrome. Haven't tested in Firefox or Edge.
Re-logged in multiple times. Restarted Floorp and PC multiple times.

Assuming that this is related to data encryption on Spotify's end.
Change of User Agent doesn't fix the issue.

### To Reproduce

1. Go to Spotify Web player (eg. https://open.spotify.com/album/2ssAYAQ5MJq7hfc0Sk79aD)
2. Click Play (playlist, or song)
3. Observe as Spotify returns the text "Spotify can't play this right now. If you have the file on your computer you can import it".

### Expected behavior

Expected to be able to use Spotify Web player.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/25324402/09338a78-6cd3-4fdf-a7fc-567e2ad00a2f)

### OS Info

Windows 10 22H2

### Floorp Version

11.6.1

**Comment by regularenthropy** [comment]
This issue is DRM-related, so it's not fix-able right now.

https://github.com/Floorp-Projects/Floorp/issues/272#issuecomment-1587334609
