### ISSUE TITLE
window options not visible when auto hide is enabled

### ISSUE THREAD

**Issue by viking316** [Floorp-Projects/Floorp#652]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

when floorp is launched it is in minimized size and the window options arent visible when the auto hide is turned on, only workd once its been maximized

### To Reproduce

1. enable auto hide window controls
2. minimize window
3. the window controls arent visible unless its in maximized mode

### Expected behavior

it should show the window controls

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/82701532/91babdc5-e399-478f-ba6e-6506eb9e5cb9

### OS Info

windows 10 22H2

### Floorp Version

Version 11.7.1 (64-bit) | Firefox: 115.6.0

**Comment by surapunoyousei** [comment]
This is a limitation and specification of CSS.
