### ISSUE TITLE
[Bug] Context menu glitch

### ISSUE THREAD

**Issue by hlqviet** [Floorp-Projects/Floorp#653]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Right-clicking somewhere after right-clicking a link makes the context menu show unnecessary separators. Right-clicking again will show the normal context menu. The is triggered again when the actions are repeated.

### To Reproduce

1. Go to any page
2. Right-click any link
3. Right-click anywhere else
4. Observe the separators

### Expected behavior

The context menu should not display unnecessary separators

### Screenshots

Actual result
![image](https://github.com/Floorp-Projects/Floorp/assets/5486625/494f80e2-0387-44c3-8509-574397496804)

Expected result
![image](https://github.com/Floorp-Projects/Floorp/assets/5486625/a08f9db1-2971-4859-b033-84a6757f695b)

### OS Info

Windows 11 23H2

### Floorp Version

11.7.1

### Additional context

Also happens on earlier version with all the UI variants but I didn't know the exact reproduction steps.

**Comment by CutterKnife** [comment]
https://github.com/Floorp-Projects/Floorp/issues/537

**Comment by creeper-0910** [comment]
Close issue due to duplication.
