### ISSUE TITLE
[Bug] Not able to use Firefox sync

### ISSUE THREAD

**Issue by TheChilledBuffalo** [Floorp-Projects/Floorp#658]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Not able to sign into my firefox account for sync features. This is a Windows only issue. I tried it out on Linux but there's no issue there.

### To Reproduce

1. Click on the profile icon
2. Enter your email on the redirected page
3. The page gets stuck at "Working..."

### Expected behavior

Should be able to sign in without hiccups.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/87632612/f330e2bf-f327-4b30-888c-c0568c0acd12)

### OS Info

Windows 11 23H2

### Floorp Version

11.7.1

**Comment by TheChilledBuffalo** [comment]
> Maybe you applied User.js

@surapunoyousei I use the Floorp default User.js

**Comment by surapunoyousei** [comment]
Tets it on new profile

**Comment by TheChilledBuffalo** [comment]
thanks that worked!!

ありがとうございます。
