### ISSUE TITLE
[Bug] Web App open, bookmarks disappear & dual windows opened when web app opened on its own.

### ISSUE THREAD

**Issue by LazKot** [Floorp-Projects/Floorp#659]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

if a Webb App is currently open and you go to open another Floorp window, bookmarks in the new window are not visible, despite the bookmark toolbar being visible. also, every time you open a web app with no floor window open previously, it opens 2 windows.

### To Reproduce

1. Install a web app
2. Close Floorp and open the saved web app the start menu (Windows).

### Expected behavior

what should be expected is another Floorp windows will be automatically open, which is not ideal. Bookmarks are also not visible despite the bookmarks bar being visible. Some occasions the application menu hamburger does not respond after reproducing this issue.

### Screenshots

![Screenshot 2023-12-30 091612](https://github.com/Floorp-Projects/Floorp/assets/38168706/701ded4f-9d9f-4261-8102-550f7e644be8)

### OS Info

Windows 11 22H2

### Floorp Version

11.7.1

**Comment by surapunoyousei** [comment]
It's expexted

**Comment by surapunoyousei** [comment]
So... Bookmark bar issue is tracked another issue
