### ISSUE TITLE
[Bug] Floorp sometimes forgets all installed extensions and setting after restart

### ISSUE THREAD

**Issue by Jozhin-s-Bazhin** [Floorp-Projects/Floorp#662]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Floorp sometimes completely forgets all settings and extensions I installed and resets to default after a restart. 

### To Reproduce

It has happened two times so far:

1.  I had just installed Floorp and was done configuring it, I closed it and when I opened it it was back to defaults. 
2. The second time was when Floorp  wanted to install an update and asked to restart. Floorp closed, I waited a couple of minutes and opened it. It reset again.

### Expected behavior

Floorp not forgetting my settings and extensions.

### OS Info

Arch Linux, Hyprland (Wayland)

### Floorp Version

11.7.1-4 (Installed from floorp-bin)

### Additional context

There was one setting that didn't reset which was the bottom bar that was turned off.

**Comment by TheChilledBuffalo** [comment]
Its an issue with the package. They moved to the `floorp-bin` package only like a week ago and the pkgbuild is not completely ready yet. What happened was it created a new profile. Try switching to your other profile, you old settings will be there.

**Comment by Jozhin-s-Bazhin** [comment]
Thanks, reinstalled it from the floorp package and it works now.
