### ISSUE TITLE
[Bug] On the latest version of Floorp Daylight, the tabs are stacking up vertically on the top bar for some reason.

### ISSUE THREAD

**Issue by TheBeeBoi** [Floorp-Projects/Floorp#663]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

![image](https://github.com/Floorp-Projects/Floorp/assets/97726243/12e8512d-8bc7-4303-ba13-c8b634d08abf)

### To Reproduce

1. Update Floorp Daylight to the commit called "Update submodules".
2. Notice vertical tabs
3. Try opening a different vanilla profile
4. Still the same
5. Open bug report

### Expected behavior

Normal horizontal tabs and/or normal vertical tabs (keep in mind that I do not use or prefer vertical tabs)

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/97726243/63524e68-cb34-47e7-84d8-d308c1e737e1)

### OS Info

Arch Linux with Zen Kernel version

### Floorp Version

11.7.1, build ID 20240101090714

**Comment by surapunoyousei** [comment]
Opps, I will fix it. Thanks

**Comment by s0u7a** [comment]
Same issue at windows 10 pro.

**Comment by surapunoyousei** [comment]
FIxed
