### ISSUE TITLE
[Bug] 1password Browser Exention "Problems Connecting"  

### ISSUE THREAD

**Issue by thelawrencearm** [Floorp-Projects/Floorp#666]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Floorp does not unlock with the Windows 11 app.   Works fine with Firefox.  

![image](https://github.com/Floorp-Projects/Floorp/assets/20508294/f5f772c4-2cfa-4623-8b31-535b9297a316)

### To Reproduce

1. Open 1password app in windows
2. Login and unlock 1password
3. Open Floorp
4. Open the 1password browser extension. 
5. 1password prompts for the master password rather than opening via the integration.  

Open the settings of the extension and find the "Integrate with 1password app"  
error states "problems connecting.  Please make sure the 1password app is unlocked. 

### Expected behavior

Unlocking the 1password app should unlock the browser add-on 

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/20508294/e8b4122c-1ac5-4503-8ffe-871bd066c838)

### OS Info

Windows 11 22H2

### Floorp Version

11.7.1 (64-bit)

### Additional context

I have tried disabling this security.csp.wasm-unsafe-eval.enabled  in the config but it didn't work

**Comment by surapunoyousei** [comment]
This is just not supported by 1Password.

**Comment by surapunoyousei** [comment]
You can use Nightly channel 1Password

**Comment by thelawrencearm** [comment]
1password supports Firefox. Works fine in Firefox ESR and the latest Firefox build.  Just not Floorp.   Nightly\beta build of the addon has the same issue. Below is a screenshot of Firefox working.

![image](https://github.com/Floorp-Projects/Floorp/assets/20508294/41a1f202-7aed-4bd3-9919-d786fec9dff8)

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/666#issuecomment-1877990938
