### ISSUE TITLE
[Bug] New Tab button at far right of window

### ISSUE THREAD

**Issue by NepuShiro** [Floorp-Projects/Floorp#667]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Following the Vertical Tab bug, #663 The New Tab button appears at the far right of the window next to the Minimize button.

### To Reproduce

Update Floorp Daylight to the latest commit.
New tab button is at the far right
Using a different profile provides the same issue
Open bug report

### Expected behavior

The New Tab button to be next to the most recent tab in the Tab list

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/147555953/e610c8c3-9e1b-4718-a8d2-6a2170a39d32)

### OS Info

Windows 11 Pro 23H2

### Floorp Version

Floorp Daylight 11.7.1

**Comment by surapunoyousei** [comment]
So. restart not affect the problem?

**Comment by NepuShiro** [comment]
Restarting doesn't fix this issue

**Comment by surapunoyousei** [comment]
Since I can't reproduce it and there are no other reports, there may be a problem with your customization.

**Comment by glaucon1984** [comment]
I can reproduce this issue.

I have set the following values in "about:config"
**browser.tabs.insertAfterCurrent=true
browser.tabs.insertRelatedAfterCurrent=true**

When I open a new tab with middle click, the tab appears just below the current tab (I'm using vertical tabs) for a fraction of a second, then it's moved to the bottom of the list.

I've also tried with these extensions:
https://addons.mozilla.org/en-GB/firefox/addon/open-tabs-next-to-current/
https://addons.mozilla.org/en-GB/firefox/addon/always-right/

Here is how it looks a fraction of a second after I mid-click the "Google" logo in a google search:
![image](https://github.com/Floorp-Projects/Floorp/assets/54037993/fee1eeef-907d-4250-8abd-24f1aa07ff5d)

Here is just another fraction of a second after, while it's still loading the webpage:
![image](https://github.com/Floorp-Projects/Floorp/assets/54037993/491612ed-d4f2-48b3-b96d-53fa73c9c98d)

Then it just finishes loading and shows the Google favicon:
![image](https://github.com/Floorp-Projects/Floorp/assets/54037993/03b095ad-d2af-4caf-9da1-e77e2e1769f5)
