### ISSUE TITLE
[Bug] dragging out a tab to move it to a new window does not work properly with vertical tab bar

### ISSUE THREAD

**Issue by danielah05** [Floorp-Projects/Floorp#671]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

whenever you drag out a tab out of the tab bar, it moves the tab to an entire separate browser window.

on the horizontal tab bar this works perfectly fine with no issues.

on the vertical tab bar however, if you drag the tab out of the bar inside of the browser still, it will not create a separate browser window, it will only do this if you drag the tab OUTSIDE of the browser.

because of this, moving a tab to a new browser window while the browser is maximized is more annoying now, as you either need to unmaximize the window and then drag it out (unless you have another monitor), or right click and use the "move to" option

### To Reproduce

1. go to settings and enable "vertical tab bar (experimental)" (none of the other extra options matter in this case)
2. try to drag out a tab out of the vertical tab bar onto your browser
3. tab should be moved to a separate window now, but nothing happens instead

### Expected behavior

the dragged out tab should have been moved to a new browser window (as seen as in the attached footage)

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/35849198/6f8b0aa4-7846-4a3e-b39f-3fd518a7cabc

### OS Info

Windows 10 Pro 22H2

### Floorp Version

11.7.1

**Comment by surapunoyousei** [comment]
Duplication
