### ISSUE TITLE
[Bug] Can't use CMD for keyboard shortcuts

### ISSUE THREAD

**Issue by rawkode** [Floorp-Projects/Floorp#672]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I try to set a keyboard shortcut using the CMD modifier on macOS, only the other keys are listed.

### To Reproduce

Try to assign CMD-; to toggle sidebar

### Expected behavior

CMD-; is the shortcut

### OS Info

macOS 14

### Floorp Version

10

**Comment by surapunoyousei** [comment]
It's expected. Not problem

**Comment by repsejnworb** [comment]
> It's expected. Not problem

Can you point to some reference explaining this more, or explain it more?

CMD is not usable for shortcuts?

Man moving from Chrome to Firefox has been a journey.. all I want is to have my next/prev-tab bind that I have everywhere else.

Can you (if CMD isn't usable for some reason) please add/give the option to populate the menubar then with binds? Like "Next Tab" behind under "Window" one can rebind in MacOS Settings.

**Comment by surapunoyousei** [comment]
This is for compatibility between OSes.
