### ISSUE TITLE
Tabs don't open just below the current tab

### ISSUE THREAD

**Issue by glaucon1984** [Floorp-Projects/Floorp#673]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Tabs don't open just below the current tab (using vertical tabs)

I have set the following values in "about:config"
**browser.tabs.insertAfterCurrent=true
browser.tabs.insertRelatedAfterCurrent=true**
(The issue was there before I set those variables to "true")

When I open a new tab with middle click, the tab appears just below the current tab (I'm using vertical tabs) for a fraction of a second, then it's moved to the bottom of the list.

I've also tried with these extensions:
https://addons.mozilla.org/en-GB/firefox/addon/open-tabs-next-to-current/
https://addons.mozilla.org/en-GB/firefox/addon/always-right/

Here is how it looks a fraction of a second after I mid-click the "Google" logo in a google search:
![image](https://github.com/Floorp-Projects/Floorp/assets/54037993/fee1eeef-907d-4250-8abd-24f1aa07ff5d)

Here is just another fraction of a second after, while it's still loading the webpage:
![image](https://github.com/Floorp-Projects/Floorp/assets/54037993/491612ed-d4f2-48b3-b96d-53fa73c9c98d)

Then it just finishes loading and shows the Google favicon:
![image](https://github.com/Floorp-Projects/Floorp/assets/54037993/03b095ad-d2af-4caf-9da1-e77e2e1769f5)

### To Reproduce

Open a new tab with middle click.

### Expected behavior

The new tab should open just below the current tab and stay there.

### Screenshots

See description above.

### OS Info

Windows 11 32H2 (OS Build 22631.2861)

### Floorp Version

11.7.1

**Comment by glaucon1984** [comment]
Forgot to add, this is my configuration under "about:preferences":

![image](https://github.com/Floorp-Projects/Floorp/assets/54037993/62ea3914-d67d-43c0-b1ba-3e7eb156b29c)

**Comment by surapunoyousei** [comment]
I cannot reproduce teh bug

**Comment by surapunoyousei** [comment]
browser.tabs.insertAfterCurrent=true
browser.tabs.insertRelatedAfterCurrent=true

This preferences affect to your problem. Please revert to default

**Comment by glaucon1984** [comment]
The problem was there before I set those preferences.

**Comment by surapunoyousei** [comment]
Yeah. It's not reproduce.

**Comment by glaucon1984** [comment]
After disabling the Firefox extension "Tree Style Tab", tabs behavior now is the expected one.

**Comment by surapunoyousei** [comment]
Ah...
