### ISSUE TITLE
[Bug] Bottom bookmarks bar disappears completely with particular settings

### ISSUE THREAD

**Issue by bataneske** [Floorp-Projects/Floorp#677]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Only Show on New Tab preference always hides the toolbar, even on New Tab.
**Note: You have to restart the browser for this change to take effect!** 

### To Reproduce

1. "Show the Bookmarks Toolbar at the bottom of Floorp" is ON
2. Right click the Bookmarks Toolbar
3. Bookmarks Toolbar -> Only Show on New Tab

### Expected behavior

Toolbar should be absent on every page, except for the New Tab/Floorp Homepage.

### Screenshots

![Screenshot from 2024-01-10 16-46-40](https://github.com/Floorp-Projects/Floorp/assets/107265248/8b71525e-a2b3-4342-8fa5-f2c938f733b3)

Bookmarks Toolbar (bottom) with Always Show option selected

![Screenshot from 2024-01-10 16-47-38](https://github.com/Floorp-Projects/Floorp/assets/107265248/8d673bd1-5050-4f08-bfcf-d6c18efbbd30)

Bookmarks Toolbar (bottom) with Only Show on New Tab option selected

### OS Info

Fedora Linux 38 (Workstation Edition) with Linux 6.2.9-300.fc38.x86_64

### Floorp Version

Floorp for Flatpak 11.7.1 (64-bit) 

### Additional context

Only Show on New Tab works properly if _Show the Bookmarks Toolbar at the bottom of Floorp_ is disabled. To see your bookmarks again, disable said option.

**Comment by TheChilledBuffalo** [comment]
I'll try to fix it.

**Comment by surapunoyousei** [comment]
Oh... Really? Thanks!

**Comment by TheChilledBuffalo** [comment]
@surapunoyousei I'm really sorry. I tried a lot but I couldn't fix it. Sorry again...

**Comment by surapunoyousei** [comment]
Don't say "sorry". You did nice try!!! I'll fix it.

**Comment by surapunoyousei** [comment]
Fixed
