### ISSUE TITLE
[Bug] Custom search engines do not find an icon

### ISSUE THREAD

**Issue by embyveddii** [Floorp-Projects/Floorp#680]
### Attention!

- [x] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When you add custom search engines, it will not find an icon for this. Even when using the search engine or restarting the browser, all the icons are the default grey ones which makes it really hard to distinguish each one. I'm sure it should be as easy as detecting the favicon of the site used to search?
Adding a search engine in the page (by pressing the green plus on the search bar) seems to use icons correctly however.

### To Reproduce

1. Go to about:preferences#search
2. Add a search engine (or a few) to Search Shortcuts
3. All custom engine icons stay blank permenantly

### Expected behavior

They should find the site's icon and use that so you can distinguish between them. 

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/59317664/bc55a539-e502-4ed1-8601-b83c951b739d)

### OS Info

Windows 10 Pro 22H2 19045.3930

### Floorp Version

11.7.1 (64-bit)

**Comment by surapunoyousei** [comment]
This is not a bug. Please send Feature request
