### ISSUE TITLE
[Bug] Bookmark's star button doesn't work

### ISSUE THREAD

**Issue by sickmitch** [Floorp-Projects/Floorp#682]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When clicking the star to add a link to bookmarks nothing happens.

### To Reproduce

1. Go to an unmarked address
2. Click the star to add it to bookmarks

### Expected behavior

Add the address to bookmarks

### Screenshots

![Recording](https://github.com/Floorp-Projects/Floorp/assets/134487828/5ba8bfdd-bbea-46ef-b6e3-2416170ab0e0)

### OS Info

Arch Linux

### Floorp Version

Mozilla Floorp 11.7.1 20231219011847

### Additional context

System is all up to date, on Firefox the star button works.

**Comment by surapunoyousei** [comment]
Need more info

**Comment by sickmitch** [comment]
> Need more info

Up to give whatever is needed. The problem persist without extensions and on a freshly spin up VM. Ask whatever you need and I'll give it to you.

**Comment by surapunoyousei** [comment]
Didi you change preferences relate to bookmark bar?

**Comment by sickmitch** [comment]
> Didi you change preferences relate to bookmark bar?

I'm using Firefox Photon with Lepton design, with bookmarks bar showing ever. Tried adding bookmarks "by hand", right click the bookmarks bar -> add bookmark, and it works flawlessly.
Tried stock too but doesn't make it work.

**Comment by surapunoyousei** [comment]
Ok. Try this on new profile

**Comment by surapunoyousei** [comment]
hello??? @sickmitch

**Comment by surapunoyousei** [comment]
No reply. Close issue

**Comment by sickmitch** [comment]
I've been on travel for a week, sorry for disappearing.
On my back got a floorp update and now seems to work.
Thanks for your time and sorry again.

**Comment by surapunoyousei** [comment]
Ahh. OK. No Problem
