### ISSUE TITLE
Show Your Bookmark button opens popup menu with overlapping icons and texts for fixed items

### ISSUE THREAD

**Issue by artist-linux** [Floorp-Projects/Floorp#683]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The Show Your Bookmark button opens a popup menu with some fixed items, and the actual bookmarks and folders.
For the fixed items the icon and text overlap, so this occurs for these items:
- View bookmarks sidebar
- Search bookmarks
- Manager bookmarks

### To Reproduce

Add the Show Your Bookmark button to the toolbar
Click on the button

### Expected behavior

Text should be besides icon.

### Screenshots

![floorp-bookmark-menu-overlap](https://github.com/Floorp-Projects/Floorp/assets/76697611/b9f13877-238c-4e94-bfdb-1c149e2e9c16)

### OS Info

Artix Linux

### Floorp Version

11.7.1

**Comment by surapunoyousei** [comment]
Fixed
