### ISSUE TITLE
[Bug] Nicochannel video player unsupported

### ISSUE THREAD

**Issue by kusahopper** [Floorp-Projects/Floorp#686]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

If user accesses a video from Floorp, it says このブラウザはサポートされていません。 (en translate: this browser is not supported), then video and live is not playable. This issue is has already been resolved in upstream firefox, but persists in floorp.

Original bug and fix in Firefox:
https://github.com/webcompat/web-bugs/issues/124463
https://bugzilla.mozilla.org/show_bug.cgi?id=1849058

Attached screenshots for further context.

### To Reproduce

Go to a nicochannel page and click a link that directs to video page.

### Expected behavior

Video embed playback should work as normal.

### Screenshots

![Screenshot 2024-01-15 at 22-04-49 2024年初のFC配信💎](https://github.com/Floorp-Projects/Floorp/assets/124662404/74a7e999-bca2-4b4e-8541-1f679b795f33)
![Screenshot 2024-01-15 at 22-04-50 2024年初のFC配信💎](https://github.com/Floorp-Projects/Floorp/assets/124662404/c38ba9ed-154f-41eb-8699-ae99876c88a6)

### OS Info

Windows 10

### Floorp Version

11.7.1

### Additional context

Site used in screenshot example:
https://nicochannel.jp/shiratamautano/

**Comment by surapunoyousei** [comment]
Shit. It's Japanese Company.

**Comment by surapunoyousei** [comment]
I'll add injection

**Comment by surapunoyousei** [comment]
Fixrd
