### ISSUE TITLE
[Bug]  when i try to open floorp browser it dosent open nothing happen pls show me how to fix it i wanna try this browser

### ISSUE THREAD

**Issue by RUOKexe** [Floorp-Projects/Floorp#689]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

when i double click at the browser to open it nothing happen idk why

### To Reproduce

i click on floorp browser it dosent open

### Expected behavior

help me pls to fix it !

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/148570728/33857409-a097-4e4a-8294-b1d4619a9238

### OS Info

windows 10 22h2

### Floorp Version

latest i gusse ofc site

**Comment by surapunoyousei** [comment]
Why.....

**Comment by surapunoyousei** [comment]
Did you try reboot  your pc?

**Comment by RUOKexe** [comment]
> Did you try reboot your pc?

no

**Comment by RUOKexe** [comment]
> Did you try reboot your pc?

> try it
ok i will

**Comment by RUOKexe** [comment]
> try it

it didnt work same prblm

**Comment by surapunoyousei** [comment]
https://support.mozilla.org/kb/diagnose-firefox-issues-using-troubleshoot-mode

**Comment by RUOKexe** [comment]
> https://support.mozilla.org/kb/diagnose-firefox-issues-using-troubleshoot-mode

is this floorp or firefox !!!

**Comment by RUOKexe** [comment]
> https://support.mozilla.org/kb/diagnose-firefox-issues-using-troubleshoot-mode

what should i do here

**Comment by surapunoyousei** [comment]
Honestly, There is no another submitter. Most user can use Floorp. Please check your environment.

**Comment by surapunoyousei** [comment]
> > https://support.mozilla.org/kb/diagnose-firefox-issues-using-troubleshoot-mode
> 
> what should i do here

You should start with the mode.

**Comment by RUOKexe** [comment]
> > > https://support.mozilla.org/kb/diagnose-firefox-issues-using-troubleshoot-mode
> > 
> > 
> > what should i do here
> 
> You should start with the mode.

thats weird why dosent work

**Comment by creeper-0910** [comment]
try reinstalling or offline installer

**Comment by surapunoyousei** [comment]
It is no more in my hands. Most people can handle Floorp just fine. I don't have your device so I can't help you any further.

Please try the portable version. No further replies are needed.

**Comment by RUOKexe** [comment]
> try reinstalling or offline installer

i tryd offline instaler first dosent work yeh

**Comment by RUOKexe** [comment]
> It is no more in my hands. Most people can handle Floorp just fine. I don't have your device so I can't help you any further.
> 
> Please try the portable version. No further replies are needed.

hmm lets see when ppl start instaling we will se if they will face the same prblm
