### ISSUE TITLE
[Bug] Picture in Picture is completely broken in browser manager sidebar

### ISSUE THREAD

**Issue by github-user93** [Floorp-Projects/Floorp#692]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The picture in picture is completely unusable when using on a page opened on browser manager sidebar.

### To Reproduce

1. Open any website with video on the browser manager sidebar
2. Try to use picture in picture

### Expected behavior

The picture in picture window is completely unusable, and can not be closed (needs to be closed from OS taskbar)

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/127530649/cc332b7c-4197-46b4-9f91-6a42f6e0a5a3)

### OS Info

Windows 10 21H2

### Floorp Version

11.7.1

**Comment by surapunoyousei** [comment]
It expected
