### ISSUE TITLE
[SOLVED] [Bug]  Floorp doesn't floorp hard enough

### ISSUE THREAD

**Issue by Honkychunkymonkey** [Floorp-Projects/Floorp#693]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Yknow I'm just flooprin' around and stuff, like normal, but when I try to floorp, hardly any floorp comes out of the floorp hole!

### To Reproduce

Grab your floorp, start floorping it, keep going, little bit more, and then boom, floorp all over the place

### Expected behavior

It should floorp hard

### OS Info

Floorp OS

### Floorp Version

Floopity

**Comment by TheChilledBuffalo** [comment]
?????

Please don't joke around. Its not like you don't know this already but this is the place for you to file reports on genuine issues you face with the product.

**Comment by p134c0d3** [comment]
I was genuinely confused by this...

**Comment by d00d00fart** [comment]
floorpy floorp
