### ISSUE TITLE
[Bug]  Attempting to update Floorp in Pop!_OS 22.04 LTS returns a 404 error

### ISSUE THREAD

**Issue by p134c0d3** [Floorp-Projects/Floorp#694]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I received a notification that Floorp had an update, so I attempted to update it within my ZSH shell terminal. It acts like it updates the repo just fine when using the command, `sudo nala update` or `sudo apt update`. However, when I run `sudo nala upgrade` or `sudo apt upgrade` I then get the following errors: "Client error '404 Not Found' for url 'https://ppa.floorp.app/amd64/floorp-11.8.0.deb", "No more mirrors available for floorp-11.8.0.deb", and finally "Download failure. The following downloads failed:" where it then lists the Floorp .deb package. Screenshot is attached as well.

**Just to note, I added the PPA and followed instructions exactly as displayed on the Floorp official website. Copiied and pasted each command.

### To Reproduce

1. Open terminal (whether with bash or zsh, doesn't matter)
2. Run `sudo nala update` or `sudo apt update`
3. Run `sudo nala upgrade -y` or `sudo apt upgrade -y`
4. Error received

### Expected behavior

I expected the Floorp package to be successfully upgraded to 11.8.0

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/70922864/239ef13e-2fd2-4319-91b2-16fb42ee3fa3)

### OS Info

Pop!_OS 22.04 LTS

### Floorp Version

Current: 11.7.1 ~> Version to upgrade to: 11.8.0

### Additional context

System is completely up to date other than this one package. Rebooted a few times to see if that helped as well.

**Comment by creeper-0910** [comment]
The problem is regularly reported, but the cause is unknown...
We apologize for the inconvenience, but please download the file from "https://ppa.floorp.app/amd64/floorp-11.8.0.deb" and install it or wait a while and try again.

**Comment by p134c0d3** [comment]
No worries! I actually tried again here a few minutes go, and while the download was a decent amount slower than usual, it actually connected and downloaded and upgraded the package! I'll close this since it's no longer happening. In the future, I'll just wait a bit and try again.

Thanks for a phenomenal browser team.

**Comment by tukiminya** [comment]
Close again with "Close as not planned" as the cause remains unknown.
Thanks for the report @p134c0d3 !
