### ISSUE TITLE
[Bug] Touchpad Gestures and Kinetic Scrolling on Linux

### ISSUE THREAD

**Issue by vigneshpai2003** [Floorp-Projects/Floorp#696]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Touchpad gestures and kinetic scrolling (which work on firefox out of the box) do not work on my system (Ubuntu 23.10, Wayland). Setting the environment variable MOZ_ENABLE_WAYLAND=1 does not help. I checked the relevant settings in about:config and they are set to the correct values. 

### To Reproduce

Touchpad gestures (ex: two finger swipe to go back a page) does not work out of the box.

### Expected behavior

Touchpad gestures and kinetic scrolling is expected to work as in firefox.

### OS Info

Ubuntu 23.10 (Wayland)

### Floorp Version

11.8.0

**Comment by kgorol** [comment]
@vigneshpai2003 did you find the solution? Gestures seem not to work on Arch/Garuda install.

**Comment by vigneshpai2003** [comment]
I have moved to NixOS now, and the above features work out of the box. Perhaps try installing from an alternative package source (flatpak, nix etc), it is most likely a configuration issue and not a bug. Also remember to relogin once after installation, that sometimes fixes things too.

**Comment by ErranticSam** [comment]
I also encounter this issue on Debian 12, using Wayland and the PPA package of Floorp ... 
Is just Wayland not supported yet by Floorp or is it a real bug ?

**Comment by creeper-0910** [comment]
Wayland is currently not supported.
