### ISSUE TITLE
[Bug]  User-Agent Spoofing does not work with cloudflare protected sites

### ISSUE THREAD

**Issue by kriptn** [Floorp-Projects/Floorp#697]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

As mentioned in the title, the UA spoofing doesn't work with **cloudflare turnstile** using websites and causes and infinite checking.

### To Reproduce

1. Go to chat.openai.com
2. Done

### Expected behavior

![image](https://github.com/Floorp-Projects/Floorp/assets/62275748/b69e53cf-5b70-427c-9f06-1032c614d6c2)

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/62275748/89de1ede-3cca-49c8-bdc7-82d77da471b3)

### OS Info

Any. Windows 11/Ubuntu

### Floorp Version

11.8.0

**Comment by creeper-0910** [comment]
Not a bug.
This should not be possible to avoid in disguising the UserAgent.
