### ISSUE TITLE
[Bug] ワークスペースが複数あるときにブラウザーマネージャーサイドバーに表示される

### ISSUE THREAD

**Issue by menndouyukkuri** [Floorp-Projects/Floorp#698]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

ワークスペースが複数あるときに、設定にかかわらずブラウザーマネージャーサイドバーに表示され、ツールバーのボタンから切り替えることができなくなります。

### To Reproduce

1. ワークスペースを複数作る
2. ブラウザーマネージャーサイドバーにワークスペースが表示される

### Expected behavior

「ブラウザーマネージャーサイドバーでワークスペースを管理」の設定がオフになっている場合、ワークスペースはツールバーのボタンから切り替えられる。

### Screenshots

![2024-01-17_17h32_30](https://github.com/Floorp-Projects/Floorp/assets/61068665/3f0c0eb8-1fa2-4f65-bd76-2278e55c052f)
![2024-01-17_17h32_48](https://github.com/Floorp-Projects/Floorp/assets/61068665/5870a4ed-8dd3-4068-9156-10793ee0b10e)

### OS Info

Windows 11 23H2 / Zorin OS 17 (Linux)

### Floorp Version

11.8.0

**Comment by surapunoyousei** [comment]
なおした
