### ISSUE TITLE
[Bug] Cannot install firefox extensions

### ISSUE THREAD

**Issue by Emrozgs** [Floorp-Projects/Floorp#699]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

For some reason the firefox addons page isn't recognizing floorp as an instance of firefox.

### To Reproduce

You should see this issue if you just visit the addons page, to install any firefox addon

### Expected behavior

Floorp is just enhanced firefox, addons should be able to be installed as such

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/101697991/3ca41e34-5fdf-45f7-b89c-fab1aa287db6)

### OS Info

MacOS Monterey

### Floorp Version

11.8.0

**Comment by creeper-0910** [comment]
Are you disguising the UserAgent?

**Comment by Emrozgs** [comment]
> Are you disguising the UserAgent?

Please excuse me, but I was using s disguised UserAgent.

**Comment by creeper-0910** [comment]
No problem. I'm glad it's resolved!

**Comment by antheiz** [comment]
I get same problem.
How to solve this issues?

**Comment by surapunoyousei** [comment]
Revert user agent to default.

**Comment by antheiz** [comment]
Ok, Thank you!
