### ISSUE TITLE
[Bug] Show sidebar over website content doesn't work

### ISSUE THREAD

**Issue by PetricaT** [Floorp-Projects/Floorp#701]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The feature that is marked as "Show Sidebar over website content" from the Lepton UI settings does not work. It still resized the website in order to fit the sidebar window.

### To Reproduce

1. Enable "Show Sidebar over website content" in Settings > Design > Firefox Photon - Lepton UI
2. Open any application in the sidebar

### Expected behavior

The sidebar applet draws OVER the website, so it doesn't resize the window.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/24418935/991416c5-72f7-4ed7-bf28-fb75ea76743b)
![image](https://github.com/Floorp-Projects/Floorp/assets/24418935/4446d069-806c-49f6-a0f7-319d2e488cec)

### OS Info

Windows 10 22H2

### Floorp Version

Version 11.8.0 (64-bit) | Firefox: 115.7.0

### Additional context

The theme is selected, but the issue persists
![image](https://github.com/Floorp-Projects/Floorp/assets/24418935/cd3a6efc-491c-4057-aa19-141b6ff11d73)

**Comment by surapunoyousei** [comment]
It's not affect to Floorp Sidebar. affect to Firefox sidebar

**Comment by PetricaT** [comment]
Ah okay I get it, the naming was very confusing since they are both called Sidebar. Would it be possible to extend that functionality to make the Floorp Sidebar draw over websites too?

**Comment by surapunoyousei** [comment]
Yeah. We have plan about that.
