### ISSUE TITLE
[Bug] Rounded corner white pixels in dark mode

### ISSUE THREAD

**Issue by Silther** [Floorp-Projects/Floorp#702]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

if rounded corners are enabled you can see white pixels if the browser is in dark mode and the website to

### To Reproduce

1. activate dark mode int the browser
2. open a webpage with darkmode (or a dark part in the corner)
3. activate rounded corners
4. a few white pixels are shown

### Expected behavior

there shouldn't be distracting white pixels.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/97352673/8a0a3348-0cef-4e2d-ac1a-354082206704)

### OS Info

Windows 11

### Floorp Version

11.8.0

**Comment by surapunoyousei** [comment]
This is CSS issue. No way to fix it....

**Comment by surapunoyousei** [comment]
So... In the past, Rounded corners feature is implemented by `Border-radius` but, Current version uses `clip-path: inset(0px 0px 0px round 0 0) !important;`

Mozilla maybe fixes this issue. Depend on it

![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/92882dbf-3e0b-410a-8c3e-e28dfa9ed3b1)

**Comment by surapunoyousei** [comment]
I'll think that
