### ISSUE TITLE
[Bug] Firefox Sync stuck on "Working...."

### ISSUE THREAD

**Issue by Sparkrdom** [Floorp-Projects/Floorp#703]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I'm unable to login to Firefox Sync to grab any info and sync data.

### To Reproduce

1. Open Floorp
2. Attempt to login to sync options
3. Enter email associated with sync data, attempt proceed to next step
4. Loading stays on "Working..."

### Expected behavior

I successfully login and gather my sync data as I can in regular Firefox, and in Firefox ESR

### Screenshots

![2024-01-17_06-57](https://github.com/Floorp-Projects/Floorp/assets/22569083/9cd06d0f-d2c6-48a1-8525-ddb36d752502)

### OS Info

Windows 11 22H2

### Floorp Version

11.8.0

### Additional context

Identical to https://github.com/Floorp-Projects/Floorp/issues/461, except I have confirmed that ESR works for me, so the issue is localized to Floorp.

I have also used Mull, Fennec, and a few others and can use Sync without issue.

I have tried uninstalling, clearing appdata, and reinstalling Floorp.

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/issues/658

**Comment by creeper-0910** [comment]
Try creating a new profile.

**Comment by Sparkrdom** [comment]
I installed Floorp, and when it didn't work, I used https://www.bcuninstaller.com/ to uninstall it completely from the PC. I then installed Firefox ESR to test if the profiles worked, and they did. I then uninstalled Firefox the same way, just in case, and then reinstalled Floorp, to the same problem.

I assume they don't expect new users to create a new profile on a brand new install just to make Sync work. Hopefully that gets fixed in a future release :)

**Comment by creeper-0910** [comment]
To be honest, this is a problem that has been reported several times but never reproduced in the developer's environment... Might be difficult to fix.

**Comment by Sparkrdom** [comment]
Ahh, the old unreproducible error. Well, glad making a profile is an easy workaround. 

Thanks for the quick help, I missed that other issue, or I would have solved it myself when looking for answers.

**Comment by hermitpopcorn** [comment]
Sorry for joining in when when the issue's already been closed, but this happened to me too.

I think it's because the user agent spoofing settings. Setting it to "Spoof Chrome on Windows" causes the endless "Working..." bug, but setting it back to "Use Firefox User Agent" causes the page to work again.

**Comment by surapunoyousei** [comment]
I will remove userAgent preferences. due to this issue
