### ISSUE TITLE
[Bug] Floorp crashes on MacOs Sierra 10.12 though firefox(115) works fine

### ISSUE THREAD

**Issue by newinnov** [Floorp-Projects/Floorp#705]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Opening floorp on Macos Sierra fails with error - Floorp quit unexpectedly.

### To Reproduce

1. Install Floorp 
2. Open Floorp via Launchpad
3.  Floorp crashes

### Expected behavior

It should just open instead of crashing. Same version firefox 115 works fine

### OS Info

Macos

### Floorp Version

10.12.6

**Comment by surapunoyousei** [comment]
Please tell me about your mac

**Comment by surapunoyousei** [comment]
No response
