### ISSUE TITLE
[Bug]  Collapsed Vertical Tab Bar shows a scrollbar even when vertical scrollbar option unchecked

### ISSUE THREAD

**Issue by Sarah-Connelli** [Floorp-Projects/Floorp#707]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The vertical tab bar is showing a vertical scrollbar which hides a quarter of the tab icon when bar is collapsed.
Also the bar shows the scrollbar when the vertical tab bar is not collapsed.

### To Reproduce

Install v11.8.0
Enable vertical tab bar, make it collapsable, uncheck vertical-tabs scrollbar.

### Expected behavior

There should not be a vertical scrollbar on the vertical tab bar unless the option is checked in the settings. However it seems that option is relative to a custom scrollbar which shows alongside a 'system' vertical scrollbar.

The system vertical scrollbar on the vertical tab bar should be disabled.

### OS Info

Windows 11 23h2

### Floorp Version

11.8.0

**Comment by surapunoyousei** [comment]
This issue will fix it and eill remove scrollbar option

**Comment by Sarah-Connelli** [comment]
![tabar](https://github.com/Floorp-Projects/Floorp/assets/94207965/35eec1ec-0bfb-403c-a8c9-a7188c3f142f)

**Comment by surapunoyousei** [comment]
Scrollbar will be hide.
