### ISSUE TITLE
[Bug] Downloading Yokoffing Fastfox as user.js fails - only content is   404: Not Found

### ISSUE THREAD

**Issue by artist-linux** [Floorp-Projects/Floorp#708]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Applying, so downloading, Yokoffing Fastfox from the Settings page as user.js fails - only content is   404: Not Found

The only item that downloads correctly is Yokoffing Default.
All others result in an empty user.js file, or the file only having content   404: Not Found

### To Reproduce

1. Open Settings / Customize Floorp with user.js
2. For item "Yokoffing Fastfox" click on "Apply"
3. The downloaded user.js file's only content is   `404: Not Found`

### Expected behavior

File user.js should have the content of https://raw.githubusercontent.com/yokoffing/Betterfox/115.0/Fastfox.js or maybe a newer release.
Eg. `wget -O user.js https://raw.githubusercontent.com/yokoffing/Betterfox/115.0/Fastfox.js` works fine

### OS Info

Artix Linux

### Floorp Version

11.8.0

**Comment by surapunoyousei** [comment]
Floorp is ESR115 bases. Please check your internet connection

**Comment by artist-linux** [comment]
My net work is ok, as a manual download works fine:

```
wget -O user.js https://raw.githubusercontent.com/yokoffing/Betterfox/119.0/Fastfox.js  
--2024-01-18 18:05:20--  https://raw.githubusercontent.com/yokoffing/Betterfox/119.0/Fastfox.js
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39538 (39K) [text/plain]
Saving to: ‘user.js’

user.js                                 100%[==============================================================================>]  38.61K  --.-KB/s    in 0.004s  

2024-01-18 18:05:20 (9.38 MB/s) - ‘user.js’ saved [39538/39538]
```

- Yokoffing Default downloads and install OK from within Floorp
- Yokoffing Fastfox does NOT download and install OK from within Floorp; the resulting user.js file shows `404: Not Found` which is the reply from the webserver

Not sure why only Yokoffing Default works.

**Comment by matti-kz** [comment]
Hello,
I can confirm this is not working, I also find only `404: Not Found` in `user.js` after applying Fastfox
Changing the file manually is impossible as well because it is being overwritten with `404: Not Found` on browser restart.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp-core/pull/30
