### ISSUE TITLE
hung up whilst working[Bug] 

### ISSUE THREAD

**Issue by zeziw** [Floorp-Projects/Floorp#709]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Third times a charm! Im trying to use floorp more. However my main issue is when i go to log into my mozilla account, i enter my gmail email that is associated with it, and it proceeds to say 'working' with the thing churning showing it's still working. but it never gets any furher

### To Reproduce

open floorp
press three verticle buttons on the upper right side
Press the sign in button
Try singing in
gets hung up for ages
doesn't ever log in

### Expected behavior

I log into my gmail account that's associated with firefox so I can use the extensions and what not, also access to update saved passwords and bookmarks

### OS Info

windows 10

### Floorp Version

11.7.1 (64-bit

### Additional context

cant switch to the app if its consistantly gonna let me down. I also don't comprehend japanese, making a  lot of proprietary information in the settings unreadable. and since i cant have access to get extensions. it forever sits unreadable

**Comment by TheChilledBuffalo** [comment]
#703 and #658 

This issue as of now, unfortunately, cannot be reproduced in a developer environment. So please create a new profile. That should fix it.

**Comment by surapunoyousei** [comment]
Delicate
