### ISSUE TITLE
Make the new sidebar keep content loaded when switching between different sidebar links.

### ISSUE THREAD

**Issue by sakanatha** [Floorp-Projects/Floorp#71]
Make the new sidebar keep content loaded when switching between different sidebar links. Basically treat the sidebar links as tabs. I get that it's not an easy task but currently without this feature there's not that much point in switching links with web content.

**Comment by surapunoyousei** [comment]
This is technically possible, but it takes time and effort. I can't implement it right away, but I would like to work on it.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/commit/3c78c90db3e21d0107192338887f1452b91a269a
