### ISSUE TITLE
[Bug] Debian Repo not installing latest version

### ISSUE THREAD

**Issue by nekolifestyle** [Floorp-Projects/Floorp#710]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

`sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  systemd-hwe-hwdb tzdata tzdata-icu tzdata-legacy
The following packages will be upgraded:
  floorp
1 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Need to get 92.5 MB of archives.
After this operation, 352 kB disk space will be freed.
Do you want to continue? [Y/n] y
Err:1 https://ppa.floorp.app/amd64 ./ floorp 11.8.1
  404  Not Found [IP: xxxx:xxxx:xxxx::xxxx:xxxx xxx]
E: Failed to fetch https://ppa.floorp.app/amd64/./floorp-11.8.1.deb  404  Not Found [IP: xxxx:xxxx:xxxx::xxxx:xxxx xxx]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

Using apt-get update and --fix-missing is not fixing issue.

### To Reproduce

Run sudo apt-get update and sudo apt-get upgrade

### Expected behavior

Should update floorp to latest version

### OS Info

Debian Linux

### Floorp Version

11.8.0

**Comment by GBT55** [comment]
+1

**Comment by surapunoyousei** [comment]
Deplicate
