### ISSUE TITLE
[Bug] Cannot use disabled Default Firefox Keybinds for Extensions

### ISSUE THREAD

**Issue by Hempflingclub** [Floorp-Projects/Floorp#711]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

With unbound Firefox keybinds, when trying to use the unbound keybinds for extension specific keybinds it gives the error
"Floorp-Keybinds cannot be overwritten"

### To Reproduce

1. Unbind Firefox Keybinds
2. Reboot Floorp
3. Go into Extensions Keybind Settings
4. Try to use Firefox Default Keybind (tried CTRL+Shift+Y)

### Expected behavior

Able to be rebind the key, as it's not bound to any behaviour.

### OS Info

Debian 12 / Plasma Wayland

### Floorp Version

11.8.0

**Comment by Hempflingclub** [comment]
Also tested on 11.8.1

**Comment by surapunoyousei** [comment]
Firefox's issue. We will not fix it
