### ISSUE TITLE
[Bug] Can't configure shortcut with arrow-up/arrow-down/arrow-left/arrow-right

### ISSUE THREAD

**Issue by Eragonfr** [Floorp-Projects/Floorp#714]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When using the Keyboard Shortcuts configuration menu and recording the keyboard the arrow-up/down/right/left keys are caught by the "Select an action to trigger" menu in the popup.
This apply to using Shift and arrow-up/down too, which will change the workspace without closing the popup nor stoping the keyboard recording.

### To Reproduce

1. Go to about:preferences#cSK
2. Click on "Add shortcut"
3. In the popup click on "Start listening"
4. Use any of the "arrow" key
5. Watch the "Select an action to trigger" menu being changed

### Expected behavior

The "Start listening" button should catch all key being pressed even if they should trigger any other functionality of the browser. Effectively disabling the keyboard for the rest of the browser.
And registering the keys as a new keybinding overwriting all already defined keybinds with those keys.

### OS Info

Linux - Artix Linux on Wayland, WM: Sway

### Floorp Version

11.7.1

### Additional context

I was trying to change the keybinding for the workspace switch action, because I already use Shift and Arrow up/down to select text in multi-line texts.

**Comment by surapunoyousei** [comment]
It expected

**Comment by Eragonfr** [comment]
Why tho ? It means I can't rebind the workspace buttons to control, shift, arrow-up/down

**Comment by surapunoyousei** [comment]
Since we are using Mozilla's keyboard shortcut principle, we must wait for Mozilla to make the change and for the arrow keys to become available.

**Comment by Eragonfr** [comment]
Upstream limitation then ? I'll ask for it on bugzilla

**Comment by surapunoyousei** [comment]
**Bugzilla is not a place where you are free to ask questions. Please do not do this.**

Your actions will waste the time of many Mozilla employees and indirectly make Firefox worse.

If I am seeing things correctly, arrow keys are not available in Mozilla's shortcut key implementation. If they can be used, you should implement them.

**Comment by Eragonfr** [comment]
I took some time to debug the settings. And it seems that it's this `key.length == 1` check that fails for key `ArrowUp` or `ArrowDown`.
https://github.com/Floorp-Projects/Floorp-core/blob/c8d5d6dd448baa99c1b7b5bf3e0ad6409ef3c3d4/browser/components/preferences/dialogs/manage-keyboard-shortcut.js#L98

I think it's the same for PageUp/PageDown and a lot of other keys that just aren't between `F1` and `F24`.
Currently those conditions only allows for a combination of some modifiers `Alt`, `Control`, `Shift` and `Tab`. Which is probably sufficient. A key from the F keys `F1` to `F24` (`keycodesList`) or a key which have a name of length equal to 1.
Which mean, all alphanumeric keys, and F1 to F24 + any number of modifiers.

I don't think it's a problem on Mozilla's side, but in your conditions where you exclude keys that are perfectly valid from the CustomKeyboardShortcutsUtils point of view.

But the thing is that this exclude a certain number of keys that don't need to be in the keyCodesList, and that have a name of length greater than 1.
To my eyes this length check is unnecessary.

**Comment by surapunoyousei** [comment]
The keycode output by JavaScript is different from the one used by Mozilla, so it is implemented this way
