### ISSUE TITLE
[Bug] Arrow Buttons for "Go back/forward one page" non-functional

### ISSUE THREAD

**Issue by C0deNuclear** [Floorp-Projects/Floorp#715]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

This bug is being reported from firedragon-next at the behest of one of Firedragon's maintainers. In short, the tab history navigation buttons (including keyboard shortcuts) are no longer functional as of 11.8.0. The maintainer in question stated that the culprit is likely these three settings no longer working properly:

`defaultPref("userChrome.autohide.page_action", true);
defaultPref("userChrome.autohide.forward_button", true);
defaultPref("userChrome.autohide.back_button", true);`

### To Reproduce

1. Be using version 11.8.0
2. Open new tab
3. Search anything
4. Click another link in same tab
5. Attempt tab history navigation using arrow buttons or keyboard shortcuts.

### Expected behavior

Functional tab history navigation buttons/shortcuts.

### OS Info

Garuda Linux KDE Dr460nized Edition

### Floorp Version

11.8.0

**Comment by surapunoyousei** [comment]
ah,,,,,,,,,,,,,,,,,


ok.. Check it

**Comment by surapunoyousei** [comment]
So… Could you provide a video, to reproduce this issue

**Comment by C0deNuclear** [comment]
[2024-01-17 22-34-48.webm](https://github.com/Floorp-Projects/Floorp/assets/141107922/4d702fd3-b4f9-4037-88a1-1479fb13e64e)

Sorry if the video is a little choppy, I had to set up recording software from scratch. Anyways, in the video you can see that the arrows stay greyed out, usually they become highlighted once going to a new page in a tab and one can then navigate the tab history. 

However, I have also very recently been informed by the maintainer I mentioned before that this bug might have something to do with workspaces and might in fact be something on their end rather than yours. If this is the case I must apologize for taking up your time.

**Comment by surapunoyousei** [comment]
I cannot reproduce the bug... Odd

**Comment by surapunoyousei** [comment]
If you have Windows OS, please try this on there?

This is big issue. I want to reproduce it

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/assets/73892113/65cecc24-1578-4923-baa2-528b0937cb57

Maybe no issue.

**Comment by jst-r** [comment]
I tried the reproduction on Windows 10, Floorp version 11.8.1, works fine for me. Behavior is the same as surapunoyousei's video.

**Comment by surapunoyousei** [comment]
> I tried the reproduction on Windows 10, Floorp version 11.8.1, works fine for me. Behavior is the same as surapunoyousei's video.

Thanks

**Comment by C0deNuclear** [comment]
Sorry for the late response, I have been away due to some personal matters. As far as I can tell, the maintainer that first sent me here to make this issue has since resolved the problem on their end, so I am going to close this issue. Thank you for spending time looking into this issue anyways.
