### ISSUE TITLE
[Bug] Unable to log into Twtich.tv

### ISSUE THREAD

**Issue by aggonzo326** [Floorp-Projects/Floorp#716]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Given the following warning when attempting to log in via Floorp "[y]our browser is not currently supported. Please use a [recommended browser](https://help.twitch.tv/s/article/supported-browsers) or learn more [here](https://help.twitch.tv/s/article/supported-browsers)." This issue does not occur in other browsers such as Chrome and Firefox (non-beta).

### To Reproduce

1.  Go to Twitch.tv
2.  Click Log In on the top right corner
3.  Input your calid credentials
4.  Given error "Your browser is not currently supported. Please use a [recommended browser](https://help.twitch.tv/s/article/supported-browsers) or learn more [here](https://help.twitch.tv/s/article/supported-browsers)."

### Expected behavior

I expected to be able to log in without issue, and view my profile and other items that can be seen when logged in.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/6976539/d08a583d-5d11-4d74-8641-965ef15ac12e)

### OS Info

Windows 11 22635

### Floorp Version

11.8.1

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/463cc03a-a4fc-408e-a7e0-f12f9f693eac)

I can login on Private Window & Normal window

**Comment by aggonzo326** [comment]
You are also on version 11.8.1? You logged out, and then logged back in without issue?

I should also mentioned that I tried to log in unsuccessfully on Chrome User Agent Spoofer and Default User Agent.

**Comment by surapunoyousei** [comment]
Provide a video please wait.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/assets/73892113/6c6dfd5b-9308-4e05-8f98-d145d8a4a13f

**Comment by aggonzo326** [comment]
So interesting. I was able to figure it out though. Thank you for your help!

It was because I had uBlock Origin enabled. Not sure why that's an issue for me when you have it enabled and are able to log in. I wonder if it's a region thing. Closing issue.

**Comment by surapunoyousei** [comment]
#Pin this issue because, not little of the users get occurred...

**Comment by Thorazin** [comment]
Unable to log in to Twitch no matter what I try. I disabled ALL extensions, I cleared cache and cookies, nothing. Firefox works fine.
Firefox version 122
Floorp Version  11.8.1

**Comment by AlexPewMaster** [comment]
If you have **Enable strong protection against fingerprinting** enabled, Twitch will say that your browser is not supported. This is because of **privacy.resistFingerprinting** being enabled in **about:config** by this setting:

![image](https://github.com/Floorp-Projects/Floorp/assets/68469103/b17da2b0-c4df-4727-9569-ab6da121e8d9)

You can temporarily disable that setting and then log into your Twitch account. After that, you can turn it back on.

**Comment by Thorazin** [comment]
That did it, thank you.

**Comment by NakedTrashPanda** [comment]
> If you have **Enable strong protection against fingerprinting** enabled, Twitch will say that your browser is not supported. This is because of **privacy.resistFingerprinting** being enabled in **about:config** by this setting:
> 
> ![image](https://private-user-images.githubusercontent.com/68469103/298393292-b17da2b0-c4df-4727-9569-ab6da121e8d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTQ1MDcsIm5iZiI6MTcwNzM1NDIwNywicGF0aCI6Ii82ODQ2OTEwMy8yOTgzOTMyOTItYjE3ZGEyYjAtYzRkZi00NzI3LTk1NjktYWI2ZGExMjFlOGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAxMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjQ2MjMyZDFkZDRlYWM4NTYzYzBiODJhNDgyNTQzMDg1ZjkwYjk1MmJjZGQ2MGZmMzgxNzdlNDY4ODFiOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GQ9qxGvi9zNUprTvUTSXeSh5x7mqvfy1XOwy6ehx1Kc)
> 
> You can temporarily disable that setting and then log into your Twitch account. After that, you can turn it back on.

Didn't work for me. I disabled everything related to privacy and all extensions but kept getting the error. Had to import my cookie from Firefox to login.

**Comment by ALEZ-DEV** [comment]
@NakedTrashPanda I had the same issue, but that was just because the spoof mode was activated

Use the default one
![image](https://github.com/Floorp-Projects/Floorp/assets/38623465/d7e8df61-78ae-4eba-9334-f6e076de912e)

**Comment by NakedTrashPanda** [comment]
@ALEZ-DEV I made sure it was set to default, still didn't work then. 
It does seem to be working now for some reason. I haven't changed anything so I don't know what's up with the issue. 

Possible it was just Twitch having issues in that moment.

**Comment by blindmodz** [comment]
5/23 and still is a problem. Tried with `privacy.resistFingerprinting false` and without user-agent. Tried with a new profile on private and still cant log in.

**Comment by SamuelCHIF** [comment]
Hey, just tried everything mentioned above, it still doesn't work. but in private mode it does work perfectly fine. Any Ideas?

    - strong protection against fingerprinting --> disabled
    - User Agent --> default
    - Extensions --> all disabled
    - Cookies and Site Data --> cleared all from Twitch

![image](https://github.com/Floorp-Projects/Floorp/assets/89636490/37178025-c735-4da5-8590-a9d08206abc2)
![image](https://github.com/Floorp-Projects/Floorp/assets/89636490/e6812947-81b9-4bc3-bbb3-7c575c817ed5)
![image](https://github.com/Floorp-Projects/Floorp/assets/89636490/455757c0-ce5d-4df5-8507-85ce441df386)
![image](https://github.com/Floorp-Projects/Floorp/assets/89636490/c4a9e47b-62b9-4683-9929-31483688fb25)
