### ISSUE TITLE
[Bug] Upgrade PDF.js to avoid CeTZ glitches 

### ISSUE THREAD

**Issue by ThatOneCalculator** [Floorp-Projects/Floorp#717]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

CeTZ graphs have a graphical issue on older versions of PDF.js.

### To Reproduce

1. View PDF rendered with Typst and CeTZ

### Expected behavior

The latest verison of PDF.js (used in regular Firefox) fixes this issue.

### Screenshots

Floorp 11.8.1:

![image](https://github.com/Floorp-Projects/Floorp/assets/44733677/cc9b9578-8e5d-4470-a554-22bf8751c262)

Firefox 121.0: 

![image](https://github.com/Floorp-Projects/Floorp/assets/44733677/f154c2db-124b-4272-88f4-5c6df509d6c6)

### OS Info

Arch Linux x86_64

### Floorp Version

11.8.1

**Comment by surapunoyousei** [comment]
Floorp cannot fix this issue because it is ESR-based.

**Comment by ThatOneCalculator** [comment]
Will there ever be a verison of Floorp that's based on the current Firefox version instead of ESR?

**Comment by surapunoyousei** [comment]
Currently, the Main maintainer is only one person. It's me.

So, There are lots of issues... Users requests are still got more & more. But, Coder writer is not got more.
