### ISSUE TITLE
[Bug] Unable to open PWA without a Floorp window opening

### ISSUE THREAD

**Issue by aggonzo326** [Floorp-Projects/Floorp#718]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I click on my PWA that's pinned to my taskbar, an accompanying Floorp window also opens. This behaviour does not happen when opening that same PWA that is installed via Chrome.

### To Reproduce

1. Click on pinned PWA in taskbar
2. PWA opens
3. Floorp window also opens
4. Additionally, a second top/menu bar is added to the Floorp window
4a. The second top/menu bar goes away if the Floorp window is made a full window or dragged to one half of the screen 

### Expected behavior

1. Click on pinned PWA in taskbar
2. PWA opens
3. Floorp window does NOT open and PWA is the only open window
3a. No second top/menu bar is added to the Floorp window

### Screenshots

PRIMARY ISSUE
Floorp window opens when PWA opened:
![image](https://github.com/Floorp-Projects/Floorp/assets/6976539/6634c0e9-6681-48eb-acec-44dec6e2ca82)

SECONDARY ISSUE
Normal top/menu bar:
![image](https://github.com/Floorp-Projects/Floorp/assets/6976539/c01ba1e3-0570-453e-a8e7-8be23a8c071e)

Abnormal top/menu bar when a PWA is opened:
![image](https://github.com/Floorp-Projects/Floorp/assets/6976539/73205250-29a5-454b-bbfe-ad7b15d482db)

### OS Info

Windows 11 22635

### Floorp Version

11.8.1

### Additional context

N/A

**Comment by surapunoyousei** [comment]
Could you separate issues?

**Comment by surapunoyousei** [comment]
But, the First issue is not issue. Expected

**Comment by aggonzo326** [comment]
Floorp main window opening when opening a PWA is planned behavior? Is the roadmap for a fix or is that an upstream issue?

If yes to both, I will close out and reopen with the secondary as a new issue. Thank you.

**Comment by surapunoyousei** [comment]
No roadmap to fix it due to not a bug.

**Comment by aggonzo326** [comment]
Closing out per maintainer's comment.
