### ISSUE TITLE
[Bug] A second top/menu bar is added to the Floorp window when a PWA is opened first

### ISSUE THREAD

**Issue by aggonzo326** [Floorp-Projects/Floorp#719]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I click on my PWA that's pinned to my taskbar, an accompanying Floorp window opens, and that Floorp main window displays a second top/menu bar.

### To Reproduce

1. Click on pinned PWA in taskbar
2. PWA opens
3. Floorp window then opens
4. A second top/menu bar is added to the Floorp window
4a. The second top/menu bar goes away if the Floorp window is made a full window or dragged to one half of the screen

### Expected behavior

The main browser window of Floorp should only have one top bar.

### Screenshots

Normal top/menu bar:
![image](https://github.com/Floorp-Projects/Floorp/assets/6976539/c01ba1e3-0570-453e-a8e7-8be23a8c071e)

Abnormal top/menu bar when a PWA is opened before opening Floorp:
![image](https://github.com/Floorp-Projects/Floorp/assets/6976539/73205250-29a5-454b-bbfe-ad7b15d482db)

### OS Info

Windows 11 22635

### Floorp Version

11.8.1

### Additional context

N/A

**Comment by surapunoyousei** [comment]
Hmmm... 

So.. I find another bug. Maybe relate to this issue.

**Comment by surapunoyousei** [comment]
The problem with the main window has been resolved by adding a delay. This bug would have also been fixed.
