### ISSUE TITLE
New workspaces weird behavior

### ISSUE THREAD

**Issue by Lovasz-Akos** [Floorp-Projects/Floorp#725]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The new workspaces behave stragely. 
- When switching workspaces random tabs get moved to the new workspace
- Right clicking a tab has no option to move it to another workspace
- Workspaces can't be reordered in sidebar

### To Reproduce

With 2 workspaces created, open a few tabs in one. Then switch workspaces to the other, and some tabs carry over and get removed from the first workspace. This may be related to sleeping tabs.

### Expected behavior

Each tab should stay in the workspace it was created in

Also the tabs having no context menu to move them to another workspace

### OS Info

Windows 11 Pro 23H2

### Floorp Version

Version 11.8.0 (64-bit) | Firefox: 115.7.0

**Comment by Lovasz-Akos** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/55391231/ffd26d78-0038-45b9-90df-26414679b41a)
here's a screenshot of a tab's right click menu, no option to move the tab to another workspace

**Comment by Lovasz-Akos** [comment]
Move tab only has ordering options
![image](https://github.com/Floorp-Projects/Floorp/assets/55391231/5b611e4e-9d28-44ba-a100-fe903fe992e1)

**Comment by Lovasz-Akos** [comment]
Move to another workspace appeared after 2 more restarts, I'll close this if I can't reproduce the tabs moving workspaces again

**Comment by Lovasz-Akos** [comment]
Drag and drop reordering of workspaces in the sidebar still dont work
![image](https://github.com/Floorp-Projects/Floorp/assets/55391231/a8637f1d-b914-426c-918b-bfc840259633)

**Comment by CutterKnife** [comment]
Please update to v11.8.1.
I think the inability to reorder Workspaces was the same specification as in previous versions.

**Comment by Lovasz-Akos** [comment]
updated to Version 11.8.1 (64-bit), I no longer have the tabs moving workspaces bug, but the sidebar icons still can't be reordered, but that might be a feature request if it was not possible before
