### ISSUE TITLE
[Bug] Show the Bookmarks Toolbar at the bottom of Floorp is broken

### ISSUE THREAD

**Issue by wat0114** [Floorp-Projects/Floorp#726]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Settings->Design->Bookmarks Toolbar, enable switch: Show the Bookmarks Toolbar at the bottom of Floorp

Results in Bookmarks Toolbar showing at bottom of Floorp only briefly. Once a new tab is selected, the toolbar disappears and will not show again. 

### To Reproduce

1. Go to: Settings, Design, Bookmarks Toolbar
2. Turn switch "on" to enable option
3. Bookmarks Toolbar will appear as expected at the bottom of Floorp
4. click on any open tab, and the Bookmarks Toolbar disappears.

### Expected behavior

The Bookmarks Tool bar should show at the bottom of Floorp, and the only time it should not appear is when the Taskbar, set to "Autohide", covers it. 

### OS Info

Linux MX-23, kernel v6.1.0-13-amd64 (64-bit)

### Floorp Version

11.8.1 (64 bit)

**Comment by surapunoyousei** [comment]
I'll fix it next week. Currently i have a sick now.

**Comment by surapunoyousei** [comment]
Fixed. Patch will arrive at next week
