### ISSUE TITLE
[Bug]  Collapsed Vertical tab bar has transparent background when expanded

### ISSUE THREAD

**Issue by AnushM55** [Floorp-Projects/Floorp#727]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Vertical tab set to collapse and expand when hovered ,does not display its background properly.

### To Reproduce

1, Go to settings -> Design -> Tab Bar Style  
2. Select 'vertical tab bar (experimental)' 
3. Turn on 'collapse vertical tab bar'.
4. Hover over the vertical tabs on a new page

### Expected behavior

Expanded tabs should have the same background as the browser theme

### Screenshots

![FloorpTab](https://github.com/Floorp-Projects/Floorp/assets/143617212/41ffa35b-16fc-4c97-9024-132cd3a203ec)

### OS Info

OS: EndeavourOS Linux x86_64 [Arch based distro]

### Floorp Version

11.8.1 (64 bit)

### Additional context

setting the following in inspector tab of chrome://browser/content/browser.xhtml , changes its background to black  (if that helps)
![image](https://github.com/Floorp-Projects/Floorp/assets/143617212/b2dfc1e8-7a32-4618-9f15-6cdbd3b6d22a)

**Comment by surapunoyousei** [comment]
Deplicate
