### ISSUE TITLE
Open links in the sidebar instead of the main browser window 

### ISSUE THREAD

**Issue by regularenthropy** [Floorp-Projects/Floorp#73]
## Describe the solution you'd like
Currently, the sidebar is opening links in the main browser window. I think, it would be better to open them inside the sidebar.

**Comment by surapunoyousei** [comment]
` target="_blank`

No change may be required as this depends on what is specified

**Comment by regularenthropy** [comment]
> ` target="_blank`
> 
> No change may be required as this depends on what is specified
Oh, yeah. It works for Google search, but it doesn't work for Frea Search (the default one).
