### ISSUE TITLE
[Bug] Bookmarks toolbar hides when switching workspaces

### ISSUE THREAD

**Issue by Scridgeon** [Floorp-Projects/Floorp#732]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The Bookmarks toolbar autohides when "Show the Bookmarks Toolbar at the bottom of Floorp" is enabled and you change workspaces.

### To Reproduce

1. Enable "Show the Bookmarks Toolbar at the bottom of Floorp" in the settings.
2. Enable Show Bookmarks Toolbar
3. Change workspaces

### Expected behavior

The Toolbar should remain visible when changing workspaces. This behavior works as expected when the Bookmarks Toolbar is at the top of the screen.

### OS Info

Linux Flatpak

### Floorp Version

11.8.0_2023-01-16

**Comment by surapunoyousei** [comment]
Duplicate. 

Please be sure to check other issues maybe relate your problem before commenting. 

It takes time away from the developer that for create Floorp
