### ISSUE TITLE
[Bug] Weird behaviour when deleting any but rightmost tab when many tabs open

### ISSUE THREAD

**Issue by alecames** [Floorp-Projects/Floorp#735]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When you have enough tabs to fill the width of the tab bar, the first time you delete any tab except the rightmost tab (with middle click or X button) causes the tabs in tab row to jump/shift for a moment. Deleting more tabs after this (or the rightmost tab) while still hovered over tab row, does not exhibit this behaviour. 

### To Reproduce

1. Have ~10+ tabs open
2. Delete any tab except the rightmost tab (middle click/close button)

### Expected behavior

The tabs in the tab row should not shift when deleting while hovered over tab row.

It should behave the same way as it does in Proton UI mode.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/18179415/029fe387-de39-4f1f-88fe-6ccfc0f077e6

### OS Info

Windows 11 23H2

### Floorp Version

11.8.1

### Additional context

- Occurs in every UI mode except Proton UI
- No customization options in Lepton UI affect this behaviour

**Comment by surapunoyousei** [comment]
This appears to be expected behavior.
