### ISSUE TITLE
[Bug] Workspaces not working after last update

### ISSUE THREAD

**Issue by HassanJbara** [Floorp-Projects/Floorp#737]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Title. I don't see the workspaces in the sidebar, and even the options menu Move to Another Workspace does not display any workspace. I tried turning workspaces on and off and it didn't change anything.

### To Reproduce

I don't know, just updated and this happened.

### Expected behavior

Workspaces working.

### OS Info

Windows 11 Home 22H2

### Floorp Version

11.8.1

**Comment by surapunoyousei** [comment]
Did you read release note?

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/ce8e9321-b5a2-4791-a78a-bb0b5ee2dd49)
