### ISSUE TITLE
Workspaces are gone after update to 11.8.1

### ISSUE THREAD

**Issue by msmafra** [Floorp-Projects/Floorp#738]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

After the update, I use the flatpak, to 11.8.1 my workspaces are gone and I cant create one anymore.
As I not using as my main browser yet, I disabled Workspaces restarted; re-enabled; restarted again and still can't create Workspaces.

### To Reproduce

1, Use 11.7.1 and create your workspaces
2. Use the workspaces
3. Update to 11.8.1

### Expected behavior

After the update to have my previous Workspaces and be able to create new ones.

### Screenshots

![Captura de tela de 2024-01-19 10-58-04](https://github.com/Floorp-Projects/Floorp/assets/1005457/d5141dff-c693-4429-849d-4670c7c35d69)
![Captura de tela de 2024-01-19 10-50-29](https://github.com/Floorp-Projects/Floorp/assets/1005457/1528bf17-4c75-4ef3-8e9d-c9003afe4c71)
[Gravação de tela de 2024-01-19 10-52-43.webm](https://github.com/Floorp-Projects/Floorp/assets/1005457/f92d72ef-5351-4bac-8b86-0363e91a310c)

### OS Info

Fedora Workstation 39

### Floorp Version

11.8.1

**Comment by CutterKnife** [comment]
Please read the release notes.

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/e0a86ba0-8bef-42cb-b589-da1637bde0d8)

**Comment by msmafra** [comment]
> Please read the [release notes](https://blog.ablaze.one/3865/2024-01-17/).

That should be a warning after the update inside the browser.
