### ISSUE TITLE
[Bug] Floorp 11.8.1 release downgrades itself

### ISSUE THREAD

**Issue by da3dsoul1** [Floorp-Projects/Floorp#742]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When launching Floorp portable 11.8.1 it's updating itself to 11.7.1 on the next browser launch

### To Reproduce

1. Download and launch floorp portabble 11.8.1
2. Restart the browser

### Expected behavior

It shouldn't downgrade itself from 11.8.1 to 11.7.1

### OS Info

Windows 11 21H2

### Floorp Version

11.8.1

**Comment by surapunoyousei** [comment]
Fixed

**Comment by da3dsoul1** [comment]
Thank you very much!
