### ISSUE TITLE
[Bug] A small bug with floorp's lepton theme. The open link icon is missing.

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#745]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The lepton theme in floorp is missing an icon in the context menu, specifically the one to open link

### To Reproduce

1, Search for a link on any page.
2. Highlight the link and right click to open the context menu.

### Expected behavior

When you open the context menu the open link icon appears

### Screenshots

On the left applied lepton theme by black7375 version 8.5.1
On the right the default lepton theme from Floorp
![floorp-img1](https://github.com/Floorp-Projects/Floorp/assets/86812371/99425db4-5f71-4f5a-a9a8-6e7abbbf551e)

### OS Info

Windows 10 22H2

### Floorp Version

11.8.1

### Additional context

Until version 11.6 of floorp the icon appeared but since version 11.7 onwards the icon has disappeared.

**Comment by surapunoyousei** [comment]
SO... Please show English style context menu.

**Comment by kaos-55** [comment]
Sure, here it is.
On the left default lepton theme from Floorp.
On the right applied lepton theme by black7375 version 8.5.1.

![floorp-img](https://github.com/Floorp-Projects/Floorp/assets/86812371/22cbbbc1-91e1-4dc8-ba0b-03865d8bdfae)

**Comment by surapunoyousei** [comment]
What you selected?

**Comment by kaos-55** [comment]
This in google search.

![floorp-img1](https://github.com/Floorp-Projects/Floorp/assets/86812371/494d98e4-f162-41c6-a3a0-a16523d133d2)

**Comment by surapunoyousei** [comment]
OK

**Comment by surapunoyousei** [comment]
Fixed
