### ISSUE TITLE
[Bug] Workspaces in the sidebar disappear when the workspaces button in the tab bar is removed.

### ISSUE THREAD

**Issue by kaos-55** [Floorp-Projects/Floorp#746]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When you enable the option to manage workspaces in the sidebar and remove the workspaces button from the tab bar, the workspaces in the sidebar also disappear.

### To Reproduce

1. Activate the workspaces.
2. Place the workspaces button on the tab bar.
3. Activate the option to manage workspaces in the sidebar and restart the browser.
4. Remove the workspaces button from the tab bar and restart the browser.
5. The workspaces in the sidebar also disappear.

### Expected behavior

When you remove the workspaces button, the workspaces in the sidebar remain

### OS Info

Windows 10 22H2

### Floorp Version

11.8.1

### Additional context

When you put the workspaces button back on the tab bar and restart the browser, the workspaces in the sidebar appear again.
I don't know if this is the developer's desired behavior of having the workspaces button and workspaces in the sidebar at the same time, when I think it is better to have only one of the two instead of both at the same time.

**Comment by surapunoyousei** [comment]
I can't speak specifically now, but this is expected behavior.

I will know the reason in the future, but absolutely cannot speak to the reason now.

**Comment by surapunoyousei** [comment]
I will give you a few hints.

Floorp's new beginning is scheduled for August of this year.
