### ISSUE TITLE
[Bug] Big bug with Windows Floorp video playback

### ISSUE THREAD

**Issue by jarrard** [Floorp-Projects/Floorp#750]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Will frequently whitebox flicker the browser window, can stop the video playing with whitebox in place of video/site. 
White Window can remain but audio keeps playing in background.
Can take a minute or so of clicking around before it triggers. 
Can affect Window-1 as well as Window-2
Can affect non video playback websites.

### To Reproduce

1: Open two windows
2: Window-1 open up amazon (example only)
3: Window-2 open up a youtube video and start playing it. (or twitch)
4: Start clicking through different pages on amazon website. (window 1)
5: Keep clicking through amazon pages, toggle back and forward to window-1/2 

### Expected behavior

Not flicker or produce whitebox browser window bug. 

### Screenshots

no at moment

### OS Info

Windows 11 E 22621

### Floorp Version

11.8.1

### Additional context

This is really a deal breaker for this browser. 
Issue does NOT happen with firefox but does with a clean floorp

This imo is what I call a CRITICAL BUG.  Will it be ignored by the floorp team? probably.

**Comment by creeper-0910** [comment]
Hmmm, I basically work in two windows and have never had that symptom happen...

**Comment by jarrard** [comment]
By work, what content are you loading.  Because it could be a issue with heavy script and/or video content playing only.

**Comment by surapunoyousei** [comment]
This is the first time a bug this big has been reported, so this must be a problem with your environment.

**Comment by surapunoyousei** [comment]
This is the first time a bug this big has been reported, so this must be a problem with your environment.

**Comment by surapunoyousei** [comment]
Also, Floorp has not changed the code related to video playback.

**Comment by jarrard** [comment]
I don't see how it could be my environment that is issue since its Windows 11, and it was working fine.  
Well I guess it was problem a windows update that broke it somehow.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/464

Ahh. I remember this issue.

**Comment by jarrard** [comment]
Thanks for that. Hopefully this does the trick.
