### ISSUE TITLE
[Bug] Home Assistant UI is broken

### ISSUE THREAD

**Issue by matti-kz** [Floorp-Projects/Floorp#752]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Home Assistant UI is broken, seems like CSS issue, interacting with the website in some way usually fixes it (changing a tab back and forth from the hamburger menu). Tried without any extensions and in Troubleshooting mode on Windows 11 & MacOS - same issue.

### To Reproduce

1. Go to https://demo.home-assistant.io/#/lovelace/0

### Expected behavior

Should work, is not broken on stock Firefox.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/8735263/dd9c98bc-f8a9-4531-8ac3-2c0bda53bc12)

### OS Info

Windows 11, MacOS 14.2.1

### Floorp Version

11.8.1

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/29acece3-5c80-4ed7-a350-ac540298c899)
？

**Comment by matti-kz** [comment]
Hmm interesting, in this case I will try to find out what combination of settings causes this on my side.

**Comment by surapunoyousei** [comment]
Ahhh. Ok Floorp is ESR based. Firefox has "has:()" selector

**Comment by surapunoyousei** [comment]
SO... First of visiting website show broken visible.

**Comment by xairoo** [comment]
Still exists in v11.12.2.
When I load the page the content is placed in the vertical center.
Changing tabs in Home Assistant fixes that.
Reloading the page sometimes (rarely) shows the content nearly perfect, but a part of the content is outside of the view.

**Comment by GameAreaCZ** [comment]
Yep, still exists. What will change with v12 to fix this issue?
