### ISSUE TITLE
[Bug] The issue of the scroll bar being unscrollable persists in the new update

### ISSUE THREAD

**Issue by Plexprofile** [Floorp-Projects/Floorp#753]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Tried reinstalling the browser, hoping this will solve the issue, unfortunately it did not work 
![floorp 20240121_200317](https://github.com/Floorp-Projects/Floorp/assets/139643082/5a2b6bbd-baeb-41e9-85c4-5da294148e79)

### To Reproduce

use scroll bar in the new update

### Expected behavior

the scroll bar should work 

### Screenshots

this is my tab settings 
<img width="637" alt="image_36" src="https://github.com/Floorp-Projects/Floorp/assets/139643082/e284bfde-5d1b-4d6c-a63f-b7646198f04a">

### OS Info

Win10 21h2

### Floorp Version

Version 11.8.1 (64-bit) | Firefox: 115.7.0

**Comment by surapunoyousei** [comment]
Deplicate
