### ISSUE TITLE
[Bug] Error when starting the application

### ISSUE THREAD

**Issue by ex1side** [Floorp-Projects/Floorp#755]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I have the following errors when launching the browser
"The instruction at 0x00007FF971404AA0 referenced memory at 0x0000000000001240. The memory could not be read."
If I click OK, the browser will launch, If I click "Cancel", another error will appear 
This occurs at every startup, tested on versions 11.8.1, 11.8.0

### To Reproduce

1. Click on Floorp icon
2. Wait

### Expected behavior

Launching the browser without error windows

### Screenshots

![NVIDIA_Share_ADpSgMFqlw](https://github.com/Floorp-Projects/Floorp/assets/78278069/4576942c-0f36-444d-b2a9-374dcafff444)
the second error occurs if I click "Cancel"
![floorp_4PXtOgdeb6](https://github.com/Floorp-Projects/Floorp/assets/78278069/f7fabaee-e115-4330-a6b3-8e775cb19cc8)

### OS Info

Windows 11 23H2

### Floorp Version

11.8.1

### Additional context

Also, when installing the latest version, the icon in the taskbar is attached without a logo (perhaps a problem with my system, but in the previous version this is not observed)

**Comment by surapunoyousei** [comment]
Tell me about your machine

**Comment by ex1side** [comment]
> Tell me about your machine

Ryzen 5 5600H, 8 gb ram (paging file(swap) is enabled), GTX1650, Windows 11 23H2 Stable channel

**Comment by surapunoyousei** [comment]
Memory corruption appears to have occurred.

This is usually a device or Windows problem.

**Comment by ex1side** [comment]
Thank you for the answer
