### ISSUE TITLE
[Bug] Workpaces resetting when rebooting Floorp.

### ISSUE THREAD

**Issue by ktlknss** [Floorp-Projects/Floorp#760]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

If I set up some workspaces, after closing & opening Floorp, they reset.

### To Reproduce

1. Enable workspaces and add the workspace thing to the toolbar
2. Create some workspaces (and customise them).
3. Close Floorp
4. Open Floorp again
5. The workspaces are reset to what they used to be

### Expected behavior

What I would like to happen is that the workspaces keep their customisation.

### OS Info

Windows 11 Home - 23H2

### Floorp Version

Version 11.8.1 (64-bit) | Firefox: 115.7.0

**Comment by surapunoyousei** [comment]
Please provide a video

**Comment by win8linux** [comment]
Recently updated to 11.8.1 and all my previously set workspaces are gone as well.

**Comment by surapunoyousei** [comment]
If you upgrade from v11.7.0 or past versions, It maybe happen. I cannot solve this because I could not test against all environments or the old workspace was not well implemented.

**Comment by win8linux** [comment]
Re-enabling workspaces on 11.8.1 also doesn't show the workspace switcher and manager; the feature is outright not working at all at least on my end.

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/7f4be00b-f030-48ee-b6e2-6284d7e24770)

You should try it. Workspaces is re-designed

**Comment by win8linux** [comment]
Oh apologies, the update page didn't open on startup as expected. Perhaps as a UI suggestion, add that notice in the settings?

**Comment by surapunoyousei** [comment]
I was not sure whether to notify them of this, but did not implement it because the average user does not use deprecated features. Now I regret it.

**Comment by win8linux** [comment]
Please re-open this issue, as upon restarting Floorp the new workspaces have disappearred along with the tabs inside them!

**Comment by surapunoyousei** [comment]
I was the first to say **please provide a video about it**.

**Comment by win8linux** [comment]
Unfortunately my network connection keeps cutting out while uploading to GitHub, so here's a Streamable link (expires in two days):
https://streamable.com/ibq6ua

**Comment by surapunoyousei** [comment]
OK. You should put button to toolbar. otherwise, Floorp workspaces is not enabled

**Comment by win8linux** [comment]
Perhaps it may be a good idea to tell users this in the workspace settings as well? It's reasonable for someone to assume that turning on the setting to have the workspace manager in the sidebar means that they can remove the workspace button, since in the previous implementation its counterpart was removed upon enabling that setting.

**Comment by surapunoyousei** [comment]
Yeah ill do that
