### ISSUE TITLE
[Bug] Unable to use streaming platforms like netflix or hotstar

### ISSUE THREAD

**Issue by LawrenceVeigas** [Floorp-Projects/Floorp#761]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Whenever I visit streaming websites like netflix or disney hotstar. I get a pop-up on the top right saying `Floop is installing components needed to play audo or video on this page. Please try again later.`

However, even after letting the browser sit for hours, restarting the browser, restarting Windows. The problem still persists. 

### To Reproduce

1. Open Floorp
2. Visit https://www.netflix.com or https://www.hotstar.com
3. Play any title/video on the website

### Expected behavior

Play the video on the website

### Screenshots

![Screenshot 2024-01-22 222731](https://github.com/Floorp-Projects/Floorp/assets/26686946/e7b7d47c-0c93-4dda-9e95-a2477d1670ee)
![Screenshot 2024-01-22 222210](https://github.com/Floorp-Projects/Floorp/assets/26686946/941c7c23-2c86-4f38-8e91-13a35f5b0cfb)

### OS Info

Windows 11 Pro 21H2 OS build 22000.2538

### Floorp Version

Version 11.8.1 (64-bit) | Firefox: 115.7.0

**Comment by LawrenceVeigas** [comment]
Updated Floorp to Version 11.8.2 (64-bit) | Firefox: 115.7.0. However, issue still persists.

**Comment by creeper-0910** [comment]
This is a DRM issue.
It will be difficult to solve because it costs a lot of money to purchase a DRM license...

**Comment by 32bitx64bit** [comment]
Hey uh, I'm a bit late here. But if you're on arch linux this problem does not exist.
*Might not exist on other distros as well*

**Comment by TheChilledBuffalo** [comment]
> Hey uh, I'm a bit late here. But if you're on arch linux this problem does not exist.
> *Might not exist on other distros as well*
> 

This issue does not occur on Linux. Windows and MacOS have strict DRM restrictions and that's what's causing this issue.

**Comment by melroy89** [comment]
Again read: https://docs.floorp.app/docs/issue-tracker/drm#why-floorp-doesnt-have-a-license

**Comment by djsiropchik** [comment]
> Again read: https://docs.floorp.app/docs/issue-tracker/drm#why-floorp-doesnt-have-a-license

Yeah. I read it, but why problem only on MacOs. It's a little strange
