### ISSUE TITLE
Home Assistant dashboard is compressed

### ISSUE THREAD

**Issue by Lovasz-Akos** [Floorp-Projects/Floorp#762]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When opening default Home Assistant dashboard, the layout is compressed like it's trying to fit into a much smaller screen than it is being displayed on. This can only be fixed by navigating to another page and then back to the dashboard within Home Assistant. If I reload the page, the same compression happens.

![image](https://github.com/Floorp-Projects/Floorp/assets/55391231/00761d9b-9d94-4db1-b79b-09c9ffc52b9e)

### To Reproduce

Open HA Dashboard

### Expected behavior

The normal layout should look something like this
![image](https://github.com/Floorp-Projects/Floorp/assets/55391231/beec8226-bfdb-4b5a-9bec-cf9a8990dbac)

### OS Info

Windows 11 Home 22H2

### Floorp Version

Version 11.8.1 (64-bit) I Firefox: 115.7.0

**Comment by Lovasz-Akos** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/55391231/63628d20-b0c9-4642-ae6c-bd8e7355f77d)
![image](https://github.com/Floorp-Projects/Floorp/assets/55391231/b2bbabaf-207c-4d0f-953e-066c646e1cc3)

seems like the flex-container becomes 0 width

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/issues/752
It seems to be similar to this issue.

**Comment by Lovasz-Akos** [comment]
ah I was about to upload a video showing it but yes, it's the same thing, thank you @creeper-0910 I'll close this and wait :)
