### ISSUE TITLE
[Bug] Collapsed vertical tab bar only expands the text

### ISSUE THREAD

**Issue by Svahnen** [Floorp-Projects/Floorp#767]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The vertical tab bar only expands the text and not the whole sidebar from collapsed mode. This means that the text is very hard to read since it is drawn on top of the webpage directly, without the sidebar expanding behind the text.

### To Reproduce

1. Enable vertical tab bar.
2. Enable Collapsing vertical tab bar.
3. Hover over the sidebar where the tabs are shown.

### Expected behavior

The whole tab bar should expand so text can be read.

### Screenshots

[Screencast from 01-23-2024 11:42:31 AM.webm](https://github.com/Floorp-Projects/Floorp/assets/32038561/d965dc20-8879-4c0a-9e14-fc4ba1675801)

### OS Info

PoP_OS 22.04 (64bit)

### Floorp Version

11.8.2

### Additional context

Window manager: Gnome (64bit)

**Comment by LeonardoMantovani** [comment]
Idk why I can't see the video, but from your description it seems you're experiencing the same issue I was talking about in issue #704
If so, they fixed it few hours ago and I guess the fix will be shipped in the next release
