### ISSUE TITLE
[Bug] New window doesn't show already created workspaces

### ISSUE THREAD

**Issue by avinal** [Floorp-Projects/Floorp#768]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

As per the release note here: https://github.com/Floorp-Projects/Floorp/releases/tag/v11.8.1, workspaces work across multiple windows. I would expect that my already created workspaces are available in all windows, or the ability to assign a particular workspace to a window.

But if I open a new window it only shows a new workspace.

### To Reproduce

1. Create few workspaces
2. Create a new window
3. See the workspaces in the new window

### Expected behavior

Either already created workspaces should be available in all windows or/and should be able to assign a window to a workspace. 

### Screenshots

![2024-01-23T16:36:26,004696904+05:30](https://github.com/Floorp-Projects/Floorp/assets/74113200/5ec1ef8b-450f-483c-acd4-d47e7a39a57f)

### OS Info

Fedora 39 Sway

### Floorp Version

11.8.2

**Comment by surapunoyousei** [comment]
Expected

**Comment by avinal** [comment]
Thanks for the clarification

**Comment by jficz** [comment]
> Expected

care to elaborate? I just switched to Floorp but this design decision makes me seriously consider switching back to my previous browser

**Comment by CutterKnife** [comment]
> > Expected
> 
> care to elaborate? I just switched to Floorp but this design decision makes me seriously consider switching back to my previous browser

Floorp 12, which they are currently developing, will reimplement the Workspaces.

**Comment by jficz** [comment]
Thanks, this is good info!
