### ISSUE TITLE
[Bug] Sidebar become transparent if Collapse Vertical Tab Bar enable

### ISSUE THREAD

**Issue by KnoyanMitsu** [Floorp-Projects/Floorp#770]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Sidebar transparent after showing from collapse vertical tab bar

and i disable collapse vertical tab bar sidebar not trasparent

### To Reproduce

1.showing tab bar with mouse
2.background tab bar become transparent

### Expected behavior

after showing tab bar from collapse, the background not become transparent

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/65282316/689e7161-18aa-4dd8-b22d-95b740f9a6ea)

### OS Info

Debian 12

### Floorp Version

11.8.2

**Comment by creeper-0910** [comment]
Duplicate
