### ISSUE TITLE
[Bug] Floorp closes automatically after 5 seconds of opening on Fedora 39

### ISSUE THREAD

**Issue by giridhrubajyoti2002** [Floorp-Projects/Floorp#771]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I have installed Floorp from Flatpak in Fedora 39.
After opening, it closes automatically after nearly 5 seconds.

When running from the terminal it gives the following result : 

``` 
flatpak run one.ablaze.floorp 
console.error: ({})
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
```

### To Reproduce

1. Search for Floorp
2. Run it
3. Wait for some seconds
4. It will be closed automatically after nearly 5 seconds

### Expected behavior

It should run as expected.

### OS Info

Fedora 39, kernel-6.6.12-200

### Floorp Version

11.8.2

**Comment by TheChilledBuffalo** [comment]
Please go to the `.floorp` directory in your home folder and post a screenshot of the contents in it.

**Comment by surapunoyousei** [comment]
Please use tarball version

**Comment by giridhrubajyoti2002** [comment]
> Please go to the `.floorp` directory in your home folder and post a screenshot of the contents in it.

There is no .floorp directory in /home, found it in /home/user/.var/app/one.ablaze.floorp/.floorp
![Screenshot_20240124_182138](https://github.com/Floorp-Projects/Floorp/assets/72687228/6752151b-2430-42c0-86d4-18da43d38022)

**Comment by giridhrubajyoti2002** [comment]
> Please use tarball version

tarball version not running

**Comment by surapunoyousei** [comment]
What do you mean?

**Comment by giridhrubajyoti2002** [comment]
> What do you mean?

The executable file inside floorp-11.8.2.linux-x86_64.tar.bz2 is not running in Fedora 39

**Comment by giridhrubajyoti2002** [comment]
Oh! Only Debian and Arch-based distributions are supported, Fedora is not supported yet.

**Comment by surapunoyousei** [comment]
Yeah. It's unsported. But, You can use AUR package

**Comment by giridhrubajyoti2002** [comment]
> Yeah. It's unsported. But, You can use AUR package

How can I use the AUR package in Fedora?

**Comment by surapunoyousei** [comment]
I mean, You can move to the OS.

Honestly, I do not want to add OS now. Developer is only me

**Comment by TheChilledBuffalo** [comment]
Try reinstalling the Flatpak package. I'm using it from flatpak on Fedora 39 and I have absolutely no issues with it.

**Comment by giridhrubajyoti2002** [comment]
> Try reinstalling the Flatpak package. I'm using Floorp from flatpak on Fedora 39 and I have absolutely no issues with it.

Reinstalled, but still the same issue.
