### ISSUE TITLE
[Bug] Broken icon

### ISSUE THREAD

**Issue by Luiszd2305** [Floorp-Projects/Floorp#772]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

The browser icon looks like this once the app is opened 

### To Reproduce

-Open the floorp browser

### Expected behavior

The icon should remain the same once the app is opened

### Screenshots

![Screenshot from 2024-01-23 14-29-53](https://github.com/Floorp-Projects/Floorp/assets/108742284/2d2c3a16-fe06-4514-a947-6a7a1a566a7d)

### OS Info

Fedora 39

### Floorp Version

11.8.1

**Comment by TheChilledBuffalo** [comment]
Isn't that how..... icon is supposed to look like??

**Comment by Luiszd2305** [comment]
Once opened, it looks like the icon between Slack and the trash can icon

**Comment by TheChilledBuffalo** [comment]
I use Fedora 39 as well and noticed no such issues. Are you using the tarball or flatpak version?

**Comment by surapunoyousei** [comment]
Please use tarball version,

**Comment by TheChilledBuffalo** [comment]
> Please use tarball version,

I use the flatpak version and its working well. No issues there.

**Comment by surapunoyousei** [comment]
For the most part, problems with Linux are usually problems with the operating system

**Comment by surapunoyousei** [comment]
Close issue.

There have been no other report. If there are more reports or it becomes a significant issue, it will be reopened.

Thank you for your report
