### ISSUE TITLE
Open new tabs at the end of the Tab Bar, not working

### ISSUE THREAD

**Issue by maktaba** [Floorp-Projects/Floorp#774]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I'm using floorp 11.8.2 on mx-linux 21.
Even though the setting "Open new tabs at the end of the Tab Bar" is selected, tabs only open next to the tab from which it was opened and not at the end of the tab bar as expected.

### To Reproduce

1 go to: settings
2 find: New tab position
3 select: "Open new tabs at the end of the Tab Bar"
4 while having a few tabs open try to open a tab from a tab that is not the last one

### Expected behavior

The expected behaviour is that the new tab opens at the end of the tab bar instead of next to the tab from where it was opened..

### OS Info

mx-linux 21

### Floorp Version

11.8.2

### Additional context

I also tried modifying the value of "floorp.browser.tabs.openNewTabPosition" in about:config without any result.

**Comment by surapunoyousei** [comment]
Please remove TST
