### ISSUE TITLE
[Bug] Can't add SearXNG instance that shares the name of the default SearX instance

### ISSUE THREAD

**Issue by rikafuruda** [Floorp-Projects/Floorp#775]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When trying to add a different SearXNG instance, I cannot add the instance to my search engines, even after remove the default one (For some reason a SearX instance is labeled as SearXNG). I have to use an extension like Libredirect in order to be able to add my instance.

### To Reproduce

1. Remove SearXNG from the search shortcuts menu
2. Go to any SearXNG instance (that is named SearXNG like the deafult search suggestion)
3. Try and add the instance in the search bar (It should have the little green plus sign)

### Expected behavior

The search engine gets added to the search shortcuts list

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/138363522/5e0c6e0b-5488-405a-961f-1756fb218539)

### OS Info

Windows 10 21H2

### Floorp Version

11.8.2

### Additional context

Could probably be temporarily fixed by getting an instance admin to change the name of the instance or uncompressing search,json and changing it there (but it would revert every update)
Changing it from SearXNG to SearX could also work as the default instance is a SearX instance, not a SearXNG instance.

**Comment by surapunoyousei** [comment]
Not bug.
