### ISSUE TITLE
[Bug] vertical tab bar disappears on mouse hover

### ISSUE THREAD

**Issue by BenAgin1** [Floorp-Projects/Floorp#776]
### Describe the bug

When I set my tabs to vertical and hover over the tab bar, tab bar background leaves the screen instead of expanding to the expanded tab bar, the web page shifts to the edge of the screen by  1 "tab column" distance. 

### To Reproduce

1. create blank profile in new window (to get default settings)
2. enable vertical tabs
3. restart (needed?)
4. enable collapse tab bar
5. restart

### observe on tab bar hover over:
the tab background leaves the screen, the web page shifts to the left on the screen by  1 "tab column" distance. 

### Expected behavior

the tab bar background should expand to the full size instead of disappearing. The web page should not move at all when hovering over the tab bar as it expands.

### Screenshots

![Screenshot from 2024-01-23 23-05-33](https://github.com/Floorp-Projects/Floorp/assets/37192648/e1c62547-ab97-4918-838a-8fa72d4bd876)

sorry I did not get them cropped perfectly but the scale is good enough.

### OS Info

Fedora linux 39, kernel 6.6.12-200, GNOME 45.3

### Floorp Version

11.8.2 flathub, idk why I cannot find the version inside the app when i type "version".... why does this not have parity with my mac install.

**Comment by TheChilledBuffalo** [comment]
Duplicate. This issue has been fixed and will be shipped in the next update.

**Comment by BenAgin1** [comment]
Dang I did not find any mention of it

**Comment by BenAgin1** [comment]
Dang I did not find any mention of it
