### ISSUE TITLE
[Bug] Screenshots are broken in VK

### ISSUE THREAD

**Issue by jk0893** [Floorp-Projects/Floorp#778]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

It happens anytime I make a screenshot and share it in DMs. It happens only to screenshots, images and gifs are fine.

### To Reproduce

1. Make a screenshot with either print screen button or win+s in windows.
2. Sign in/Sign up in VK.
3. Send screenshot to anyone.

### Expected behavior

Screenshot should look like this:
https://i.imgur.com/P41RHB4.png
But instead it looks like this:
https://i.imgur.com/UQ1JjRf.jpg

### Screenshots

How it looks when user sends a screenshot:
https://i.imgur.com/SzpYFVm.png
And when he inspects what he tries to send:
https://i.imgur.com/ZZkzw0I.png

### OS Info

Windows 10 Home

### Floorp Version

11.8.2

### Additional context

I tried doing same process in different browsers, but it seems only Floorp does this. I also tried to reproduce this in the web version of telegram, but they look perfect there. To be honest, I have no idea what could cause this behavior.

**Comment by regularenthropy** [comment]
Looks like canvas fingerprint error. Disable privacy.trackingprotection.enabled and privacy.resistfingerprinting in about:config

Also search for "Automatically dismiss access confirmation prompts for html5 image data" and set it to false in Floorp's settings

**Comment by jk0893** [comment]
Oh, it seems like some of these fixed the problem. An issue may consider closed.
