### ISSUE TITLE
[Bug] Previously created workspaces gone when Floorp closed and reopened.

### ISSUE THREAD

**Issue by ramsaoji** [Floorp-Projects/Floorp#779]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Previously created workspaces gone when Floorp closed and reopened.

### To Reproduce

1. Create new workspaces.
2. Close Floorp.
3. Open Floorp again.
4. Previously created workspaces will be gone.

### Expected behavior

Workspaces should be there even if Floorp is closed and reopened.

### Screenshots

Check video for reference -
https://github.com/Floorp-Projects/Floorp/assets/5617780/0fe45d50-2e15-4873-bc33-60971a472301

### OS Info

Windows 11 22H2

### Floorp Version

11.8.2

**Comment by surapunoyousei** [comment]
I ha some ideas to fix this issue

**Comment by menndouyukkuri** [comment]
Floorp workspaces disappear without tabs. So they disappear if "Open previous windows and tabs" is disabled in the settings.
If they disappear even after you enable it, it may be a bug.

**Comment by surapunoyousei** [comment]
I watched the video, but the behavior is strange.  Your workspace will be gone unless you enable the setting to restore previous tabs.

**Comment by ramsaoji** [comment]
I tried turning on "Open previous windows and tabs" still same behavior. The issue might be linked to user.js or related to history options !

**Comment by surapunoyousei** [comment]
I will submit a patch to the beta version tomorrow or the day after tomorrow.

**Comment by NandiyaLive** [comment]
Can you this to restore previous workspaces even if I haven't enabled "Open previous windows and tabs"?

**Comment by surapunoyousei** [comment]
What's meaning?

**Comment by NandiyaLive** [comment]
I don't want to restore my previous windows or tabs, but I want to restore previously created workspaces. So can you separate the option to restore workspaces from "Open previous windows and tabs" option. Like creating a new toggle in workspaces setting to restore workspaces?

**Comment by surapunoyousei** [comment]
Unfortunately, that is not possible. This is because workspaces work in conjunction with tabs

**Comment by NandiyaLive** [comment]
Ah right. No problem!

And one more thing, when I open a workspace the first tab doesn't open in the selected container. Can you fix that?

**Comment by menndouyukkuri** [comment]
> And one more thing, when I open a workspace the first tab doesn't open in the selected container. Can you fix that?

Since there is no mechanism to specify a container when creating a workspace, I think this behavior is by specification.

**Comment by surapunoyousei** [comment]
I send a patch to Floorp Daylight. Please check it

**Comment by NandiyaLive** [comment]
How can I test?

**Comment by surapunoyousei** [comment]
Change mechanism

**Comment by NandiyaLive** [comment]
Opening first tab in the selected container doesn't work even in the Daylight build. I think it can't be fixed!

Other than that workspaces work perfectly fine for me after updating to 11.8.2.

**Comment by WiLuX-Source** [comment]
I'm also having the same issue. 

> I tried turning on "Open previous windows and tabs" still same behavior. The issue might be linked to user.js or related to history options !

This fixed it for me. Even though I like the workspaces I definetely dont like this behavior, in order to keep your workspaces you need to enable an option you don't want.

**Comment by surapunoyousei** [comment]
I will close this issue as I do not intend to support manipulation of hidden settings.

**Comment by surapunoyousei** [comment]
> I'm also having the same issue.
> 
> > I tried turning on "Open previous windows and tabs" still same behavior. The issue might be linked to user.js or related to history options !
> 
> This fixed it for me. Even though I like the workspaces I definetely dont like this behavior, in order to keep your workspaces you need to enable an option you don't want.

SO. Please tell me what you changed?

**Comment by WiLuX-Source** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/61833703/77b6596e-4aa1-4334-b152-75d7c3231c5e)
I only enabled this and it worked.

**Comment by NandiyaLive** [comment]
Yea same. It works fine for me too

**Comment by OneJaredNewman** [comment]
I am losing Workspaces as well, even with "Open previous windows and tabs" enabled, but not every time. Sometimes the Workspaces are available after re-opening Floorp, other times they are gone.

When the Workspaces disappear, no pages appear under "Recently Closed" in Floorp View. I'm still trying to figure out a way to replicate this.
