### ISSUE TITLE
[Bug] Web Apps show both the address bar and Title Bar

### ISSUE THREAD

**Issue by alvinchitena** [Floorp-Projects/Floorp#781]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

All Web Apps display the address bar. The address bar is redundant because it cannot be edited or used as normal. It just displays the URL, which is a duplicate of the page name displayed on the title bar right above it. Most browsers remove the address bar from Web Apps and it definitely looks better. **Is it possible to disable the address bar for Web Apps?**

### To Reproduce

1. Open the browser and go to youtube.com
2. Install YouTube as a Web App
3. Open the YouTube Web App and observe the title bar and address bar

### Expected behavior

For the address bar to not be displayed e.g. here is how the YouTube Web App looks on the Brave Browser:
![Brave Web App Interface](https://github.com/Floorp-Projects/Floorp/assets/61254477/027a5e18-cb79-4a55-8568-d020e06d3e78)

### Screenshots

![Floorp Web App Interface](https://github.com/Floorp-Projects/Floorp/assets/61254477/ec827453-734d-4122-8be9-76e552e7f106)

### OS Info

Windows 11 Home

### Floorp Version

11.8.2 (64-bit)

**Comment by surapunoyousei** [comment]
I will add a option & this is not bug
