### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Tealk** [Floorp-Projects/Floorp#785]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

If you activate "Collapse vertical tab bar", it looks as if the background is transparent.

### To Reproduce

install flatpack
enable vertical tab bar
restart browser
hover over tab bar

### Expected behavior

the entries are easy to read thanks to a background

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/12276250/5f251858-c5cb-40d5-9853-7090029970ec)

### OS Info

Arch

### Floorp Version

Flatpack 11.8.2 (64-bit)

**Comment by CutterKnife** [comment]
https://github.com/Floorp-Projects/Floorp/issues/704
