### ISSUE TITLE
[Bug] Pinch zoom does not work Ubuntu 22.04

### ISSUE THREAD

**Issue by NikMikM** [Floorp-Projects/Floorp#786]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

I've installed Floorp browser from PPA on Linux Ubuntu and from the box pinch zoom on my laptops touchpad does not work. I've checked about:config flags, and they are set (apz.gtk.touchpad_pinch.enabled = true), but it still not working.

### To Reproduce

1. Install Floorp from PPA on laptop 
2. Open Floorp
3. Open new tab with google.com (for example i've typed there floorp)
4. Try to pinch out or in on a touchpad

### Expected behavior

On Firefox 121.0.1 with the flag apz.gtk.touchpad_pinch.enabled = true, pinch zoom works on my laptop.

### OS Info

Ubuntu 22.04 on Wayland, core 6.5.0-14-generic, X86_64

### Floorp Version

11.8.2

### Additional context

I could not find any information about this on a web-site or github, if it is duplicate, sorry. I'm passionate about experiencing Floorp, but this situation is preventing me from enjoying it.

**Comment by surapunoyousei** [comment]
Floorp  is esr based browser unsupprted

**Comment by surapunoyousei** [comment]
Floorp  12 will have it
