### ISSUE TITLE
[Bug] vertical tab bar - double click

### ISSUE THREAD

**Issue by Jayrgo** [Floorp-Projects/Floorp#787]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

double click on the vertical tab bar space should open a new tab or do nothing

### To Reproduce

enable vertical tab bar
double click on space
maximizes or restores the window

### Expected behavior

open new tab or do nothing

### OS Info

linux (artix) - kde (5.27.10)

### Floorp Version

11.8.2 (64-Bit)

**Comment by surapunoyousei** [comment]
Please  send as feature request
