### ISSUE TITLE
[Bug] Bing AI not working on Flatpak version specifically

### ISSUE THREAD

**Issue by bataneske** [Floorp-Projects/Floorp#789]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Bing AI never actually loads. Regardless of the navigation method (bing.com/chat chat.bing.com or simply searching for a prompt), the prompt will never load.

### To Reproduce

1. Open chat.bing.com
The site never loads
-or-
1. Ask a question using Bing search
2. The AI prompt loads indefinitely

### Expected behavior

Prompts eventually load on Bing search.
chat.bing.com loads.

### Screenshots

![Screenshot from 2024-01-24 21-58-55](https://github.com/Floorp-Projects/Floorp/assets/107265248/a884ef47-f8c6-4be5-bc91-9d43b88a3b1e)
![Screenshot from 2024-01-24 21-59-28](https://github.com/Floorp-Projects/Floorp/assets/107265248/7a61f816-349c-42aa-a259-ab5295fe5b3b)

### OS Info

Fedora 39 (Workstation Edition)  on Linux 6.6.12-200.fc39.x86_64

### Floorp Version

Floorp for Flatpak 11.8.2 (64-bit)

### Additional context

**There are no issues on Floorp 11.8.2 for Windows.**
**Tested on Firefox RPM, Firefox Flatpak and Firefox ESR 115 executable for Linux. Bing AI works properly on each instance as well as on a Chromium browser. So this isn't a Firefox/Bing issue nor a problem on the Windows version.**
**Settings are synced between Windows and Linux (Flatpak) using Mozilla account so it doesn't seem to be a privacy or any other setting.**

**Comment by surapunoyousei** [comment]
Flatpak is unstable. normal behavior
