### ISSUE TITLE
[Bug]  System Theme Auto Doesn't work properly

### ISSUE THREAD

**Issue by FrozenVertx** [Floorp-Projects/Floorp#790]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

As default firefox behaviour on system theme auto is when changed to darkmode everything changed to dark including urlbar,toolbar and text become white. But in floorp when i switched to system theme auto and apply dark mode the panels remains light.

### To Reproduce

1.Go to "about:addons"
2.Go to Themes
3.Choose System Theme- Auto
4.Change OS mode to DarkMode

### Expected behavior

I should be like dark theme but it is partial dark and light

### Screenshots

![Screenshot from 2024-01-25 11-46-37](https://github.com/Floorp-Projects/Floorp/assets/72699730/609e6311-ee2a-4fe8-8f61-2ec08250ed52)

### OS Info

Linux Ubuntu 23.10

### Floorp Version

Version 11.8.2 (64-bit) from apt

**Comment by surapunoyousei** [comment]
Your OS has issue.

**Comment by surapunoyousei** [comment]
No problem. You should use tarball version.

**Comment by surapunoyousei** [comment]
Yeah. Tarball version has auto update feature

**Comment by surapunoyousei** [comment]
I don't know.

**Comment by surapunoyousei** [comment]
It works fine in many environments and will not be addressed further.

This issue is closed as there is only one Floorp developer and support is limited.

**Comment by surapunoyousei** [comment]
Ahhh... So Where is it?

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/fd8889e2-88f7-459a-bc1e-39b3f93e7920)

**Comment by surapunoyousei** [comment]
Anyway, Thank you for your report. If I get same issue, I research about this issue.

**Comment by surapunoyousei** [comment]
#TabsToolbar
