### ISSUE TITLE
Large memory leak while using google cloud console

### ISSUE THREAD

**Issue by DarkMaster964** [Floorp-Projects/Floorp#792]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

For my job, I'm managing a project on Google Cloud Console. The web API isn't the fastest thing ever, however, recently when I've switched from the Opera GX browser to Floorp, freezing on that page has started occurring.
On opera same tab uses about 500-700mb of ram, while on Floorp same tab uses about 4gb of ram, which is absurd.
Although I have 16gb ddr4 ram and i5-7400, that page is unusable

### To Reproduce

Open a project on the Google Cloud Console.
Select any service
See the ram usage spiking up

### Expected behavior

It shouldn't consume that much ram, and it should work smoothly

### OS Info

Windows 11 22H2

### Floorp Version

11.8.2 64bit FIrefox 115.7.0

**Comment by creeper-0910** [comment]
Does the same problem occur in Firefox?

**Comment by surapunoyousei** [comment]
The memory leak cannot be resolved on the Floorp side, so the issue is closed.

Please contact Google Could Console.

**Comment by DarkMaster964** [comment]
> Does the same problem occur in Firefox?

No, it doesn't

**Comment by FloraMaeWolfe** [comment]
Just mentioning that this issue is still present. My ram use shot up to over 8GB while trying to use google cloud console and I had to stop using it because all my ram and swap was used up and about to crash the system. So as of May 2024, this is still an ongoing issue apparently.

**Comment by surapunoyousei** [comment]
Currently, We migrating to Rapid release version of Firefox. it may fix tbe issue
