### ISSUE TITLE
[Bug] Toggle sidebars only working for tabs panel

### ISSUE THREAD

**Issue by cherrynoize** [Floorp-Projects/Floorp#794]
### Attention!

- [x] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I click on the toggle sidebars button in the toolbar only the left sidebar (I'm using Sidebery there, haven't tested switching places but I assume it isn't position-dependent) gets toggled.

### To Reproduce

Click on the button.

### Expected behavior

Both toggled.

### OS Info

Arch

### Floorp Version

Mozilla Floorp 11.7.1

**Comment by surapunoyousei** [comment]
It's expected. The button is for Floorp Sidebar

**Comment by cherrynoize** [comment]
That's the issue. The Floorp sidebar remains uneffected. It's not being toggled, while the tabd panel is.

**Comment by surapunoyousei** [comment]
I said mistake it's only affect Floorp Sidebar
