### ISSUE TITLE
[Bug] The `:hover` behavior is broken on Wayland. widget.gtk.ignore-bogus-leave-notify 1 doesn't work.

### ISSUE THREAD

**Issue by Zaphkiell** [Floorp-Projects/Floorp#796]
### Attention!

- [x] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

It is a bug featured in vanilla firefox and nightly. Basically, when dragging, the hover state that is supposed to persist, stops and in combination with autocollapse in addons like TST, sideberry, makes it impossible to change tree structure in a sane manner. the solution is widget.gtk.ignore-bogus-leave-notify 1 in the config. But it doesn't seem to work at all on wayland. 

### To Reproduce

I.
1. Log into floorp using wayland window protocol
2.  go to https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/CSS/:hover/_sample_.basic_example.html
3.  hover over the text. take note of the styling
4.  drag the text. Observe the absence of `:hover` styling
5.  use widget.gtk.ignore-bogus-leave-notify 1
---------------------------------------------------------------------
 II.
    1. Log into Floorp through xwayland
    2. Follow the same steps as in I.

### Expected behavior

I. 
The `:hover`  styling should now persist after the changes to the config. Ideally it should persist even without the changes to the config
----------------------------------------------
II. 
The `:hover`  styling should now persist after the changes to the config. **And they do**

### OS Info

Linux 6.7.0-arch3-1

### Floorp Version

11.8.2

### Additional context

Like I said, the issue is known and has a report in bugzilla, but I don't think there is any progress being made. The fact that widget.gtk ... config change doesn't work at all on Wayland is concerning, and I haven't found a meaningful solution without building firefox and applying patches manually. Although, in the bug report that I included below, there is already a proposed solution.
My Floorp uses a custom CSS theme, so I can't say for sure, but I think vertical tabs option doesn't suffer from the problem of hovering at all, but since Floorp officially endorses add-ons like TST, I believe it's an issue worth noting since it severely cripples the experience when the autocollapse option is on.

I'd be glad if either the root problem or the widget.gtk.ignore one gets fixed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1818517

**Comment by regularenthropy** [comment]
If this bug occurs in Firefox and Firefox Nightly, then you will need to wait for the next ESR release. 
Floorp is based on ESR.

**Comment by surapunoyousei** [comment]
Floorp is ESR based. Thank you for your report
