### ISSUE TITLE
[Bug] Can't open on Arch Linux

### ISSUE THREAD

**Issue by DADA30000** [Floorp-Projects/Floorp#798]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

After recent update, it now crashes on startup and gives this:
XPCOMGlueLoad error for file /usr/lib/floorp/libxul.so:
libvpx.so.8: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
Latest firefox and firefox-esr works

### To Reproduce

1. Update all packages
2. Start floorp

### Expected behavior

It should start without any error

### Screenshots

![изображение](https://github.com/Floorp-Projects/Floorp/assets/73874445/041d5224-f837-49c4-87a6-2da25ad2d06a)

### OS Info

Arch Linux, latest updates

### Floorp Version

11.8.2-1

**Comment by DADA30000** [comment]
floorp-bin works

**Comment by Voidlighter** [comment]
I'm having this same issue in version 11.14.1 on SteamOS, and I tried the floorp file and the floorp-bin file

**Comment by DADA30000** [comment]
> I'm having this same issue in version 11.14.1 on SteamOS, and I tried the floorp file and the floorp-bin file

I personally don't even use floorp or arch right now lol, but I will reopen the issue

**Comment by DADA30000** [comment]
> @Voidlighter @DADA30000 If you are facing issues in Arch Linux, contact the maintainer of the respective packages. I think this issue should remain closed.
> 
> And also, @Voidlighter its not about the `floorp` or the `floorp-bin` file. Try installing the `floorp-bin` package from the AUR.
> 
> `yay -S floorp-bin`

oh ok then

**Comment by Voidlighter** [comment]
That answer would probably work: I ended up putting nix on my steam deck and installing it that way, and that worked.
