### ISSUE TITLE
[Bug] Vertical tab background doesn't slide-out with tabs in light mode

### ISSUE THREAD

**Issue by craftnut** [Floorp-Projects/Floorp#800]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

In light-mode, the background doesn't slide out with the tabs when vertical tabs are in collapsible mode

### To Reproduce

1. Go to settings
2. Set theme to Lepton UI light mode
3. Enable vertical tab bar, with collapse option enabled

### Expected behavior

I would expect a background is supposed to expand outward with the tabs, as it does in dark mode

### Screenshots

The issue:
![backone](https://github.com/Floorp-Projects/Floorp/assets/61483322/2c6d5b4e-b241-4295-a18b-a0b659627c1a)
![backtwo](https://github.com/Floorp-Projects/Floorp/assets/61483322/61836699-2681-4663-a688-e96e067412ca)

Looks normal in dark mode:
![dark](https://github.com/Floorp-Projects/Floorp/assets/61483322/726db226-59f0-4101-8dab-9707d8be90a6)

### OS Info

Windows 10 22H2

### Floorp Version

11.8.2 (64-bit)

**Comment by creeper-0910** [comment]
Duplicate
