### ISSUE TITLE
[Bug] workspaces top left menu not rendered correctly

### ISSUE THREAD

**Issue by lazymonkey2** [Floorp-Projects/Floorp#805]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

the top left workspaces menu is not correctl rendered (see the grey part):
![image](https://github.com/Floorp-Projects/Floorp/assets/26486758/3f823c77-845e-4172-981a-5867138a880d)

### To Reproduce

1. create some workspaces
2. open the top left menu

### Expected behavior

the grey part should not be visible

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/26486758/c7d3b6d8-9e4f-4c57-9326-5042fc286b48)

### OS Info

windows 10 22h2

### Floorp Version

11.8.2

**Comment by surapunoyousei** [comment]
It expected now. But, will change more good
