### ISSUE TITLE
[Bug] korean typing bug

### ISSUE THREAD

**Issue by ecruosnepo** [Floorp-Projects/Floorp#807]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I type Korean in url bar, the search window at the center of the screen appears and disappears.

### To Reproduce

typing korean in url bar.

### Expected behavior

search window appears and disappears.

### OS Info

windows 10 22h2

### Floorp Version

11.8.2

### Additional context

I found out about this browser while looking for firebox userchrome. I transferred right away because there were so many good features. Thank you for providing me with the browser.

**Comment by surapunoyousei** [comment]
Please provide a video

**Comment by nyanrus** [comment]
If you talking about search-suggest in URL bar, that occurs in firefox too.
the issue is not Floorp issue.

**Comment by ecruosnepo** [comment]
https://github.com/Floorp-Projects/Floorp/assets/67457511/0218484c-c992-4c60-8250-9384fd16cd1b

**Comment by surapunoyousei** [comment]
OK. Send report to Firefox

**Comment by ecruosnepo** [comment]
Thank you for your response.

**Comment by surapunoyousei** [comment]
You're welcome! Thank you for your bug report!
