### ISSUE TITLE
[Bug] Context menu lacking options when used with Tree Style Tabs

### ISSUE THREAD

**Issue by Astarte902** [Floorp-Projects/Floorp#808]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When using Tree Style Tabs and going to use the context menu, the context menu lacks all of the Floorp specific options and appearance

### To Reproduce

1. Install Tree Style Tabs
2. In Tree Style Tabs, bring up context menu for tab

### Expected behavior

Context menu for a tab in Tree Style Tabs includes Floorp options (such as move to another workspace).

### Screenshots

![Floorp_TST_Bug_1](https://github.com/Floorp-Projects/Floorp/assets/77045403/414bac58-1dd3-4739-b361-a61c8154c054)
Context menu when clicking on a TST tab
![Floorp_TST_Bug_2](https://github.com/Floorp-Projects/Floorp/assets/77045403/71688361-0e1a-47d2-9b1d-441e628c1f14)
Context menu when normally clicking on a tab

### OS Info

Windows 11 23H2

### Floorp Version

11.8.2

**Comment by surapunoyousei** [comment]
Not bug
