### ISSUE TITLE
[Bug] Touch ID does not work for 1password extension on Mac

### ISSUE THREAD

**Issue by dasherma** [Floorp-Projects/Floorp#809]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Mac Touch Id does not work to open the 1Password app via the extension even though the setting to integrate the extension and the app is selected.

### To Reproduce

Click on the 1Password icon in the toolbar
There should be an option to open 1Password with touch id
To see how I believe it should work, see the behavior in Firefox.

### Expected behavior

There should be a secondary dialog allowing touch id to interact with the 1Password app to retrieve a password.

### OS Info

MacOS 13.4.6

### Floorp Version

11.8.2

**Comment by surapunoyousei** [comment]
deplicate

**Comment by dasherma** [comment]
This was also posted on Reddit, but I have deleted the Reddit post.
I was told that the nightly build of 1Password can add Floorp to the list of trusted browsers, which the "stable" build cannot do. 
I will take this up further with the 1Password people.

**Comment by surapunoyousei** [comment]
Thanks

**Comment by dasherma** [comment]
Sorry, I know this bug/request is closed, but - you can now add Floorp to the list of trusted browsers in the production build of 1Password.

Again, sorry about continuing to comment here -- I just didn't know where else to comment.
