### ISSUE TITLE
Can not complete Cloudflare capthas [Bug] 

### ISSUE THREAD

**Issue by Minashi26** [Floorp-Projects/Floorp#812]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Cloudflare capthas can not be completed.

The following error shows up every time: 'This check is taking longer than expected. Check your Internet connection and refresh the page if the issue persists'. 

Additionally, CPU ussage goes to 100% right after clicking the captcha box.

### To Reproduce

1. Go to a page where Cloudflare captcha is required to log in, such as https://chat.openai.com/ or https://gitlab.com/users/sign_i

2. Click the captcha box

3. After a few seconds, you will always see the error 'This check is taking longer than expected. Check your Internet connection and refresh the page if the issue persists'
Additionally, CPU ussage will go to 100%

### Expected behavior

It is expected for the capthca to work propperly.

### Screenshots

![imagen](https://github.com/Floorp-Projects/Floorp/assets/124444988/2e58bc9a-e984-43f8-88b5-e95301e9efb3)

### OS Info

Windows 10 Home Single Language 22H2

### Floorp Version

11.8.2 (64-bit)

### Additional context

Also tried filling capthas in another PC with antiX Linux. The same problem occurred.

**Comment by creeper-0910** [comment]
This problem occurs when the UserAgent is disguised.

**Comment by Minashi26** [comment]
> This problem occurs when the UserAgent is disguised.

My User Agent is configured to 'Use Firefox User Agent (Default)'

**Comment by creeper-0910** [comment]
Hmmm... 
does this problem also occur with Firefox ESR115?
Or if you are applying user.js, it could be the cause.

**Comment by Minashi26** [comment]
I changed the user agent to 'Spoof Chrome on Windows' and then back to default. It works now

**Comment by cindrmon** [comment]
is there a way to bypass cloudflare even while still using the spoofed user agent? or do i really have to use the default for it..?

**Comment by creeper-0910** [comment]
CloudFlare Turnstile checks are strict and it would be difficult to pass the check with the UserAgent changed...

**Comment by JimFlasch** [comment]
I'm having this issue with fanart.tv without a useragent switcher active!

**Comment by Sasikuttan2163** [comment]
I didn't have any issues, it could be with your network. Switch to another network and try again. Also check if you have any VPNs on because Cloudflare can be picky with that too.

**Comment by JimFlasch** [comment]
I don't have any VPNs on and it's not the network - Cloudflare's Turnstile works fine on other browsers I have installed.

**Comment by JimFlasch** [comment]
After 3-4 days of working fine, Cloudflare's Turnstile is acting up again - not only on Floorp but also on Waterfox! Firefox (for now) and Chrome have no problems with it though.

**Comment by Alistair1231** [comment]
Would it be possible to blacklist pages from the changed user agent or does this always have to be a browser-wide setting?
Since I am using Privacy Pass, I could just blacklist https://pp-attester-turnstile.research.cloudflare.com/ and that should solve the issue, I expect.
I would like to appear as Chrome.

**Comment by JimFlasch** [comment]
Cloudflare Turnstile is broken on Floorp AGAIN!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Can someone fix it please?????????????????????????????????

**Comment by JimFlasch** [comment]
Turnstile's also broken on Waterfox, BTW, so this might be a Mozilla problem ... maybe - it works on Firefox, the original Mozilla browser, oddly enough. Whatever the problem is, it must be fixed so users of all browsers can access sites protected by it!

**Comment by JimFlasch** [comment]
Turnstile is working on Floorp again as of 6/17/2024 @ 3:55 PM. Hopefully it will never break here again.

**Comment by JimFlasch** [comment]
broken on Floorp again as of 6/26/2024.

**Comment by JimFlasch** [comment]
broken on Waterfox as of 7/2/2024 9:43 PM

**Comment by JimFlasch** [comment]
And on Firefox, too! (there it doesn't even let me click on the checkbox - it just automatically goes from the checkbox screen to the "verifiyng you are human" screen and back again.)

**Comment by JimFlasch** [comment]
working on firefox again 7/4/2024, 3:16 PM

**Comment by JimFlasch** [comment]
working on Floorp again 7/7/2024 3:51 PM

broken on Floorp again 7/14/24 3:37 PM; working on Firefox and Waterfox, though.

**Comment by JimFlasch** [comment]
back working on Floorp again 7/14/2024 5:30 PM - weird

**Comment by JimFlasch** [comment]
broken on Floorp AGAIN after third blackout-induced restart 7/14/2024 9:50 PM! (worked after each of the first two, weirdly enough) Whatever is going wrong, make it stop!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by TheChilledBuffalo** [comment]
@JimFlasch We understand this can be frustrating. This happens because ESR115 (on which Floorp is based on) is pretty old. So these captcha systems might find it suspicious. But don't worry, the main dev is working on migrating the codebase to ESR128 which should fix these issues. The release is planned for next month. Please wait until then, thanks!

**Comment by JimFlasch** [comment]
Would prefer it to be out now!

**Comment by JimFlasch** [comment]
OK, Turnstile is working on Floorp again as of 7/21/2024, 3:40 PM; maybe you could get out the Floorp version based on ESR128 before it breaks again?

**Comment by JimFlasch** [comment]
broken AGAIN, 7/21/2024, 9:27 PM; where's the ESR128-based Floorp?????????????????????????

**Comment by creeper-0910** [comment]
We are currently working on transitioning to ESR128.
No further reports are required.
