### ISSUE TITLE
[Bug] Can't sign in to ChatGPT

### ISSUE THREAD

**Issue by CarlSmotricz** [Floorp-Projects/Floorp#815]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Accessed with Floorp, ChatGPT goes into a loop with "Verify you are human" and "checking connection is secure."

### To Reproduce

1. Go to https://chat.openai.com

### Expected behavior

Passing the "humanity check" in one go.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/11720421/87de1cbd-97ab-4a53-84ae-feec28d26cd7)

![image](https://github.com/Floorp-Projects/Floorp/assets/11720421/e9d336a6-27d4-4e21-8d2d-2fef27dd2f63)

![image](https://github.com/Floorp-Projects/Floorp/assets/11720421/d07b90dc-52f2-4e89-b225-3e267ee9f881)

![image](https://github.com/Floorp-Projects/Floorp/assets/11720421/2bc94ea9-d3ce-4997-b0fb-f06b72ff303a)

### OS Info

MS Windows 11 Home, 10.0.22621

### Floorp Version

11.8.2

### Additional context

I have Floorp set to "emulate Chrome". I would prefer not to deactivate this feature as it's a main reason I want to use Floorp in the first place.

**Comment by regularenthropy** [comment]
Related: https://github.com/Floorp-Projects/Floorp/issues/812
