### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by h0ppi** [Floorp-Projects/Floorp#816]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Cannot connect using floorp (11.8.2 - 64-bit). Meanwhile, Firefox (115.7.0esr 64-bit) has no issues.

### To Reproduce

Enter DSM IP > No response
- tab says "Problem loading page'
- Page info window says 'Connection not secure'

### Expected behavior

Open DSM login page

### OS Info

Windows 10

### Floorp Version

11.8.2 - 64-bit

**Comment by surapunoyousei** [comment]
Did you install userjs?
