### ISSUE TITLE
[Bug]: Rounded Corners causing Blurriness and Lag

### ISSUE THREAD

**Issue by TyraelWasTaken** [Floorp-Projects/Floorp#819]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When enabled rounded corners will make ultrawide monitors have heavy blur and lag on pages, clearing up once hovered over.

### Reproduction Steps

1. Enable rounded corners
2. Get to above ~3440x1440

### Expected Behavior

Rounded corners on windows.

### Actual Behavior

Rounded corners on windows, but very heavy lag and blur

### Browser Version

11.8.2

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
This is a limitation of CSS and is not planned to be corrected.

Also, this is a duplicate
