### ISSUE TITLE
[Codebase suggestion]: Separate static sidebar modes from dynamic URL modes

### ISSUE THREAD

**Issue by regularenthropy** [Floorp-Projects/Floorp#82]
It would be an improvement to the codebase, if static and dynamic modes were completely separated from each other.
It would add more clarity and reduce hacks such as addition and subtraction to set CustomURLs. 

e.g
```js
custom_url_id = sbar_id + DEFAULT_STATIC_SIDEBAR_MODES_AMOUNT
```
```js
webpanel_id = modeValuePref - DEFAULT_STATIC_SIDEBAR_MODES_AMOUNT;

```

**Comment by surapunoyousei** [comment]
Where exactly?

**Comment by regularenthropy** [comment]
> Where exactly?

# Part 1. The whole problem
To fully understand the problem with combining static and dynamic modes, we need to look at how modes are being set up.
```js
function setStaticSidebarMode(sbar_id) { 
    Services.prefs.setIntPref("floorp.browser.sidebar2.mode", sbar_id);
    displayBrowserManagerSidebar()
    setSelectedPanel()
} 

/* From 0 to 19 - CustomURLSetter. 20 URLs in total.*/
function setDynamicSidebarMode(sbar_id){
    let custom_url_id = sbar_id + DEFAULT_STATIC_SIDEBAR_MODES_AMOUNT /* Hack to start from 0, yet maintain compatibility with the previous solution. eg: If 0, than 5. If 1, than 6  */
    Services.prefs.setIntPref("floorp.browser.sidebar2.mode", custom_url_id);
    displayBrowserManagerSidebar();
    setSelectedPanel();
}
```
Static sidebar modes are unchangeable, but due to the fact, that they aren't separated from each other, I created a hack below.
```js
let custom_url_id = sbar_id + DEFAULT_STATIC_SIDEBAR_MODES_AMOUNT
```
This thing sets up dynamic modes (customURLs), while also omitting the indexes of a static mode ID's (Browser Manager Mode, Bookmark Mode, History Mode, Downloads Mode and TreeStyleTab Mode).

To differentiate these two modes, I also created the following hack:
```js
const DEFAULT_STATIC_SIDEBAR_MODES_AMOUNT = 5 /* Static sidebar modes, that are unchangable by user. Starts from 0 */
const DEFAULT_DYNAMIC_CUSTOMURL_MODES_AMOUNT = 19 /* CustomURL modes, that are editable by user. Starts from 0 */
```
This thing explicitly separates the amount of static and dynamic modes, which are being set up by changing “floorp.browser.sidebar2.mode” pref.

#### Why had I done this?
Currently, the dynamic and static modes are combined in one single integer pref “floorp.browser.sidebar2.mode”, which is being used for static and dynamic modes together. (From 0 to 4 static, unchangeable by user, and from 5 to 20 (changeable by users))
To separate both modes, I created two constants, and then a small hack, to differentiate them from each other. 
```js
let custom_url_id = sbar_id + DEFAULT_STATIC_SIDEBAR_MODES_AMOUNT
```

# Part 2. The proposed solution
If the modes will be separated from each other, it will be much easier to create even more modes without any hacks!
You don't need to explicitly change these variables, or even add/subtract value from each other!
e.g., "floorp.browser.sidebar2.customurl_mode{id_here}" or  "floorp.browser.sidebar2.static_mode{id_here}"

**Comment by surapunoyousei** [comment]
I see. Isolating the relationship between the web panel and the browser management tool sidebar. understood.

 I'm currently implementing per-container isolation of webpanels. I'll touch you a little after that.

**Comment by surapunoyousei** [comment]
It was decided to introduce various changes in 10.7.1, so it will be closed.
