### ISSUE TITLE
[Bug]: Theme tab/menu bar background not applied correctly

### ISSUE THREAD

**Issue by Redjard** [Floorp-Projects/Floorp#832]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

⁤

### Reproduction Steps

Create a new profile/installation of Floorp
Select install my theme (https://addons.mozilla.org/en-US/firefox/addon/oledfox/)
tab/menu bar doesn't apply the background
switch "Firefox Photon・Lepton UI" between "Use Photon design", "Use Lepton design", and "Use tweaked Proton design"
All three now show the background only in the top right corner

### Expected Behavior

This, but with the "Firefox Photon・Lepton UI" Design
![image](https://github.com/Floorp-Projects/Floorp/assets/47570415/5c0b547d-b407-4860-8505-c03db322c30b)

### Actual Behavior

![image](https://github.com/Floorp-Projects/Floorp/assets/47570415/c11f8586-cb5d-4e90-92d1-13311d9a9783)

### Browser Version

11.8.2 | Firefox: 115.7.0

### Operating System

Linux 64bit (tarball), Linux 64bit (flatpak), Windows 10 64bit

### Additional Context

This is the theme used:
https://addons.mozilla.org/en-US/firefox/addon/oledfox/

**Comment by surapunoyousei** [comment]
Did you test it on Firefox  UI Fix on Firefox ?

**Comment by Redjard** [comment]
https://github.com/Floorp-Projects/Floorp/assets/47570415/325915f6-7f9c-4799-9f58-c5c6fa1a459c

**Comment by Redjard** [comment]
Is this what you mean?

**Comment by surapunoyousei** [comment]
So... I means, Use lepon Firefox

**Comment by Redjard** [comment]
as in native firefox with this (https://github.com/black7375/Firefox-UI-Fix) userscript?

**Comment by Redjard** [comment]
The issue occurs with Lepton too. So I assume this is a Lepton issue and I should report it there?

**Comment by surapunoyousei** [comment]
Yeah. report it on there
