### ISSUE TITLE
[Bug]: The UI is broken when maximized on MacOS using the Lepton UI theme

### ISSUE THREAD

**Issue by The-Marik** [Floorp-Projects/Floorp#834]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

<img width="1680" alt="Screenshot 2024-02-02 at 09 45 12" src="https://github.com/Floorp-Projects/Floorp/assets/92184649/76ff4225-84f5-4b39-853e-e4e4790d63a2">
<img width="1680" alt="Screenshot 2024-02-02 at 09 44 41" src="https://github.com/Floorp-Projects/Floorp/assets/92184649/9c58ac4d-fb41-46b7-9f53-9df90b80365a">
The UI is broken when maximized on MacOS using the LeptonUI

### Reproduction Steps

1. Set the theme to Lepton UI
2. Set the tab style to vertical and allow to restart
3. Maximize on MacOS (green traffic light) and should be broken

### Expected Behavior

The UI appears properly without any cut off text and proper spacing, pleasant to look at
<img width="1680" alt="Screenshot 2024-02-02 at 09 49 17" src="https://github.com/Floorp-Projects/Floorp/assets/92184649/5065e848-5830-48e4-9666-3be3c5250b93">

### Actual Behavior

The Text is cut off, the is a strange grey bar at the top of the screen not appearing in any other screen

### Browser Version

11.8.2 (64-bit) | Firefox: 115.7.0

### Operating System

MacOS Sonoma 14.2

### Additional Context

Macbook Pro 13 inch M1 2020 resolution set to 1680x1050 or "more space"

**Comment by surapunoyousei** [comment]
Please check issue on Firefox ESR with Lepton

**Comment by Pontaro1010** [comment]
私も同じ問題に悩まされていましたが、userchromeに`#titlebar {
    display: none;
  }
`と追加することによって解決しました。
ご参考になれば幸いです。

**Comment by The-Marik** [comment]
There are no vertical tabs on Firefox ESR nor any design settings available in Firefox ESR

> Please check issue on Firefox ESR with Lepton

**Comment by surapunoyousei** [comment]
Lepton is userChrome.css theme

**Comment by surapunoyousei** [comment]
I find the bug on macOS somona

**Comment by surapunoyousei** [comment]
Fixed
