### ISSUE TITLE
[Bug]: 404 when updating from ppa.floorp.app

### ISSUE THREAD

**Issue by jcdickinson** [Floorp-Projects/Floorp#835]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

It looks like a relative path is causing issues updating floorp:

```
> sudo apt upgrade
...
https://ppa.floorp.app/amd64/./floorp-11.9.0.deb  404  Not Found
```

### Reproduction Steps

On Ubuntu 22.04

1. Have floorp installed
2. run `sudo apt update && sudo apt upgrade`

### Expected Behavior

Floorp updates

### Actual Behavior

Apt fails to update floorp

### Browser Version

11.8.2

### Operating System

Ubuntu 22.04

**Comment by surapunoyousei** [comment]
Fixed
