### ISSUE TITLE
[Bug]: Floorp hijacked css files system wide (MacOS)

### ISSUE THREAD

**Issue by m-thomson** [Floorp-Projects/Floorp#843]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp hijacked all .css files on my MacOS system to be opened with Floorp. It's easy to fix with changing the file association ("open with" + "change all") in Finder but it shouldn't happen.

### Reproduction Steps

I had previous installed Floorp some months ago (not sure what version) and today updated to 11.9.0 and that's when I noticed that all .css files were set to open with Floorp. It could already be fixed and this happened with the previous version but I'm not sure.

### Expected Behavior

Floorp should not take over .css file associations system wide.

### Actual Behavior

Floorp associates itself as the dedicated app to open all .css files.

### Browser Version

11.9.0

### Operating System

macOS Sonoma 14.3

### Additional Context

Note that .js files seem to be unaffected.

**Comment by CutterKnife** [comment]
Well, I don't think it is a serious problem because it is easy to fix.

**Comment by surapunoyousei** [comment]
This  is not bug.

**Comment by m-thomson** [comment]
Okay, I’m a bit surprised by that response. Let me try to explain it differently: 

If I didn’t set Floorp as my default browser then you certainly shouldn’t be assuming I want Floorp to be the default handler for **all the css files on my entire machine**.  I mean… think about it. Why would I want that? I’m just taking the browser for a test drive at this point - not making a commitment 😕.

Go ahead and close it but know that you’re going to annoy a lot of Mac web designers (and developers) who have .css files set to open in their favourite editor. 

Best of luck.

**Comment by CutterKnife** [comment]
This happens with some apps, not just Floorp.
For example, installing Nibbles (convert to GIF) changes the default app for video, but does not allow the video to play.
However, I am not a Mac App expert, so I don't know if that is an app issue that can be fixed.

**Comment by m-thomson** [comment]
I'm a developer. I know some apps do this. That doesn't make it right. 

If it won't be fixed because it's an issue with developer resources then that's 100% understandable. I know you guys are a very small team. But trying to justify this behaviour as desirable is weird. You should be asking yourself "is that what users expect?" and "is this helpful for users?". The answer to both those questions is a resounding no.

It's not really worth my time to explain why this behaviour is user-hostile beyond what I've already said. Best of luck guys.

**Comment by surapunoyousei** [comment]
I don't recall manipulating CSS file associations around Firefox code.

So it is not a bug.

**Comment by menndouyukkuri** [comment]
> If it won't be fixed because it's an issue with developer resources then that's 100% understandable. I know you guys are a very small team. But trying to justify this behaviour as desirable is weird. You should be asking yourself "is that what users expect?" and "is this helpful for users?". The answer to both those questions is a resounding no.

Generally speaking, the word bug does not mean that something does not behave as the user expects.

**Comment by m-thomson** [comment]
After going through the effort to bring an (admittedly) minor issue to your attention all I've seen is low-level hostility. I literally don't care anymore. I was trying to be helpful. Helpful because this behaviour will [annoy Designers and Developers](https://github.com/Floorp-Projects/Floorp/issues/843#issuecomment-1925595568), and those people are often early adopters and tech evangelists. If you don't mind annoying those people, then have at it. I don't care.

But, please understand that for going through the effort to report something that could make your software better, I expected better treatment.

Anyways, I uninstalled your browser a long time ago so I'm not sure why you're commenting on this closed issue, just to... nitpick? What's your problem? I've made it clear that I've moved on. You should too.

Hijacking file associations with zero advantage to the user is just bad practice. Call it whatever you want "bug", "issue", "unexpected behaviour", "annoyance",  whatever.  *I don't care*.

*Again* best of luck to you guys. You're sure going to need it.
