### ISSUE TITLE
[Bug]: Recent file from right click icon on linux - item is still present, noot able to delete it

### ISSUE THREAD

**Issue by Rolo1973** [Floorp-Projects/Floorp#845]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hi, I'm on Linux Arch based, I have Floorp on the application bar, if i click right button I will have a Recent file item displayed,  If i click to forgot recent file it does nothing, if I clean coockies and history too, the item is still present on my right click menu.

### Reproduction Steps

have a recent file downloaded but deleted from the system
right click on florp icon on my application bar and i have a recent file item with the name of that file deleted
no way to delete the item even clicckin on delete recent file or delete cookies or history

### Expected Behavior

Recent file been empty

### Actual Behavior

Recent file has a item present on it even if this file is deleted some times agoo

### Browser Version

11.9.0

### Operating System

EndeavouOS Linux, Arch based OS

**Comment by surapunoyousei** [comment]
You should provide a video

**Comment by Rolo1973** [comment]
https://github.com/Floorp-Projects/Floorp/assets/111699894/883b34b4-424b-41f8-93b1-d4b43f017b52

That's is my issue

**Comment by surapunoyousei** [comment]
What is your package manager that is Floorp install source.

**Comment by Rolo1973** [comment]
installed Floorp using chaotic-aur that is the aur package available for arch distros  been compiled by Garuda Linux devs that are who crate this chaotic-aur source, so we don't need to compiled it, is pre-compiled. Is last available 11.9.0 revision.
Garuda Linux devs will use Floorp as base for their future Firedragon Browser but at the moment is in alpha stage and not available, just to let you know

**Comment by surapunoyousei** [comment]
Ubuntu does not show this, so I assume the problem is on the package side, not Floorp.

Please contact that side.

**Comment by Rolo1973** [comment]
ok
