### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kaekkr** [Floorp-Projects/Floorp#850]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

System: Ubuntu, laptop. 13 screen size

When I rolled up the vertical tabs bar, the theme of this area is light, while the main theme of browser is set to dark. Because of that, the names of tabs cannot be seen. 

### Reproduction Steps

1. Set vertical tabs
2. Hide them
3. Restart Floorp
4. Bug

### Expected Behavior

So, on my pc, which runs windows 11, and has 24 screen size all works perfectly. The hidden vertical tab (rolled up) has dark theme and names of tabs can be seen. 

### Actual Behavior

While the actual behavior is that, it is in light mode, and the name of tabs cannot be seen. 

### Screenshots

[Screencast from 05-02-24 12:32:23.webm](https://github.com/Floorp-Projects/Floorp/assets/94045551/19c08c49-fa1c-4a1a-9c52-e20e1ce87cc4)

### Browser Version

11.9.0

### Operating System

Ubuntu 22.04.3 LTS

### Additional Context

![Screenshot from 2024-02-05 12-29-46](https://github.com/Floorp-Projects/Floorp/assets/94045551/81ae4d12-23cd-4651-80bd-15dae98e1c3d)
![Screenshot from 2024-02-05 12-30-13](https://github.com/Floorp-Projects/Floorp/assets/94045551/d74cc927-4f2b-41ac-b30e-a69bb7bbd713)

**Comment by surapunoyousei** [comment]
This is due to compatibility with other operating systems and cannot be corrected at this time.

Please use other themes instead.

**Comment by kaekkr** [comment]
Okay, Thanks!

**Comment by surapunoyousei** [comment]
Thank you for your report

**Comment by Th1nkK1D** [comment]
@kaekkr I ran into the same issue and I found out that I can actually activate Firefox native dark theme in the "Extensions & Themes" settings at `about:addons`, and it just solves the issue.
 
![image](https://github.com/Floorp-Projects/Floorp/assets/8860448/f3a92387-0cfc-42ba-bf87-ef8d00a29208)

**Comment by kaekkr** [comment]
@Th1nkK1D thank you! I will try this
