### ISSUE TITLE
[Bug]: Still getting a warning from MacOS when installing v 11.9.0

### ISSUE THREAD

**Issue by papernoise** [Floorp-Projects/Floorp#851]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

This is more of a heads up, but I still get a warning when installing the latest **floorp-macOS-universal.dmg** on MacOS Ventura.

### Reproduction Steps

1. download v. 11.9.0 for MacOS from github
2. install
3. see warning

### Expected Behavior

What is written in the readme:

> After version 11.0.0, Floorp has obtained Apple Notarization & Certification. This means that you can install Floorp without any warning messages. Additionally, Floorp now includes an auto-update system.

### Actual Behavior

See screenshot

### Screenshots

<img width="262" alt="image" src="https://github.com/Floorp-Projects/Floorp/assets/1595523/debab19e-0cdb-42e4-9128-0dc26ba3c398">

### Browser Version

11.9.0

### Operating System

MacOS Ventura 13.3.1

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/actions/runs/7749887107/job/21138052242

**Comment by surapunoyousei** [comment]
Floorp is built by running this action, but I see no problem output and cannot reproduce it on my Mac.

**Comment by papernoise** [comment]
Reopening because I have some new info and I still get the same error with 11.12.0

Checked the console (Mac Analytics Data) and it gives me this:

```
assessment denied for .app
com.apple.message.domain: com.apple.security.assessment.outcome2
com.apple.message.signature2: bundle:org.mozilla.floorp
com.apple.message.signature3: .app
com.apple.message.signature5: 115.10.0
com.apple.message.signature4: 1
com.apple.message.signature: denied:Unnotarized Developer ID
SenderMachUUID: 8E7F91C4-B93F-3CDA-B98A-A1F46E5944AB
```

**Comment by surapunoyousei** [comment]
hmm

**Comment by papernoise** [comment]
And I should also point out that I don't normally get any warning messages for notarized apps.
