### ISSUE TITLE
[Bug]: Zoom percentage in address bar

### ISSUE THREAD

**Issue by SakethKanchi** [Floorp-Projects/Floorp#859]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

There is no zoom level indicator in the addesss bar

### Reproduction Steps

1. Zoom in on any webpage

### Expected Behavior

Expected a zoom level indicator in the address bar

### Actual Behavior

No indication of zoom level 

### Screenshots

https://imgur.com/a/VFBLaMe

### Browser Version

11.9.0

### Operating System

Windows 11

**Comment by CutterKnife** [comment]
Immediate alternatives include the following:
- Open the application menu and click on the zoom level
- `Ctrl (Cmd)` + `0` shortcut
- Adding a zoom in/out tool to the toolbar or status bar

**Comment by breadbeforerice** [comment]
I have confirmed that the latest version of Firefox ESR does not have this problem.
 is checked, but I tried with a new profile and it is not in the address bar.
 How did you get it to show up in the address bar? Please tell me.

**Comment by SakethKanchi** [comment]
`Ctrl (Cmd) + 0` shortcut just resets the zoom level to 100. But I still get a zoom indicator in address bar.

**Comment by CutterKnife** [comment]
Yes, I understand. I am just mentioning another way.
To display the zoom level on the toolbar or status bar, follow the video below:
https://imgur.com/a/eR82uig

**Comment by SakethKanchi** [comment]
> Yes, I know. I am just mentioning another way. To display the zoom level on the toolbar or status bar, follow the video below: [imgur.com/a/eR82uig](https://imgur.com/a/eR82uig)

I was asking for something like this. The solution you mentioned has a permanent zoom level indicator outside the address bar. 
https://imgur.com/a/lZjZB1S

**Comment by da3dsoul1** [comment]
Yeah, I miss that indicator as well, using the workaround by CutterKnife rightnow

**Comment by breadbeforerice** [comment]
It certainly exists. My apologies. I hope things get back to normal.

**Comment by surapunoyousei** [comment]
Remove statusbar's zoom in & out button for show the button

**Comment by da3dsoul1** [comment]
> Remove statusbar's zoom in & out button for show the button

Thank you, it works! 👍

**Comment by SakethKanchi** [comment]
> Remove statusbar's zoom in & out button for show the button

Yeah this works. Thanks
