### ISSUE TITLE
[Bug]: I'm haveing a issue with cloudflare. I do not know if its this browser's fault but the issue is happaning to this one only

### ISSUE THREAD

**Issue by DarkKnight502** [Floorp-Projects/Floorp#861]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I do not know if its this browser's fault but the issue is happening to this one only, so when I tried to log into codepen.io or any other site that uses cloud flare it trys verifying me but stop and does it again in a loop. I cleared my cookies and it works for a bit but then when I click to a new page or something it needs to verify again, I tried a vpn also didn't work, I tried firefox and it worked but I need it on my main browser(floorp)

### Reproduction Steps

1. go to a site that uses cloudflare but in this case its codepen.io
2. then it would give you a page to verify thats you are a human(if not try logging in or interact with it)
3. then it would be stuck in a loop trying to verify
4.

### Expected Behavior

It should ether verify quickly and let you access the rest of the site or you would not need to verify at all.

### Actual Behavior

when verifying it gets looped trying to verify.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/136509883/a2a152fd-dcbb-45de-9d48-fe21938af079)
![image](https://github.com/Floorp-Projects/Floorp/assets/136509883/8d5c466d-f5cd-472c-9992-dc17885f7aae)
![image](https://github.com/Floorp-Projects/Floorp/assets/136509883/616fd08a-dd32-4901-9869-3e1119427d06)

### Browser Version

I think 11 (the newest one)

### Operating System

windows 10

**Comment by CutterKnife** [comment]
In most cases, this problem is caused by the UserAgent or user.js.

**Comment by creeper-0910** [comment]
Duplicate
