### ISSUE TITLE
[Bug]: Web Panel creation broken

### ISSUE THREAD

**Issue by imh1kiko** [Floorp-Projects/Floorp#863]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The latest update has broken web panel creation. "Pages to open" only shows "webpage" and none other. "Container" has nothing, even though containers are enabled. Existing creations work fine.
Disabling workspaces does not resolve it. Creating a new profile (which essentially makes a 'fresh start') does not resolve it. Console does not report anything.

### Reproduction Steps

1. Press + to the right
2. Click "pages to open"
3. None other than "webpage"
4. Click on "use the following container"
5. Nothing to select

### Expected Behavior

Allows creation adding addons and other functionality to the sidebar, as in prior versions.

### Actual Behavior

Does not allow creation of anything beyond webpage, and no specific container.

### Screenshots

![8W0N3kwEw3AGjGTRex41e9uBsjhwEn7L](https://github.com/Floorp-Projects/Floorp/assets/23316799/77406006-ff38-417b-a73d-9a91bf4a9069)

### Browser Version

11.9.0

### Operating System

Windows 10

### Additional Context

Possibly caused by an update. Worked fine prior to it.

**Comment by surapunoyousei** [comment]
Fixed
