### ISSUE TITLE
[Bug]: Vertical Tab Bar is not compatible with Combine Tab Bar and Toolbar

### ISSUE THREAD

**Issue by matti-kz** [Floorp-Projects/Floorp#864]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The options Vertical Tab Bar (experminetal) and Lepton UI Combine Tab Bar and Toolbar are not compatible and lead to weird UI glitch. This is quite confusing when I've enabled the option to combine first and then enable vertical tabs - it is not obvious what is the problem.

### Reproduction Steps

1. Lepton UI
2. Enable Vertical Tab Bar (experminetal)
3. Enable Combine Tab Bar and Toolbar

### Expected Behavior

Enable Vertical Tab Bar (experminetal) should disable Combine Tab Bar and Toolbar since those options don't make sense together anyway.

### Actual Behavior

It is possible to enable both and break the UI.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/8735263/fc700ea8-5a52-4ba4-80b8-0595fc9c4e2c)

### Browser Version

11.9.0 (64-bit)

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
Basically, the goal is for the vertical tab to work on its own.

If you are not happy with it, you can implement the feature yourself. I do not see the benefit of this feature and will not work on it.

close this issue as this is difficult to implement.

**Comment by surapunoyousei** [comment]
I'll do it when I feel like it.
