### ISSUE TITLE
[Bug] Can't Add Search Engine Which Already Exists After Removing

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [Floorp-Projects/Floorp#868]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

If you remove for an example an existing search engine on floorp then you can't add it back if the title of the search engine's homepage is having the exact same title as the existing removed search engine.

### Reproduction Steps

1. Remove any existing search engine (i.e. DuckDuckGo, SearXNG).
2. Visit the search engine homepage [**SearXNG**](https://baresearch.org) and [**searxng**](https://searx.si)
3. Try to add those search engine.

### Expected Behavior

You will see you won't get an option to add it from the search engine homepage url for [**SearXNG**](https://baresearch.org) but for [**searxng**](https://searx.si). Because, there is no existing search engine with name **searxng**.

### Actual Behavior

There should be an option to add both of the search engine with even with different tittle names. Or even for the existing search engine which is removed and had the same title.

### Screenshots

![SearXNG](https://github.com/Floorp-Projects/Floorp/assets/109698175/23019326-5977-4796-b608-618f57f174b3) ![SearXNG Add Action](https://github.com/Floorp-Projects/Floorp/assets/109698175/9cda554d-626c-4226-b2c4-0b87e3183f78)
![searxng](https://github.com/Floorp-Projects/Floorp/assets/109698175/fa8fbdd1-0a02-4ebe-8b25-ad8943ce0851) ![searxng Add Action](https://github.com/Floorp-Projects/Floorp/assets/109698175/94f7ca2d-114a-48df-9ad2-643c12f116cd)

### Browser Version

11.9.0

### Operating System

Arch Linux

**Comment by surapunoyousei** [comment]
I'll remove searXNG from Floorp

**Comment by BL4CKH47H4CK3R** [comment]
> I'll remove searXNG from Floorp

Removing won't solve your issues. I mean even if you remove google you can't add it back like that I have shown

**Comment by surapunoyousei** [comment]
So... SearSNG & Google are both built in search engine. it affect to that.

I will remove it

**Comment by BL4CKH47H4CK3R** [comment]
> So... SearSNG & Google are both built in search engine. it affect to that.
> 
> I will remove it

Cooldown Man!
Then please remove all of them and let user add what they need to add or try to follow [LibreWolf's](https://codeberg.org/librewolf/settings/src/branch/master/distribution/policies.json) way of doing it

**Comment by surapunoyousei** [comment]
policy discourages integration into Linux, so we adopt the former

**Comment by BL4CKH47H4CK3R** [comment]
> policy discourages integration into Linux, so we adopt the former

OK. I will build floorp with my modifications/patches applied.
Thank you very much BTW xDD.

**Comment by wiz64** [comment]
@BL4CKH47H4CK3R true,  google should be removed from this, need a little bit of help in compiling this, was planning to make some changes to Blink engine on chromium based browsers then i found this one.
also, how does Floorp deal with advanced fingerprinting techniques ?
