### ISSUE TITLE
[Bug]: Text in Iframes not following locale.

### ISSUE THREAD

**Issue by wulfalpha** [Floorp-Projects/Floorp#869]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

On some websites with a secure text entry field inside an Iframe, when text entry should be left to right it only accepts text left to right in an English locale.

### Reproduction Steps

1. Navigate to a site with secure text entry in an iframe in English locale (happens on windows and linuxs)
2. try to enter text (text is entered right to left.
3. Try to backspace, it backspaces out of order.

### Expected Behavior

when in a left to right locale all text entry fields should allow you to enter text in left to right format.

### Actual Behavior

Text is entered right to left.

### Screenshots

![Untitled video](https://github.com/Floorp-Projects/Floorp/assets/16473924/9d8c4b4d-d486-46d4-b972-a7d838017237)

### Browser Version

11.09

### Operating System

Windows

### Additional Context

The quality of the video went way down. I apologize. Also this is a very specific and odd issue so if you can't replicate the issue that's ok. Hopefully it gets fixed anyway and I can go back to using floorp. Keep up the good work!

**Comment by surapunoyousei** [comment]
Did you install userjs?

**Comment by surapunoyousei** [comment]
Honestly, Floorp does not manipulate the iflame implementation so I am convinced it is a night problem for the third party.

**Comment by wulfalpha** [comment]
I did not install any userjs. It's entirely possible a third party issue. Does the fact that I have the vertical tabs turned on? Is there anything in particular I should look for?

**Comment by creeper-0910** [comment]
Please test Firefox ESR 115 and the latest version of Firefox to see if the same problem occurs.

**Comment by wulfalpha** [comment]
Well I'll be a monkeys overweight uncle.
Looks like service now does not support mozilla firefox/ it's a rendering issue. cheers friends. I shall go back to using floorp as my default and just run that one site in chrome. Thanks for the help!

**Comment by wulfalpha** [comment]
have a good evening all!
