### ISSUE TITLE
Scrollable browser manager sidebar for 10.6.0?

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#87]
## Describe the bug
I updated floorp to 10.6.0 justnow and browser manager sidebar became scrollable.

## Expected behavior
browser manager sidebar can not scrollable.

## Screenshots

![scrollable bms](https://user-images.githubusercontent.com/11323774/193433254-d7eb8beb-ddca-4180-bfd3-e5b0be2de659.jpg)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Floorp Version: 10.6.0

## Additional context
Nope

**Comment by surapunoyousei** [comment]
This looks like a Windows 10 specific issue.  At least I don't see that issue in Windows Insider Preview BETA builds.

 What happens if you change ```widget.non-native-theme.scrollbar.style``` to ``5`` in about:config?

![image](https://user-images.githubusercontent.com/73892113/193433328-ccc75c9a-8c24-4dbd-8c38-069e2e8c2191.png)

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/193433387-0df6f928-fe18-4c2a-8696-a195d1ef7c4e.png)

left side

**Comment by benzBrake** [comment]
> This looks like a Windows 10 specific issue. At least I don't see that issue in Windows Insider Preview BETA builds.
> 
> What happens if you change `widget.non-native-theme.scrollbar.style` to `5` in about:config?

change `widget.non-native-theme.scrollbar.style` to `5` in about:config and restart browser.

Nothing happen

![nothing_happen](https://user-images.githubusercontent.com/11323774/193433427-9dbfe714-163f-4490-b995-529a61464cda.png)

When I set it's value to 2, horizontal scrollbar disappear

![disappear](https://user-images.githubusercontent.com/11323774/193433502-8b12544b-e4ed-4b7a-96d5-633b8449590c.png)

**Comment by surapunoyousei** [comment]
I see. I don't have a Windows 10 environment so I can't fully grasp it, but it's clear that there is a problem with the icon's margin value or padding value.

 I would like to solve it by reducing the size a little.

 Set the target milestone to 10.6.1.

**Comment by benzBrake** [comment]
OK Currenty force browser manager sidebar to style to
```
overflow: hidden auto;
```

**Comment by surapunoyousei** [comment]
> OK 現在、ブラウザー マネージャーのサイドバーのスタイルを強制的に
> 
> ```
> overflow: hidden auto;
> ```

Is vertical scrolling fine?

**Comment by benzBrake** [comment]
https://user-images.githubusercontent.com/11323774/193433987-29f4b075-e6b9-49d5-bc49-7d080b1e0842.mp4

**Comment by surapunoyousei** [comment]
> Video_20221002092221.mp4

Thank you. Use this code to fix it. This issue will be closed once the push is complete
