### ISSUE TITLE
[Bug]: Vertical Tabs when hovered moves the site to the left

### ISSUE THREAD

**Issue by SVTA-OP** [Floorp-Projects/Floorp#872]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The webpage moves left on hover.

### Reproduction Steps

1. Ensure that the platform used is Linux-based. This issue isn't there on Windows.
2. Enable vertical tabs
3. Optimize for vertical tabs
4. Collapse vertical tabs
5. Hover the mouse on the tab bar.

### Expected Behavior

Expanding of the vertical tab bar without the webpage moving.

### Actual Behavior

The webpage moves left.  

### Screenshots

[Screencast from 2024-02-11 14-56-52.webm](https://github.com/Floorp-Projects/Floorp/assets/126323835/e9e1b839-9c3c-440c-809f-1b4d328a7b52)  
![image](https://github.com/Floorp-Projects/Floorp/assets/126323835/90e8bdb3-5310-4c98-8fa8-c14959ed4ef7)

### Browser Version

11.9.0 on flatpak

### Operating System

Fedora 39, GNOME 45 on wayland

**Comment by surapunoyousei** [comment]
This is a compatibility issue and there are no plans to fix it at this time.
 

This is because it does not interfere with the user experience to that extent.
