### ISSUE TITLE
[Bug]: Translation into Ukrainian does not work

### ISSUE THREAD

**Issue by BRamil1** [Floorp-Projects/Floorp#877]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Translation into Ukrainian does not work

### Reproduction Steps

1. Make Ukrainian the main language

### Expected Behavior

Working translation into Ukrainian

### Actual Behavior

I have no translation into Ukrainian when I set Ukrainian as the main language

### Screenshots

![Знімок екрана 2024-02-12 220944](https://github.com/Floorp-Projects/Floorp/assets/83756169/5e5d996b-d721-4658-a174-fb9fc8bec497)

### Browser Version

11.9.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
Floorp is not support UK language yet. Wait for addition.

**Comment by regularenthropy** [comment]
Floorp is already fully translated into Ukrainian, yet you need to wait for the main dev to include it inside Floorp.

**Comment by surapunoyousei** [comment]
OK Added

**Comment by BRamil1** [comment]
Thank you for explaining
