### ISSUE TITLE
[Bug]: Open in external browser no longer works

### ISSUE THREAD

**Issue by LMasterGame** [Floorp-Projects/Floorp#878]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Open in external browser doesn't work for Floorp 11.9.0, and at settings no longer shows a list of the available browsers to open externally.
This happens even with a clean installation, and it was working correctly on Floorp 11.8.2.

### Reproduction Steps

1. Enable Open in external browser from Settings > General > Open in external browser.
2. Update Floorp to 11.9.0.

### Expected Behavior

Right-clicking a tab then clicking on "Open in external browser" will open the tab in the browser you selected from settings.
And at Settings > General > Open in external browser, shows a list of the available browsers in the operative system if Open in external browser feature is enabled.

### Actual Behavior

At Settings > General > Open in external browser, no longer shows a list of available browsers, and tabs can't be opened externally.

### Screenshots

![bug](https://github.com/Floorp-Projects/Floorp/assets/46695618/4d02988e-150e-4526-9447-7ac6af74c6ed)
![correct](https://github.com/Floorp-Projects/Floorp/assets/46695618/5e06daeb-e58f-455b-9822-b0148b702518)

### Browser Version

11.9.0

### Operating System

Windows 10 22H2

**Comment by surapunoyousei** [comment]
Yeah. We know. Floorp 11.10.0 will fix it

**Comment by wpeckham** [comment]
Why is this closed.  Running 11.19.1 on Manjaro this is still (or again) a problem!
