### ISSUE TITLE
[Bug]: Browser is in Dutch and Korean mixed

### ISSUE THREAD

**Issue by PathosEthosLogos** [Floorp-Projects/Floorp#881]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

![image](https://github.com/Floorp-Projects/Floorp/assets/9344681/15f6cbd4-cd32-4cf5-a9c8-fbf4696be628)

### Reproduction Steps

1. Install Floorp on Windows 10
2. Open Floorp

### Expected Behavior

I expected full UK English, but it's neither

### Actual Behavior

It is a mix of both Korean and Dutch.

### Screenshots

Posted above

### Browser Version

11.9.0 64 bit

### Operating System

Windows 10

### Additional Context

First time install, completely new profile, etc.

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/f5dca20f-9754-43e3-bdca-daea784e8404)

Not reproducible
