### ISSUE TITLE
[Bug]: Address Bar Popup Overlay / Z Index issues with tabs

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Floorp-Projects/Floorp#889]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

There is an overlay / z index issue for some beta layouts.

### Reproduction Steps

Go into options and set "bottom"

![image](https://github.com/Floorp-Projects/Floorp/assets/1291364/65358e26-0f68-4b5c-8888-cc5d2f40c4bc)

### Expected Behavior

The tabs are BEHIND the address bar

### Actual Behavior

The tabs are INFRONT the address bar

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/1291364/71a1f4b8-07ba-4641-b5bd-4c0800b09eb6)

### Browser Version

MOST NEW

### Operating System

Windows 10

### Additional Context

This bug report is overly complicated and seems unnecessary, consuming valuable time. While I appreciate your perspective, I believe simplifying the process would be more beneficial for future reports.

**Comment by surapunoyousei** [comment]
OK. I send a patch for fix this issue.

**Comment by surapunoyousei** [comment]
Fixed
