### ISSUE TITLE
Floorp can't remember ui density setting

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#89]
## Describe the bug
After I change the ui density, Floorp can't remember it.

## To Reproduce
1.Customize the browser
2.Change the ui density to compact
3.Restart browser
4.You will find that ui density is reseted to default value

## Expected behavior
Browser would rememer the ui density setting

## Screenshots
https://user-images.githubusercontent.com/11323774/193437632-88a604e1-b699-46a1-b549-8f8065638414.mp4

## Desktop (please complete the following information):
 - OS: windows 10
 - Floorp Version: 10.6.0
 
## Additional context
Nope

**Comment by surapunoyousei** [comment]
Does the default Photon also have a problem?

**Comment by benzBrake** [comment]
I'm using  Proton UI
Photon UI doesn't have this problem

**Comment by surapunoyousei** [comment]
OK, I've almost made a prediction. I'll fix it

**Comment by benzBrake** [comment]
And I have to say, 
Set the density to compact via Photon UI
Change ui to Phroton
Customize the browser
Change the ui density to compact
Restart browser
After browser restart density is reset to compact

**Comment by surapunoyousei** [comment]
Fixed
