### ISSUE TITLE
[Bug]: PWA Navigation Bar remains present

### ISSUE THREAD

**Issue by Coragyps** [Floorp-Projects/Floorp#895]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When you enable "**Use Titlebar**" on _customize toolbar_ (to enable the native windows titlebars), the _navigation bar_ remains present even if "**Disable toolbars on Web Apps Window**" is enabled.

### Reproduction Steps

1. Enable titlebars on _Customize toolbar_
2. Enable the option: _Disable toolbars on Web Apps Window_.
3. Create a PWA

### Expected Behavior

From what I understand, the _toolbar_, _tabbar_ and _navigationbar_ would be hidden when utilizing such option

### Actual Behavior

Only the _toolbar_ and _tabbar_ get hidden.

### Screenshots

![desktop](https://github.com/Floorp-Projects/Floorp/assets/24980774/1dbdd497-4d2c-4266-9b1b-eb59b6e099b9)

### Browser Version

Version 11.9.0 (64-bit) | Firefox 115.7.0

### Operating System

Windows 11 23H2

### Additional Context

_I was told this may be an issue regarding PWAs_, so I had to open this thread. It cannot be replicated on default Firefox due to not having first-party WebApp support.
This could be an issue for users that only want the titlebar present.

**Comment by surapunoyousei** [comment]
Could you provide a video?

**Comment by Coragyps** [comment]
I apologize for not providing a video. It's a work machine so I can't install a screen capture program.
However, I tried to replicate this behavior in the latest update, and seems to have been fixed.
![version2](https://github.com/Floorp-Projects/Floorp/assets/24980774/8f93704e-ac3a-439f-8a48-2385d9782e57)

**Comment by surapunoyousei** [comment]
OK
