### ISSUE TITLE
[Bug]: Workspaces not syncing properly between windows.

### ISSUE THREAD

**Issue by Thrywyn** [Floorp-Projects/Floorp#896]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Workspaces are not synced between windows and can result in loss of tabs.

### Reproduction Steps

1. Open a new Floorp window (1)
2. Create a new workspace (A) and open a single tab in it.
3. Open a new window (2) of Floorp, and check the workspaces, the previous workspace does not appear.
4. Create a new workspace (B) in the second window (2), open a tab in it.
5. Now close the first window (1)
6. Close the second window (2)
7. Re-open Floorp, now the only workspaces shown are (B). The workspace A has been lost along with all the tabs inside it.

### Expected Behavior

I expect the workspaces to sync between windows. If i try to open a workspace that is already opened in another window, it should either focus that previously opened window, or open the same workspace and sync them as i open new tabs.
It could work something like vivaldi's workspaces where this shows in the second window:
![image](https://github.com/Floorp-Projects/Floorp/assets/24990129/be885960-4757-4c0a-a160-73f43c529912)

### Actual Behavior

The workspaces are not synced between the windows.

### Screenshots

Window 1
![image](https://github.com/Floorp-Projects/Floorp/assets/24990129/48917702-6a94-422e-9b36-85aebd917e3f)

Window 2
![image](https://github.com/Floorp-Projects/Floorp/assets/24990129/9c0781d3-da6a-4fc3-9dc3-039fa849b7e4)

### Browser Version

11.9.0

### Operating System

Windows 11

**Comment by CutterKnife** [comment]
maybe related: https://github.com/Floorp-Projects/Floorp/issues/768

**Comment by makorus** [comment]
Got the same issue here on macOS 14.4 with Floorp 11.10.5 x65.
