### ISSUE TITLE
Some things work randomly

### ISSUE THREAD

**Issue by kulitnov852** [Floorp-Projects/Floorp#897]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

**Workspace** 
1. Delete the last tab of a workspace brings the last tab of the previous workspace. 

2. Workspaces fade away by themselves

**WebPanel**
1. Website in a container. 

2. Manage widget of the web panel

### Reproduction Steps

   |

### Expected Behavior

**Workspace**
1. Deleting all workspace tabs should bring up a home page that cannot be deleted.

2. Workspace stability

**WebPanel**
1. We should be able to run a website in a container as in previous versions. It seems that the parameter/widget designed for this purpose cannot unfold 

2. Manage widget. It seems that the parameter/widget designed for this purpose cannot unfold 

### Actual Behavior

**Workspace**
1. Delete the last tab of a workspace brings the last tab of the previous workspace. 

2. Sometimes workspaces just fade away. I've changed my profile, it keeps happening.

**WebPanel**
1. Impossible
 
2. Impossible

### Screenshots

**WebPanel**
1. ![1](https://github.com/Floorp-Projects/Floorp/assets/148592961/e495f516-3e74-4ed7-bc41-eb4fa205c060)

2. ![2](https://github.com/Floorp-Projects/Floorp/assets/148592961/3e163fa0-c582-4267-99b3-4b067a8069c8)

### Browser Version

11.9.0

### Operating System

Linux, Debian 11

**Comment by surapunoyousei** [comment]
You should split this issue.

Workspaces stability issue  & Web Panel will fix.
