### ISSUE TITLE
[Bug]: Ignoring preinstalled extensions placed in /usr/lib/floorp-addons/distribution/extensions

### ISSUE THREAD

**Issue by Botspot** [Floorp-Projects/Floorp#898]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

A fresh launch of Firefox with no `~/.mozilla` folder present will install extensions listed in `/usr/lib/firefox/distribution/extensions`.
The amd64 deb release of floorp does not include the `/usr/lib/floorp/distribution/extensions` directory, but it does include this folder: `/usr/lib/floorp-addons/distribution/extensions`

It seems that adding .xpi files to this folder has no effect. Floorp ignores the directory.

HOWEVER, adding .xpi files to `/usr/lib/floorp/distribution/extensions` does work.

### Reproduction Steps

1. Add a file like `uBlock0@raymondhill.net.xpi` to `/usr/lib/floorp/distribution/extensions`

### Expected Behavior

The extension will be automatically installed on first launch.

### Actual Behavior

The extension is not installed, and there are no errors in the terminal.

### Screenshots

not necessary

### Browser Version

11.10.0

### Operating System

Raspberry Pi OS

### Additional Context

This is an easy fix. Just correct your `mkdir` commands in your linux-x64-deb.yml: https://github.com/Floorp-Projects/Floorp/blob/ESR115/.github/workflows/linux-x64-deb.yml#L51-L53

**Comment by surapunoyousei** [comment]
Could you send PR?

**Comment by Botspot** [comment]
Done. https://github.com/Floorp-Projects/Floorp/pull/899

**Comment by surapunoyousei** [comment]
Thank you

**Comment by surapunoyousei** [comment]
Merged. Thanks
