### ISSUE TITLE
[Bug]: Auto-update fails

### ISSUE THREAD

**Issue by georgeat8** [Floorp-Projects/Floorp#900]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Before moving to 11.10.0, the auto-update didn't show a new version, even if the latest one was released. Now, after manually upgrading using the installer, the update check shows "Failed to check for updates".

### Reproduction Steps

1. Help -> About Floorp
2. See update check

### Expected Behavior

Find the new released version when using the update check

### Actual Behavior

No new version is being shown

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/62032417/c0ad2ea5-e3f7-4f9e-9325-c09391bb4b34)

### Browser Version

11.10.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
Floorp 11.10.0 is not released for 11.9.0. 

The sentences will be fixed in 3hours
