### ISSUE TITLE
[Bug]: Workspaces not accessible after latest update

### ISSUE THREAD

**Issue by malleyeno** [Floorp-Projects/Floorp#902]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After the latest update, I cannot seem to use Workspaces on my default profile. I have tried it with other profiles and workspaces are accessible as a feature. However, the profile does not contain the workspaces I have already defined, nor the container definitions, and would require redoing setup to use. I am unsure about what changed that could have produced this, though after I closed the browser the last time the workspaces worked, the browser updated the next time I opened Floorp. Then after that, it seemed like workspaces did not work anymore.

Enabling/disabling workspaces in settings did not fix it. Nor did restarting with extensions and add-ons disabled. The tabs I defined are still available as Hidden Tabs, but they do not keep any container tab definitions from their original workspace.

I have provided reproduction steps on how to utilize workspaces. But I am not sure how exactly to reproduce this bug since I am unsure of the cause. The update could have been coincidental.

### Reproduction Steps

1. Enable workspaces.
2. Click the top-left workspaces button.
3. Attempt to utilize workspaces by creating or managing workspaces.

### Expected Behavior

Workspaces are able to be accessed, created, and managed.

### Actual Behavior

The workspace pop-up is blank, despite workspaces already being created. The manage workspaces button and create new workspaces button are unresponsive.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/47365670/fa621013-dc53-40d6-90d5-dd07c2fc9083)

### Browser Version

11.10.0 (64-bit)

### Operating System

Windows 10

**Comment by malleyeno** [comment]
Adding in more relevant screenshot:

- The workspaces button is no longer available on the context menu for tabs
![image](https://github.com/Floorp-Projects/Floorp/assets/47365670/a359bfcf-3353-47b9-a9a5-76ea2404a9b2)

- Workspaces are enabled in the settings window
![image](https://github.com/Floorp-Projects/Floorp/assets/47365670/222c3039-d05b-4921-9b80-43541d4bc1fc)

**Comment by malleyeno** [comment]
Also adding a screenshot of my about:config with a filter for "workspace" just in case it's relevant:
![image](https://github.com/Floorp-Projects/Floorp/assets/47365670/c76a7c5c-199d-4403-a683-853c61bdf0be)

**Comment by malleyeno** [comment]
I found a workaround that might help if anyone else is having this problem!
Note: this will not restore your old workspaces (unless you happen to have a copy of your old workspaces.json for your profile. In which case, goodie!) but this seemingly restores Workspace functionality.

It seems to me that my default profile had a Workspaces.json that was entirely blank, but functioning profiles did have text in their json files. So I figured I could just put in the text from one profile into the default one to restore functionality. This did work (though did not restore my workspaces, but I figure those are gone for good anyway given that the json was completely replaced with whitespace.)


Steps:
1. Create a new profile. Open it in a new browser to confirm that workspaces works for you in that profile.
2. Open the profile directory for your new profile **which has funcitoning workspaces.**
3. Navigate to Workspaces > workspaces.json
4. Copy the entirely of this new profile to clipboard.
5. Navigate the the profile directory of the profile with **the non-functioning workspaces.**
6. Navigate to Workspaces > workspaces.json
7. Paste the contents into your workspaces.json. You may need to remove a lot of whitespace like what was present in mine (unknown why this was present.)
8. Reload your browser, and test that the workspaces in the top left works now.

**Comment by surapunoyousei** [comment]
Hmmm odd.

**Comment by surapunoyousei** [comment]
I will Revert sone commit

**Comment by surapunoyousei** [comment]
Fixed

**Comment by KingDigweed** [comment]
This exact bug just happened to me. I'm running 11.14.1 on Windows 10. Thank you Malleyeno for the detailed report; if I had to type up my exact experience of the last 15-20 minutes trying to work out whats gone wrong, I couldn't have done it any better than yourself. Exact same issue.

**Comment by surapunoyousei** [comment]
The structure has changed compared to February, please provide the procedure for reproduction.

**Comment by KingDigweed** [comment]
Thanks for the quick reply! Unfortunately I simply found the browser in the faulty state, and created a new profile in order to get things working again. I wouldn't be sure of what triggered the bug, but if it occurs again I will return to this thread. Sorry I can't be of much help. Let me know if there is anything you would like me to test - I can always switch back to the broken profile...

**Comment by surapunoyousei** [comment]
I see thanks.
