### ISSUE TITLE
[Bug]: Vertical Tabs Fullscreen Graphical Issue

### ISSUE THREAD

**Issue by Xenotiic** [Floorp-Projects/Floorp#905]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I am using the vertical tabs, rather than the top tabs. Any time I go into full screen, be it a video player, image, or webpage, I can see the sidebar separator for the vertical tabs on the left, where I also have the vertical tabs located.

Separately, I do not know if this is a bug, but when I hover over that area, the tabs don't reveal themselves like how the top bar does when I hover over the top.

### Reproduction Steps

1. Set the tab style to vertical tabs
2. Press F11, or go into full screen on a video player
3. The sidebar separator should be visible, and will disappear when exiting full screen

### Expected Behavior

I believe this is supposed to be hidden until hovered over, like with the top bar, but it does not show. Also like the top bar, I think that the separator is supposed to be hidden as to not interrupt the fullscreen viewing area.

### Actual Behavior

When I go into full screen, the sidebar on the left is hidden, except for the separator. Also, I cannot seem to capture this, but my cursor goes into the horizontal drag state when I hover over the separator. When I try to click and drag it, nothing happens.

### Screenshots

Image 1: New Tab Page (the whole background is this salmon-red color)
![image](https://github.com/Floorp-Projects/Floorp/assets/83891987/b7a61ae4-f1dc-4d37-b9d7-803ffd458311)
Image 2: Crunchyroll
![image](https://github.com/Floorp-Projects/Floorp/assets/83891987/e3512f8d-e524-4b02-9832-0b09ddc2f5cf)
Image 3: Youtube (the video'ss border is all blue)
![image](https://github.com/Floorp-Projects/Floorp/assets/83891987/c8525f6f-29fc-4e41-88e3-3777f5881cd1)
In comparison, here is the same scene on the same Youtube video at the same time in Firefox 122.0.1
![image](https://github.com/Floorp-Projects/Floorp/assets/83891987/41ea7579-ec5a-4bbf-acdc-a13c3b40b3ab)

### Browser Version

11.8.0

### Operating System

Linux Mint 21.3 (Cinnamon 6.0.4 in x11)

### Additional Context

In Firefox, I have the Tree Style Tab add-on to emulate the vertical tab functionality in Floorp.

**Comment by surapunoyousei** [comment]
This is a specification issue.  Ignore it as it has almost no effect.
