### ISSUE TITLE
[Bug]: does not open

### ISSUE THREAD

**Issue by coccobellof5** [Floorp-Projects/Floorp#911]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I don't know what the problem is, but on my windows 10, floorp won't open.
I tried the portable version.
I tried the x64 version
I tried the x32 version

It doesn't work... in any way.
I also tried the beta version and some older versions, but it doesn't open.
I press on the executable and it doesn't even appear in the taskmanager.
I tried changing the compatibility by masquerading as windows vista/7/8, but nothing.

Maybe it takes some addiction in particular?

FireFox works fine.

### Reproduction Steps

Unfortunately I have nothing to list.
I install and open... but it doesn't work.

### Expected Behavior

I would expect the application to open, but nothing..

### Actual Behavior

There's no point in attaching screenshots, I wanted to make a video, but I think it's useless in this case too.
After installation I open the .exe but absolutely NOTHING happens.

### Screenshots

already said before, there's no point in attaching screenshots, also because there's no way to do them...

### Browser Version

v11.10.2

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
Closed as there is no way to resolve this issue.

**Comment by surapunoyousei** [comment]
I can't fix it because Firefox has no way to do that.

**Comment by coccobellof5** [comment]
> I can't fix it because Firefox has no way to do that.

Is it possible that there is no solution?
It seems I'm the only one who can't start Floorp.
Everyone manages to install the app and enjoy the browser.

Am I doing something wrong?
Is it necessary to have firefox installed?
Do you have any addictions in particular?
What are the demands of this app?

**Comment by coccobellof5** [comment]
> Floorp 10 had requirements, but now if you meet Windows 10 you are good to go.
> 
> I don't know of any particular reason.
> 
> But you can try cmd line option
> 
> ```
>  path/to/your/floorp/exe/file -no-remote -wait-for-browser -attach-console
> ```

![image](https://github.com/Floorp-Projects/Floorp/assets/83649516/ef00423d-6719-4de6-9649-9ebf862e1563)
I installed Windows 10 even though I don't fully meet the mini requirements, I have a 10 year old laptop.
But other browsers work, so I was wondering if it was Floorp that requested something in particular, it's suggested by many precisely because it's light and well optimized, so it's strange that it doesn't work on older machines, it's a contradiction.

When I try to open the application, nothing appears in the task manager. Like it's going to freeze right away or there's no way to start it.
It's strange...Usually if there is something wrong, an error appears or at least it appears in the task manager list.

![image](https://github.com/Floorp-Projects/Floorp/assets/83649516/1ecea6cb-ce03-4a4b-bff4-cbecf8f19a99)
This "core is broken!!!" error appears with the portable version. It is the only visible "anomaly".

**Comment by coccobellof5** [comment]
> Bene, qual è la tua CPU

![image](https://github.com/Floorp-Projects/Floorp/assets/83649516/8f5adad5-6eee-4789-816c-bbf114cdf306)

**Comment by surapunoyousei** [comment]
I see. It appears that the CPU does not meet the minimum requirements.

I have an idea, wait for the next release and you will be able to install the Windows 32 bit version.

**Comment by coccobellof5** [comment]
> I see. It appears that the CPU does not meet the minimum requirements.
> 
> I have an idea, wait for the next release and you will be able to install the Windows 32 bit version.

I don't know if it can be useful, but I already tried the 32bit version and it didn't work at the moment.


Do you have a timeline for the release of this new release?

Because I've been trying to find a solution on my own for two whole weeks and I'm dying to experiment with floorp. 😊

**Comment by surapunoyousei** [comment]
I will change the release to tomorrow.

**Comment by surapunoyousei** [comment]
wait for 11.10.3. it will fix this issue

**Comment by coccobellof5** [comment]
> wait for 11.10.3. it will fix this issue
Hi, but it hasn't been released yet?

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/actions/workflows/deployments.yml

We are delaying the release slightly because we are finding bugs when we try to release it.

**Comment by coccobellof5** [comment]
I think another system is needed to compile, looking at the history, it has been trying to compile for days but fails.
Furthermore I would add it is too slow, it takes so many hours.
How can you wait so long... it's frustrating 😅

**Comment by surapunoyousei** [comment]
It takes less than an hour on my machine.

**Comment by coccobellof5** [comment]
That anger!!!
again it doesn't work...
Now there is a small difference it appears in the taskmanager and then closes after 3 seconds.
I tried adding the parameters you suggested previously and it still doesn't work.

**Comment by surapunoyousei** [comment]
I have a feeling there is a problem with your system.

**Comment by coccobellof5** [comment]
> I have a feeling there is a problem with your system.
I repeat what I said last time.
If the system had problems, many applications would not work, especially the official Firefox. Right?
This is why from the beginning I asked if there were any very specific requests. Also of any bills.

Mine is windows ltsb.

**Comment by surapunoyousei** [comment]
I don't want to devote any more time to this, so let's end this. Wait for the official release and if that doesn't work either, give up.

It may not be compatible. This is because it works on many devices.

**Comment by coccobellof5** [comment]
I understand your situation and will look forward to the new release.

But remember, not everyone signs up to github to ask for help, not everyone is practical, many people don't work if it doesn't work and move on to something else, skipping floorp.
I'm sorry but if there is a problem of this type, I don't think anyone else will write about it here...

Anyway. Thank you for your availability, you are a serious person who cares about the community and I really appreciate this.

Thank you

**Comment by surapunoyousei** [comment]
Sorry I can't help you.

**Comment by coccobellof5** [comment]
So, for information.
I tried the new version 11.10.3, as you suggested.
Unfortunately it doesn't work yet.

Thanks anyway for your work.
Good luck. 😊

**Comment by surapunoyousei** [comment]
I wonder why.

**Comment by coccobellof5** [comment]
> I wonder why.

I do not know...
Unfortunately, since no error appears and I don't have a startup log, I can't verify and possibly tell you the problem.

A little advice for the future, create an executable that can only be started manually before running floorp, so as to generate a log if necessary. It can be useful for many and also for you, to make it faster.

Thanks for everything again, I wish you good work.
I swear not to write any further, I don't want to disturb.

**Comment by coccobellof5** [comment]
> > Mi chiedo perché.


I do not know...
Unfortunately, since no error appears and I don't have a boot log, I can't verify and possibly report the problem to you.

A little tip for the future, create an executable that can only be started manually before running floorp, in order to generate a log if necessary. It can be useful to many and also to you, to make support faster.

Thanks again for everything, I wish you good work.
I swear not to write anymore, I don't want to disturb.

**Comment by surapunoyousei** [comment]
Thanks for the advice.

I appreciate users who are not arrogant like you. Thank you so much. I also apologize for not being able to help you.

**Comment by Codling** [comment]
Hello,

I have the same issue with the latest version of Floorp (11.10.5 - 32 or 64-bit) on a freshly installed Windows 10. It just can't open.

The CPU is an Intel( Core 2 Duo CPU T5900 @ 2.20GHz.

**Comment by pingu6** [comment]
Hi, i have the same problem on Windows 10, my cpu is `AMD A8-3520M`
