### ISSUE TITLE
[Bug]: glitches on images and youtube videos 

### ISSUE THREAD

**Issue by brackhap** [Floorp-Projects/Floorp#913]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp can't display some images correctly, instead it show pixels. and sometimes there are glitches while watching youtube videos. even google sheets aren't displayed correctly. I haven't encountered these issues while using firefox or chrome or any other browser.

### Reproduction Steps

1. watch any video on youtube and move cursor over it,
2. try to edit any photo on canvas or send it on whatsapp web...

### Expected Behavior

display videos and images correctly

### Actual Behavior

images are pixelated or glitches

### Screenshots

![floorp issue 1](https://github.com/Floorp-Projects/Floorp/assets/66040880/a0ddce70-64c8-4f96-b790-8efcd6679e34)
![floorp issue 2](https://github.com/Floorp-Projects/Floorp/assets/66040880/47b7617d-3470-44d8-8169-7418227a8cba)
![floorp issue 3](https://github.com/Floorp-Projects/Floorp/assets/66040880/c28cc873-14a2-4c0d-9dda-02d1b0204d12)

### Browser Version

11.10.1

### Operating System

Windows

**Comment by surapunoyousei** [comment]
You should try this on Firefox "ESR"

**Comment by PasVegan** [comment]
I have freezes on youtube videos too !

**Comment by surapunoyousei** [comment]
Deplicate https://github.com/Floorp-Projects/Floorp/issues/655
