### ISSUE TITLE
[Bug]: Clicking very top of tab doesn't activate tab

### ISSUE THREAD

**Issue by r3dp0int** [Floorp-Projects/Floorp#916]
### Bug Summary

With the mouse pointer located at the very top edge of a tab, clicking does nothing, it appears to be dead space.
I've checked this behaviour in other browsers, and it is not universal.

### Reproduction Steps

1. Move mouse pointer to top edge of Floorp tab
2. Click, and notice that the tab does not become active.
3. Also notice that on this edge, the tab does not highlight

### Expected Behavior

Expected behaviour is for the tab to highlight at any point of the tab, and to be able to click and activate the tab, without needing to move the mouse down further into the tab.

### Actual Behavior

The mouse click on this top edge does nothing at all.

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/127828057/e59f553d-81ec-4df5-9d6e-a41b1f2ec177

### Browser Version

11.10.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
If use enable multirow-tab, It its normal
