### ISSUE TITLE
[Bug]: New sidebar functionality keeps extension manage page from opening after a related sidebar app is opened once

### ISSUE THREAD

**Issue by SemnoSao** [Floorp-Projects/Floorp#917]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Turned new functionality on for experimenting and found out that stylus manage style page can't be opened anymore after opening a stylized page on sidebar. I use a style on whatsapp, turning the functionality on and restarting floorp I can open whatsapp and still open stylus manage style page. Once I open the whatsapp on sidebar I cant open the stylus manage style page anymore. I understand it's a preview and still in active development I hope this can help maybe.

### Reproduction Steps

1. Enable the Extensions Content Scripts in Browser Manager Sidebar option
2. Restart Floorp
3. Open an stylus stilized app on sidebar
4. Go on the Stylus extension and click on the "manage" button

### Expected Behavior

Manage page should open on click

### Actual Behavior

No page opens after sidebar page opens

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/16153554/a370ade2-9564-4edb-b5e7-68cdb73d6b34

### Browser Version

11.10.2

### Operating System

BigLinux Based on Manjaro Linux

### Additional Context

Again I understand this is a feature in development and it is expected to have bugs. I hope this can help on the process. If more info is needed I'm more than glad to help further.

**Comment by surapunoyousei** [comment]
I am not stating that all features will work with this feature enabled.

I don't want the browser to respond to extensions, so if you don't like bugs, don't use this feature.
