### ISSUE TITLE
[Bug]: Elements disappear in alternative Mastodon frontend "Phanpy"

### ISSUE THREAD

**Issue by abominabledrh** [Floorp-Projects/Floorp#925]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

phanpy.social is alternative frontend for Mastodon, which offers multiple layouts. One of these is a "tab/menu bar" for "shortcuts" (which can be "local" timeline, notifications, search results for multiple hashtags, etc)

With shortcuts set to "tab/menu bar" the bar is autohidden (upwards)  after a number of scrolls, or if a post further down than the top one is fully opened. It doesn't then reappear when the post is closed, or if the timeline is scrolled back  up. The only way to get it to reappear is to refresh the page, or use  the menu options to go to another page (e.g. "local" or  "notifications"). This happens in I can't  reproduce it in a Chromium browser, the latest ESR release (115.8.0), or the latest FF release (non-ESR).

### Reproduction Steps

1. Login to an existing Mastodon account using phanpy.social
2. Switch shortcuts to display as "tab/menu bar"  using the "shortcuts / columns" menu.
3. Add shortcuts.
4. Scroll down a few posts, or open any post which isn't the top one of the home feed.
5. Tab bar has been "hidden" and does not unhide

### Expected Behavior

Tab/menu should not disappear. It should remian in place when scrolling and be overloaid by a post opening

### Actual Behavior

With shortcuts set to "tab/menu bar" the bar is autohidden (upwards)  after a number of scrolls, or if a post further down than the top one is fully opened. It doesn't then reappear when the post is closed, or if the timeline is scrolled back  up.

### Screenshots

![phanpy1](https://github.com/Floorp-Projects/Floorp/assets/70437624/075ef604-ad4c-48e7-8050-d3b5fd8cc590)

### Browser Version

11.10.2 (64 bit)

### Operating System

Windows 11 Pro 23H2

### Additional Context

Happy to supply any "console outputs" you want (as long as you can tell me how to get them!)

**Comment by surapunoyousei** [comment]
I will check it

**Comment by surapunoyousei** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/2c1c5b49-5ce4-4a02-b162-2c81751e811a)
If I'm not mistaken, this also seems to occur in the ESR version of Firefox

**Comment by abominabledrh** [comment]
I downloaded ESR last night on my personal machine to check, and I couldn't reproduce it. I'm at work at the moment but I'll check again later.

**Comment by abominabledrh** [comment]
Yep. My apologies. I see it now in ESR. Sorry for wasting your time. Feel free to close this.

**Comment by surapunoyousei** [comment]
OK
