### ISSUE TITLE
[Bug]: 0xc0000374 Exception popup

### ISSUE THREAD

**Issue by thohnb** [Floorp-Projects/Floorp#927]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

This is the first time i see 0xc0000374 occur on Floorp. 

### Reproduction Steps

1. Start Floorp
2. Using as daily
3. Suddently the error occur

### Expected Behavior

Normal

### Actual Behavior

Get 0xc0000374 error

### Screenshots

![ảnh](https://github.com/Floorp-Projects/Floorp/assets/125535323/194f9455-0272-4500-96bb-da57ebfb5ac4)

### Browser Version

11.10.2

### Operating System

Windows 10 64 bit

### Additional Context

Hmn this is the first time that i encounter this bug. It very rarely because it not happened again in 1 hour.

Also, when bug box popup, i forgot to take a screenshot. So i decide to take screenshot in Event Viewer !
I don't know if this bug will happened again in future. But for sure, i will report it to the dev to check it.

Thanks you

**Comment by creeper-0910** [comment]
The problem may be caused by corrupted Windows.
Try repairing Windows with the sfc or dism command.

**Comment by surapunoyousei** [comment]
I find some Microsoft form comment. This issue not affected y Floorp
