### ISSUE TITLE
[Bug]: You can't see your tabs on private windows with vertical tabs.

### ISSUE THREAD

**Issue by Axenide** [Floorp-Projects/Floorp#931]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using a private window, if you have enabled vertical tabs and have them collapsed, you can't see their icons due to a private icon hiding them. I don't know if it's intentional though.

### Reproduction Steps

1. Open browser
2. Set vertical collapsed tabs
3. Open private window
4. Enjoy

### Expected Behavior

Being able to see opened tabs.

### Actual Behavior

A private window icon is hiding all the tabs when collapsed.

### Screenshots

![imagen](https://github.com/Floorp-Projects/Floorp/assets/66109459/4ccb0697-a40e-4575-b52f-5099496e3a92)
![imagen](https://github.com/Floorp-Projects/Floorp/assets/66109459/0693e28d-360f-49ef-bee8-a138be2382c9)

### Browser Version

Mozilla Floorp 11.10.2

### Operating System

Arch Linux

**Comment by surapunoyousei** [comment]
You should uninstall theme. or use new profile.

**Comment by Axenide** [comment]
> You should uninstall theme. or use new profile.

It worked!
I have the exact same extensions and config on another computer (same OS and Floorp version) and I don't have this issue. I guess it was just a bug from my profile.
Thank you. :)
