### ISSUE TITLE
[Bug]:the "open in an external browser" option does not work

### ISSUE THREAD

**Issue by bepolymathe** [Floorp-Projects/Floorp#932]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I have tried several times to enable the "open in external browser" option in settings.  I am asked to restart the browser.  After opening, the option is still not active.

### Reproduction Steps

1. Enable option
 2. Restart the browser
 3. Return to options
 4. The option is still not active (greyed out)

### Expected Behavior

This option is usable, especially as long as playing videos with DRM is not possible.

### Actual Behavior

The option is disabled.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/29939805/bf1f5dab-8de3-4ccb-9751-4f2eba9f833f)

### Browser Version

11.10.2 (64 bits) - Flatpak

### Operating System

Linux (Fedora 39)

**Comment by TheChilledBuffalo** [comment]
Actually, this is a limitation with the Flatpak package. Flatpak runs applications in a sandbox and so this feature doesn't work.

**Comment by regularenthropy** [comment]
"Open in External Browser" doesn't work on flatpak.
