### ISSUE TITLE
[Bug]: Copying images not working properly.

### ISSUE THREAD

**Issue by Axenide** [Floorp-Projects/Floorp#933]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When trying to copy an image, most of the time it doesn't work. It has worked a couple of times but I would say that 95% of the time it doesn't, even after several attempts.

### Reproduction Steps

1. Find image
2. Right-click
3. Click "Copy image"
4. Doesn't copy it most of the time.

### Expected Behavior

Right-click copying image should copy the image to clipboard.

### Actual Behavior

It doesn't copy the image most of the time.

### Screenshots

-

### Browser Version

Mozilla Floorp 11.10.2

### Operating System

Arch Linux

**Comment by Axenide** [comment]
Sorry, I just installed Firefox ESR to test and it doesn't work either. My bad.

**Comment by surapunoyousei** [comment]
OK
