### ISSUE TITLE
[Bug]: opening new tabs switches to new tabs instantly

### ISSUE THREAD

**Issue by sdsucks** [Floorp-Projects/Floorp#935]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

opening new tabs switches to new tabs instantly
i'm using latest Daylight 20240222032634
Floorp stable works just fine and i think Daylight versions before 20240222032634 didn't have this behavior

### Reproduction Steps

mouse middle-click a link in a web page
or
right-click and select "open link in new tab"

### Expected Behavior

i should stay in the source tab

### Actual Behavior

new tab is immediately selected and focused

this is painful

### Screenshots

![new tab](https://github.com/Floorp-Projects/Floorp/assets/6938353/86dfcb98-f3cd-427b-b59b-7151e6278bfb)

### Browser Version

20240222032634

### Operating System

win10

**Comment by surapunoyousei** [comment]
fixed https://github.com/Floorp-Projects/Floorp/commit/f9878e8aa3c261e79191dc4c8e0999e818fab022
