### ISSUE TITLE
[Bug]: Workspaces and tabs dissapear after closing Floorp

### ISSUE THREAD

**Issue by MatfenV1** [Floorp-Projects/Floorp#936]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The problem is a bit like #779. When I close Floorp when a private window is open, the workspaces I had in Floorp are all gone if I re-open Floorp back when the private windows is still open.

### Reproduction Steps

1. Open Floorp and work as normally with my workspaces.
2. Open a new private window
3. Close the main Floorp window (private window still open)
4. Re-open Floorp, now all my previous opened tabs and workspaces are gone.
5. There are now 2 new Floorp workspaces that have replaced my previous workspaces, these new workspaces seem to be duplicates of each other (see the screenshot)

### Expected Behavior

I expected that when I re-opened Floorp all my previous tabs and workspaces were still existing.

### Actual Behavior

My previous tabs and workspaces are cleared when Floorp is re-opened when a private window is still open.

### Screenshots

![afbeelding](https://github.com/Floorp-Projects/Floorp/assets/95773389/48d8da84-2081-4100-bf16-889ffb6aced1)

### Browser Version

Version 11.10.2 (64-bits) | Firefox: 115.8.0

### Operating System

Windows 11 22H2

### Additional Context

The previous tabs and workspaces are always saved when Floorp is closed, only when I do the above steps it's all cleared.

**Comment by surapunoyousei** [comment]
This is the intended specification, since one workspace is assigned to each window.

I am not planning any changes in this regard as I am working on a specification that is compatible with Firefox.

Workspaces and windows can be restored from the History button in the menu panel.

Also, issues should be split into separate issues.

Both are fine. The latter will be resolved.
