### ISSUE TITLE
Add "tree-style-tab" attribute to main-window

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#94]
## Is your feature request related to a problem? Please describe.
I want to write customize css that hide horizontal tabsbar when Tree Style Tab is opened.

## Describe the solution you'd like
When Tree Style Tab open, main-window's attribue "tree-style-tab" would set to true, else set to false.

The effect can refer to the video

https://user-images.githubusercontent.com/11323774/193781733-eb65b668-8738-49ca-97b9-55cb512c73dc.mp4

**Comment by surapunoyousei** [comment]
I feel like it's possible inside the Browser Manager Sidebar.

**Comment by surapunoyousei** [comment]
Native vertical tabs will be implemented and will be closed
