### ISSUE TITLE
[Bug]: some extensions cannot be set to Don't allow run in private windows

### ISSUE THREAD

**Issue by LET33T37** [Floorp-Projects/Floorp#942]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Like uBlock Origin and Gesturefy are always be set to allow run in private windows and cannot be changed.

### Reproduction Steps

1. install uBlock Origin or Gesturefy no matter what u  choose about "Run in private Windows".
2. Open about:addons and they're all allowed.
3. set their "Run in private Windows" option to "Don't Allow".
4. Reopen about:addons, changes never be saved.

### Expected Behavior

They should be "Don't Allow"

### Actual Behavior

uBlock Origin and Gesturefy are always be set to allow run in private windows and cannot be changed.

### Screenshots

![Uploading logo_256_75.svg…]()

### Browser Version

11.10.2

### Operating System

win10 22H2

**Comment by surapunoyousei** [comment]
These extensions are now intentionally made to work.

This is because otherwise problems will occur.
