### ISSUE TITLE
[Bug]: Unable to add local searxng as search engine

### ISSUE THREAD

**Issue by CypherDragon** [Floorp-Projects/Floorp#944]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When attempting to add a local SearXNG instance to Floorp, instead of adding it to the search engine list, it throws the error:
"Floorp could not download the search plugin from: http://heimdall.local.test/opensearch.xml?method=POST&autocomplete=duckduckgo"

### Reproduction Steps

1. Install self-hosted instance of SearXNG (I am using a Docker container hosted on a RPi)
2. Install latest Floorp release
3. Browse to URL for local SearxNG instance
4. Right-click in URL bar
5. Click "Add searxng""
6. Error is thrown

### Expected Behavior

Local SearXNG added to search engine list; allowed to select SearXNG as default search engine

### Actual Behavior

Error is thrown

### Screenshots

![Floorp_searx_error](https://github.com/Floorp-Projects/Floorp/assets/45954806/745d2d54-2ce8-441f-bb30-12fdbc12e648)
![Floorp_searx_curl](https://github.com/Floorp-Projects/Floorp/assets/45954806/534857ce-c3fa-4ae9-839a-4d71ae79804c)
![Floorp_searx_added_in_esr](https://github.com/Floorp-Projects/Floorp/assets/45954806/8e34ec38-5349-42a0-9697-d5bea65db627)

### Browser Version

11.10.2

### Operating System

Arch Linux

### Additional Context

This is an issue that has happened with Firefox in the past, related to searx and other search engine options. Digging through old searches comes across this closed bug from searx:
https://github.com/searx/searx/issues/2042

Note that in the included screenshots, it _does_ appear to have the correct response to the opensearch.xml file, but Floorp doesn't appear to be parsing it correctly.

This issue also occurred in old versions of Firefox:
https://support.mozilla.org/en-US/questions/972425

However, the current Firefox ESR does allow my local searx instance to be added correctly, as shown in attached screenshots. My searx instance is not public, so I cannot provide it for testing, but I am able/willing to provide anything needed.

**Comment by surapunoyousei** [comment]
Fixed

**Comment by CypherDragon** [comment]
Bug still exists on v. 11.10.5

**Comment by surapunoyousei** [comment]
SearXNG search engine related codes have been removed from Floorp.

I will not address this further as it is a minor issue

**Comment by CypherDragon** [comment]
Seriously? I'll make sure to get this "answer" distributed to anyone that recommends this fork in the future. This is a trash answer, and I will be making sure no one I know uses this project going forward.

**Comment by surapunoyousei** [comment]
That's too rude.

Why don't you just write the code instead? I have not received any donation or anything from you.

Is there any benefit for me to work on this feature? Is it beneficial to many people?

I will prioritize things and only work on features that are necessary.

Ok?

**Comment by surapunoyousei** [comment]
As I have said many times, I do not get my revenue from browsers, so I can't solve all problems.

If this makes you angry, you are too arrogant.

I can't work on my browser all day. And it is unethical and disgusting to expose this issue and incite other users to reduce it.

I can't do what I can't do. Less than 1% of people use local search.

**Comment by CypherDragon** [comment]
This _is not_ a problem with any other Firefox fork, or mainline Firefox, or ESR. It works normally in every other fork _except Floorp,_ so it is something you have done to change the code. As I am not a programmer, I do not know what the changes are, I can only show you what I am seeing, what the errors are, and include good bug reports. If you need more info, tell me what you need and I can try and provide it.

There is someone that is being arrogant here, but it isn't me. Either way, I'm done trying to use your pet project, and as your replies have not been constructive and only accusatory, sincerely FUCK YOU.

**Comment by creeper-0910** [comment]
You are too heated.
There is nothing we can do except remove searxng from Floorp. This is because we have not made any other searxng related changes.
Thank you for your understanding and cooperation.
