### ISSUE TITLE
[Bug]: Bluescreen appeared after updating, browser unusable after restart

### ISSUE THREAD

**Issue by AutoShedTV** [Floorp-Projects/Floorp#948]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I checked the reddit and saw the post that problems couldn't be posted there, so now I'm here. My problem occurred after updating the browser, for a split second, it had worked but a blue screen occurred immediately after. After restarting the computer and launching the browser, the browser appears broken and none of the UI is functional. If I re-install the browser, I fear that I'll lose all of my bookmarks. How do I retrieve the bookmarks in this scenario?

### Reproduction Steps

1. Restart browser for update.
2. Blue screen appeared.
3. Upon restart and launching the browser, the browser became inoperable with nothing working.

### Expected Behavior

Behavior normally associated with a simple update.

### Actual Behavior

Completely inoperable

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/129382242/5b9ae9d1-309e-46e0-93e3-80c5a9affc41)

### Browser Version

11.10

### Operating System

Windows 11

**Comment by AutoShedTV** [comment]
> I don't think this is an issue on Floorp's side. Having a BSOD appear can obviously cause issues to any application. Especially because the BSOD appeared during an update, Floorp's files may have got corrupted. Your best bet is to try reinstalling the browser. And also try checking your system for errors or instabilities. BSODs are terrible isn't it?

Fair point. I don't notice anything wrong with my system yet aside from the BSOD, It's a relatively new lenovo leagion 5 pro. But importantly, is there a way to recover the bookmarks within the browser's files before I re-install?

**Comment by TheChilledBuffalo** [comment]
Hey @AutoShedTV , you should be fine from just uninstalling and reinstalling normally. You're profile files are stored at a different place and don't get deleted when uninstalling.

Also, quick tip that might help you solve your system error, try running an sfc scan and dism check in an admin command prompt. Google for detailed instructions. 😉

**Comment by TheChilledBuffalo** [comment]
If you want to make absolutely sure your profiles don't get deleted, make a backup of this folder: C:\Users\<Your Username>\AppData\Roaming\Floorp

**Comment by AutoShedTV** [comment]
Re-installing did the trick while preserving the bookmarks. Thanks again @TheChilledBuffalo . I'll run those scans tonight and see if there's anything up with my system.
