### ISSUE TITLE
[Bug]: Enabling extensions content scripts in browser manager sidebar stacks panels when toggling using keyboard shortcuts.

### ISSUE THREAD

**Issue by Axenide** [Floorp-Projects/Floorp#949]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When using a keyboard shortcut to open a panel, it doesn't toggle but stacks them as shown in the screenshot. It only happens when enabling extensions content scripts in browser manager sidebar.

### Reproduction Steps

1. Go to `about:preferences#bSB`
2. Enable content scripts in browser manager sidebar
3. Use a keyboard shortcut to open a panel

### Expected Behavior

Toggling and not stacking.

### Actual Behavior

Panels opening inside, creating new instances of themselves and stacking inside the sidebar.

### Screenshots

![imagen](https://github.com/Floorp-Projects/Floorp/assets/66109459/bec0f611-81bd-4938-aff9-30b67b9ec5f8)

### Browser Version

Mozilla Floorp 11.10.2

### Operating System

Arch Linux

**Comment by surapunoyousei** [comment]
fixed
