### ISSUE TITLE
Show wrong context menu when right click in BST organizer

### ISSUE THREAD

**Issue by benzBrake** [Floorp-Projects/Floorp#95]
## Describe the bug
Show wrong context menu when right click in BST organizer

## To Reproduce
1. Open organizer in BST
2. Right click manage
3. See super long menupopup

## Expected behavior
Don't open context menu.

## Screenshots

https://user-images.githubusercontent.com/11323774/193854526-f291bd95-cac9-4d2c-93e7-760db07c1e7c.mp4

## Desktop (please complete the following information):
 - OS: Windows 10
 - Floorp Version: 10.6.0

**Comment by surapunoyousei** [comment]
This is due to the management tool being aggressively displayed. The sync tab was also removed for the same reason.

**Comment by benzBrake** [comment]
It's easy to fix it. I have wrote an uc.js
```
// ==UserScript==
// @name            fixPlacesRightClick.uc.js
// @author          Ryan
// @version         0.0.1
// @compatibility   Firefox 78
// @include         chrome://browser/content/places/places.xhtml
// @homepageURL     https://github.com/benzBrake/FirefoxCustomize
// ==/UserScript==

(function () {
    if (window.parent === window) return;
    var fixPlacesRightClick = function () {
        var placesToolbox = document.querySelector('#placesToolbox');
        if (!placesToolbox) {
            return;
        }

        placesToolbox.setAttribute("contextmenu", "none");
    }

    new fixPlacesRightClick();
})()
```

**Comment by surapunoyousei** [comment]
i see. 

it'll be fixed

**Comment by surapunoyousei** [comment]
8354b3f5be2b22393ad4f9524eea1ab141f45131

Fixed !

**Comment by benzBrake** [comment]
this problem recur in 10.6.2

**Comment by surapunoyousei** [comment]
OPPS

It seems that there was a mistake when moving to the Floorp core method.

**Comment by surapunoyousei** [comment]
I'll fix it. I am very sorry
