### ISSUE TITLE
[Bug]: Double line on context menu when a word or text is selected.

### ISSUE THREAD

**Issue by fabcard** [Floorp-Projects/Floorp#952]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Hello. I'm a new Floorp user. It's not a big issue, just a double line on context menu when a text or word is selected.

### Reproduction Steps

1. Select a text on any webpage.
2. Right click to open the context menu.

### Expected Behavior

No double line on context menu.

### Actual Behavior

As said on "Reproduction Steps".

### Screenshots

Uploading simplescreenrecorder-2024-02-25_01.28.23.mp4…

### Browser Version

11.10.2 (64-bit)

### Operating System

Linux Mint

**Comment by fabcard** [comment]
https://github.com/Floorp-Projects/Floorp/assets/88634350/bc0c8ed5-c20d-4809-9bfc-49f1cc442961

**Comment by surapunoyousei** [comment]
Duplication.

**Comment by surapunoyousei** [comment]
But, TY for your report
