### ISSUE TITLE
Newly opened tabs can't be closed[Bug]: 

### ISSUE THREAD

**Issue by Xenonionite** [Floorp-Projects/Floorp#956]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When a new tab is made it can't be closed with the tiny x on the tab row, the plus button doesn't open a new tab also I cant select a tab unless my cursor is at the edge of the screen. I can only create a new tab with CTRL T

### Reproduction Steps

1.Press the + button that creates a tab
2.Try to close tab by clicking the tiny x
3.select a tab with a mouse cursor on the tab row 

### Expected Behavior

1. The tab should close
2. The tab should be selected
3. A new tab should open

### Actual Behavior

1.When the tiny x is pressed to close the tab nothing happens
2. When the tab is clicked it doesn't get opened
3. When the + button that opens a new tab is clicked nothing happens

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/111075401/d2654fc9-8b2b-46e2-ba1d-e414f4a1f95b

### Browser Version

11.10.4 (64-bit)

### Operating System

Windows 11 23H2

### Additional Context

The issues weren't there until I updated to the 11.10.4 update and these issues only seem to affect new tabs

**Comment by TheChilledBuffalo** [comment]
This occurs only when there is more than one Floorp window is open right? For now, you could try turning off Content Scripts in Browser Manager Sidebar through the settings. Its still in experimental phase and can cause issues.

**Comment by Xenonionite** [comment]
Nope I only have one window open

**Comment by surapunoyousei** [comment]
WTF

**Comment by Xenonionite** [comment]
The new update fixed the bug
