### ISSUE TITLE
[Bug]: Web App not work with Containers

### ISSUE THREAD

**Issue by ZgblKylin** [Floorp-Projects/Floorp#957]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When a website is configures `Always open this in a Container`, then click `Install this site as an app`, the app is failed to create and open. Instead, a new tab will be opened for the website.

### Reproduction Steps

1. Configures a website as `Always open this in a Container`
2. Click `Install this site as an app`

### Expected Behavior

Web app should be installed as usual. When web app window opens, the page will be opened in configured container.

### Actual Behavior

Web app failed to install. A new tab opened instead of app window.

### Screenshots

![图片](https://github.com/Floorp-Projects/Floorp/assets/13114351/2c6dff1c-7aa8-4b0b-8203-aea6d808480c)

![图片](https://github.com/Floorp-Projects/Floorp/assets/13114351/dbe0a68e-103f-40c9-b24b-c2bd922268b0)

### Browser Version

11.10.2

### Operating System

Windows 11(23H2 build 22631.3155)

### Additional Context

In addition, there should be a `extensions` button in web app's toolbar, so we can operate on those extensions witch have popup panel without keyboard shortcuts.

**Comment by surapunoyousei** [comment]
Please re-send with feature request.

**Comment by ZgblKylin** [comment]
> It appears that your version of Floorp is not up to date.

Retried in latest 11.10.4, same result

**Comment by surapunoyousei** [comment]
It appears that this extension was not created with PWA windows in mind.

This is a problem with the extension and cannot be resolved by Floorp. Unless you change the code of the extension, it is difficult.

Please give up so we can assign containers to PWAs.

**Comment by surapunoyousei** [comment]
This also occurs in normal pop-up windows, which Mozilla does not support.
https://github.com/Floorp-Projects/Floorp/assets/73892113/3598a9ab-1b7a-4473-bd1f-3a1eb3fe3bbe
