### ISSUE TITLE
[Bug]: Can't open new tabs when extensions are enabled in BMS

### ISSUE THREAD

**Issue by newmomizi** [Floorp-Projects/Floorp#958]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

新しいタブを開こうとした際(またはリンク先を新しいタブで開こうとした際)、どのウィンドウを操作しているかに関わらず対象のタブが最初のウィンドウで開かれてしまう。
「ブラウザーマネージャーサイドバーで拡張機能のコンテンツスクリプトを有効にする (実験的)」をオンにしている場合にのみ発生。

### Reproduction Steps

1. 「ブラウザーマネージャーサイドバーで拡張機能のコンテンツスクリプトを有効にする (実験的)」をオンにする。
2. 新しいウィンドウを開く。この際、元のウィンドウは残しておく。
3. 新しい方のウィンドウで新しいタブを開く(Ctrl+T)。

### Expected Behavior

新しい方のウィンドウに新しいタブが追加される。

### Actual Behavior

元のウィンドウに新しいタブが追加された。

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/114981625/ca1832f3-fa8a-4ad7-9314-f755e7382e9b

### Browser Version

11.10.4

### Operating System

Windows 11 22H2 / Windows 10 22H2

### Additional Context

Floorp 11.10.2では発生しなかった。

**Comment by surapunoyousei** [comment]
TY. It will fix at 11.10.5.
