### ISSUE TITLE
[Bug]: Shortcut to toggle Browser Manager Sidebar not working

### ISSUE THREAD

**Issue by lurkynerd** [Floorp-Projects/Floorp#959]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Shortcut to show bookmark manager doesn't work. 

### Reproduction Steps

1. Go to shortcuts and setup a shortcut to enable/disable browser bookmark manager
2. Restart browser
3. Shortcut doesn't toggle anything. Bookmark Manager stays either hidden or active. No toggling.

### Expected Behavior

Browser manager sidebar should be toggled to show/hide with shortcut. Instead nothing happens. 

### Actual Behavior

Shortcut should toggle (show/hide) the browser manager sidebar on and off. 

### Screenshots

![2024-02-26_10-36](https://github.com/Floorp-Projects/Floorp/assets/94551170/4795ded7-8b4a-4573-a8eb-4f289f6c64be)
![2024-02-26_10-35](https://github.com/Floorp-Projects/Floorp/assets/94551170/afbda200-fc66-43ad-a08b-87e09826e413)

### Browser Version

11.10.4

### Operating System

Tumbleweed

**Comment by surapunoyousei** [comment]
This shortcut key is expected to be used once the sidebar is activated

**Comment by lurkynerd** [comment]
Ok, I may change this to a feature request then. Can we make a way to show/hide the Browser Manager sidebar just like we can show/hide the normal sidebar? 

Before I forget: Thank you for your amazing work on Floorp!

**Comment by surapunoyousei** [comment]
The function is proceeding in the background.
