### ISSUE TITLE
[Bug]: The address bar is messed up when in full screen on MacOS.

### ISSUE THREAD

**Issue by Avendo07** [Floorp-Projects/Floorp#962]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

WIth the latest update, which added a draggable space to the browser. This cause the title bar to be squished to half height and is causing the address bar to be not visible.

### Reproduction Steps

1. Start the browser.
2. Set the setting for tab bar in design settings to - "Optimise browser for Vertical Tab Bar"
3. Make browser full screen.

### Expected Behavior

The address bar should be completely visible and accessible.

### Actual Behavior

The address bar gets cut in half and looks weird.

### Screenshots

Full Screen - <img width="1728" alt="Screenshot 2024-02-27 at 13 29 30" src="https://github.com/Floorp-Projects/Floorp/assets/43928724/9976208b-649d-4ec7-a654-1d984868ce7d">

Not Full Screen - 
<img width="1485" alt="Screenshot 2024-02-27 at 13 30 26" src="https://github.com/Floorp-Projects/Floorp/assets/43928724/67171464-0664-46c0-94e9-d74e44ca2962">

### Browser Version

11.10.5

### Operating System

MacOS Sonoma 14.3.1

### Additional Context

Running MacOS Sonoma on Apple Silicon Mac.

Side Note - Very thanks for all the efforts into the browser, liking it so far.

**Comment by SonnevilleJ** [comment]
Just had this happen on Floorp 12.2.0 after upgrading via Homebrew today. Running on MacOS Sequoia 15.7.

**Comment by UtsavAchar** [comment]
@SonnevilleJ same here, I had downloaded version 11 from brew earlier.Now right after it got auto updated to version 12 there's no address bar when i'm on full screen. I'm using Sonoma 14.7.5
