### ISSUE TITLE
[Bug]: padding on the top when using vertical tabs

### ISSUE THREAD

**Issue by Minnona** [Floorp-Projects/Floorp#964]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

After the latest update there's a padding or a box on top of the address bar, can't remove it.

### Reproduction Steps

1. Turn on vertical tabs
2. Suffer 

### Expected Behavior

No padding

### Actual Behavior

Yes padding!

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/23418072/4126d3a3-ffdc-4fec-83da-f9d468c05a66)

### Browser Version

11.10.5 (64-bit)

### Operating System

Windows 11

**Comment by CutterKnife** [comment]
Check for the same issue, including closed ones.

**Comment by Axenide** [comment]
Same here, maybe there is an option to disable it but I didn't find any.

**Comment by surapunoyousei** [comment]
Deplicate

**Comment by sr-tream** [comment]
> Deplicate

Can you post link please? May be existed workaround to disable this?

**Comment by surapunoyousei** [comment]
Drag space will be able to be disabled in the next update in 2 weeks

**Comment by JimFlasch** [comment]
How about disabling it now????????????

**Comment by JimFlasch** [comment]
Should have had an options to disable this right from the start!

**Comment by sr-tream** [comment]
> How about disabling it now????????????

Temporary I just revert commit what adds it in floorp-core

```diff
diff --git a/browser/base/content/browser-tabbar.js b/browser/base/content/browser-tabbar.js
index b16e3c2..1cccf1e 100644
--- a/browser/base/content/browser-tabbar.js
+++ b/browser/base/content/browser-tabbar.js
@@ -66,12 +66,8 @@ const tabbarDisplayStyleFunctions = {
             display: none !important;
           }
           #titlebar {
-            display: inherit;
             appearance: none !important;
-            padding-top: 10px;
-          }
-          :root[sizemode="fullscreen"] #titlebar[id] {
-            flex-basis: auto;
+            display: none !important;
           }
           #TabsToolbar #workspace-button[label] > .toolbarbutton-icon,
           #TabsToolbar #firefox-view-button[flex] > .toolbarbutton-icon {
diff --git a/browser/base/content/browser-verticaltabs.js b/browser/base/content/browser-verticaltabs.js
index e5bb9a5..843f71b 100644
--- a/browser/base/content/browser-verticaltabs.js
+++ b/browser/base/content/browser-verticaltabs.js
@@ -81,6 +81,8 @@ var gFloorpVerticalTabBar = {
     Services.prefs.setBoolPref("floorp.browser.tabs.verticaltab", true);
     Services.prefs.setIntPref("floorp.browser.tabbar.settings", 2);
 
+    document.getElementById("nav-bar-customization-target").style.paddingTop = "10px"
+
     // Move Tab Bar
     this.browserBox?.prepend(this.tabsToolbar || "");
 
@@ -187,6 +189,8 @@ var gFloorpVerticalTabBar = {
       "scrollbox",
     );
 
+    document.getElementById("nav-bar-customization-target").style.removeProperty("padding-top")
+
     // Observer
     if (this._widthObserver) {
       this._widthObserver.disconnect();
```

**Comment by JimFlasch** [comment]
What am I supposed to do with that code? (putting it in chrome.css didn't work.)

**Comment by sr-tream** [comment]
> What am I supposed to do with that code? (putting it in chrome.css didn't work.)

1. Clone the Floorp repo
2. Initialize all submodules
3. Apply this patch to floorp-core submodule
4. Build Floorp

**Comment by JimFlasch** [comment]
Yeah...  I'd prefer something easier.

**Comment by JimFlasch** [comment]
Oh, BTW - could you put up an English-language version of your website for those of us who don't know Japanese?

**Comment by JimFlasch** [comment]
And next time they make a change like this that they should know not everyone will want, they should include an option to disable it from the get-go!

**Comment by surapunoyousei** [comment]
```CSS
#titlebar[id] {
  display: none;
}
```

add this text to userchrome.css

**Comment by surapunoyousei** [comment]
Issue is locked to make my comment stand out
