### ISSUE TITLE
[Bug]: Can't set as default browser in Portable version

### ISSUE THREAD

**Issue by jp-man25** [Floorp-Projects/Floorp#967]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Portable Floorp doesn't appear as an option in the web browser section of Windows 10's "default apps". I don't have Floorp on my C drive, not sure if that matters. But I don't have much space there so...

### Reproduction Steps

1. Try to set portable version as default browser
2. It doesn't appear
3. Scream

### Expected Behavior

Floorp should appear as an option when I try to change my default browser.

### Actual Behavior

Tried to choose Floorp as a default browser in Windows 10's "default apps", but it doesn't appear as an option

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/93134243/c12939d6-618d-4d07-ac3b-a4d8d0756ace)
Only browsers that appear

### Browser Version

11.10.2 64bit - Firefox 115.8.0

### Operating System

Windows 10

**Comment by creeper-0910** [comment]
Floorp Portable is not designed to be registered as the default browser.
Sorry.

**Comment by jp-man25** [comment]
I was able to do it by using this program: https://github.com/SiL3NC3/PortableRegistrator
