### ISSUE TITLE
[Bug]: Bitwarden in side panel does not load

### ISSUE THREAD

**Issue by DasDunkel** [Floorp-Projects/Floorp#969]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When the Bitwarden extension is added to the browser manager sidebar and opened it does not load, simply displaying a flat color, refreshing the panel does not resolve the issue, however, pressing the "Home" button for some reason does fix the issue until the panel content is unloaded

### Reproduction Steps

1. Install bitwarden extension
2. Add extension to browser manager sidebar
3. Open and be greeted with a "blank" page
4. Press the "Home" button and watch it load
5. Right click icon and select "Unload this panel"
6. Watch the issue come right back

### Expected Behavior

The panel loads Bitwarden's extension in a side panel

### Actual Behavior

Nothing gets loaded in the side panel

### Screenshots

https://dunk.dev/vid/rZ5EAr7i29.mp4

### Browser Version

11.10.4

### Operating System

Arch linux  -  Kernel 6.7.6

### Additional Context

I would test with other extensions but Bitwarden is the only extension that shows when adding a new panel, not sure if that is another bug or just a misconfiguration on my end - I will check further

**Comment by creeper-0910** [comment]
Upload extension and browser toolbox logs if possible.
When uploading, please be careful not to include any personal information.

**Comment by creeper-0910** [comment]
I cannot reproduce the problem in my environment (using Windows and Ubuntu, showing up to the login page).

**Comment by surapunoyousei** [comment]
Please disable running extensions on sidebar. 

This issue will fixed at 11.11.0
