### ISSUE TITLE
[Bug]: titlebar partly visible at top of window

### ISSUE THREAD

**Issue by JimFlasch** [Floorp-Projects/Floorp#971]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

the titlebar is partly visible at t he top of the Floorp window above the urlbar, even when "optimize for vertical tabbar" is set to on.

### Reproduction Steps

open Floorp
set "optimize for vertical taskbar" to on
notice titlebar of Floorp window is partly visible at top of window above urlbar.

### Expected Behavior

nothing at top of window above the urlbar

### Actual Behavior

titlebar of Floorp window is partly visible at top of window above urlbar. 

### Screenshots

![Floorp](https://github.com/Floorp-Projects/Floorp/assets/26049376/510fe296-2bf9-4e4b-9d0e-0280dd90ec00)

### Browser Version

11.10.5

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
duplicate

**Comment by JimFlasch** [comment]
What do you mean, duplicate?? I'm the first to to report this bug! It was not  previously listed in the issues list - I know because I checked it myself.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/964

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp/issues/961

These issue are same

**Comment by menndouyukkuri** [comment]
It's inappropriate to write about #964 here, but since it's locked, I'll write about it. Acts such as rude behavior toward developers or posting requests that are unrelated to the content of the issue are nuisance behaviors, so please do not do them again.
