### ISSUE TITLE
[Bug]: Visual advance configuration does not get applied on Linux

### ISSUE THREAD

**Issue by Ian-Marcel** [Floorp-Projects/Floorp#974]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I'm using *Floorp flatpak version* and basically the browser does not applies the following command that is used in advanced configuration page[*about:config*]:
**widget.gtk.rounded-bottom-corners.enabled**;
This is a boolean command that make's all browser window's corners **rounded**, is a small change but it make's the desktop appearance much more concise ;
I'm not sure if this a bug or just conflicting configuration, but still this command should've be working.

### Reproduction Steps

1. Open Floorp;
![step 1](https://github.com/Floorp-Projects/Floorp/assets/96081694/e7fafad0-78ee-48a8-a428-43b39b0b1db9)

2. search *about:config* in search bar;
![step 2](https://github.com/Floorp-Projects/Floorp/assets/96081694/83a38ab2-3abe-471c-a6a9-5f3bdc12a0a1)

3. Accept the risk prompt
![step 3](https://github.com/Floorp-Projects/Floorp/assets/96081694/03575796-6751-4bff-aa87-0cd0c38a71b4)

4. Paste **widget.gtk.rounded-bottom-corners.enabled** in page search bar and set a boolean *true*
![step 4 1](https://github.com/Floorp-Projects/Floorp/assets/96081694/ed2cf893-b851-455d-9165-3c060a0f738c)
![step 4 2](https://github.com/Floorp-Projects/Floorp/assets/96081694/59d5aa00-d852-4bcd-85ee-464901c0fff9)

### Expected Behavior

The expected behavior can be seen down bellow with 2 screenshots of Firefox ESR[also flatpak] with **widget.gtk.rounded-bottom-corners.enabled** set to false and then to true.
![widget gtk rounded-bottom-corners enabled=false](https://github.com/Floorp-Projects/Floorp/assets/96081694/52ce442f-9df9-418a-9742-c05d93d108ef)
![widget gtk rounded-bottom-corners enabled=true](https://github.com/Floorp-Projects/Floorp/assets/96081694/96c8ea2f-30cf-4c30-87ad-66a9739f5b05)
### Actual Behavior

What actually happened 🥲:
![Captura de tela de 2024-03-02 14-14-14](https://github.com/Floorp-Projects/Floorp/assets/96081694/e5129ce7-5de4-43cc-81cd-e6d668adc2a7)
### Browser Version

Floorp 11.10.5

### Operating System

Fedora Linux 39 | GNOME 45.4

### Additional Context

Obviously this isn't a serious issue, to me Floorp is what Firefox should've be, but still i'm hoping that somehow this can be fixed 🤗

**Comment by surapunoyousei** [comment]
Did you use tarball version of Floorp ?

**Comment by Ian-Marcel** [comment]
I don't know what you're meaning with ***tarball* version**, but i can say that **I'm using flatpak version of Floorp from the Flathub repository**, i currently have a userChrome.css file with customization, but i tested it both on Floorp vanilla and customized and had no difference, same with Firefox, with and without userChrome the rounded corners are simply working.

**Comment by Ian-Marcel** [comment]
> Did you use tarball version of Floorp ?

I don't know what you're meaning with ***tarball* version**, but i can say that **I'm using flatpak version of Floorp from the Flathub repository**, i currently have a userChrome.css file with customization, but i tested it both on Floorp vanilla and customized and had no difference, same with Firefox, with and without userChrome the rounded corners are simply working.

**Comment by surapunoyousei** [comment]
Flatpak version of Floorp is limited. It running inside of sandbox. You should use tarball to fix this issue

**Comment by Ian-Marcel** [comment]
Oh, i get it, thanks for clear things out, honestly I'm not going to use a tarball(which I'm guessing that is the system wide[ .rpm, .deb] package ) version.

For me flatpak simplifies managing apps in many ways since it's a unified package that runs in any Linux distribution and blah blah blah, either way thank you.

I'll close this issue, but not without giving my opinion on *"I think the Floorp team should focus on flatpak version when developing for Linux, it simply works better"*.
 **:-D**
