### ISSUE TITLE
[Bug]: Context menu item name mismatch

### ISSUE THREAD

**Issue by yolobnb** [Floorp-Projects/Floorp#975]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

This is related to the vertical tab layout and the naming convention that should be expected vs what is present. It is not significant, but this can still be noted. Rather than rambling a paragraph, I will attach the screenshot(s), making it easier to understand.

### Reproduction Steps

1. Open the browser and have vertical tab layout enabled
2. Have multiple tabs open
3. Right-click on a tab and go to the "Close Multiple Tabs" menu item
4. Check the menu item(s) naming

### Expected Behavior

This should be how it looks, taken from the official Firefox browser. I have vertical tabs enabled using a custom method, as it is not native in the official version. Check the naming convention.

![1](https://github.com/Floorp-Projects/Floorp/assets/98680372/e4e2b775-2b40-484e-9061-d75b674e45ec)

### Actual Behavior

The actual behavior or naming in Floorp is as below, which is quite confusing as it is not horizontal but vertical.

### Screenshots

![Screenshot_20240303_012434](https://github.com/Floorp-Projects/Floorp/assets/98680372/f262a34d-ca98-46f7-9925-66cb62468171)

### Browser Version

Version 11.10.5 (64-bit) | Firefox: 115.8.0

### Operating System

Arch Linux Rolling

### Additional Context

As mentioned, this is not significant in its fundamental nature but can still add to the polish that Floorp is aiming towards. I am reporting it here to be noticed and considered if and when possible.

**Comment by CutterKnife** [comment]
I believe that was changed by an update to Firefox. I could see the same string in Firefox ESR.

**Comment by surapunoyousei** [comment]
I'll try to fix this issue

**Comment by yolobnb** [comment]
> I'll try to fix this issue

Sounds good.

**Comment by surapunoyousei** [comment]
Fixed
