### ISSUE TITLE
[Bug]: Discord doesn't recognize mobile user agent in side bar

### ISSUE THREAD

**Issue by StratusFearMe21** [Floorp-Projects/Floorp#984]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When launching Discord through the sidebar with mobile user agent turned on, it does not load a mobile friendly interface (note that launching Discord via the developer tools responsive UI does work)

### Reproduction Steps

1. Make a new side panel app at https://discord.com/app
2. Enable mobile user agent
3. Sign into Discord
4. Observe that it is showing the desktop UI

### Expected Behavior

Discord shows the mobile friendly version of the site in the side bar

### Actual Behavior

It shows the desktop version of the site instead.

### Screenshots

![20240306_01h28m40s_grim](https://github.com/Floorp-Projects/Floorp/assets/57533634/d59a0f7c-8a23-40bc-8d27-b689e6fcad58)
![20240306_01h29m09s_grim](https://github.com/Floorp-Projects/Floorp/assets/57533634/b7bf9be3-07c2-4fd8-bd62-a14182df56c9)

### Browser Version

11.10.5

### Operating System

Artix Linux

### Additional Context

I know that floorp *is* sending a mobile user agent because my mom's website https://scrappapercircus.com does work in the sidebar and switches to the mobile view properly. The problem seems to be that the mobile user agent that you guys are using is one that Discord doesn't recognize

**Comment by CutterKnife** [comment]
I don't think Discord for Web was designed for mobile design. Try opening it on your phone to test it out.

**Comment by surapunoyousei** [comment]
Discord doesnt have mobile version website
