### ISSUE TITLE
[Bug]: Floorp fails to set the correct text encoding for pages with mixed text encoding.

### ISSUE THREAD

**Issue by nightson** [Floorp-Projects/Floorp#985]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp fails to set the correct text encoding for pages with mixed text encoding.

### Reproduction Steps

1.Visit https://web.archive.org/web/19980114053027/http://www.ponycanyon.co.jp/
2.Japanese text doesn't display correctly due to archive.org using UTF-8 while the archived page is in SHIFT-JIS.

### Expected Behavior

Japanese text shows correctly as in Tete009 build and Vivaldi.

### Actual Behavior

Japanese text doesn't display correctly.

### Screenshots

![图片](https://github.com/Floorp-Projects/Floorp/assets/843241/4a7695d2-d968-493e-863c-53e249be9597)
![图片](https://github.com/Floorp-Projects/Floorp/assets/843241/ea7dde1e-c06a-45b1-8a1f-e7ffdc24cebd)
![图片](https://github.com/Floorp-Projects/Floorp/assets/843241/832935e1-6105-4ea8-9621-a0c79a5b6b0b)

### Browser Version

Floorp 11.10.5

### Operating System

Windows 10

**Comment by surapunoyousei** [comment]
Have you tried Firefox ESR?  In addition to Vivaldi, you should try Firefox ESR.

**Comment by nightson** [comment]
> Have you tried Firefox ESR? In addition to Vivaldi, you should try Firefox ESR.

Oh sorry. I just found out that the issue was caused by the extension LocalCDN. It's pretty weird since I have it installed on Vivaldi as well.

Unrelated question: why is the repair text encoding button always greyed out? This seem to be an upstream problem though.

**Comment by nightson** [comment]
I figured it out. It seems that the Firefox version of LocalCDN supports more features than the Chromium based version. One of the feature called HTML filtering was the cause of the problem.

**Comment by nightson** [comment]
Sorry for the invalid bug report. I'm closing this.

**Comment by surapunoyousei** [comment]
Ok Dont worry. Thank you
