### ISSUE TITLE
[Bug]: No audio on Floorp Browser v11.10.5

### ISSUE THREAD

**Issue by DipayanRay** [Floorp-Projects/Floorp#986]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

No audio on Floorp Browser v11.10.5 running on Fedora 39 x86_64

### Reproduction Steps

1. Open the browser and play video on youtube.com  no sound plays
2. Open online speaker test on Floorp and no sound plays

### Expected Behavior

Performed clean install and the issue still exists used both flatpack and tar.bz2 ([source](https://github.com/Floorp-Projects/Floorp/releases/tag/v11.10.5)). Issue exists on both.

### Actual Behavior

No Audio

### Screenshots

None

### Browser Version

11.10.5

### Operating System

Fedora 39 x86_64

### Additional Context

Audio works fine on same and separate Windows 10 system.

**Comment by surapunoyousei** [comment]
It is not Floorp's issue, You should send this issue to Bugzilla
