### ISSUE TITLE
[Bug]: can't access course

### ISSUE THREAD

**Issue by ksso83** [Floorp-Projects/Floorp#988]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The free course at this page: https://sena.territorio.la/cms/index.php

can't be accessed because page freezes and slow down the pc (somehow)
the plaform is called territorium, sofiaplus and lms

### Reproduction Steps

1. Go to https://sena.territorio.la/cms/index.php
2. Register (is free)
3. Access a course
4. The page freezes

### Expected Behavior

Access the course

### Actual Behavior

Page freeze

### Screenshots

![Selección_003](https://github.com/Floorp-Projects/Floorp/assets/12177142/5cf595de-1d9b-4395-a783-272b8493d2ed)

### Browser Version

11.10.5

### Operating System

Operating System: Kubuntu 23.10 KDE Plasma Version: 5.27.8 KDE Frameworks Version: 5.110.0 Qt Version: 5.15.10 Kernel Version: 6.5.0-25-generic (64-bit) Graphics Platform: X11 Processors: 12 × AMD Ryzen 5 5500U with Radeon Graphics Memory: 3.1 GiB of RAM Graphics Processor: AMD Radeon Graphics Manufacturer: HP Product Name: HP Laptop 15-ef2xxx

**Comment by surapunoyousei** [comment]
このページは Firefox ESR では動作しません。 この問題を WebCompat に送信してください

**Comment by surapunoyousei** [comment]
This page is not working on Firefox ESR. Please send this issue to WebCompat
