### ISSUE TITLE
[Bug]: searchbar display bug 

### ISSUE THREAD

**Issue by pitroytech** [Floorp-Projects/Floorp#990]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

[Bug]: searchbar display bug when use Microsoft Fluent UI (deprecated) theme:

If I type some key word with 0 search result, icons of search engine will overlap the search bar

![Screenshot 2024-03-11 003254](https://github.com/Floorp-Projects/Floorp/assets/162911108/18fc4278-0787-42a0-93a4-ac571226084a)

### Reproduction Steps

Set Microsoft Fluent UI (deprecated) theme in Setting
type some keyword without zero search resault, eg sadfadsfdsfasrefsdfdsf

### Expected Behavior

Search engin icon not overlap the Line of search engine box

### Actual Behavior

If I type some key word with 0 search result, icons of search engine will overlap the search bar

### Screenshots

![Screenshot 2024-03-11 003254](https://github.com/Floorp-Projects/Floorp/assets/162911108/bac9c282-c510-4da1-9c26-f59658233cf7)

### Browser Version

11.10.5

### Operating System

Win 11x64

**Comment by surapunoyousei** [comment]
FluentUI is out of date. unsupported
