### ISSUE TITLE
[Bug]: Sidebar web panels don't react to additional mouse buttons (history/forward)

### ISSUE THREAD

**Issue by emvaized** [Floorp-Projects/Floorp#991]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Many mouses have additional side buttons for history navigation (forward/backward). When sidebar web panel is focused, additional mouse buttons actions are sent to the main browser view instead of currently focused web panel. 

### Reproduction Steps

1. Add any page as sidebar web panel
2. Open it, and navigate to any other URL inside the web panel
3. Press additional mouse button to go back

### Expected Behavior

Sidebar web panel navigates to the previous page, main browser view ignores the button press

### Actual Behavior

Sidebar web panel ignores the button, main browser view navigates backwards instead

### Screenshots

![img-2024-03-11-03-45-38](https://github.com/Floorp-Projects/Floorp/assets/37851576/95534dbc-5233-4a33-9fa4-2838e81960c8)

### Browser Version

11.10.5

### Operating System

Windows 11 23H2

**Comment by surapunoyousei** [comment]
Currently, Unsupported. Please send this request to disscussions

**Comment by emvaized** [comment]
@surapunoyousei 
Thanks for responding. I think this is rather a bug report than a feature request, because such problem doesn't occur with `Alt + arrow` history hotkeys, which navigate sidebar correctly. Is "Discussions" section meant to be used for bug reports as well?

**Comment by menndouyukkuri** [comment]
@emvaized I think you first need to make sure that your mouse side buttons are definitely typing `Alt + arrow`.

**Comment by surapunoyousei** [comment]
> @surapunoyousei Thanks for responding. I think this is rather a bug report than a feature request, because such problem doesn't occur with `Alt + arrow` history hotkeys, which navigate sidebar correctly. Is "Discussions" section meant to be used for bug reports as well?


On Firefox sidebar, There is no same feature. Floorp uses similar technology for make web panel.
