### ISSUE TITLE
[Bug]: Workspace prompt appears on new window

### ISSUE THREAD

**Issue by jab098** [Floorp-Projects/Floorp#993]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When a new window is created, if the workspace customisation option visible in the toolbar, the workspace prompt activates.

### Reproduction Steps

1. Customise the toolbar, right click in the toolbar and hit customise
2. Drag the workspace item anywhere into the toolbar and save
3. Open a new window, ctrl +n, or ctrl + shift + p for private window

### Expected Behavior

Expected behavior not to prompt the workspace selection

### Actual Behavior

Workspace automatically prompts a choice and interrupts the user if they are typing immediately in search box

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/17009279/1e58b8c0-fb0f-4c9a-a495-aa71cc733b8a)

### Browser Version

Version 11.10.5 (64-bit) | Firefox: 115.8.0

### Operating System

Windows 11

**Comment by surapunoyousei** [comment]
Is it reproducible on new profile?

**Comment by jab098** [comment]
> Is it reproducible on new profile?

Strangely, on a new profile, this problem doesn't exist.
Only on my existing one, which im not sure why.

**Comment by surapunoyousei** [comment]
It maybe your profile is broken... Not Floorp issue... Sorry... i cannot help you because, I cannot reproduce it.
