### ISSUE TITLE
[Bug]: Mica For Everyone support does not apply on Lepton

### ISSUE THREAD

**Issue by legofanlovessayori** [Floorp-Projects/Floorp#997]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Enabling Mica For Everyone support (needed for stuff like DWMBlurGlass to properly modifiy the titlebar) on **Windows 10 exclusively** while Lepton is applied does not function properly.

### Reproduction Steps

1. **Run Floorp under Windows 10**
2. Download and run the latest release of DWMBlurGlass [found here](https://github.com/Maplespe/DWMBlurGlass/releases/tag/2.0.1)
3. Enable Mica For Everyone support
4. Select Lepton as the theme

### Expected Behavior

Active titlebars should show up as intended

### Actual Behavior

1. Active Titlebars in the main Browser Window stay opaque in the users accent color
2. Caption Buttons are barely visible when the window is focused

### Screenshots

https://github.com/Floorp-Projects/Floorp/assets/94994630/6e5cf304-1d43-49c8-95f9-bbc45f1830fd

### Browser Version

11.10.5 (Stable)

### Operating System

Windows 10 22H2 (Build 19045.4046, Locale de-DE)

### Additional Context

This Bug is **Windows 10 exclusive**, in my testing at least DWMBlurGlass does apply correctly under Windows 11.

**Comment by surapunoyousei** [comment]
NOTE:

https://github.com/mozilla/gecko-dev/commit/7719dba185903ffa34fbcf64cf477ff2f68aa985

**Comment by legofanlovessayori** [comment]
then uhhh
either remove it out of the box or make a settings toggle cause idk what to remove

**Comment by surapunoyousei** [comment]
I consider it
